- lib/documentation/templates/template.js
- packages/main/test/playground/css/api.css
> docs(playground): Implement footer for sample pages

- lib/documentation/templates/template.js
- packages/main/test/playground/css/api.css
- packages/playground/webapp/controller/Main.controller.js
> docs(playground): Fix function declaration

- packages/main/src/themes/base/TextArea.less
Fixes: https://github.com/SAP/ui5-webcomponents/issues/29
> fix(ui5-textarea): focus outline with character counter

- packages/main/src/themes/base/Popup.less
Fixes https://github.com/SAP/ui5-webcomponents/issues/30
> fix(ui5-popover): bottom border radius

- packages/main/test/sap/ui/webcomponents/main/samples/Table.sample.html
> docs(playground): fix table sample

- packages/playground/webapp/index.html
> docs(playground): add link to video in youtube

- packages/main/src/themes/base/Panel.less
> refactor(ui5-panel): adapt panel to fiori 3 spec

- packages/main/src/themes/base/CheckBox.less
- packages/main/src/themes/sap_fiori_3/CheckBox.less
- packages/main/test/specs/CheckBox.spec.js
> refactor(ui5-checkbox): adapt to fiori 3 spec

- packages/main/test/sap/ui/webcomponents/main/samples/Input.sample.html
> docs(playground): fix input suggestions sample

- packages/main/src/CheckBox.js
- packages/main/src/CheckBoxTemplateContext.js
- packages/main/src/ListItem.hbs
- packages/main/src/RadioButton.js
- packages/main/src/RadioButtonTemplateContext.js
- packages/main/test/sap/ui/webcomponents/main/pages/List_test_page.html
- packages/main/test/specs/List.spec.js
Skip inner ui5-radiobutton and ui5-checkbox components inside list items upon TAB,
added in single and multi selection modes.
> refactor(ui5-list): improve keyboard handling on TAB

- packages/base/src/sap/ui/webcomponents/base/WebComponent.js
> refactor: remove redundant getMetadata method

- packages/base/src/sap/ui/webcomponents/base/Core.js
- packages/base/src/sap/ui/webcomponents/base/Theming.js
- packages/main/bundle.es5.js
- packages/main/bundle.esm.js
- packages/main/test/sap/ui/webcomponents/main/pages/DatePicker_fg.html
> move addCustomCSS away from Core

- packages/base/src/sap/ui/webcomponents/base/shims/jquery-shim.js
- packages/playground/webapp/www/samples/settings.js
> refactor: remove hungarian notation

- packages/playground/webapp/css/style.css
- packages/playground/webapp/view/Main.view.xml
> docs(playground): substitute combobox with select in filters

- README.md
> docs: Update link to Slack invite

- packages/main/test/sap/ui/webcomponents/main/samples/Card.sample.html
Setting a fixed width for two of card samples, based on VD feedback.
Fixing the first sample, as the code snippet has been part of the card itself by mistake.
> docs(playground): update card sample

- packages/playground/webapp/index.html
> docs(playground): add sample applications links

- packages/main/test/sap/ui/webcomponents/main/samples/ShellBar.sample.html
> docs(shellbar): fix typo in shellbar tag

- packages/playground/webapp/controller/Main.controller.js
- packages/playground/webapp/css/style.css
- packages/playground/webapp/model/models.js
- packages/playground/webapp/view/Main.view.xml
> docs(playground): add badge to new components

- packages/base/src/sap/ui/webcomponents/base/DOMEventHandler.js
- packages/base/src/sap/ui/webcomponents/base/WebComponent.js
- packages/base/src/sap/ui/webcomponents/base/delegate/ItemNavigation.js
- packages/base/src/sap/ui/webcomponents/base/events/PseudoEvents.js
- packages/main/src/DayPicker.js
- packages/main/src/Icon.js
- packages/main/src/Input.js
- packages/main/src/List.js
- packages/main/src/ListItem.js
- packages/main/src/ListItemBase.js
- packages/main/src/MonthPicker.js
- packages/main/src/Panel.hbs
- packages/main/src/Panel.js
- packages/main/src/RadioButton.js
- packages/main/src/Select.js
- packages/main/src/ShellBar.js
- packages/main/src/TabContainer.js
- packages/main/src/YearPicker.js
- packages/main/test/sap/ui/webcomponents/main/qunit/DayPicker.qunit.js
- packages/main/test/sap/ui/webcomponents/main/qunit/RadioButton.qunit.js
- PsuedoEvents is now a module that exports several reusable methods for identifying keydown
> refactor: pseudo events modularisation

- packages/base/src/sap/ui/webcomponents/base/Configuration.js
- packages/base/src/sap/ui/webcomponents/base/LocaleDataConfigurationProvider.js
- packages/base/src/sap/ui/webcomponents/base/dates/CalendarUtils.js
- packages/main/src/DayPicker.js
- CalendarUtils switched to es6 module
- CalendarUtils#getLocaleBasedCalendarType added
- Non calendar bundle size reduced ~ 6kb (angular webpack build)
> refactor(configuration): remove localeData as dependency

- packages/main/test/sap/ui/webcomponents/main/samples/Select.sample.html
- packages/main/test/sap/ui/webcomponents/main/samples/ShellBar.sample.html
- packages/main/test/sap/ui/webcomponents/main/samples/Switch.sample.html
- packages/main/test/sap/ui/webcomponents/main/samples/Timeline.sample.html
- packages/playground/webapp/index.html
- packages/playground/webapp/view/Main.view.xml
> docs(playground): change version

- packages/main/test/sap/ui/webcomponents/main/samples/Card.sample.html
- packages/main/test/sap/ui/webcomponents/main/samples/List.sample.html
> docs(playground): improve list samples

- packages/playground/lib/rewritebootstrap/index.js
- packages/playground/lib/static-index.js
- packages/playground/package.json
- packages/playground/webapp/Component.js
- packages/playground/webapp/index.html
- packages/playground/webapp/model/models.js
- packages/playground/webapp/playground/component/Name/index.ejs
- packages/playground/webapp/playground/index.html
- packages/playground/webapp/view/Main.view.xml
- yarn.lock
- switch ui5 router to location.history API
- generate static index.html files for all component routes
- generate sitemap
- add title and meta tag keywords
> improvement (playground): switch playground to real URL routes for SEO

- README.md
Playground URL was pointing to a 404-page
> fix(docs): Fixed Playground URL

- packages/main/src/DayPicker.hbs
- packages/main/src/DayPicker.js
- packages/main/src/themes/base/DayPicker.less
- packages/main/src/themes/sap_belize/DatePicker.less
- packages/main/src/themes/sap_belize_hcb/DayPicker.less
- packages/main/src/themes/sap_fiori_3/DayPicker.less
> refactor(ui5-datepicker): refactor the css

- packages/main/src/themes/base/Panel.less
Remove sap-desktop and sap-tablet dependant styles
> refactor(ui5-panel): remove obsolete styles

- packages/main/src/themes/base/Calendar.less
- packages/main/src/themes/sap_belize/Calendar.less
- packages/main/src/themes/sap_belize_hcb/Calendar.less
- packages/main/src/themes/sap_fiori_3/Calendar.less
> refactor(ui5-calendar): refactor the css

- packages/main/src/TextArea.hbs
- packages/main/src/TextAreaTemplateContext.js
- packages/main/src/themes/base/TextArea.less
- packages/main/src/themes/sap_belize_hcb/TextArea.less
- packages/main/test/sap/ui/webcomponents/main/qunit/TextArea.qunit.js
- a fix with styling for focus outline of show-exceeded-text Text Area is also included
> refactor(textarea): move styles to base

- packages/main/src/themes/base/MonthPicker.less
- packages/main/src/themes/sap_belize/MonthPicker.less
- packages/main/src/themes/sap_belize_hcb/MonthPicker.less
- packages/main/src/themes/sap_fiori_3/MonthPicker.less
> refactor(ui5-monthpicker): refactor the css

- packages/main/src/themes/base/YearPicker.less
- packages/main/src/themes/sap_belize/YearPicker.less
- packages/main/src/themes/sap_belize_hcb/YearPicker.less
- packages/main/src/themes/sap_fiori_3/YearPicker.less
> refactor(ui5-yearpicker): refactor the css

- packages/main/src/themes/base/DatePicker.less
- packages/main/src/themes/base/MonthPicker.less
- packages/main/src/themes/base/YearPicker.less
- packages/main/src/themes/sap_belize_hcb/DatePicker.less
CSS initial is not supported in IE.
> refactor: replace the CSS initial property

- packages/playground/package.json
- webcomponentsjs package should be deployed in the playground as well
copy the necessary files from main/dist
> improvement: copy webcomponentsjs files for deploy

- packages/playground/webapp/index.html
- packages/playground/webapp/model/models.js
- packages/playground/webapp/view/Main.view.xml
> chore: prepare playground for release

- packages/main/test/sap/ui/webcomponents/main/samples/Panel.sample.html
> docs(ui5-panel): improve sample readability in HCB

- packages/main/src/themes/base/ListItem.less
> fix(ui5-li): fix description text in compact mode

- packages/main/src/themes/base/Panel.less
Fixes: https://github.com/SAP/ui5-webcomponents/issues/212
> fix(ui5-panel): correct icon size on small screens

- packages/main/src/ListItem.hbs
- packages/main/src/themes/base/ListItem.less
> fix(ui5-li): fix delete list item button height

- packages/main/test/sap/ui/webcomponents/main/samples/Button.sample.html
Provide invisible labels for each Button, that is icon only, that would be read by the screen reader.
> docs: improve Button sample accessibility

- packages/playground/package.json
- yarn.lock
the playground starts correctly instead of showing a directory listing
changes in webcomponents and sample pages are reflected and shown on refresh
> playground: fix yarn start command

- packages/main/src/List.js
> fix(ui5-li): fix typo

- packages/main/src/themes/base/CheckBox.less
Remove background from touchable area and set it to the square box.
> fix(ui5-checkbox): remove background from the touchable area

- packages/main/src/RadioButtonTemplateContext.js
- packages/main/test/specs/RadioButton.spec.js
> fix(ui5-radiobutton): fix keyboard handling on TAB/SHIFT+TAB

- packages/base/src/Configuration.js
- packages/base/src/Locale.js
- packages/base/src/LocaleProvider.js
- packages/base/src/RTL.js
- packages/base/src/compatibility/ShadowDOM.js
- packages/base/src/util/detectNavigatorLanguage.js
- packages/base/src/util/getDesigntimePropertyAsArray.js
- packages/base/src/util/getEffectiveRTL.js
- RTL is now set from the configuration by priority. If no configuration
is defined for the rtl or language - navigator lanaguage is checked
> fix: checks navigator language for rtl enabling

- packages/base/src/CSS.js
- packages/base/src/Theming.js
- packages/base/src/WebComponent.js
- packages/base/src/compatibility/ShadowDOM.js
- packages/base/src/theming/ThemeBundle.js
- packages/main/test/sap/ui/webcomponents/main/pages/kitchen-scripts.js
- packages/main/test/sap/ui/webcomponents/main/qunit/Table.qunit.js
- fallback to style elements for unsupported browsers
https://github.com/WICG/construct-stylesheets/blob/gh-pages/explainer.md
> improvement: add constructable stylesheets support

- packages/main/src/CustomListItem.js
- packages/main/src/themes-next/CustomListItem.css
> refactor(ui5-li-custom): apply css vars

- packages/main/src/ToggleButton.js
- packages/main/src/themes-next/ToggleButton.css
- packages/main/src/themes-next/base/ToggleButton-parameters.css
- packages/main/src/themes-next/sap_belize/ToggleButton-parameters.css
- packages/main/src/themes-next/sap_belize_hcb/ToggleButton-parameters.css
- packages/main/src/themes-next/sap_fiori_3/ToggleButton-parameters.css
> refactor(ui5-togglebutton): apply css vars

- packages/main/src/themes-next/base/derived-colors.css
- packages/main/src/themes-next/sap_belize_hcb/derived-colors.css
- packages/main/src/themes-next/sap_fiori_3/derived-colors.css
> chore: extract derived colors

- packages/main/src/SwitchTemplateContext.js
- packages/main/src/themes-next/Switch.css
- packages/main/src/themes-next/base/Switch-parameters.css
- packages/main/src/themes-next/sap_belize_hcb/Switch-parameters.css
- packages/main/test/sap/ui/webcomponents/main/pages/Switch.html
Change the Width and Height of the Switch, when no label is set.
Change the colour of the "track" on hover in Belize_HCB
> refactor(ui5-switch): update component styling

- packages/main/src/ShellBar.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/297
> fix(ui5-shellbar): pass correct values for events details

- packages/main/test/sap/ui/webcomponents/main/samples/List.sample.html
Fixes: https://github.com/SAP/ui5-webcomponents/issues/307
> docs(ui5-list): remove references to old key attribute

- LICENSE.txt
Triggered by confusion we noticed in past Twitter comments
> docs: clarify that licenses of subcomponents do not apply to the project

- packages/main/lib/postcss-process-derived-colors/index.js
> chore: make derived colors build work on windows

- packages/main/src/Select.js
- packages/main/test/sap/ui/webcomponents/main/pages/Select.html
- packages/main/test/specs/Select.spec.js
- Pressing escape now reverts the selection before openinig the picker
- Focusing out the popover now triggers a change event (if selection is changed)
Fixes: https://github.com/SAP/ui5-webcomponents/issues/339
> fix(ui5-select): preselect first item if none is selected

- packages/main/src/TabContainer.js
> fix: update tab container documentation

- packages/main/src/DatePicker.js
- packages/main/test/sap/ui/webcomponents/main/pages/DatePicker_test_page.html
- packages/main/test/specs/DatePicker.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/380
>  fix(ui5-datepicker): fix js error thrown upon 'value' attr removal

- packages/playground/webapp/css/index.css
- packages/playground/webapp/index.html
adds a button on the landing page to a CodeSandbox sample page for easy editing with no setup.
fixes #272
> docs: add codesandbox link

- packages/main/test/sap/ui/webcomponents/main/samples/Popover.sample.html
Change things that were different in the example from the code that is being executed
- Fix some ids that were different
- Change the `open()` function to `openBy()`
Fixes #395
> docs(ui5-popover): Adjust Popover Component example

- packages/base/src/UI5Element.js
- make slot detection better
- rename some variables
- fix all code that still uses data-ui5-slot (monitored child properties)
> improvement: fix slots edge cases

- lib/documentation/templates/api-events-section.js
- packages/main/src/List.js
- packages/main/test/playground/css/api.css
- packages/main/test/sap/ui/webcomponents/main/pages/List.html
- packages/main/test/sap/ui/webcomponents/main/pages/List_test_page.html
- packages/main/test/sap/ui/webcomponents/main/samples/List.sample.html
- packages/main/test/specs/List.spec.js
Fixes #367
BREAKING CHANGE: the "selectionChange" event param "items" is  renamed to "selectedItems".
> feat(ui5-list): selectionChange event provides previousSelection items

- packages/base/src/RenderScheduler.js
> chore: filter out ui5 webcomponents in #whenFinished

- packages/playground/webapp/index.html
- packages/playground/webapp/view/Main.view.xml
* update version info from 0.10.0 -> 0.11.0
> doc: update version info

- packages/main/src/MultiComboBox.hbs
- packages/main/src/MultiComboBox.js
- packages/main/test/sap/ui/webcomponents/main/samples/MultiComboBox.sample.html
- suggestion module is no longer needed to run the component
- documentation for keyboard handling is added
- sample page responsiveness is improved
https://github.com/SAP/ui5-webcomponents/issues/428
> fix(ui5-multi-combobox): docs and API improvements

- packages/main/src/Table.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/451
>  fix(ui5-table): fix sticky column headers being overlapped by cells

- packages/base/src/TemplateContext.js
- packages/base/src/UI5Element.js
- packages/base/src/renderer/LitRenderer.js
- packages/main/lib/hbs2lit/src/litVisitor2.js
- packages/main/lib/hbs2ui5/RenderTemplates/LitRenderer.js
- packages/main/src/DatePicker.hbs
- packages/main/src/DatePicker.js
- packages/main/src/Select.hbs
- packages/main/src/ShellBar.js
- packages/main/src/Timeline.js
- packages/main/src/TimelineItem.hbs
- packages/main/src/themes/ShellBarInput.css
- packages/main/src/themes/TimelineItem.css
> Use lit maps for templates

- packages/main/src/themes/Select.css
FIXES: https://github.com/SAP/ui5-webcomponents/issues/460
> fix(ui5-select): fix component clickable area

- packages/main/src/Tab.js
- packages/main/src/TableCell.js
Suppress console warnings by fixing metadata
> refactor: remove redundant boolean value defaults

- CHANGELOG.md
- package.json
- packages/base/CHANGELOG.md
- packages/base/package.json
- packages/core/CHANGELOG.md
- packages/core/package.json
- packages/main/CHANGELOG.md
- packages/main/package.json
- packages/playground/CHANGELOG.md
- packages/playground/package.json
> chore(release): publish v0.11.1

- packages/main/src/themes/TabContainer.css
Correct the text colour of the selected tab in text only scenario.
>  fix(ui5-tabcontainer): fix the text colour of the selected tab

- packages/base/src/Renderer.js
- packages/base/src/UI5Element.js
- packages/base/src/UI5ElementMetadata.js
- packages/base/src/renderer/LitRenderer.js
- packages/main/src/Card.js
- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
- packages/main/src/MultiComboBox.hbs
- packages/main/src/MultiComboBox.js
- packages/main/src/Select.hbs
- packages/main/src/Select.js
- packages/main/src/ShellBar.js
- packages/main/src/Tab.js
- packages/main/src/TimelineItem.hbs
- packages/main/src/TimelineItem.js
- packages/main/src/Token.js
- packages/main/src/Tokenizer.js
- adds eventContext to the LitRenderer
- removes type: Function props from the metadata
- refactors all components that used to define functions in metadata
> refactor: call all event listeners with 'this' pointing to the component

- packages/main/src/Title.js
- packages/main/test/sap/ui/webcomponents/main/samples/Title.sample.html
Updated sample, based on the feedback of designers.
> docs(ui5-title): improve component sample and jsdoc

- packages/main/src/Button.hbs
- packages/main/src/Button.js
- packages/main/test/sap/ui/webcomponents/main/pages/Button.html
- packages/main/test/sap/ui/webcomponents/main/pages/Kitchen.html
- packages/main/test/sap/ui/webcomponents/main/pages/Kitchen.openui5.html
- packages/main/test/sap/ui/webcomponents/main/pages/Panel.html
- packages/main/test/sap/ui/webcomponents/main/samples/Button.sample.html
- packages/main/test/sap/ui/webcomponents/main/samples/ToggleButton.sample.html
BREAKING CHANGE: activeIcon property is removed
> refactor(ui5-button): remove activeIcon property

- README.md
> docs: fix typo in Readme

- packages/base/src/UI5Element.js
Changing the implementation of the check if given custom element was registered.
> refactor: check if custom element has been registered

- packages/main/src/StandardListItem.hbs
- packages/main/src/StandardListItem.js
- packages/main/src/themes/ListItem.css
- packages/main/test/sap/ui/webcomponents/main/pages/List.html
- packages/main/test/sap/ui/webcomponents/main/samples/List.sample.html
Added property "info" (together with infoState), displayed in the end of the list item.
> feat(ui5-li): add info and infoState properties

- packages/main/src/DatePicker.hbs
- packages/main/src/DatePicker.js
- packages/main/src/Dialog.hbs
- packages/main/src/Input.hbs
- packages/main/src/MultiComboBox.hbs
- packages/main/src/Popover.hbs
- packages/main/src/Popover.js
- packages/main/src/Popup.js
- packages/main/src/Select.hbs
- packages/main/src/ShellBar.hbs
- packages/main/src/TabContainer.hbs
- packages/main/test/sap/ui/webcomponents/main/pages/Popups.html
- packages/main/test/sap/ui/webcomponents/main/pages/ShellBar.html
- packages/main/test/sap/ui/webcomponents/main/samples/ShellBar.sample.html
BREAKING CHANGE: hideHeader property renamed to noHeader
> refactor(ui5-popover): hideHeader property renamed to noHeader

- packages/main/test/specs/Input.spec.js
https://github.com/SAP/ui5-webcomponents/issues/542
> chore: add tests for setting empty value to ui5-input

- docs/PublicModuleImports.md
- packages/main/bundle.esm.js
- packages/main/src/Button.js
- packages/main/src/CheckBox.js
- packages/main/src/DatePicker.js
- packages/main/src/Input.js
- packages/main/src/Option.js
- packages/main/src/RadioButton.js
- packages/main/src/Select.hbs
- packages/main/src/Select.js
- packages/main/src/TextArea.js
- packages/main/test/sap/ui/webcomponents/main/pages/Select.html
- packages/main/test/sap/ui/webcomponents/main/pages/form.html
BREAKING CHANGE: in change event the parameter is renamed from selectedItem to selectedOption
> feat: add form support for ui5-select

- packages/main/src/Title.hbs
> refactor(ui5-title): Remove unneeded accessibility role

- packages/main/config/postcss.components/postcss.config.js
- packages/main/src/MessageStrip.hbs
- packages/main/src/themes/InvisibleTextStyles.css
- packages/main/src/themes/MessageStrip.css
> chore: add common ACC invisible text styles

- packages/base/src/UI5Element.js
- packages/main/src/Badge.js
- packages/main/src/Input.js
- packages/main/src/List.js
- packages/main/src/Panel.js
- packages/main/src/Popup.js
- packages/main/src/ShellBar.js
- packages/main/src/Timeline.js
> refactor: remove support for data-ui5-slot

- docs/HowToUse.md
Also fixed line endings for the whole file
> docs: fix slots and events documentation after recent changes

- packages/main/src/DatePicker.hbs
- packages/main/src/Dialog.hbs
- packages/main/src/Input.hbs
- packages/main/src/MultiComboBox.hbs
- packages/main/src/Popover.hbs
- packages/main/src/Popover.js
- packages/main/src/Popup.hbs
- packages/main/src/Popup.js
- packages/main/src/Select.hbs
- packages/main/src/ShellBar.hbs
- packages/main/src/TabContainer.hbs
- packages/main/test/sap/ui/webcomponents/main/pages/DatePicker.html
- packages/main/test/sap/ui/webcomponents/main/pages/Popups.html
- packages/main/test/sap/ui/webcomponents/main/pages/ShellBar.html
- packages/main/test/sap/ui/webcomponents/main/samples/ShellBar.sample.html
BREAKING CHANGE: the property noHeader is removed, the presence of header is based on the values of "headerText" property and "header" slot
>  refactor(ui5-popover, ui5-dialog): remove noHeader property

- packages/main/src/BusyIndicator.hbs
- packages/main/src/BusyIndicator.js
- packages/main/src/themes/BusyIndicator.css
- in addition, document the slot ("default"), that the element accepts
> refactor(ui5-busyindicator): clean up styles

- packages/base/src/delegate/CustomResize.js
- packages/main/src/Table.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/568
> fix(ui5-table): call resize handler on initial rendering

- packages/main/src/Input.js
> chore(ui5-input): improve VoiceOver speech output

- packages/main/src/Dialog.hbs
- packages/main/src/Popover.hbs
> chore: improve accessibility of popups

- lib/documentation/templates/api-properties-section.js
- packages/main/src/Select.js
- packages/main/wdio.conf.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/457
> feat(ui5-select): adds readonly property selectedOption

- packages/main/src/DatePicker.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/85
> feat(ui5-datepicker): adds public getter dateValue

- packages/main/test/sap/ui/webcomponents/main/samples/Table.sample.html
> chore: update table sample for ie & edge

- packages/main/src/Tokenizer.hbs
- packages/main/src/Tokenizer.js
- packages/main/src/themes/MultiComboBox.css
- packages/main/src/themes/Tokenizer.css
- packages/main/src/themes/base/MultiComboBox-parameters.css
- packages/main/src/themes/sap_belize/MultiComboBox-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcb/MultiComboBox-parameters.css
- packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3/MultiComboBox-parameters.css
- packages/main/src/themes/sap_fiori_3/parameters-bundle.css
FIXES: https://github.com/SAP/ui5-webcomponents/issues/712
> fix(ui5-multi-combobox): overflow tokens correctly when not enough space

- packages/main/src/IconTemplate.lit.js
> chore(ui5-icon): aria-label added to the template

- packages/main/test/sap/ui/webcomponents/main/samples/DatePicker.sample.html
Setting initially "today" or "yesterday" is confusing as upon ENTER the shortcuts are not evaluated , because there is no value change.
> docs: update datepicker sample

- packages/main/src/themes/Button.css
- packages/main/test/sap/ui/webcomponents/main/pages/Button.html
FIXES: https://github.com/SAP/ui5-webcomponents/issues/795
> fix(ui5-button): align buttons with and without icons on same line

- packages/main/test/sap/ui/webcomponents/main/samples/Label.sample.html
Updated sample html file (doc) for Label to display the code used for the example implementation.
> docs: update Label sample

- packages/main/lib/i18n/defaults.js
write the export statement to a new line
> chore: update i18n-defaults.js generation

- packages/base/src/UI5Element.js
- packages/base/src/UI5ElementMetadata.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/833
> chore: add events info to UI5ElementMetadata

- packages/main/src/CustomListItem.js
Reverts SAP/ui5-webcomponents#831
> Revert "fix(ui5-li-custom): propagate spacebar input to input field"

- packages/main/src/ShellBar.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/811
> docs(ui5-shellbar): describe when title and subtitle hide

- packages/main/.eslintignore
- packages/main/package-scripts.js
- packages/main/package.json
- yarn.lock
extract scripts from package.json to nps (package-scripts.js)
> chore: refactor build scripts

- packages/main/src/themes/sap_fiori_3/base-parameters.css
- packages/main/src/themes/sap_fiori_3/global-derived-colors.js
- packages/main/src/themes/sap_fiori_3/global-parameters.css
- packages/main/test/sap/ui/webcomponents/main/pages/Kitchen.html
FIXES: https://github.com/SAP/ui5-webcomponents/issues/849
> refactor: update Fiori 3 theme parameters

- packages/main/src/Popover.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/885
> docs: fix popover documentation

- packages/main/src/themes/Input.css
- packages/main/test/pages/Input.html
FIXES: https://github.com/SAP/ui5-webcomponents/issues/890
> fix(ui5-input): fix input pushed downward

- packages/main/src/Label.hbs
- packages/main/src/Label.js
> refactor(ui5-label): subscribe event handlers within HBS template

- packages/main/src/RadioButton.hbs
- packages/main/src/RadioButton.js
> refactor(ui5-radiobutton): subscribe event handlers within HBS template

- packages/main/src/RadioButton.hbs
- packages/main/src/RadioButton.js
> Radio button

- packages/main/src/Label.hbs
- packages/main/src/Label.js
> refactor(ui5-Label): remove _eventHandlersByConvention from metadata

- packages/main/src/Button.js
- packages/main/src/ListItem.hbs
- packages/main/src/TabContainer.hbs
- packages/main/src/ToggleButton.js
- packages/main/test/pages/BusyIndicator.html
- packages/main/test/pages/Button.html
- packages/main/test/pages/CheckBox.html
- packages/main/test/pages/Dialog.html
- packages/main/test/pages/List.html
- packages/main/test/pages/Panel.html
- packages/main/test/pages/Select.html
- packages/main/test/pages/Table.html
- packages/main/test/pages/ToggleButton.html
- packages/main/test/pages/kitchen-scripts.js
- packages/main/test/pages/modules/Popups.js
- packages/main/test/samples/BusyIndicator.sample.html
- packages/main/test/samples/Dialog.sample.html
- packages/main/test/samples/Popover.sample.html
- packages/main/test/specs/Button.spec.js
- packages/main/test/specs/List.spec.js
- packages/main/test/specs/ToggleButton.spec.js
The 'press' event is for a long time private, the public 'click' should be used.
> refactor(ui5-button, ui5-togglebutton): stop firing 'press' event

- packages/main/src/Input.hbs
- packages/main/src/Input.js
Refactor UI5 Web Components' on* events for Input.
Part of #834
> refactor(ui5-input): subscribe event handlers within HBS template

- packages/main/src/Table.hbs
- packages/main/src/Table.js
Refactor UI5 Web Components' on* events for Table.
Part of #834
> refactor(ui5-table): subscribe event handlers within HBS template

- packages/main/src/Select.hbs
- packages/main/src/Select.js
Part of https://github.com/SAP/ui5-webcomponents/issues/834
> refactor(ui5-select): subscribe event handlers within HBS template

- packages/main/src/List.hbs
- packages/main/src/List.js
Part of https://github.com/SAP/ui5-webcomponents/issues/834
> refactor(ui5-list): subscribe event handlers within HBS template

- packages/main/src/DatePicker.hbs
- packages/main/src/DatePicker.js
Part of  https://github.com/SAP/ui5-webcomponents/issues/834
> refactor(ui5-datepicker): subscribe event handlers within HBS template

- packages/main/src/Input.hbs
- packages/main/src/Input.js
- packages/main/test/pages/Input.html
- packages/main/test/specs/Input.spec.js
> feat(ui5-input): introduce maxlength property

- packages/fiori/src/ProductSwitch.js
- packages/fiori/src/ProductSwitchItem.js
> docs: adjust ProductSwitch documentation

- packages/main/src/DatePicker.hbs
- packages/main/src/DatePicker.js
- packages/main/test/pages/DatePicker.html
- packages/main/test/pages/DatePicker_test_page.html
- packages/main/test/specs/DatePicker.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/980
> feat(ui5-datepicker) show value format as default placeholder

- docs/Public Module Imports.md
- packages/core/README.md
- packages/fiori/README.md
- packages/icons/README.md
- packages/main/README.md
- packages/main/src/MultiComboBox.js
- packages/main/src/Tokenizer.js
- packages/playground/README.md
- packages/tools/README.md
- Every package has a readme following the same pattern - with a little information about the specific package and a link to the main README.md
- No package duplicates the main README.md
- Additionally, fixed the build
> refactor: unify README.md files for packages

- packages/main/src/themes/Input.css
> fix(ui5-input): fix Input hover effect when valueState="None"

- packages/fiori/src/ShellBar.js
- packages/fiori/src/ShellBarItem.js
Based on this https://github.com/SAP/ui5-webcomponents/blob/bdfeb78d6f0e166e17bc8895f54aac179a7752a0/docs/Migration-guides.md#new-npm-package-ui5webcomponents-fiori
> fix(ui5-shellbar): Change path in imports for playground

- packages/main/src/themes/CheckBox.css
> fix(ui5-checkbox): fix wrapping of a long word

- packages/main/src/CustomListItem.js
- packages/main/src/GroupHeaderListItem.hbs
- packages/main/src/GroupHeaderListItem.js
- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
- packages/main/src/ListItemBase.js
- packages/main/src/StandardListItem.js
- packages/main/test/specs/Select.spec.js
Part of https://github.com/SAP/ui5-webcomponents/issues/834
This pull request contains multiple ListItem components, as they are connected with each other and therefore I wanted to do them together.
> refactor(ui5-li,ui5-li-custom,ui5-li-groupheader, ListItem.js, ListItemBase.js): subscribe event handlers within HBS template

- packages/main/src/RadioButton.hbs
- packages/main/src/RadioButton.js
- packages/main/src/themes/RadioButton.css
- packages/main/test/pages/RadioButton.html
- packages/main/test/samples/RadioButton.sample.html
- packages/main/test/specs/RadioButton.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/981
> feat(ui5-radiobutton): introduce wrap property

- packages/tools/components-package/rollup.js
Stop live reload on windows only (for performance reasons)
> chore: remove live reload

- packages/playground/build-scripts/pages-prepare.js
- don't use the layout, no navigation or header necessary
> chore: display test pages standalone

- packages/main/src/Popover.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1029
> fix(docs): display the ui5-popover API correctly

- packages/fiori/test/samples/ProductSwitch.sample.html
Make clear what the ui5-product-switch actually looks like as it`s hidden in the popover of the ui5-shellbar.
> docs(ui5-product-switch): improve sample

- packages/base/package-scripts.js
- packages/main/test/pages/Icon.html
- packages/main/test/pages/Panel.html
- packages/tools/components-package/rollup.js
- remove colors for wdio for the `base` package to make it the same as others
- remove all rollup functionality that no longer seems to be needed (warnings for old files, hacks for `ui5 serve` which is no longer used, etc...
- Fix other small findings
> chore: improve rollup file

- packages/tools/package.json
- yarn.lock
- webcomponents polyfill
- chromedriver
> chore(framework) update some dependencies

- packages/base/src/StaticArea.js
- packages/base/src/StaticAreaItem.js
> fix(framework): StaticArea and StaticAreaElement identify as UI5Element

- packages/main/src/Table.js
- packages/main/test/pages/Table.html
- packages/main/test/specs/Table.spec.js
New event "popinChange" has been introduced.
FIXES: #1106
> feat(ui5-table): introduce popinChange event

- packages/main/test/samples/DatePicker.sample.html
- Set the min-date and max-date correctly - the properties are minDate and maxDate, but the attributes are min-date and max-date.
- Shorten the range a bit.
> docs: fix DatePicker min/max sample

- packages/main/src/Table.js
- packages/main/src/TableRow.hbs
- packages/main/src/TableRow.js
- packages/main/test/pages/Table.html
- packages/main/test/specs/Table.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1018
> feat(ui5-table): provide rowClick event

- docs/Public Module Imports.md
- packages/main/src/MultiComboBox.hbs
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1115
> refactor(ui5-multi-combobox): add unique parts to tokens

- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/ShellBar.js
- packages/fiori/src/ShellBarItem.js
- packages/fiori/src/themes/ShellBar.css
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/samples/ShellBar.sample.html
- packages/fiori/test/specs/ShellBar.spec.js
> feat(ui5-shellbar-item): introduce count property

- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/ShellBar.js
- packages/fiori/src/themes/ShellBar.css
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/samples/ShellBar.sample.html
- packages/fiori/test/specs/ShellBar.spec.js
BREAKING CHANGE: profile property is removed in favour of profile slot
> feat(ui5-shellbar): add profile slot

- packages/base/src/UI5Element.js
The "_propertyChange" event is used only for the purpose of the "listenFor" metadata property, yet it is fired always. Now it is only fired when there are listeners.
> chore(framework): Do not fire _propertyChange unless there are listeners

- packages/base/test/pages/AllTestElements.html
- packages/tools/package.json
- yarn.lock
In addition, remove the left over test element that causes RenderScheduler to wait for 5 sec
> chore: update chromedriver to 80

- packages/main/src/Dialog.hbs
- packages/main/src/themes/Dialog.css
> chore(ui5-dialog): dialog should have min-width on desktop

- packages/base/src/types/ValueState.js
- packages/main/src/themes/Input.css
- packages/main/src/themes/TextArea.css
- packages/main/test/pages/Input.html
- packages/main/test/pages/TextArea.html
- packages/main/test/samples/Input.sample.html
- packages/main/test/samples/Select.sample.html
- packages/theme-base/src/themes/sap_belize/base-parameters-vars.less
- packages/theme-base/src/themes/sap_belize/base-parameters.less
- packages/theme-base/src/themes/sap_belize_hcb/base-parameters-vars.less
- packages/theme-base/src/themes/sap_belize_hcb/base-parameters.less
- packages/theme-base/src/themes/sap_belize_hcw/base-parameters-vars.less
- packages/theme-base/src/themes/sap_belize_hcw/base-parameters.less
- packages/theme-base/src/themes/sap_fiori_3/base-parameters-vars.less
- packages/theme-base/src/themes/sap_fiori_3/base-parameters.less
- packages/theme-base/src/themes/sap_fiori_3_dark/base-parameters-vars.less
- packages/theme-base/src/themes/sap_fiori_3_dark/base-parameters.less
Input, TextArea, Select, DatePicker, etc has now Information value state enabled
> feat: provide "Information" value state

- packages/main/src/Icon.js
> fix(ui5-icon): remove unneccessary aria-label attribute

- packages/main/src/Dialog.hbs
- packages/main/src/Dialog.js
- packages/main/src/Popup.hbs
> feat(ui5-dialog): improve accessibility

- packages/main/src/Toast.hbs
- packages/main/src/Toast.js
- packages/main/src/themes/Toast.css
- packages/main/test/pages/Toast.html
- packages/main/test/specs/Toast.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1292
> fix(ui5-toast): keep toast open when hovered

- packages/base/src/SVGIconRegistry.js
- packages/main/src/Icon.js
- packages/main/src/themes/Icon.css
- packages/main/test/pages/Button.html
Promise.reject causes zone js, used internally in Angular to throw exception.
So we replace Promise.reject with Promise.resolve 
👏
> fix(ui5-icon): remove promise rejection

- packages/main/src/themes/Toast.css
- packages/main/src/themes/base/Toast-parameters.css
- remove margin, it shifts the toast a little bit from the ideal center
- increase the vertical offset
> refactor(ui5-toast): update vertical offset

- packages/fiori/test/pages/ShellBar.html
- packages/main/src/InputPopover.hbs
- packages/main/src/features/InputSuggestions.js
- packages/main/test/pages/Input.html
Recently we received feedback that the "info" "description" and "image" are not displayed for the input suggestions. It turns out this is a regression after refactoring the component due to the static area integration.
> refactor(ui5-input): show suggestions description, info and image

- packages/main/src/themes/DayPicker.css
- packages/main/src/themes/MonthPicker.css
- packages/main/src/themes/YearPicker.css
- packages/main/src/themes/base/DayPicker-parameters.css
- packages/main/src/themes/base/MonthPicker-parameters.css
- packages/main/src/themes/base/YearPicker-parameters.css
- packages/main/src/themes/sap_belize_hcb/DayPicker-parameters.css
- packages/main/src/themes/sap_belize_hcb/MonthPicker-parameters.css
- packages/main/src/themes/sap_belize_hcb/YearPicker-parameters.css
- packages/main/src/themes/sap_belize_hcw/DayPicker-parameters.css
- packages/main/src/themes/sap_belize_hcw/MonthPicker-parameters.css
- packages/main/src/themes/sap_belize_hcw/YearPicker-parameters.css
- packages/main/src/themes/sap_fiori_3/DayPicker-parameters.css
- packages/main/src/themes/sap_fiori_3/MonthPicker-parameters.css
- packages/main/src/themes/sap_fiori_3/YearPicker-parameters.css
- packages/main/src/themes/sap_fiori_3_dark/DayPicker-parameters.css
- packages/main/src/themes/sap_fiori_3_dark/MonthPicker-parameters.css
- packages/main/src/themes/sap_fiori_3_dark/YearPicker-parameters.css
- packages/theme-base/src/themes/base/component-derived-colors-vars.less
- packages/theme-base/src/themes/base/component-derived-colors.less
- packages/theme-base/src/themes/sap_belize/base-parameters-vars.less
- packages/theme-base/src/themes/sap_belize/base-parameters.less
- packages/theme-base/src/themes/sap_belize_hcb/base-parameters-vars.less
- packages/theme-base/src/themes/sap_belize_hcb/base-parameters.less
- packages/theme-base/src/themes/sap_belize_hcw/base-parameters-vars.less
- packages/theme-base/src/themes/sap_belize_hcw/base-parameters.less
- packages/theme-base/src/themes/sap_fiori_3/base-parameters-vars.less
- packages/theme-base/src/themes/sap_fiori_3/base-parameters.less
- packages/theme-base/src/themes/sap_fiori_3_dark/base-parameters-vars.less
- packages/theme-base/src/themes/sap_fiori_3_dark/base-parameters.less
*The removed params are used in DayPicker, MonthPicker and YearPicker
> chore: replace derived css params

- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
- packages/main/src/types/ListItemType.js
- packages/main/test/pages/List.html
- packages/main/test/pages/List_test_page.html
- packages/main/test/specs/List.spec.js
Added new enumeration value in ListItemType. 
When ListItemType.Detail is used, list items show edit icon. When this icon is pressed, the coresponding list item fires "detailClick" event.
> feat(ListItemType): add Detail type

- packages/base/src/locale/nextFallbackLocale.js
- packages/base/src/locale/normalizeLocale.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1318
Prevent the possibility of infinite loop, if localeId is null, undefined, etc.:
```
const fetchI18nBundle = async packageName => {
const language = getLocale().getLanguage();
let localeId = normalizeLocale(language);
while (!bundlesForPackage[localeId]) {
localeId = nextFallbackLocale(localeId);
}
~~~
}
```
> fix(i18n): prevent infinite loop when fetching bundles

- packages/fiori/src/ShellBar.js
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/specs/ShellBar.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1325
> fix(ui5-shellbar): provide correct target ref when clicking overflowing item

- packages/main/src/Button.js
- packages/tools/components-package/wdio.js
- Add missing commands for WDIO to await, most notably `shadow$$`
- Delete old no longer used commands
- Remove button `eslint` warning
> chore(tools): Improve WDIO tests stability

- packages/main/src/themes/Avatar.css
- packages/main/test/pages/Avatar.html
- packages/main/test/samples/Avatar.sample.html
The styles considers the attribute name, not the property one.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1351
> fix(ui5-avatar): make styles attribute dependant

- packages/main/src/MultiComboBox.js
- packages/main/src/MultiComboBoxPopover.hbs
- packages/main/test/specs/MultiComboBox.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1359
> fix(ui5-mcb): open correct popover from show more text

- packages/main/src/Switch.js
> docs(Switch): document graphical as boolean

- packages/main/src/SegmentedButton.js
> fix(ui5-segmentedbutton): button can no longer be clicked when disabled

- packages/main/test/samples/Input.sample.html
Fixes  "Input with suggestion" not working.
Root cause: the recently added sample "Input with suggestions and ValueStateMessage" uses the same variable name for the ui5-input  -  "var oInput"
> chore: fix input sample

- packages/base/src/UI5Element.js
> fix(framework): allow components with static area content only

- packages/main/src/GroupHeaderListItem.hbs
- packages/main/src/GroupHeaderListItem.js
- packages/main/src/List.hbs
- packages/main/src/List.js
- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
- packages/main/src/StandardListItem.hbs
- packages/main/src/i18n/messagebundle.properties
- packages/main/src/themes/GroupHeaderListItem.css
- packages/main/src/themes/ListItem.css
- packages/main/test/specs/ComboBox.spec.js
> (ui5-list): implement accessibility spec

- packages/main/src/TimePicker.js
- packages/main/src/WheelSlider.js
- packages/main/src/themes/WheelSlider.css
- packages/main/test/specs/WheelSlider.spec.js
> feat(ui5-wheelslider): swipe feature implementation

- packages/main/src/Timeline.hbs
- packages/main/src/Timeline.js
- packages/main/src/TimelineItem.hbs
- packages/main/src/i18n/messagebundle.properties
> feat(ui5-timeline): implement acc spec

- packages/base/src/delegate/ScrollEnablement.js
> fix(scroll enablement): improve scrolling on android devices

- packages/main/src/TimePicker.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/1499
> fix(ui5-timepicker): periods apply fix

- packages/main/src/ResponsivePopover.hbs
- packages/main/src/ResponsivePopover.js
- packages/main/src/themes/ResponsivePopover.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/test/pages/ResponsivePopover.html
> fix(ui5-responsive-popover): implement default close button

- packages/main/src/themes/Link.css
- packages/theme-base/package.json
- packages/theme-base/src/themes/sap_belize/parameters-bundle.css
- packages/theme-base/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/theme-base/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/theme-base/src/themes/sap_fiori_3/parameters-bundle.css
- packages/theme-base/src/themes/sap_fiori_3_dark/parameters-bundle.css
- yarn.lock
- update to the latest `theming-base-content` version
- start using the standard parameter `--sapLink_SubtleColor`
> chore(theme-base): Update to the newest version of theming-base-content

- packages/main/src/themes/Popover.css
- packages/main/src/themes/base/Popover-parameters.css
- packages/main/src/themes/sap_belize_hcb/Popover-parameters.css
- packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/Popover-parameters.css
- packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1525
> fix(ui5-popover): show arrow border

- packages/main/src/themes/ResponsivePopover.css
> fix(ui5-responsive-popover): add minimum sizes

- packages/main/src/GroupHeaderListItem.hbs
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1542
> fix(ui5-li-groupheader): fix focus handling

- packages/fiori/src/themes/ProductSwitchItem.css
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1543
> fix(ui5-product-switch-item): fix active state

- packages/main/src/DateTimePicker.js
- packages/main/test/pages/DateTimePicker.html
- packages/main/test/specs/DateTimePicker.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1530
> fix(ui5-datetime-picker): fix AM/PM selection

- packages/main/src/SegmentedButton.js
> fix(ui5-segmentedbutton): import ui5-togglebutton by default

- packages/base/src/delegate/ScrollEnablement.js
> fix(scroll enablement): fix scrolling issue on scroll & mobile

- packages/main/src/ComboBox.hbs
- packages/main/src/ComboBox.js
- packages/main/src/ComboBoxPopover.hbs
- packages/main/src/i18n/messagebundle.properties
> feat(ui5-combobox): implement accessibility spec

- packages/main/src/ComboBox.hbs
- packages/main/src/ComboBox.js
accesibleName translation now works as expected.
> fix(ui5-combobox): translate accessibleName

- docs/CustomTheming.md
- docs/Public Module Imports.md
> docs: document custom theme integration

- docs/React-tutorial.md
> docs: correct end tag in React Tutorial

- packages/main/src/Select.js
> feat(ui5-select): implement angular two way data binding

- packages/main/src/FileUploader.hbs
- packages/main/src/FileUploader.js
- packages/main/src/i18n/messagebundle.properties
> feat(ui5-fileuploader): Implementing accessiblity specification

- packages/main/src/themes/DurationPickerPopover.css
- packages/main/src/themes/TimePickerPopover.css
After #1586 the style of some buttons should be reworked
> chore: adapt components to button fix

- packages/main/src/themes/TableColumn.css
- packages/playground/_sass/layout.scss
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1602
> fix(ui5-table-column): fix sticky column overlaps dialogs

- packages/main/src/BusyIndicator.hbs
- packages/main/src/BusyIndicator.js
- packages/main/test/pages/BusyIndicator.html
- packages/main/test/specs/BusyIndicator.spec.js
> fix(ui5-busyindicator): prevent keyboard events propagation to controls

- packages/main/test/pages/Kitchen.html
- packages/main/test/pages/kitchen-scripts.js
- packages/tools/lib/hbs2lit/src/compiler.js
> fix(framework): remove white spaces from hbs parser

- packages/main/src/SegmentedButton.js
> fix(ui5-segmentedbutton): fix rendering in ie

- README.md
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1629
> docs: fix dev guide info

- packages/main/src/themes/TableCell.css
> fix(uit-table-cell): fix popin of long texts

- packages/main/src/SegmentedButton.js
> fix(ui5-segmentedbutton): fix measuring when parent is not displayed

- packages/main/src/themes/Dialog.css
- packages/main/src/themes/Popup.css
- packages/main/test/pages/Dialog.html
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1662
> fix(ui5-dialog): restrict max height and width based on spec

- packages/main/src/Carousel.js
- packages/main/test/pages/Carousel.html
- packages/main/test/pages/CarouselLoadMore.html
- packages/main/test/specs/Carousel.spec.js
Fixes #1663
Fixes one more bug: After reaching the last page of non cyclic carousel, the navigate event was thrown. Now it is not
> feat(ui5-carousel): introduce loadMore event

- packages/main/src/BusyIndicator.js
closes: https://github.com/SAP/ui5-webcomponents/issues/1673
> docs: explain how to handle width issues with block elements

- packages/main/src/Popover.js
By design the popover should have a minimum 10 px offset from the window borders.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1656
> fix(ui5-popover): ensure offset from window borders

- packages/main/src/MessageStrip.hbs
- packages/main/src/themes/MessageStrip.css
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1739
> fix(ui5-messagestrip): add RTL support

- packages/main/src/DatePicker.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1740
> fix(ui5-datepicker): fix value state when min/max  set

- packages/main/src/RatingIndicator.js
- packages/main/test/samples/RatingIndicator.sample.html
Address few comments left: the since info, readonly JSFOC, no need of Promise all for single await, etc.
> chore(RatingIndicator): fix few comments from review

- packages/base/src/util/isValidPropertyName.js
- packages/main/src/Button.hbs
- packages/main/src/Button.js
- packages/main/test/pages/Button.html
- packages/main/test/specs/Button.spec.js
> fix(ui5-button): apply aria-expanded to inner button tag

- packages/main/src/Input.hbs
- packages/main/src/Input.js
- packages/main/test/pages/Input.html
- packages/main/test/specs/Input.spec.js
> feat(ui5-input): implement aria-label

- packages/main/src/TabInStrip.hbs
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1788
> fix(ui5-tabcontainer): fix id duplication

- packages/main/test/pages/MessagePage.html
This example illustrates how to implement the `Fiori Message Page` using the correct CSS Vars.
closes: https://github.com/SAP/ui5-webcomponents/issues/1805
> docs: how to create a Fiori 3 message page

- packages/main/src/themes/ToggleButton.css
> fix(ui5-togglebutton): vertically align icon in IE

- packages/main/src/themes/Button.css
> fix(ui5-button): vertically align icon in IE

- docs/Public Module Imports.md
- packages/main/README.md
- packages/main/src/TimePicker.hbs
- packages/main/src/TimePicker.js
- packages/main/src/TimePickerPopover.hbs
- packages/main/src/themes/TimePicker.css
- packages/main/src/themes/TimePickerPopover.css
- packages/main/test/pages/Kitchen.html
- packages/main/test/pages/TimePicker.html
- packages/main/test/samples/TimePicker.sample.html
- packages/main/test/specs/TimePicker.spec.js
BREAKING_CHANGE: ui5-timepicker is renamed to ui5-time-picker
> chore(ui5-time-picker): rename component

- packages/base/src/util/isNodeHidden.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1834
> chore: fix typo in isNodeHidden

- packages/main/src/themes/TabContainer.css
> fix(ui5-tabcontainer): fix box-shadow

- packages/main/src/Dialog.js
> fix(ui5-dialog): fix behaviour on mobile when added to DOM on interaction

- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/ShellBar.js
- packages/fiori/src/themes/ShellBar.css
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/samples/ShellBar.sample.html
- packages/playground/_sass/base.scss
Replace the existing property "logo" with a slot with the same name to enable users set an element of their choice and freedom to customize it.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1841
BREAKING_CHANGE: property "logo" has been removed, use the "logo" slot instead as follows:
```html
<ui5-shellbar>
</ui5-shellbar>
```
> feat(ui5-shellbar): add "logo" slot

- packages/fiori/bundle.esm.js
- packages/fiori/src/FlexibleColumnLayout.hbs
- packages/fiori/src/FlexibleColumnLayout.js
- packages/fiori/src/fcl-utils/FCLLayout.js
- packages/fiori/src/i18n/messagebundle.properties
- packages/fiori/src/themes/FlexibleColumnLayout.css
- packages/fiori/src/themes/base/FlexibleColumnLayout-parameters.css
- packages/fiori/src/themes/sap_belize/parameters-bundle.css
- packages/fiori/src/themes/sap_belize_hcb/FlexibleColumnLayout-parameters.css
- packages/fiori/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/fiori/src/themes/sap_belize_hcw/FlexibleColumnLayout-parameters.css
- packages/fiori/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3_dark/FlexibleColumnLayout-parameters.css
- packages/fiori/src/themes/sap_fiori_3_dark/parameters-bundle.css
- packages/fiori/src/types/FCLLayout.js
- packages/fiori/test/pages/FCL.html
- packages/fiori/test/pages/FCLApp.html
- packages/fiori/test/samples/FlexibleColumnLayout.sample.html
- packages/fiori/test/specs/FCL.spec.js
- packages/playground/build-scripts/samples-prepare.js
- packages/theme-base/css-vars-usage.json
Introduce new component in the "fiori" package, called FlexibleColumnLayout. The component implements the master-detail-detail paradigm by displaying up to three pages in separate columns. There are several possible layouts that can be changed either with the component API, or by pressing the arrows, displayed between the columns.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1851
>  feat(ui5-flexible-column-layout): new component

- packages/main/test/pages/DialogSemantic.html
This new test page demonstrates how to build a Dialog implementing the "MessageBox" concept:
The same could be done for the positive/negative/info/etc... variations by just changing the icons and colors.
closes: https://github.com/SAP/ui5-webcomponents/issues/1881
> chore(ui5-dialog): Show how to build a semantic dialog

- packages/fiori/test/samples/FlexibleColumnLayout.sample.html
The tag name was wrong in the sample.
> chore(fcl): fix tag name in sample

- packages/base/src/UI5Element.js
- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/ShellBar.js
- packages/fiori/src/ShellBarItem.js
- packages/main/src/Tab.js
- packages/main/src/TabContainer.js
- packages/main/src/TabInStrip.hbs
- packages/main/test/pages/TabContainer.html
In this PR two components are implementing the functionality that is introduced in Ui5Element:
- TabContainer
- ShellBar
Fixes: #1840
> feat(framework): implement stabledomref functionality

- packages/fiori/src/UploadCollectionItem.hbs
- packages/fiori/src/UploadCollectionItem.js
- packages/fiori/src/themes/UploadCollectionItem.css
- packages/fiori/src/themes/base/UploadCollection-parameters.css
- packages/fiori/src/themes/sap_belize_hcb/UploadCollection-parameters.css
- packages/fiori/src/themes/sap_belize_hcw/UploadCollection-parameters.css
Replaced custom progress indicator with the webcomponent **ui5-progress-indicator** in **ui5-upload-collection-item**. Removed unneeded styles, css variables and code.
Fixes #1914
> refactor(ui5-upload-collection): integrated ui5-progress-indicator

- packages/main/src/Input.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1930
> fix(ui5-input): Fix JS error on mouseover/out

- packages/base/src/UI5Element.js
When `managedSlots: true` is set, the expectation is that you'll have properties for all children, no matter if you have a template or not.
Until now, only components that render in the Shadow DOM (have a template) had their children processed and observed. However, it is possible to have abstract items that don't render in the Shadow DOM, but still need to have properties for their children. This becomes possible by moving the code related to managed slots out of the condition that checks for Shadow DOM usage.
Additionally, the `await` before `renderImmediately` was removed since it's no longer an async function.
> fix(framework): managedSlots: true always has effect

- packages/main/src/Input.hbs
- packages/main/src/Input.js
- packages/main/src/i18n/messagebundle.properties
> feat(ui5-input): announce suggestions count

- packages/main/src/TabContainer.hbs
> fix(ui5-tabcontainer): fix accessibility of overflow button

- packages/main/src/themes/Carousel.css
> fix(ui5-carousel): make content under the navigation arrows accessible

- packages/fiori/src/UploadCollectionItem.hbs
- packages/fiori/src/UploadCollectionItem.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2003
> fix(ui5-upload-collection-item): Activate editing with SPACE

- packages/main/src/Tokenizer.js
Tokenizer invalidation logic seems overly complicated:
- `setTimeout` during `onBeforeRendering`
- Manually calling `_invalidate` which is not allowed for the component layer
The solution is to remove the "hidden state" and declare it as explicit state in metadata:
- Add `_nMoreCount` which is the actual state that needs to invalidate the component upon change
- Make the `_nMoreText` a getter, since it's computed state based on `_nMoreCount` only
- Recalculate `_nMoreCount` directly in 2 places: the resize handler and during `onAfterRendering`. If, and only if, it computes to a different number, this will automatically invalidate the component, so no need for manual checks or invalidation.
Additionally, moved the item navigation callback to a separate function and named it …
> refactor(ui5-tokenizer): simplify invalidation

- packages/fiori/src/ShellBar.js
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/specs/ShellBar.spec.js
> fix(ui5-shellbar-item): make item invalidate shellbar

- packages/main/src/themes/Card.css
> fix(ui5-card): card header now can be focused correctly

- packages/main/src/Select.js
- packages/main/src/SelectPopover.hbs
- packages/main/src/themes/Select.css
- packages/main/src/themes/SelectPopover.css
- packages/main/test/samples/Select.sample.html
Now, **ValueStateMessage**s are supported in **ui5-select** when **ValueState** is set to "Warning", Error or "Information"
#1086
> feat(ui5-select): Add value state message

- packages/main/src/Carousel.hbs
- packages/main/src/Carousel.js
> feat(ui5-carousel): implement rtl support

- packages/main/src/DurationPicker.js
> fix(ui5-duration-picker): fix incorrect data support

- packages/main/src/ComboBox.js
- packages/main/src/ComboBoxPopover.hbs
- packages/main/test/pages/ComboBox.html
Implement value state msg for another "input" component
Related to: https://github.com/SAP/ui5-webcomponents/issues/1086
> feat(ui5-combobox): implement valueStateMessage

- packages/main/src/DurationPicker.hbs
- packages/main/src/DurationPicker.js
- packages/main/test/pages/DurationPicker.html
- packages/main/test/specs/DurationPicker.spec.js
- packages/main/test/specs/TimePicker.spec.js
Related to: https://github.com/SAP/ui5-webcomponents/issues/1086
> feat(ui5-duration-picker): implement valueStateMessage

- packages/main/src/MultiComboBox.js
- packages/main/src/MultiComboBoxPopover.hbs
> fix(ui5-multi-combobox): fix behavior of show all selected button

- packages/main/src/TextArea.hbs
> fix(ui5-textarea): add aria-required

- packages/main/src/Input.hbs
- packages/main/src/Input.js
> fix(ui5-input): implement aria-required

- packages/main/src/Select.hbs
- packages/main/src/Select.js
> feat(ui5-select): introduce required property

- packages/main/src/DatePicker.js
Part of #2108
Depends on #2114
> feat(ui5-datepicker): introduce required property

- packages/main/src/DatePicker.js
- packages/main/src/Input.js
- packages/main/test/pages/DatePicker.html
- packages/main/test/pages/DatePicker_test_page.html
- packages/main/test/specs/DatePicker.spec.js
FIXES https://github.com/SAP/ui5-webcomponents/issues/2107
> feat(ui5-date-picker): add ariaLabel and ariaLabelledby properties

- packages/main/src/themes/Tokenizer.css
> fix(ui5-multi-combobox): fix jumping parent div

- packages/main/src/DateTimePicker.js
- packages/main/src/DateTimePickerPopover.hbs
Now you can navigate with arrows between the sliders.
Related to: #1534
> feat(ui5-datetime-picker): improve keyboard handling support

- packages/main/src/ComboBox.hbs
- packages/main/src/ComboBox.js
> feat(ui5-combobox): implement icon slot

- packages/main/src/DurationPicker.js
- packages/main/src/TimePicker.js
- packages/main/src/WheelSlider.js
Extracted the PageUp and PageDown slider handler in the WheelSlider component to remove code repeat.
> refactor(ui5-time-picker, ui5-duration-picker, ui5-datetime-picker): Extracting some of the heyboard handling logic on slider level

- yarn.lock
Update chromedriver version from 83.0.0 to 84.0.1, that supports Chrome 84 and 85, as all new PRs started failing with "This version of ChromeDriver only supports Chrome version 83"
> chore: update chromedriver

- packages/main/src/MultiInput.js
- packages/main/test/pages/MultiInput.html
- packages/main/test/pages/MultiInput_Suggestions.html
- packages/main/test/specs/MultiInput.spec.js
- yarn.lock
Fire the value-help-trigger when F4 or ALT/OPTION + ARROW_UP/ARROW_DOWN keyboard keys are used.
FIXES https://github.com/SAP/ui5-webcomponents/issues/2143
BREAKING CHANGE value-help-icon-press is renamed to value-help-trigger
> feat(ui5-multi-input): fire value-help-trigger with F4, ALT/OPTION + ARROW_UP/DOWN

- packages/main/src/MultiComboBox.hbs
- packages/main/src/MultiComboBox.js
> feat(ui5-multi-combobox): implement icon slot

- packages/main/src/themes/Tab.css
- packages/main/src/themes/TabContainer.css
- packages/main/test/specs/TabContainer.spec.js
> fix(ui5-tabcontainer): remove scroll from empty tabs

- packages/main/src/themes/Button.css
> chore(ui5-button): propagate more css properties to host element

- packages/main/src/DateRangePicker.js
- packages/main/test/pages/DateRangePicker.html
- packages/main/test/specs/DateRangePicker.spec.js
> fix(ui5-daterange-picker): enable selection of single day

- README.md
- docs/dev/Playground.md
> docs: add tutorial for local start of the playground

- packages/main/src/themes/Button.css
> fix(ui5-button): prevent buttons with icon truncate in ie

- packages/main/src/popup-utils/PopupUtils.js
> fix(ui5-popover): fix js errors if parent is removed from DOM

- packages/playground/assets/js/playground.js
> docs: make playground set rtl properly

- packages/main/src/themes/BusyIndicator.css
- packages/main/src/themes/CustomListItem.css
> fix(ui5-li-custom): fix pointer-events inheritance

- packages/main/src/Input.hbs
- packages/main/src/Panel.hbs
- packages/main/src/Panel.js
- packages/main/src/themes/Input.css
- packages/main/src/themes/Panel.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/test/pages/Panel.html
Fixes some visual deviations from Fiori spec, we recently received as feedback.
- input filed padding with and without an icon (reflects in all input based components)
- panel icon type, border and background
>  fix: fix visual deviations from Fiori spec

- packages/main/src/Calendar.js
- packages/main/src/CalendarHeader.hbs
- packages/main/src/CalendarHeader.js
- packages/main/src/DayPicker.hbs
- packages/main/src/DayPicker.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/pageobjects/DatePickerTestPage.js
- packages/main/test/specs/DatePicker.spec.js
- packages/main/test/specs/DateRangePicker.spec.js
> feat(ui5-date-picker): add screen reader support

- packages/main/src/ListItem.js
- packages/main/src/Select.hbs
- packages/main/src/Select.js
- packages/main/src/SelectPopover.hbs
- packages/main/src/i18n/messagebundle.properties
>  feat(ui5-select): improve accessibility

- packages/main/src/Calendar.js
- packages/main/src/MultiInput.hbs
- packages/main/src/Tokenizer.js
- packages/main/src/TokenizerPopover.hbs
- packages/main/src/themes/ResponsivePopoverCommon.css
- packages/main/test/pages/MultiInput.html
FIXES: #1086 
ValueStateMessage is now shown inside the nMore popover on both desktop and mobile devices.
> fix(ui5-multiinput): Improve valueStateMessage in nMore popover

- packages/main/src/Select.js
> fix(ui5-select): make disabled select not focusable

- packages/base/src/Device.js
Now device.js supports wrong input data
> chore(framework): refactor device.js

- packages/main/src/ListItem.js
> feat(ui5-li, ui5-li-tree, ui5-li-custom, ui5-upload-collection-item):  implement role property

- packages/main/src/List.hbs
- packages/main/src/List.js
- packages/main/src/Tree.hbs
>  feat(ui5-list): introduce role property

- packages/fiori/src/NotificationListItem.js
- packages/main/src/DateRangePicker.js
- packages/main/src/GroupHeaderListItem.js
- packages/main/src/List.js
- packages/main/src/RadioButton.js
> fix(JSDoc): correct typing errors

- packages/main/src/popup-utils/OpenedPopupsRegistry.js
> fix(ui5-popup, ui5-dialog): remove instance from openedPopupsRegistry

- packages/main/src/themes/ListItem.css
- packages/main/src/themes/base/sizes-parameters.css
Corrected **ui5-li** and its icon sizes in Cozy mode.
Part of #2218
> fix(ui5-li): correct sizes

- packages/main/src/ComboBox.js
> fix(ui5-combobox): allow setting value with javascript

- packages/fiori/src/ShellBar.hbs
- packages/fiori/test/pages/SideNavigation.html
> feat(ui5-shellbar): implement root part

- packages/main/src/ComboBox.js
Reverts SAP/ui5-webcomponents#2253 as the change causes degradation in the component behavior.
FIXES https://github.com/SAP/ui5-webcomponents/issues/2321
> Revert "fix(ui5-combobox): allow setting value with javascript"

- packages/main/src/themes/TextArea.css
FIXES https://github.com/SAP/ui5-webcomponents/issues/2338
> fix(ui5-textarea): fix placeholder font-style

- packages/main/src/themes/DatePicker.css
- packages/main/src/themes/DateRangePicker.css
- packages/main/src/themes/DateTimePicker.css
- packages/main/src/themes/DurationPicker.css
- packages/main/src/themes/TimePicker.css
With this change you can change the color and bg-color by standard CSS, applied on the host of the DatePicker, TimePicker, DateTimePicker and DateRangePicker components
> chore(ui5-date*): enable color and bg-color restyling

- packages/main/src/themes/TabContainer.css
Fixes #2354
Must not break #2144
> fix(ui5-tab): expand tab height to tabcontainer height

- packages/main/src/MessageStrip.hbs
- packages/main/src/MessageStrip.js
> fix(ui5-messagestrip): fix close button accessibility

- packages/base/src/StaticAreaItem.js
- packages/main/src/Input.js
> fix(ui5-input): prevent js error when element is removed from DOM

- packages/fiori/src/NotificationListItem.js
> docs(NotificationListItem): add type annotation for wrap property, fix typos

- README.md
> docs(README.md): adjust link to in depth tutorial

- packages/main/src/MultiComboBox.hbs
- packages/main/src/MultiComboBox.js
- packages/main/test/specs/MultiComboBox.spec.js
> fix(ui5-multi-combobox): make focus outline visible

- packages/main/src/FileUploader.js
> docs(ui5-file-uploader): explain that accept file types require dots

- packages/main/src/Icon.js
- packages/main/test/samples/Dialog.sample.html
- packages/main/test/samples/Icon.sample.html
- packages/main/test/specs/MultiComboBox.spec.js
Showcase: 
- dialog: resizable, draggable
- SAP Fiori Tools Icons
> docs: showcase new features within playground

- packages/main/test/samples/List.sample.html
> fix(docs): fix list sample code

- packages/fiori/src/NotificationOverflowAction.js
> docs(ui5-notification-overflow-action): add missing tagname

- packages/main/src/Popup.hbs
- packages/main/src/Popup.js
- packages/main/src/themes/Popover.css
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2387
> fix(ui5-popover): correct arrow position on RTL

- packages/main/src/themes/Badge.css
FIXES https://github.com/SAP/ui5-webcomponents/issues/2451
> fix(ui5-badge): enable letter spacing overwrite

- packages/base/src/types/CalendarType.js
- packages/base/src/types/DataType.js
- packages/base/src/types/PopupState.js
- packages/base/src/types/ValueState.js
- packages/fiori/src/types/FCLLayout.js
- packages/fiori/src/types/UploadCollectionDnDMode.js
- packages/fiori/src/types/UploadState.js
- packages/main/src/types/AvatarBackgroundColor.js
- packages/main/src/types/AvatarFitType.js
- packages/main/src/types/AvatarShape.js
- packages/main/src/types/AvatarSize.js
- packages/main/src/types/BusyIndicatorSize.js
- packages/main/src/types/ButtonDesign.js
- packages/main/src/types/CarouselArrowsPlacement.js
- packages/main/src/types/InputType.js
- packages/main/src/types/LinkDesign.js
- packages/main/src/types/ListItemType.js
- packages/main/src/types/ListMode.js
- packages/main/src/types/ListSeparators.js
- packages/main/src/types/MessageStripType.js
- packages/main/src/types/PanelAccessibleRole.js
- packages/main/src/types/PopoverHorizontalAlign.js
- packages/main/src/types/PopoverPlacementType.js
- packages/main/src/types/PopoverVerticalAlign.js
- packages/main/src/types/Priority.js
- packages/main/src/types/SemanticColor.js
- packages/main/src/types/TabContainerTabsPlacement.js
- packages/main/src/types/TabLayout.js
- packages/main/src/types/TitleLevel.js
- packages/main/src/types/ToastPlacement.js
Rename generat**a**TypeAcessors -> generat**e**TypeAcessors
> chore: fix typo in generateTypeAcessors

- packages/fiori/src/i18n/messagebundle_en_US_saprigi.properties
- packages/main/src/i18n/messagebundle_en_US_saprigi.properties
> Translation Delivery

- packages/main/src/DateRangePicker.js
- packages/main/test/specs/DateRangePicker.spec.js
- The ui5-daterange-picker tests are now stable and don't introduce timing issues due to rendering of the component.
- The ui5-daterange-picker value in the input field gets updated properly on focus out or "Enter" keyboard key press.
Fixes: #2475
> fix(ui5-daterange-picker): all tests are now enabled

- packages/main/src/Input.js
- packages/main/test/pages/Input.html
- packages/main/test/specs/Input.spec.js
> fix(ui5-input): don't render aria-describedby if not neccessary

- packages/main/src/Carousel.js
- packages/main/test/pages/Carousel.html
- packages/main/test/specs/Carousel.spec.js
> fix(ui5-carousel): add all visible items to tab chain

- packages/main/bundle.esm.js
- packages/main/src/Avatar.hbs
- packages/main/src/Avatar.js
- packages/main/src/AvatarGroup.hbs
- packages/main/src/AvatarGroup.js
- packages/main/src/themes/Avatar.css
- packages/main/src/themes/AvatarGroup.css
- packages/main/src/themes/base/Avatar-parameters.css
- packages/main/src/themes/base/AvatarGroup-parameter.css
- packages/main/src/themes/sap_belize_hcb/Avatar-parameters.css
- packages/main/src/themes/sap_belize_hcw/Avatar-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Avatar-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Avatar-parameters.css
- packages/main/src/types/AvatarGroupType.js
- packages/main/test/pages/Avatar.html
- packages/main/test/pages/AvatarGroup.html
- packages/main/test/samples/AvatarGroup.sample.html
- packages/main/test/specs/Avatar.spec.js
- packages/main/test/specs/AvatarGroup.spec.js
- packages/playground/build-scripts/samples-prepare.js
Introduce new component in the `main` package, called `AvatarGroup`. 
The component is used to display a group of avatars arranged horizontally. It is useful to visually showcase a group of related avatars, such as, project team members or employees. The control allows you to display the avatars in different sizes, depending on your use case.
Supports 2 types - `Group` and `Invidual`:
- `Group` type: The avatars are displayed as partially overlapped on top of each other and the entire group has one click/tap area.
- `Individual` type: The avatars are displayed side-by-side and each avatar has its own click/tap area.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/2409
> feat(ui5-avatar-group): initial implementation

- packages/main/src/Tree.hbs
- packages/main/src/themes/Tree.css
FIXES https://github.com/SAP/ui5-webcomponents/issues/2545
> fix(ui5-tree): make the height of tree adjustable

- packages/main/src/Button.hbs
- packages/main/test/pages/Button.html
> fix(ui5-button): hide icon tooltip

- packages/fiori/test/samples/SideNavigation.sample.html
Fixing this issue as a follow up from the side navigation handover to team RD
> docs: fix ui5-side-navigation sample

- packages/fiori/test/samples/Bar.sample.html
Correct the package info as the component is part of the @ui5/webcomponents-fiori package.
> docs(ui5-bar): correct package info

- packages/fiori/src/ShellBar.js
- packages/main/src/TabContainer.js
> docs: add missing docs for stable DOM refs

- packages/main/src/SliderBase.js
The default slot is never used.
> fix(ui5-slider):  remove default slot as never used

- packages/main/src/MultiComboBox.js
Document StartsWith and Contains filter options as well.
> docs(ui5-multi-combobox): add more filter options

- packages/fiori/src/ShellBar.hbs
> fix(ui5-shellbar) accessibility improvements

- packages/main/src/List.hbs
- packages/main/src/List.js
- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
- packages/main/src/Tree.hbs
- packages/main/src/TreeListItem.hbs
- packages/main/src/TreeListItem.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/src/themes/TreeListItem.css
Fixes #2465
Done:
- Tooltip for the expand/collapse icon is added
- Tree item is now announced
- Selected state is now announced
- Announced level is fixed
- Translation for LIST_ITEM_SELECTED is fixed
- Tree view is now read out once.
> feat(ui5-tree): implement acc spec 

- packages/main/src/themes/Avatar.css
- packages/main/test/pages/AvatarGroup.html
> fix(ui5-avatar): correct icon color

- docs/React-tutorial.md
> fix(docs): mis-spelling in react tutorial

- packages/fiori/src/ShellBar.js
> docs(ui5-shellbar): profile slot description improvement

- packages/fiori/src/themes/UploadCollectionItem.css
- packages/main/src/themes/Link.css
> fix(ui5-upload-collection-item): fix title behaviour on small screens

- packages/main/src/Tree.hbs
- packages/main/src/TreeItem.js
- packages/main/src/TreeListItem.hbs
- packages/main/src/TreeListItem.js
- packages/main/src/themes/TreeListItem.css
- packages/main/test/pages/Tree.html
Info and infoState attributes are added to ui5-tree-item.
Fixes: #2633
> feat(ui5-tree-item): implement info/infoState attributes

- packages/main/src/Dialog.hbs
- packages/main/src/Dialog.js
- packages/main/src/Popover.js
- packages/main/src/ResponsivePopover.js
> fix(ui5-popover, ui5-dialog): do not render empty headers

- packages/main/src/MultiComboBox.hbs
- packages/main/src/MultiComboBox.js
- packages/main/test/pages/MultiComboBox.html
- packages/main/test/specs/MultiComboBox.spec.js
> fix(ui5-multicombobox): hide placeholder when tokens

- packages/main/src/Input.js
- packages/main/src/InputPopover.hbs
- packages/main/src/MultiComboBox.js
- packages/main/src/MultiComboBoxPopover.hbs
> fix(ui5-input): ValueStateMessage width fixed

- packages/main/src/Tokenizer.hbs
- packages/main/src/Tokenizer.js
- packages/main/src/themes/Token.css
- packages/main/src/themes/Tokenizer.css
- packages/main/src/themes/base/sizes-parameters.css
> fix(ui5-multi-input): fix appearance in RTL

- packages/main/src/AvatarGroup.js
- packages/main/test/pages/Avatar.html
Make clear that the avatars with "Circle" shape is the one Fiori 3 suggests and meant to be used.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2612
> docs(ui5-avatar-group): comment on the avatars' shape

- packages/main/src/ComboBox.js
> fix(ui5-combobox): User action cancelled when clicking "X" on mobile

- packages/main/src/Input.hbs
- packages/main/src/Input.js
- packages/main/src/themes/DatePicker.css
- packages/main/src/themes/Input.css
- packages/main/test/pages/Input.html
> fix(ui5-input): enable centering of text

- packages/base/src/asset-registries/Themes.js
> fix(ThemeAssetRegistry): fix error message

- packages/main/test/specs/MultiComboBox.spec.js
- packages/main/test/specs/Select.spec.js
Comment regally failing tests, Issues have been created and dispatched to the responsible teams
https://github.com/SAP/ui5-webcomponents/issues/2846
https://github.com/SAP/ui5-webcomponents/issues/2845
> chore: comment failing tests

- packages/main/src/themes/Label.css
- packages/main/test/pages/Label.html
> fix(ui5-label): text-align works with property wrap

- packages/fiori/src/UploadCollectionItem.js
- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
> fix(ui5-upload-collection-item): show disabled delete button

- docs/React-tutorial.md
Fixes https://github.com/SAP-samples/ui5-webcomponents-sample-react/issues/35
> docs: add link to the ui5 webcomponents for react project

- packages/fiori/src/Page.js
- packages/fiori/src/ShellBar.js
- packages/fiori/src/ShellBarItem.js
- packages/fiori/src/SideNavigation.js
- packages/main/src/AvatarGroup.js
- packages/main/src/ColorPalette.js
- packages/main/src/DatePicker.js
- packages/main/src/Dialog.js
- packages/main/src/Input.js
- packages/main/src/Popover.js
- packages/main/src/Popup.js
- packages/main/src/RangeSlider.js
- packages/main/src/ResponsivePopover.js
- packages/main/src/Select.js
- packages/main/src/StepInput.js
- packages/main/src/TabContainer.js
- packages/main/src/TimePicker.js
- packages/main/src/TimePickerBase.js
- packages/main/src/TreeItem.js
- packages/main/src/WheelSlider.js
Changes:
- all events have `detail` in the metadata object for the parameters
- all public methods are documented with `@return` and `@async`
- `Popup.js`: the `open` method documented as `@protected` so it doesn't appear for `Popover.js`. Only in `Popover.js` is it documented as `@public`.
- `ResponsivePopover.js`: the `open` method is now `async` (not only in terms of documentation)
- The documentation of `boolean`, `Integer` and `Float` is unified (in terms of small/capital letters)
> docs: Improve methods documentation

- packages/main/src/themes/Select.css
- value color was different than the others form controls. Now it is
the same as them.
> fix(ui5-select): incorrect value color is now fixed

- packages/main/test/specs/MultiComboBox.spec.js
This is a temp commit to check what might be failing with mcb's tests
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2845
> ui5-multicombobox: fix failing test

- docs/FAQ.md
> docs: fix broken link in faq

- packages/main/src/DateRangePicker.js
- packages/main/src/Popover.js
For some time `eslint` was not running and some code with eslint errors made it to master while the fix was being prepared.
> chore: fix lint errors

- packages/main/src/ColorPalette.hbs
- packages/main/test/samples/ColorPalette.sample.html
- More colors text used to have 6 dots (3 from the template and 3 from the translated text)
- sample updated to show real-case scenario of ColorPalette with "more-colors" set.
> fix(ui5-color-palette): remove additional dots in more-colors

- packages/main/src/TableColumn.hbs
- packages/main/src/themes/TableColumn.css
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2945
> fix(ui5-table-column): align content right in RTL

- packages/main/src/TableRow.hbs
- packages/main/src/TableRow.js
- packages/main/test/specs/Table.spec.js
Start firing row-click upon ENTER/SPACE
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2944
> fix(ui5-table-row): fire row-click on SPACE/ENTER

- README.md
- docs/dev/Development Workflow.md
Update the documentation regarding the required `node.js` version
> docs: require Node.js 14

- packages/main/test/specs/Select.spec.js
Related issue: https://github.com/SAP/ui5-webcomponents/issues/3000
> chore(ui5-select): temporarily comment out failing tests

- packages/localization/lib/copy-list/index.js
Copy the `used-modules.txt` files asynchronously.
Build time reduced from `14 sec` to `4 sec`.
Total build time is now `2min 23sec`
> chore: improve the localization build

- packages/main/src/themes/Table.css
> fix(ui5-table): bottom borded added

- packages/fiori/src/FlexibleColumnLayout.js
We changed the breakpoints for layout changes in the past, but the docs still point to the old ones. Now we update them to correctly reflect the component behaviour.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2976
> docs: fix breakpoints info

- packages/fiori/src/ShellBar.js
- packages/fiori/test/specs/ShellBar.spec.js
> fix(ui5-shellbar): primary title menu is closed on content click

- packages/main/src/FileUploader.hbs
- packages/main/src/FileUploader.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/3001
> fix(ui5-file-uploader): opening dialog with space or enter key

- packages/fiori/src/themes/NotificationListItem.css
- packages/fiori/test/pages/NotificationListGroupItem.html
> fix(ui5-li-notification): Fix contents if description cannot wrap

- packages/main/src/Dialog.hbs
- packages/main/src/Dialog.js
> fix(ui5-dialog): Fix aria-labelledby attribute value

- packages/ie11/src/features/IE11WithoutFetch.js
closes: https://github.com/SAP/ui5-webcomponents/issues/3052
> chore(ie11): Provide a polyfill feature without fetch

- packages/main/src/Dialog.js
- packages/main/src/Popover.js
- packages/main/src/themes/BrowserScrollbar.css
- packages/main/test/pages/Dialog.html
> fix(ui5-dialog): Fixed scrollbars styling

- packages/main/src/Popup.hbs
- packages/main/src/Popup.js
> fix(ui5-dialog): Fixed RTL mode

- packages/main/src/Button.js
- packages/main/src/ListItem.js
Reverts SAP/ui5-webcomponents#3046
> Revert "refactor(ui5-button, ui5-li): make touch events handlers passive"

- packages/main/src/Button.js
> fix(ui5-button, ui5-togglebutton): fix behaviour on mobile

- packages/main/src/themes/ColorPicker.css
The Shadow Parts names of the Slider have [changed](https://github.com/SAP/ui5-webcomponents/pull/3096)
and the Color Picker should adopt the new names.
> chore(ui5-color-picker): adopt new shadow part names

- packages/main/test/samples/Table.sample.html
The selection sample now shows the "mode" attribute set.
> docs: update table sample

- packages/main/src/ColorPalette.hbs
- packages/main/src/ColorPalette.js
- packages/main/src/themes/ColorPalette.css
- packages/main/test/pages/ColorPalette.html
- packages/main/test/samples/ColorPalette.sample.html
- packages/main/test/specs/ColorPalette.spec.js
> feat(ui5-color-palette): implement show-recent-color functionality

- packages/main/src/SliderBase.hbs
- packages/main/test/specs/ColorPalette.spec.js
> fix(ui5-slider, ui5-range-slider): render only one top level element

- packages/fiori/src/Wizard.js
- packages/fiori/src/i18n/messagebundle.properties
- packages/fiori/test/specs/Wizard.spec.js
> fix(ui5-wizard): remove repetitive announcement

- packages/main/src/TableRow.js
> docs(ui5-table): Documentation enhancement

- docs/Angular-tutorial.md
> docs: fix lists in angular tutorial

- packages/main/src/themes/Avatar.css
- packages/main/src/themes/Button.css
- packages/main/src/themes/Icon.css
When the button is a slot in the file uploader, the hover state flag was given by a class added to the button. So now we create selectors for the different button styles with this class also.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3119
> fix(ui5-file-uploader): hovering now gives correct button styles

- packages/fiori/src/Bar.hbs
- packages/fiori/src/Bar.js
fix(ui5-bar): aria label added depending on the "design" property
Fixes #3020
> fix(ui5-bar): aria label added depending on the "design" property

- packages/main/src/themes/BusyIndicator.css
> fix(ui5-busyindicator): fix typo in styles

- docs/Public Module Imports.md
Some of the newly added components has not been documented in the Public Imports Document
> docs: add more public imports

- packages/main/package.json
- packages/main/src/Carousel.hbs
- packages/main/src/Carousel.js
- packages/main/src/themes/Carousel.css
- packages/main/test/specs/Carousel.spec.js
> fix(ui5-carousel): hides navigation arrows on mouse out

- packages/main/src/themes/ListItem.css
> fix(ui5-li): info text width

- packages/playground/docs/landing-page.html
> chore: use only one tab for the playground app

- packages/fiori/src/ProductSwitch.hbs
- packages/fiori/src/ProductSwitch.js
- packages/fiori/src/ProductSwitchItem.hbs
- packages/fiori/src/ProductSwitchItem.js
- packages/fiori/src/i18n/messagebundle.properties
- packages/fiori/test/specs/ProductSwitch.spec.js
FIXES: #2707
Additionally: 
UP and DOWN arrow keys navigation is updated, and limited to the product switch borders.
> feat(ui5-product-switch): Implement accessibility specification

- packages/main/src/DatePicker.js
- packages/main/src/TimePickerBase.js
- packages/main/src/TimeSelection.js
Related to: https://github.com/SAP/ui5-webcomponents/issues/3107
> docs: rename param from oDate to date

- packages/main/src/TableColumn.js
> docs(ui5-table-column): Enhance documentation about minWidth property

- packages/main/src/Label.hbs
- packages/main/src/Label.js
- packages/main/src/themes/Label.css
- packages/main/test/pages/Label.html
> fix(ui5-label): fix required label in safari

- packages/fiori/src/Page.js
- packages/fiori/src/themes/Page.css
> docs(ui5-page): improve docs

- docs/CustomFonts.md
Documentation review of CustomFonts.md
> docs: update custom fonts.md

- docs/How To Use.md
Review of the documentation topic How to Use.
> docs: review of how to use.md

- docs/Migration-guides.md
Review of the documentation topic Migration Guides.
> docs: update migration-guides.md

- docs/Configuration.md
> docs: update configuration.md

- docs/Public Module Imports.md
Review of the documentation topic Public Module Imports.
> docs: review of public module imports.md

- docs/Assets.md
> docs: update assets.md

- packages/playground/docs/getting-started.md
Please, check the first sentence: The UI5 Web Components share fundamental UI5 qualities with others to provide enterprise-grade features, Fiori UX and themeability. It's not clear what 'others' refers to.
> docs: update getting-started.md

- packages/fiori/src/FlexibleColumnLayout.js
- packages/main/src/Avatar.js
- packages/main/src/CheckBox.js
- packages/main/src/Icon.js
- packages/main/src/List.js
- packages/main/src/Select.js
> feat: add keyboard handling docs

- docs/Scoping.md
Review of the documentation topic Micro-frontends and Custom Elements Scoping.
> docs: review of scoping.md

- docs/i18n.md
Review of documentation topic UI5 Web Components i18n for apps.
> docs: review of  i18n.md

- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/ShellBar.js
- packages/fiori/src/themes/ShellBar.css
- packages/fiori/test/pages/FCL.html
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/samples/FlexibleColumnLayout.sample.html
- packages/fiori/test/samples/NotificationListGroupItem.sample.html
- packages/fiori/test/samples/NotificationListItem.sample.html
- packages/fiori/test/samples/ShellBar.sample.html
Part of #3107
BREAKING_CHANGE: ```notificationCount``` property is deprecated in favour of ```notificationsCount``` property
> refactor(ui5-shellbar): rename notificationCount property to notificationsCount

- packages/main/src/TextArea.js
- packages/main/test/specs/TextArea.spec.js
> fix(ui5-textarea): revert value on escape

- packages/main/src/CheckBox.js
- packages/main/src/themes/CheckBox.css
- packages/main/src/themes/base/CheckBox-parameters.css
> feat(ui5-checkbox): add new value state type

- packages/fiori/src/themes/ShellBar.css
> fix(ui5-shellbar): menu button arrow position

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
Update the GitHub templates for filing issues and feature requests: 
- simplify the sections headings.
- add new fields to encourage authors provide info regarding the severity/urgency of the requirements.
> chore: update github templates

- packages/main/test/pages/Table.html
- packages/main/test/samples/Table.sample.html
> docs: improve ui5-table sample

- packages/main/src/themes/Card.css
> fix(ui5-card): fix styles for slotted images

- packages/base/src/util/TabbableElements.js
- packages/base/src/util/isNodeTabbable.js
- packages/main/src/ListItem.hbs
Delete button should not be part of tab chain. It should be accessed only with mouse.
Fixes: #2964
> fix(ui5-li): delete button focus

- docs/Public Module Imports.md
- packages/fiori/test/pages/FCL.html
- packages/fiori/test/pages/Wizard.html
- packages/fiori/test/pages/Wizard_test.html
- packages/fiori/test/samples/Wizard.sample.html
- packages/main/README.md
- packages/main/src/DateTimePickerPopover.hbs
- packages/main/src/MultiComboBoxPopover.hbs
- packages/main/src/SegmentedButton.js
- packages/main/src/ToggleButton.js
- packages/main/src/themes/SegmentedButton.css
- packages/main/src/themes/ToggleButton.ie11.css
- packages/main/test/pages/Button.html
- packages/main/test/pages/Calendar.html
- packages/main/test/pages/Components.html
- packages/main/test/pages/Kitchen.html
- packages/main/test/pages/Kitchen.openui5.html
- packages/main/test/pages/RTL.html
- packages/main/test/pages/SegmentedButton.html
- packages/main/test/pages/Select.html
- packages/main/test/pages/ToggleButton.html
- packages/main/test/pages/Tree.html
- packages/main/test/pages/kitchen-styles.css
- packages/main/test/samples/SegmentedButton.sample.html
- packages/main/test/samples/ToggleButton.sample.html
- packages/main/test/specs/SegmentedButton.spec.js
- packages/playground/lib/static-index.js
The change is part of: https://github.com/SAP/ui5-webcomponents/issues/3107
BREAKING_CHANGE: The tag name `ui5-togglebutton` has been renamed to `ui5-toggle-button`
> refactor(ui5-toggle-button): rename tag name

- packages/main/src/Select.hbs
- packages/main/src/Select.js
- packages/main/src/themes/Select.css
> fix(ui5-select): display icon of selected option

- packages/main/src/Card.hbs
- packages/main/src/Card.js
- packages/main/src/themes/Card.css
- packages/main/test/pages/Card.html
- packages/main/test/pages/Carousel.html
- packages/main/test/pages/CarouselLoadMore.html
- packages/main/test/samples/Card.sample.html
- packages/main/test/samples/Carousel.sample.html
- packages/main/test/specs/Card.spec.js
Part of #3107 
BREAKING_CHANGE: rename ```heading```/```subheading``` to ```titleText```/```subtitleText```
> fix(ui5-card): rename heading/subheading to titleText/subtitleText

- packages/main/test/samples/Button.sample.html
Replace `disabled` with `design="Default"` in the "Button Design" section
part of: https://github.com/SAP/ui5-webcomponents/issues/3107#issuecomment-843032055
> docs: improve Button sample

- packages/main/test/specs/MultiComboBox.spec.js
> fix(ui5-multi-combobox): Fix failing test

- packages/main/src/ComboBox.js
- packages/main/test/specs/ComboBox.spec.js
> fix(ui5-combobox): announce selected item

- packages/main/test/samples/ColorPalette.sample.html
Updating sample to align with recommendations
> fix(ui5-color-palette): updated sample

- packages/main/src/Select.js
Now, Home and End keyboard keys are enabled.
> fix(ui5-select): enable home/end keys

- packages/main/src/Select.js
Fixes @dobrinyonkov comment in #3372.
> docs(ui5-select): add home/end button to keyboard handling section

- packages/main/src/Carousel.js
- packages/main/src/Switch.js
Document Carousel's behaviour or desktop/mobile.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/2345
Closes: https://github.com/SAP/ui5-webcomponents/issues/2345
> docs(Switch, Carousel):  improve docs

- packages/main/src/TableRow.js
- packages/main/test/specs/Table.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/3390
> fix(ui5-table-row): Prevent space when target is tr

- packages/fiori/src/UploadCollection.hbs
- packages/fiori/test/pages/FCL.html
- packages/fiori/test/pages/Wizard.html
- packages/fiori/test/pages/Wizard_test.html
- packages/fiori/test/pages/Wizard_test_mobile.html
- packages/fiori/test/samples/Wizard.sample.html
- packages/main/src/CheckBox.hbs
- packages/main/src/CheckBox.js
- packages/main/src/Label.js
- packages/main/src/RadioButton.hbs
- packages/main/src/RadioButton.js
- packages/main/src/themes/Label.css
- packages/main/test/pages/Kitchen.html
- packages/main/test/pages/Kitchen.openui5.html
- packages/main/test/pages/Label.html
- packages/main/test/pages/Panel.html
- packages/main/test/samples/Label.sample.html
- packages/main/test/samples/Panel.sample.html
- packages/main/test/specs/Components.spec.js
Part of #3107
BREAKING_CHANGE: property wrap has been renamed to wrappingType and its type has changed
> fix(ui5-label): rename wrap property to wrappingType

- packages/base/hash.txt
- packages/main/src/WheelSlider.js
- packages/main/src/themes/base/WheelSlider-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/src/themes/sap_belize/WheelSlider-parameters.css
- packages/main/src/themes/sap_belize_hcb/WheelSlider-parameters.css
- packages/main/src/themes/sap_belize_hcw/WheelSlider-parameters.css
- packages/main/src/themes/sap_fiori_3/WheelSlider-parameters.css
- packages/main/src/themes/sap_fiori_3_dark/WheelSlider-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/WheelSlider-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/WheelSlider-parameters.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/2819
The problem was, because we were using rems, and the fontsize of the test page and the playground is different, so there was some missplacement.
> fix(ui5-wheelslider): correcting the placement on mobile in different fontsizes

- packages/main/src/Icon.hbs
- packages/main/src/Icon.js
> feat(ui5-icon): add accessibility role

- packages/main/src/TreeListItem.hbs
- packages/main/src/themes/TreeListItem.css
- packages/main/test/pages/Tree.html
Fixed visual issue where `ui5-checkbox` position is not correctly when the `ui5-tree` is shrinked.
In addition now `additional-text` value is displayed correctly, since it was broken after the change of the property name.
Fixes: #3415
> fix(ui5-tree): alignment of items

- packages/main/src/themes/StepInput.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/3377
> fix(ui5-step-input): min width is now correct

- packages/main/src/Select.js
> feat(ui5-select): support angular reactive forms

- packages/main/src/themes/Button.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/3401
> fix(ui5-button): stabilizing buttons line-height

- packages/main/src/Link.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3007
> fix(ui5-link): event is now fired on space pressed

- packages/fiori/src/Bar.hbs
- packages/fiori/src/Bar.js
- packages/fiori/src/Page.js
- packages/fiori/src/themes/Page.css
- packages/fiori/test/pages/Page.html
- packages/fiori/test/samples/Page.sample.html
> feat(ui5-page): implement responsive paddings

- packages/fiori/src/SideNavigation.js
- packages/fiori/src/Wizard.js
- packages/main/src/ComboBox.js
- packages/main/src/DatePicker.js
- packages/main/src/Input.js
- packages/main/src/MultiComboBox.js
- packages/main/src/ResponsivePopover.js
- packages/main/src/Select.js
- packages/main/src/TabContainer.js
- packages/main/src/TimePickerBase.js
- packages/main/src/Tokenizer.js
- packages/main/src/features/InputSuggestions.js
- packages/main/test/pages/ColorPalette.html
- packages/main/test/pages/ResponsivePopover.html
- packages/main/test/samples/ResponsivePopover.sample.html
Part of #3107
BREAKING_CHANGE: open method renamed to openBy
> refactor(ui5-responsive-popover): API enhancements

- packages/theme-base/hash.txt
- packages/theme-base/package.json
- yarn.lock
related to: https://github.com/SAP/ui5-webcomponents/pull/3445
> chore: update sap-theming dependency to 11.1.30

- README.md
- docs/Public Module Imports.md
- packages/fiori/src/NotificationListItem.js
- packages/main/README.md
- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
- packages/main/src/RadioButton.js
- packages/main/src/themes/CustomListItem.css
- packages/main/src/themes/RadioButton.css
- packages/main/src/themes/base/RadioButton-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/src/themes/sap_belize_hcb/RadioButton-parameters.css
- packages/main/src/themes/sap_belize_hcw/RadioButton-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/RadioButton-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/RadioButton-parameters.css
- packages/main/test/pages/Components.html
- packages/main/test/pages/FormSupport.html
- packages/main/test/pages/Kitchen.html
- packages/main/test/pages/Kitchen.openui5.html
- packages/main/test/pages/List.html
- packages/main/test/pages/List_keyboard_support.html
- packages/main/test/pages/List_test_page.html
- packages/main/test/pages/RadioButton.html
- packages/main/test/pages/form.html
- packages/main/test/pages/kitchen-styles.css
- packages/main/test/samples/Label.sample.html
- packages/main/test/samples/RadioButton.sample.html
- packages/main/test/specs/DatePicker.spec.js
- packages/main/test/specs/List.spec.js
- packages/playground/lib/static-index.js
Part of #3107
BREAKING_CHANGE: component's tag name `ui5-radiobutton` has been changed to `ui5-radio-button`
> refactor(ui5-radio-button): change tag name

- packages/main/src/themes/sap_belize/parameters-bundle.css
fixes:  https://github.com/SAP/ui5-webcomponents/issues/3482
> fix(ui5-button): added belize parameters to bundle

- packages/main/src/themes/Card.css
- packages/main/src/themes/base/Card-parameters.css
- packages/main/src/themes/sap_belize_hcb/Card-parameters.css
- packages/main/src/themes/sap_belize_hcw/Card-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Card-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Card-parameters.css
- packages/theme-base/hash.txt
> fix(ui5-card): update border width and box shadow

- packages/fiori/src/ShellBar.js
- packages/fiori/test/specs/ShellBar.spec.js
Debounce the handleResize function to be executed just once in a given
interval of time.
Fixes: #3312
> fix(ui5-shellbar): fix error when there are too many resizes

- packages/main/test/specs/ComboBox.spec.js
- packages/main/test/specs/MultiComboBox.spec.js
After we update to ChromeDriver 92 some assertion start randomly failing and have been commented for the time being:
Related to: https://github.com/SAP/ui5-webcomponents/issues/3541
> chore: comment randomly failing tests

- packages/fiori/src/IllustratedMessage.js
- packages/fiori/src/themes/base/IllustratedMessage-parameters.css
- packages/fiori/src/themes/sap_belize/parameters-bundle.css
- packages/fiori/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/fiori/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3_dark/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3_hcb/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3_hcw/parameters-bundle.css
- packages/fiori/test/pages/IllustratedMessage.html
- packages/playground/build-scripts/samples-prepare.js
> fix(ui5-illustrated-message): documentation and missing parameters

- packages/fiori/src/IllustratedMessage.js
- packages/fiori/src/types/IllustrationMessageType.js
- packages/main/src/Input.js
- Fixed Typo in `IllustratedMessageType` prototype
- Use correct interface for IllustratedMessage default slot
- Add <code> tags to `ui5-input`
> docs: minor corrections for rc.15

- packages/main/src/CalendarHeader.hbs
- packages/main/src/CalendarHeader.js
- packages/main/test/specs/Calendar.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/3555
> fix(ui5-calendar): opening month/year picker by space now works correct

- packages/fiori/test/pages/NotificationListGroupItem.html
- packages/fiori/test/pages/NotificationListItem.html
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/pages/SideNavigation.html
- packages/fiori/test/samples/NotificationListGroupItem.sample.html
- packages/fiori/test/samples/NotificationListItem.sample.html
- packages/fiori/test/samples/ShellBar.sample.html
- packages/main/src/StandardListItem.hbs
- packages/main/src/themes/ListItem.css
- packages/main/test/pages/Avatar.html
- packages/main/test/pages/Button.html
- packages/main/test/samples/AvatarGroup.sample.html
Adopt the removal of "image" property in Avatar in favour of slot to display images.
- in sample and test pages
- in ListItem template
> chore: adopt Avatar API changes

- packages/base/hash.txt
- packages/base/src/util/InvisibleMessage.js
closes: https://github.com/SAP/ui5-webcomponents/issues/3582
> fix(framework): InvisibleMessage synced with framework lifecycle

- packages/main/src/SegmentedButton.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/3545
> fix(ui5-segmented-button): no longer has an error on removal

- docs/dev/Creating UI5 Web Components Packages.md
@ui5/webcomponents-tools should be a devDependency
> chore: update creating component documenation

- packages/main/src/DatePicker.js
- packages/main/test/pages/DatePicker.html
- packages/main/test/pages/DatePicker_test_page.html
- packages/main/test/specs/DatePicker.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/3516
In this change we introduce the preventable behaviour of the change  event in the DatePicker control.
This change will allow the application developers to control the whole value setting and value validation, this means that they will receive this event before we set the value and the value state and will have the possibility to prevent our setters and validators and update the value and the value state themselves.
> feat(ui5-date-picker): preventable change and input events

- packages/fiori/src/ViewSettingsDialog.js
> docs(ui5-view-settings-dialog): correct type of `sortItems` slot

- packages/fiori/src/IllustratedMessage.hbs
- packages/fiori/src/IllustratedMessage.js
- packages/fiori/test/pages/IllustratedMessage.html
- packages/fiori/test/samples/IllustratedMessage.sample.html
> feat(ui5-illustrated-message): introduce subtitle slot

- packages/main/src/Select.js
- packages/main/src/SelectPopover.hbs
By visual specification the value state message should have 32px height when it is on a single line.
#3611
> fix(ui5-select): align value state to visual specification

- packages/main/src/Calendar.hbs
- packages/main/src/Calendar.js
- packages/main/src/CalendarHeader.hbs
- packages/main/src/CalendarHeader.js
- packages/main/src/DateComponentBase.js
- packages/main/src/DayPicker.hbs
- packages/main/src/DayPicker.js
- packages/main/src/themes/CalendarHeader.css
- packages/main/src/themes/DayPicker.css
- packages/main/src/themes/base/DayPicker-parameters.css
- packages/main/src/themes/sap_fiori_3/DayPicker-parameters.css
- packages/main/src/themes/sap_fiori_3_dark/DayPicker-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/DayPicker-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/DayPicker-parameters.css
- packages/main/test/pages/Calendar.html
- packages/main/test/specs/Calendar.spec.js
feat(ui5-calendar): Calendars to support secondary calendar type
> feat(ui5-calendar): support secondary calendar type

- packages/main/src/DatePickerPopover.hbs
- packages/main/test/pages/DatePicker.html
- packages/main/test/samples/DatePicker.sample.html
> fix(ui5-datepicker): support secondary calendar type

- packages/main/src/ResponsivePopover.hbs
- packages/main/src/ResponsivePopover.js
> chore(ui5-responive-popover): implement _hideCloseButton property

- packages/fiori/src/Timeline.hbs
- packages/fiori/src/Timeline.js
fix(ui5-Timline): keyboard handling now compliant with the specification
> fix(ui5-timeline): keyboard handling is now compliant with the specification

- packages/fiori/src/IllustratedMessage.js
> fix(ui5-illustrated-message): add missing dependencies

- packages/main/src/RadioButton.hbs
- packages/main/src/themes/RadioButton.css
- packages/main/test/samples/RadioButton.sample.html
- packages/main/test/specs/RadioButton.spec.js
The cursor should be a pointer
There should be a readonly sample
The width should be correct when focus is on the radio-button
Fixes: #3622
> fix(ui5-radio-button): exploratory testing issues

- packages/main/src/CardHeader.hbs
- packages/main/src/themes/CardHeader.css
- packages/main/test/samples/Card.sample.html
Header and sub header match the direction in RTL
There are no console warnings in the Card section
Part of #3619
> fix(ui5-card): exploratory testing issues

- packages/main/src/ColorPalettePopover.js
The method is required for the ```ui5-texteditor``` component
> feat(ui5-color-palette-popover): implement isOpen method

- packages/main/src/SegmentedButton.js
> fix(ui5-segmented-button): correct focus on first click

- packages/main/src/themes/DatePickerPopover.css
> fix(ui5-date-picker): calendar horizontal center align

- packages/main/src/Card.js
- packages/main/src/CardHeader.hbs
- packages/main/src/CardHeader.js
- packages/main/src/themes/CardHeader.css
- packages/main/test/samples/Card.sample.html
Fixes the "of 10 3" issue from #3619
> fix(ui5 card): exploratory testing issues

- packages/fiori/src/themes/TimelineItem.css
- packages/main/src/themes/base/sizes-parameters.css
fix(ui5-timeline) properly aligned indicator in compact mode
> fix(ui5-timeline): align indicator in compact mode

- packages/fiori/src/WizardPopover.hbs
> fix(ui5-wizard): step titles are now visible

- packages/main/src/themes/ColorPaletteItem.css
- packages/main/src/themes/base/ColorPalette-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
fix(ui5-color-palette): align space between swatches
> fix(ui5-color-palette): align space between swatches

- packages/main/src/TextArea.js
> fix(ui5-textarea): Value state message link is accessible

- packages/main/src/Popover.js
> fix(ui5-popover): Fixed initial flickering

- packages/main/src/TimeSelection.hbs
- packages/main/src/TimeSelection.js
- packages/main/test/specs/DateTimePicker.spec.js
- packages/main/test/specs/TimePicker.spec.js
> fix(ui5-timepicker): correct navigation to the am/pm slider

- packages/main/src/ProgressIndicator.hbs
- packages/main/src/ProgressIndicator.js
- packages/main/src/themes/ProgressIndicator.css
- packages/main/test/pages/ProgressIndicator.html
- packages/main/test/samples/ProgressIndicator.sample.html
- packages/main/test/specs/ProgressIndicator.spec.js
Introducing new property "displayValue" with which we can set a custom text as value for the ProgressIndicator.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3573
Closes: https://github.com/SAP/ui5-webcomponents/issues/3573
> feat(ui5-progress-indicator): implement displayValue property

- packages/main/test/pages/RadioButton.html
- packages/main/test/samples/RadioButton.sample.html
> fix(ui5-radio-button): Fixed grouping examples accessibility

- packages/main/src/ComboBox.js
> fix(ui5-combo-box): Link in value state message is now accessible

- packages/main/src/Label.js
- packages/main/src/themes/Label.css
- packages/main/test/pages/Label.html
> fix(ui5-label): adjust colon margins

- packages/main/src/Calendar.hbs
- packages/main/src/Calendar.js
- packages/main/src/CalendarHeader.js
- packages/main/src/DateComponentBase.js
- packages/main/src/DayPicker.hbs
- packages/main/src/DayPicker.js
- packages/main/test/specs/DatePicker.spec.js
fix(ui5-calendar): ACC improvements and remove calculation from CalendarHeader
> fix(ui5-calendar): ACC improvements

- packages/main/src/Input.js
- packages/main/src/themes/ValueStateMessage.css
The padding of the value state message popup and header are fixed to reflect the Fiori specifications.
Fixes: #3611
Closes: #3611
> fix(ui5-input): adjust value state paddings according to specifications

- packages/main/src/Table.js
- packages/main/src/themes/Table.css
- packages/main/test/pages/TableSelection.html
> fix(ui5-table): Select all column is now sticky

- packages/main/src/SliderBase.js
- packages/main/test/specs/RangeSlider.spec.js
- packages/main/test/specs/Slider.spec.js
The KBH now works correctly in RTL mode. 
Fixes #3747
> fix(ui5-slider): Keyboard handling now works correct in RTL

- packages/fiori/src/WizardPopover.hbs
> fix(ui5-wizard): Grouped steps could be activated

- packages/main/src/themes/Link.css
- packages/main/src/themes/sap_belize_hcb/Link-parameters.css
- packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/Link-parameters.css
- packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
fix(ui5-link): Added underlining in the regular state in hcb / hcw
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3932
> fix(ui5-link): Added underlining in the regular state in hcb / hcw

- packages/main/src/MultiComboBox.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/specs/MultiComboBox.spec.js
> fix(ui5-multi-combobox): select an item when value matches and enter is pressed

- packages/base/hash.txt
- packages/fiori/src/Bar.hbs
- packages/fiori/src/Bar.js
- packages/fiori/src/themes/Bar.css
- packages/fiori/test/pages/Bar.html
fixes: https://github.com/SAP/ui5-webcomponents/issues/3456
> fix(ui5-bar): align of elements is now correct

- packages/main/src/themes/Label.css
This bug was caused due to a missed code line during downporting of #3897
Fixes: #3980
> fix(ui5-label): fix truncation

- packages/main/test/pages/CoreControls.html
Adding Core Controls test page
> chore: add sap_horizon test page

- packages/main/src/Dialog.js
> fix(ui5-dialog): Fixed "aria-label" text screen reading

- packages/fiori/src/Wizard.js
> fix(ui5-wizard): check if tab has a focusable element

- packages/fiori/src/Timeline.hbs
- packages/fiori/src/TimelineItem.hbs
- packages/fiori/test/specs/Timeline.spec.js
> fix(ui5-timeline): elements with role option have a parent element with role listbox

- packages/main/src/List.hbs
- packages/main/src/List.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/src/themes/List.css
- packages/main/test/pages/List_test_page.html
- packages/main/test/specs/List.spec.js
> feat(ui5-list): announce the selection mode of the list on entry

- packages/main/src/CheckBox.hbs
- packages/main/src/CheckBox.js
- packages/main/src/themes/CheckBox.css
- packages/main/src/themes/base/CheckBox-parameters.css
- packages/main/src/themes/sap_horizon/CheckBox-parameters.css
- packages/main/test/pages/CheckBox.html
Fixes: https://github.com/SAP/ui5-webcomponents/issues/404
>
> feat(ui5-checkbox): implement sap_horizon

- packages/fiori/src/FilterItem.js
- packages/fiori/src/Interfaces.js
- packages/fiori/src/ViewSettingsDialog.js
> docs(ui5-view-settings-dialog): create interfaces for slots

- packages/main/test/samples/Card.sample.html
> docs(ui5-card): Update list card samples to look well with rounded borders in SAP Horizon

- packages/main/src/Table.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/4094
> fix(ui5-table): Add missing dependency to Checkbox

- packages/fiori/src/ShellBar.js
- packages/fiori/src/themes/ShellBar.css
Fixed long title overlapping of left and right container on small screen devices.
> fix(ui5-shellbar): Fixed growing of left container

- packages/main/src/themes/DateTimePickerPopover.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/4249
> fix(ui5-datetime-picker): aligning the focus borders

- packages/main/src/themes/DatePicker.css
- packages/main/src/themes/TimePicker.css
- packages/main/src/themes/base/TimePicker-parameters.css
- packages/main/src/themes/sap_horizon/DatePicker-parameters.css
- packages/main/src/themes/sap_horizon/TimePicker-parameters.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
ui5-date-picker, ui5-date-time-picker, ui5-date-range-picker, ui5-time-picker inputs aligned to sap_horizon theme.
fixes:  https://github.com/SAP/ui5-webcomponents/issues/4266
> fix(ui5-date-picker): alignment of input controls

- docs/2-advanced/06-using-i18n-for-apps.md
- docs/2-advanced/07-accessibility.md
> docs: add accessibility documentation

- packages/main/src/TabContainer.js
> fix(ui5-tab-container): selector fixed

- packages/main/src/themes/DatePicker.css
- packages/main/src/themes/base/DatePicker-parameters.css
- packages/main/src/themes/sap_horizon/DatePicker-parameters.css
- packages/main/src/themes/sap_horizon_exp/DatePicker-parameters.css
Follow up fix for all themes + active state of normal date picker
> fix(ui5-date-picker): Hover state on readonly is now fixed

- packages/main/src/Switch.js
> chore(ui5-switch): add missing import

- packages/base/hash.txt
- packages/base/src/util/encodeXML.js
- packages/base/src/util/escapeRegex.js
- packages/base/src/util/generateHighlightedMarkup.js
- packages/ie11/hash.txt
- packages/main/src/features/InputSuggestions.js
- packages/main/test/pages/Input.html
- packages/main/test/specs/Input.spec.js
> fix(ui5-input): escape HTML before highlighting suggestions (XSS)

- packages/main/src/FileUploader.js
> fix(ui5-file-uploader): component is successfully rendered on firefox

- docs/2-advanced/07-accessibility.md
- docs/2-advanced/08-CSP.md
This article documents the recently added public APIs in `CSP.js`.
Read the article here: https://github.com/SAP/ui5-webcomponents/blob/csp-docs/docs/2-advanced/08-CSP.md
> docs: document CSP

- docs/2-advanced/08-CSP.md
@LilyanaOviPe Corrections for your comments from the last PR
@pskelin I mentioned that we deal with styles compliance only
> docs: fix CSP article

- packages/main/src/ComboBox.js
- packages/main/src/Input.js
- packages/main/src/MultiComboBox.js
- packages/main/src/TextArea.js
- packages/main/test/pages/ComboBox.html
- packages/main/test/pages/Input.html
- packages/main/test/pages/MultiComboBox.html
- packages/main/test/pages/TextArea.html
- packages/main/test/specs/ComboBox.spec.js
- packages/main/test/specs/Input.spec.js
- packages/main/test/specs/MultiComboBox.spec.js
- packages/main/test/specs/TextArea.spec.js
> fix(inputs): value state message is not presented in readonly mode

- packages/main/src/themes/sap_fiori_3_hcb/Token-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Token-parameters.css
> fix(ui5-token): border-radius adjusted to spec in SAP Quartz HCB/HCW

- packages/main/src/Input.js
- packages/main/src/InputPopover.hbs
- packages/main/src/MultiComboBox.js
- packages/main/src/MultiComboBoxPopover.hbs
> fix(ui5-input, ui5-multi-combobox): value state popup now aligned properly in RTL mode

- packages/main/src/DayPicker.js
- packages/main/src/themes/DatePickerPopover.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/4260
> fix(ui5-date-picker): Align day names in hide-week-numbers mode

- packages/main/src/themes/RatingIndicator.css
> fix(ui5-rating-indicator): not round values are correctly visualised in RTL mode

- packages/base/src/Device.js
- packages/main/src/Popover.js
- packages/main/test/pages/Dialog.html
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3847
> fix(ui5-popover): adjust top position when iOS keyboard is opened

- packages/main/src/themes/Dialog.css
> fix(ui5-dialog): correct border radius when stretched on phones

- packages/main/src/Dialog.hbs
- packages/main/src/Dialog.js
> fix(ui5-dialog): resize handle is no longer shown on phones

- packages/main/test/samples/Carousel.sample.html
> fix(ui5-carousel): Playground example is fixed

- packages/main/src/Input.js
- packages/main/src/InputPopover.hbs
- packages/main/src/features/InputSuggestions.js
- packages/main/test/specs/Input.spec.js
> fix(ui5-input) Prevent duplicating focus on group header click

- packages/fiori/test/pages/styles/UploadCollection.css
- packages/fiori/test/samples/UploadCollection.sample.html
> fix(ui5-upload-collection): buttons are now visible on small screens

- packages/fiori/src/UploadCollectionItem.js
- packages/fiori/src/themes/UploadCollectionItem.css
> fix(ui5-upload-collection): removed active and hover states

- packages/fiori/src/themes/NotificationListGroupItem.css
- packages/fiori/src/themes/NotificationListItem.css
- "collapse" arrow is now pointing down in RTL
- buttons and status icons are correctly aligned in RTL
- background is not switching to blue when user taps (on touch device)
Fixes #4255
Fixes #4256
Fixes #4257
> fix(ui5-li-notification-group): visual fixes for right-to-left mode

- packages/main/src/themes/CheckBox.css
> fix(ui5-checkbox): cursor style when disabled

- packages/main/src/themes/Badge.css
> fix(ui5-badge): center text vertically

- packages/main/src/themes/RadioButton.css
> fix(ui5-radio-button): removed cursor pointer on hover for disabled state

- packages/main/src/SegmentedButton.hbs
- packages/main/src/SegmentedButton.js
- packages/main/test/samples/SegmentedButton.sample.html
> feat(ui5-segmented-button): accessibleName property implemented

- packages/fiori/src/Wizard.hbs
- packages/fiori/src/Wizard.js
- packages/fiori/test/specs/Wizard.spec.js
> fix(ui5-wizard): announce active step when navigating via a button (#4298)

- packages/main/src/SegmentedButton.hbs
- packages/main/src/SegmentedButton.js
- packages/main/test/samples/SegmentedButton.sample.html
> feat(ui5-segmented-button): implement accessibleName property

- docs/3-customizing/01-theme.md
> fix(playground): fix broken links

- packages/main/src/RatingIndicator.js
- packages/main/test/pages/RatingIndicator.html
- packages/main/test/specs/RatingIndicator.spec.js
The keyboard specification for RatingIndicator is now fully adopted.
> feat(ui5-rating-indicator): add full keyboard support

- packages/fiori/test/samples/Wizard.sample.html
> fix(ui5-wizard): make playground sample fully usable

- packages/main/src/Table.hbs
- packages/main/src/Table.js
- packages/main/test/specs/Table.spec.js
> fix(ui5-table): check select all checkbox, when all rows are selected programatically

- packages/main/src/SliderBase.hbs
- packages/main/src/SliderBase.js
- packages/main/src/themes/SliderBase.css
> fix(ui5-slider, ui5-range-slider): remove focus outline on mobile

- packages/fiori/src/DynamicSideContent.js
- packages/playground/build-scripts/samples-prepare.js
- fix es6 module import
- mark as new
> docs(ui5-dynamic-side-content): fix ES6 module import in docs

- packages/main/test/samples/Card.sample.html
- packages/playground/assets/css/api.css
> fix(ui5-card): adjust some classes in Playground samples

- packages/main/src/MultiComboBox.js
> fix(ui5-multi-combobox): make readonly component focusable on mobile device

- packages/main/src/themes/Token.css
- packages/main/src/themes/base/Token-parameters.css
- packages/main/src/themes/sap_belize_hcb/Token-parameters.css
- packages/main/src/themes/sap_belize_hcw/Token-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Token-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Token-parameters.css
> fix(ui5-token): apply correct background color in HC themes

- packages/main/test/samples/MultiInput.sample.html
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3765
> docs(ui5-multi-input):  Improved samples

- packages/main/src/Panel.hbs
- packages/main/src/themes/Panel.css
> fix(ui5-panel): rotate button counterclockwise in RTL mode

- packages/main/test/samples/Input.sample.html
> fix(ui5-input): improve sample visualization

- packages/main/src/TextArea.js
- packages/main/src/themes/BrowserScrollbar.css
- packages/main/src/themes/base/BrowserScrollbar-parameters.css
- packages/main/src/themes/sap_belize/BrowserScrollbar-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcb/BrowserScrollbar-parameters.css
- packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/BrowserScrollbar-parameters.css
- packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
- packages/main/src/themes/sap_horizon_exp/parameters-bundle.css
As part of the change, the BrowserScrollbar styles are adjusted according to the visual specification.
FIXES: #3845
> fix(ui5-textarea): apply specified scrollbar stylings

- packages/main/src/ListItem.hbs
- packages/main/src/Tree.hbs
- packages/main/src/TreeItem.js
- packages/main/src/TreeListItem.js
- packages/main/test/pages/Tree.html
> feat(ui5-tree-item): add indeterminate state

- packages/fiori/src/Wizard.js
- packages/fiori/src/themes/Wizard.css
FIXES: https://github.com/SAP/ui5-webcomponents/issues/3612
> fix(ui5-wizard): adjust content and navigator paddings based on spec

- packages/fiori/src/Bar.hbs
- packages/fiori/src/Bar.js
- packages/fiori/src/themes/Bar.css
fix(ui5-bar): add rtl mode supported
> fix(ui5-bar): add rtl mode supported

- packages/fiori/src/SideNavigation.js
- packages/fiori/src/themes/SideNavigation.css
- packages/fiori/src/themes/SideNavigationPopover.css
> fix(ui5-side-navigation): correct styles for static area

- packages/main/test/samples/ResponsivePopover.sample.html
- packages/playground/assets/css/api.css
The sample popover had 300px width.
Part of #4206
> fix(ui5-popover): make sample responsive for small devices

- packages/main/src/Dialog.js
- packages/main/src/Popover.js
- packages/main/src/Popup.js
- packages/main/src/ResponsivePopover.hbs
- packages/main/test/pages/Dialog.html
- packages/main/test/pages/Popover.html
- packages/main/test/pages/ResponsivePopover.html
- packages/main/test/specs/Dialog.spec.js
- packages/main/test/specs/Popover.spec.js
Affects Dialog, Popover and ResponsivePopover.
> feat(ui5-popup): add accessibleNameRef property

- packages/main/src/Option.js
- packages/main/src/Select.js
- packages/main/src/SelectPopover.hbs
> feat(ui5-option): title attribute handle

- packages/base/hash.txt
- packages/main/src/themes/base/Card-parameters.css
- packages/main/src/themes/sap_horizon/Card-parameters.css
The parameter for the border-radius has been updated to use sapElement_BorderCornerRadius.
> fix(ui5-card): update theming parameter

- packages/main/test/samples/MultiComboBox.sample.html
> doc(ui5-multi-combo-box): improved playground sample

- packages/main/src/CheckBox.hbs
- packages/main/src/CheckBox.js
- packages/main/test/pages/CheckBox.html
- packages/main/test/specs/CheckBox.spec.js
Fixes: #4500
Added `accessible-name` and `accessible-name-ref` properties.
> feat(ui5-checkbox): accessibleName and accessibleNameRef implemented

- docs/2-advanced/07-accessibility.md
- packages/main/src/Icon.js
- packages/main/test/pages/Icon.html
- packages/main/test/specs/Icon.spec.js
> feat(ui5-icon): accessibleRole property implemented

- packages/main/test/pages/Breadcrumbs.html
Cleanup test page from obsolete code.
> fix(ui5-breadcrumbs): remove obsolete attribute from test page

- packages/fiori/src/ViewSettingsDialog.hbs
- packages/fiori/src/ViewSettingsDialog.js
- packages/fiori/test/pages/ViewSettingsDialog.html
- packages/fiori/test/specs/ViewSettingsDialog.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/4371
> fix(ui5-view-settings-dialog): Implement single page functionality

- packages/fiori/src/MediaGallery.js
Added description, KBH details and reference to the ui5-media-gallery-item.
> docs(ui5-media-gallery): improve overview section

- packages/base/hash.txt
- packages/base/src/Keys.js
- packages/main/bundle.common.js
- packages/main/src/SplitButton.hbs
- packages/main/src/SplitButton.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/src/themes/SplitButton.css
- packages/main/test/pages/SplitButton.html
- packages/main/test/pages/styles/SplitButton.css
- packages/main/test/samples/SplitButton.sample.html
- packages/main/test/specs/SplitButton.spec.js
- packages/theming/hash.txt
Related to: https://github.com/SAP/ui5-webcomponents/issues/1436
> feat(ui5-split-button): initial implementation

- packages/create-package/index.js
- packages/fiori/src/MediaGallery.js
- packages/main/src/Icon.js
- packages/main/src/SplitButton.js
- packages/main/test/samples/ColorPalettePopover.sample.html
- packages/playground/build-scripts/samples-prepare.js
- packages/playground/docs/landing-page.html
Related to: https://github.com/SAP/ui5-webcomponents/issues/4608
> chore: fix js docs issues

- packages/fiori/src/MediaGalleryItem.js
> fix(ui5-media-gallery-item): correct initialization order

- packages/main/src/ColorPalettePopover.js
- packages/main/test/pages/ColorPalettePopover.html
- packages/main/test/samples/ColorPalettePopover.sample.html
Deprecate openPopover in favour of "showAt" to be consistent with Popover, ResponsivePopover
> refactor(ui5-color-palette-popover): deprecate openPopover

- packages/base/hash.txt
- packages/base/src/Device.js
> fix: fix ipad recognition

- packages/main/src/Switch.hbs
- packages/main/test/specs/Switch.spec.js
> fix(ui5-switch): change switch role to role checkbox

- packages/main/src/Table.js
- packages/main/src/TableColumn.js
> chore(ui5-table): cleanup code

- packages/base/hash.txt
- packages/main/src/themes/base/Badge-parameters.css
The text color of the badge was updated to the latest Fiori 3
specification.
#3940
> fix(ui5-badge): update color-scheme parameters

- packages/main/src/themes/TableRow.css
FIXES: https://github.com/SAP/ui5-webcomponents/issues/4544
> fix(ui5-table-row): align checkbox vertically

- packages/base/hash.txt
- packages/main/src/SliderBase.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/4478
> fix(ui5-slider): sets correct color to tickmarks based on theme

- packages/main/src/MultiComboBox.js
Before implementing the full keyboard specifications I did a small refactoring of already existing keyboard handling logic for a better base.
> refactor(ui5-multi-combobox): Optimize existing MultiComboBox keyboard handling code

- packages/main/src/MultiComboBox.js
- packages/main/test/pages/MultiComboBox.html
- packages/main/test/specs/MultiComboBox.spec.js
Issue #3090
Note: The value is not tokenized on TAB as there is still no 'type ahead' implemented. It will be added in another change.
> feat(ui5-multi-combobox) Implement tab navigation

- packages/main/test/samples/TabContainer.sample.html
> docs(ui5-tabcontainer): edit texts in sample

- packages/main/src/themes/base/SliderBase-parameters.css
> fix(ui5-slider): prevent handle's jumping on focus

- packages/base/hash.txt
- packages/main/src/Label.js
- packages/main/test/pages/Label.html
- packages/main/test/pages/modules/LabelPageCustomElement.js
- packages/main/test/specs/Label.spec.js
> fix(ui5-label): allow focusing elements linked with for attribute inside a shadow root

- packages/main/src/RatingIndicator.hbs
- packages/main/test/specs/RatingIndicator.spec.js
> feat(ui5-rating-indicator): Accessibility enhancements

- packages/main/src/TextArea.hbs
- packages/main/test/specs/Input.spec.js
- packages/main/test/specs/TextArea.spec.js
> fix(ui5-textarea): enhance aria-invalid attribute handling

- packages/fiori/src/themes/Wizard.css
> fix(ui5-wizard): prevent unnecessary content scrolling

- packages/main/src/ComboBox.js
> fix(ui5-combobox): prevent dropdown closing on scroll

- packages/main/src/MultiComboBox.js
- packages/main/test/pages/MultiComboBox.html
- packages/main/test/specs/MultiComboBox.spec.js
> fix(ui5-multi-combobox): add value selection on focus

- packages/main/src/MultiComboBox.js
- packages/main/test/specs/MultiComboBox.spec.js
CTRL+A selects/deselects all (filtered) items.
Issue: #3090
> feat(ui5-multi-combobox): Implement 'Select All' functionality

- packages/main/src/TabContainer.js
- packages/main/src/TabContainerPopover.hbs
- packages/main/src/i18n/messagebundle.properties
> fix(ui5-tabcontainer): replace hardcoded text

- packages/fiori/src/MediaGallery.js
- packages/fiori/src/ViewSettingsDialog.js
- packages/main/src/Breadcrumbs.js
- packages/main/src/Calendar.js
- packages/main/src/ComboBox.js
- packages/main/src/FileUploader.js
- packages/main/src/ProgressIndicator.js
- packages/main/src/RangeSlider.js
- packages/main/src/SegmentedButtonItem.js
- packages/main/src/Slider.js
- packages/main/src/SplitButton.js
- packages/main/src/TableRow.js
- packages/main/src/TextArea.js
- packages/main/src/Tokenizer.js
- packages/main/src/features/InputSuggestions.js
- packages/tools/lib/scoping/missing-dependencies.js
- packages/tools/lib/scoping/report-tags-usage.js
- describe dependencies
- do not check tag name, but attribute
> fix: correct scoping issues with several components

- packages/main/src/MultiComboBox.js
- packages/main/src/Tokenizer.js
- packages/main/test/specs/MultiComboBox.spec.js
Issue: #3090
MultiComboBox:
CTRL + Home/End handling;
Tokenizer:
CTRL + Home/End handling;
SHIFT +Home/End handling;
> feat(ui5-multi-combobox, ui5-tokenizer): Full Home/End implementation

- packages/main/src/ResponsivePopover.hbs
- packages/main/src/ResponsivePopover.js
> fix(ui5-responsive-popover): Fixed auto close during re-rendering

- packages/main/src/MultiComboBox.js
> fix(ui5-multi-combobox): Prevent scrolling on page up/down

- packages/main/src/TabContainer.js
> fix(ui5-tabcontainer): Fixed overflow button visibility

- packages/fiori/src/ViewSettingsDialog.hbs
- packages/fiori/src/ViewSettingsDialog.js
- packages/main/src/List.js
> fix(ui5-view-settings-dialog): fixing comments from previous commit

- packages/main/src/Select.hbs
- packages/main/src/Select.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/specs/Select.spec.js
> feat(ui5-select): add aria-roledescription attribute

- packages/playground/_sass/layout.scss
- packages/playground/_sass/search.scss
- packages/playground/assets/js/playground.js
- packages/theming/hash.txt
> fix(playground): fix search results

- packages/main/src/CheckBox.hbs
- packages/main/src/themes/CheckBox.css
- packages/main/src/themes/base/CheckBox-parameters.css
- packages/main/src/themes/sap_horizon_exp/CheckBox-parameters.css
SAP Horizon Experimental theme implementation for Checkboxes.
Theme name: **sap_horizon_exp**
> feat(ui5-checkbox): implement sap_horizon_exp theme

- packages/main/test/samples/Card.sample.html
> docs(ui5-card): Use standard list items in sample

- packages/main/src/ColorPicker.hbs
- packages/main/src/ColorPicker.js
- packages/main/src/themes/ColorPicker.css
> fix(ui5-color-picker): rtl support

- packages/main/src/themes/ColorPalette.css
- packages/main/src/themes/ColorPalettePopover.css
- packages/main/src/themes/base/sizes-parameters.css
> fix(ui5-color-palette): Adapt components with responsive paddings

- packages/main/src/DateTimePicker.js
- packages/main/src/DateTimePickerPopover.hbs
- packages/main/src/themes/Calendar.css
- packages/main/src/themes/DateTimePickerPopover.css
> fix(ui5-datetime-picker): Adapt components with responsive paddings

- packages/main/src/Option.js
- packages/main/src/Select.js
- packages/main/src/SelectPopover.hbs
- packages/main/test/pages/Select.html
- packages/main/test/samples/Select.sample.html
- packages/main/test/specs/Select.spec.js
Proposed implementation for #4999
> feat(ui5-option): add additional-text property

- packages/main/src/Tab.js
> fix(ui5-tabcontainer): add missing dependency in Tab

- packages/main/src/Link.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/4963
> fix(ui5-link): remove double click event

- packages/main/src/themes/Panel.css
- packages/main/src/themes/base/Panel-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/src/themes/sap_belize/Panel-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/Panel-parameters.css
- packages/main/src/themes/sap_fiori_3/Panel-parameters.css
- packages/main/src/themes/sap_fiori_3_dark/Panel-parameters.css
- packages/main/src/themes/sap_horizon/Panel-parameters.css
- packages/main/src/themes/sap_horizon_dark/Panel-parameters.css
- packages/main/src/themes/sap_horizon_exp/Panel-parameters.css
- packages/main/src/themes/sap_horizon_hcb/Panel-parameters.css
- packages/main/src/themes/sap_horizon_hcw/Panel-parameters.css
- existing themes adjustments
- implementation of Horizon themes
Related to: #5007
> feat(ui5-panel): implement SAP Horizon themes

- packages/fiori/src/themes/base/FlexibleColumnLayout-parameters.css
- packages/fiori/src/themes/sap_fiori_3_dark/FlexibleColumnLayout-parameters.css
- packages/fiori/src/themes/sap_fiori_3_dark/parameters-bundle.css
> feat(ui5-fcl): implement Horizon theme

- packages/fiori/src/FlexibleColumnLayout.hbs
- packages/fiori/src/Timeline.hbs
- packages/fiori/src/ViewSettingsDialog.hbs
- packages/fiori/src/themes/FlexibleColumnLayout.css
- packages/fiori/src/themes/Timeline.css
- packages/fiori/src/themes/ViewSettingsDialog.css
- packages/main/src/CalendarHeader.hbs
- packages/main/src/Card.hbs
- packages/main/src/CardHeader.hbs
- packages/main/src/themes/Button.css
- packages/main/src/themes/CalendarHeader.css
- packages/main/src/themes/CardHeader.css
- packages/main/src/themes/base/rtl-parameters.css
- Where possible CSS Logical properties are replacing RTL specific stlyes
- Where not possible to use CSS Logical properties - we extract the values as CSS vars to rtl-parameters.css
> refactor(ui5-vsd, ui5-timeline, ui5-card-header, ui5-calendar-header): make use of CSS Logical properties to implement RTL

- packages/main/src/themes/Suggestions.css
- packages/main/src/themes/ValueStateMessage.css
- packages/main/src/themes/base/Suggestions-parameters.css
- packages/main/src/themes/base/ValueStateMessage-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
- packages/main/src/themes/sap_horizon/Suggestions-parameters.css
- packages/main/src/themes/sap_horizon/ValueStateMessage-parameters.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
- packages/main/src/themes/sap_horizon_dark/Suggestions-parameters.css
- packages/main/src/themes/sap_horizon_dark/ValueStateMessage-parameters.css
- packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcb/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcw/parameters-bundle.css
Focus outline of first/last suggestion, value state header and group header is not rounded anymore.
Related to: #5007
> feat(inputs): adjust dropdowns according to Horizon themes specification

- packages/main/src/Tokenizer.hbs
- packages/main/src/Tokenizer.js
- packages/main/src/TokenizerPopover.hbs
- packages/main/src/themes/MultiComboBox.css
- packages/main/src/themes/MultiInput.css
- packages/main/src/themes/Token.css
- packages/main/src/themes/Tokenizer.css
- packages/main/src/themes/base/Token-parameters.css
- packages/main/src/themes/base/Tokenizer-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/src/themes/sap_belize/Token-parameters.css
- packages/main/src/themes/sap_belize/Tokenizer-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/Token-parameters.css
- packages/main/src/themes/sap_fiori_3/Token-parameters.css
- packages/main/src/themes/sap_fiori_3_dark/Token-parameters.css
- packages/main/src/themes/sap_horizon/Token-parameters.css
- packages/main/src/themes/sap_horizon/Tokenizer-parameters.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
- packages/main/src/themes/sap_horizon_dark/Token-parameters.css
- packages/main/src/themes/sap_horizon_dark/Tokenizer-parameters.css
- packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
- packages/main/src/themes/sap_horizon_exp/Token-parameters.css
- packages/main/src/themes/sap_horizon_hcb/Token-parameters.css
- packages/main/src/themes/sap_horizon_hcw/Token-parameters.css
> feat(ui5-token): implement Horizon themes

- packages/main/src/themes/FileUploader.css
- packages/main/src/themes/base/FileUploader-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcb/FileUploader-parameters.css
- packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/FileUploader-parameters.css
- packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcb/FileUploader-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcw/FileUploader-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
- packages/main/src/themes/sap_horizon/FileUploader-parameters.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
- packages/main/src/themes/sap_horizon_dark/FileUploader-parameters.css
- packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcb/FileUploader-parameters.css
- packages/main/src/themes/sap_horizon_hcb/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcw/FileUploader-parameters.css
- packages/main/src/themes/sap_horizon_hcw/parameters-bundle.css
CSS parameters have been applied in the component's CSS files for Horizon/Horizon Dark/Horizon HCB/Horizon HCW themes
related to: https://github.com/SAP/ui5-webcomponents/issues/5009
> feat(ui5-file-uploader): implement SAP Horizon theme parameters

- packages/main/src/Menu.hbs
- packages/main/src/themes/Menu.css
- packages/main/src/themes/base/Menu-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
- packages/main/src/themes/sap_horizon/Menu-parameters.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
- packages/main/src/themes/sap_horizon_dark/Menu-parameters.css
- packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcb/Menu-parameters.css
- packages/main/src/themes/sap_horizon_hcb/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcw/Menu-parameters.css
- packages/main/src/themes/sap_horizon_hcw/parameters-bundle.css
Implementation of the Horizon theme (Morning, Evening, HCB/HCW) for ui5-menu web component.
> feat(ui5-menu): implement Horizon theme

- packages/main/src/themes/ColorPaletteItem.css
- packages/main/src/themes/base/ColorPalette-parameters.css
- packages/main/src/themes/sap_horizon/ColorPalette-parameters.css
- packages/main/src/themes/sap_horizon/sizes-parameters.css
- packages/main/src/themes/sap_horizon_dark/ColorPalette-parameters.css
- packages/main/src/themes/sap_horizon_dark/sizes-parameters.css
Implementation of the Horizon theme (Morning, Evening, HCB/HCW) for ui5-color-palette web component.
> feat(ui5-color-palette): implement Horizon theme

- packages/main/src/themes/TextArea.css
- packages/main/src/themes/base/TextArea-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/TextArea-parameters.css
- packages/main/src/themes/sap_horizon_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_horizon_hcw/TextArea-parameters.css
> fix(ui5-textarea): adjust focus outline offset

- packages/fiori/src/themes/TimelineItem.css
- packages/fiori/src/themes/base/TimelineItem-parameters.css
- packages/fiori/src/themes/sap_horizon/TimelineItem-parameters.css
- packages/fiori/src/themes/sap_horizon_dark/TimelineItem-parameters.css
Implementation of the Horizon theme (Morning, Evening) for ui5-timeline web component.
> feat(ui5-timeline): implement Horizon theme

- packages/main/src/ColorPaletteDialog.hbs
- packages/main/src/themes/ColorPalette.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/4976
> fix(ui5-color-palette): align buttons to spec

- packages/main/src/themes/SelectPopover.css
> fix(ui5-select): correct Horizon popover styles

- packages/main/src/themes/AvatarGroup.css
- packages/main/src/themes/base/AvatarGroup-parameter.css
- packages/main/src/themes/base/AvatarGroup-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
- packages/main/src/themes/sap_horizon/AvatarGroup-parameters.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
- packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcb/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcw/parameters-bundle.css
- packages/main/test/pages/AvatarGroup.html
- packages/main/test/pages/styles/AvatarGroup.css
> feat(ui5-avatar-group): implement Horizon theme

- packages/base/src/features/F6Navigation.js
> fix(f6navigation): fix keydown events for all inputs

- packages/main/test/specs/DatePicker.spec.js
Issue has been created to investigate the failing test https://github.com/SAP/ui5-webcomponents/issues/5203
> chore: comment DatePicker test failing often on travis

- packages/main/src/MultiComboBox.hbs
- packages/main/src/MultiComboBox.js
- packages/main/test/pages/MultiComboBox.html
- packages/main/test/specs/MultiComboBox.spec.js
> feat(ui5-multi-combobox): add "accessibleName" and "accessibleNameRef" properties

- packages/main/src/Breadcrumbs.hbs
> fix(ui5-breadcrumbs): set aria-current to the focused element

- packages/main/src/Input.js
> fix(ui5-input): adjust maxLength property documentation

- packages/fiori/src/themes/Page.css
> fix(ui5-page): remove unnecessary scrollbar

- packages/main/src/Select.js
- packages/main/src/SelectPopover.hbs
- packages/main/test/pages/Select.html
> fix(ui5-select): correct picker width

- packages/fiori/src/themes/TimelineItem.css
> fix(ui5-timeline-item): align text in title link

- packages/base/bundle.esm.js
- packages/fiori/src/FlexibleColumnLayout.js
- packages/fiori/src/NotificationListItem.hbs
- packages/fiori/src/NotificationListItem.js
- packages/fiori/src/themes/FlexibleColumnLayout.css
- packages/fiori/src/themes/NotificationListItem.css
- packages/main/bundle.common.js
- packages/main/src/BusyIndicator.js
- packages/main/src/ColorPicker.js
- packages/main/src/DatePicker.js
- packages/main/src/DatePickerPopover.hbs
- packages/main/src/Input.js
- packages/main/src/List.js
- packages/main/src/MultiComboBox.js
- packages/main/src/SegmentedButton.js
- packages/main/src/Table.js
- packages/main/src/TextArea.js
- packages/main/src/TimeSelection.hbs
- packages/main/src/TimeSelection.js
- packages/main/src/TreeListItem.js
- packages/main/src/themes/BusyIndicator.css
> refactor: cleanup IE code part 2: isIE

- packages/main/src/DateTimePicker.js
- packages/main/test/pages/DateTimePicker.html
- packages/main/test/specs/DateTimePicker.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/4684
fixes: https://github.com/SAP/ui5-webcomponents/issues/5121
> feat(ui5-datetime-picker): make change events preventable

- packages/main/src/MultiComboBox.js
- packages/main/src/MultiComboBoxPopover.hbs
- packages/main/test/pages/MultiComboBox.html
- packages/main/test/specs/MultiComboBox.mobile.spec.js
- packages/main/test/specs/MultiComboBox.spec.js
implement type ahead (autocomplete)
Related to #3488
> feat(ui5-multi-combobox): implement type ahead (autocomplete)

- packages/main/src/themes/sap_horizon/CheckBox-parameters.css
- packages/main/src/themes/sap_horizon_dark/CheckBox-parameters.css
- packages/main/src/themes/sap_horizon_hcb/CheckBox-parameters.css
- packages/main/src/themes/sap_horizon_hcw/CheckBox-parameters.css
> fix(ui5-checkbox): correct label color in Horizon

- packages/main/src/SliderBase.hbs
- packages/main/src/themes/ColorPicker.css
- packages/main/src/themes/SliderBase.css
- packages/main/src/themes/base/SliderBase-parameters.css
- packages/main/test/specs/RangeSlider.spec.js
> fix(ui5-slider, ui5-range-slider): adjust padding to spec

- packages/main/src/themes/Link.css
- packages/main/test/pages/Link.html
fixes: https://github.com/SAP/ui5-webcomponents/issues/5267, https://github.com/SAP/ui5-webcomponents/issues/5218
> fix(ui5-link): enable overstyling

- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/themes/ShellBar.css
Fixes: https://github.com/SAP/ui5-webcomponents/issues/5332
> fix(ui5-shellbar): correct accessibility DOM

- docs/2-advanced/07-accessibility.md
> fix: document new accessibility properties

- docs/2-advanced/07-accessibility.md
> fix(ui5-shellbar): document new accessibility property

- packages/base/README.md
- packages/main/README.md
Related to: https://github.com/SAP/ui5-webcomponents/issues/5381
> docs: update public imports info

- .husky/post-checkout
- .husky/post-merge
- .husky/post-rewrite
- package.json
- yarn.lock
add git hooks via husky, to check whether the lock file is changed and automatically run `yarn`
> chore: add yarnhooks for automatic updates

- packages/main/src/ComboBox.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/specs/ComboBox.spec.js
> fix(ui5-combobox): annouce group item's text when accessed via keyboard

- packages/main/src/StandardListItem.js
- packages/main/src/SuggestionItem.js
- packages/main/src/TreeItem.js
- packages/main/src/TreeListItem.js
> docs: fix typo

- docs/2-advanced/07-accessibility.md
- packages/playground/docs/landing-page.html
Added limitation note for Windows High Contrast mode
> docs: add a11y limitation note

- packages/main/src/Table.hbs
> fix(ui5-table): render selectAll checkbox only in case ui5-table is not empty

- packages/main/test/pages/ComboBox.html
- packages/main/test/pages/Input.html
- packages/main/test/pages/MultiComboBox.html
- packages/main/test/pages/MultiInput.html
- packages/main/test/specs/ComboBox.mobile.spec.js
- packages/main/test/specs/Input.mobile.spec.js
- packages/main/test/specs/MultiComboBox.mobile.spec.js
- packages/main/test/specs/MultiInput.mobile.spec.js
Adding mobile tests for 
- ui5-input
- ui5-combobox
> test: adding mobile tests

- packages/main/src/RadioButton.js
- packages/main/test/pages/RadioButton.html
- packages/main/test/specs/RadioButton.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/5165
> fix(ui5-radio-button): correct keyboard navigation in RTL

- packages/main/src/Panel.hbs
- packages/main/src/themes/Panel.css
- packages/main/test/specs/Panel.spec.js
> fix(ui5-panel): add tooltip to expand/collapse icon

- packages/main/src/Select.js
- packages/main/test/pages/Select.html
- packages/main/test/specs/Select.spec.js
> fix(ui5-select): announce value state type

- packages/main/src/themes/Input.css
- packages/main/src/themes/base/Input-parameters.css
- packages/main/src/themes/sap_belize_hcb/Input-parameters.css
- packages/main/src/themes/sap_belize_hcw/Input-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Input-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Input-parameters.css
- packages/main/src/themes/sap_horizon_hcb/Input-parameters.css
- packages/main/src/themes/sap_horizon_hcw/Input-parameters.css
> fix(inputs): adjust placeholder styling

- packages/main/src/RadioButton.js
> feat(ui5-radio-button): add accessibleName property

- packages/fiori/src/Bar.js
- packages/fiori/test/pages/Bar.html
fixes: https://github.com/SAP/ui5-webcomponents/issues/4901
> feat(ui5-bar): implement resize handlers for each slot

- packages/main/src/Badge.js
- packages/main/src/Interfaces.js
With this change, `ui5-badge` is defined as a component that may be nested in a `badge` slot.
To implement badge support (e.g. for `ui5-button`):
1. Define a `badge` slot:
`packages/main/src/Button.js`:
```js
slots: /** @lends sap.ui.webcomponents.main.Button.prototype */ {
/**
* Defines the optional <code>ui5-badge</code> that will be used.
*
* @type {sap.ui.webcomponents.main.IBadge}
* @slot
* @public
* @since 1.5.0
*/
badge: {
type: HTMLElement,
},
}
```
2. Same as above, for the Handlebars template:
`packages/main/src/Button.hbs`:
```html
<button>
...
<slot name="badge"></slot>
...
</button>
```
3. Use the `::slotted([ui5-badge][slot="badge"])` selector to apply styles:
`packages/main/src/themes/Button.css`:
```css
::slotted([ui5-badge][slot="badge"]) {
min-width: 1rem;
background: …
```
> chore(ui5-badge): implement IBadge interface

- packages/main/src/Button.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/5386
> fix(ui5-button): announce is now correct when button is icon only with tooltip

- packages/main/src/Menu.js
- packages/main/src/MenuItem.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/5557
> docs(ui5-menu): improve documentation

- packages/main/src/Input.js
> fix(ui5-input): additional check added for robustness

- packages/main/src/Dialog.hbs
- packages/main/src/Dialog.js
- packages/main/src/Popup.hbs
- packages/main/src/Popup.js
- packages/main/src/themes/Dialog.css
- packages/main/src/themes/base/Dialog-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Dialog-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Dialog-parameters.css
- packages/main/src/themes/sap_horizon_hcb/Dialog-parameters.css
- packages/main/src/themes/sap_horizon_hcw/Dialog-parameters.css
- packages/main/test/pages/Dialog.html
- packages/main/test/samples/Dialog.sample.html
- packages/main/test/specs/Dialog.spec.js
Dialogs now support the alertdialog role according to their state property
> feat(ui5-dialog): add state property

- packages/main/src/List.js
- packages/main/src/Tree.js
- packages/main/test/pages/Tree.html
- packages/main/test/specs/Tree.spec.js
> fix(ui5-tree): include `targetItem` in `selection-change` event

- packages/main/src/Input.js
- packages/main/test/pages/Input.html
- packages/main/test/specs/Input.spec.js
Fixes: #5635
Related to: #5157 #5260 #3732 #4340
> fix(ui5-input): correction of change event

- packages/main/src/themes/MonthPicker.css
- packages/main/src/themes/YearPicker.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/5644
> fix(ui5-calendar): align year and month picker focus to horizon
