UI5/webcomponents

- packages/fiori/src/NotificationListGroupItem.js
- packages/fiori/src/NotificationListItem.js
- packages/fiori/src/ShellBar.js
- packages/main/src/Button.js
- packages/main/src/Card.js
- packages/main/src/MultiComboBox.js
- packages/main/src/Slider.hbs
- packages/main/src/Slider.js
- packages/main/src/StandardListItem.js
- packages/main/src/SuggestionListItem.js
- packages/main/src/Switch.js
- packages/main/src/TableCell.js
- packages/main/src/TableColumn.js
- packages/main/src/TableRow.js
- packages/main/src/TextArea.js
- packages/main/src/TreeListItem.js
Fixes #3082
BREAKING_CHANGE: The following Slider CSS parts have been renamed:
- ```slider-progress``` -> ```progress-bar```
- ```slider-handle``` -> ```handle```
> docs: add docs for css parts

- packages/main/test/specs/Select.spec.js
Fxes: #3000 
Sample page is reloaded for tests that rely on global state (the #mySelect ref).
Additionally: 
- Тests take into account the port on which the sample page runs.
> fix(ui5-select): avoid global state in test spec

- packages/fiori/src/Page.js
We had feedback in one of the Slack channels that the content will start with an offset even when the "header" slot is not present. And this is what we address here - setting "2.75rem" top offset to the content in case the Page has a header.
> chore(ui5-page): offset content top when header exists

- packages/fiori/src/Wizard.js
- packages/fiori/src/i18n/messagebundle.properties
- "Optional" text added to the aria-label attribute of the step is now translated.
> fix(ui5-wizard): translate optional step text

- packages/fiori/src/themes/ShellBar.css
The notification bubble used to remain displayed when notification-count is an empty string
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3121
> fix(ui5-shellbar): hide notification bubble if empty str

- packages/main/src/Input.js
- packages/main/src/MultiInput.js
- packages/main/test/specs/Input.spec.js
- packages/main/test/specs/MultiInput.spec.js
On accessing the ui5-input web component, the suggestions count should not be read out.
It is expected to be read out, once the suggestions are opened or after entering a value.
FIXES: #3051
> fix(ui5-input): Suggestions count is read out when expected

- packages/main/src/List.js
- packages/main/test/pages/List_test_page.html
- packages/main/test/specs/List.spec.js
This is a change already merged in release-0.29, because of a tight deadline, set by stakeholders. Now we ensure that the issue is fixed in the future versions. The commit  in the release-0.29 branch is the following: https://github.com/SAP/ui5-webcomponents/commit/af2070f468e7b1fbb5e5b2d3dc0ea8f758e43739
And the change fixes the case when the List does not actually overflow, the bottom most part of the List is visible and the IntersectionObserver detects that the bottom of the List is reached. What happens in the apps is that  the List fires "load-more" just before the items that the app wants to show initially are actually rendered, which results in additional loading, not due to user scroll.
> fix(ui5-list): prevent load-more on initial intersection

- packages/main/src/TableRow.js
If the user clicks on a non-focusable element within the ui5-table-cell, the focus goes to the body or to the first focusable element above, so we have to bring it back to the row. If the user clicks on input, button or a similar clickable element, the focus remains on that element.
> chore(ui5-table): forward focus correctly to row element

- packages/main/src/DatePicker.js
- packages/main/src/DateRangePicker.js
- packages/main/src/DateTimePicker.js
- packages/main/src/Input.hbs
- packages/main/src/Input.js
- packages/main/src/i18n/messagebundle.properties
- ui5-date-picker: Replace aria-owns with aria-controls.
- ui5-datetime-picker: Change aria-roledescription's value to Date Time Input
- ui5-daterange-picker: Change aria-roledescription's value to Date Range Input
Fixes #3002
> fix(ui5-date*): components accessibility improved

- docs/Assets.md
- docs/Public Module Imports.md
- packages/base/hash.txt
- packages/base/src/asset-registries/Icons.js
- packages/icons-tnt/hash.txt
- packages/icons-tnt/src/AllIcons-static.js
- packages/icons-tnt/src/AllIcons.js
- packages/icons-tnt/src/Assets-static.js
- packages/icons-tnt/src/Assets.js
- packages/icons/hash.txt
- packages/icons/src/AllIcons-static.js
- packages/icons/src/AllIcons.js
- packages/icons/src/Assets-static.js
- packages/icons/src/Assets.js
- packages/main/bundle.es5.js
- packages/main/bundle.esm.js
- packages/main/src/Icon.js
❗❗❗ **IMPORTANT - BREAKING CHANGE** ❗❗❗
When developing apps, if an icon was not imported, the whole icon bundle is silently fetched and the developers have no easy way of finding out which icon caused that fetch.
**After this change, it will no longer be possible to use an icon you did not import, unless you explicitly import all icons**:
`import "@ui5/webcomponents-icons/dist/AllIcons.js";`
`import "@ui5/webcomponents-icons-tnt/dist/AllIcons.js";`
Additional changes:
- the icons registry module now throws a more specific error (used to be `loadIcons is not a function` which sounds more like a runtime error than lack of setup), because after the change all apps that use not-imported icons are expected to see this error.
- The documentation was updated
- Documentation was added for the …
> refactor(ui5-icon): Show not-imported icons warning

- packages/main/src/ResponsivePopover.hbs
- packages/main/src/ResponsivePopover.js
- packages/main/test/pages/ResponsivePopover.html
We use lit-html [classMaps](https://lit-html.polymer-project.org/guide/template-reference#classmap) to render classes out of objects , but it works with this getter "get classes()". Previously instead of having a class, the header element got this:
```html
<header class="[object Object]"
```
FIXES: https://github.com/SAP/ui5-webcomponents/issues/3173
> fix(ui5-responsive-popover): fix header styles

- packages/fiori/src/Wizard.hbs
- packages/fiori/test/specs/Wizard.spec.js
Aria-controls should point to an id instead of a class.
FIXES: #3160
> fix(ui5-wizard): correct aria-controls value

- packages/base/hash.txt
- packages/tools/package.json
- yarn.lock
Changes:
- `serve` is now an optional dependency
- the used protocol is now `git` instead of `github`
> chore: make serve an optional dependency

- packages/main/src/DurationPicker.js
- packages/main/src/TimePicker.hbs
- packages/main/src/TimePicker.js
- packages/main/src/WheelSlider.hbs
- packages/main/src/WheelSlider.js
- packages/main/src/i18n/messagebundle.properties
The ui5-time-picker and ui5-duration picker inner input
elements and wheel sliders now have aria properties set
according to the screen reader specification.
Fixes #3010
> fix(ui5-time-picker): accessibility improved

- packages/base/hash.txt
- packages/base/src/util/FocusableElements.js
- packages/main/src/BusyIndicator.hbs
- packages/main/src/BusyIndicator.js
- packages/main/test/pages/BusyIndicator.html
- packages/main/test/specs/BusyIndicator.spec.js
Removed "tabIndex" attribute from default \<slot\> of ui5-busyindicator, because it breaks `findFirstFocusableElement` and `findLastFocusableElement` . Instead focus redirecting is now done with `span` helper
Fixes #3181
> fix(ui5-busyindicator): focus handling improvements

- packages/main/src/ColorPalette.hbs
- packages/main/src/ColorPalette.js
- packages/main/src/ColorPaletteItem.hbs
- packages/main/src/ColorPaletteItem.js
- packages/main/src/themes/ColorPalette.css
- packages/main/src/themes/ColorPaletteItem.css
- packages/main/src/themes/base/sizes-parameters.css
This PR fixes the following issues:
-  Color Picker height in Compact size
-  Focus & hover handling of ```ui5-color-picker-item```
-  Clicking on recent colors affects their order now
> refactor(ui5-color-palette): refactor rendering of items

- packages/main/src/RatingIndicator.hbs
- packages/main/src/RatingIndicator.js
- packages/main/test/pages/RatingIndicator.html
- packages/main/test/specs/RatingIndicator.spec.js
When a Rating Indicator is not editable, aria-readonly attribute is added to the root element.
FIXES: #3203
> fix(ui5-rating-indicator): Aria-readonly attribute added

- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
- packages/main/test/specs/List.spec.js
#3089 
Add DELETE shourtcut key for deleting items when `mode` property is `Delete`. 
Also, remove the delete button from the tab chain.
Additionally - remove debug code for running only one of the tests in the spec.
Note: #3194 - Keyboard Handling JSDoc should be updated depending on which PR gets merged first.
> feat(ui5-list): add DELETE shortcut key

- packages/main/src/ColorPalette.hbs
- packages/main/src/ColorPalette.js
- packages/main/test/pages/ColorPalette.html
- packages/main/test/samples/ColorPalette.sample.html
- packages/main/test/specs/ColorPalette.spec.js
Rename moreColors to showMoreColors to make it sound like boolean and consistent with showRecentColors.
Related to: https://github.com/SAP/ui5-webcomponents/issues/3107
BREAKING_CHANGE: the property `"moreColors"` has been renamed to `"showMoreColors"`
> refactor(ui5-color-palette): rename moreColors to showMoreColors

- packages/main/src/Input.js
Related to https://github.com/SAP/ui5-webcomponents/issues/3107
BREAKING CHANGE: the `isOpen` method that used to return if the value state popover is open or closed has been removed as normally app developers do not need it.
> fix(ui5-input): change public method to private

- packages/main/src/RatingIndicator.js
- packages/main/test/pages/RatingIndicator.html
- packages/main/test/specs/RatingIndicator.spec.js
We have decided that we do not need to have private property on the web component level, as all HTML elements have 'title' attribute by default. 
The 'title' property of the inner div will be synced with the provided one.
In case no title is provided - the default from the internationalisation bundle will be taken.
> refactor(ui5-rating-indicator): remove private property "title"

- packages/main/src/List.js
- packages/main/src/themes/List.css
- packages/main/test/pages/List_keyboard_support.html
- packages/main/test/pages/Popups.html
Part of #3107
BREAKING_CHANGE: ```inset``` property of ```ui5-list``` is deprecated in favour of ```indent``` property
> fix(ui5-list): rename inset property to indent

- packages/main/src/CalendarHeader.js
- packages/main/test/pages/Calendar.html
- packages/main/test/specs/Calendar.spec.js
Prev and next buttons should be disabled when there is min and max dates set
Fixes #3201
> fix(ui5-calendar): correct enable/disable of prev and next buttons

- packages/main/src/Button.hbs
- packages/main/src/Button.js
- packages/main/src/MessageStrip.hbs
- packages/main/src/themes/MessageStrip.css
iconSize is a public property that is used only for the purpose of the MessageStrip close button. Remove the property and add a Shadow Part so the MessageStrip can re-style the button. Part of #3107
BREAKING_CHANGE: ```iconSize``` property of ```ui5-button``` has been deprecated
> fix(ui5-button): remove iconSize property

- packages/playground/_layouts/default.html
- packages/playground/_sass/layout.scss
- packages/playground/assets/css/landing-page.css
- packages/playground/docs/landing-page.html
Changes on the landing page:
- Desktop:
- Mobile:
In the documentation pages:
- Desktop:
- Mobile: Links are hidden on devices with width < 1100px
> chore: add links to the docs on the landing page of the playground

- packages/fiori/src/Wizard.js
- packages/fiori/test/pages/Wizard.html
- packages/fiori/test/pages/Wizard_test.html
- packages/fiori/test/samples/Wizard.sample.html
- packages/fiori/test/specs/Wizard.spec.js
We have decided to rename the selection-change event in order for its name to better represent its origins. In relation to https://github.com/SAP/ui5-webcomponents/issues/3107.
BREAKING_CHANGE: The “selection-change” event has been renamed to "step-change". In addition, the event param "selectedStep" has been renamed to "step" and the event param "previouslySelectedStep" has been renamed to "previousStep".
> refactor(ui5-wizard): selection-change renamed to step-change

- packages/main/src/AvatarGroup.js
- packages/main/src/themes/AvatarGroup.css
First and second deviations were cause because IE11 support. It was rounding incorrectly floated values.
The Third issue comes from base padding of **ui5-button** which is now removed in the context of overflow button in **ui5-avatar-group**
Fixes: #3197
> fix(ui5-avatar-group): visual design deviations

- packages/main/src/Carousel.hbs
- packages/main/src/Carousel.js
Part of #3107
BREAKING_CHANGE: ```hideNavigation``` property of ```ui5-carousel``` is deprecated in favour of ```hideNavigationArrows```. The new property shows/hides the arrows only(not both the arrows and the dots in the bottom)
> fix(ui5-carousel): implement hideNavigationArrows property

- packages/main/src/BusyIndicator.hbs
- packages/main/src/BusyIndicator.js
> fix(ui5-busyindicator): fixed aria-labelledby value

- packages/main/src/List.js
Part of: #3089 
Prevent default behavior of the keydown event when `SPACE` key is pressed, to avoid scrolling of the page.
> fix(ui5-list): prevent scrolling with space

- packages/main/src/TreeListItem.hbs
- packages/main/src/themes/TreeListItem.css
There was a separate CSS class `.ui5-li-tree-info` which add the same styles as `.ui5-li-info`. Now, `ui5-tree-item` uses `.ui5-li-info` CSS class.
Fixes: #3130
> fix(ui5-li-tree): fix info text visual appearance

- packages/main/src/themes/TreeListItem.css
Nested items should have border only when they are selected which has the same border and background colorsas `ui5-li`.
Changing the border color to be the same as background color for nested items so we can reuse the rest CSS styles from `ui5-li`.
Fixes #3238
> fix(ui5-li-tree): arrow flickering

- packages/main/src/MessageStrip.js
This is to full-fill global requirement of the VD team. It turns out that the currently used message/value state icons do not cover the contrast ratio criteria. The change replaces the icons in the MessageStrip component with the[ recommended icons](https://wiki.wdf.sap.corp/wiki/pages/viewpage.action?pageId=2036840833):
message-information -> information
message-success -> sys-enter-2
message-error -> error
message-warning -> alert
Old ones
New ones
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3287
> refactor(ui5-messagestrip): update icons for better contrast ratio

- packages/main/src/Table.hbs
- packages/main/src/Table.js
- packages/main/test/pages/Table.html
- packages/main/test/samples/Table.sample.html
Part of #3107 
BREAKING_CHANGE: ```show-no-data``` property is deprecated in favour of ```hide-no-data``` property
> fix(ui5-table): introduce hide-no-data property

- packages/main/src/Slider.js
- packages/main/src/SliderBase.js
- packages/main/test/specs/Slider.spec.js
- Tooltips will become and remain visible when the focus is
on the slider/handle.
- In case the slider looses the focus and the mouse is not
over it, the tooltip will be hidden.
> refactor(ui5-slider): show tooltips on focus

- packages/fiori/src/themes/sap_fiori_3_hcb/FlexibleColumnLayout-parameters.css
- packages/fiori/src/themes/sap_fiori_3_hcb/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3_hcw/FlexibleColumnLayout-parameters.css
- packages/fiori/src/themes/sap_fiori_3_hcw/parameters-bundle.css
CSS parameters points to wrong values. Now, they are aligned to correct values for high contrast Fiori 3 themes.
Fixes: #3320
> fix(ui5-flexible-column-layout): column borders in high contrast themes

- packages/main/src/List.js
ui5-li-notification-group uses a list inside a list
The issue:
The issue can be reproduced on
https://sap.github.io/ui5-webcomponents/playground/components/NotificationListGroupItem
When the focus is on the list item and shif+tab is pressed, the focus doesn't go to the notification group item header buttons.
The error:
When ListItemBase fires "_forward-before" event, the event is handled from each ui5-list above it, but it should be handled only from the parent list. 
The solution:
Bubbling of the "_forward-before" event is now prevented
> fix(ui5-list): fixed keyboard navigation when a list is inside a list

- packages/main/src/themes/TreeListItem.css
Styles for active and hover states were limited to the context of `ui5-side-navigation`. Now, they will be applied to the both components - `ui5-side-navigation` and `ui5-li-tree`
Hover and active state should be visible when the item could be selected. In addition the cursor should be pointer only when the expand/collapse icon is hovered or when the item could be selected.
Fixes: #3291
> fix(ui5-li-tree): hover and active visual state

- packages/main/src/TabContainer.js
- packages/main/src/types/TabContainerTabsPlacement.js
- packages/main/test/pages/TabContainer.html
Hide the tabsPlacement, but keep it working for some time as it is consumed in production, until we introduce the feature  on stakeholder's side. Part of: https://github.com/SAP/ui5-webcomponents/issues/3107
BREAKING_CHANGE: tabsPlacement has been removed as it is not specified in SAP Fiori 3 design system
> refactor(ui5-tabcontainer): deprecate tabsPlacement

- docs/dev/Creating UI5 Web Components Packages.md
Review of documentation topic Creating UI5 Web Components Packages
> docs: review of Creating UI5 Web Components Packages.md

- packages/base/hash.txt
- packages/fiori/src/UploadCollection.js
Part of #3107
BREAKING_CHANGE: property noDnd is renamed to hideDragOverlay
> fix(ui5-upload-collection): rename noDnd property to hideDragOverlay

- packages/main/src/Input.js
- packages/main/test/pages/Input.html
All inputs by Fiori Specification should highlight
matching suggestions.
BREAKING CHANGE: highlight property is removed and the feature is enabled by default
> refactor(ui5-input): remove highlight property

- packages/fiori/src/Wizard.hbs
- packages/fiori/src/Wizard.js
- packages/fiori/src/WizardStep.js
- packages/fiori/src/WizardTab.hbs
- packages/fiori/src/WizardTab.js
- packages/fiori/src/themes/WizardTab.css
- packages/fiori/test/pages/FCL.html
- packages/fiori/test/pages/Wizard.html
- packages/fiori/test/pages/Wizard_test.html
- packages/fiori/test/pages/Wizard_test_mobile.html
- packages/fiori/test/samples/Wizard.sample.html
Part of #3107
BREAKING_CHANGE: heading/subheading properties of WizardStep are renamed to titleText/subtitleText
> fix(ui5-wizard-step): rename properties

- packages/fiori/src/NotifactionOverflowActionsPopover.hbs
- packages/fiori/src/ShellBarPopover.hbs
- packages/main/src/ComboBoxPopover.hbs
- packages/main/src/DatePickerPopover.hbs
- packages/main/src/FileUploaderPopover.hbs
- packages/main/src/InputPopover.hbs
- packages/main/src/MultiComboBoxPopover.hbs
- packages/main/src/Popover.js
- packages/main/src/SelectPopover.hbs
- packages/main/src/TabContainerPopover.hbs
- packages/main/src/TextAreaPopover.hbs
- packages/main/src/TimePickerPopover.hbs
- packages/main/src/TokenizerPopover.hbs
- packages/main/src/themes/Popover.css
- packages/main/test/pages/Dialog.html
- packages/main/test/pages/Input_quickview.html
- packages/main/test/pages/Popover.html
- packages/main/test/pages/Popups.html
- packages/main/test/samples/ColorPalette.sample.html
- packages/main/test/specs/Popover.spec.js
Part of #3107 
BREAKING_CHANGE: rename ```noArrow``` property to ```hideArrow```
> fix(ui5-popover): rename noArrow property to hideArrow

- packages/fiori/src/FlexibleColumnLayout.js
- packages/fiori/test/pages/FCL.html
Part of #3107 
BREAKING_CHANGE: rename ```noArrows``` property to ```hideArrows```
> fix(ui5-flexible-column-layout): rename noArrows property to hideArrows

- packages/main/src/Carousel.hbs
- packages/main/src/Carousel.js
- packages/main/src/themes/Carousel.css
- packages/main/test/pages/Carousel.html
- packages/main/test/specs/Carousel.spec.js
The page indicator can now be hidden by setting the property
hide-page-indicator on the ui5-carousel element.
- the arrows are always visible when `arrowsPlacement` is set to `Navigation`
- fixed typos
- changed height reduction of the carousel viewport to 1rem
Closes: #3158
> feat(ui5-carousel): add property hide-page-indicator

- packages/base/hash.txt
- packages/fiori/src/UploadCollection.hbs
- packages/fiori/test/pages/FCL.html
- packages/fiori/test/samples/FlexibleColumnLayout.sample.html
- packages/main/src/Title.js
- packages/main/src/themes/Title.css
- packages/main/src/types/WrappingType.js
- packages/main/test/pages/DateTimePicker.html
- packages/main/test/pages/Title.html
- packages/main/test/specs/Components.spec.js
- packages/main/test/specs/Title.spec.js
Part of #3107
BREAKING_CHANGE: property wrap has been renamed to wrappingType and its type has changed
> fix(ui5-title): rename wrap property to wrappingType

- packages/main/src/Popover.js
Resolves https://github.com/SAP/ui5-webcomponents/issues/3131
This fix steps on the following commit: https://github.com/SAP/ui5-webcomponents/commit/e35cc1ae9f3830fa137b3d683dc10481e13743f4
It enhances it in a way that Popover.MIN_OFFSET is taken into account into Popover's maxContentHeight. Popover.MIN_OFFSET is used when calculating the offset of the Popover from the top but has never been extracted from the content's height.
> fix(ui5-popover): Calculate max content height

- packages/fiori/src/NotificationAction.js
- packages/main/src/Link.js
- packages/main/src/Option.js
- packages/main/src/StandardListItem.js
- packages/main/src/SuggestionItem.js
- packages/main/src/themes/Link.css
- packages/main/test/pages/Link.html
- packages/main/test/specs/Components.spec.js
Part of #3107
- fixed documentation errors
BREAKING_CHANGE: property wrap has been renamed to wrappingType and its type has changed
> fix(ui5-link): rename wrap property to wrappingType

- packages/main/src/DateRangePicker.js
- packages/main/test/specs/DateRangePicker.spec.js
Part of https://github.com/SAP/ui5-webcomponents/issues/3107#issuecomment-843032055
BREAKING_CHANGE:  The readonly attributes `firstDateValue` and `lastDateValue` have been renamed to `startDateValue` and `endDateValue`.
> refactor(ui5-daterange-picker): rename first/lastDateValue

- packages/main/src/CheckBox.hbs
- packages/main/src/CheckBox.js
- packages/main/src/themes/CheckBox.css
- packages/main/test/pages/CheckBox.html
- packages/main/test/pages/Kitchen.html
- packages/main/test/pages/Kitchen.openui5.html
- packages/main/test/samples/CheckBox.sample.html
- packages/main/test/specs/CheckBox.spec.js
As part of https://github.com/SAP/ui5-webcomponents/issues/3107 we decided to replace the boolean property `wrap` as we expect to add a new type of wrapping (Hyphenated) and for this the string property from enum type is more suitable.
BREAKING_CHANGE: The boolean property `wrap` has been removed in favour of string prop `wrappingType`. If you previously used `wrap`, now set `wrappingType="Normal"` instead.
> refactor(ui5-checkbox): replace `wrap` with `wrappingType`

- packages/main/src/RadioButton.hbs
- packages/main/src/RadioButton.js
- packages/main/src/themes/RadioButton.css
- packages/main/test/pages/RadioButton.html
- packages/main/test/samples/RadioButton.sample.html
- packages/main/test/specs/RadioButton.spec.js
As part of #3107 we decided to replace the boolean property wrap as we expect to add a new type of wrapping (Hyphenated) and for this the string property from enum type is more suitable.
BREAKING_CHANGE: The boolean property wrap has been removed in favour of string prop wrappingType. If you previously used wrap, now set wrappingType="Normal" instead.
> refactor(ui5-radiobutton): replace `wrap` with `wrappingType`

- packages/fiori/src/UploadCollection.js
- packages/fiori/test/pages/uploadCollectionScript.js
- packages/fiori/test/specs/UploadCollection.spec.js
Part of #3107
BREAKING_CHANGE: ```file-deleted``` event is renamed to ```file-delete```
> fix(ui5-upload-collection): change file deleted event name

- packages/main/src/RatingIndicator.hbs
- packages/main/src/RatingIndicator.js
- packages/main/test/pages/RatingIndicator.html
- packages/main/test/samples/RatingIndicator.sample.html
- packages/main/test/specs/RatingIndicator.spec.js
Part of #3107
BREAKING_CHANGE: ```maxValue``` property of ```ui5-rating-indicator``` is deprecated in favour of ```max``` property.
> fix(ui5-rating-indicator): rename maxValue property to max

- packages/main/src/Popup.hbs
- packages/main/src/Popup.js
tabIndex on the root element is set to "-1" if there are no focusable elements
Fixes #3330
> fix(ui5-popup): scroll handle is now working for input controls

- packages/main/src/themes/CheckBox.css
This PR moves the icon inside the CheckBox outside of the flow, so it doesn't affect elements aligned with `baseline`.
See this codeSandbox for reference:
https://codesandbox.io/s/ui5-webcomponents-forked-fnmzi
> fix(CheckBox): Prevent shifting of elements aligned with baseline when checking/unchecking

- packages/fiori/src/TimelineItem.hbs
- packages/fiori/src/TimelineItem.js
- packages/fiori/test/pages/Timeline.html
- packages/fiori/test/samples/Timeline.sample.html
- packages/fiori/test/specs/Timeline.spec.js
- packages/main/test/samples/Card.sample.html
- packages/main/test/samples/Carousel.sample.html
Improve naming as part of https://github.com/SAP/ui5-webcomponents/issues/3107. The word `item` is obsolete in the props/event names as the component is TimelineItem and has  the word `item` itself.
BREAKING_CHANGE: The properties `itemName` and `itemNameClickable` are renamed to renamed to `name` and `nameClickable` and the event `item-name-click` is renamed to `name-click`
> refactor(ui5-timeline-item): rename API

- packages/fiori/src/NotificationListGroupItem.hbs
- packages/fiori/src/NotificationListItem.hbs
- packages/fiori/src/NotificationListItemBase.js
- packages/main/src/BusyIndicator.hbs
- packages/main/src/BusyIndicator.js
- packages/main/src/List.hbs
- packages/main/src/List.js
- packages/main/src/Table.hbs
- packages/main/src/Table.js
- packages/main/test/pages/BusyIndicator.html
- packages/main/test/specs/BusyIndicator.spec.js
Also added new "busyDelay" property to ui5-list, ui5-table, ui5-li-notification-group, ui5-li-notification.
> feat(ui5-busy-indicator): add new "delay" property

- packages/main/src/ColorPalette.js
- packages/main/test/pages/ColorPalette.html
Part of #3107 
BREAKING_CHANGE: ```change``` event of ```ui5-color-palette``` is renamed to ```item-click```
> fix(ui5-color-palette): rename change event

- packages/fiori/src/UploadCollectionItem.js
- packages/fiori/test/pages/UploadCollection.html
- packages/fiori/test/specs/UploadCollection.spec.js
- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
Part of #3107
Added property `hideDeleteButton` which hides the always-visible delete button.
BREAKING_CHANGE: property `noDelete` has been renamed to `disableDeleteButton`
BREAKING_CHANGE: property `noRetry` has been renamed to `hideRetryButton`
BREAKING_CHANGE: property `noTerminate` has been renamed to `hideTerminateButton`
> refactor(ui5-upload-collection): rename properties

- packages/main/src/ColorPaletteItem.js
The  `stableDomRef` is meant for components that don't have a template on their own, but are pure elements, that the parent component renders (for example Select and Options). In this case the ColorPaletteItem is a component with own template and does not need to expose a special property like this to app developers to get its DOM ref as there is already `getDomRef` method that is sufficient.
BREAKING_CHANGE: `stableDomRef` is removed, if you need to get the item's DOM ref, use `getDomRef` on the item instance.
> refactor(ui5-color-palette-item): remove `stableDomRef` as not needed

- packages/main/src/themes/Input.css
- packages/main/src/themes/ResponsivePopoverCommon.css
- packages/main/src/themes/StepInput.css
- packages/main/src/themes/TextArea.css
- packages/main/src/themes/base/Input-parameters.css
- packages/main/src/themes/sap_fiori_3/Input-parameters.css
- packages/main/src/themes/sap_fiori_3_dark/Input-parameters.css
- packages/theme-base/css-vars-usage.json
There is a standard css variable `--sapField_BorderCornerRadius` meant to be used for Input's border radius. It is 0.125rem in sap_fiori_3 and sap_fiori_3_dark and 0 in all other themes. This allows changing the border radius of all inputs via the Theme Designer
> fix(inputs): use base CSS param for border-radius

- packages/fiori/src/Bar.hbs
- packages/fiori/src/Bar.js
- packages/fiori/test/pages/Bar.html
- packages/fiori/test/pages/Page.html
- packages/fiori/test/samples/Bar.sample.html
- packages/fiori/test/samples/Page.sample.html
Part of #3107
BREAKING_CHANGE: ```middleContent``` slot is deprecated in favour of default slot
> refactor(ui5-bar): rename middleContent slot

- packages/fiori/src/Wizard.hbs
- packages/fiori/src/Wizard.js
- packages/fiori/src/i18n/messagebundle.properties
- packages/fiori/test/specs/Wizard.spec.js
- aria-describedby added to the element with role 'list'
- aria-label enhanced for each step. Now the steps will be
announced as "Active" or "Inactive" depending on their
'deactivated' property.
> refactor(ui5-wizard): ARIA attributes enhanced

- packages/main/src/Card.hbs
<section> does not support role='group'
Fixes: #3439
> fix(ui5-card): correct content html tag

- packages/fiori/src/FlexibleColumnLayout.js
Sometimes timeout that adds `ui5-fcl-column--hidden` is executed when the calculations are already done. Executing the timeout callback later causes visual issue where column is hidden when it should be displayed.
Now, timeout is replace with listener for `transionend` so if it is no longer needed to be removed.
Fixes: #3425
> fix(ui5-flexible-column-layout): correct columns display

- packages/fiori/src/SideNavigation.js
- packages/fiori/test/specs/SideNavigation.spec.js
When sideNavigation is collapsed, subitems in popup did not fire "click" event. Test are adapted, because the issue was giving wrong values.
Fixes: #3333
> fix(ui5-sideNavigation): Items in popup fire click event

- LICENSE.txt
+ Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents/blob/master/CONTRIBUTING.md#how-to-contribute) section 
---
In order to be able to identify the main license of all managed repositories centrally, the SAP Open Source Program Office (OSPO) asks all teams to have an identifiable license in their repositories. For some reason (probably formatting - we usually have these issues with licenses copied via the [REUSE tool](https://reuse.software)) the [license in this repository is not detected properly by GitHub](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/licensing-a-repository#detecting-a-license). This …
> chore: use GitHub license template

- packages/main/bundle.common.js
- packages/main/src/Table.js
- packages/main/src/TableGroupRow.hbs
- packages/main/src/TableGroupRow.js
- packages/main/src/TableRow.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/src/themes/TableGroupRow.css
- packages/main/test/pages/TableGrouping.html
- packages/main/test/samples/Table.sample.html
- packages/main/test/specs/Table.spec.js
- packages/main/test/specs/TableGrouping.spec.js
- packages/theme-base/css-vars-usage.json
The new type of row represents group header row which can be used in case a grouping in the table is required. 
Fixes #3319
> feat(ui5-table-group-row): introduce new component

- packages/main/src/Dialog.js
When dialog is nested inside an element containing z-index, this might break the z-index management of the ui5-dialog.
Related to:  #3426
> docs(ui5-dialog): Documentation is updated referencing z-index

- packages/main/src/StepInput.js
- packages/main/test/specs/StepInput.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/3457
> fix(ui5-step-input): firing step input once when value is deleted

- packages/fiori/src/NotificationListGroupItem.hbs
- packages/fiori/src/NotificationListItem.hbs
- packages/fiori/test/pages/NotificationListGroupItem.html
- packages/fiori/test/pages/NotificationListItem.html
- packages/fiori/test/specs/NotificationList.spec.js
- packages/main/src/List.hbs
- packages/main/src/List.js
- packages/main/src/Tree.hbs
Instead of creating a NotificationList web component with only role attribute changed (compared to the List), we decided to rename the List's private **"accRole"** property  to **"accessibleRole"** and make it public, with default value as previous "listbox", and recommend setting it to **"accessible-role=list"** for the notifications use case.
- List: new property **"accessibleRole"**
- NotificationList(Group)Item: **role="option"** changed to **role="listitem"** to full-fill the a11y spec.
- Tree now setting the new prop **"accessibleRole"**
> refactor(ui5-list): introduce accessibleRole prop

- packages/main/src/themes/PopupsCommon.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/test/pages/Dialog.html
- packages/theme-base/hash.txt
The header height is defined as 44px in Cozy and 40px in compact.
This change affects the Dialog and Popover components only when the property headerText is used.
This doesn't change the height of the slot `header`.
Fixes #3497
> fix(ui5-popup): adjust default header height

- packages/main/src/themes/Popover.css
- packages/main/test/pages/ResponsivePopover.html
**ResponsivePopover** overrides the custom property `_ui5_popup_content_padding`
as it is used by other components.
The calculation for the position of the arrow depends on this padding,
and the calculation will be wrong when the padding is set to "0".
Solved by changing the positioning of the arrow by using `top`.
Fixes #3500
> fix(ui5-responsive-popover): fixed position of downward pointing arrow

- packages/fiori/src/themes/ShellBar.css
Make limitation of the space (equal on both sides) to be applied only when the coPilot
logo is appearing to visually "divide" the Shellbar.
Fixes: #3501
> fix(ui5-shellbar): Fix unnecessary cutting space on left side

- packages/main/src/CheckBox.hbs
- packages/main/src/Icon.hbs
- packages/main/src/Icon.js
- packages/main/test/pages/CheckBox.html
- packages/main/test/pages/Icon.html
- packages/main/test/specs/CheckBox.spec.js
- packages/main/test/specs/Icon.spec.js
The role `presentation` on the icon `SVG` is ignored in some cases:
* The element is focusable, e.g. it is natively focusable like an HTML link or input, or it has a tabindex attribute.
* **The element has any of the twenty-one global ARIA states and properties, e.g., `aria-label`.**
With this change we introduce `ariaHidden` property on the `ui5-icon` to be able to completly hide it from the accessibility tree mapping.
Also, change the default value of `effectiveAccessibleName` property to `undefined` as a value of "" will still set the `aria-label` attribute and the `presentation` role will be ignroed.
Fixes #3433
> fix(ui5-checkbox): add aria-hidden attribute to icon

- packages/fiori/src/themes/Wizard.css
Recently a "invisible text" has been added to the WIzard's template with this PR #3443 but the required styles has not been imported and the text is actually visible, right under the step (as described in the related issue). The change imports the styles and the "invisible text" is really invisible now.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/3551
> fix(ui5-wizard): import "InivisibleText" styles

- packages/main/src/InputPopover.hbs
- packages/main/src/SuggestionListItem.hbs
The additional-text used to be broken for the SuggestionItem
> fix(ui5-input): additionalText in suggestions

- packages/fiori/src/NotificationListItem.js
- packages/fiori/src/themes/NotificationListItem.css
- packages/fiori/test/pages/NotificationListItem.html
- packages/fiori/test/pages/NotificationList_test_page.html
We change the boolean "wrap" property in the Link, Label, Title to string property "wrappingType" to make it more flexible for the upcoming "hyphenated type of wrapping". The change does the same with the ui5-li-notification.
BREAKING CHANGE: 
for ```ui5-li-notification```, ```wrap``` property is renamed to ```wrappingType```
> fix(ui5-li-notification): rename wrap property to wrappingType

- packages/main/src/CardHeader.js
- packages/main/test/pages/Card.html
- packages/main/test/pages/Carousel.html
- packages/main/test/samples/Card.sample.html
- packages/main/test/samples/Carousel.sample.html
As we extracted all header related properties from the Card component to a new CardHeader and the "headerInteractive" property now belongs to CardHeader component, we no longer have to use "header" in the name, but call it just "interactive" - same as we did with the "header-click" event, that is now called "click".
Changes:
- rename "headerInteractive" to "interactive"
- fix Carousel sample to use the CardHeader
BREAKING CHANGE: The CardHeader's property "headerInteractive" has been renamed to "interactive"
> refactor(ui5-card-header): rename "headerInteractive" to "interactive"

- packages/main/src/Select.js
- packages/main/test/specs/Select.spec.js
Implement changing of focus of options on keypress - typing letters now allows focusing different options of the ui5-select.
Fixes: #3476
> feat(ui5-select): Change focus of options on keypress

- packages/base/hash.txt
- packages/fiori/src/NotificationListGroupItem.hbs
- packages/fiori/src/NotificationListGroupItem.js
- packages/fiori/src/NotificationListItem.hbs
- packages/fiori/src/NotificationListItem.js
- packages/fiori/src/NotificationListItemBase.js
- packages/fiori/src/themes/NotificationListGroupItem.css
- packages/fiori/src/themes/NotificationListItem.css
- packages/fiori/test/pages/NotificationListGroupItem.html
- packages/fiori/test/pages/NotificationListItem.html
- packages/fiori/test/pages/NotificationList_test_page.html
- packages/fiori/test/pages/ProductSwitchItem.html
- packages/fiori/test/samples/NotificationListGroupItem.sample.html
- packages/fiori/test/samples/NotificationListItem.sample.html
- packages/fiori/test/specs/NotificationList.spec.js
BREAKING CHANGE
For ```ui5-li-notification``` and ```ui5-li-notification-group```, ```heading``` property has been renamed to ```titleText```
> fix(ui5-li-notification, ui5-li-notification-group): rename heading property to titleText

- packages/fiori/test/samples/FlexibleColumnLayout.sample.html
- packages/main/src/themes/Avatar.css
- packages/main/test/samples/AvatarGroup.sample.html
- packages/main/test/specs/TableGrouping.spec.js
The color-scheme property currently does not take any effect due to these styles that rely on the old property. Now it works fine.
> chore(ui5-avatar): fix color-scheme API usage

- packages/fiori/src/ViewSettingsDialog.js
- packages/fiori/test/pages/ViewSettingsDialog.html
- packages/fiori/test/samples/ViewSettingsDialog.sample.html
The Dialog's and Popup's public methods have been recently renamed to show (previously open), showAt (previously openBy) and  we have to use "show" here as well to keep the convention. Also, the public method should be documented.
> chore(ui5-vsd): rename "open" to show"

- packages/base/hash.txt
- packages/base/src/renderer/LitRenderer.js
- packages/tools/lib/hbs2lit/src/litVisitor2.js
- packages/tools/lib/hbs2lit/src/svgProcessor.js
- packages/tools/lib/hbs2ui5/RenderTemplates/LitRenderer.js
- packages/tools/lib/scoping/lint-src.js
`lit-html 2.0` has optimizations that require creating lit templates only once. 
Our current code generates templates like this:
```js
const main = (context, tags, suffix) => {
const block0 = (context) => { return html`<div class="ui5-badge-root" dir="${ifDefined(context.effectiveDir)}"><slot name="icon"></slot>${ context.hasText ? block1(context) : undefined }<span class="ui5-hidden-text">${ifDefined(context.badgeDescription)}</span></div>`; };
const block1 = (context) => { return html`<label class="ui5-badge-text"><bdi><slot></slot></bdi></label>`; };
return block0(context);
};
export default main;
```
Every time the `main` function is executed, `block0`, etc... are created again.
The new code creates templates like this:
```js
const block0 = (context, tags, suffix) => html`<div …
```
> chore(framework): Generate better lit templates

- packages/main/src/DatePicker.js
- packages/main/src/DateRangePicker.js
- packages/main/src/DateTimePicker.js
- Focus is moved on the component input field after closing
the corresponding popover via Escape keyboard key.
related to: #3091
> fix(ui5-date-picker): keyboard handling now compliant with the specification

- packages/main/src/Calendar.js
- packages/main/src/DatePicker.js
- packages/main/src/DatePickerPopover.hbs
- packages/main/src/DateTimePickerPopover.hbs
- packages/main/test/specs/DatePicker.spec.js
- Day picker is always shown when the corresponding ui5-date-picker,
ui5-datetime-picker or ui5-daterange-picker component popover is opened.
> fix(ui5-date-picker): internal calendar component state managed properly

- packages/main/src/themes/ColorPaletteItem.css
- The color palette swatches focus outline is properly visualized
according to the global focus visual concept.
Fixes: #3521
> fix(ui5-color-palette): focus outline is properly visualized

- packages/main/src/ColorPicker.js
> fix(ui5-color-picker): hue slider position is decoupled from the opacity slider position

- packages/main/src/Card.hbs
- packages/main/src/Card.js
- packages/main/src/CardHeader.js
- packages/main/test/pages/Card.html
- packages/main/test/specs/Card.spec.js
Now card doesn't reference element ID in another shadow DOM with `aria-labelledby`. The header is labelled by its own title instead.
Fixes #3643
> fix(ui5-card): correctly set aria-labelledby

- packages/main/src/Panel.js
- packages/main/test/pages/Panel.html
- packages/main/test/specs/Panel.spec.js
New property called noAnimation is added to the ui5-panel component. When set to true, the ui5-panel is expanded/collapsed without animation.
FIXES: #3505
> feat(ui5-panel): noAnimation property introduced

- packages/main/src/SegmentedButton.js
Focus is moved on the first element of Segmented Button or last element via PageUp or PageDown keyboard key.
Related to: https://github.com/SAP/ui5-webcomponents/issues/3091
> fix(ui5-SegmentedButton): keyboard handling now compliant with the specification

- packages/main/src/DatePicker.js
- packages/main/test/pages/DatePicker.html
- packages/main/test/pages/DatePicker_test_page.html
fixes: https://github.com/SAP/ui5-webcomponents/issues/3516
> fix(ui5-date-picker): setting value before firing event

- packages/main/src/DayPicker.js
Waiting for @vladitasev before merging this.
This PR addresses an issue that is currently present in the master branch only.
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/DatePicker/
2. Open the first datepicker
3. Select a date
4. Check the console
The framework sets a multiple attribute's value to string when we pass an array with only one item inside because the DOM doesn't support arrays. Later, when we read the attribute and try to set the value to the property the error is thrown, because we **can't** read multiple attribute from the DOM(Array or Object).
One solution that we discussed with @ilhan007 is to internally treat every multiple property as if it has ```noAttribute``` set.
> fix(ui5-daypicker): fix js error

- packages/base/bundle.esm.js
- packages/base/hash.txt
- packages/base/src/StaticAreaItem.js
- packages/base/test/elements/WithStaticArea.js
- packages/base/test/pages/AllTestElements.html
- packages/base/test/specs/StaticArea.spec.js
When `dir="rtl"` is set on some DOM element that is not the body, RTL mode is applied only on the components (like `ui5-select`), but not on their popovers, as the `dir="rtl"` is not transferred to the static area item.
This change sets the dir attribute on the static area item such that it matches the effective dir attribute of the component.
> fix(framework): apply RTL for components with popovers

- packages/base/hash.txt
- packages/base/src/UI5ElementMetadata.js
- packages/main/src/DayPicker.js
- packages/main/src/MultiInput.js
A recent change (https://github.com/SAP/ui5-webcomponents/pull/3604) introduced this bug. `DayPicker.js` has a `multiple` property of type `Integer`, which is a `DataType.js` descentent, hence it was affected by the new code, introduced by the above change.
Additionally: 
- `noAttribute: true` is no longer needed for `DayPicker.js`
- `multiple: true` is not needed for `MultiInput.js` (this metadata entity is only valid for properties, not for slots)
fixes: https://github.com/SAP/ui5-webcomponents/pull/3677
> fix(framework): Multiple properties have no attribute

- packages/main/src/Popup.js
- packages/main/src/popup-utils/OpenedPopupsRegistry.js
- packages/main/test/pages/Dialog.html
- packages/main/test/specs/Dialog.spec.js
Body scrolling is now blocked only on first call of `blockBodyScrolling` and restored on the last call of `unblockBodyScrolling`. 
Fixes #3690
> fix(ui5-dialog): correctly restore body scrolling on ESC

- packages/main/src/ToggleButton.js
If [SPACE] is pressed, releases the ToggleButton without changing its state
> fix(ui5-ToggleButton): keyboard handling now compliant with the specification

- docs/CustomTheming.md
The Theme Designer is no longer publicly available and we had to add this note and also the "trial" app has been removed, so I added a link to a Demo Theme Designer
https://themedesigner-themedesignerdemo.dispatcher.eu2.hana.ondemand.com/index.html
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3515
> docs: fix Custom Theming section

- packages/main/src/ComboBoxGroupItem.js
- packages/main/src/Interfaces.js
- packages/main/src/SegmentedButton.js
- packages/main/src/SegmentedButtonItem.js
- packages/main/src/TableGroupRow.js
It's preferable to add interfaces information in JSDoc for all components that are intended to slot specific items.
*Additionally:* `ui5-table-group-row` was missing a dependency.
> chore: add interfaces JSDoc

- packages/main/src/SegmentedButtonItem.js
- Removed the `iconSize` property that no longer exists in `Button.js`
- Added the correct JSDoc for the `type` and `defaultValue` of the overridden properties
> chore(ui5-segmented-button): fix jsdoc

- packages/base/src/EventProvider.js
- `EventProvider.js` now uses a `Map` instead of an `Object` for the registry. 
- Listeners are now stored directly, instead of in an Object with an `fnFunction` field.
- `attachChange` checks if the listener is registered before adding it.
BREAKING CHANGE: Multiple calls of `attachEvent` with the same listener for the same event will result in the event listener being registered only once.
> refactor(framework): EventProvider.js reworked

- packages/main/src/Input.js
This PR fixes the typing error of the `icon` slot, as it's possible to pass multiple `Icons` to the Input.
> docs(Input): correct icon type in jsdocs comments

- packages/main/src/Card.js
- packages/main/src/CardHeader.js
- packages/main/test/pages/Card.html
- packages/main/test/specs/Card.spec.js
This change stops the native browser click event from firing.
Also fixed the firing of the click event on an non-interactive header.
Fixes: #3786
> fix(ui5-card-header): no longer fires click event twice

- packages/main/src/Popover.js
- packages/main/src/themes/Popover.css
- packages/main/src/themes/base/PopupsCommon-parameters.css
The popover is specified to have a 10px page margin.
This change covers this specific case.
Fixes: #2969
> fix(ui5-popover): restrict width on small screens

- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
- packages/main/src/RadioButton.hbs
- packages/main/src/RadioButton.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/pages/RadioButton.html
- packages/main/test/specs/RadioButton.spec.js
Fixes point 5 of #3806.
Add accessible name to the radio button used in the single select mode of `ui5-list`.
Summary: 
- new private property `accessibleName` is introduced in `ui5-radio-button`;
- `accessibleName` property is set internally on the `ui5-radio-button` used in `ui5-li`;
> fix(ui5-li): add accessible name to single select radio button

- packages/fiori/test/specs/ViewSettingsDialog.spec.js
- packages/main/src/ListItem.js
- packages/main/test/pages/List_test_page.html
- packages/main/test/specs/List.spec.js
Fixes point 3 of #3806
The not announced selected state seems to be an issue with screen readers, but in order to provide better experience we add the custom "Selected" text to the items with aria-selected=true, similarly to sap.m.List of openui5.
> fix(ui5-li): add "Selected" text to item's accessible name

- packages/main/src/GroupHeaderListItem.hbs
- packages/main/src/GroupHeaderListItem.js
- packages/main/test/pages/List_test_page.html
- packages/main/test/specs/List.spec.js
Fixes points 1 & 2 of #3806 
The group header should not be treated as an item (option) and should not be calculated with the posinset and setsize values.
With this change we set role `group` with `aria-roledescription` of Group Header to the `ui5-li-groupheader` root element.
> fix(ui5-li-groupheader): change role option

- packages/main/src/themes/Label.css
- packages/main/test/pages/Label.html
CustomListItem sets the `white-space` style to `nowrap`. The solution is to explicitly set the style of the label to `normal` when wrapping is required.
In addition fixed the cursor - it should always be `text`.
Fixes #3324
> fix(ui5-label): wrapping now works when used in CustomListItem

- packages/main/src/Avatar.js
- packages/main/src/Icon.js
Having the `onclick` handler attached, makes the screen readers read the element as clickable even if `interactive` is set to false.
With this change the click handler is only attached if the `interactive` property is true.
Fixes: #3683
> fix (ui5-avatar, ui5-icon): attach onclick handler based on interactive property

- packages/main/src/themes/TreeListItem.css
Fixed the following issues from #3623
Text too close to the icons in RTL.
Too much right padding in RTL.
Icons are too close to the border of the items.
> fix (ui5-side-navigation): fix exploratory testing issues

- packages/base/hash.txt
- packages/main/src/ColorPalettePopover.js
Prior to this change, you could access the selected colours like this: ```event.detail.detail.color```.
Now it is fixed and can be accessed like this: ```event.detail.color```
BREAKING CHANGE: The selected color is now available as it is documented: ```event.detail.color```
> fix(ui5-color-palette-popover): fix event params

- packages/main/src/Dialog.js
There is no ResizeHandler warning when a dialog is created dynamically
Fixes: #3620
> fix(ui5-dialog): fix console warning from exploratory testing

- packages/main/src/SliderBase.js
> fix(ui5-slider): show tooltips when component has focus

- packages/fiori/src/UploadCollection.hbs
- packages/fiori/src/UploadCollection.js
- packages/fiori/src/themes/UploadCollection.css
- packages/fiori/test/pages/UploadCollection.html
- packages/fiori/test/samples/UploadCollection.sample.html
- packages/fiori/test/specs/UploadCollection.spec.js
> feat(ui5-upload-collection): Added "accessibleName" property

- packages/main/src/themes/base/Badge-parameters.css
The previous accent colors were incorrect.
Fixes #3923
> fix(ui5-badge): update accent colors for color-scheme=8

- packages/fiori/src/SideNavigation.hbs
- packages/fiori/src/SideNavigationItem.js
- packages/fiori/src/SideNavigationItemPopoverContent.hbs
- packages/fiori/src/SideNavigationSubItem.js
- packages/fiori/test/pages/SideNavigation.html
- packages/fiori/test/specs/SideNavigation.spec.js
Items now have `title` property. If it is not specified, the text property is used as their tooltip. It is shown in both expanded and collapsed state.
Fixes #3549
> feat(ui5-side-navigation): Items now have tooltip

- packages/main/src/Toast.hbs
- packages/main/src/Toast.js
- packages/main/test/specs/Toast.spec.js
Since ui5-toast component has role "alert", its content could be read out when render on opening or changed dynamically when opened.
FIXES: #3841
> fix(ui5-toast): Content is announced when ui5-toast is shown

- packages/main/src/ComboBox.js
- packages/main/test/pages/ComboBox.html
- packages/main/test/specs/ComboBox.spec.js
Pressing the arrow of the ComboBox web component now correctly toggles the picker on desktop.
> fix: ComboBox arrow now correctly toggles the picker

- packages/main/src/ComboBox.js
- packages/main/test/specs/ComboBox.spec.js
Issue #3784:
When the picker is closed the entered value is not cleared. When the picker is opened, it closes but the value remains in the input field.
Now the component is synced with the desired by specifications behavior.
If the suggestions popover is opened: ESC closes it.
If the suggestions are not opened: ESC resets the value to the last confirmed by the user with 'ENTER' or item click, or if there isn't one - with the initial value of the component when focused by the user.****
> fix(ui5-combobox): Fix value reset on ESC #3886

- packages/main/src/Input.js
- packages/main/test/specs/Input.spec.js
Issue #3784:
> When the picker is closed the entered value is not cleared. When the picker is opened, it closes but the value remains in the input field.
Now the component is synced with the desired by specifications behavior.
If the suggestions popover is opened: ESC closes it.
If the suggestions are not opened: ESC resets the value to the last confirmed by the user with 'ENTER' or if there isn't one - with the initial value of the component when focused by the user.
> fix(ui5-input): Fix value reset on ESC

- packages/main/src/Input.hbs
The `data-sap-no-tab-ref` is removed to allow container controls which are checking for tabbable children to pass the focus to it via the TAB key.
Issue: #3603
> fix(ui5-input): remove data-sap-no-tab-ref attribute from the inner input

- packages/main/src/Tokenizer.js
The update of `this._nMoreCount` property in onAfterRendering was causing too many re-rendering cycles causing the framework to throw. 
Issue: #3867
> fix(ui5-tokenizer): Prevent re-rendering error

- packages/main/src/MultiComboBox.js
> fix(ui5-multi-combobox): prevent setting max-width of dialog header on mobile

- packages/main/src/MultiComboBox.js
- packages/main/src/MultiComboBoxPopover.hbs
User can cancel its selection by pressing the close button of the dialog on mobile phone. In this case, selection will be reverted and no event will be called at all. If the OK button is pressed selection will replicate to tokens and fire event `selection-change`
FIXES: #3764
> fix(ui5-multi-combobox): revert selection after close button is pressed

- packages/fiori/src/themes/InvisibleTextStyles.css
- packages/main/src/themes/InvisibleTextStyles.css
fix(ui5-tree): Unnecessary scrollbar in RTL mode removed
ui5-hidden-text "left: property value of -1000px was causing additional space in overflow: auto controls in RTL mode and needs
to be preseted to its "right" property.
Fixes #3947
Fixes #3503
Part of #3623
> fix(ui5-tree): Unnecessary scrollbar in RTL mode removed

- packages/main/src/FileUploader.hbs
- packages/main/src/FileUploader.js
Upload files button now is activated with Enter/Space key with screen reader virtual cursor  ON"
Fixes:  https://github.com/SAP/ui5-webcomponents/issues/3767
Closes: https://github.com/SAP/ui5-webcomponents/issues/3767
> fix(ui5-file-uploader): Button is activated with Enter/Space key with screen reader virtual cursor

- packages/main/src/themes/Avatar.css
- packages/main/test/samples/AvatarGroup.sample.html
After introducing image slot in `ui5-avatar` samples in the playground were not adjusted to it. Also color property was changed to color-scheme.
Images used inside the `image` slot were blocking the click event and the focus was not able to be applied.
> fix(ui5-avatar-group): exploratory testing issues

- docs/dev/Testing Web Components.md
- packages/tools/components-package/wdio.sync.js
- packages/tools/lib/init-package/resources/test/specs/Demo.spec.js
This is a follow-up change to: https://github.com/SAP/ui5-webcomponents/pull/3896
- Documentation on testing updated 
- The old `wdio.js` file copied as `wdio.sync.js`
- When creating a new package, the demo component's test now uses the *asynchronous* syntax
BREAKING CHANGE: The `@wdio/sync` package is no longer a dependency to `@ui5/webcomponents-tools`, therefore the *synchronous* syntax for writing tests is no longer supported out of the box. If you had already written tests,  using the *synchronous* syntax, you must:
- Install `@wdio/sync` manually as a `devDependency` to your project
- Start using `module.exports = require("@ui5/webcomponents-tools/components-package/wdio.sync.js");` in your `config/wdio.conf.js` file.
> chore: Update tests docs

- packages/main/src/List.js
Recently we change the accessibleRole visibility to private as it needed for internal usage only.
Now that it's requested by our stakeholders I am changing it back to public.
Related to: https://github.com/SAP/ui5-webcomponents/issues/3973
> chore(ui5-list): revert accessibleRole visibility to public

- docs/dev/Testing Web Components.md
- packages/base/test/specs/ConfigurationChange.spec.js
- packages/base/test/specs/ConfigurationScript.spec.js
- packages/fiori/test/specs/UploadCollection.spec.js
- packages/fiori/test/specs/ViewSettingsDialog.spec.js
- packages/main/test/specs/DatePicker.spec.js
- packages/main/test/specs/Icon.spec.js
- packages/main/test/specs/Input.spec.js
- packages/main/test/specs/Link.spec.js
- packages/main/test/specs/LitKeyFunction.spec.js
- packages/main/test/specs/Select.spec.js
- packages/main/test/specs/TabContainer.spec.js
- packages/main/test/specs/Toast.spec.js
- packages/main/test/specs/base/InvisibleMessage.spec.js
This is a follow-up to: https://github.com/SAP/ui5-webcomponents/pull/3969
`assert.include` and `assert.notInclude` should be used instead of string manipulation functions.
> refactor: Use assert.include in tests

- packages/main/test/specs/BusyIndicator.spec.js
- packages/main/test/specs/Carousel.spec.js
- packages/main/test/specs/RangeSlider.spec.js
- packages/main/test/specs/Slider.spec.js
- packages/tools/components-package/wdio.js
- Using `executeAsync` to query the browser for an element is ok, but there is an official pattern in WebdriverIO: [Custom locator strategy](https://webdriver.io/docs/api/browser/custom$). A very common use case in our tests is to get the `activeElement` inside a `shadowRoot`. A custom locator strategy is defined globally for that, and used in all relevant tests.
- The `before` and `beforeCommand` lifecycle hooks in `wdio.js` were not awaiting for all async operations (only `afterCommand` was). This is now also fixed.
> refactor: Use custom select strategy in tests

- packages/fiori/src/ShellBar.hbs
The `ui5-button` components used inside `ui5-shellbar` have both `aria-label` and `title` attributes set with the same value. This may lead to double announcement
and trigger warnings by test tools. With this change we remove the `aria-label` attribute. 
Fixes: #3953
> fix(ui5-shellbar): remove unnecessary aria-label from buttons

- packages/base/hash.txt
- packages/fiori/test/specs/Page.spec.js
- packages/fiori/test/specs/Wizard.spec.js
- packages/main/test/specs/BusyIndicator.spec.js
- packages/main/test/specs/ComboBox.spec.js
- packages/main/test/specs/DateTimePicker.spec.js
- packages/main/test/specs/Dialog.spec.js
- packages/main/test/specs/Input.spec.js
- packages/main/test/specs/List.spec.js
- packages/main/test/specs/MultiComboBox.spec.js
- packages/main/test/specs/Panel.spec.js
- packages/main/test/specs/TabContainer.spec.js
- packages/main/test/specs/Table.spec.js
- packages/main/test/specs/TimePicker.spec.js
- packages/main/test/specs/Toast.spec.js
- packages/tools/components-package/wdio.js
This change fixes one often failing test (List - load more button) and re-adds a commented-out similar test.
Using `browser.pause` in tests is generally an anti-pattern. WebdriverIO recommend the `browser.waitUntil` and element `waitFor*` commands instead. See [browser.pause](https://webdriver.io/docs/api/browser/pause/)
The main advantage of `browser.waitUntil` compared to `browser.pause` is that it polls each `500ms` (can be even lowered with the `interval` option) and the test execution immediately resumes after the first time the condition is evaluated to `true`. This may be much sooner than the `timeout` value. This allows to set a high value for the timeout, when uncertain, but in reality the test will rarely wait this much. On the other hand, `browser.pause` blocks test execution …
> refactor: Use waitUntil in tests

- packages/main/test/specs/ComboBox.spec.js
The `waitUntil` covers this assertion.
> chore: remove redundant assert

- packages/base/src/EventProvider.js
In `detachEvents` the `eventRegistry` was never updated when detaching an event, therefore the events weren't cleaned up and caused memory leaks.
Here's an example caused by `attachLanguageChange`, this memory leak occurs with all components that have translatable texts:
1. Open [codeSandbox](https://2qini.csb.app/) in fullscreen mode (for some reason the Performance Monitor doesn't work with codeSandbox in IDE mode - [here you can find the link to the codeSandbox w/o fullscreen mode](https://codesandbox.io/s/hopeful-cannon-2qini?file=/src/App.js))
2. Open dev tools and the [Performance Monitor](https://developer.chrome.com/blog/new-in-devtools-64/#perf-monitor)
3. Click on "Toggle Calendar" multiple times and see that the DOM Nodes are not garbage collected.
I'm not sure where else the …
> fix: detach events correctly to prevent memory leaks

- packages/base/bundle.esm.js
- packages/base/test/specs/EventProvider.spec.js
The test will pass after: https://github.com/SAP/ui5-webcomponents/pull/3941 is merged
**Important:** The error is masked by this code:
```js
if (eventListeners.length === 0) {
eventRegistry.delete(eventName);
}
```
when there is only **1** event listener!
The true test for the error requires that at least one more listener exists before the `detachEvent` is called. This way the `eventRegistry.delete` does not take place, and the memory leak manifests.
> chore: Create a test for EventProvider

- packages/main/src/Icon.js
By design, decorative icons (role=presentation) should also have aria-hidden=true.
Fixes: #3954
> fix(ui5-icon): decorative icons now have aria-hidden=true

- packages/main/src/Input.js
- packages/main/src/features/InputSuggestions.js
- When showSuggestions is set to true, on focus in the dialog is open
- When the dialog is open, the focus remains in the input field within it, no matter there are suggestions available or not.
FIXES: #3848
> fix(ui5-input): Behaviour on mobile device enhanced

- packages/main/src/themes/Popover.css
- packages/main/src/themes/PopupsCommon.css
- packages/main/src/themes/base/PopupsCommon-parameters.css
- packages/main/src/themes/sap_horizon/Popover-parameters.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
The current approach works for both Top & Bottom placement types:
> feat(ui5-popover, ui5-responsive-popover): implement sap_horizon theme

- .reuse/dep5
Fixes #3598 
I changed the following - 
1. I remove the '/' in the `dep5` file for files referring the `MIT` license - as they were not detected under `MIT` license by the reuse tool.
2. I remove the '/' in the `dep5` file for files referring the `BSD-3-Clause-Clear` license - as they were not detected under the  `BSD-3-Clause-Clear` license by the reuse tool.
3. I update the paths of files under `BSD-3-Clause-Clear` license as the files are not present at the old path. 
4. I also remove the line from `dep5` file referring to file - `packages/playground/docs/pages/content/main/diffable-html.js` as the file no longer a part of the repository.
5. Tested the repository for compliance on local system with `reuse version 0.13.0` and it was compliant.
> fix:Updating the dep5 file - Making the repo compatible with reuse 0.13.0

- packages/main/src/TableRow.js
`document.activeElement` does not travers into shadow DOMs.
Therefore, if the `ui5-table` is contained in a shadow DOM, it will never contain `document.activeElement`.
Similarly, the `document.activeElement` will never be the `ui5-table-row`.
To get the desired effect, get the root node for the current element and check which is the activeElement
within that DOM.
Fixes #4023
> fix(ui5-table-row): use activeElement within the current shadow DOM

- packages/main/src/themes/InputIcon.css
- packages/main/src/themes/Select.css
- packages/main/src/themes/base/InputIcon-parameters.css
- packages/main/src/themes/base/Select-parameters.css
- packages/main/src/themes/sap_horizon/InputIcon-parameters.css
- packages/main/src/themes/sap_horizon/Select-parameters.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
The icon's background and color, and the selected option's text within the input field had to be updated to full fill the sap_horizon design. The options will be updated with the list item implementation.
before: Notice how the icon's bg overlaps the focus outline
after: besides the bug with the icon bg, the icon color is changed and the text color is also changed
.
> feat(ui5-select): adjust input and icon to sap_horizon

- packages/main/src/themes/sap_horizon/CheckBox-parameters.css
The border-radius of the square box in now 0.25rem in sap_horizon, not 0.125rem as previously.
> fix(ui5-checkbox): fix component square's border-radius

- packages/main/test/pages/List.html
Exploratory testing bug fixed:
Minor: In the test page, there should be 
items.join("") instead of items.join() because currently there are unwanted comas between the items when we reset the list.
> fix(ui5-list) Sample fix: ',' doesn`t appear after deletion of item

- packages/main/src/themes/PopupsCommon.css
By design the header text should be bold. As we do not know what will be set in the header slot of the popup, by developers or components developers, we will only make bold the when it is set with header-text.
> feat(ui5-popup): adjust bold text in header

- packages/main/src/themes/Panel.css
Add bottom border, when the panel is fixed and expanded, with no header slot.
> fix(ui5-panel): add border bottom, when fixed

- packages/main/src/themes/GrowingButton.css
- packages/main/src/themes/Panel.css
- packages/main/src/themes/Table.css
- packages/main/src/themes/TableColumn.css
- packages/main/src/themes/TableGroupRow.css
- packages/main/src/themes/base/Panel-parameters.css
- packages/main/src/themes/sap_horizon/GrowingButton-parameters.css
- packages/main/src/themes/sap_horizon/Panel-parameters.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
- Add focus outline for More button of table and groups
- Adjust focus border radius for panel depending on the collapse state
- Sticky is now applied to the header row instead of applying it to each column header, since this lead to a visual bug in sap horizon (in future we should remove the remaining logic for sticky in the js of the columns)
> feat(ui5-panel, ui5-table): SAP Horizon focus outline

- packages/main/src/ComboBox.js
- packages/main/test/specs/ComboBox.spec.js
Focus next or previous element on TAB or SHIFT + TAB even if the picker is currently opened.
Issue #3965
> fix(ui5-combobox) always focus the next/previous element on TAB/SHIFT+TAB

- packages/fiori/src/Wizard.js
- packages/fiori/src/WizardStep.js
- Remove accessible-name on Wizard level as it is unneeded, the region has a default aria-label and the wizard itself should be used along with a page with title.
- Remove accessible-name and accessible-name-ref from Wizard Step, as it does not work and also again not needed. The wizard step title is used as a label of the element.
> fix(ui5-wizard): remove unneeded aria properties

- packages/fiori/bundle.common.js
- packages/fiori/bundle.esm.js
Remove it from the common fiori bundle and manually add it to the ESM bundle only.
> chore: do not bundle the barcode scanner component for IE11

- packages/base/package.json
- packages/ie11/hash.txt
- packages/ie11/package.json
- packages/ie11/src/features/IE11.js
- packages/tools/components-package/rollup.js
- packages/tools/package.json
- yarn.lock
- Update `lit-html` to `2.0.1`
- Add the necessary polyfills for IE11 so that `lit-html` can spread DOM nodes. These require `core-js`.
- Disable the source maps for the ES5 build as they do not work well in IE11
> chore: lit-html 2 works fully on IE11

- packages/fiori/src/ShellBar.js
- packages/fiori/test/pages/ShellBar.html
Pressing on custom action throws JS error 
To reproduce, open the link and click on random ui5-shellbar-item 
https://sap.github.io/ui5-webcomponents/master/playground/fiori/pages/ShellBar/
The ShellBarItem used to have template before, but we have recently remove it, and any access to the shadowRoot that previously worked, now resolves to null as the ShellBarItem.
In addition, make the overflow popover open safely by always requiring it explicitly, not relying on a side effect, that other will be called and initialise the popover beforehand.
> fix(ui5-shellbar): press on custom action throws JS error

- packages/fiori/src/ShellBar.js
- add proper JS docs
- fix one of the public getter name + return the correct DOM ref:
overflowlogoDomRef -> overflowDomRef
[data-ui5-stable="notifications"] -> [data-ui5-stable="overflow"]
> fix(ui5-shellbar): fix public readonly getters

- packages/main/src/Breadcrumbs.hbs
- packages/main/src/Breadcrumbs.js
- packages/main/src/BreadcrumbsItem.js
- packages/main/test/specs/Breadcrumbs.spec.js
Remove BreadcrumbsItem's `stableDomRef` public property, as calling `getDomRef` on BreadcrumbsItem's now returns the matching actual DOM ref, typically `ui5-link`.
In case it is requested we can later add API to get the "showMore" link DOM Ref and the matching actual DOM Ref inside the overflow area.
BREAKING CHANGE: BreadcrumbsItem's `stableDomRef` property has been removed - use 
`getDomRef` to get the matching actual DOM ref
> refactor(ui5-breadcrumbs-item): remove stableDomRef public property

- packages/fiori/src/ShellBar.js
- packages/fiori/src/ShellBarItem.js
- packages/fiori/test/pages/ShellBar.html
Change event name from **"item-click"** to **"click"** as  it belongs to the ShellBarItem, not the ShellBar and using "item" in the event's name does not make sense and this is also the rule we used throughout the major API change activity in RC.15.
BREAKING CHANGE: ShellBarItem's event **"item-click"** has been renamed to **"click"**.
> refactor(ui5-shellbar-item): rename "item-click" to "click"

- LICENSES/BSD-3-Clause.txt
This PR fixes #4157 - the standard BSD 3 clause license was missing.
+ Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents/blob/master/CONTRIBUTING.md#how-to-contribute) section 
P.S: The contributing guidelines seem to have moved, please adjust your issue templates: https://github.com/SAP/ui5-webcomponents/blob/master/docs/6-contributing/02-conventions-and-guidelines.md
> chore(reuse): add standard BSD-3-clause license, fixes #4157

- packages/base/hash.txt
- packages/fiori/src/ShellBar.js
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/specs/ShellBar.spec.js
- Fix an issue with the following code, although no longer throws an error as before the recently introduced [fix](https://github.com/SAP/ui5-webcomponents/pull/4287/files) is not complete:
```js
const refItemId = event.target.getAttribute("data-ui5-external-action-item-id");
const shellbarItem = this.items.find(item => {
return this.shadowRoot.querySelector(`#${refItemId}`);
});
```
As this is always true (the clicked item is among all items):
```js
return this.shadowRoot.querySelector(`#${refItemId}`);
```
the result will be always the same - the first ui5-shellbar-item in the array will be returned and the"click" event will be always fired by the first ui5-shellbar-item, although we might click on another custom icon within the bar - the 2nd, 3rd, etc.
- Add a test to avoid …
> fix(ui5-shellbar): fire "click" by the correct abstract ui5-shellbar-item

- packages/fiori/.npmignore
- packages/main/.npmignore
- packages/theming/.npmignore
The CSP-compliance for Firefox/Safari requires the `/dist/css/` directory for the following packages to be in NPM:
- `@ui5/webcomponents-base`
- `@ui5/webcomponents-theming`
- `@ui5/webcomponents`
- `@ui5/webcomponents-fiori`
Currently only  `@ui5/webcomponents-base` ships its .css files.
> chore: start shipping .css files to NPM

- packages/main/src/PopupBlockLayer.hbs
In popups block layer tabindex is set to 1 which is a valiolation of some accessibility html validators. 
To resolve the issue we are setting the tabindex  to 0 of the block layer.
FIXES: 4187
> fix(popups): Tabindex of block layer is 0 

- packages/main/src/themes/CheckBox.css
Checkmark position was set to absolute inside its parent but without concrete position which leads to unwanted behaviour in IE11.
Fixes: #4307
> fix(ui5-checkbox): fix position of checkmark in ie11

- packages/fiori/src/ShellBar.hbs
The stakeholders can't provide own 'title' for the ShellBar's profile button. We show "profile", which is not what the stakeholders need. As currently, it's not possible to replace a specific text in the i18n bundle, we would need to provide either a HBS template hook, or an API to allow developers set their own text. The template hook is the simplest solution without any change in the APIs.
Extract the profile button mark up as Handlebars partial to allow custom component developers to overwrite the Handlebars partial and change the profile button "title" to the desired one.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/4009
> refactor(ui5-shellbar): extract profile btn as HBS partial

- packages/main/src/themes/TimeSelection.css
There is no vertical scroll in the corresponding component
popover when navigated to the time picker part.
> fix(ui5-date-time-picker): proper visualization on mobile

- packages/tools/lib/documentation/templates/template.js
Correct the SAP logo path in the footer to start displaying it.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/3126
> docs: fix SAP logo path

- packages/main/src/Popover.js
- packages/main/test/pages/Popover.html
- Removed unused property `_height`
- Unified switch/case statements
- Added more samples to the test page
> refactor(ui5-popover): simplify calcPlacement()

- packages/fiori/src/ShellBar.hbs
- packages/main/src/TabContainer.hbs
> fix: adding stable selectors for tab container and shellbar

- packages/fiori/src/ShellBar.js
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/specs/ShellBar.spec.js
New property from type Object, called `accessibilityTexts` is introduced to allow customization of some internal parts of the ShellBar web component via stable API. Currently the only thing available on the object is the `profileButtonTitle` to define the profile button tooltip, showing up on hover.
Fixes: #4009
In a plain html, using the property would look like this:
```html
<script>
sbAcc.accessibilityTexts = {
profileButtonTitle: "John Dow",
};
</script>
```
But in a React or similar programming model environment, one should be able to bind a object to this property in the template in a declarative manner.
> feat(ui5-shellbar): introduce accessibilityTexts property

- packages/main/src/DatePicker.js
- packages/main/src/DateRangePicker.js
The inherited methods from ui5-date-picker component, which are not in use
in the ui5-date-range-picker component are pointed out in the documentation.
> docs(ui5-date-range-picker): inherited methods documentation is improved

- packages/base/hash.txt
- packages/main/src/themes/List.css
Part of #4258
When tapping on list items in Chrome on Android, items would unintendedly receive a light-blue overlay.
This change removes this overlay.
> fix(ui5-list): remove highlighting on items after tap on mobile

- packages/fiori/bundle.esm.js
The i18n texts for the fiori package were not exposed via the global testAssets objects.
Now, we can make use of them in the tests.
> chore: add fiori i18n texts to testAssets

- packages/main/src/themes/Input.css
- packages/main/src/themes/TextArea.css
- packages/main/src/themes/base/Input-parameters.css
- packages/main/src/themes/base/TextArea-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Input-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Input-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/TextArea-parameters.css
Text and placeholder styles were not correct in SAP Quartz HC themes according to the specification.
FIXES: #3849
> fix(inputs): adjust value and placeholder styles

- packages/main/src/MessageStrip.hbs
- packages/main/src/MessageStrip.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/specs/MessageStrip.spec.js
Couple enhancements are included in that change:
-> Close button information is read out only once when button is accessed.
-> Information regarding the ui5-message-strip is more comprehensive now.
-> All the texts used are translated.
FIXES: #3447 
FIXES: #4406
> fix(ui5-message-strip): make speech output more comprehensive

- packages/main/src/MessageStrip.hbs
- packages/main/src/MessageStrip.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/specs/MessageStrip.spec.js
Couple enhancements are included in that change:
-> Close button information is read out only once when button is accessed.
-> Information regarding the ui5-message-strip is more comprehensive now.
FIXES: #3447
> make speech output more comprehensive

- packages/main/test/pages/DatePicker.html
- packages/main/test/samples/DatePicker.sample.html
Removes the title attributes from all date picker samples
to comply with the fiori accessibility guidelines.
FIXES: #3534
> fix(ui5-date-picker): do not use the title attribute

- packages/main/src/Input.js
Fixes #3982
The issue comes from the fact that the handler of the event is calling ```event.stopImmediatePropagation();``` and in the meantime, the handler is async. This leads to waiting for the async code to run, while the native event propagates out of the shadow root. And only after that, the code tries to stop the propagation of the native event.
```getInputDOMRef``` method can safely be made sync, because in InputSuggestions constructor, we are calling ```_getSuggestionPopover``` which gets the reference to the responsive popover & later we don't need to look for it in the DOM.
> fix(ui5-input): fix event handling in firefox

- packages/main/src/DateComponentBase.js
- packages/main/test/specs/DatePicker.spec.js
A validity check is now performed while parsing the date value.
Fixes: #4409
> fix(ui5-date-picker): enable date value strict parsing

- packages/playground/assets/js/playground.js
Currently we only set dir="rtl" to the body of the Playground samples, but some of the components need to re-render to apply specific RTL styles and that can be triggered by the `applyDirection` method as suggested in this PR.
There are multiple examples, let's see one
1. Go to https://sap.github.io/ui5-webcomponents/master/playground/components/Table/
2. Observe the first Table sample
3. Set RTL via the Settings menu
4. Some of the texts in the columns' header remain unaligned
5. Run `window["sap-ui-webcomponents-bundle"].applyDirection();` in the console
and observe how the texts are properly aligned.
> fix(Playground): apply RTL properly

- packages/fiori/test/pages/NotificationListGroupItem.html
- packages/fiori/test/pages/NotificationListItem.html
- packages/fiori/test/samples/NotificationListGroupItem.sample.html
Fixed samples when ui5-li-notification-group is used in Shellbar the close button functionality now works
Fixes first issue of #4202
> fix(ui5-li-notification-group): fixed close button functionality in shell bar sample

- packages/main/src/themes/CustomListItem.css
- packages/main/src/themes/base/sizes-parameters.css
CustomListItem is no longer restricted to a hardcoded height. Now it
aligns its height depending on its content.
fixes: #4450
> fix(ui5-li-custom): removed height restriction

- packages/playground/_sass/layout.scss
- display breadcrumbs in the playground
- sets playground padding higher z-index to get over components stylings
FIXES: https://github.com/SAP/ui5-webcomponents/issues/3817
> fix(plaground): adjust main wrapper paddings

- packages/main/src/themes/Input.css
- packages/main/src/themes/base/Input-parameters.css
- packages/main/src/themes/sap_belize_hcb/Input-parameters.css
- packages/main/src/themes/sap_belize_hcw/Input-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Input-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Input-parameters.css
- When text style is italic, the text is usually cut off from the end. The issue is always reproducible in RTL mode, since the text's slope is to the right, but it can be reproduced in LTR mode as well depending on the font used.
FIXES: #3810
> fix(ui5-input): fix value  truncation

- packages/main/src/RadioButton.js
- packages/main/test/pages/RadioButton.html
- packages/main/test/pages/styles/RadioButton.css
- packages/main/test/specs/RadioButton.spec.js
> feat(ui5-radio-button): add accessibleNameRef property

- packages/main/src/Button.hbs
- packages/main/src/Button.js
- packages/main/test/pages/Button.html
- packages/main/test/specs/Button.spec.js
- Receives id(or many ids) of the elements that label the component.
Related to: #4497
> feat(ui5-button): accessibleNameRef property implemented

- packages/base/hash.txt
- packages/base/package.json
- packages/base/src/UI5Element.js
- packages/tools/components-package/rollup.js
- yarn.lock
Added [focus visible polyfill](https://github.com/WICG/focus-visible) to `UI5Element`.
Polyfill adds a `focus-visible` class to the focused element, in situations in which the `:focus-visible` pseudo-selector should match.
Relates to SAP Horizon Experimental theme implementation.
> feat(focus-visible-polyfill): add focus-visible polyfill

- packages/main/src/CardHeader.hbs
- packages/main/src/themes/CardHeader.css
Fixes #4451
The root cause of the issue was a ```dir="auto"```  set on the inner span in the shadow root of the component.
Moreover, the padding was not applied at all if ```action``` slot was present. This is fixed in this PR as well.
> fix(ui5-card-header): fix rtl support

- packages/main/src/Breadcrumbs.js
- packages/main/test/pages/Breadcrumbs.html
- packages/main/test/pages/styles/Breadcrumbs.css
- fixed the code that breaks when there are no items
- additionally, fixed the test page after `separator-class="Slash"` had been mistakenly identified as a `class` attribute by the script that refactored all test pages a while ago and extracted all hard-coded CSS to a separate file
@kineticjs Please investigate how Breadcrumbs should look like with no items and one item only. Currently, even with one item, nothing is displayed. If that is not intended, please create an issue or a follow-up change to fix that.
closes: https://github.com/SAP/ui5-webcomponents/issues/4562
> fix: Breadcrumbs no longer throws an error when empty

- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/ShellBar.js
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/specs/ShellBar.spec.js
Improved accessibilityTexts property to allow customisation of `ui5-shellbar` logo tooltip.
Logo tooltip could be changed in following way:
```
<script>
sbAcc.accessibilityTexts = {
logoTitle: "My new logo title",
};
</script>
```
Fixes: #4426
> feat(ui5-shellbar): improved accessibilityTexts property

- packages/base/hash.txt
- packages/fiori/src/MediaGallery.js
- packages/fiori/src/themes/MediaGallery.css
- packages/fiori/src/themes/ViewSettingsDialog.css
- packages/main/src/ColorPalette.js
- packages/main/src/ColorPalettePopover.hbs
- packages/main/src/ColorPalettePopover.js
- packages/main/src/MultiComboBox.js
- packages/main/src/ResponsivePopover.js
- packages/main/src/Tokenizer.js
- packages/main/src/themes/TabSeparatorInOverflow.css
- packages/main/src/themes/ValueStateMessage.css
⚠️  *Important for component developers:*
UI5 Web Components tag names may vary. Users can take advantage of the "scoping" feature (https://github.com/SAP/ui5-webcomponents/pull/2091), so for example `ui5-button` could be used as `ui5-button-demo`. However, it will always have a `ui5-button` attribute set, no matter what its name is. 
Example
```html
<ui5-button-demo ui5-button>Click me</ui5-button-demo>
```
This attribute will always be there, even if the scoping feature is not used:
Example
```html
<ui5-button ui5-button>Click me</ui5-button>
```
**You must only use this attribute in your code, never the tag name.**
The following are not allowed:
- using the tag name in CSS
- comparing `localName` of a component
- querying the shadow root with a hard-coded local name.
Also, it is …
> fix: Scoping issues corrected

- packages/base/hash.txt
- packages/fiori/src/ShellBar.js
- packages/fiori/src/ShellBarPopover.hbs
We need to wait for DOM to be updated when ui5-popover is closed, otherwise if Enter key is hold there will be no visual indication that this has happened
Fixes: #4556
> fix(ui5-shellbar): allow selection with Enter key in overflow menu

- packages/base/hash.txt
- packages/main/src/Breadcrumbs.js
- packages/main/test/pages/Breadcrumbs.html
- packages/main/test/specs/Breadcrumbs.spec.js
- packages/theming/hash.txt
Add the missing label of breadcrumbs with a single item.
Fixes #4565
> fix(ui5-breadcrumbs): correct missing label for single breadcrumb

- packages/main/test/pages/Breadcrumbs.html
- packages/main/test/specs/Breadcrumbs.spec.js
Two tests checking for item-click event are passing, although the eventlistener isn't called in the test run, probably due to the noConflict configuration here: https://github.com/SAP/ui5-webcomponents/blob/b030586bc7354d9ab9a8074805e54df96246a831/packages/tools/components-package/wdio.js#L308
It can be reproduced by following the commits in this PR chronologically.
> test(ui5-breadcrumbs): fix false-positive event listener tests

- packages/fiori/src/ViewSettingsDialog.js
I've tried to import from `@ui5/webcomponents/dist/ViewSettingsDialog` as indicated `Overview` on [ViewSettingsDialog](https://sap.github.io/ui5-webcomponents/playground/components/ViewSettingsDialog/).
However, it did not work. 
So I modified import component part as same as [document](https://github.com/SAP/ui5-webcomponents/blob/aea5b030fe8115fac4c020c48b40f3941be96c23/packages/fiori/README.md).
`@ui5/webcomponents/dist/ViewSettingsDialog` to `@ui5/webcomponents-fiori/dist/ViewSettingsDialog`.
> doc(ui5-view-settings-dialog): fix imported component doc

- packages/main/src/Link.hbs
- packages/main/src/Link.js
- packages/main/src/types/HasPopup.js
- packages/main/test/pages/Link.html
- packages/main/test/pages/styles/Link.css
- packages/main/test/specs/Link.spec.js
The ui5-link component now supports accessibilityAttributes property,
which enables users to supply additional accessibility attribute
values. As a result the control could now be used as a collapsible
link.
Related to: #3546
> feat(ui5-link): accessibilityAttributes property implemented

- packages/base/hash.txt
- packages/fiori/src/ShellBarItem.js
- packages/fiori/test/pages/ShellBar.html
- packages/fiori/test/specs/ShellBar.spec.js
- packages/main/src/BreadcrumbsItem.js
- packages/main/src/MultiComboBoxItem.js
- packages/main/src/Option.js
- packages/main/src/Tab.js
- packages/main/src/TabSeparator.js
- packages/theming/hash.txt
closes: https://github.com/SAP/ui5-webcomponents/issues/4593
This change allows developers to set stable DOM refs to abstract items via the `stable-dom-ref` attribute.
**Background:**
Currently, all abstract items that support the stable dom ref concept, form their stable dom refs as follows:
```js
`${this._id}-stable-dom-ref`
```
Then, developers can call `getDomRef()` on the abstract item:
```
shellBarItem.getDomRef(); // returns the ui5-button instance in the shadow root
```
The presumption is that developers should only call this method and should not care about how exactly the reference is constructed internally.
**The problem:**
There are scenarios, involving third-party services, that must rely solely on DOM APIs. Therefore, the `.getDomRef()` invocation solution is not always …
> feat: stable-dom-ref supported for abstract items

- packages/main/src/Popover.js
- packages/main/test/pages/PopoverArrowBounds.html
- packages/main/test/pages/styles/PopoverArrowBounds.css
Part of #4581
The arrow of the Popover is now restricted within a range along each
dimension.  The border-radius of the Popover in the different themes is
considered.
This solves the issue where the Popover may be opened by a
small element placed at the corners of the viewport.
> fix(ui5-popover): restrict arrow going out of bounds

- packages/main/src/SplitButton.js
- packages/main/test/pages/SplitButton.html
- packages/main/test/specs/SplitButton.spec.js
When the default slot is empty, e.g no text is provided, the `this.text[0].textContent` throws an error. 
Instead, call to `this.textContent` is sufficient.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/4609
> fix(ui5-split-button): fix JS error on empty text content

- packages/fiori/src/MediaGalleryItem.js
The icon is used within the template, but not imported and may cause an error in apps that don't load the entire icons bundle, but import only the icons they use.
> fix(ui5-media-gallery-item): add missing icon import

- packages/main/src/themes/base/Title-parameters.css
This PR replaces the custom heading level with the theme dependant `theming-base-content` CSS vars. 
I am not sure if this was implemented this way on purpose. If it was, feel free to close this PR, but please explain why it was implemented like this :)
> fix(ui5-title): replace custom heading CSS vars with SAP theming-base vars

- packages/fiori/src/types/MediaGalleryLayout.js
This PR replaces the `@type` annotations to the correct ones for `MediaGalleryLayouts`. 
The wrong annotations led to incorrect entries in our React wrapper implementation, which we fixed manually, so it is not urgent that the PR is merged.
> docs(ui5-media-gallery): fix types for `MediaGalleryLayouts`

- packages/base/hash.txt
- packages/base/src/Runtimes.js
- packages/base/src/features/F6Navigation.js
- packages/base/src/util/metaUrl.js
`import.meta.url` breaks on webpack 4, and with webpack 5 gets resolved at build time to the file system path which is not the intended use of the feature.
Fixes: #4627
> fix: remove import.meta.url

- docs/4-frameworks/03-Vue.md
Update Vue related docs as with Vue 3.x there is a  BREAKING change - the Custom elements whitelisting is now performed during template compilation, and should be configured via compiler options instead of runtime config.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/4637
> docs: update Vue + UI5WebComps docs

- packages/main/src/themes/SelectPopover.css
- packages/main/src/themes/Suggestions.css
- packages/main/src/themes/base/sizes-parameters.css
List items of suggestion popovers are now aligned with FIori visual specification and have correct height of 2.5rem for Cozy and 2rem for Compact.
Fixes: #4616
> fix(popovers): correct list items height of input dropdowns

- packages/main/src/FileUploaderPopover.hbs
fixes: https://github.com/SAP/ui5-webcomponents/issues/4592
> fix(ui5-file-uploader): fixing the console warning

- packages/base/hash.txt
- packages/main/src/TreeListItem.js
ListItem is extended by TreeListItem. ListItem has its own onDefine method which is not called by TreeListItem's onDefine method which leads to errors when `ui5-li-tree` is used and ListItem is not imported separately.
Solution is based on: #4128 
Fixes: #4667
> fix(ui5-li-tree): correct usage of i18nBudnle

- packages/fiori/README.md
- packages/fiori/src/MediaGalleryItem.js
- packages/main/README.md
- packages/main/src/Select.js
- packages/main/src/SplitButton.js
- packages/main/src/themes/SplitButton.css
- packages/main/test/samples/ColorPalette.sample.html
- fix SplitButton styles - it relies on ui5-button, instead of the system [ui5-button] attribute, breaking the scoping case.
- fix some issues in the SplitButton's Overview section
- update public module imports
> chore: fix docs and tag misuse in CSS

- packages/base/hash.txt
- packages/main/src/TabContainer.js
The issue occurs in a case where TabContainer's handleResize gets
called before onAfterRendering. At that point, TabContainer hasn't
rendered its own representation of the tabs (stripPresentation)
which it later relies on.
Part of #4628
> fix(ui5-tabcontainer): await for renderFinished in resize handler

- packages/main/src/SplitButton.js
Fix typo on [split-button](https://sap.github.io/ui5-webcomponents/playground/components/SplitButton/)
**"(double quotes)** is missing from the documentation!
> doc(ui5-split-button): fix import module doc typo

- packages/main/src/DatePickerPopover.hbs
- packages/main/src/themes/Calendar.css
- packages/main/src/themes/base/DayPicker-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/DayPicker-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/DayPicker-parameters.css
The ui5-calendar component styles are now adjusted according to the visual specification.
- The ui5-datepicker popover content paddings are now removed.
- The ui5-calendar component paddings are now compliant with the visual specification for cozy and compact form factor mode.
- The font styles and colors of the ui5-calendar-header buttons, week numbers and day names are now compliant with the visual specification.
> fix(ui5-calendar): adjust picker styles

- docs/5-development/03-understanding-components-metadata.md
- packages/tools/lib/documentation/templates/api-properties-section.js
- packages/tools/lib/jsdoc/plugin.js
- packages/tools/lib/jsdoc/template/publish.js
With this change we enhance the JSDOC parser to automatically omit attribute names for properties of type "Object" or "object". The code literally checks if the type is equal to the "Object" and "object" strings.
```js
/**
* @type {object}
* @public
*/
```
To complement the auto detection which only checks for the "Object" and "object" strings, we also introduce a new JSDOC tag, called "noattribute" to manually and explicitly tag a member for which the attribute counterpart should not be displayed in the API reference:
```js
/**
* @noattribute
* @public
*/
```
After this change the attribute counterpart of the following properties of type Object will be omitted (automatically detected):
- Links
accessibilityAttributes
- ShellBar
accessibilityTexts
- FCL
accessibilityRoles …
> feat(jsdoc): remove attr name for Object props

- docs/2-advanced/07-accessibility.md
- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/ShellBar.js
- packages/fiori/src/ShellBarPopover.hbs
- packages/main/src/AvatarGroup.hbs
- packages/main/src/AvatarGroup.js
- packages/main/src/Button.hbs
- packages/main/src/Button.js
- packages/main/src/MessageStrip.hbs
- packages/main/src/MessageStrip.js
- packages/main/src/Panel.hbs
- packages/main/src/Panel.js
- packages/main/src/SegmentedButtonItem.hbs
- packages/main/test/pages/Button.html
- packages/main/test/pages/styles/Button.css
- packages/main/test/samples/Dialog.sample.html
- packages/main/test/specs/AvatarGroup.spec.js
- packages/main/test/specs/Button.spec.js
The ui5-button component now supports 'accessibilityAttributes' property,
which enables users to supply additional accessibility attributes for
the button element.
A standard use case would be to provide the corresponding accessibility attributes
for a button opening a popover or a dialog.
Related to: #3546
> feat(ui5-button): implement accessibilityAttributes property

- packages/base/hash.txt
- packages/base/src/util/TabbableElements.js
The code in `TabbableElements.js` may throw an error, if the shadow root is empty, because `currentNode` will be `undefined` and then the following code will be executed:
```js
if (currentNode.tagName === "SLOT") {
```
> fix(framework): Tabbable elements error

- packages/main/src/DatePicker.js
- packages/main/test/specs/DatePicker.spec.js
The following changes would affect the ui5-date-picker, ui5-daterange-picker and ui5-datetime-picker components:
- The combobox role is now removed from the inner input field for compliance with the accessibility specification.
- The aria-haspopup attribute value is updated to "grid" instead of "true".
> fix(ui5-date-picker): remove combobox role

- packages/main/src/ColorPicker.js
- packages/main/test/specs/ColorPicker.spec.js
> fix(ui5-color-picker): adjust hue value update when user presses over the main color section

- packages/main/src/themes/base/Switch-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/src/themes/sap_belize_hcb/Switch-parameters.css
- packages/main/src/themes/sap_belize_hcw/Switch-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Switch-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Switch-parameters.css
- packages/main/src/themes/sap_horizon/Switch-parameters.css
- packages/main/src/themes/sap_horizon_exp/Switch-parameters.css
The ui5-switch component focus outline is drawn
with the help of a pseudo element. This pseudo
element is displayed bigger than the actual
ui5-switch root element. As a result the focus
outline could get cut off.
Related to: #2925
> fix(ui5-switch): adjust focus outline

- packages/main/src/themes/base/Switch-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/src/themes/sap_belize_hcb/Switch-parameters.css
- packages/main/src/themes/sap_belize_hcw/Switch-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Switch-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Switch-parameters.css
- packages/main/src/themes/sap_horizon/Switch-parameters.css
- packages/main/src/themes/sap_horizon_exp/Switch-parameters.css
The change is reverted, in order to go trough the core team review.
Reverts SAP/ui5-webcomponents#4665
> Revert "fix(ui5-switch): adjust focus outline"

- packages/main/src/DatePickerPopover.hbs
- packages/main/src/TimePickerPopover.hbs
The `stayOpenOnScroll` private property has been removed from the Popover long time ago with the [PR](https://github.com/SAP/ui5-webcomponents/pull/779)
> chore: remove non-existing props

- packages/main/src/Link.hbs
- packages/main/src/Link.js
- packages/main/test/pages/Link.html
- packages/main/test/specs/Link.spec.js
add new property "accessibleName"
Fixes: #4498
> feat(ui5-link): provide accessible-name support

- packages/fiori/src/Timeline.hbs
- packages/fiori/src/Timeline.js
- packages/fiori/test/pages/Timeline.html
- packages/fiori/test/specs/Timeline.spec.js
add new property "accessibleName"
FIXES: #4644
> feat(ui5-timeline): provide accessible-name support

- packages/main/test/samples/TabContainer.sample.html
Attribute `text` was missing a `t` for component `ui5-tabcontainer`.
> doc(ui5-tabcontainer): fix typo in code sample

- packages/main/src/Switch.js
- packages/main/test/pages/Switch.html
- packages/main/test/specs/Switch.spec.js
Application developers could now provide additional label
text for the aria-label attribute of the ui5-switch root element
trough the "accessibleName" property.
Fixes: #4147
> feat(ui5-switch): provide accessible-name attribute support

- packages/main/src/Input.hbs
The attribute aria-invalid="true" is now fully rendered, as otherwise, it will not be announced by JAWS screen reader.
Fixes #4723
> fix(ui5-input): aria-invalid is now properly rendered

- packages/main/src/Calendar.hbs
- packages/main/src/DatePicker.hbs
- packages/main/src/List.hbs
- packages/main/src/Panel.hbs
- packages/main/src/StepInput.hbs
Replaces the HTML comments inside the HBS templates with HBS comments as suggested in the related issue and following the [official docs](https://handlebarsjs.com/examples/comments.html). The HBS comments are stripped from the output and are available only to developers at DEV time, while the HTML ones are part of the output and could be observed in the browser. After this change only the lit-html comments can be seen.
Previously (the comment is part of the lit template)
```js
const block0 = (context, tags, suffix) => html`<div class="ui5-panel-root"><div @click="${context._headerClick}"
```
After (the comment is removed)
```js
const block0 = (context, tags, suffix) => html`<div class="ui5-panel-root"><div @click="${context._headerClick}"
```
As the related issue suggests, I went trough …
> fix(templates): replace HTML comments with HBS ones

- packages/main/src/Button.js
- packages/main/src/themes/Button.css
Focus outline removed on phone and tablet devices. Now "focused" attribute is placed only on Desktop devices.
> fix(ui5-button): remove focus on phone and tablet

- packages/main/src/ColorPalettePopover.js
Including the name of the slot in the documentation
> fix(ui5-color-palette-popover): update documentation

- packages/base/hash.txt
- packages/base/src/Boot.js
- packages/base/src/util/InvisibleMessage.js
With the old implementation it was possible for `boot` to run without executing all attached callbacks (the ones attached after boot is over).
Additionally, reworked `InvisibleMessage.js` to be CSP-compliant.
> fix: attached boot tasks always run

- packages/fiori/src/FlexibleColumnLayout.hbs
- packages/fiori/src/NotificationListGroupItem.hbs
- packages/fiori/src/NotificationListItem.hbs
- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/UploadCollectionItem.hbs
- packages/fiori/test/pages/Bar.html
- packages/fiori/test/pages/BarcodeScannerDialog.html
- packages/fiori/test/pages/Page.html
- packages/fiori/test/samples/Bar.sample.html
- packages/fiori/test/samples/Bar2.sample.html
- packages/fiori/test/samples/BarcodeScannerDialog.sample.html
- packages/fiori/test/samples/Page.sample.html
- packages/fiori/test/specs/FCL.spec.js
- packages/main/src/Button.hbs
- packages/main/src/Button.js
- packages/main/src/Carousel.hbs
- packages/main/src/Link.js
- packages/main/src/ListItem.hbs
- packages/main/src/MessageStrip.hbs
- packages/main/src/Panel.hbs
- packages/main/src/TabContainer.hbs
- packages/main/test/pages/Button.html
- packages/main/test/specs/Button.spec.js
Problem description:
The ui5-button tooltip text was supplied trough the
private "title" property. As result the same title
attribute was placed to the ui5-button element and
to the inner native button element, which was causing
duplicate tooltip announcements.
Solution:
New public "tooltip" property is added, which results
in placing "tooltip" attribute to the ui5-button element
and a "title" attribute to the inner native button element.
Fixes: #4689
> feat(ui5-button): add new tooltip property

- packages/tools/lib/documentation/templates/template.js
For child components, like the TreeItem, the playground only displays props and slots, but not methods. The change adds the method API info.
> fix: display methods in child components API

- packages/main/src/RadioButton.hbs
- packages/main/src/themes/RadioButton.css
- packages/main/src/themes/base/RadioButton-parameters.css
- packages/main/src/themes/sap_horizon_exp/RadioButton-parameters.css
SAP Horizon Experimental theme implementation for **Radio Buttons**.
I've added `viewBox` to `svg` tag to prevent the initial showing of the big unstyled svg.
If there are some concerns kindly let me know.
Theme name: **sap_horizon_exp**
> feat(ui5-radio-button): implement sap_horizon_exp theme

- packages/main/src/themes/ListItemBase.css
- packages/main/src/themes/base/ListItemBase-parameters.css
- packages/main/src/themes/sap_horizon/ListItemBase-parameters.css
**Background**
For some reason the bottom-border **--ui5-listitem-border-bottom**  has been left **transparent** in sap_horizon only 
and this parameter is responsible for the default (rest) state. In this state the bottom border is needed to separate the list items.
Changes:
- Show the border-bottom line in rest state, so that the list items are separated.
Additional  Changes. When comparing to the UI5 List I noticed other issues
- the focus outline merges with the selection outline of previous/next items. Add 1px offset to the focused outline to ensure it does not merge with the selection bottom border line of the next or previous items.
- the selection border-bottom is missing
before
after
FIXES: https://github.com/SAP/ui5-webcomponents/issues/4803
> fix(ui5-list): fix separators in SAP Horizon

- packages/main/src/Input.js
- packages/main/src/Panel.js
If a component is used in the `.hbs` of another component, but is not in `dependencies`, then it won't be scoped when scoping is enabled.
> fix: describe all dependencies for some components

- packages/base/hash.txt
- packages/main/src/List.js
- packages/main/test/pages/List_test_page.html
- packages/main/test/specs/List.spec.js
Compared to OpenUI5 current focus behaviour is not correct. Correct behaviour is:
- If the focus enters the list for first time the focused element should be the first list item.
- If some of the list items was focused in the past it should be focused again when the focus comes back to the list.
Fixes: #4806
> fix(ui5-list): initial focus target

- packages/fiori/src/FlexibleColumnLayout.hbs
- packages/fiori/src/FlexibleColumnLayout.js
- packages/fiori/test/pages/FCL.html
- packages/fiori/test/specs/FCL.spec.js
Hidden columns are rendered in the DOM but not visible to the users, so they should be hidden from the accessibility tree.
Summary:
- remove the role attribute
- aria-hidden attribute set to true
Fixes: #4789
> fix(ui5-flexible-column-layout): improve accessibility

- packages/fiori/src/MediaGalleryItem.js
Corrected the jsdoc to specify that the app should be providing only a single item in the "content" and "thumbnail" slots of the ui5-media-gallery-item 
Any other items (second etc.) in those slots are currently ignored.
> fix(ui5-media-gallery-item): correct jsdoc

- packages/main/src/themes/Avatar.css
- packages/main/test/pages/AvatarGroup.html
- packages/main/test/samples/AvatarGroup.sample.html
In Playground sample, when avatar with image is clicked the image disappears, showed in the Popover. After clicking again
it disappears from both places. It is now fixed, applying a cloned node, instead of original one.
Fixes #4812
> fix(ui5-avatar-group): Fixed sample with image avatars

- packages/fiori/src/MediaGallery.js
Changed the tag-name selector to use attribute-name instead, as recommended by best practice.
> fix(ui5-media-gallery): correct selector

- packages/main/src/Popup.js
- packages/main/src/themes/PopupGlobal.css
- packages/main/test/pages/Dialog.html
- packages/main/test/pages/styles/Dialog.css
- packages/main/test/specs/Dialog.spec.js
Popups add styles to the body element to prevent scrolling, which can disrupt the layout of the page.
Now the scrolling is prevented by adding `overflow: hidden` style to the html element.
Fixes #4347
> fix(ui5-popup): body styles are no longer modified 

- packages/main/test/pages/DatePicker_test_page.html
- packages/main/test/specs/DatePicker.spec.js
- The DateFormat's parse method wasn't expected
to call getDate on the already correctly parsed
JavaScript Date object. The result is declared
invalid and replaced with null when the day doen't
match the one from the string. The time-zone test
is removed as we don't have a way to mock the JS Date.
Fixes: #4443
> fix(ui5-date-picker): remove time-zone test

- packages/base/src/Keys.js
- packages/main/src/MultiComboBox.js
- packages/main/src/Token.js
- packages/main/src/Tokenizer.js
- packages/main/test/specs/MultiComboBox.spec.js
Issue: #3090
Note: The CTRL+ SPACE handling should be implemented in the List, - as the 'Space' selection functionality, or not implemented at all, if it is not by the List UX specifications. 
Doing it in the MultiComboBox is wrong (if possible) as the individual 'SPACE' key is handled in the List.
> feat(ui5-multi-combobox, ui5-tokenizer):  Handle 'Space' key combinations

- packages/main/src/DatePicker.js
- packages/main/src/TimePicker.js
- packages/main/test/specs/DatePicker.spec.js
The aria-expanded attribute is removed from the
ui5-date-picker, ui5-daterange-picker, ui5-datetime-picker
input element for compliance with the combobox role removal.
Fixes: #4865
> fix(ui5-date-picker): remove aria-expanded attribute

- packages/fiori/src/FlexibleColumnLayout.js
- packages/main/src/types/ListGrowingMode.js
- packages/main/src/types/TableGrowingMode.js
1) The event `layoutChange` in `ui5-flexible-column-layout`:
```js
/**
* Fired when the layout changes via user interaction by clicking the arrows
* or by changing the component size due to resizing.
*
* @param {FCLLayout} layout The current layout
* @param {Array} columnLayout The effective column layout, f.e [67%, 33%, 0]
* @param {boolean} startColumnVisible Indicates if the start column is currently visible
* @param {boolean} midColumnVisible Indicates if the middle column is currently visible
* @param {boolean} endColumnVisible Indicates if the end column is currently visible
* @param {boolean} arrowsUsed Indicates if the layout is changed via the arrows
* @param {boolean} resize Indicates if the layout is changed via resizing
* @event …
```
> refactor: several fixes

- packages/main/src/DatePicker.js
- packages/main/test/specs/DatePicker.spec.js
- packages/main/test/specs/DateRangePicker.spec.js
- We don't need explicit handling on enter keyboard key
press after adaptations in the ui5-input control related
to change event handling.
Fixes: #4826
> fix(ui5-date-picker): handle date selection via enter keyboard key

- packages/fiori/src/themes/ViewSettingsDialog.css
- packages/main/src/themes/Title.css
- packages/main/src/themes/base/Title-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
- packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
- packages/main/src/themes/sap_horizon/parameters-bundle.css
- packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
- packages/main/src/themes/sap_horizon_exp/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcb/parameters-bundle.css
- packages/main/src/themes/sap_horizon_hcw/parameters-bundle.css
The `ui5-title` used custom `ui5-` css variables for configuring the font size. As they are consistent in all themes I removed the custom variables which makes it more intuitive to modify the title font sizes via SAP Theme Designer.
> refactor(ui5-title): remove custom css variables

- packages/fiori/src/MediaGallery.js
- packages/fiori/test/pages/MediaGallery.html
- packages/fiori/test/pages/styles/MediaGallery.css
- packages/fiori/test/specs/MediaGallery.spec.js
When the container of the ui5-media-gallery is initially narrow enough to allow room only for the overflow button to be rendered, then all items should overflow and the label of the overflow button should be correct.
Fixes #4902
> fix(ui5-media-gallery): correct overflow label

- packages/main/src/themes/StepInput.css
- packages/main/src/themes/base/StepInput-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/4786
Aligning the minimum width of the step input control to specification.
There is no specific min width by the design team, but by their suggestions we have to combine min width of input field, two buttons and also the borders of the buttons inside.
> fix(ui5-step-input): align the min width to visual specification

- packages/fiori/src/FlexibleColumnLayout.hbs
- packages/fiori/src/themes/FlexibleColumnLayout.css
Mirrored border styles (border-left <=> border-right) when RTL is set to the flexible column layout.
Fixes: #4906
> fix(ui5-flexible-column-layout): correct column border styles for RTL

- packages/base/hash.txt
- packages/base/src/css/FontFace.css
**Issue**
The **72-Bold** font did not apply correctly on stakeholder side in FireFox (see the linked issue for more information.).
This can be also reproduced in our test pages by opening the Card test page **in sap_horizon in FireFox** via this [link](https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Card/?sap-ui-theme=sap_horizon).
The headings in the Card header should have been bold, however they appear normal instead. I
In Chrome the issue is not reproducible, probably because of difference in the font loading.
**Solution**
The insertion of the **72-Bold,  '72-Boldfull', '72-Light' and  '72-Lightfull'** fonts explicitly as part of the system vars
seem to resolve the issue. The changes is adding the ones that are missing, compared to …
> fix(framework): add more 72-* fonts as system styles

- packages/main/src/ListItemBase.js
When content list item content contains focusable element double focus appear (one to the list item and one to the nested focusable element). Now, we are not marking list item as focused if it is different from focus target.
Fixed: #4916
> fix(ui5-li): correct focus handling

- CHANGELOG.md
- lerna.json
- packages/base/CHANGELOG.md
- packages/base/package.json
- packages/create-package/CHANGELOG.md
- packages/create-package/package.json
- packages/fiori/CHANGELOG.md
- packages/fiori/package.json
- packages/icons-business-suite/CHANGELOG.md
- packages/icons-business-suite/package.json
- packages/icons-tnt/CHANGELOG.md
- packages/icons-tnt/package.json
- packages/icons/CHANGELOG.md
- packages/icons/package.json
- packages/ie11/CHANGELOG.md
- packages/ie11/package.json
- packages/localization/CHANGELOG.md
- packages/localization/package.json
- packages/main/CHANGELOG.md
- packages/main/package.json
- packages/playground/CHANGELOG.md
- packages/playground/docs/landing-page.html
- packages/playground/package.json
- packages/theming/CHANGELOG.md
- packages/theming/package.json
- packages/tools/CHANGELOG.md
- packages/tools/package.json
This is an intermediate patch release due to approaching DEV close on stakeholders' side. 
The releases include only pre-selected set of fixes on important stakeholders' issues.
The change log can be seen here:
1.2.2
- Changelog https://github.com/SAP/ui5-webcomponents/releases/tag/v1.2.2
- The release to NPM is performed from the https://github.com/SAP/ui5-webcomponents/tree/release-1.2.2 branch.
1.2.3
- Changelog https://github.com/SAP/ui5-webcomponents/releases/tag/v1.2.3
- The release to NPM is performed from the https://github.com/SAP/ui5-webcomponents/tree/release-1.2.3 branch.
> chore: release v1.2.3

- packages/base/src/renderer/executeTemplate.js
Currently, we determine the tags that need to be scoped within components' templates,
based on the component's unique dependencies + app defined rules trough configuration:
```js
// executeTemplate.js
component.constructor.getUniqueDependencies().map(dep => dep.getMetadata().getPureTag()).filter(shouldScopeCustomElement);
```
However, there is one use-case when the Input web components uses `ui5-input` inside the InputPopoverTemplate
```hbs
// InputPopover.hbs
<div class="input-root-phone">
<ui5-input>
```
which is currently skipped from scoping due to the check below as the Input is not a dependency of itself
```js
// LitRenderer.js
// suffix && (tags || []).includes(tag) is falsy
const scopeTag = (tag, tags, suffix) => {
const resultTag = suffix && (tags || []).includes(tag) ? …
```
> fix(framework): fix scoping of self tag

- packages/main/src/DatePicker.js
- packages/main/test/pages/DatePicker_test_page.html
- packages/main/test/specs/DatePicker.spec.js
Problem description:
When a value string is provided initially with an incorrect
format pattern, then this value gets cleared in the on
before rendering hook.
Solution:
The initial value remains unchanged if the internal formatter
isn't able to parse it.
Fixes: #4958
> fix(ui5-date-picker): adjust initial value formatting

- packages/main/src/DateTimePickerPopover.hbs
- packages/main/src/TimeSelection.js
- packages/main/test/pages/DateTimePicker.html
- packages/main/test/samples/DateTimePicker.sample.html
- packages/main/test/specs/DateTimePicker.spec.js
- Secondary calendar type value is propagated to the
ui5-datetime-picker component trough it's popover view.
Fixes: #4959
> fix(ui5-datetime-picker): enable secondary calendar type

- packages/main/src/TimePickerBase.js
- packages/main/test/specs/TimePicker.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/4918
> fix(ui5-time-picker): firing change event after input change submit

- packages/main/src/Input.js
- packages/main/test/pages/Input.html
- packages/main/test/specs/Input.spec.js
A new `openPicker()` method for manually opening the suggestions popover has been introduced.
Usage:
```js
<ui5-input id="myInput" show-suggestions></ui5-input>
------
myInput.addEventListener("event-type", () => {
fetch(myRequest)
.then((response) => {
// Arrange items before calling openPicker, to prevent an empty popover from showing
myInput.openPicker();
});
});
```
A sample implementation with recent item history will be available in [Input with openPicker() on focusin
](https://sap.github.io/ui5-webcomponents/master/playground/main/pages/Input/#openPickerInput) once merged.
> feat(ui5-input): introduce openPicker() functionality

- packages/main/src/Input.js
- packages/main/test/pages/Input.html
After this change, suggestion items must be preloaded for `openPicker` to take effect. The documentation has been updated accordingly.
> refactor(ui5-input): prevent opening an empty picker and update docu

- packages/main/src/TokenizerPopover.hbs
The paddings in the nMore responsive popover have been adjusted on mobile to match the VD spec. 
Previously, the custom header was applied only when a value state message was present. Now it is always applied, as there is currently no other way to determine when to set side padding (depending on the presence of a value state) on the built-in header :part of the ResponsivePopover.
Fixes: #4871
> fix(ui5-tokenizer): correct header paddings in nMore popover

- packages/main/src/Label.hbs
> fix(ui5-label): prevent screenreader announcement of colon and asterisk

- .travis.yml
- deploy/deploy.sh
- package.json
- packages/tools/components-package/nps.js
- packages/tools/components-package/rollup.js
After the IE11 cleanup the rollup script no longer needs:
- `DEPLOY_PUBLIC_PATH`
- context overwrite for `url-search-params-polyfill`
> chore: remove DEPLOY_PUBLIC_PATH

- packages/base/src/Device.js
- packages/main/src/ComboBox.js
Autocomplete is now disabled on Android as it caused clashes with the soft keyboard.
Fixes: #5039
> fix(ui5-combobox): disable autocomplete on Android

- packages/base/hash.txt
- packages/tools/lib/hbs2ui5/index.js
When rollup is in `watch` mode, and you change an `.hbs` file, this leads to all templates for the project being recompiled. This updates tens of files on the file system, leading to a big reaction by rollup. This is the reason you see several "created dist/resources in 3.7s" rollup messages in the console one after the other - rollup detects some files changed and recreates the bundle, but then it detects more files and does it again, potentially several times.
The proposed optimization only updates the files that really changed. Side effects:
- if you change whitespaces in an `.hbs` file, rollup will not rebuild (as this will not produce a different template result)
> refactor: optimize templates disk writes

- packages/fiori/src/MediaGallery.hbs
- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/themes/MediaGallery.css
- packages/fiori/src/themes/ShellBar.css
- packages/main/src/ProgressIndicator.hbs
- packages/main/src/Select.hbs
- packages/main/src/themes/ProgressIndicator.css
- packages/main/src/themes/Select.css
- packages/main/src/themes/base/Select-parameters.css
- packages/main/src/themes/base/rtl-parameters.css
- packages/main/src/themes/sap_belize_hcb/Select-parameters.css
- packages/main/src/themes/sap_belize_hcw/Select-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/Select-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/Select-parameters.css
- packages/main/src/themes/sap_horizon_hcb/Select-parameters.css
- packages/main/src/themes/sap_horizon_hcw/Select-parameters.css
- packages/main/test/pages/ProgressIndicator.html
Hello @SAP/ui5-webcomponents-topic-p 
this is related to the recently stopped support of IE, allowing us to implement RTL using features, not supported on IE, as the CSS logical properties. 
The Browser flips the paddings, margins, etc. automatically based on the direction - there is no need to write specific RTL styles manually. At least for the styles that have CSS logical prop alternative.
In case, there is no CSS logical props alternative or the use-case is very specifi, we can extract CSS vars which will have different value in RTL and LTR and add them to global rtl-parameters.css. The same pattern (sizes-parameters.css) that we currently use for the cozy/compact styles.
Doing so, from one hand side we turn more to native implementation and standards, from the other we want to avoid …
> refactor(ui5-shellbar, ui5-progress-indicator, ui5-select, ui5-media-gallery): refactor RTL implementation - part 3

- packages/base/package.json
- yarn.lock
Set the version as `^2.0.1` so that existing apps don't have to change anything, if running `2.0.1`.
However, internally upgrade to `2.2.2` for our libraries.
With this change apps that use any `lit-html` 2 version (`2.x`) will not bundle the library twice.
closes: #5109
> chore: upgrade lit-html to 2.2.2

- packages/base/hash.txt
- packages/main/src/Tab.js
- packages/main/src/TabContainer.js
- packages/main/src/TabInOverflow.hbs
- packages/main/src/TabInStrip.hbs
- packages/main/src/TabSeparator.js
- packages/main/src/themes/TabContainer.css
- packages/main/src/themes/TabInOverflow.css
- packages/main/src/themes/TabInStrip.css
- packages/main/src/themes/TabSemanticIcon.css
- packages/main/src/themes/TabSeparatorInOverflow.css
- packages/main/src/themes/base/TabContainer-parameters.css
- packages/main/src/themes/sap_belize/TabContainer-parameters.css
- packages/main/src/themes/sap_belize_hcb/TabContainer-parameters.css
- packages/main/src/themes/sap_belize_hcw/TabContainer-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/TabContainer-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/TabContainer-parameters.css
- packages/main/src/themes/sap_horizon/TabContainer-parameters.css
- packages/main/src/themes/sap_horizon_dark/TabContainer-parameters.css
- packages/main/src/themes/sap_horizon_exp/TabContainer-parameters.css
- packages/main/src/themes/sap_horizon_hcb/TabContainer-parameters.css
- packages/main/src/themes/sap_horizon_hcw/TabContainer-parameters.css
- packages/main/test/pages/TabContainer.html
- packages/main/test/specs/TabContainer.spec.js
- packages/theming/hash.txt
- Semantic icons are now displayed using Icon components.
- The design property is no longer visualised when the tab is disabled.
Fixes: #2540
> feat(ui5-tabcontainer): enable semantic icons in high contrast themes

- packages/main/src/Dialog.hbs
- packages/main/src/Popup.hbs
- packages/main/src/themes/Dialog.css
- packages/main/src/themes/Popover.css
- packages/main/src/themes/ResponsivePopover.css
- packages/main/src/themes/base/rtl-parameters.css
Hello https://github.com/orgs/SAP/teams/ui5-webcomponents-topic-rd
this is related to the recently stopped support of IE, allowing us to implement RTL using features, not supported on IE, as the CSS logical properties.
The Browser flips the paddings, margins, etc. automatically based on the direction - there is no need to write specific RTL styles manually. At least for the styles that have CSS logical prop alternative.
In case, there is no CSS logical props alternative or the use-case is very specific as with the Popover's arrow margins, which are different in RTL and LTR (not even mirrored), we extract them as CSS vars and add them to global rtl-parameters.css as we do for the cozy/compact styles.
Doing so, from one hand side we turn more to native implementation and standards, from the …
> refactor(ui5-popups): refactor RTL implementation - part 4

- package.json
- packages/base/hash.txt
- packages/theming/hash.txt
- packages/tools/components-package/nps.js
Parallelize as many tasks as possible, both on **monorepo** level and **components package** (main/fiori) level.
This optimization reduces the build time (from clean state) by *35 sec* on my local machine.
**On the build server:**
Before the change: 
After the change:
> chore: parallelize build tasks

- packages/base/src/css/FontFace.css
The subpath `/sdk/` is a legacy path for the SDK which must be avoided. The SDK is now deployed to the context root.
+ Especially the [How to Contribute](https://github.com/SAP/ui5-webcomponents/blob/master/CONTRIBUTING.md#how-to-contribute) section 
> fix(base): use fonts from proper SDK URL

- .github/actions/pre-release.js
The playground's package.json has not been ignored, now it is excluded. Somehow the [ignoreFiles](https://github.com/sindresorhus/globby#ignorefiles) option did not work as expected. I checked the docs - "ignoreFiles: Glob patterns to look for ignore files, which are then used to ignore globbed files." but could not make it work, so I used the "!" syntax.
> chore: ignore playground package

- packages/main/src/themes/TextArea.css
- packages/main/src/themes/base/TextArea-parameters.css
- packages/main/src/themes/sap_belize_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_belize_hcw/TextArea-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/TextArea-parameters.css
- packages/main/src/themes/sap_horizon_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_horizon_hcw/TextArea-parameters.css
Related to: #5007 
FIXES: #5169
> fix(ui5-textarea): adjust placeholder styling

- packages/base/src/asset-registries/Themes.js
- packages/base/test/specs/Theming.spec.js
When the user sets unknown theme, the fallback does not quite work. The framework correctly displays a warning, but the theme parameters are not returned (as the theme parameters map ends up empty at that point), and the page is left in broken state. Now we use the same flow to fallback to the default theme, as if the user set it.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/5136
Closes: https://github.com/SAP/ui5-webcomponents/issues/5136
> fix(theming): fix fallback to default theme

- packages/main/src/List.js
Currently, the `ui5-list` documentation mentions some `@ui5/webcomponents-fiori` components, but `@ui5/webcomponents` does not have a dependency to `@ui5/webcomponents-fiori` (but the other way round).
This creates a "reverse dependency" in the documentation.
When we create OpenUI5 wrappers for the webcomponents, we replace all mentions of tags in the documentation with the OpenUI5 class names. For example, `ui5-li-notification` should be replaced with `sap.ui.webc.fiori.NotificationListItem`. However, since `@ui5/webcomponents` does not have a dependency to `@ui5/webcomponents-fiori`, during the wrappers generation for `sap.ui.webc.main` we don't have the `sap.ui.webc.fiori`  classes loaded, and we cannot match `ui5-li-notification` against anything, thus leaving it unchanged in the …
> docs(ui5-list): do not use names from @ui5/webcomponents-fiori

- packages/main/src/themes/Panel.css
- packages/theming/css-vars-usage.json
Use --sapGroup_Title_FontSize, instead of --sapGroup_TitleFontSize
Fixes: https://github.com/SAP/ui5-webcomponents/issues/5201
> fix(ui5-panel): fix typo in css var name

- packages/tools/lib/create-icons/index.js
We now use the icon name string as default export. This will allow developers to directly set the imported icon name string
to the Icon component (as shown below)  improving the DEV experience:
- easier to determine  (within the IDE) if imported icons are still used in the module
- immediate feedback (within the IDE) when import is missing for an icon that is actually used
FIXES: https://github.com/SAP/ui5-webcomponents/issues/5122
```js
import "@ui5/webcomponents/dist/Icon.js";
import home from "@ui5/webcomponents-icons/dist/home.js";
export default function App() {
return (
<ui5-icon name={home}></ui5-icon>
);
}
```
or with UI5 Web Components 4 React
```js
import { Icon } from "@ui5/webcomponents-react";
import home from "@ui5/webcomponents-icons/dist/home.js";
export default function …
```
> feat(icons): use icon name as default module export

- packages/main/src/themes/Input.css
ValueState border should not be visualized in readonly and disabled state.
> fix(ui5-input): correct value-state styles in readonly and disabled

- packages/main/src/TextArea.js
- packages/main/src/themes/TextArea.css
- We used to have warning state if max-length was exceeded, which was incorrect behavior of the component, since in some cases we can overwrite the valueState set by the application.
> fix(ui5-textarea): prevent valueState if maxlenght is exceeded

- packages/main/src/Tab.js
In Firefox, using two or more slots with the same name (i.e. "disabled-slot")
in a shadow root will prevent the other slots from being shown.
Further clicking on a Tab in the strip after the slots are broken will cause
the browser tab to crash.
This change fixes the ui5-tabcontainer to work correctly in Firefox by
ensuring each slot that should be hidden gets a unique name.
Fixes #5178
> fix(ui5-tabcontainer): provide unique names for each disabled slot

- packages/main/src/Calendar.js
This is a follow up on https://github.com/SAP/ui5-webcomponents/pull/5212 where the month selection view has been fixed. We noticed that the header button text should also rely on `getMonthsStandAlone`, instead of `getMonths`.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/5242
> fix(ui5-calendar): correct header month button text localization

- packages/main/src/Table.js
In MultiSelect mode, we should count the selection column as a visible column as well, since the "growing" row as well as the "no-data-text" row are one column narrower if the value of their colspan attribute is the count of the visible columns without the selection one.
FIXES: #5234
> fix(ui5-table): adjust colspan value in MultiSelect mode

- packages/base/src/css/BusyIndicator.css
Problem:
Two busy indicators appear if component has logic for "local" busy indicator.
Fix:
Hide all nested `ui5-busy-indicator` inside busy wrapper.
Part of #5236
> fix(retrofit): hide busy indicator if owned by the component

- packages/main/src/Select.js
When item is selected via typing text value state message is detected as a child of ui5-select. Now, we are searching only in the displayed options.
> fix(ui5-select): select correct item by typing text

- packages/main/src/ColorPicker.hbs
- packages/main/src/ColorPicker.js
- packages/main/src/RangeSlider.hbs
- packages/main/src/RangeSlider.js
- packages/main/src/Slider.hbs
- packages/main/src/SliderBase.hbs
- packages/main/src/SliderBase.js
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/pages/RangeSlider.html
- packages/main/test/pages/Slider.html
- packages/main/test/specs/ColorPicker.spec.js
- packages/main/test/specs/RangeSlider.spec.js
- packages/main/test/specs/Slider.spec.js
Issue description:
- The screen reader should announce meaningful messages
in relation to the inner input controls of the "ui5-color-picker".
Solution:
- The "accessibleName" property is enabled for the "ui5-slider"
and "ui5-range-slider" components.
- The missing label references for the "ui5-color-picker" inner input
components are added as per specification.
Related to: #5015
Related to: #5023
> fix(ui5-color-picker): provide meaningful labels for the inner input components

- packages/main/src/themes/Panel.css
When we hover the content of the ui5-panel or not clickable header, the cursor should be the default one instead of pointer.
FIXES: #5248
> fix(ui5-panel): set pointer cursor only over the header

- packages/main/src/themes/sap_horizon_hcb/RatingIndicator-parameters.css
- packages/main/src/themes/sap_horizon_hcw/RatingIndicator-parameters.css
The focus border is now according to the spec in HC themes.
> fix(ui5-rating-indicator): apply correct styles for focus in HC themes

- packages/main/src/ListItem.hbs
- packages/main/src/ListItem.js
FIxes: #5196
AccessibleName should override any other native labeling mechanism, such as LI's element text content.
> fix(ui5-li): correct accessible-name mappings

- packages/fiori/src/ShellBar.hbs
- packages/fiori/src/ShellBar.js
- packages/fiori/src/themes/ShellBar.css
Now, button is used to wrap title and logo only when menuItems are used. In addition, some unused CSS styles and JS methods from the class are removed.
Fixes: #5051
> refactor(ui5-shellbar): menu button logic

- packages/tools/lib/generate-json-imports/themes.js
**Background**
The following assets import fails in codesandbox
```js
import "@ui5/webcomponents/dist/Assets.js";
```
with
```js 
TypeError
Cannot read properties of undefined (reading 'forEach')
```
**Root cause**
It turns out that our JS module below that includes JSON imports was missing couple of ";" at the end of the methods and confused the parcel bundling.
```js
@ui5/webcomponents-theming/dist/generated/json-imports/Themes.js
```
**Fix**
After we added ";" everywhere needed, the theming ис working properly in codesandbox.
- with laters version 1.4.0 without the fix
https://codesandbox.io/s/ui5-webcomponents-forked-7q7f6m
https://7q7f6m.csb.app/?sap-ui-theme=sap_fiori_3_dark
- with preview version 0.0.0-453158269 including the fix …
> chore: fix import of theming assets in codesandbox

- packages/main/src/Carousel.hbs
- packages/main/src/Carousel.js
- packages/main/src/themes/Carousel.css
The ui5-carousel's navigation buttons now will focus the carousel after
being clicked. This avoids losing the focus when the first/last button
of the carousel dissapears when reaching the fist/last pages.
With this change, the arrow buttons will no longer retain the focus.
Fixes: #5125
> fix(ui5-carousel): correct navigation buttons behavior

- packages/main/src/RatingIndicator.js
The Icon component is not imported, although used. Not marked as dependency.
If someone bundles just the RatingIndicator, the Icon component will be missing and actually the stars won't be displayed.
Also, when we don't mark  it as dependency, we break the scoping, which adds suffixes to the dependencies of the component -  the case with the issue, linked below. The users enabled the scoping feature and used `ui5-rating-indicator-demo`, but in the Shadow DOM, the ui5-icon did not get its suffix (ui5-icon-demo) and thus not rendered.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/5318
> fix(ui5-rating-indicator): import ui5-icon as used in template

- packages/base/src/util/Caret.js
- packages/fiori/src/themes/Bar.css
- packages/fiori/src/themes/MediaGalleryItem.css
- packages/fiori/src/themes/ProductSwitchItem.css
- packages/fiori/src/themes/ShellBar.css
- packages/fiori/src/themes/Wizard.css
- packages/fiori/src/themes/WizardTab.css
- packages/main/src/themes/Badge.css
- packages/main/src/themes/BusyIndicator.css
- packages/main/src/themes/Button.css
- packages/main/src/themes/CalendarHeader.css
- packages/main/src/themes/CheckBox.css
- packages/main/src/themes/ColorPicker.css
- packages/main/src/themes/DayPicker.css
- packages/main/src/themes/Input.css
- packages/main/src/themes/ListItem.css
- packages/main/src/themes/ListItemBase.css
- packages/main/src/themes/MonthPicker.css
- packages/main/src/themes/MultiComboBox.css
- packages/main/src/themes/MultiInput.css
- packages/main/src/themes/PopupsCommon.css
- packages/main/src/themes/ResponsivePopoverCommon.css
- packages/main/src/themes/SliderBase.css
- packages/main/src/themes/Switch.css
- packages/main/src/themes/TextArea.css
- packages/main/src/themes/Toast.css
- packages/main/src/themes/ToggleButton.css
- packages/main/src/themes/YearPicker.css
- packages/main/test/specs/Input.spec.js
Remove all IE11-related CSS:
- denoted by comments
- starting with the `-ms` prefix
Additionally, remove the code using IE-specific `document.selection` for the inputs.
> refactor: cleanup IE code part 3: CSS

- packages/base/src/util/isDefaultSlotProvided.js
- packages/main/test/pages/Badge.html
- packages/main/test/specs/Badge.spec.js
> fix(ui5-badge): correctly detect if default slot is provided

- packages/main/src/Button.hbs
- packages/main/src/Button.js
- packages/main/test/pages/Button.html
- packages/main/test/specs/Button.spec.js
Issue:
The ui5-button icon was announced by the screen readers
when there is a text and a icon.
Solution:
The ui5-button icon has role "presentation" when we aren't
in an icon only scenario.
Fixes: #5288
> fix(ui5-button): adjust icon role

- packages/main/src/AvatarGroup.js
The calculations of the main container width have been adjusted to take into account sibling nodes.
Fixes #5333
> fix(ui5-avatar-group): adapt width calculations in composite layouts

- packages/theming/lib/generate-css-vars-usage-report/index.js
Glob pattern must contain only forward slashes, which is not the case on Windows. Related issue in globby - https://github.com/sindresorhus/globby/issues/179.
Fixes https://github.com/SAP/ui5-webcomponents/issues/5368
> chore: fix css-vars-usage-report on Windows

- packages/base/src/features/F6Navigation.js
- packages/fiori/test/pages/F6TestPage.html
Prevent default browser behaviour only when all conditions for F6 navigation next / back are meet.
Fixes: #5339
> fix(f6navigation): prevent default behavior on windows OS

- packages/main/src/Popover.js
- packages/main/test/specs/Popover.spec.js
> fix(ui5-popover): avoid dangling aria-labelledby attribute

- packages/base/src/delegate/ItemNavigation.js
- packages/main/test/pages/ItemNavigation.html
- packages/main/test/specs/ItemNavigation.spec.js
In RTL, the left and right arrow keys now correctly move the focus for
horizontally navigable items in the absolute direction of Left/Right.
Fixes: #5166
> fix(framework): correct use of arrow keys for ItemNavigation in RTL

- packages/fiori/src/DynamicSideContent.js
- packages/main/src/ColorPalette.js
- packages/main/src/ColorPalettePopover.js
- packages/main/src/DatePicker.js
It should be event.detail by spec -> https://developer.mozilla.org/en-US/docs/Web/API/CustomEvent/detail.
Luckily, it's not a breaking change as the framework properly fires the event and assigns the data on the "detail" object.
Also, the "details" does not show up in the API reference.
> chore: fix event metadata

- packages/fiori/src/IllustratedMessage.js
- packages/fiori/src/types/IllustrationMessageSize.js
- packages/fiori/test/pages/IllustratedMessage.html
- packages/fiori/test/specs/IllustratedMessage.spec.js
A new `size` property for IllustratedMessage has been implemented.
It determines which illustration breakpoint variant is used.
Available options are:
- `Auto` (default) - Automatically decides the size depending on the component width.
- `Base` (XS breakpoint) - Suitable for cards (two columns).
- `Spot` (S breakpoint) - Suitable for cards (four columns).
- `Dialog` (M breakpoint) - Suitable for dialogs.
- `Scene` (L breakpoint) - Suitable for a `Page` or a table.
Resolves #5221
> feat(ui5-illustrated-message): implement size property

- packages/main/src/ComboBox.js
- packages/main/test/specs/ComboBox.spec.js
There's a case when the user types the full value of some of the items, without any differences, but then clicks on the item itself in the list.
By now, this didn't fire change event as the item selection had its own handler for events. It checks with the value of the input whether it differs from the value of the item. If they differ, then fires a change event. However, in that edge case, this is a false positive and we need to take it into account.
Fixes #5432
> fix(ui5-combobox): correctly fire change event on item press

- package.json
run build:prerequisites as quite a lot of projects are not built after a clean
> chore: fix local playground start

- packages/main/src/Input.js
- packages/main/test/pages/InputsLazyLoading.html
- packages/main/test/specs/Input.spec.js
If items are removed and update on input with a delay, the suggestions popover remains open while the items are loading.
FIXES: #5365
> fix(ui5-input): enhance lazy loading

- packages/main/src/features/InputElementsFormSupport.js
- packages/main/test/pages/FormSupport.html
- packages/main/test/specs/FormSupport.spec.js
Form is submitted even if the submit event was prevented. Now, we check if the submit event is prevented and if it's not we submit the form.
Fixes: #5427
> fix(formEnablement): correct submit event behaviour

- packages/main/src/Panel.hbs
- packages/main/src/Panel.js
- packages/main/test/pages/Panel.html
Prevent rendering ui5-panel header part when both header and header text are not set.
FIXES: #5342
> feat(ui5-panel): remove header when not used

- packages/create-package/index.js
- packages/create-package/template/src/MyFirstComponent.js
- packages/create-package/template/test/pages/index.html
This change fixes several bugs in the `create-package` package:
- path to the `bundle.esm.js` in the test page is now correct after the tooling update
- the new package is now always created with the same version as the `package.json` of the `create-package` package.
- added JSDoc to the new component
> fix: create package bugs

- packages/main/src/ComboBox.hbs
- packages/main/src/ComboBox.js
- packages/main/src/ComboBoxPopover.hbs
- packages/main/src/Input.js
- packages/main/src/MultiComboBox.hbs
- packages/main/src/MultiComboBox.js
- packages/main/src/MultiComboBoxPopover.hbs
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/pages/ComboBox.html
- packages/main/test/pages/Input.html
- packages/main/test/pages/MultiComboBox.html
- packages/main/test/pages/MultiInput.html
- packages/main/test/specs/ComboBox.spec.js
- packages/main/test/specs/Input.spec.js
- packages/main/test/specs/MultiComboBox.spec.js
Value state types (warning. error, etc) are added to the screen readers value state message announcements.
Related to #5392 and #5495
> fix(ui5-input, ui5-multi-input, ui5-combobox, ui5-multi-combobox): announce value state type

- packages/main/src/GroupHeaderListItem.hbs
Fixes: #5400
With #3869 we override the role of the GroupHeaderListItem node to group.
Role overriding is not allowed for `<li>` items. We may use group role on `<ul>` nodes only as in this ARIA tree example:
https://w3c.github.io/aria-practices/examples/treeview/treeview-navigation.html
> fix(ui5-li-groupheader): use group role on UL nodes only

- packages/main/src/themes/Title.css
SAPUI5 is using the bold font family for rendering Titles in the Horizon Themes. I think it would be better to use the `sapFontHeaderFamily` variable.
Compare to: https://ui5.sap.com/#/entity/sap.m.Title/sample/sap.m.sample.TitleWrapping
> fix(ui5-title): use correct font-family for Horizon Themes

- packages/main/src/Panel.hbs
- packages/main/src/Panel.js
- packages/main/test/specs/Panel.spec.js
When the ui5-panel is fixed and accessibleName is not set by the users, we add a reference to the panel's title in order to be announced. If the ui5-panel is fixed but accessibleName is set, then its value take precedence over aria-labelledby referencing the title.
FIXES: #5438
> fix(ui5-panel): enhance aria-labelledby handling

- packages/main/src/MultiComboBox.js
- packages/main/src/themes/Icon.css
- packages/tools/components-package/nps.js
GroupHeaderListItem is used in the MultiComboboxPopoverTemplate and it should be part of the MultiCombobox dependencies in order to be identified and scoped, when Scoping is turned on.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/5521
> fix(MultoComboBox): fix component scoping

- .github/workflows/auto_close.yaml
The action is scheduled to run every day at 17:30 UTC and mark inactive issues for 21 days as "Stale" and close "author action", "wontfix" and "stale" issues after 28 days of inactivity.
> ci: add auto-close of stale issues

- packages/main/src/Avatar.hbs
- packages/main/src/Avatar.js
- packages/main/src/Badge.js
- packages/main/src/Interfaces.js
- packages/main/src/themes/Avatar.css
- packages/main/src/themes/Badge.css
- packages/main/test/pages/Avatar.html
- packages/main/test/pages/styles/Avatar.css
- packages/main/test/samples/Avatar.sample.html
- packages/main/test/specs/Avatar.spec.js
The Avatar now supports visual affordance using a new `badge` slot:
```js
<ui5-avatar initials="AB" color-scheme="Accent1">
<ui5-badge slot="badge">
<ui5-icon slot="icon" name="accelerated"></ui5-icon>
</ui5-badge>
</ui5-avatar>
```
**Note:** To achieve the target design, please use only `ui5-icon` in the corresponding slot of `ui5-badge`, without text nodes.
The `IBadge` interface has been removed as it limits the scope of slottable elements and causes issues in the enablement context.
Related to https://github.com/SAP/ui5-webcomponents/issues/4624
> feat(ui5-avatar): introduce badge support

- packages/main/src/Menu.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/5582
> fix(ui5-menu): opening a submenu no longer throws a console error

- packages/base/lib/generate-styles/index.js
Using recursive option of mkdir method ensures that each folder from path will be created and if any of the folders exist error is not thrown.
> fix: regenarete base styles on change

- packages/fiori/src/IllustratedMessage.hbs
- packages/fiori/src/IllustratedMessage.js
- packages/fiori/test/pages/IllustratedMessage.html
- packages/fiori/test/samples/IllustratedMessage.sample.html
Introduced new title slot, that allows custom title levels.
```html
<ui5-illustrated-message name="UnableToUpload">
<ui5-title slot="title" level="H1">This is a slotted title</ui5-title>
</ui5-illustrated-message>
```
Closes: #5503
> feat(ui5-illustrated-message): introduce title slot

- packages/main/src/MultiInput.js
- packages/main/test/pages/MultiInput.html
- packages/main/test/specs/MultiInput.spec.js
The token-delete event is not fired when the ui5-multiinput
has "readonly" attribute added.
Fixes: #5448
> fix(ui5-multiinput): token-delete not fired when readonly

- docs/1-getting-started/04-using-icons.md
- docs/3-customizing/02-fonts.md
- packages/base/src/asset-registries/LocaleData.js
- packages/base/src/css/FontFace.css
- packages/fiori/src/NotificationAction.js
- packages/fiori/src/ProductSwitchItem.js
- packages/fiori/src/SideNavigationItem.js
- packages/fiori/src/SideNavigationSubItem.js
- packages/fiori/src/TimelineItem.js
- packages/fiori/src/WizardStep.js
- packages/fiori/test/pages/ShellBar.html
- packages/icons-business-suite/README.md
- packages/icons-tnt/README.md
- packages/icons/README.md
- packages/localization/src/locale/getLocaleData.js
- packages/main/bundle.common.js
- packages/main/src/Avatar.js
- packages/main/src/Button.js
- packages/main/src/Icon.js
- packages/main/src/MenuItem.js
- packages/main/src/MessageStrip.js
- packages/main/src/Option.js
- packages/main/src/SplitButton.js
- packages/main/src/StandardListItem.js
- packages/main/src/SuggestionItem.js
- packages/main/src/Tab.js
- packages/main/test/pages/Button.html
- packages/main/test/pages/Kitchen.html
- packages/main/test/pages/Kitchen.openui5.html
- packages/main/test/pages/OpenUI5.html
Hi team,
let's use the latest promoted the SDK url. 🎉
Last month (July 2022) two new SDK deployments were rolled out. See blog post [Short and Powerful: Convenient URLs for SAPUI5/OpenUI5 CDN](https://blogs.sap.com/2022/07/20/short-and-powerful-convenient-urls-for-sapui5-openui5-cdn/).
Former SDK deployments:
- `sapui5.hana.ondemand.com`, `sapui5.netweaver.ondemand.com` are substituted by `ui5.sap.com`
- `openui5.hana.ondemand.com` is substituted by `sdk.openui5.org` 
-  `openui5nightly.hana.ondemand.com` is substituted by `sdk.openui5.org/nightly/`
The former SDK deployments will continue to work, there is no actual change implemented or planned as of now.
However, only the new SDK URLs should be promoted in future.
+ Especially the [How to …
> refactor: use new sdk url

- packages/main/src/Panel.hbs
- packages/main/src/Panel.js
- packages/main/test/specs/Panel.spec.js
Panel header was not recognized due to the fact that it was inside an element with a header role. Now the heading element wraps the button and the panel header is announced and recognized in JAWS's heading list dialog.
FIXES: #5504
> fix(ui5-panel): recognizable panel heading

- packages/main/src/themes/Breadcrumbs.css
Breadcrumbs \<li\> element contains initial padding, which is not visible, but gets inherited by the <span> element, which is visible when the focus style is applied.
Fixes: #5492
> fix(ui5-breadcrumbs): current location misalignment is fixed

- packages/base/src/i18nBundle.js
Formatter function should invoked if parameters for placeholders exist.
If parameters exist the output should be:
`Text  '{0}` => `Text {placeholder's text}`
`Text  ''{0}` => `Text '{placeholder's text}`
`Text  ''{0}''` =>  `Text '{placeholder's text}'`
If parameters don't exist the output should be:
`Text`   => `Text `
`Text  '` => `Text '`
`Text  ''` => `Text '`
`Text  {0}` => `Text {0}`
Fixes: #5626
> fix(i18n): usage of quotes in texts

- packages/base/src/UI5Element.js
- packages/base/src/types/DOMReference.js
- packages/main/src/Popover.js
Changes:
- new custom type `DOMReference` defined (accepts a string or DOM element)
- `opener` is now of type `DOMReference`
- The framework gets new functionality:`attributeChangedCallback` can be skipped for an attribute that is being mutated internally (in order to avoid the property being synchronized back)
- the opener ID is now queried from the same HTML document as the `ui5-popover` instance itself, rather than `window.document`.
**Why the opener type change?**
There are use cases where the popover and opener are _in different documents_ which makes it impossible to pass an ID. At the same time calling the public method to open the popover is not a good option either, because it is not declarative-friendly. The most convenient solution is to be able to pass a DOM Reference directly …
> feat(ui5-popover): new type DOMReference for opener

- packages/main/src/Panel.js
Previously in Safari, when the ui5-panel expand/collapsed button was activated via Enter key, the component did not remain open but closed instantly.
FIXES: #5579
> fix(ui5-panel): toggle ui5-panel correctly on Enter key

- packages/main/src/themes/Badge.css
Scope linter failing because its regex doesn't catch if the tag name is used in comment or not.
> chore: fix css comments of Badge

- packages/main/src/TextArea.js
- packages/main/test/pages/TextArea.html
- packages/main/test/specs/TextArea.spec.js
> fix(ui5-textarea): show exceeded text when maxLength is 0

- packages/main/src/TabContainer.js
- packages/main/test/pages/TabContainer.html
- packages/main/test/specs/TabContainer.spec.js
The `tab-select` event can now be prevented.
Added new public getter `allItems` that returns an array which includes all
slotted tabs and their subTabs. The reason for the addition is that
the `tab-select` event returns a `tabIndex` of the selected tab, but if that selected tab is
nested, then `tabIndex` will not correspond to the `items` property,
which includes only the top-level tabs.
Fixes #5116
> feat(ui5-tabcontainer): make tab-select event preventable

- packages/main/src/themes/sap_horizon/parameters-bundle.css
- packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
Related to: #5667
Since #5171, the badge css files are uncorrectly imported and are now causing deviations from the design specification.
> fix: correct imports of horizon Badge CSS files

- packages/main/src/CardHeader.hbs
- packages/main/src/CardHeader.js
Recently we got a request from the MDK colleagues to customize the background of the CardHeader and to make this possible we add a new shadow part (as we have for the title, status and sub-status texts).
> refactor(ui5-card-header): add new CSS Shadow part

- packages/fiori/src/NotificationOverflowActionsPopover.hbs
- packages/fiori/src/themes/NotificationOverflowActionsPopover.css
- packages/fiori/test/pages/NotificationListItem.html
The change aligns actions' texts to the left.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/5704
Before:
After:
> fix(ui5-li-notification): align actions' texts to the left

- packages/main/src/Button.hbs
- packages/main/src/Button.js
The default tooltip announcement coming from the inner ui5-button icon is not
present.
Reverts SAP/ui5-webcomponents#5714
> Revert "fix(ui5-button): adjust icon role"

- packages/main/src/themes/GroupHeaderListItem.css
Fixes #5720 
Bug description:
There are spaces that should not be, between the items with different GroupHeaders. It is caused by #3869.
Fix:
Removed the spaces between the items.
> fix(ui5-list): unexpected spaces between group items

- packages/main/src/themes/Button.css
* When using a segment button placed in a container with display flex a minimum width setting is necessary
FIXES: #5027
> fix(ui5-button): correct calculation of the min width of an icon button

- packages/main/src/CalendarHeader.hbs
- The elements representing the previous, month, year and next
actions in the ui5-calendar header now have role "button"
as per specification.
Fixes: #5708
> fix(ui5-calendar): adjust the role attribute of the header actions elements

- packages/tools/lib/create-icons/index.js
With 1.6.0 we provided default exports for all icons in all collections.  However we export the icon name without the collection and for `@ui5/webcomponents-icons-tnt` and `@ui5/webcomponents-icons-business-suite` packages it makes it not that convenient
**For example,** 
let's take the "actor" icon from "tnt" (source code: https://unpkg.com/browse/@ui5/webcomponents-icons-tnt@1.6.0/dist/actor.js), where we export the string "actor"
```js
// actor.js
import { registerIcon } from "@ui5/webcomponents-base/dist/asset-registries/Icons.js";
const name = "actor";
const pathData = "..."
registerIcon(name, { pathData, ltr, collection, packageName });
export default "actor";
export { pathData, ltr, accData };
```
**Example from usage point of view:**
```js
import "@ui5/webcomponents/dist/Icon.js"; …
```
> refactor: add collection to icons' name export

- packages/main/src/Button.js
- packages/main/test/samples/Button.sample.html
According to UX guidelines, every instance of an icon-only button needs a tooltip.
When the inner ui5-icon element doesn't have a default one, the tooltip property
should be provided at the application side.
Related to: #5687
Related to: #5596
Related to: #5505
> fix(ui5-button): provide tooltip for icon-only buttons

- packages/main/src/Menu.hbs
- packages/main/src/MenuItem.js
- packages/main/test/pages/Menu.html
- packages/main/test/specs/Menu.spec.js
The ui5-menu-items can now have an additional description provided
by the application developer.
Fixes: #5514
Fixes: #5656
> feat(ui5-menu-item): add new `accessibleName` property

- packages/main/src/DateRangePicker.js
- packages/main/test/pages/DateRangePicker.html
- packages/main/test/specs/DateRangePicker.spec.js
When the ui5-date-range-picker tries to split its values by delimiter there was no handle for the case with single date in the values.
Fixes: #5738
> fix(ui5-daterange-picker): handle single date value

- packages/main/src/TabContainer.js
- packages/main/test/pages/TabContainer.html
- packages/main/test/specs/TabContainer.spec.js
> fix(ui5-tabcontainer): fixed error when no tabs

- packages/fiori/src/BarcodeScannerDialog.js
The `zxing` library does not provide sourcemaps which causes Webpack 5 to produce enormous amounts of warnings when starting or building a project that imports the `BarCodeScannerDialog` component:
The proposed solution is to use the UMD bundle instead, in which case there are no errors:
Additionally, using the UMD bundle seems to improve bundle size by about 2KB:
**Webpack (demo app from the ticket)**
Before: 198.06 kB (+1.8 kB)    build/static/js/main.fa6690d4.js
After: 196.26 kB (-1.8 kB)  build/static/js/main.301eeacc.js
**Vite (UI5 Web Components' own build task)**
Before: dist/assets/bundle.esm.070a07f0.js     5043.94 KiB / gzip: 1548.36 KiB
After: dist/assets/bundle.esm.ed0a9f80.js  4989.66 KiB / gzip: 1546.88 KiB
closes: https://github.com/SAP/ui5-webcomponents/issues/5648
> refactor: use the UMD bundle for zxing

- packages/base/src/css/FontFace.css
The refactoring to use the new SDK URL left a `.com` after the new domain `sdk.openui5.org`.
Thanks to @tonitone for finding this 
> Fix #5820 - Remove .com from URL font-face 72Black

- packages/fiori/src/IllustratedMessage.js
- packages/fiori/test/pages/IllustratedMessage.html
- packages/fiori/test/specs/IllustratedMessage.spec.js
AriaLabelledBy association is introduced to IllustratedMessage.
> feat(ui5-illustrated-message): accessible-name-ref added

- packages/tools/lib/create-icons/index.js
Created TypeDefinitions for all icon packages. This helps TypeScript users to better use the Icon Name Export feature which was introduced with #5747
Fixes #5335
> feat(icons): create type-definitions for icon imports

- packages/base/src/StaticAreaItem.js
The change was done upon stakeholder's request (via internal communication channel) and the use case is the same as with the standard components - to have stable query selectors no matter the scoping suffix that is set.
> fix(ui5-static-area-item): add tag as attr on the host

- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
- .github/workflows/test.yaml
- packages/base/src/asset-registries/LocaleData.js
ENABLE_CLDR variable does not have any effect since the rollup to vite switch so it should be removed. DEV_MODE does not exist as well.
> chore: remove CLDR warning and ENABLE_CLDR usage

- docs/1-getting-started/04-using-icons.md
- packages/base/src/asset-registries/Icons.js
- packages/main/src/Icon.hbs
- packages/main/src/Icon.js
- packages/tools/lib/hbs2lit/src/compiler.js
A fully custom SVG content can be provided by developers and will be rendered inside the `<ui5-icon>`. 
This allows usage of more complex items where multiple SVG elements like `rect` and `circle` are used instead of just `path`. 
Attributes can also be added allowing more efficient icons using `stroke-width` for example, or even multi-colored icons.
Closes: #5347
> feat(main): add support for custom SVG icons

- packages/main/src/ComboBox.js
- packages/main/src/features/InputSuggestions.js
- packages/main/test/specs/ComboBox.spec.js
While navigating through the suggestions, 'selected' state of an item is not announced anymore.
FIXES: #5824
> fix(ui5-input,ui5-combobox): remove 'selected' announcement

- packages/main/src/i18n/messagebundle.properties
- packages/tools/lib/i18n/defaults.js
**Prior to this PR**, changing the `messagebundle.properties` file does not take effect as the default i18n texts are generated based on the locale specific file (for "en" - messagebundle_en.properties).
**Now,** the output is based on both the source `messagebundle.properties` and the locale specific files. As a result, changing the `messagebundle.properties` file will take immediate effect.
**Note:**  as the  `messagebundle.properties` file is always written in English, this improvement only makes sense for the "en" locale.
> build: improve i18n texts update at dev time

- packages/main/src/RadioButton.js
- packages/main/test/pages/RadioButton.html
- packages/main/test/specs/RadioButton.spec.js
In frameworks like React, conditional rendering such as:
```js
<div>
{ falsyValue && <RadioButton /> }
</div>
```
will remove radio buttons from the DOM completely. 
With this fix, buttons from the same group will have the correct tabindex set when they are placed back in the DOM.
Fixes #5803
> fix(ui5-radio-button): correct syncing radio group when exiting DOM

- packages/main/src/Menu.hbs
- packages/main/src/MenuItem.js
- packages/main/src/themes/Menu.css
- packages/main/src/themes/base/Menu-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/test/pages/Menu.html
- packages/main/test/samples/Menu.sample.html
- packages/main/test/specs/Menu.spec.js
The newly implemented additional text of the menu item provides a way to display additional texts such as shortcut combinations in the menu items via the additionalText proprty. In addition, there is another property hideAdditionalText which can be used to hide defined additional texts in some situations (on mobile devices for example).
related to: #5369
> feat(ui5-menu-item): implement additional text

- packages/main/src/themes/Icon.css
In Safari, the svg does not occupy 100% of the Icon's height and that causes the issue. The svg needs to take full width and height of the root in order to be visualised correctly. Setting the width and height of the svg to 100%, I tested many different samples and components that use ui5-icon and I did not find any side effects from the change. Something more, the ui5-icon has a predefined width and height of 1rem, so that has to prevent unexpected changes in the svg size.
FIXES: #5842
> fix(ui5-icon): visualize the icons properly in Safari

- packages/base/hash.txt
Not needed as we don't make use of hashes build time any more.
> chore: remove obsolete hash file

- packages/main/src/Link.js
- packages/main/test/pages/Link.html
- The previously private `accessibleRole` property is now made public, in order to enable
application developers to configure a given ui5-link element to be interpreted as button
by the accessibility tools.
Fixes: #5686
> feat(ui5-link): make acceessibleRole property public

- packages/base/src/StaticAreaItem.js
- packages/main/test/pages/OpenUI5.html
- packages/main/test/pages/styles/OpenUI5.css
**Issue**
When UI5WC ui5-date-picker is opened inside UI5 dialog, click "ESC" wrongly close whole dialog.
**Root cause** 
It's an integration issue between UI5WC Popups and OpenUI5 Popups - the focus never gets to the DatePicker's popover as it's not recognized as an external content by the sap.m.Dialog.
**Solution**
While we are working on more general, out of the box solution by integrating UI5WC Popups and OpenUI5 Popups, we would like to provide the following solution for the time being:
Forwarding the `"data-sap-ui-integration-popup-content"` attribute from the component that opens popup to its the static are item, which makes the static are item an external content for the sap.m.Dialog (as the aforementioned attribute is already part of the OpenUI5 logic). When the attribute is …
> fix: make static are items recognizable to openui5 dialogs

- packages/fiori/src/BarcodeScannerDialog.js
- packages/fiori/src/themes/sap_fiori_3/ShellBar-parameters.css
- packages/fiori/src/themes/sap_fiori_3/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3_dark/ShellBar-parameters.css
- packages/fiori/src/themes/sap_fiori_3_dark/parameters-bundle.css
There were mismatch in outline color for focused buttons/elements in ui5-shellbar for Quartz light and dark themes.
It is corrected in this change.
Fixes: #5795
> fix(ui5-shellbar): outline buttons color on focus fixed for quartz

- packages/main/src/Avatar.js
One `&nbsp` in `Avatar.js` is missing the `;` which causes it to not be replaced by the `@uit/tooling-webc` wrapper generator, ultimately breaking the UI5 Enablement for Web Components build
> docs: fix bad nbsp

- packages/fiori/src/NotificationListGroupItem.js
- packages/fiori/src/NotificationListItem.js
- packages/fiori/src/NotificationListItemBase.js
> fix(ui5-notifications): add missing imports for used icons

- package.json
- packages/main/src/Avatar.js
- packages/main/test/pages/Avatar.html
- packages/main/test/specs/Avatar.spec.js
Now, the ui5-avatar control supports three letters initials. If the initials are not valid or they are overflowing the control, an icon should be shown.
> feat(ui5-avatar): support of 3 letters is enabled

- packages/base/bundle.esm.js
- packages/base/package-scripts.js
- packages/base/test/elements/WithComplexTemplate.hbs
- packages/base/test/elements/WithComplexTemplate.js
- packages/base/test/pages/WithComplexTemplate.html
- packages/base/test/specs/WithComplexTemplate.spec.js
- packages/tools/lib/hbs2lit/src/litVisitor2.js
The PR addresses several issues with context setting within the lit templates by the HBS-2-lit compiler.
**Note:** There is one downside - to test it out, I have created a dummy component in "base", I created an HBS template and test, but I needed to enable the lit template generation. So, I guess we can find a smarter way to test it out - to pass templates to the compiler and check the output (I will look into that).
**Issues that are resolved with this change:**
- when "@root" is used in HBS template - it will throw an error: invalid or unexpected token
- when trying to access root context from nested loop with "{{../../text}}", it will compile to "{{text}}" ("context.text" would have been correct) and will throw an error
```hbs
<div>
{{#each items}}
<ul>
{{#each words}}
<li> …
```
> fix(framework): fix contexts management in hbs-2-lit compiler

- packages/main/src/themes/StepInput.css
- packages/main/src/themes/TimePicker.css
- Text spacing is now applied when custom styles are provided to the parent element.
Fixes: #5792
> fix(ui5-time-picker): enable text spacing

- packages/main/src/Switch.hbs
- packages/main/src/Switch.js
- packages/main/test/pages/Switch.html
- packages/main/test/specs/Switch.spec.js
- Application developers are enabled to use the new tooltip property in cases when referring
an external label is not wanted.
Fixes: #5552
> feat(ui5-switch): provide tooltip property

- packages/playground/docs/landing-page.html
The "Blog" link opens non-existing page, now points to blog.sap.com and ui5-webcomponents blogs
> docs: fix "Blog" link's href

- packages/fiori/package-scripts.js
- packages/tools/components-package/nps.js
In order to be generated file, with all of the illustrations imported in it, it was hardcoded that the illustrations to be taken from **specific path**. But when they were requested from npm, which has different path names for the packages, an error is thrown.
Paths are now dynamic.
Fixes: #5992
> fix(framework): fix paths for generating illustration imports in nps

- packages/fiori/src/DynamicSideContent.hbs
- packages/fiori/src/DynamicSideContent.js
- packages/fiori/test/pages/styles/DynamicSideContent.css
- packages/fiori/test/specs/DynamicSideContent.spec.js
When side content position is set to 'Start', the side content container is now rendered before the main content container, which effectively fixes the tab order.
Fixes https://github.com/SAP/ui5-webcomponents/issues/6012
> fix(ui5-dynamic-side-content): fix tab order when side content position is 'Start'

- packages/main/src/Menu.hbs
- packages/main/src/Menu.js
- packages/main/src/MenuItem.js
- packages/main/test/pages/Menu.html
- packages/main/test/specs/Menu.spec.js
There are new properties defined: **opener** and **open**, and by setting them the menu can be opened and closed declaratively.
Also there are new events provided: **before-open** (can be prevented), **after-open**, **before-close** (can be prevented) and **after-close** that are fired on opening and closing of the menu.
Fixes https://github.com/SAP/ui5-webcomponents/issues/5558
Fixes https://github.com/SAP/ui5-webcomponents/issues/5440
Fixes https://github.com/SAP/ui5-webcomponents/issues/5653
> feat(ui5-menu): add open/opener functionality and open/close events

- .github/workflows/deploy_latest.yaml
Playground is not deploying since a few days
I suspect that the build has been broken with a recent update of the `Gemfile` coming from https://github.com/SAP/ui5-webcomponents/commit/e1b02714a79c30001af99b7ed689f723610d43a3#diff-6f7aab33e75ae07ef9e183f84b74b8755e9aa05c4dde9824902dc5da2aca98be
Not really familiar with how gh actions work but I suggest you to bump the ruby version to `2.7.6` as `2.2` is quite old.
P.S. change of the `Gemfile` was required to get the playground running.
> chore: update ruby version on deploy

- packages/main/src/themes/TextArea.css
The min-width CSS prop was set to the incorrect element making the component not respecting it, I moved it to the host.
> fix(ui5-textarea): fix the minimum width of the component

- packages/base/src/delegate/ItemNavigation.ts
- packages/base/src/i18nBundle.ts
- new interface Tabbable that child components, subject to item navigation need to implement
- fix return type of getI18nBundle and getI18nBundleSync to Promise {I18nBundle} and I18nBundle respectively.
> chore: refactor ItemNav and I18nBundle types

- packages/main/src/TabContainer.js
remove `.prototype` from `headerBackgroundDesign` and `contentBackgroundDesign`
> docs(TabContainer): fix jsdoc types

- packages/fiori/src/ShellBar.js
- packages/fiori/test/specs/ShellBar.spec.js
Now there is option to programmatically toggle the display of the search field (if there is a valid slot in use).
Part of #5818
> feat(ui5-shellbar): programmatically show search field

- packages/main/src/TableColumn.js
- packages/main/src/types/TableColumnPopinDisplay.ts
In order to fulfill the naming conventions we renamed TableCellPopinDisplayType to TableColumnPopinDisplay. This does not affect the end users, API stays the same.
> refactor(ui5-table): renaming tablecellpopindisplaytype

- packages/base/src/Device.ts
Previously,Device.isIOS had the following return type: " boolean | RexExpMatch | null" which is a bit confusing.
Now, "boolean" is enforced.
Related to: https://github.com/SAP/ui5-webcomponents/issues/6080
> chore: ensure Device.iOS returns boolean

- packages/base/src/delegate/ItemNavigation.ts
Simplified return type of _getCurrentItem function of ItemNavigation. Previously it was returning null | HTMLElement | undefined. Now, it only returns HTMLElement | undefined
Related to: #6080
> chore(item-navigation): simplify return type of _getCurrentItem

- packages/base/src/MarkedEvents.ts
- packages/fiori/src/NotificationListItem.js
- packages/fiori/src/NotificationListItemBase.js
- packages/fiori/src/Timeline.js
- packages/main/src/Button.js
- packages/main/src/FileUploader.js
- packages/main/src/Link.js
- packages/main/src/ListItem.js
- packages/main/src/SplitButton.js
- packages/main/src/TableRow.js
Use global map for event marking, instead of marking the event instances:
- don't use `event.isMarked === "link"`, use `getEventMark(event)`
- don't use  `event.isMarked = "button"`, use `mark(event, "button")`
> refactor: use global map for event marking

- packages/tools/lib/dev-server/virtual-index-html-plugin.js
Adding a Content-Type=text/html header to the testsuite index.html will hint to Safari to correctly display the content as HTML.
Fixes #6107
> fix(infra): set Content-Type header on testsuite

- packages/base/src/util/FocusableElements.ts
- Added type `FocusableElement` to the `FocusableElements.ts` file, which I think will make the code a little bit more readable and understandable for a future refference.
Related to: #6080
> chore: add type to FocusableElements

- packages/fiori/src/ShellBar.js
Focus in list items, inside Popover is fixed on the first item, when opening the Popover, not caching its last state as it worked
before.
Fixes: #5994
> fix(ui5-shellbar): focus on popover fixed

- packages/fiori/src/types/BarDesign.ts
- packages/main/src/types/BreadcrumbsSeparatorStyle.ts
- packages/main/src/types/TableGrowingMode.ts
- packages/main/src/types/TitleLevel.ts
- packages/main/src/types/ToastPlacement.ts
- packages/tools/lib/jsdoc/preprocess.js
It's now once again possible to use `/` in `types/**/*.ts` files comments. Before this fix, the regular expression used to parse comments for JSDoc had a bug that prevented the usage of slashes.
> chore: use a better regex for types parsing

- packages/base/src/MediaRange.ts
- packages/base/src/util/FocusableElements.ts
We did the following changes: 
- `getCurrentRange` now always returns a result, because it fallbacks to the default `rangeSet`, previously it was returning "null";
- `initRangeSet` method now expects 2 params, instead of 3. 
- We completely changed the usage of the `initRangeSet`, instead of `initRangeSet(name: string, borders: [600, 1100, 1400], names: [S, L, M])`, we now use it like: 
```js
initRangeSet(name: string, range: Map<string, Array<number>>);
```
Related to: #6080
> refactor: change type and methods in `MediaRange.ts`

- packages/fiori/src/ShellBar.hbs
`<header>` semantic element is now supported by modern browsers, so it is used instead of `<div role="banner">`
> feat(ui5-shellbar): use header semantic element

- package.json
- packages/base/package.json
- packages/fiori/package.json
- packages/icons-business-suite/package.json
- packages/icons-tnt/package.json
- packages/icons/package.json
- packages/localization/package.json
- packages/main/package.json
- packages/theming/package.json
- yarn.lock
Make Typescript a dev dependency of the root and bump typescript from 4.9.3 to 4.9.4
> chore: make TS dev dependency

- packages/base/package.json
- packages/localization/src/sap/ui/core/Configuration.ts
- packages/localization/src/sap/ui/core/Core.ts
- packages/localization/src/sap/ui/core/FormatSettings.ts
- packages/localization/used-modules.txt
- packages/main/src/TimeSelection.js
- packages/tools/lib/copy-list/index.js
- yarn.lock
- fix build script to take proper location of openui5 for copying files
- add new files coming from upgrade as used modules
TimeSelection.js uses a field from DateFormat that was changed in openui5
https://github.com/SAP/openui5/commit/166f2dc05599e4dd94097e76dad3738832bbd780
previously it was `aDayPeriods`, now the equivalent seems to be `aDayPeriodsAbbrev`
> chore: correct openui5 imports after upgrade to 1.109

- packages/main/src/Input.hbs
There is a typo in input's renderer introduced with #5908
> fix(ui5-input): fix typo in renderer

- packages/main/src/themes/base/sizes-parameters.css
- Component's width is now 20rem as per visual specification. This would result in not displaying a horizontal scrollbar on 320px screen size.
Fixes: #5641
> fix(ui5-calendar): adjust displayed width

- packages/main/src/themes/Button.css
Issue:
- The tooltips wasn't displayed when the ui5-button is disabled.
Solution:
- Pointer events are now enabled for disabled buttons.
Fixes: #5083
> fix(ui5-button): adjust tooltip display

- packages/main/src/ProgressIndicator.ts
The **ProgressIndicator** component have been migrated to Typescript as part of the TS migration initiative.
**Note:** The `@name sap.ui.webc.main.ProgressIndicator.prototype.{propertyName}` added to all properties
Related to: https://github.com/SAP/ui5-webcomponents/issues/6080
> refactor(ui5-progress-indicator): migrate to TS

- packages/main/src/themes/DatePicker.css
- The proper background color is now set to the ui5-datepicker element when there is a value state configured or the component is in read only mode.
fixes: https://github.com/SAP/ui5-webcomponents/issues/5699
fixes: https://github.com/SAP/ui5-webcomponents/issues/5698
fixes: https://github.com/SAP/ui5-webcomponents/issues/5913
> fix(ui5-date-picker): align styles to input

- packages/main/src/SegmentedButton.hbs
- packages/main/src/SegmentedButton.js
Trigger focus on mousedown and selection only if mousedown and mouseup are executed over the element.
fixes: https://github.com/SAP/ui5-webcomponents/issues/5390
> fix(ui5-segmented-button): align mousedown and mouseup on item behaviour

- packages/main/src/themes/Select.css
- packages/main/src/themes/base/Select-parameters.css
- packages/main/src/themes/sap_horizon_exp/Select-parameters.css
There is a little typo in the css-variable `--_ui5_select_label_color`.
Changed it from `--_ui5_select_label_olor` -> `--_ui5_select_label_color` with this PR
> fix(ui5-select): correct typo in --_ui5_select_label_color

- packages/main/src/DatePicker.ts
- packages/main/src/DateRangePicker.ts
The **DateRangePicker** component have been migrated to Typescript as part of the TS migration initiative.
Related to: #6080
> feat(ui5-daterange-picker): migrate to TS

- packages/base/package.json
- packages/fiori/package.json
- packages/icons-business-suite/package.json
- packages/icons-tnt/package.json
- packages/icons/package.json
- packages/localization/package.json
- packages/localization/src/sap/ui/core/Configuration.js
- packages/localization/src/sap/ui/core/Core.js
- packages/localization/src/sap/ui/core/FormatSettings.js
- packages/localization/used-modules.txt
- packages/main/package.json
- packages/main/src/TimeSelection.js
- packages/theming/package.json
- packages/tools/lib/copy-list/index.js
- yarn.lock
Updated used openui5 version to 1.109.0. Added missing dependencies based on https://github.com/SAP/ui5-webcomponents/pull/6147.
> chore: update openui5 version

- packages/fiori/src/UploadCollection.ts
- packages/fiori/src/ViewSettingsDialog.ts
- packages/main/src/ColorPalette.ts
- packages/main/src/ColorPicker.ts
- packages/main/src/FileUploader.ts
- packages/main/src/Input.ts
- packages/main/src/StepInput.ts
- packages/main/src/TimePickerBase.ts
We used to have temp types for components that haven't been migrated to TS. Now as they are in TS, we can directly use them and remove the "ts-ignore" comments on those component imports any temp types created meanwhile.
> chore: remove ts-ignore on migrated components imports

- packages/base/src/locale/normalizeLocale.ts
The change adds "nb": "no" to fallback to "no" locale, when "nb" is set.
In addition the mapping from the old ISO639 language code "in" to "id" removed to align with SAPUI5/OpenUI5 mappings, where "in" to "id" mapping has been also removed with https://github.com/SAP/openui5/commit/b4efdf14404c2cff51f8b5af5b3b2b257b54c58d
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6283
> refactor(i18n): add mapping for norwegian locale

- packages/main/src/themes/TextArea.css
- packages/main/src/themes/base/TextArea-parameters.css
- packages/main/src/themes/base/sizes-parameters.css
- packages/main/src/themes/sap_belize/TextArea-parameters.css
- packages/main/src/themes/sap_belize_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_belize_hcw/TextArea-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/TextArea-parameters.css
- packages/main/src/themes/sap_horizon/TextArea-parameters.css
- packages/main/src/themes/sap_horizon_dark/TextArea-parameters.css
- packages/main/src/themes/sap_horizon_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_horizon_hcw/TextArea-parameters.css
1. New readonly design is Horizon Light and Dark applied.
2. Background image for disabled state in Horizon Light and Dark removed.
3. Paddings are updated according to the specification in all supported themes.
> fix(ui5-textarea): adjust styles according to the visual specification

- packages/tools/lib/jsdoc/preprocess.js
Previously, JSDoc preprocessor was looking for comments followed by @decorator to mark them as a comment that should be moved to the end of the file. Now, we append at the end of the file each JSDoc comment that has @name tag inside it.
Related to: https://github.com/SAP/ui5-webcomponents/issues/6300
> docs: fix jsdoc preprocessing of default slot

- packages/main/src/StepInput.ts
The JSDoc plugin can't process the "name" annotation if it's in the middle of the comment, move it along the other annotations.
part of: https://github.com/SAP/ui5-webcomponents/issues/6300
> chore: fix StepInput value-state-msg slot jsdoc

- packages/main/src/DatePicker.ts
- packages/main/src/Dialog.ts
- packages/main/src/Popover.ts
- packages/main/src/ResponsivePopover.ts
Mark parameters with default value as optional on all public methods in Typescript files.
Related to: #6300
> chore: mark JSdoc function parameters as optional

- packages/base/src/UI5Element.ts
- packages/fiori/src/Wizard.js
The underlying issue was that `_breakpoint` is of type `String`, however when `this.width` is `0`, the following expression:
```js
RESPONSIVE_BREAKPOINTS[Object.keys(RESPONSIVE_BREAKPOINTS).findLast(size => Number(size) < this.width)]
```
does not return a string, but rather `undefined`. Since `_breakpoint` does not have a default value, it becomes the string `"undefined"` which triggers the infinite invalidation loop of `undefined` vs `"undefined"`.
The solution is to always use a string for `_breakpoint`. For zero-width, this is the smallest breakpoint ("S").
Additionally, improved the invalidation debug code that is normally commented out to work better with objects.
> chore(ui5-wizard): provide a better fix

- packages/main/src/CheckBox.ts
Hi,
please correct this typo.
Thanks!
Oliver
> docs(CheckBox): typo red-only -> read-only

- packages/main/src/Badge.ts
- packages/main/src/ComboBox.js
- packages/main/src/MultiComboBox.js
This PR changes the JSDoc annotation of the `icon` slot for the `Badge`, `ComboBox` and `MultiComboBox` component.
For the `Badge` I changed it because the TypeScript type accepts an array of `HTMLElement`s and not only a single element. For the `ComboBox` and the `MultiComboBox` I changed it because the type of the [Input](https://github.com/SAP/ui5-webcomponents/blob/eea1822a1a72811521eace8d7548d7f3fd48e1b0/packages/main/src/Input.ts#L567) accepts an array as well and since (at least in my opinion) these components should behave in the same way, they should also accept an array.
Additionally I believe that the TypeScript type of the [MessageStrip](https://github.com/SAP/ui5-webcomponents/blob/eea1822a1a72811521eace8d7548d7f3fd48e1b0/packages/main/src/MessageStrip.ts#L166) is wrong. When …
> docs: fix type annotation for `icon` slot

- packages/base/package-scripts.js
- packages/base/src/global.d.ts
- packages/base/tsconfig.json
- packages/fiori/global.d.ts
- packages/main/global.d.ts
- packages/main/src/ListItem.ts
this change moves all TS related imports to the dist path
1. `base/global.d.ts` is moved to the `src` folder and contains a manual copy to `dist` as the typescript compiler does not touch .d.ts files
2. the remaining `src` imports are changed to `dist`
> chore: change all src imports to dist

- packages/localization/package.json
- yarn.lock
this way, developers with typescript won't get errors or have to install it as a dependency themselves
> fix: add openui5 types as a dependency

- packages/fiori/src/MediaGallery.js
- packages/fiori/src/NotificationListGroupItem.js
- packages/fiori/src/NotificationListItem.js
- packages/fiori/src/NotificationListItemBase.js
- packages/fiori/src/ProductSwitch.ts
- packages/fiori/src/ShellBar.js
- packages/fiori/src/SideNavigation.js
- packages/fiori/src/Timeline.ts
- packages/fiori/src/UploadCollection.ts
- packages/fiori/src/ViewSettingsDialog.ts
- packages/fiori/src/Wizard.js
- packages/main/src/Breadcrumbs.ts
- packages/main/src/Calendar.ts
- packages/main/src/Card.ts
- packages/main/src/ColorPalette.ts
- packages/main/src/ComboBox.js
- packages/main/src/Input.ts
- packages/main/src/List.ts
- packages/main/src/Menu.ts
- packages/main/src/MultiComboBox.js
- packages/main/src/MultiInput.js
- packages/main/src/SegmentedButton.js
- packages/main/src/Select.js
- packages/main/src/TabContainer.js
- packages/main/src/Table.ts
- packages/main/src/Tree.js
- packages/playground/build-scripts/api-for-sample/index.js
- packages/playground/build-scripts/samples-prepare.js
API Tables weren't fully complete because enriching the documentation with parent props wasn't correct. Previously build documentation was working with base name (Button) and name (sap.ui.webc.main.Button) of the component which was leading to not found / missing documentation. Now, we build documentation based on name (sap.ui.webc.main.Button) in order to display it correctly. Also switched @appenddocs from basename to name.
> chore: fix API tables in playground

- packages/base/CHANGELOG.md
- packages/base/package.json
- packages/create-package/package.json
- packages/fiori/package.json
- packages/icons-business-suite/package.json
- packages/icons-tnt/CHANGELOG.md
- packages/icons-tnt/package.json
- packages/icons/CHANGELOG.md
- packages/icons/package.json
- packages/localization/CHANGELOG.md
- packages/localization/package.json
- packages/main/CHANGELOG.md
- packages/main/package.json
- packages/theming/CHANGELOG.md
- packages/theming/package.json
- packages/tools/CHANGELOG.md
- packages/tools/package.json
The auto releases did not force version bump to all packages (pushed some to 1.10.2, kept some on 1.10.1), so with this change we fix this to keep all packages in sync and we need to force lerna to bump all packages even if they are not changed.
> chore: release 1.10.2 to keep all packages in sync

- package.json
- packages/tools/components-package/nps.js
- packages/tools/lib/generate-custom-elements-manifest/index.js
Generate custom element when api.json of the package is generated and use only references to the related components instead of merging their metadata (and making them as dependencies when the command is executed).
> chore: generate custom element manifest when package is build

- packages/main/src/Input.ts
setSelectionRange method is not supported by input with type "number" and throws an error
FIXES: #6386
> fix(ui5-input): prevent setSelectionRange on number input

- packages/fiori/src/BarcodeScannerDialog.ts
instead of importing the instance type, use the typescript utility helper InstanceType to describe an instance of a class is expected
> chore: improve typing

- packages/main/src/themes/Avatar.css
Color scheme aplied from the public attribute may not be strong enough if a stronger _color-scheme (e.g avatar-group ctx.) is set. 
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6405
> fix(ui5-avatar): make color-scheme attribute css selector stronger

- packages/main/src/i18n/messagebundle.properties
- packages/main/test/specs/Select.spec.js
Based on feedback and consultation with the accessibility team, the term "combobox" used for the select's `aria-roledescription` means that there may be multiple ways to change the selected value. The term "Listbox" is the more appropriate one for the ui5-select. 
Related to #2910
> fix(ui5-select): change roledescription to Listbox

- packages/main/src/TabContainer.ts
Reasons:
- `_handleResize` was async function, which is not supported type of callback by the ResizeHandler
- It awaited the rendering of the TabContainer, which is unnecessary. The logic is already in the onAfterRendering hook
- Rarely (when the media range changed), `_setItemsForStrip` was called twice - once onAfterRendering and once in `_handleResize`
Solution:
- Simplify the logic by always invalidating on resize
> refactor(ui5-tabcontainer): Simplify _handleResize

- packages/base/src/delegate/ResizeHandler.ts
- packages/fiori/src/IllustratedMessage.ts
- packages/fiori/src/Page.ts
- packages/fiori/src/ProductSwitch.ts
- packages/main/src/Breadcrumbs.ts
- packages/main/src/Carousel.ts
- packages/main/src/DateTimePicker.ts
- packages/main/src/Input.ts
- packages/main/src/List.ts
- packages/main/src/Popup.ts
- packages/main/src/SliderBase.ts
- packages/main/src/Table.ts
There are use-cases to register an async resize handler in several components (SegmentedButton, TabContainer) and currently the ResizeHandler.register accepts only sync ones. In order to allow registration of async functions:
- change **ResizeObserverCallback** type to accept async functions
- export the **ResizeObserverCallback** type and adopt ResizeObserverCallback in all components using the ResizeHandler
To Discuss:
- Does it worth using the "Promise.all" workaround to fix eslint "no-misused-promises" rule or just "eslint-disable-line"
> chore(ResizeHandler): accept async resize handlers

- docs/5-development/07-ts.md
With this change it is added a documentation section with the latest **Conventions and Guidelines** about the TypeScript development of the components for our project.
Ref: #6317
> docs: add typescript conventions and guidelines section

- packages/fiori/src/SideNavigation.js
Added ui5-side-navigation-item and ui5-side-navigation-sub-item as dependencies to dynamically scope them because they are used inside the static area template. More info: #2091
FIXES: #6361
> fix(ui5-side-navigation): scope components in static area

- .github/actions/release.js
Prior to this change the snapshot releases (0.0.0-{commit_id}), triggered via the **Release Snapshot** action used to be published as "@next" tag.
Recently we setup weekly auto releases - RC versions, such as 1.10.3-rc.0, 1.11.0-rc.0, etc. to also be published as "@next" versions, the versions look weird and mixed up.
So we either 
- option 1 - need to publish those types of  versions as two different tags
f.e. 1.11.0-rc.0 as "@next" and "0.0.0-dae342da" as "@experimental"
- option 2 - or need to align **Release-weekly-auto** and the **Release Snapshot** to both create the next "rc" and both publish as "@next" tag.
In this PR, the first option is implemented, because sometimes we want to release a state that's not actually the "next" thing, but something to try out, adn experiment with.
> chore: change snapshot npm tag to @experimental

- packages/main/test/specs/RangeSlider.spec.js
Comment out a test related to the value-swapping functionality of the RangeSlider until we find a solution for it as it fails the build regularly.
> fix(ui5-range-slider): disable unstable test temporarily

- packages/main/src/DatePicker.hbs
- packages/main/src/DatePicker.ts
- packages/main/test/specs/DatePicker.spec.js
The issue was occuring only when you write wrong value in input, focus out, then select something and without focusing out write the same wrong value in the input and then focus out. This was not triggering the change event of the input, hence we were not validating the value, because the input would have same value before and after the selection.
Now we set the value to the input when we select, so the input would react to every value change.
fixes: https://github.com/SAP/ui5-webcomponents/issues/6303
fixes: https://github.com/SAP/ui5-webcomponents/issues/5963
> fix(ui5-date-picker): align value state

- packages/fiori/src/themes/ShellBarPopover.css
- packages/main/src/themes/SelectPopover.css
- packages/main/src/themes/Suggestions.css
Color of the icons (of list items/options) isnide dropdown should be the same as the  text color of the options.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6068
> fix(ui5-select, ui5-suggestion-item, ui5-shellbar): color of icon inside options is according to spec

- packages/main/src/SegmentedButton.ts
- packages/main/test/pages/SegmentedButton.html
- packages/main/test/specs/SegmentedButton.spec.js
The slot where segmented button items are placed, was not set to invalidate the component when some of the child items was changed ("pressed" to be exact). So setting directly "pressed" attribute of any item did not tell the parent control that something was changed. In addition, the logic that removes the pressed state of other segmented button items when another one was set as "pressed" worked partially, so there were scenarios where more than one segmented button item can be in "pressed" state. This PR fixes the issue by setting a slot to invsalidate when children are changed, and the logic for updating "pressed" states of the items is fixed too.
Fixes: #5890 
Fixes: #4969
> fix(ui5-segmented-button): press item programatically works properly

- packages/main/test/samples/ColorPalettePopover.sample.html
There was wrong tag mentioned in the Playground page of ui5-color-palette-popover. Now it is fixed.
Fixes: #6496
> docs(ui5-color-palette-popover): fix tag in Playground page

- packages/main/bundle.common.js
- packages/main/test/specs/Icon.spec.js
- packages/tools/lib/create-icons/index.js
**Background**
After splitting the SAP TNT icons to support 2 version - v2 and v3, we now have a top level module , that refers to and imports the versioned ones.
Before the split, the top level module used to export the icon name, including the collection ("tnt/actor"). 
After the split, the top level module (built from different flow) includes only the icon name ("actor").
```js
// In recent RC release the exported value is "actor"
import actor from "@ui5/webcomponents-icons-tnt/dist/actor.js";
```
[RC release](https://unpkg.com/browse/@ui5/webcomponents-icons-tnt@1.11.0-rc.2/dist/actor.js) 
```js
// In our latest release the exported value is "tnt/actor"
import actor from "@ui5/webcomponents-icons-tnt/dist/actor.js";
```
[latest …
> chore: fix tnt icons export value

- packages/playground/.storybook/main.ts
Deployed assets are always one directory back in the `gh-pages` branch. The storybook build is in the `./_playground` dir. Changing the assets path to relative `../` ensures storybook assets are loaded successfully in the `main` sub directory as well.
> fix(playground): use relative path for storybook assets

- packages/main/src/Tree.ts
The `TreeItemCustom` is a public component, but the API reference is not available - let's add it.
> docs: add ui5-tree-item-custom API docs

- packages/main/src/themes/ToggleButton.css
- packages/main/src/themes/base/ToggleButton-parameters.css
- packages/main/src/themes/sap_belize/ToggleButton-parameters.css
- packages/main/src/themes/sap_belize/parameters-bundle.css
- packages/main/test/pages/ToggleButton.html
There was not applied text-shadow of the non-pressed Emphasized Toggle Button in Belize theme.
This PR fixes it.
In fact the issue is reported for sap.ui.webc.main.ToggleButton
Internal incident: 2270135209
> fix(ui5-toggle-button): fix Emphasized Toggle Button text shadow in Belize theme

- packages/main/src/TreeList.ts
- packages/main/test/pages/Tree.html
- packages/main/test/specs/Tree.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6571
The flag `includeCollapsed` was not passed to the recursive call of `flattenTree` function, causing it not to work pass the the second level of sub nodes.
> fix(ui5-tree): correctly pass mode to sub items

- docs/2-advanced/01-configuration.md
Storybook mdx can't prase new lines using `<br/>` tags inside tables. Until we figure out a new way and add a eslint-mdx plugin, we will temporary remove new lines fron md tables
> fix(chore): temporary remove new lines in md tables

- packages/main/test/samples/Table.sample.html
> fix(ui5-table): adjust sample snippet

- packages/main/src/SelectPopover.hbs
If the valuestate message text is too long, sometimes it all the space of the selec't popover. This way the select items are not visible and can't be accessed by scrolling.
This is why valuestate is no longer in the header slot of the select's popover but in the content slot. This way a scrollbar appears when the valuestate text is too long and the select's items are not visible/accessible.
Fixes #5970
> fix(ui5-select): fixed valuestate message scroll prevention

- packages/main/src/MultiComboBox.js
- packages/main/src/themes/MultiComboBox.css
- packages/main/src/themes/MultiInput.css
- packages/main/src/themes/base/sizes-parameters.css
Previously, the ui5-tokenizer had a defined min-width no matter there are tokens or not which was not correct. When there are no tokens presented, the ui5-tokenizer width is expected to be 0.
> fix(ui5-multi-input/ui5-multi-combobox): enhance tokenizer visualization

- packages/main/src/ListItem.ts
- packages/main/test/pages/List_test_page.html
- packages/main/test/specs/List.spec.js
Fix `selection-change` private event detail  `selectionComponentPressed`:
- event target type `HTMLInputElement` replaced with `CheckBox`
- event target type is `RadioButton`, not `ListItemBase`
- the property of the RadioButton is `checked` (after 1.0), not `selected` (prior to 1.0) (due to this - actually the logic was not working for a long time)
- add a test to cover the click on a radio button
> chore(ui5-li): fix `selection-change` event detail

- packages/fiori/src/UploadCollection.ts
`UploadCollection` has been migrated separately, `UploadCollectionItem` was not present
> refactor: use `UploadCollectionItem` as `UploadCollection` items slot type

- packages/base/src/Boot.ts
- packages/base/test/assets/bundle.light.js
- packages/base/test/assets/styles/Boot.css
- packages/base/test/pages/Boot.html
- packages/base/test/specs/Boot.spec.js
Previously calling `attachBoot` used to trigger `boot`, which was causing unexpected issues.
```js
const attachBoot = async (listener: () => void) => {
await boot();
listener();
};
```
One effect of this was that theme properties were not loading properly. This happens when the theme registration (triggered by component define call) comes after someone calls `attachBoot`. In this case, our logic looks for a registered theme properties, can't find any and continues without loading. 
```js
// applyTheme.js
const loadThemeBase = async (theme: string) => {
if (!isThemeBaseRegistered()) {
return; // no theme props are registered at this point
}
}
```
Later when the registration happens and boot is called again, we reuse the created promise and just return,
and we no longer reach to the point …
> fix(framework): fix boot, interfering theme load

- packages/tools/lib/create-new-component/index.js
- packages/tools/lib/create-new-component/jsFileContentTemplate.js
- packages/tools/lib/create-new-component/tsFileContentTemplate.js
Previously the component package level command `create-ui5-element` was producing skeleton files for a new web component with only **JavaScript** as a possible and **_default_** option. 
Within this change since we support TypeScript for development and even more, 3rd parties can now create custom web component in **TypeScript.**
#
Additionally the following is implemented as well:
- Now when a user is executing the `yarn create-ui5-element`, could specify up to **three** arguments:
- **component name** 
` yarn create-ui5-element myComponent `
- **custom tag name** 
`yarn create-ui5-element myComponent my-component`
- **language** 
`yarn create-ui5-element myComponent my-component typescript`
Each argument is independent from one another, which means if:
- One argument is provided, a …
> feat: enhance create-ui5-element command to create component in TS

- packages/main/src/themes/Input.css
- packages/main/src/themes/TextArea.css
Having these styles applied, the text styles relevant to the text spacing accessibility standard were not applied when an input component was placed within a shadow DOM. As they are not needed and not specified in the visual specification, they are removed.
FIXES: #5792
> fix(ui5-input, ui5-textarea): remove redundant styles

- packages/fiori/src/SideNavigationItem.ts
- packages/fiori/src/SideNavigationSubItem.ts
The lack of these 2 interfaces breaks the OpenUI5 Retrofit build when trying to upgrade.
> docs: fix side navigation items interfaces

- packages/icons-business-suite/src/json-imports/Icons.ts
- packages/icons-tnt/src/json-imports/Icons.ts
- packages/icons/src/json-imports/Icons.ts
vitejs complains when using a template literal (even a static one) in an import
> fix(icons): use strings instead of template literal for imports

- packages/main/src/ComboBox.ts
- packages/main/test/specs/ComboBox.spec.js
Previously, when a suggestion was selected and then a value matching another suggestion was entered, the selection-change event was not fired which is not correct.
FIXES: #6560
> fix(ui5-combobox): fire selection-change correctly

- packages/main/src/features/InputElementsFormSupport.ts
Without the `.js` file extension, projects building in ESM mode will fail due do an import error:
```bash
node_modules/@ui5/webcomponents/dist/features/InputElementsFormSupport.d.ts:1:29 - error TS2307: Cannot find module '@ui5/webcomponents-base/dist/UI5Element' or its corresponding type declarations.
1 import type UI5Element from "@ui5/webcomponents-base/dist/UI5Element";
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```
> refactor(InputsElementFormSupport): add file extension to import

- packages/localization/lib/copy-and-strip-cldr/index.js
- packages/localization/package-scripts.js
CLDR files have grown a lot lately after updating to the recent OpenUI5 version. This change aims to reduce their size by stripping all fields that are not used by any of our components.
With this change CLDR .json files are around 55% smaller.
The only components that import files from `@ui5/webcomponents-localization` are:
- `ui5-calendar`
- `ui5-date-picker` (and its parts)
- `ui5-time-picker` (and its parts)
- `ui5-datetime-picker`
closes: https://github.com/SAP/ui5-webcomponents/issues/6692
> chore: strip CLDRs of unused fields

- packages/main/src/SplitButton.hbs
- packages/main/src/SplitButton.ts
- packages/main/test/pages/SplitButton.html
Solution: We don't create slot for text if we don't have text.
fixes: https://github.com/SAP/ui5-webcomponents/issues/6688
> fix(ui5-split-button): align styles in icon only mode

- packages/base/package-scripts.js
- packages/localization/package-scripts.js
- packages/tools/components-package/eslint.js
- packages/tools/components-package/nps.js
When creating a JS type of components package via the `yarn create @ui5/webcomponents-package` command, the `@typescript-eslint` package that is used by the eslint config requires `typescript `and the lint command fails. Now the TS overrides are added only for TS  projects and JS Projects lint works properly.
> fix: fix eslint for JS 3rd party projects

- docs/2-advanced/01-configuration.md
- packages/base/src/config/Language.ts
- packages/base/src/config/Theme.ts
Currently, users are not able to set language and theme to their default values because there is no mechanics for that.
With this PR we are introducing new `getDefaultLanguage` / `getDefaultTheme` method which returns the default value for language / theme.
To reset your language to the default value:
```ts
import { setLanguage, getDefaultLanguage } from "@ui5/webcomponents-base/dist/config/Language.js";
setLanguage(getDefaultLanguage());
```
To reset your theme to the default value:
```ts
import { setTheme, getDefaultTheme } from "@ui5/webcomponents-base/dist/config/Theme.js";
setTheme(getDefaultTheme());
```
Fixes: #6712
> feat(framework): add default values for language/theme

- packages/fiori/src/NotificationListItemBase.ts
NotificationListItemBase's appears to be `ui5-li-notification-group` but should not:
```json
{
"kind": "class",
"name": "sap.ui.webc.fiori.NotificationListItemBase",
"basename": "NotificationListItemBase",
"tagname": "ui5-li-notification-group",
}
```
Also, no need to append docs, as this is done by the NotificationListItem and NotificationListGroupItem.
> docs: fix NotificationListItemBase's jsdoc

- packages/base/src/asset-registries/Icons.ts
- packages/main/bundle.common.js
- packages/main/test/specs/Icon.spec.js
The Button component needs to set the icon's accessible name as its "tooltip". And for that we introduce the `getIconAccessibleName` method to return the accessible name for the given icon name:
```js
import { getIconAccessibleName } from  "@ui5/webcomponents-base/dist/asset-registries/Icons.js";
getIconAccessibleName("back-to-top") // returns "Back To Top"
```
Related to: https://github.com/SAP/ui5-webcomponents/pull/6719
> chore: add `getIconAccessibleName` base method

- packages/main/src/DatePicker.ts
- packages/main/src/TimePickerBase.ts
Hi, those types were in the meantime improved in the copy in the OpenUI5 repo, but reverted by the latest copy.
I redid the improvements in I9663c71d80280bb0841fb8a2e36c44a174378955, but they would be overridden again. Am I right assuming that the DateTimePicker etc. get the types from these two base classes?
The commit message mimics the one of https://github.com/SAP/ui5-webcomponents/commit/e50e00cddcba575d61442a9f87b48523369c8d51
> chore: improve DatePicker/TimePickerBase types (brought over from OpenUI5)

- packages/fiori/src/SideNavigation.ts
Styles were wrongly described in customElement decorator.
Fixes: #6813
> fix(ui5-side-navigation): correct-style description

- packages/main/src/CalendarPart.ts
- packages/main/test/pages/Calendar.html
- packages/main/test/specs/DatePicker.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/6750
> feat(ui5-calendar): focus the nearest day when today is out of range

- docs/3-customizing/01-theme.md
- packages/base/bundle.esm.js
- packages/base/src/validateThemeRoot.ts
- packages/base/test/pages/Configuration.html
- packages/base/test/specs/ConfigurationURL.spec.js
Fix error when relative paths are used for theme root and add documentation how the external themes could be loaded.
Related to: #6758
> fix(framework): relative paths for external themes

- packages/base/lib/generate-asset-parameters/index.js
- packages/base/src/config/Icons.ts
- packages/base/src/config/Theme.ts
- packages/base/src/global.d.ts
- packages/main/bundle.common.js
- packages/main/test/pages/base/IconCollection.html
- packages/main/test/pages/base/IconCollectionInCustomTheme.html
- packages/main/test/pages/css/css_variables.horizon.css
- packages/main/test/specs/base/IconCollection.spec.js
- packages/tools/lib/create-icons/index.js
Currently, for older themes (`sap_belize`, `sap_fiori_3`) we display old icon fonts, while for `sap_horizon` - the latest icon fonts. This applies for all icon collections. And, to do that we check if the current theme is part of the `sap_horizon` theme family or not. However, once an app is using custom theme, the current theme has a custom theme and by default we will enforce the old icon fonts, because the custom theme name won't match "sap_horizon".
With this change, when the current theme name is not part of the built-in theme families, we now look for an custom theme and check the base theme that the custom theme is built upon.
- rename `isThemeFamily`  to `isLegacyThemeFamily` and adopt it in the code (all isThemeFamily("sap_horizon") calls are replaced with !isLegacyThemeFamily)
- …
> fix(theming): fix icons version detection for custom theme (built via the ThemeDesigner)

- packages/main/test/specs/base/IconCollection.spec.js
- packages/tools/lib/dev-server/virtual-index-html-plugin.js
- packages/tools/lib/dev-server/virtual-index-html-plugin.mjs
- vite.config.js
When `yarn start` is executed inside root folder the vite config file is not found because of an error. Packages have `type: module` config and based on that setting vite requires ESM modules and the root folder doesn't have that setting so when vite is started there CJS module is required which leads to an error when shared config is used.
> chore(framework): fix build

- packages/base/index.js
- packages/base/src/decorators/slot.ts
Notes:
- the change to `slot.ts` was needed, because when I re-export `slot`, I get eslint errors regarding the combination of the `?` operator and the `default` keyword. This is most probably a glitch with eslint.
- modules with side effects (all modules from `features/`) are **not re-exported** in order to avoid potential complications with build tools (if they are not tree-shaken, thus all features unnecessarily registered)
- the order of exports is following the directory structure of `src/`: sub-directories first, and then the files in `src/` itself, and not alphabetically for the exported entities.
*Not all re-exported functions are documented (with `@public`) - let me know if others are considered public and needed*
closes: https://github.com/SAP/ui5-webcomponents/issues/6739
> feat(framework): re-export all public imports from index.js

- packages/theming/lib/generate-css-vars-usage-report/index.js
Inside ESM modules __dirname and __pathname variables doesn't exist so we have to define them by ourselves.
With the previous solution paths are resolved to `\C:\user...` on windows. When these paths are used for creating a new file the destination path is `C:\C:\user..`.
With the new solution paths are resolved to `C:\user...`.
> chore: correct dir path when generate css vars usage report

- packages/base/src/decorators/customElement.ts
The `customElement` decorator used to set default values for `languageAware = false`, `themeAware = false`, `fastNavigation = false` when the fields are not provided. However, this leads to a wrong metadata in case the field is set by a parent class. Then, the value set by the parent class won't be considered as the child class already set it to "false" and as expected the values set by the child class are taken with precedence.
**For Example:**
- `Calendar` component `does not set languageAware` at all (but gets  languageAware: false by default)
- Calendar's parent class `DateComponentsBase` has `languageAware: true`
- When merging the metadata of the inheritance chain to get the resulting metadata, the Calendar's metadata is taken with precedence and languageAware is false at the end, …
> fix: fix components metadata calculation

- packages/base/src/getSharedResource.ts
The **"ui5-shared-resources"** elements used to be created in the **"head"**. However, this turns out to be invalid markup as per the [HTML standard](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/head): **title**, **meta**, **link**, **script**, **style**, **base**, **noscript** and **template** tags are allowed only. With this change, it becomes part of the **body**.
**Note:** `document.querySelector("ui5-shared-resources")` continues working, however accessing via the head, f.e `document.querySelector("head>ui5-shared-resources")`, won't work anymore.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6748
> fix(framework): remove invalid element from head

- packages/main/src/TreeItem.hbs
- packages/main/src/themes/TreeItem.css
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6757
Similarly to the `ListItem` components, the `additionalText` element is now rendered outside the `.ui5-li-text-wrapper` container, preventing alignment issue when the main text truncates.
> fix(u5-tree-item): correct text alignment on truncation

- packages/fiori/src/themes/TimelineItem.css
While `layout` property/attribute of the `ui5-timeline` component is being not set, or set to `layout="Vertical"` the chronological line, wasnt rendering. With this change is now being rendered properly. 
Also the **dot** which is being rendered when there is no `icon` set, is now positioned with pixel-perfect vertical and horizontal alignment.
Fixes: #6827
> fix(ui5-timeline*): fix chronological line not displaying in vertical or default layout

- packages/base/src/util/FocusableElements.ts
- packages/main/test/pages/Dialog.html
- packages/main/test/specs/Dialog.spec.js
getLastFocusableElement returns wrong element when it looks for previous focus element. It's because when we go over assigned elements to slot we only check forward. Now, we go over elements based on the direction of the traversing.
Fixes: #6858
>  fix(framework): return correct element when getLastFocusableElement is used

- packages/fiori/src/themes/Bar.css
When there are a `Button/s` inside a `ui5-bar` component, which is being shrinked or is used in a small aspect, the top and bottom borders of the `Button` components are being hidden.
With this change now in every length, the `Buttons` are displayed properly.
> fix(ui5-bar): fix top and bottom border of Buttons hidden in ui5-bar when shrinked

- packages/base/src/asset-registries/Icons.ts
Fixing the issue in the framework will be safer for future use cases.
closes: https://github.com/SAP/ui5-webcomponents/issues/6889
> fix: getIconAccessibleName now handles empty strings

- packages/main/src/TableRow.ts
- packages/main/src/themes/TableCell.css
- packages/main/src/themes/TableRow.css
The combination of display: table-cell and overflow: hidden styles
was causing the browser to crash upon component re-rendering
Fixes: #6570
> fix(ui5-table): prevent Safari from crashing

- packages/fiori/src/themes/ShellBar.css
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6212
> fix(ui5-shellbar): primary title respects text spacing styles

- packages/main/src/themes/Menu.css
- packages/main/src/themes/base/rtl-parameters.css
We have an issue which occurs when using the `ui5-menu` component, where the opener of the menu is aligned to the right side of the screen. When attempting to hover over the sub-menu items, they unexpectedly close or disappear. This problem occurs more frequently when the cursor is moved slowly.
The cause of this issue seems to be a small gap between the menu and the sub-menu items, which is only noticeable when the opener is aligned to the right side of the screen. This issue can be frustrating for users who are trying to navigate the menu and its sub-menus.
With this change, the sub-menus are aligned properly ( including in **RTL**, **LTR** mode ).
Fixes: #5802
> fix(ui5-menu): fix children closing unexpectedly when opener is right aligned

- packages/base/src/StaticArea.ts
Since this modules has no `import`, nor `export` statements, some build tools may get confused about its module type. To avoid this, the otherwise anonymous class is now named, and exported. This will not change existing functionality.
closes: https://github.com/SAP/ui5-webcomponents/issues/6916
> chore: export StaticArea class

- packages/main/src/themes/TableCell.css
- packages/main/src/themes/TableRow.css
Fixes: #6843
Safari ignores table row height. Now the `height` style property is moved from `ui5-table-row` to `ui5-table-cell`, which is more correct since the row takes the height of the cell as a min-height. 
> The height of a 'table-row' element's box is calculated once the user agent has all the cells in the row available: it is the maximum of the row's computed ['height'](https://www.w3.org/TR/CSS2/visudet.html#propdef-height), the computed ['height'](https://www.w3.org/TR/CSS2/visudet.html#propdef-height) of each cell in the row, and the minimum height (MIN) required by the cells. A ['height'](https://www.w3.org/TR/CSS2/visudet.html#propdef-height) value of 'auto' for a 'table-row' means the row height used for layout is MIN. MIN depends on cell box heights and cell box alignment …
> fix(ui5-table): correct row height in Safari

- packages/tools/lib/esm-abs-to-rel/index.js
- packages/tools/lib/i18n/toJSON.js
- packages/tools/lib/jsdoc/preprocess.js
- packages/tools/lib/replace-global-core/index.js
`globby` is bugged on Windows and does not work if you pass it `\`, it only works with `/`
Some usages were already fixed, but some were still broken.
> chore: fix globby usage in Windows

- packages/main/test/specs/DateRangePicker.spec.js
With Chrome 111, some DateRangePicker tests started to fail. The upgrade seems to have broken how Date objects are transferred from the browser to the wdio test runtime.
With this change, the dates are transferred as timestamps instead of date objects and are converted to Date objects in the test.
> chore: restore failing tests correctly

- packages/base/src/delegate/ResizeHandler.ts
> fix(framework): avoid ResizeObserver loop limit exceeded error

- packages/main/src/InputPopover.hbs
- packages/main/src/themes/Suggestions.css
FIXES: #6943
The `ui5-input` is using another `ui5-input` for the content of its dialog on mobile device. Other components such as combobox share the same styles as the ui5-input, but the use native input. That leads to some issues when same styles are applied for all mobile input dialogs.
> fix(ui5-input): remove double border of input in dialog on phone

- packages/main/src/Carousel.ts
- packages/main/src/TabContainer.ts
Rewrote the comment to display the actual HTML code for the example.
Additionally, marked the Carousel's getter `visibleItemsIndices`
as `@public` so it shows in the playground.
> docs(ui5-tabcontainer): rewrite JSDoc

- packages/main/src/themes/TabContainer.css
- packages/main/test/specs/TabContainer.spec.js
The focus outline of the overflow buttons now has correct border radius
Fixes: #6763
> fix(ui5-tabcontainer): correct focus outline

- packages/main/src/Popup.ts
Sometimes on Safari, after the dialog is opened, a focusin event will be fired on the root. This event will race with the applyInitialFocus call which results in the wrong element being focused.
This PR attempts to solve the issue.
Part of #6768
> fix(ui5-dialog): always wait for applying of initial focus to complete

- packages/main/src/Title.ts
- packages/main/src/themes/Link.css
- packages/main/src/themes/Title.css
- packages/main/src/themes/base/Link-parameters.css
- packages/main/src/themes/sap_horizon/Link-parameters.css
- packages/main/src/themes/sap_horizon_dark/Link-parameters.css
- packages/main/src/themes/sap_horizon_hcb/Link-parameters.css
- packages/main/src/themes/sap_horizon_hcw/Link-parameters.css
- packages/main/test/pages/Title.html
- packages/main/test/pages/styles/Title.css
- packages/main/test/samples/Title.sample.html
- packages/playground/_stories/main/Title/Title.stories.ts
There are cases when a Link will be used inside a Title.
Elements nested inside, mainly the Link, will inherit the Title's font styles.
Refactored Link to allow for overstyling. Updated text-underline when hovering a Subtle link to match the latest VD spec.
Fixes #6785
> feat(ui5-title): add custom overstyles when used with Link

- packages/main/src/Tab.ts
- packages/main/src/TabInStrip.hbs
- packages/main/src/themes/TabInStrip.css
- packages/main/test/pages/TabContainer.html
Strip tabs text is bottom aligned even when there is no additional text
Fixes: #6764
> fix(ui5-tabcontainer): bottom align tab strip item text with no additional text

- packages/main/src/Card.ts
This is a leftover from a refactoring. The relevant text with the information about CSS Shadow Parts remains in the CardHeader component.
Part of #6381
> docs(ui5-card): remove outdated CSS Shadow Parts text

- packages/create-package/template/tsconfig.json
We found issues with 3rd party generated packages with the `create-package` tools, caused by the recently updated (with the latest 1.13.0) `tsconfig` setting for moduleResolution -`node16` . The package is not ready for `node16`, it requires more efforts to make it work, thus reverting back to `node` to have at least a stable state and the running properly as before.
> fix(create-package): revert  `moduleResolution` setting to `node`

- packages/create-package/create-package.js
- packages/create-package/template/src/MyFirstComponent.js
- packages/create-package/template/src/MyFirstComponent.ts
Added the option to choose a namespace for the JSDoc comments when creating a package. This is relevant for the UI5 Enablement scenario.
Note: the current templating must be improved. If the `INIT_PACKAGE_VAR_NAME` var is replaced in the templates first, it will "break" usages of `INIT_PACKAGE_VAR_NAMESPACE`. Therefore, the longer name (`INIT_PACKAGE_VAR_NAMESPACE`) must be replaced first. We should consider using the `<%= VAR_NAME %>` syntax or similar.
> feat: users can provide a JSDoc namespeace when creating a package

- docs/2-advanced/09-scrollbars-customization.md
- docs/2-advanced/10-ignore-custom-elements.md
- packages/base/README.md
- packages/base/src/IgnoreCustomElements.ts
- packages/base/src/UI5Element.ts
- packages/main/bundle.common.js
- packages/main/test/pages/base/IgnoreCustomElements.html
- packages/main/test/pages/base/styles/IgnoreCustomElements.css
- packages/main/test/specs/base/IgnoreCustomElements.spec.js
The framework always waits for the definition of slotted children inside UI5 Web Components' if they have hyphen ("-") in their name (e.g another custom element), which is required in many cases, but unnecessary when the slotted custom HTML element has no JavaScript attached and has pure semantic purpose.
Provide new API to allow users define such tags that later the framework can ignore, improving the time to render factor for our components.
```js
import { ignoreCustomElements } from "@ui5/webcomponents-base/dist/IgnoreElements.js";
ignoreCustomElements("app-");
```
The feature is useful, when UI5 Web Components and used together with custom HTML elements with custom tags to make application's markup more semantic.
For example:
```html
<ui5-card>
<app-trip-calendar></app-trip-calendar> …
```
> feat(framework): add `ignoreCustomElements` public API

- packages/base/src/getSharedResource.ts
- packages/base/src/util/getSingletonElementInstance.ts
- packages/base/test/specs/SystemDOMElements.spec.js
**Background**
Previously we used to create `ui5-shared-resources` semantic HTML element to store shared resources (as registered runtimes, tags and SVGs) that can be reused between multiple UI5 Web Components runtimes.
The element used to be appended to the `head` in the past, but this produced invalid markup when tested with HTML validators as there is specific list of allowed tags that can be inserted in the `head`. To address this, we moved the `ui5-shared-resources` to the `body`.
**Issue**
However, currently we got another issue with `the body not being ready` at the point we access it and try to append the `ui5-shared-resources`. And, this issues is subject of the current PR.
**Solution**
Use `meta` tag with the minimum required attributes and append it to head (the `meta` tag is …
> fix(framework): store shared resources as `meta` tag within the `head`

- packages/main/src/Tree.ts
- packages/main/test/pages/TreeDynamic.html
*This is not the final solution but a workaround.*
**This issue must be addressed on framework level.**
The problem is that the `ui5-list` inside the `ui5-tree`'s shadow root has a `slot` child and the list items are inside the slot. This slot is taken into account in the tree code (`getSlottedItems` used everywhere) so the list renders correctly regardless of whether its list items are direct children of the list, or come through a slot. However, the framework's invalidation logic does not take this case into account.
closes: https://github.com/SAP/ui5-webcomponents/issues/6726
> fix(ui5-tree): tree list is re-rendered when the tree changes

- README.md
- docs/3-customizing/README.md
- docs/ReleaseManagement.md
Adds a new article to describe the Release management in UI5 Web Components - the semantic versioning strategy that we apply and the  established release schedule of monthly stable and weekly preview releases.
> docs: add `release` management info

- packages/main/src/Label.hbs
- packages/main/src/Label.ts
- packages/main/src/i18n/messagebundle.properties
- packages/main/src/themes/Label.css
- packages/main/test/pages/Label.html
- packages/main/test/pages/modules/LabelPage.js
- packages/main/test/pages/styles/Label.css
- packages/main/test/specs/Label.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7048
> fix(ui5-label): colon symbol is now language-dependent

- packages/main/src/Menu.ts
- packages/main/test/pages/Menu.html
- packages/main/test/samples/Menu.sample.html
- packages/main/test/specs/Menu.spec.js
The ui5-before-open event is now getting fired for the sub-menus as well.
As a result the application developers would be able to fetch data from
a database before a sub-menu gets opened. In the meanwhile the busy
state of the sub-menu will be displayed.
Related to: #6131
> feat(ui5-menu): dispatch ui5-before-open for the sub-menus

- packages/fiori/src/themes/TimelineItem.css
- packages/main/src/themes/DatePicker.css
- packages/main/src/themes/TimePicker.css
- packages/main/test/pages/TimePicker.html
- packages/main/test/pages/styles/TimePicker.css
There was a little overflowing in the input fields of the `ui5-datetime-picker` and the `ui5-time-picker` as we can see from the example below.
There should be margin, but it should not be visible as it was:
Fixes: #5912 
Fixes: #7021 
Fixes: #7104
> fix(ui5-datetime-picker/ui5-time-picker): fix top and bottom overflows of input

- packages/main/src/Menu.ts
It's followup PR on recently merged [change](https://github.com/SAP/ui5-webcomponents/pull/7064) that introduced "before-open" event for opening of sub-menus and new event parameter "item".
The PR is meant to:
- correct the event.detail.item "type" in the event docs from "Object" to "HTMLElement" as it's the `ui5-menu-item` element that is passed as event detail, not some kind of Object.
- [in addition as I have noticed the events are not described with TS types] 
add new TS types for several events ("item-click", "before-open" and "before-close" as all have event details) and describe their details, and use them in the fireEvent generic syntax to enable static code checks.
> docs(ui5-menu): improve jsdoc

- packages/create-package/create-package.js
Handle following package name patterns as valid package names:
- some-package
- under_score
- 123numeric
- example.com
- @npm/thingy
- @jane/foo.js
Some unused functions are removed.
> chore: support more package name patterns

- packages/fiori/src/DynamicSideContent.ts
- packages/fiori/src/FlexibleColumnLayout.ts
- packages/fiori/src/NotificationListGroupItem.ts
- packages/fiori/src/NotificationListItem.ts
- packages/fiori/src/NotificationListItemBase.ts
- packages/fiori/src/ShellBar.ts
- packages/fiori/src/UploadCollection.ts
- packages/fiori/src/ViewSettingsDialog.ts
- packages/main/src/Breadcrumbs.ts
- packages/main/src/Calendar.ts
- packages/main/src/ComboBox.ts
- packages/main/src/DatePicker.ts
- packages/main/src/DateRangePicker.ts
- packages/main/src/DateTimePicker.ts
- packages/main/src/Dialog.ts
- packages/main/src/FileUploader.ts
- packages/main/src/Input.ts
- packages/main/src/List.ts
- packages/main/src/Menu.ts
- packages/main/src/MultiComboBox.ts
- packages/main/src/MultiInput.ts
- packages/main/src/Popover.ts
- packages/main/src/SegmentedButton.ts
- packages/main/src/Select.ts
- packages/main/src/TabContainer.ts
- packages/main/src/Table.ts
- packages/main/src/TimePicker.ts
- packages/main/src/TimePickerBase.ts
- packages/main/src/Tree.ts
- packages/main/src/features/InputSuggestions.ts
The PR addresses inconsistencies with event detail types: missing types, wrong naming or missing exports of types:
- add missing event detail types
- rename existing  types to follow the convention: `type {ComponentName}{EventName}EventDetail = {}`
- export all event detail types
- re-export event detail types of base classes from child classes (see DateTimePicker, DateRangePicker)
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7118
> chore: add event detail types

- packages/main/test/samples/FileUploader.sample.html
As there are ongoing discussions regarding the inclusion of the new property **`accessibleNameRef`** in our **`ui5-file-uploader`** component, we have decided to enhance the accessibility aspects of the component's samples. This improvement involves providing instructions on utilizing the accessibility features by incorporating them into the examples. However, if the decision is made to include the mentioned property, the samples might need to be updated again.
Part of: #5893
> docs(ui5-file-uploader): improve accessibility showcase for samples

- packages/fiori/src/UploadCollection.hbs
- packages/fiori/src/UploadCollection.ts
The import to the Tent illustration was wrong. Previously the import used to include the **"sapIllus-Scene-Tent.js"** which is the illustration just for one of the sizes (the illustration changes on resize). However, we need to import the top-level module **"Tent.js"** as it's the one to register the illustration "Tent" in the illustration registry.
And to force the "Scene" size, we can set it directly in the template as the IllustratedMessage provides a property for it - "size".
In the test pages and the playground sample we have all illustrations as part of the bundle, so the problem can't be seen - it does not matter if it's written as before or even if we don't add the import at all, the illustration will be displayed.
However, in real-case apps where the app imports only the things …
> chore: fix import to "Tent" illustration

- packages/playground/.storybook/addons/html/processors/AttributeProcessor.ts
Related to: #7035
Working with a copy of the attributes array fixes an issue of wrong indexing and randomly skipping to filter the private APIs
> docs(playground): use copy of attributes array for API filter

- packages/fiori/src/themes/ShellBar.css
- packages/main/src/themes/base/rtl-parameters.css
By removing the `float` property, the searchField slot can now expand to its parent full width container in RTL mode.
Fixes: #7065
> fix(ui5-shellbar): improve RTL styling of searchField

- packages/fiori/src/themes/Bar.css
With this change we apply the correct value to the `box-shadow` property in our `<ui5-bar>` component, according to latest specifications.
Fixes: #6150
> fix(ui5-bar): apply correct box-shadow parameter

- packages/main/src/Select.ts
- packages/main/src/TextArea.ts
New property popover is released with Google Chrome version 1.114. This new property collides with our current existing class members and this collision leads to errors that block the whole page.
https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover
FIXES: #7147
> fix(ui5-textarea, ui5-select): collision of 'popover' property with Google Chrome 

- packages/base/src/StaticAreaItem.ts
When static area item's getDomRef function is used, it updates only content density related properties. All other properties like scoping attribute or runtime index attribute are added / updated only when the owner of the static area item owner is updated. With this change we made all properties to be properly updated.
> fix(ui5-static-area-item): element additional properties

- packages/base/src/css/FontFace.css
- packages/main/test/pages/Card.html
- packages/main/test/pages/FontFace.html
- packages/main/test/pages/styles/Card.css
- packages/main/test/pages/styles/FontFace.css
Fetch the latest font file and then fallback to locally installed.
- reorder font source origin `url()` and `local()` and make `url` first (previously `local()` used to be first and then followed by `url()`), so the latest version of the woff2 file will be fetched, and if this fails it will fallback to locally installed font with the same name.
This is also the order in OpenUI5: https://github.com/SAP/openui5/blob/master/src/themelib_sap_horizon/src/sap/ui/core/themes/sap_horizon/shared.less#L259
- the path to the external source is slightly changed: sap/ui/core/themes/**sap_fiori_3** changed to sap/ui/core/themes/**sap_horizon**, although it should be the same
- added test pages
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7177
> fix(framework): prioritize external fonts over locally installed

- packages/main/src/ComboBoxPopover.hbs
Same implementation as `MultiComboBoxPopover.hbs` (extract `listItem` partial).
This is needed by our stakeholders who build their custom combobox, based on ours.
> refactor(ui5-combobox): extract listItem inline

- packages/create-package/template/src/MyFirstComponent.js
- packages/create-package/template/src/themes/MyFirstComponent.css
- packages/create-package/template/test/pages/css/index.css
Changes:
- used `type` instead of `validator` for the JS version (OpenUI5 uses the 1.5 runtime where `validator` is not introduced yet) - this can be reverted once the OpenUI5 version is upgraded
- made the styles less reliant on the test page (more CSS into the host)
> chore: improve the create package component

- packages/main/src/ComboBox.ts
- packages/main/test/pages/ComboBox.html
- packages/main/test/specs/ComboBox.spec.js
Previously, all items matching the user input were selected. According to the specification, only the first matching item has to be selected.
FIXES: #6978
> fix(ui5-combobox): prevent selection of multiple items

- packages/main/src/MultiComboBox.ts
On mobile device, when text is typed in the dialog's input and suggestion is selected, then the OK button is pressed, if custom value is not allowed, we have to clear the typed in value.
FIXES: #6966
> fix(ui5-multi-combobox): delete value after OK button is pressed

- packages/tools/components-package/postcss.themes.js
- yarn.lock
Currently, to scope the CSS variables in the current runtime, we modify selectors by adding [_ui5host] attribute and the final selector for compact mode looks like: `.sapUiSizeCompact [_ui5host]`. With this selector we can set compact mode to component only if parent its parent has that `.sapUiSizeCompact` class and not by adding it directly to component `<ui5-button class="sapUiSizeCompact"></ui5-button>`.
With this change we enhance the selectors to `.sapUiSizeCompact [_ui5host], .sapUiSizeCompact[_ui5host]`. This way, we can handle both cases and now, we can explicitly set compact/rtl mode to component.
> fix(framework): missing CSS variables in compact mode / rtl mode

- packages/main/src/themes/RangeSlider.css
- packages/main/src/themes/SliderBase.css
- packages/main/src/themes/base/SliderBase-parameters.css
- packages/main/src/themes/sap_belize/SliderBase-parameters.css
- packages/main/src/themes/sap_belize_hcb/SliderBase-parameters.css
- packages/main/src/themes/sap_belize_hcw/SliderBase-parameters.css
- packages/main/src/themes/sap_fiori_3/SliderBase-parameters.css
- packages/main/src/themes/sap_fiori_3_dark/SliderBase-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/SliderBase-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/SliderBase-parameters.css
- packages/main/src/themes/sap_horizon_hcb/SliderBase-parameters.css
- packages/main/src/themes/sap_horizon_hcw/SliderBase-parameters.css
Previously, hover styles were always applied on both handles no matter that a handle is hovered or the progress bar.
According to the specification, when the progress bar is no hover, both handle should have hover styles applied and when just the handle is on hover, the other one should not receive hover visualization as well.
FIXES: #7100
> fix(ui5-range-slider): adjust hover state visualization

- packages/base/src/Boot.ts
- packages/base/src/FontFace.ts
- packages/base/src/InitialConfiguration.ts
- packages/base/src/features/OpenUI5Support.ts
- packages/base/src/util/PopupUtils.ts
- packages/main/test/pages/Kitchen.openui5.html
The `OpenUI5Support.ts` module must be able to work with any version of OpenUI5/SAPUI5. The latest OpenUI5 version `1.116` introduces some breaking changes (f.e. `getThemeRoot` no longer available via the central configuration class).
Additionally, the version must be resolved synchronously, therefore I reverted to the old version parsing (and removed the usage of the official version util)
WIP
Background: `OpenUI5Support.init()` is expected to be called by the framework as early as possible. Therefore, it must preload all OpenUI5 modules that might be used anywhere else in the code. 
I'm looking for feedback especially on: 
- `isLoaded` (later renamed to `OpenUI5Detected`): is this the right check to tell if OpenUI5 is on the window or not
- `isModularCore` (later renamed to …
> chore: support modular core

- packages/base/src/features/OpenUI5Support.ts
- packages/base/src/theming/applyTheme.ts
**Background**
There are use-cases with multiple versions of the framework with some of them with OpenUI5Support enabled and others not. One of the consequences is that the z-indexes of popovers/dialogs on the page are not synchronised as the next z-index is calculated differently when OpenUI5Support is enabled and when isn't.
**Solution**
**To always enable the OpenUI5Support feature.** 
However, we had to ensure it's completely safe and won't have a side effect when the feature is imported, but OpenUI5 is not loaded on the page. And, this is what the PR addresses by refactoring a single usage in `applyTheme` and using `OpenUI5Support.isOpenUI5Detected` to check if OpenUI5 is available in the runtime.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7175
> fix(framework): fix OpenUI5Support feature usage

- docs/1-getting-started/06-using-features.md
- docs/2-advanced/04-OpenUI5-integration.md
- packages/base/src/features/OpenUI5Support.ts
- packages/base/src/util/PopupUtils.ts
- packages/main/test/pages/OpenUI5.html
In some cases the OpenUI5Support feature is enabled but `sap.ui.require("sap/ui/core/Popup")` returns `undefined` leading to exceptions when trying to read `Popup.getNextZIndex()`. 
The root cause was the import order of the modules. The OpenUI5Support feature module was included after the component's import and the features was not enabled on framework boot and not initialised properly. As a result the Popup hasn't been loaded and later when getNextZIndex is called, requiring the Popup from OpenUI5 fails and returns undefined.
Although we can add a check and prevent the exception, actually it's better to leave it fails, but add a message why the exception is thrown and how to correctly one should use the OpenUI5Support feature.
In addition, the documentation has been improved to explain …
> docs(framework): improve OpenUI5Support feature usage documentation

- packages/playground/package.json
- yarn.lock
The latest version of storybook fixes an issue of not displaying decorators inside the source of the stories in the docs page.
> chore: update storybook version

- packages/fiori/src/themes/ViewSettingsDialog.css
**Issue**
In the release testing we caught an issue - the buttons in the footer were not vertically centered
1. Go to https://sap.github.io/ui5-webcomponents/nightly/playground/?path=/docs/fiori-viewsettingsdialog--docs
2. Observe the footer
**Solution**
After setting `aling-items: center` they look better:
**Additional refactoring**
In addition, `padding-*`, `margin-* ` have been replaced with equivalent CSS logical properties for out of the box RTL support.
> fix(ui5-view-settings-dialog): fix footer buttons position

- packages/fiori/src/ViewSettingsDialog.ts
The previous JSDoc description for the **`setConfirmedSettings`** method lacked proper line breaks, leading to a text overflow on the 'Docs' page of Storybook. This resulted in an unintended horizontal overflow throughout the page.
With this update, we've reformatted the JSDoc to prevent such issues, ensuring a better reading experience on the Storybook 'Docs' page.
> docs(ui5-view-settings-dialog): fix docs page horizontally overflowing in storybook

- packages/main/src/SegmentedButton.ts
- packages/main/src/themes/SegmentedButton.css
- packages/main/test/pages/SegmentedButton.html
With this PR we enhance the UI5 `SegmentedButton` component to provide support for setting up custom widths. With this enhancement, you can now specify the width of the SegmentedButton using inline styles or CSS classes, ensuring that the component remains responsive in various scenarios.
Fixes: #6897
> fix(ui5-segmented-button): support custom width configuration

- packages/main/src/FileUploader.ts
Added note for the slot content saying that, the component would not be interactable via keyboard if slot item is not provided.
Related to the dissusions about: #5893
> docs(ui5-file-uploader): add note for default slot behavior

- packages/main/src/AvatarGroup.ts
- packages/main/src/themes/base/sizes-parameters.css
**Issue:**
The CSS variable `--_ui5_tc_header_height_compact` is missing and TC's hight in compact is wrong.  The selection line is not visible at all.
**Solution**
Use `--_ui5_tc_item_height` instead.
Previously
Now
> fix(ui5-tabcontainer): fix height in compact

- packages/create-package/template/test/pages/index.html
- packages/playground/docs/landing-page.html
links to the documentation are outdated as we now we moved. to Storybook and the URLs are different.
> fix(framework): fix links in starting page of new pkg

- README.md
Link to playground is now correct.
> fix(playground): playground link fixed

- packages/main/src/themes/ListItem.css
Additional text was width restricted and couldn't display its whole data, even if there was enough space for it.
After its removal the additional text is still Fiori compatible when it collides with the default text (it hyphens).
Fixes: #6937
> fix(ui5-li): remove additional text width restriction

- .gitignore
- packages/playground/package.json
Some npm build scripts require certain resources from the `dist` folders of the packages, but are only needed for the build of the storybook and not for local serving.
> build(playground): optimize dev run scripts

- packages/playground/_stories/main/TabContainer/TabContainer.stories.ts
"Inline" tab layout is now the recommended layout.
> docs(ui5-tabcontainer): remove sample of items with additional text

- packages/base/src/i18nBundle.ts
The `I18Bundle#getText` method works with both objects and strings, 
however the type is set to **I18nText** ( { key: string, defaultText: string } ) and causes TS errors when the method is called with a string as described in the referenced issue.
```ts
const msg = i18nBundle.getText("TEST");
```
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7300
> chore: refactor I18Bundle#getText params types

- packages/tools/package.json
- yarn.lock
In some cases zx library is not able to find files on a machine with Windows operation system due to incorrect file path (or it might be due to terminal being used). In version 7.0.4 (https://github.com/google/zx/releases/tag/7.0.4) there is fix that sets the default terminal that should be used.
With this PR updating to latest version 7.2.3.
> chore: bump zx version

- packages/main/src/TimeSelectionClocks.ts
The internal `TimeSelectionClocks.ts`  class has the following dependencies: `TimePickerClock`, `ToggleSpinButton` and **SegmentedButton**, and all these tags are properly scoped.
Although the SegmentedButton has dependency to SegmentedButtonItem, the `ui5-segmented-button-item` tag is used inside the TimeSelectionClocks's ShadowDom (not in the SegmentedButton's ShadowDom), and has to be explicitly added to the TimeSelectionClocks dependencies to be scoped as well.
```html
<-- TimeSelectionClocks.hbs !-->
<ui5-segmented-button
<ui5-segmented-button-item></ui5-segmented-button-item>
</ui5-segmented-button>
```
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7343
> fix(ui5-time-picker): add explicit dep to SegmentedBtnItem

- packages/main/src/Switch.ts
With this change, we remove outdated statement in the `ui5-switch` documentation.
Fixes: #7093
> docs(ui5-switch): remove outdated statement in the JSDocs

- packages/fiori/src/Page.ts
This PR adds the shadow parts description for `content` to the `Page` component.
> docs(ui5-page): document available shadow parts

- packages/main/src/CheckBox.ts
- packages/main/test/pages/CheckBox.html
- packages/main/test/specs/CheckBox.spec.js
The issue seems to happen because the internal `formSupport` slot has `disabled` attribute. When inputs are disabled, the client does not send their values, resulting in the browser skipping validation.
Fixes: #7319
> fix(ui5-checkbox): trigger form validation when required

- packages/main/src/themes/CheckBox.css
The fix ensures that the checkbox works as expected without causing unintended text selection in other elements during user interactions.
Fixes: #7236
> fix(ui5-checkbox): prevent text selection on checkbox

- packages/main/src/TimePicker.ts
- packages/main/test/pages/TimePicker.html
- packages/main/test/specs/TimePicker.spec.js
Currently when the value of the component(s) is set to "now", text "now" is rendered instead of the current time.
With this change, we fix that issue.
Fixes: #7287
> fix(ui5-time-picker): support relative value "now"

- packages/main/src/Switch.ts
- packages/main/src/themes/Switch.css
Currently there was a case where we apply **`left`**, **`right`** CSS properties, which were intended for `ui5-switch` instances, which are using icons in their handles ( f.e basic switch with no text set, switch with **`design="Graphical"`**, and so on). However these styles were applying even for switches, which had `text-on` and `text-off` properties, which caused a slight misalignment.
Please refer:
On the image above, we could see the little misalignment in the text. It was occuring for both On/Off cases.
Now the content in the `ui5-switch` handles, are properly aligned.
Fixes: #7094
> fix(ui5-switch): align text/icon properly in switch handle

- packages/main/src/Switch.hbs
- packages/main/src/Switch.ts
- packages/main/src/i18n/messagebundle.properties
- packages/main/test/pages/Switch.html
- packages/main/test/pages/styles/Switch.css
- packages/main/test/specs/Switch.spec.js
- packages/playground/_stories/main/Switch/Switch.stories.ts
Introducing the `required` property for the Switch control.
We now also enable the **Form Support** feature within the control, which means now the Switch component, could be easily used and integrated within forms as well.
Fixes: #5897
> feat(ui5-switch): add required property

- packages/main/src/Menu.ts
- packages/main/test/specs/Menu.spec.js
Previously, the sub-menus would **open** and **close** in an instant when **hovering over** or **hovering out** of a menu item. This sometimes caused unintentional closing of sub-menus, resulting in a poor user experience.
To address this, we made the following changes:
- We added a `300ms` delay when opening a sub-menu upon hovering over it.
- Added `400ms` delay when closing a sub-menu upon hovering out.
Fixes: #7078
> feat(ui5-menu): add delay between opening and closing submenu and sub menu items

- packages/fiori/src/themes/ShellBar.css
- packages/fiori/src/themes/base/ShellBar-parameters.css
- packages/fiori/src/themes/sap_belize_hcb/ShellBar-parameters.css
- packages/fiori/src/themes/sap_belize_hcb/parameters-bundle.css
- packages/fiori/src/themes/sap_belize_hcw/ShellBar-parameters.css
- packages/fiori/src/themes/sap_belize_hcw/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3_hcb/ShellBar-parameters.css
- packages/fiori/src/themes/sap_fiori_3_hcb/parameters-bundle.css
- packages/fiori/src/themes/sap_fiori_3_hcw/ShellBar-parameters.css
- packages/fiori/src/themes/sap_fiori_3_hcw/parameters-bundle.css
- packages/fiori/src/themes/sap_horizon/ShellBar-parameters.css
- packages/fiori/src/themes/sap_horizon_dark/ShellBar-parameters.css
- packages/fiori/src/themes/sap_horizon_hcb/ShellBar-parameters.css
- packages/fiori/src/themes/sap_horizon_hcw/ShellBar-parameters.css
- packages/fiori/src/themes/sap_horizon_hcw/parameters-bundle.css
This commit addresses an issue identified after the recent update related to runtime-based CSS variables for components.
It adjusts the focus outline of the ShellBar buttons across all themes.
Fixes #7220
> fix(ui5-shellbar): button focus outline adjustment

- packages/fiori/src/themes/SideNavigation.css
> fix(ui5-side-navigation): allow overstyling of border-radius

- packages/playground/_stories/fiori/IllustratedMessage/IllustratedMessage.stories.ts
Property size is now correctly passed to the illustrated message.
> docs(ui5-illustrated-message): respect changes of property size in story

- packages/main/src/themes/SplitButton.css
Currently in the High Contrast themes, the arrow split button didnt had the active state styling, which is wrong.
Now we apply the correct styling over the active state of the arrow button.
Fixes: #7395
> fix(ui5-split-button): add css variables for active state

- packages/main/src/Option.ts
- packages/main/src/SelectPopover.hbs
The PR addresses two issues found accidentally when playing around with the component:
**before** - two headers are rendered 
**now** - only one header is displayed, the slot attributes was missing from the div, that meant to be a header
**before**: The dropdown used to not reflect changes of the Option's text content. For example, if the content of Option is "Hello" and we change it dynamically to "World" - the change is not reflected in the dropdown immediately, but only after some interaction (that triggers re-rendering)
**now**: It does, because the Option invalidates itself upon text content changes, and this triggers Select's invalidation and the change is immediately reflected in the UI.
> fix(ui5-select): fix header on phone & update items on options change

- packages/base/src/CustomElementsScope.ts
- packages/base/src/CustomElementsScopeUtils.ts
- packages/base/src/ManagedStyles.ts
- packages/base/src/StaticAreaItem.ts
- packages/base/src/UI5Element.ts
- packages/main/src/ColorPicker.ts
- packages/main/src/ComboBox.ts
- packages/main/src/Input.ts
- packages/main/src/MultiInput.ts
- packages/main/src/SegmentedButton.ts
- packages/main/src/Select.ts
- packages/main/src/WheelSlider.ts
- packages/main/src/themes/TextArea.css
- packages/main/src/themes/base/TextArea-parameters.css
- packages/main/src/themes/sap_belize/TextArea-parameters.css
- packages/main/src/themes/sap_belize_hcb/TextArea-parameters.css
- packages/main/src/themes/sap_belize_hcw/TextArea-parameters.css
- packages/main/test/pages/Button.html
- packages/tools/components-package/postcss.components.js
- packages/tools/components-package/postcss.themes.js
- packages/tools/lib/postcss-css-to-esm/index.js
- packages/tools/lib/postcss-css-to-json/index.js
- packages/tools/lib/postcss-scope-vars/index.js
- packages/tools/package.json
- yarn.lock
a css variable declaration in the <component_name>-parameters.css
```
:root {
--_ui5_link_text_decoration: none;
```
as well as the usage in <component_name>.css
```
text-decoration: var(--_ui5_link_text_decoration);
```
get both renamed at build time using the following convention:
```
before:
--_ui5_link_text_decoration
after:
--_ui5-v1-16-0_link_text_decoration
```
since both definition and usage get a unique name, multiple runtimes can run on the page and get their own copy of the same variable name with the correct value.
Only variables starting with `--ui5` or `--_ui5` are renamed with the scoping prefix
One copy of all css variables per running webcomponents runtime gets inserted in the document. Compared with the current scoping approach where one set of variables is inserted in …
> feat(framework): scope css variables per runtime and version

- packages/playground/_stories/main/RangeSlider/RangeSlider.stories.ts
- packages/playground/_stories/main/Slider/Slider.stories.ts
> fix(ui5-slider): enhance storybook samples

- packages/base/package.json
- packages/base/src/theming/applyTheme.ts
- packages/fiori/package.json
- packages/localization/package.json
- packages/main/package.json
- yarn.lock
OpenUI5Support should have been imported as a type, not importing the feature itself. Importing the feature is done by the consumers, when they need better OpenUI5 integration.
> fix(framework): fix OpenUI5Support usage in applyTheme

- packages/main/src/CustomListItem.ts
- packages/main/src/ListItem.hbs
- packages/main/src/StandardListItem.ts
Additionally, `edit-button` was renamed to `detail-button` to be semantically correct.
> chore: document the newly added list item shadow parts

- packages/fiori/src/ShellBarItem.ts
This PR adds a note to the `text` property of the ShellbarItem description, explaining that the text will only be visible when the item is inside the overflow popover. It also removes the `@native` JSDoc annotation from the `click` event as the event is a `CustomEvent`
> docs(ui5-shellbar-item): adjust `text` description & remove `native` annotation from `click` event

- packages/main/src/Toolbar.ts
- packages/main/src/ToolbarButton.ts
- packages/main/src/ToolbarItem.ts
- packages/main/src/ToolbarSelect.ts
- packages/playground/_stories/main/Toolbar/Toolbar.stories.ts
Since the Toolbar PR has been merged the "nightly" storybook stopped deploying due to errors when building the story of the Toolbar, see https://github.com/SAP/ui5-webcomponents/actions/runs/5974432275/job/16208568004#step:4:3210 tracked down to wrong jsdoc.
- fixed wrong namespaces, make use of appendocs
- fixed some TS construction has been fixed
In ToolbarItem.js
```js
export type { ToolbarItem };
export default ToolbarItem;
```
changed to
```js
export default ToolbarItem;
```
In Toolbar.js
```js
import type { ToolbarItem } from "./ToolbarItem.js"; 
```
changed to
```js
import type ToolbarItem from "./ToolbarItem.js";
```
- showcase ui5-toolbar-select and ui5-toolbar-select-option in the storybook
> chore: fix storybook build, Toolbar story and some Toolbar TS constructions

- packages/main/src/ToolbarButton.ts
- packages/main/src/ToolbarItem.ts
- packages/main/src/ToolbarPopover.hbs
- packages/main/src/ToolbarSelect.hbs
- packages/main/src/ToolbarSelect.ts
- packages/main/src/ToolbarSpacer.ts
- packages/main/src/themes/ToolbarPopover.css
- packages/main/src/themes/base/sizes-parameters.css
**Changes:**
- hide overflow popup `arrow`
- fix `padding` in the overflow
- add `@abstract` to all Toolbar* components
- ToolbarItem becomes a pure class, not a customElement
- ToolbarSelect now supports `width` attribute (the property was present, but the value was not propagated in the template to the ui5-select)
- The `width` property has all the JSDoc required in all components that have it ToolbarSelect, ToolbarButton and ToolbarSpacer 
- The "width" property is now public  in ToolbarSelect as well (it was public in ToolbarButton and ToolbarSpacer )
**Open for discussion:**
- The "width" property  is of type string, previously we used to have CSSSize
Example:
```js
/**
* Defines the width of the select.
* <br><br>
*
* <b>Note:</b> all CSS sizes are supported - 'percentage', 'px', …
```
> chore: update Toolbar

- vite.config.js
Mac users who have upgraded to `Ventura 13.5` have reported the browser refreshing constantly even though no files were changed.
While a solution is found, we can disable the Hot Module Reload feature for `vitejs`.
> chore: disable vitejs hot module reload

- packages/base/src/delegate/ItemNavigation.ts
We must not use `querySelector("#${someId}")` for IDs that can be supplied by app developers, because if these IDs have `.` or `:`, it becomes f.e. `querySelector("#something.somethingElse")`. Instead, we can use the attribute selector form.
Note: all selectors based on `this._id` are safe, because it's generated by the framework and known to be safe.
> chore: use a safe querySelector for ID

- packages/main/src/Toolbar.ts
- packages/main/src/ToolbarItem.ts
- packages/main/src/ToolbarPopoverSeparator.hbs
- packages/main/src/ToolbarSeparator.ts
- packages/main/src/themes/ToolbarPopover.css
- packages/main/test/pages/Toolbar.html
- packages/main/test/specs/Popover.spec.js
Show the separator in Toolbar's overflow only if it would appear between items.
**Start - all items + separator are visible**
<br>
**Only one item overflowed** - the separator is now moved out from the bar as last item, but not shown in the overflow because it would appear as first in the overflow (not separating anything)
<br>
**Next item overflows** - now the separator is visible between the two items
> chore(ui5-toolbar): show separator in overflow

- packages/base/src/Device.ts
There is an accessibility request to be able to separate the control button on Mac and the same on Windows systems. 
Therefore a detection for the Mac system is added.
> chore: add detection for Mac device

- packages/fiori/src/themes/ShellBar.css
- packages/main/src/themes/base/rtl-parameters.css
The notification counter badge is being trimmed when it is contained in the last element in the ShellBar.
Also adjusted the RTL support.
This change is continuation of #7208.
Fixes: #7456
> fix(ui5-shellbar): align notification counter

- packages/tools/package.json
- yarn.lock
`vitejs` version 3 does not work on Windows any more
> chore: upgrade to vitejs 4.4.9

- packages/tools/lib/dev-server/custom-hot-update-plugin.js
- vite.config.js
A change is observed on MacOS since 13.5, where the build generates a large amount of JSON file that spotlight search has to index, as they are considered new files.
Starting the vitejs dev server reads all of these files and this triggers the indexing. The indexing has a side effect of changing some file metadata (can be checked with `mdls <path_to_file>`). This metadata change is changing the ctime of the file, but not the mtime. This can be checked with `stat -x <path_to_file>`
Essentially only metadata is changed, not content. This should not cause a page refresh, but chokidar reports this change and vite refreshes the page. The indexing is running with a 10 second interval, so for roughtly 20 minutes vite is refreshing the page every 10 seconds
This plugin checks if the file causing …
> build: fix dev server page refresh

- packages/main/src/Toolbar.ts
In the `Toolbar` of UI5WCR it was possible to pass any component as child. Since the ui5wc `Toolbar` doesn't support that feature it's confusing for users when they are migrating. (e.g. [here](https://github.com/SAP/ui5-webcomponents-react/issues/5060)) This PR adds a description of the allowed components inside the default slot to make it more clear which components can be passed there.
> docs(ui5-toolbar): add note about allowed components in default slot

- packages/theming/package.json
- yarn.lock
This update includes the updated theme parameters.
See https://github.com/SAP/theming-base-content/releases/tag/11.6.8
> chore: bump theming-base-content version to 11.6.8

- packages/main/src/themes/Switch.css
- packages/main/src/themes/base/Switch-parameters.css
- packages/main/src/themes/sap_horizon/Switch-parameters.css
- packages/main/src/themes/sap_horizon_dark/Switch-parameters.css
- packages/main/src/themes/sap_horizon_hcb/Switch-parameters.css
- packages/main/src/themes/sap_horizon_hcw/Switch-parameters.css
The visual design for the Switch was broken in Fiori (Quartz) and Belize themes in the following change [link](https://github.com/SAP/ui5-webcomponents/pull/7350).
The issue appeared only after merging to the main branch for some reason.
Please refer:
In order to fix the visual design in all themes, we had to introduce an alternate CSS variable. This was added because in Horizon themes for example, for the Text and Graphical Switch, the variable `--_ui5_switch_text_inactive_left` needs to have a different value for each of the styles in order to be properly aligned.
After the fix:
> fix(ui5-switch): fix text alignment in all themes

- packages/fiori/src/Bar.ts
- packages/main/src/Button.ts
- packages/main/src/DatePicker.ts
- packages/main/src/FileUploader.ts
- packages/main/src/SplitButton.ts
- packages/main/src/StepInput.ts
- packages/playground/_stories/fiori/Bar/Bar.stories.ts
- packages/playground/_stories/fiori/DynamicSideContent/DynamicSideContent.stories.ts
- packages/playground/_stories/main/Button/Button.stories.ts
- packages/playground/_stories/main/Calendar/Calendar.stories.ts
- packages/playground/_stories/main/DatePicker/DatePicker.stories.ts
- packages/playground/_stories/main/DateRangePicker/DateRangePicker.stories.ts
- packages/playground/_stories/main/DateTimePicker/DateTimePicker.stories.ts
- packages/playground/_stories/main/FileUploader/FileUploader.stories.ts
- packages/playground/_stories/main/Menu/Menu.stories.ts
- packages/playground/_stories/main/SplitButton/SplitButton.stories.ts
- packages/playground/_stories/main/StepInput/StepInput.stories.ts
- packages/playground/_stories/main/Switch/Switch.stories.ts
- packages/playground/_stories/main/ToggleButton/ToggleButton.stories.ts
As a part of the #7284 initiative we enhanced the Storybook samples for the following components:
- Cleared the JSDoc enums;
- Changed the story name to -> **_Basic_**
- Cleared JSDoc enums;
- Remove redunant Storybook samples;
- Cleared JSDoc enums;
- Added custom styling to the native HTML tags as changing the themes wasn't updating the content. For example on Dark themes like Evening Horizon, both the background and the text would appear dark, which led to poor user experience;
- Cleared JSDoc enums
- Moved the Custom FileUploader sample to lower position, because we **do not** encourage using non-focusable elements;
- Fixed wrong property name `headerText` -> `header-text` because it wasnt showing on Mobile Devices;
- Changed sample name -> **_Basic with Header Text_** -> **_Basic_** …
> docs: enhance storybook samples

- packages/main/src/themes/SplitButton.css
- packages/main/src/themes/base/SplitButton-parameters.css
- packages/main/src/themes/base/rtl-parameters.css
- packages/main/src/themes/sap_belize_hcb/SplitButton-parameters.css
- packages/main/src/themes/sap_belize_hcw/SplitButton-parameters.css
- packages/main/src/themes/sap_fiori_3_hcb/SplitButton-parameters.css
- packages/main/src/themes/sap_fiori_3_hcw/SplitButton-parameters.css
- packages/main/src/themes/sap_horizon/SplitButton-parameters.css
- packages/main/src/themes/sap_horizon_dark/SplitButton-parameters.css
- packages/main/src/themes/sap_horizon_dark_exp/SplitButton-parameters.css
- packages/main/src/themes/sap_horizon_exp/SplitButton-parameters.css
- packages/main/src/themes/sap_horizon_hcb/SplitButton-parameters.css
- packages/main/src/themes/sap_horizon_hcb_exp/SplitButton-parameters.css
- packages/main/src/themes/sap_horizon_hcw/SplitButton-parameters.css
- packages/main/src/themes/sap_horizon_hcw_exp/SplitButton-parameters.css
Rework on the Split Button visual design in order to be complient with VD Spec in all themes and rtl direction as well.
> feat(ui5-split-button): adapt visual design with new parameters

- packages/main/src/Input.ts
- packages/main/src/InputPopover.hbs
- packages/main/src/features/InputSuggestions.ts
- packages/main/test/specs/Input.spec.js
- Inactive and Group items should announced
- Group items should be excluded from the total count and position of items, when announced on navigation
- Group items should be excluded from the result announcement, when an user filters the list of suggestions
FIXES: #7552
> fix(ui5-input): improve item announcement

- packages/main/src/SelectMenuOption.ts
- packages/main/src/ToolbarButton.ts
- packages/main/src/ToolbarSelect.ts
- packages/main/src/ToolbarSeparator.ts
- packages/main/src/ToolbarSpacer.ts
- packages/theming/css-vars-usage.json
These are fixes, needed for the UI5 Web Components enablement to run correctly:
- all components that go in `ui5-toolbar` must implement its interface
- `ui5-toolbar-separator` is not abstract
> chore: fix JSDoc

- packages/main/src/MultiComboBox.ts
With current solution of CSS scoping a prefix with current version information is added to every css variables starting with --ui5 / --_ui5. To manipulate this kind of variables the `getScopedVarName` function should be used in order to set the correct prefix of the variable.
> fix(ui5-multi-combobox): correct usage of css var

- packages/main/src/themes/MessageStrip.css
- Close button's width is overriden to 2rem both in cosy and compact density, which is not correct.
> fix(ui5-message-strip): remove button's custom width

- packages/main/src/ToolbarSeparator.ts
I think all slots of the `ui5-toolbar` should be abstract? Maybe this was removed by accident?
> docs(ui5-toolbar-separator): mark component as abstract

- packages/playground/assets/js/landing-page.js
- packages/playground/docs/landing-page.html
The version of the landing page was often outdated. With this PR the latest version is now fetched from the npm registry and only if for some reason the registry is not available, the static version is displayed. I also set the static text and `href` to v1.18 already.
> docs(landing-page): dynamically fetch latest ui5wc version

- packages/base/src/UI5Element.ts
Previously camelCase events were not able to be stopped from bubbling.
As part of: #7637
> fix(framework): stop bubbling of camel case events

- packages/main/src/ColorPalette.ts
- packages/main/src/ColorPaletteItem.hbs
- packages/main/src/ColorPaletteItem.ts
- packages/main/src/themes/ColorPaletteItem.css
- packages/main/src/themes/base/ColorPalette-parameters.css
- packages/main/src/themes/sap_horizon/ColorPalette-parameters.css
- packages/main/src/themes/sap_horizon_dark/ColorPalette-parameters.css
- packages/main/test/pages/ColorPalette.html
- packages/main/test/specs/ColorPalette.spec.js
We are introducing a **selected** property to the `ui5-color-palette-item`. 
This enhancement allows users to explicitly set a **selected state** to **any** `ui5-color-palette-item`.
For example, previously the first item was always on focus when opening the `ui5-color-palette-popover`.
Additionally, when one item is selected, any previously selected item will be deselected, ensuring that only one item can be selected within a `ui5-color-palette` at any given time.
The **`selected`** state could be set either by:
-  Setting it explicitly by using the `selected` property;
- By right-clicking on a `<ui5-color-palette-item>` with the mouse;
- By pressing `Enter` or `Space` upon focused `<ui5-color-palette-item>`;
> feat(ui5-color-palette-item): add selected state

- packages/fiori/src/IllustratedMessage.ts
- packages/fiori/src/themes/IllustratedMessage.css
- packages/fiori/test/pages/IllustratedMessage.html
- packages/fiori/test/specs/IllustratedMessage.spec.js
The component now has 100% height to allow it fit the parent container, if that container is sized (i.e. if the parent container is given a restricted size). If the parent container is not sized, then the size of the component will be the total size of its children as before.
Fixes: #6492
> feat(ui5-illustrated-message): enable vertical responsiveness

- packages/localization/src/sap/ui/core/Configuration.ts
Implemented the function to use the default value in order to calculate calendar week numbering by active format locale.
Fixes: #7670
> fix(localization): missing calendarWeekNumbering

- packages/tools/lib/postcss-scope-vars/index.js
In certain scenarios the NPM version of a package may contain special characters.
The valid characters for a CSS variable name are:
- alphanumeric characters
- `-`
- `_`
This change replaces each character that is not valid for a CSS variable name with a dash.
> fix: escape special characters when scoping CSS vars

- packages/main/src/themes/StepInput.css
This PR adjusts z-index values of increase/decrease buttons and focus in order to keep lower possible z-index of the component in case when there is sticky element on page.
Fixes: #7697
> fix(ui5-step-input): fix z-index of increase/decrease buttons and focus

- .github/workflows/deploy-latest-docs.yaml
- .github/workflows/deploy.yaml
- .github/workflows/deploy_latest.yaml
- .github/workflows/release-auto-weekly.yaml
- .github/workflows/release-custom-tag.yaml
- .github/workflows/release-snapshot.yaml
- .github/workflows/release.yaml
- .github/workflows/test-issue-comments.yaml
- .github/workflows/test-storybook.yaml
- .github/workflows/test.yaml
- packages/base/package.json
- packages/fiori/package.json
- packages/localization/package.json
- packages/main/package.json
- packages/tools/components-package/wdio.js
- yarn.lock
Chromedriver 117 needs Node.js version 18, but when we upgrade to Node.js 18, a connection error occurs, and @wdio/devtools-services cannot be loaded correctly. Mobile tests are failing because Node.js version 17 has changed the default value of dns.setDefaultResultOrder(order) to which 3rd party plugin of @wdio/cli depends. We can find a solution to the connection issue in this GitHub issue: https://github.com/webdriverio/webdriverio/issues/8279.
The issue is fixed in WebdriverIO version 8, but fixing it may require some bigger code changes.
> chore: upgrade to chromedriver 117

- packages/main/src/themes/TreeItem.css
> fix(ui5-tree-item-custom): text wrapper allows proper alignment of flex content

- packages/main/src/ComboBox.ts
- packages/main/test/specs/ComboBox.spec.js
- Group items are excluded from the total count and position of items, when announced on navigation
FIXES: #6736
> fix(ui5-combobox): exclude group from suggestions count

- packages/main/src/Input.hbs
- packages/main/src/Input.ts
- packages/main/src/i18n/messagebundle.properties
- Update clear icon accessible name to "Clear"
- Icon role remain 'img' until we think of a way to manipulate icon inner acc
FIXES: #7600
> fix(ui5-input): update clear icon accessible name

- packages/main/src/themes/TabContainer.css
- packages/main/test/specs/TabContainer.spec.js
> fix(ui5-tabcontainer): add margins for the Overflow buttons (start and end)

- packages/main/src/Popup.ts
Problem: If there in no focused element when the Popup opens there is "Empty string passed to getElementById()." warning in Firefox.
Fixes: #7711
> fix(ui5-popup): add check for initial focused element id

- packages/base/src/UI5Element.ts
Register custom elements explicitly to `window.customElements`.
> fix(framework): use correct customElements registry

- docs/1-getting-started/07-typescript-support.md
We now remove the "experimental" notion for our TypeScript support from the documentation.
> docs: update TypeScript Support statement

- packages/main/src/ComboBox.ts
- packages/main/test/pages/ComboBox.html
- packages/main/test/specs/ComboBox.spec.js
- When the dropdown is open and the visual focus is over the value state header, it should be announced.
FIXES: #7602
> fix(ui5-combobox): announce value state header on focus

- packages/main/src/Calendar.ts
- packages/main/test/pages/Calendar.html
- packages/main/test/specs/Calendar.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/7693
We are now considering the ui5-date, set trough nested element, for the focus. Previously we only focused the date passes as timestamp, and that timestamp changed based on current day, navigation and etc. We now check if we have a value set to the control and our initial focus goes to it, if the value is set after init state, we set the focus to the newly set date.
> fix(ui5-calendar): focus date set in slot

- packages/main/src/CheckBox.ts
- packages/main/src/FileUploader.ts
- packages/main/src/Select.ts
- packages/main/src/Switch.ts
- packages/main/src/TextArea.ts
- packages/main/src/features/InputElementsFormSupport.ts
- packages/main/test/pages/FormSupport.html
- packages/main/test/specs/FormSupport.spec.js
Previously we used to always render an input native element in the light DOM of our input-type web components for the purposes of the FormSupport. This includes the TextArea web component. However, when linebreaks are used in the TextArea web components, they got lost (native input supports one-line text) and eventually not part of the form submission. Now we use native textarea element and the line breaks are properly submitted.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7467
> fix(FormSupport): submit linebreaks in ui5-textarea

- packages/playground/.storybook/addons/html/HTMLTransformation.ts
- packages/playground/.storybook/addons/html/processors/StylesProcessor.ts
- packages/playground/.storybook/addons/html/processors/index.ts
Related: #7284 
Problem: If the story decorator includes CSS styles, the style elements were not visualized by the HTML addon. The style elements were not visualized because they were skipped in the html transformation. 
Solution: Included style nodes in the html transformation and isolated the style-related processing into a dedicated processor for style nodes.
> docs(playground): html addon now shows decorated styles

- packages/main/src/ColorPalette.ts
- packages/main/src/ColorPaletteItem.hbs
- packages/main/src/ColorPaletteItem.ts
- packages/main/src/themes/ColorPaletteItem.css
- packages/main/src/themes/base/ColorPalette-parameters.css
- packages/main/src/themes/sap_horizon/ColorPalette-parameters.css
- packages/main/src/themes/sap_horizon_dark/ColorPalette-parameters.css
- packages/main/test/pages/ColorPalette.html
- packages/main/test/specs/ColorPalette.spec.js
Due to lack of clear guidelines around the interaction, we currently decided to not move forward with the `selected` state feature in our ColorPalette's components, and revert the current implementation, until a finalized guidelines are provided in order avoid unwanted and inconsistent interaction behaviour.
Revert of: #7598 
Closes: #7731
> revert(ui5-color-palette-item): revert selected state feature

- packages/base/src/UI5Element.ts
- packages/base/src/delegate/ItemNavigation.ts
The bug: if you try to use `ItemNavigation` twice in the same component, the second is going to overwrite `_onComponentStateFinalized` and the `_init` method of the first Item Navigation will never be called.
This was fixed in: https://github.com/SAP/ui5-webcomponents/pull/7682
This change reworks the fix a bit to make `UI5Element` agnostic of `ItemNavigation`.
> fix(ItemNavigation): more than 1 ItemNavigation per component allowed

- docs/6-contributing/02-conventions-and-guidelines.md
Added text to specify when a commit changes only a sample, that is should be prefixed with 'docs'.
This is already the case in practice: https://github.com/search?q=repo%3ASAP%2Fui5-webcomponents+%22docs%3A%22&type=commits
> chore: Update commit conventions to include commits with samples

- packages/localization/lib/generate-json-imports/cldr.js
- packages/tools/lib/generate-json-imports/i18n.js
- packages/tools/lib/generate-json-imports/themes.js
This change will not affect any logic, but will make it so that build systems, such as Webpack, that use the `webpackChunkName` magic comment as a directive to assign a runtime bundle name, will now have more readable names for generated resources that are loaded via dynamic import (e.g. localized strings, localization data, themes).
For example, here is the network trace from SAC built with webpack:
&nbsp;
And here are a sample of the bundles (from each package) as they appear on disk in my build:
Fixes #7716
> fix: declare webpackChunkName in generated dynamic imports for readable runtime bundle names

- packages/main/src/List.hbs
- packages/main/src/List.ts
- packages/main/src/ListItemBase.ts
- packages/main/test/pages/List_test_page.html
- packages/main/test/specs/List.spec.js
Fixes: #6086
Resolved an issue where Shift+Tab incorrectly focused on a ListItem's inner element. The solution utilizes a new _effective-tabindex-change event to update the ListItem's tabIndex, ensuring correct ItemNavigation focus after toggling from another component.
> fix(ui5-list): shift+tab navigation in List

- packages/main/src/StepInput.ts
- packages/main/src/TextArea.ts
Adding these tags to the form related "value" property, used by the ui5-webc-ngx wrappers to properly generate the required value accessors so the ui5-webc-ngx wrappers work in Angular reactive forms.
> docs: mark form properties in TextArea, StepInput

- packages/base/src/features/OpenUI5Support.ts
add check for renamed openui5 formatting method
FIXES: #7871
> fix: openui5 support crashes with 1.121-snapshot

- packages/main/src/DayPicker.ts
- packages/main/test/specs/DayPicker.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/7831
> fix(ui5-calendar): render the correct length of day names

- packages/theming/package.json
- yarn.lock
https://github.com/SAP/theming-base-content/releases/tag/11.9.0
> chore: bump theming-base-content version to 11.9.0

- packages/fiori/src/DynamicPageTitle.hbs
- packages/fiori/src/DynamicPageTitle.ts
- packages/fiori/src/themes/DynamicPageTitle.css
- packages/fiori/test/pages/DynamicPage.html
- packages/fiori/test/pages/styles/DynamicPage.css
- packages/main/src/Breadcrumbs.ts
Two changes in the ui5-dynamic-page-title:
--The breadcrumbs now take the horizontal space that remains after positioning the navigation actions
--The content area no longer takes space if no content provided from app-side
> feat(ui5-dynamic-page): add breadcrumbs responsiveness

- packages/fiori/src/DynamicPageTitle.hbs
- packages/fiori/src/DynamicPageTitle.ts
- packages/fiori/test/pages/DynamicPage.html
- packages/main/src/Toolbar.ts
Ensures that the toolbar content with "NeverOverflow" is prioritized when distributing the available horizontal space in the ui5-dynamic-page-title
> feat(ui5-dynamic-page): ensure visibility of content outside overflow

- packages/base/src/ManagedStyles.ts
Font-families are loaded event when the `<style data-ui5-font-face></style>` element exists because `hasStyle` is returning wrong value if adoptedStyleSheets exist.  With current PR the return value is corrected. 
Fixes: #7867
> fix(framework): redundant fonts loading

- SUPPORT.md
- packages/base/README.md
- packages/create-package/README.md
- packages/fiori/README.md
- packages/icons-business-suite/README.md
- packages/icons-tnt/README.md
- packages/icons/README.md
- packages/localization/README.md
- packages/main/README.md
- packages/playground/README.md
- packages/theming/README.md
- packages/tools/README.md
Switch to https://ui5-slack-invite.cfapps.eu10.hana.ondemand.com/ as slack invitation link
> docs: update community slack channel links

- packages/main/src/themes/Table.css
> fix(ui5-table): show busy indicator above sticky column headers

- packages/base/src/css/FontFace.css
- packages/main/test/pages/FontFace.html
Font `72Blackfull` was missing from our font styles and now added. This caused unexpected font issues when `--sapFontBlackFamily` variable is used.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7800
Before - ń is thinner than the rest:
After (patching it in place) - ń is as thick as the rest:
> fix(framework): enable `72Blackfull` font-family

- packages/fiori/src/DynamicPage.hbs
- packages/fiori/src/DynamicPage.ts
- packages/fiori/src/themes/DynamicPage.css
When the footer is not shown, it is still in the DOM and takes space in order to allow the bouncing animation upon show/hide.
Problem: The above, however, causes scroll overflow of the container where the footer is positioned (when the footer is hidden). 
Solution: Place the footer element outside the scroll container and into a container that has "overflow-y: hidden"
Also isolated a simplified demo (html & CSS only):
with issue: https://jsbin.com/webayekoje/edit?html,output
with fix: https://jsbin.com/mavebagome/edit?html,output
> feat(ui5-dynamic-page): footer no longer takes space when hidden

- packages/fiori/src/BarcodeScannerDialog.ts
- packages/fiori/src/FlexibleColumnLayout.ts
- packages/fiori/src/Interfaces.ts
- packages/fiori/src/MediaGallery.ts
- packages/fiori/src/MediaGalleryItem.ts
- packages/fiori/src/ProductSwitch.ts
- packages/fiori/src/ProductSwitchItem.ts
- packages/fiori/src/types/FCLLayout.ts
- packages/fiori/src/types/MediaGalleryItemLayout.ts
- packages/fiori/src/types/MediaGalleryLayout.ts
- packages/fiori/src/types/MediaGalleryMenuHorizontalAlign.ts
- packages/fiori/src/types/MediaGalleryMenuVerticalAlign.ts
- packages/main/src/Avatar.ts
- packages/main/src/AvatarGroup.ts
- packages/main/src/Interfaces.ts
- packages/main/src/types/AvatarColorScheme.ts
- packages/main/src/types/AvatarGroupType.ts
- packages/main/src/types/AvatarShape.ts
- packages/main/src/types/AvatarSize.ts
Related: https://github.com/SAP/ui5-webcomponents/issues/7610
New cem for the following Topic-P components:
ui5-barcode-scanner-dialog, ui5-avatar, ui5-avatar-group, ui5-product-switch, ui5-media-gallery, ui5-flexible-column-layout
> docs: new cem for Topic-P components

- packages/main/src/themes/Badge.css
A lot of css props can be customized on the Badge tag, but the font-size is not one of them. 
With this change we implement the default font-size by SAP Design and enable others to change it easier with css on the tag.
The change is in respond to recent requirements by a stakeholder that has its own Design System (based on SAP Design, but with deviations) to have different sizing of the Badge, including the text font size.
> chore(ui5-badge): enable `font-size` customisation on tag level

- packages/tools/assets-meta.js
Locales have to be described in assets-meta.js so that the respective loaders are created.
- message bundle props files exist, but they consist of the english translation, the translations are to be provided by the translation service
- CLDRs for the locales don't exist (even in the latest openui5/core version) and only commented entries are added
> chore: support mk_MK, cnr_ME & sr_Cyrl_RS
