packages/main/src/Carousel.hbs, packages/main/src/Carousel.js, packages/main/test/pages/Carousel.html, packages/main/test/pages/styles/Carousel.css
The content part is exposed and can be styled.
Fixes #5697
=> feat(ui5-carousel): add new CSS Shadow part

packages/main/src/Input.js, packages/main/src/MultiInput.js, packages/main/test/pages/MultiInput.html, packages/main/test/specs/MultiInput.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/5563
=> fix(ui5-input): allows changing value in selection change event handler

packages/fiori/src/Bar.js, packages/fiori/test/pages/Bar.html
=> fix(ui5-bar): adjust resizing behavior

packages/main/src/themes/Menu.css
=> fix(ui5-menu): prevent closing sub menu when hovering over icon

packages/main/src/AvatarGroup.js, packages/main/src/themes/AvatarGroup.css
=> fix(ui5-avatar-group): width calculations for (non-)Chromium browsers adjusted

packages/main/src/themes/sap_belize_hcb/Button-parameters.css, packages/main/src/themes/sap_belize_hcw/Button-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/Button-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/Button-parameters.css
=> fix(ui5-button): correct text shadow in contrast themes

packages/main/src/themes/DayPicker.css, packages/main/src/themes/base/DayPicker-parameters.css, packages/main/src/themes/sap_belize/DayPicker-parameters.css, packages/main/src/themes/sap_belize_hcb/DayPicker-parameters.css, packages/main/src/themes/sap_belize_hcw/DayPicker-parameters.css
=> fix(ui5-calendar): adjust high contrast belize themes

packages/main/src/DatePicker.js, packages/main/src/TimePickerBase.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/5532
=> fix(ui5-date-picker): focus out now closes the popup

packages/fiori/src/ViewSettingsDialog.js, packages/fiori/test/specs/ViewSettingsDialog.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/5451
=> fix(ui5-view-settings-dialog): focus correct page on open

packages/main/src/TimeSelection.js, packages/main/src/i18n/messagebundle.properties
fixes: https://github.com/SAP/ui5-webcomponents/issues/5181
=> fix(ui5-time-picker): remove ampm translation

packages/main/src/TabContainer.js
=> docs(ui5-tabcontainer): mark allItems as readonly

packages/main/src/Table.js, packages/main/src/i18n/messagebundle.properties, packages/main/test/specs/Table.spec.js
=> fix(ui5-table): count header row as first one

packages/main/src/themes/Table.css, packages/main/src/themes/base/Table-parameters.css, packages/main/src/themes/sap_horizon/Table-parameters.css, packages/main/src/themes/sap_horizon_dark/Table-parameters.css
=> fix(ui5-table): add bottom border in Horizon themes

packages/main/src/themes/Panel.css, packages/main/src/themes/base/Panel-parameters.css, packages/main/src/themes/sap_horizon/Panel-parameters.css, packages/main/src/themes/sap_horizon_dark/Panel-parameters.css
=> fix(ui5-panel): improve focus outline visualization

packages/fiori/src/themes/IllustratedMessage.css
=> fix(ui5-illustrated-message): removed redundant scrollbar in RTL

packages/main/src/themes/TableColumn.css, packages/main/src/themes/TableRow.css
=> fix(ui5-table): apply correct padding in RTL mode

packages/main/test/samples/Table.sample.html
=> fix(ui5-table): adjust samples according to the guidelines

packages/main/src/Input.js, packages/main/test/specs/Input.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/5450
=> fix(ui5-input): enable autocomplete deletion by Meta/Alt + backspace

packages/main/src/MultiComboBox.hbs, packages/main/test/pages/MultiComboBox.html, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): apply focus when invoked explicitly

packages/main/src/Tab.js, packages/main/src/TabContainerPopover.hbs, packages/main/src/TabInOverflow.hbs, packages/main/src/TabInStrip.hbs, packages/main/src/themes/TabInOverflow.css, packages/main/src/themes/TabInStrip.css
=> fix(ui5-tabcontainer): fixed tabs accessibility issues

packages/fiori/src/themes/SideNavigation.css, packages/fiori/test/pages/SideNavigation.html
=> fix(ui5-side-navigation): toggle icon no longer shrinks with long text

packages/main/src/TabContainer.js, packages/main/test/specs/TabContainer.mobile.spec.js
=> fix(ui5-tabcontainer): fix closing overflow on mobile

packages/main/src/features/InputSuggestions.js
=> fix(ui5-input): announce suggestion text once

packages/base/src/Boot.js, packages/base/src/Keys.js, packages/base/src/features/F6Navigation.js, packages/base/src/util/getFastNavigationGroups.js, packages/fiori/test/pages/F6TestPage_2.html
Now, F6 navigation doesn't depend on element's order in light DOM of a custom element.
=> feat(f6navigation): improve fastgroup navigation

packages/main/src/Input.js
=> fix(ui5-input): type composition characters correctly

packages/main/src/Tab.js, packages/main/src/i18n/messagebundle.properties
=> fix(ui5-tabcontainer): translate semantic design aria description

packages/main/src/RadioButton.hbs, packages/main/test/specs/RadioButton.spec.js
=> fix(ui5-radio-button): improve acc

packages/main/src/features/InputElementsFormSupport.js
=> fix(form support): remove additional fields from ACC tree

packages/main/src/TableRow.js, packages/main/test/specs/Table.spec.js
=> fix(ui5-table): announce whether a row is selected or not

docs/2-advanced/01-configuration.md, docs/5-development/02-custom-UI5-Web-Components.md, docs/5-development/06-deep-dive-and-best-practices.md
Link to read formatted: https://github.com/SAP/ui5-webcomponents/blob/deep-dive-docs/docs/5-development/06-deep-dive-and-best-practices.md
=> docs: add a deep dive/best practices article

docs/5-development/01-custom-UI5-Web-Components-Packages.md, docs/5-development/02-custom-UI5-Web-Components.md, docs/5-development/03-understanding-components-metadata.md, docs/5-development/04-understanding-hbs-templates.md, docs/5-development/05-testing-UI5-Web-Components.md
- Document the last 2 metadata settings (`languageAware` and `themeAware`)
- Fix the Handlebars docs
- Fix all links in the Development section
=> docs: some more metadata settings

packages/main/src/TableRow.js, packages/main/test/pages/TableAllPopin.html, packages/main/test/specs/Table.spec.js
FIXES: https://github.com/SAP/ui5-webcomponents/issues/5761
=> fix(ui5-table): enable focus navigation in popin content

packages/main/src/ComboBox.js, packages/main/test/specs/ComboBox.spec.js
=> fix(ui5-combobox): announce additional text of selected item

packages/fiori/package.json, packages/fiori/src/BarcodeScannerDialog.js
Downgrading the version of zXing from 0.18.3 to 0.17.1
=> feat(ui5-barcodescanner): downgraded to lower helper version

packages/main/src/themes/ListItem.css
- now the img and the avatar have the same border radius
Fixes: #5919
=> fix(ui5-li): apply proper border radius to avatar with image

packages/base/package-scripts.js, packages/base/src/types/CSSColor.js, packages/base/src/types/CSSSize.js, packages/base/src/types/CalendarType.js, packages/base/src/types/DataType.js, packages/base/src/types/Float.js, packages/base/src/types/Integer.js, packages/base/src/types/InvisibleMessageMode.js, packages/base/src/types/PopupState.js, packages/base/src/types/ValueState.js, packages/main/src/Input.js
Let's start generating api.json for the base package as well - there are classes, especially data types used within components, for example (valueState, type: ValueState). This way, the API picture will be more complete.
=> build: generate api.json for base package

packages/main/src/MultiInput.js
=> fix(ui5-multi-input): import value help icon

packages/main/src/Table.hbs, packages/main/src/TableRow.hbs, packages/main/src/themes/Table.css, packages/main/src/themes/TableRow.css, packages/main/test/pages/Table.html, packages/main/test/pages/TableAllPopin.html, packages/main/test/specs/Table.spec.js
FIXES: #[5044](https://github.com/SAP/ui5-webcomponents/issues/5044)
=> fix(ui5-table-row): refactor navigated property

packages/theming/package.json, yarn.lock
=> chore: bump theming-base-content to v11.1.42

packages/main/src/themes/ValueStateMessage.css, packages/main/src/themes/base/ValueStateMessage-parameters.css, packages/main/src/themes/sap_horizon/ValueStateMessage-parameters.css, packages/main/src/themes/sap_horizon_dark/ValueStateMessage-parameters.css
=> fix(inputs): apply correct border-radius on value state message popover

packages/fiori/src/i18n/messagebundle.properties
=> fix(ui5-illustrated-message): i18n texts are fixed

packages/main/src/TabContainer.js, packages/main/test/pages/TabContainer.html, packages/main/test/specs/TabContainer.spec.js
=> fix(ui5-tabcontainer): adding selected tab programatically deselects previously selected tab

packages/main/src/features/InputElementsFormSupport.js
=> fix(formSupport): check and report validity of ui5 input components

packages/main/src/RangeSlider.js, packages/main/test/pages/RangeSlider.html, packages/main/test/specs/RangeSlider.spec.js
=> fix(ui5-range-slider): fire change event after value swapping

packages/main/src/themes/Icon.css
=> fix(ui5-icon): cursor "pointer" added for interactive icons

packages/fiori/src/Wizard.hbs, packages/fiori/src/Wizard.js, packages/fiori/src/themes/Wizard.css, packages/fiori/test/specs/Wizard.spec.js
=> feat(ui5-wizard): adopt responsive paddings

packages/base/src/UI5Element.ts
=> chore: fix getSlottedNodes context

packages/base/src/util/ColorConversion.ts
=> chore: correct return type and export for ColorConversion

packages/main/src/Tab.js, packages/main/src/TabInStrip.hbs, packages/main/test/specs/TabContainer.spec.js
=> fix(ui5-tabcontainer): added tab expand button tooltip

packages/base/src/Keys.ts
=> chore: add explicit return type to key related functions

packages/base/src/delegate/ScrollEnablement.ts
=> chore: remove generics for ScrollEnablement

packages/main/src/Avatar.js
=> fix(ui5-avatar): improved documentation of initials property

packages/main/src/themes/sap_horizon_dark/ListItemBase-parameters.css
=> fix(ui5-li): bottom border is now visible in evening horizon

packages/base/src/util/FocusableElements.ts, packages/fiori/src/SideNavigation.js, packages/fiori/src/SideNavigationItemPopoverContent.hbs, packages/fiori/test/specs/SideNavigation.spec.js, packages/main/bundle.common.js, packages/main/src/List.js, packages/main/src/ListItem.hbs, packages/main/src/ListItemBase.js, packages/main/src/Tree.hbs, packages/main/src/Tree.js, packages/main/src/TreeItem.hbs, packages/main/src/TreeItem.js, packages/main/src/TreeItemBase.hbs, packages/main/src/TreeItemBase.js, packages/main/src/TreeItemCustom.hbs, packages/main/src/TreeItemCustom.js, packages/main/src/TreeList.js, packages/main/src/themes/TreeItem.css, packages/main/test/pages/BusyIndicator.html, packages/main/test/pages/Tree.html, packages/main/test/samples/Tree.sample.html, packages/main/test/specs/BusyIndicator.spec.js, packages/main/test/specs/Tree.spec.js
Related to: #5921 
New `ui5-tree-item-custom` added to allow for custom content to be used inside a tree structure.
**New APIs available on the ui5-tree-item-custom**:
- `content` slot
- `hide-selection-element` property
**Some major changes are done to the concept of the tree:** 
- The  `ui5-tree` again accepts a tree structure, but instead of building a flat structure, it directly slots the tree structure inside the `ui5-list` through the `ui5-tree-list` subclass.
- The `ui5-tree-list` overrides the method `.getItems()` that returns a flat structure for the list to operate with.
- `ui5-tree-item` contains its subitems inside an UL element and it's diplayed as block element below the `.ui5-li-root` element.
- Some styles need to be set to `unset` and moved to the inner element, as the …
=> feat(ui5-tree-item-custom): initial implementation

packages/base/src/util/FocusableElements.ts, packages/fiori/src/SideNavigation.js
=> fix(ui5-side-navigation): focus handling of tree inside popover

packages/main/src/Icon.ts, packages/main/test/pages/Icon.html
=> fix(ui5-icon): showTooltip property documentation improved

packages/main/src/Panel.js, packages/main/test/specs/Panel.spec.js
=> fix(ui5-panel): remove aria controls from expand button

packages/main/src/MultiComboBox.js, packages/main/test/pages/MultiComboBox.html, packages/main/test/pages/styles/MultiComboBox.css, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): force tokenizer layouting when selected items are added

packages/main/src/MonthPicker.hbs, packages/main/src/MonthPicker.js, packages/main/src/YearPicker.hbs, packages/main/src/YearPicker.js, packages/main/src/i18n/messagebundle.properties
- Improve ui5-yearpicker and ui5-monthpicker components announcement.
Fixes: #5858
=> fix(ui5-calendar): set proper roledescription on the pickers

packages/main/src/MultiInput.js, packages/main/test/specs/MultiInput.spec.js
=> fix(ui5-multi-input): focus input when all tokens are deleted

packages/main/src/Dialog.js, packages/main/src/Popup.js, packages/main/src/ResponsivePopover.js, packages/main/src/popup-utils/OpenedPopupsRegistry.js, packages/main/test/pages/Dialog.html, packages/main/test/pages/ResponsivePopover.html, packages/main/test/specs/Dialog.spec.js
Only the top block layer should be visible, when a dialog over a dialog is shown.
Fixes #6089
=> fix(ui5-dialog): fix block layers when multiple dialogs are open

packages/main/src/themes/Table.css
=> fix(ui5-table): apply correct color to the header row text

packages/fiori/test/samples/IllustratedMessage.sample.html, packages/fiori/test/samples/MediaGallery.sample.html, packages/main/test/samples/StepInput.sample.html, packages/main/test/samples/Table.sample.html
=> fix(docs): samples typos

packages/main/src/MultiComboBox.js, packages/main/test/pages/MultiComboBox.html, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): prevent tokenizing of group headers

packages/main/src/StepInput.hbs, packages/main/src/StepInput.ts, packages/main/src/features/InputElementsFormSupport.ts
The most important change is the removal of `previousValueState`. Please verify it's ok.
=> refactor(ui5-step-input): convert to Typescript

packages/main/src/ComboBoxPopover.hbs, packages/main/src/themes/ValueStateMessage.css
Remove value state massage white spacing from ui5-input, ui5-combobox, ui5-multi-combobox, ui5-multi-input. Correct ui5-combobox hbs.
FIXES: #3856
=> fix(ui5-(multi)-input, ui5-(multi)-combobox): remove value state message spacing

packages/fiori/src/Wizard.js, packages/fiori/test/pages/WizardScrolling.html, packages/fiori/test/specs/Wizard.spec.js
FIXES: [#5857](https://github.com/SAP/ui5-webcomponents/issues/5857)
=> fix(ui5-wizard): allow scrolling when step is bigger than viewport

packages/main/src/ColorPalette.ts, packages/main/src/ColorPaletteItem.ts, packages/main/src/ColorPalettePopover.ts, packages/theming/css-vars-usage.json
- `ColorPaletteItem`
- `ColorPalette`
- `ColorPalettePopover`
=> feat(ui5-color-palette): convert to Typescript

packages/fiori/src/ShellBar.hbs, packages/fiori/src/ShellBar.js, packages/fiori/test/pages/ShellBar.html, packages/fiori/test/specs/ShellBar.spec.js
=> feat(ui5-shellbar): accessibilityAttributes property added

packages/main/src/Badge.ts
=> refactor(ui5-badge): convert to TS

packages/main/package.json, packages/main/src/List.ts, packages/main/src/TreeList.js, packages/main/test/pages/Tree.html, packages/main/test/specs/Tree.spec.js
=> fix(ui5-tree): correct forwarding of mode value to items

packages/base/src/util/ColorConversion.ts, packages/main/src/Card.hbs, packages/main/src/Card.ts, packages/main/src/CardHeader.hbs, packages/main/src/CardHeader.ts
=> refactor(ui5-card, ui5-card-header): migrate to TypeScript

packages/fiori/src/FilterItem.ts, packages/fiori/src/ViewSettingsDialog.ts, packages/main/src/CardHeader.ts, packages/main/src/Input.ts, packages/main/src/StepInput.ts, packages/main/src/SuggestionItem.ts
Related to: https://github.com/SAP/ui5-webcomponents/issues/6300
=> docs: fix jsdoc in several components

packages/fiori/src/DynamicSideContent.ts, packages/fiori/src/ViewSettingsDialog.ts, packages/main/src/ColorPalettePopover.ts, packages/main/src/DateRangePicker.ts, packages/main/src/Dialog.ts, packages/main/src/FileUploader.ts, packages/main/src/Input.ts, packages/main/src/Menu.ts, packages/main/src/Popover.ts, packages/main/src/Popup.ts, packages/main/src/TimePicker.ts, packages/main/src/TimePickerBase.ts
Related to: https://github.com/SAP/ui5-webcomponents/issues/6300
=> docs: fix js doc of component methods and readonly props

.github/workflows/release-on-tag.yaml, .github/workflows/release.yaml, package.json, yarn.lock
- add lerna as dev dep, using it for publish and release and changelog
=> chore: add "lerna" as dev dep

CHANGELOG.md, lerna.json, packages/base/CHANGELOG.md, packages/base/package.json, packages/create-package/CHANGELOG.md, packages/create-package/package.json, packages/fiori/CHANGELOG.md, packages/fiori/package.json, packages/icons-business-suite/CHANGELOG.md, packages/icons-business-suite/package.json, packages/icons-tnt/CHANGELOG.md, packages/icons-tnt/package.json, packages/icons/CHANGELOG.md, packages/icons/package.json, packages/localization/CHANGELOG.md, packages/localization/package.json, packages/main/CHANGELOG.md, packages/main/package.json, packages/playground/CHANGELOG.md, packages/playground/package.json, packages/theming/CHANGELOG.md, packages/theming/package.json, packages/tools/CHANGELOG.md, packages/tools/package.json
This reverts commit 7663971b953f018b2fffaf198efebef0cc0536cd.
=> chore: revert auto committed release of v1.10.1

packages/main/src/SegmentedButton.js
=> fix(ui5-segmented-button): ignore scoping suffix when checking tag name

packages/fiori/src/FilterItem.ts, packages/fiori/src/FilterItemOption.ts, packages/fiori/src/NotificationAction.js, packages/fiori/src/ShellBarItem.js, packages/fiori/src/SideNavigationItem.js, packages/fiori/src/SortItem.ts, packages/fiori/src/WizardStep.js, packages/main/src/BreadcrumbsItem.ts, packages/main/src/CalendarDate.ts, packages/main/src/ColorPaletteItem.ts, packages/main/src/ComboBoxGroupItem.js, packages/main/src/ComboBoxItem.js, packages/main/src/MenuItem.ts, packages/main/src/MultiComboBoxGroupItem.js, packages/main/src/MultiComboBoxItem.js, packages/main/src/Option.js, packages/main/src/SegmentedButtonItem.js, packages/main/src/SuggestionGroupItem.ts, packages/main/src/SuggestionItem.ts
=> docs: mark abstract components

packages/base/src/util/FocusableElements.ts
Currently, if we are looking for a focusable element inside assignedNodes and there is no one we will continue with the nextSibling element. In some cases, nextSibling element might be the next element inside the light DOM, so we are explicitly checking if the element is part of the currently monitored assigned element or we are trying to get the next assigned element.
In the following case, the nextSibling element of the slotted div inside the header slot will be the anchor tag instead of the ui5-button ignoring the correct order inside the content slot.
```html
<ui5-dialog>
<ui5-button>button</ui5-button>
<div slot="header">Header text</div>
<a href="#">a link</a>
</ui5-dialog>
```
=> fix(framework): find correct focusable element

packages/main/src/Dialog.ts
=> docs(ui5-dialog): add advice for opening multiple dialogs

packages/main/src/Select.ts, packages/main/test/pages/Select.html, packages/main/test/specs/Select.spec.js
There are two new events 'open' and 'close' which are fired after the dropdown's opening and closure respectively.
FIXES: #5836
=> feat(ui5-select): new events introduced

packages/main/src/Input.ts, packages/main/test/specs/Input.spec.js
=> fix(ui5-input): fire change after clear icon pressed and focus out

packages/fiori/src/ShellBar.hbs
=> fix(ui5-shellbar): i18n of cancel search button text

packages/main/src/Avatar.ts, packages/main/src/AvatarGroup.ts
Related to: https://github.com/SAP/ui5-webcomponents/issues/4337
=> feat(ui5-avatar-group): migrated to Typescript

packages/main/src/Tab.ts
=> fix(ui5-tab): mark the component as "abstract"

packages/fiori/src/Page.ts
=> fix(ui5-page): update documentation on page height

packages/main/test/specs/RangeSlider.spec.js
Similar test when swapping values is  failing regularly in addition to this one commented with PR https://github.com/SAP/ui5-webcomponents/pull/6447
=> chore: comment failing test

packages/main/src/themes/Table.css
=> fix(ui5-table): remove unnecessary border-top if no-data

packages/main/src/themes/Badge.css, packages/main/test/pages/Badge.html
=> fix(ui5-badge): align multiple badges when used in one line

docs/4-frameworks/03-Vue.md
- The documentation now includes a section detailing the process for setting up a project with Vite and Vue.js utilizing UI5 Web Components;
- The information related to project configurations has been slightly updated in accordance with the most recent Vue documentation;
Fixes: #6371
=> docs: update Vue and UI5 Web Components development docs

packages/main/test/samples/Table.sample.html
=> fix(ui5-table): update samples with required styles

packages/main/src/WheelSlider.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/6459
=> fix(ui5-wheel-slider): reduce the wheel speed when using pad

packages/main/src/themes/CustomListItem.css
=> fix(ui5-li-custom): fixed visual glitches

packages/main/src/Avatar.ts, packages/main/test/pages/Avatar.html, packages/main/test/specs/Avatar.spec.js
=> fix(ui5-avatar): supporting accented characters

packages/main/src/themes/Label.css
=> fix(ui5-label): use logical property in CSS to handle RTL usage

packages/main/src/TabContainer.ts
=> docs(ui5-tabcontainer): clarify example for allItems

packages/fiori/test/pages/DialogWithBar.html, packages/main/src/themes/Dialog.css
=> fix(ui5-dialog): overstyle bar when slotted in footer

packages/main/src/TextArea.ts
Related to: #4337
Follow-up of: #6499
=> feat(ui5-textarea): migrate to Typescript

packages/main/src/CheckBox.ts, packages/main/test/pages/CheckBox.html, packages/main/test/specs/CheckBox.spec.js
=> feat(ui5-checkbox): make change event preventable

packages/main/src/Input.ts, packages/main/src/MultiInput.ts, packages/main/src/Tokenizer.ts
=> feat(ui5-multi-input): migrate to Typescript

packages/main/src/Tree.hbs, packages/main/src/Tree.ts
=> fix(ui5-tree): fixed header-text apperance

packages/playground/.storybook/docs.tsx, packages/playground/_stories/fiori/ShellBar/ShellBar.stories.ts, packages/playground/_stories/main/Avatar/Avatar.stories.ts, packages/playground/_stories/main/AvatarGroup/AvatarGroup.stories.ts, packages/playground/_stories/main/AvatarGroup/TemplateAvatarGroupSizes.ts, packages/playground/_stories/main/AvatarGroup/TemplateGroupWithPopover.ts, packages/playground/_stories/main/AvatarGroup/TemplateIndividualWithPopover.ts, packages/playground/_stories/main/Dialog/Dialog.stories.ts
Related to: https://github.com/SAP/ui5-webcomponents/issues/4336
Stories with script tags are rendered from scratch every time the render function is called. They are rendered inside different containers if displayed in the docs page or in the canvas page. Dynamic selectors are needed in order for the qurey functions to work. Also, script tag variables live in the global scope so we need them to be scoped in IIFE context.
=> fix(playground): scope components inside stories

packages/main/src/RangeSlider.hbs, packages/main/src/RangeSlider.ts, packages/main/test/specs/RangeSlider.spec.js
=> fix(ui5-range-slider): add aria-valuenow to the progress bar

packages/fiori/src/SideNavigation.ts, packages/fiori/src/Wizard.ts
Closes: https://github.com/SAP/ui5-webcomponents/issues/6629
=> docs: fix namespaces in Wizard,SideNavigation

docs/6-contributing/04-writing-stories.md
Related to: https://github.com/SAP/ui5-webcomponents/issues/4336
=> docs: how to write storybook stories

packages/main/src/Switch.ts, packages/main/test/pages/Switch.html, packages/main/test/specs/Switch.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/5953
=> feat(ui5-switch): make change event preventable

packages/main/src/TimePickerBase.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/6345
=> docs(ui5-time-picker): improve event documentation

packages/fiori/src/NotificationAction.ts, packages/fiori/src/ProductSwitchItem.ts, packages/fiori/src/SideNavigationItem.ts, packages/fiori/src/SideNavigationSubItem.ts, packages/fiori/src/TimelineItem.ts, packages/fiori/src/WizardStep.ts, packages/main/src/Avatar.ts, packages/main/src/Button.ts, packages/main/src/DatePicker.ts, packages/main/src/DateTimePicker.ts, packages/main/src/Icon.ts, packages/main/src/MenuItem.ts, packages/main/src/MessageStrip.ts, packages/main/src/Option.ts, packages/main/src/SplitButton.ts, packages/main/src/StandardListItem.ts, packages/main/src/SuggestionItem.ts, packages/main/src/Tab.ts, packages/main/src/TimePicker.ts, packages/playground/assets/css/api.css
=> chore: fix link position in playground

packages/main/src/Table.ts
=> chore: fix table docs

packages/main/test/pages/OpenUI5-second.html
This simulates an app that needs to load OpenUI5 on demand with good configuration.
=> chore: create a test page showing OpenUI5-second approach

packages/main/src/themes/StepInput.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/6687
=> fix(ui5-step-input): align style to specification

packages/main/src/ComboBox.hbs, packages/main/src/DatePicker.hbs, packages/main/src/MultiComboBox.hbs, packages/main/src/MultiInput.hbs, packages/main/src/StepInput.hbs, packages/main/src/TimePicker.hbs, packages/main/src/TreeItemBase.hbs, packages/main/src/themes/Icon.css
Reverts SAP/ui5-webcomponents#6565
=> Revert "chore: add missing ui5- prefix to component events in .hbs files"

packages/main/src/Select.ts, packages/main/test/specs/Select.spec.js
=> fix(ui5-select): selected option is announced on dropdown open

packages/main/src/MultiComboBox.ts, packages/main/test/pages/MultiComboBox.html, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): prevent focus lost after token deletion

packages/main/src/themes/TextArea.css
=> fix(ui5-textarea): apply correct styles to value state None

packages/main/src/Avatar.ts
Fixes: [6789](https://github.com/SAP/ui5-webcomponents/issues/6789)
=> fix(ui5-avatar): documentation fix

packages/main/src/themes/ProgressIndicator.css
=> fix(ui5-progress-indicator): disabled opacity fix

packages/main/src/themes/CheckBox.css, packages/main/src/themes/sap_horizon/CheckBox-parameters.css, packages/main/src/themes/sap_horizon_dark/CheckBox-parameters.css
=> fix(ui5-checkbox): apply correct styles to down state

packages/main/src/themes/Button.css, packages/main/src/themes/ComboBox.css, packages/main/src/themes/FormComponents.css, packages/main/src/themes/Input.css, packages/main/src/themes/MultiComboBox.css, packages/main/src/themes/SegmentedButton.css, packages/main/src/themes/Select.css, packages/main/src/themes/SplitButton.css, packages/main/src/themes/StepInput.css, packages/main/src/themes/TextArea.css, packages/main/src/themes/TimePicker.css, packages/main/test/pages/FormComponents.html, packages/main/test/pages/styles/FormComponents.css
=> fix(ui5-input, ui5-button): align form controls vertically

packages/playground/_stories/main/Button/Button.stories.ts, packages/playground/_stories/main/SegmentedButton/SegmentedButton.stories.ts, packages/playground/_stories/main/SplitButton/SplitButton.stories.ts, packages/playground/_stories/main/StepInput/StepInput.stories.ts, packages/playground/_stories/main/Switch/Switch.stories.ts, packages/playground/_stories/main/ToggleButton/ToggleButton.stories.ts
Updated Components:
* ui5-button
* ui5-segmented-button
* ui5-toggle-button
* ui5-split-button
* ui5-step-input
* ui5-switch
=> feat(ui5-button, ui5-segmented-button, ...): add samples to storybook

packages/main/src/Select.ts, packages/main/src/SelectPopover.hbs, packages/main/test/specs/Select.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6460
=> fix(ui5-select): close picker on selection

packages/playground/_stories/main/RangeSlider/RangeSlider.stories.ts
Add ui5-range-slider storybook sample
=> docs(ui5-range-slider): add storybook sample

packages/playground/_stories/main/MultiInput/MultiInput.stories.ts, packages/playground/_stories/main/RangeSlider/RangeSlider.stories.ts
Add storybook sample for ui5-multi-input
=> docs(ui5-multi-input): add storybook sample

packages/fiori/src/themes/base/FlexibleColumnLayout-parameters.css, packages/fiori/src/themes/sap_horizon/FlexibleColumnLayout-parameters.css, packages/fiori/src/themes/sap_horizon/parameters-bundle.css, packages/fiori/src/themes/sap_horizon_dark/FlexibleColumnLayout-parameters.css, packages/fiori/src/themes/sap_horizon_dark/parameters-bundle.css
Updates the FlexibleColumnLayout to use the new border parameter as described in the Visual Design specification.
=> fix(ui5-flexible-column-layout): add new border parameter

packages/main/src/Tab.ts, packages/main/test/samples/TabContainer.sample.html
Added a sample containing tabs with Icons and tabs without icons.
Fixed sample where count should be inline
Fixes: #6765
=> docs(ui5-tabcontainer): add samples and documentation

packages/main/src/Avatar.hbs, packages/main/src/Avatar.ts, packages/main/src/themes/Avatar.css
=> fix(ui5-avatar): avatar initials correct display

packages/main/src/Card.ts, packages/main/src/CardHeader.ts, packages/main/src/Interfaces.ts
and make CardHeader implement ICardHeader
=> docs(Card): adjust type for header slot

packages/main/src/MultiComboBox.ts
=> fix(ui5-multi-combobox): prevent exception on mobile device

packages/localization/lib/copy-and-strip-cldr/index.js
Some fields are no longer stripped because of direct usage (outside of the scope of our web components)
closes: https://github.com/SAP/ui5-webcomponents/issues/6990
=> chore: return some CLDR fields

packages/main/test/specs/DateTimePicker.spec.js
Tried to reproduce it locally but it was a green test 20/20.
It might be a timing issue so this is just a blind try.
=> fix(ui5-date-time-picker): fix test

CHANGELOG.md, lerna.json, packages/base/CHANGELOG.md, packages/base/package.json, packages/create-package/CHANGELOG.md, packages/create-package/package.json, packages/fiori/CHANGELOG.md, packages/fiori/package.json, packages/icons-business-suite/CHANGELOG.md, packages/icons-business-suite/package.json, packages/icons-tnt/CHANGELOG.md, packages/icons-tnt/package.json, packages/icons/CHANGELOG.md, packages/icons/package.json, packages/localization/CHANGELOG.md, packages/localization/package.json, packages/main/CHANGELOG.md, packages/main/package.json, packages/playground/CHANGELOG.md, packages/playground/package.json, packages/theming/CHANGELOG.md, packages/theming/package.json, packages/tools/CHANGELOG.md, packages/tools/package.json
These changes have been merged while testing commands locally by mistake and reverted now.
=> chore: revert force push of 1.13.1 changelog

packages/main/src/TreeItemBase.ts
=> fix(ui5-tree): rtl styling fixes

packages/localization/lib/copy-and-strip-cldr/index.js
closes: https://github.com/SAP/ui5-webcomponents/issues/6990
Restored:
- some one-line fields that make no real difference
- some fields that are used externally
=> chore: restore some more CLDR fields

packages/fiori/src/themes/ShellBar.css
=> fix(ui5-shellbar): containers shrink factor reduced

packages/main/src/themes/Input.css
=> fix(ui5-input): apply content-box to all slotted icons with !important

packages/fiori/src/themes/ShellBar.css, packages/fiori/src/themes/sap_horizon/ShellBar-parameters.css, packages/fiori/src/themes/sap_horizon_dark/ShellBar-parameters.css
Related to: https://github.com/SAP/ui5-webcomponents/issues/5860
=> fix(ui5-shellbar): badge visual alignment

packages/main/src/TableCell.ts, packages/main/src/TableRow.ts, packages/main/src/i18n/messagebundle.properties, packages/main/test/pages/Table.html, packages/main/test/specs/Table.spec.js
=> feat(ui5-table): announce empty cells

packages/main/src/themes/TextArea.css, packages/main/src/themes/base/TextArea-parameters.css, packages/main/src/themes/sap_horizon/TextArea-parameters.css, packages/main/src/themes/sap_horizon_dark/TextArea-parameters.css
=> fix(ui5-textarea): adjust Horizon themes according to the latest specifications

packages/playground/.storybook/addons/html/HTMLTransformation.ts, packages/playground/.storybook/addons/html/processors/AttributeProcessor.ts, packages/playground/.storybook/addons/html/processors/IProcessor.ts, packages/playground/.storybook/addons/html/processors/index.ts, packages/playground/.storybook/preview.ts
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7035
=> docs(playground): hide private properties

packages/main/src/themes/FileUploader.css, packages/main/test/pages/FormComponents.html
Related to: https://github.com/SAP/ui5-webcomponents/issues/6513
Related to: https://github.com/SAP/ui5-webcomponents/issues/6514
=> fix(ui5-file-uploader): align form controls vertically

packages/main/src/themes/sap_horizon/Switch-parameters.css, packages/main/src/themes/sap_horizon_dark/Switch-parameters.css, packages/main/src/themes/sap_horizon_hcb/Switch-parameters.css, packages/main/src/themes/sap_horizon_hcw/Switch-parameters.css
There was wrong parameter value not according to the VD specification.
Now it is fixed.
fixes: #6817
=> fix(ui5-switch): fix truncation when text spacing is applied

packages/main/src/Tab.hbs, packages/main/src/TabContainer.ts, packages/main/src/TabInStrip.hbs, packages/main/src/TabSeparatorInOverflow.hbs, packages/main/src/TabSeparatorInStrip.hbs, packages/main/test/specs/TabContainer.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6796
=> fix(ui5-tab): stable dom ref is now the same as the dom ref

packages/main/src/Popup.ts
=> fix(ui5-dialog): fix focus bug in safari

packages/main/src/Avatar.hbs, packages/main/test/pages/Avatar.html, packages/main/test/specs/Avatar.spec.js, packages/playground/_stories/main/Avatar/Avatar.stories.ts
Fixes: [#6896](https://github.com/SAP/ui5-webcomponents/issues/6896)
=> fix(ui5-avatar): aria-label added to initials

packages/main/src/themes/DayPicker.css, packages/main/src/themes/base/DatePicker-parameters.css, packages/main/src/themes/base/DayPicker-parameters.css, packages/main/src/themes/base/sizes-parameters.css, packages/main/src/themes/sap_belize/DayPicker-parameters.css, packages/main/src/themes/sap_belize_hcb/DayPicker-parameters.css, packages/main/src/themes/sap_belize_hcw/DayPicker-parameters.css, packages/main/src/themes/sap_fiori_3/DayPicker-parameters.css, packages/main/src/themes/sap_fiori_3_dark/DayPicker-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/DayPicker-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/DayPicker-parameters.css, packages/main/src/themes/sap_horizon/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_dark/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcb/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcw/DayPicker-parameters.css
Related to: https://github.com/SAP/ui5-webcomponents/issues/6999
**Before** 
**After**
=> feat(ui5-calendar): update visual design to latest SAP Horizon spec

packages/main/src/themes/FileUploader.css
Fixes: #7055
Related to: #6513
=> fix(ui5-file-uploader): align vertically input and the button

packages/playground/.storybook/preview-head.html, packages/playground/_stories/fiori/ViewSettingsDialog/ViewSettingsDialog.stories.ts, packages/playground/_stories/main/ColorPalettePopover/ColorPalettePopover.stories.ts, packages/playground/_stories/main/Input/Input.stories.ts
=> docs(playground): remove hardcoded iframe min-height

packages/main/src/ProgressIndicator.ts
=> fix(ui5-progress-indicator): align icon value with VD

packages/playground/_stories/main/Table/Table.stories.ts
=> fix(ui5-table): adjust samples

packages/main/src/ComboBox.ts, packages/main/test/specs/ComboBox.spec.js
=> fix(ui5-combobox): remove position announcement for group header items

packages/main/src/themes/TreeItem.css
=> fix(ui5-side-navigation): cursor is pointer for selected items

packages/fiori/src/ShellBar.ts
=> fix(ui5-shellbar): tweaked breakpoint size "S" responsive padding

packages/main/src/Button.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/7249
=> fix(ui5-button): prevent event throw on mobile when disabled

packages/fiori/src/themes/ShellBar.css, packages/main/src/themes/base/rtl-parameters.css
=> fix(ui5-shellbar): align notification counter badge

packages/main/src/themes/Link.css
=> fix(ui5-link): change width to max-width

packages/create-package/template/src/MyFirstComponent.ts, packages/tools/lib/create-new-component/index.js
- fix placeholder: NIT_PACKAGE_VAR_NAMESPACE -> INIT_PACKAGE_VAR_NAMESPACE
- change prompt text
=> chore: fix template in create-package script

packages/base/package.json, packages/fiori/package.json, packages/icons-business-suite/package.json, packages/icons-tnt/package.json, packages/icons/package.json, packages/localization/package.json, packages/main/package.json, packages/theming/package.json, packages/tools/package.json
Force publish unchanged packages for v1.15.1
=> chore(release): force publish unchanged packages for v1.15.1

packages/playground/_stories/main/SegmentedButton/SegmentedButton.stories.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/7290
=> docs(ui5-segmented-button): include new property to storybook

packages/main/src/ProgressIndicator.hbs, packages/main/src/ProgressIndicator.ts, packages/main/test/pages/ProgressIndicator.html, packages/main/test/specs/ProgressIndicator.spec.js
Related: https://github.com/SAP/ui5-webcomponents/issues/6854
=> feat(ui5-progress-indicator): accessibleName property added

packages/main/src/themes/Token.css, packages/main/src/themes/base/Token-parameters.css, packages/main/src/themes/base/sizes-parameters.css, packages/main/src/themes/sap_horizon/Token-parameters.css, packages/main/src/themes/sap_horizon_dark/Token-parameters.css, packages/main/src/themes/sap_horizon_hcb/Token-parameters.css, packages/main/src/themes/sap_horizon_hcw/Token-parameters.css
=> fix(ui5-token): adjust Horizon themes according to the specification

packages/main/src/List.ts, packages/main/test/pages/List_test_page.html, packages/main/test/specs/List.spec.js
=> fix(ui5-list): avoid close event conflicts

packages/main/src/FileUploader.ts, packages/playground/_stories/main/FileUploader/FileUploader.stories.ts
Related to the **`accessibleNameRef`** initiative of the story #5893
=> docs(ui5-file-uploader): improve accessibility in storybook samples

packages/main/src/Token.ts, packages/main/test/pages/MultiInput.html, packages/main/test/specs/MultiInput.spec.js
=> fix(ui5-multi-input): prevent exception when single token is added

packages/main/test/specs/Table.spec.js
Due to some timing issue a test is failing from time to time. An attempt to make it more stable.
Fixes: #7336
=> fix(ui5-table): fix unstable tests

packages/base/package.json, packages/localization/package.json, packages/localization/src/sap/base/i18n/Localization.ts, packages/localization/used-modules.txt, yarn.lock
Version 1.116.0 contains fix for #7080
=> chore: update @openui5 to 1.116.0

packages/base/src/delegate/ItemNavigation.ts, packages/main/src/Popup.ts, packages/main/src/RadioButtonGroup.ts, packages/main/src/TabContainer.ts, packages/main/src/themes/BusyIndicator.css, packages/main/src/themes/CardHeader.css, packages/main/src/themes/Carousel.css, packages/main/src/themes/Dialog.css, packages/main/src/themes/RadioButton.css, packages/main/src/themes/TabInStrip.css
This change reverts #6084
Fixes #7098
Fixes #6895
=> fix(ui5): change "focus-visible" pseudo selector to "focus"

packages/playground/_stories/fiori/Page/Page.stories.ts
=> fix(ui5-page): adjust storybook sample

packages/playground/_stories/main/Dialog/Dialog.stories.ts, packages/playground/_stories/main/Popover/Popover.stories.ts, packages/playground/_stories/main/ResponsivePopover/ResponsivePopover.stories.ts, packages/playground/assets/css/api.css
=> docs(ui5-dialog): edit footer layout in dialogs samples

packages/main/src/Dialog.ts
=> docs(ui5-dialog): document usage of ui5-bar better

packages/main/src/SliderBase.ts
=> fix(ui5-slider): remove tag name from base class

packages/main/src/TabSeparator.ts
=> docs(ui5-tab-separator): mark as abstract

packages/fiori/src/NotificationAction.ts, packages/fiori/src/NotificationListItemBase.ts, packages/fiori/src/UploadCollection.ts, packages/main/src/BusyIndicator.ts, packages/main/src/Carousel.ts, packages/main/src/CheckBox.ts, packages/main/src/Label.ts, packages/main/src/Link.ts, packages/main/src/Popover.ts, packages/main/src/Popup.ts, packages/main/src/RadioButton.ts, packages/main/src/TabContainer.ts, packages/main/src/Title.ts, packages/playground/_stories/fiori/NotificationListGroupItem/NotificationListGroupItem.stories.ts, packages/playground/_stories/fiori/NotificationListItem/NotificationListItem.stories.ts, packages/playground/_stories/fiori/SideNavigation/SideNavigation.stories.ts, packages/playground/_stories/fiori/UploadCollection/UploadCollection.stories.ts, packages/playground/_stories/main/BusyIndicator/BusyIndicator.stories.ts, packages/playground/_stories/main/Card/Card.stories.ts, packages/playground/_stories/main/Carousel/Carousel.stories.ts, packages/playground/_stories/main/Dialog/Dialog.stories.ts, packages/playground/_stories/main/Label/Label.stories.ts, packages/playground/_stories/main/RadioButton/RadioButton.stories.ts, packages/playground/_stories/main/ResponsivePopover/ResponsivePopover.stories.ts, packages/playground/_stories/main/TabContainer/TabContainer.stories.ts, packages/playground/assets/css/api.css
=> docs(all): apply documentation feedback for team Rodopi

packages/playground/_stories/fiori/SideNavigation/SideNavigation.stories.ts
Part of https://github.com/SAP/ui5-webcomponents/issues/7308
=> chore(ui5-side-navigation): add Tool Layout sample

packages/fiori/src/Bar.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/7412
=> refactor(ui5-bar): remove redundant internet explorer specific code

packages/main/src/DatePicker.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/6993
=> fix(ui5-date-picker): align value state to react binding

packages/fiori/src/Page.ts, packages/playground/_stories/fiori/Page/Page.stories.ts
=> fix(ui5-page): enhance storybook samples

packages/playground/_stories/main/RatingIndicator/RatingIndicator.stories.ts
=> fix(ui5-rating-indicator): enhance storybook samples

packages/playground/_stories/fiori/Wizard/Wizard.stories.ts
=> fix(ui5-wizard): enhance storybook samples

packages/main/src/themes/sap_horizon/InputIcon-parameters.css, packages/main/src/themes/sap_horizon_dark/InputIcon-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/InputIcon-parameters.css, packages/main/src/themes/sap_horizon_exp/InputIcon-parameters.css
=> fix(ui5-input): apply correct button's box-shadow on hover

packages/main/src/Toast.ts, packages/playground/_stories/main/Toast/Toast.stories.ts
=> fix(ui5-toast): enhance storybook samples

packages/main/src/MultiComboBox.ts, packages/playground/_stories/main/MultiComboBox/MultiComboBox.stories.ts
=> fix(ui5-multi-combobox): adjust storybook sample

packages/main/src/MessageStrip.ts, packages/playground/_stories/main/MessageStrip/MessageStrip.stories.ts
=> fix(ui5-message-strip): enhance storybook samples

packages/playground/_stories/main/Panel/Panel.stories.ts
=> fix(ui5-panel): enhance storybook samples

packages/main/src/ListItem.hbs
closes: https://github.com/SAP/ui5-webcomponents/issues/7473
=> chore: add list item shadow parts

packages/main/src/TextArea.ts
=> fix(ui5-textarea): prevent console error on focus out

packages/playground/build-scripts-storybook/parse-manifest.js, packages/tools/lib/generate-custom-elements-manifest/index.js
With this change Storybook will display inherited properties.
Fixes: #7503
=> docs: show inherited properties inside storybook

packages/main/src/Table.ts, packages/playground/_stories/main/Table/Table.stories.ts
Related to: #7284
JIRA: BGSOFUIRILA-3683
=> fix(ui5-table): enhance storybook samples

packages/playground/_stories/main/MultiInput/MultiInput.stories.ts
Related to: https://github.com/SAP/ui5-webcomponents/issues/7284
JIRA: BGSOFUIRILA-3683
=> fix(ui5-multi-input): enhance storybook samples

packages/main/src/Input.ts, packages/playground/_stories/main/Input/Input.stories.ts
Related to: https://github.com/SAP/ui5-webcomponents/issues/7284
JIRA: BGSOFUIRILA-3683
=> fix(ui5-input): enhance storybook samples

packages/main/src/TreeItemBase.ts
=> fix(ui5-tree): indentation correction

packages/main/src/themes/TreeItem.css
=> fix(ui5-tree): list item active state implemented

packages/main/src/Link.hbs, packages/main/src/Link.ts, packages/main/test/pages/Link.html
fixes: https://github.com/SAP/ui5-webcomponents/issues/7518
=> fix(ui5-link): add title to inner link

packages/main/src/Select.ts, packages/main/src/SelectMenu.ts, packages/main/test/pages/SelectMenu.html
The PR addresses two issues - one in the Select and one in the SelectMenu.
- [Select] JS error is thrown when there are no options slotted - introduced with a recent [PR](https://github.com/SAP/ui5-webcomponents/commit/8ecd1183c2a8b041f444cc8d0814f096e8b2dbd5)  and it's visible in the first example in the [test page ](https://sap.github.io/ui5-webcomponents/nightly/playground/main/pages/SelectMenuLifecycle/)
<br><br>
- [SelectMenu] The dropdown's width increases with every selection when there are multiple options (+ scrollbar) and value state set.
Reproducible with multiple items:
https://github.com/SAP/ui5-webcomponents/assets/15702139/47168ce0-50c6-489b-a2cd-bbf26493b457
Now fixed:
https://github.com/SAP/ui5-webcomponents/assets/15702139/bb7a93a2-0edd-42ff-9dcf-1b7d1417cc2d
=> chore(ui5-select, ui5-select-menu): fix few issues

packages/playground/_stories/fiori/NotificationListGroupItem/NotificationListGroupItem.stories.ts, packages/playground/_stories/fiori/NotificationListItem/NotificationListItem.stories.ts
=> docs(ui5-li-notification): remove padding in popover in Storybook sample

packages/main/src/themes/sap_horizon/Dialog-parameters.css, packages/main/src/themes/sap_horizon_dark/Dialog-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/Dialog-parameters.css, packages/main/src/themes/sap_horizon_exp/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcb/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcw/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcw_exp/Dialog-parameters.css
=> fix(ui5-dialog): adjust resize handle position for Horizon

packages/main/src/themes/BusyIndicator.css
=> fix(ui5-busy-indicator): fix spacing between dots

packages/main/src/Select.ts, packages/playground/_stories/main/Select/Select.stories.ts
- update Select story by placing the SelectMenu top-level, avoiding page styles (transitions) that cause SelectMenu misplacement.
- add more info in the Select's overview
=> docs: update `Select` story

packages/main/test/samples/Card.sample.html, packages/playground/_stories/main/Card/Card.stories.ts
=> docs(ui5-card): change "form like" sample to use <span> instead of <ui5-title>

packages/main/src/themes/Input.css, packages/main/src/themes/TextArea.css
=> fix(ui5-input,ui5-textarea): adjust disabled readonly visualisation

packages/fiori/src/themes/UploadCollectionItem.css
=> fix(ui5-upload-collection-item): align thumbnail to top

packages/playground/_stories/fiori/Page/Page.stories.ts, packages/playground/_stories/main/Input/Input.stories.ts, packages/playground/_stories/main/MultiInput/MultiInput.stories.ts, packages/playground/_stories/main/RangeSlider/RangeSlider.stories.ts, packages/playground/_stories/main/RatingIndicator/RatingIndicator.stories.ts, packages/playground/_stories/main/Slider/Slider.stories.ts, packages/playground/_stories/main/TextArea/TextArea.stories.ts
=> fix(ui5-input,ui5-page,ui5-rating-indicator,ui5-slider,ui5-textarea): improve samples names

packages/main/src/themes/Button.css, packages/main/src/themes/ToggleButton.css, packages/main/src/themes/base/Button-parameters.css, packages/main/src/themes/base/sizes-parameters.css, packages/main/src/themes/sap_belize_hcb/Button-parameters.css, packages/main/src/themes/sap_belize_hcw/Button-parameters.css, packages/main/src/themes/sap_fiori_3/Button-parameters.css, packages/main/src/themes/sap_fiori_3_dark/Button-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/Button-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/Button-parameters.css, packages/main/src/themes/sap_horizon/Button-parameters.css, packages/main/src/themes/sap_horizon_dark/Button-parameters.css, packages/main/src/themes/sap_horizon_exp/Button-parameters.css, packages/main/src/themes/sap_horizon_hcb/Button-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/Button-parameters.css, packages/main/src/themes/sap_horizon_hcw/Button-parameters.css, packages/main/src/themes/sap_horizon_hcw_exp/Button-parameters.css
=> fix(ui5-button): remove box shadows

packages/main/src/popup-utils/PopoverRegistry.ts
=> fix(ui5-popover): improve positioning when scrolling

packages/main/src/themes/TableCell.css, packages/main/src/themes/TableColumn.css, packages/main/src/themes/base/Table-parameters.css, packages/main/src/themes/sap_horizon/Table-parameters.css, packages/main/src/themes/sap_horizon_dark/Table-parameters.css, packages/main/src/themes/sap_horizon_hcb/Table-parameters.css, packages/main/src/themes/sap_horizon_hcw/Table-parameters.css
- The font-family of the table's column headers and the cells content color are changed according to the specification
=> fix(ui5-table): improve Horizon styles

packages/playground/_stories/fiori/BarcodeScannerDialog/BarcodeScannerDialog.stories.ts, packages/playground/_stories/fiori/FlexibleColumnLayout/FlexibleColumnLayout.stories.ts, packages/playground/_stories/fiori/IllustratedMessage/IllustratedMessage.stories.ts, packages/playground/_stories/fiori/MediaGallery/MediaGallery.stories.ts, packages/playground/_stories/fiori/ProductSwitch/ProductSwitch.stories.ts, packages/playground/_stories/fiori/ShellBar/ShellBar.stories.ts, packages/playground/_stories/main/Breadcrumbs/Breadcrumbs.stories.ts, packages/playground/_stories/main/CheckBox/CheckBox.stories.ts, packages/playground/_stories/main/ProgressIndicator/ProgressIndicator.stories.ts, packages/playground/_stories/main/Toolbar/Toolbar.stories.ts
=> docs: improve storybook samples names

packages/main/src/Calendar.ts, packages/main/src/CalendarHeader.ts, packages/main/src/DateComponentBase.ts, packages/main/src/DayPicker.hbs, packages/main/src/DayPicker.ts, packages/main/src/MonthPicker.ts, packages/main/src/YearPicker.ts, packages/main/src/themes/DayPicker.css, packages/main/test/pages/Calendar.html, packages/main/test/specs/Calendar.spec.js
fixes: [7557](https://github.com/SAP/ui5-webcomponents/issues/7557)
=> fix(ui5-calendar): hide secondary type when same as primary

packages/main/src/Menu.ts
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7637
=> fix(ui5-menu): prevent bubbling in events

packages/fiori/test/specs/ShellBar.spec.js
=> fix(ui5-shellbar): often failing unit test

packages/main/src/themes/sap_horizon_hcb/CheckBox-parameters.css, packages/main/src/themes/sap_horizon_hcw/CheckBox-parameters.css
Fix hover of error state checkbox.
=> fix(ui5-checkbox): fix horizon hcb and hcw

packages/main/src/Avatar.ts, packages/main/test/specs/Avatar.spec.js
Role "img" added on non-interactive avatar.
Fixes: #7591
=> fix(ui5-avatar): a11y fixed

packages/main/src/themes/Panel.css, packages/main/test/pages/Panel.html, packages/main/test/pages/styles/Panel.css
=> feat(ui5-panel): enable custom styling of title

packages/fiori/src/FlexibleColumnLayout.hbs, packages/fiori/src/themes/FlexibleColumnLayout.css
=> fix(ui5-flexible-column-layout): wrong focus fixed

packages/fiori/src/FlexibleColumnLayout.ts, packages/fiori/src/IllustratedMessage.ts, packages/fiori/src/MediaGallery.ts, packages/main/src/Avatar.ts, packages/main/src/AvatarGroup.ts, packages/main/src/Breadcrumbs.ts, packages/main/src/CheckBox.ts, packages/main/src/Icon.ts, packages/main/src/List.ts, packages/main/src/ProgressIndicator.ts, packages/main/src/Select.ts, packages/main/src/Toolbar.ts, packages/main/src/Tree.ts
Related: https://github.com/SAP/ui5-webcomponents/issues/7284
The enum values are removed from the jsdoc comments
=> docs: improve stories` jsdoc

.github/workflows/deploy-latest-docs.yaml, .github/workflows/deploy.yaml, .github/workflows/deploy_latest.yaml, .github/workflows/release-auto-weekly.yaml, .github/workflows/release-custom-tag.yaml, .github/workflows/release-snapshot.yaml, .github/workflows/release.yaml, .github/workflows/test-issue-comments.yaml, .github/workflows/test-storybook.yaml, .github/workflows/test.yaml, packages/base/package.json, packages/base/src/util/ColorConversion.ts, packages/fiori/package.json, packages/localization/package.json, packages/main/package.json, packages/main/src/ColorPicker.ts, packages/main/test/specs/ColorPicker.spec.js, packages/tools/components-package/wdio.js, yarn.lock
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7660
=> fix(ui5-color-picker): fix hsl to rgb color conversion

packages/main/src/themes/sap_horizon/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_exp/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcb/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcw/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcw_exp/DayPicker-parameters.css
The border color of the day grid cell is now correct.
=> fix(ui5-calendar): adjust selected border color

packages/main/src/features/InputSuggestions.ts, packages/main/test/specs/Input.spec.js
=> fix(ui5-input): add additional text to the item's announcement

packages/playground/_stories/main/RatingIndicator/RatingIndicator.stories.ts
Updating the value as per UX recomendation.
=> docs(ui5-rating-indicator): change default value

packages/main/src/List.ts, packages/main/test/pages/List_test_page.html, packages/main/test/specs/List.spec.js
=> fix(ui5-list): removed unnecessary accessibility reading

packages/main/src/SliderBase.ts, packages/main/test/specs/Slider.spec.js
=> fix(ui5-slider): update labels on min and max change

packages/main/src/TextArea.ts
=> fix(ui5-textarea): remove white space from value state message

packages/main/src/TextArea.ts, packages/main/test/pages/TextArea.html, packages/main/test/specs/TextArea.spec.js
=> fix(ui5-textarea): select exceeded text

docs/internal/Toolbar.md, packages/main/src/themes/ToolbarPopover.css, packages/main/test/pages/Toolbar.html, packages/playground/_stories/main/Toolbar/Toolbar.stories.ts, packages/playground/build-scripts-storybook/documentation-prepare.ts
Toolbar abstract item documentation
=> docs(ui5-toolbar): fix documentation

packages/main/src/themes/Button.css, packages/main/src/themes/base/Button-parameters.css, packages/main/src/themes/sap_belize/Button-parameters.css, packages/main/src/themes/sap_belize/parameters-bundle.css, packages/main/src/themes/sap_fiori_3/Button-parameters.css, packages/main/src/themes/sap_fiori_3_dark/Button-parameters.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/7352
=> fix(ui5-button): align styles to specification

packages/main/src/SegmentedButton.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/7788
=> fix(ui5-segmented-button): check for items before applying settings

packages/main/src/TimePicker.ts
fix: https://github.com/SAP/ui5-webcomponents/issues/7790
=> fix(ui5-time-picker): check value before formatting

packages/playground/_stories/fiori/SideNavigation/SideNavigation.stories.ts
The sample should not have error in the console: "Identifier 'sidenav' has already been declared"
Fixes: #7809
=> docs(ui5-side-navigation): edit sample

packages/fiori/src/IllustratedMessage.hbs, packages/fiori/src/IllustratedMessage.ts, packages/fiori/test/pages/IllustratedMessage.html, packages/fiori/test/specs/IllustratedMessage.spec.js, packages/playground/_stories/fiori/IllustratedMessage/IllustratedMessage.stories.ts
Closes: https://github.com/SAP/ui5-webcomponents/issues/7037
=> feat(ui5-illustrated-message): titleLevel property added

packages/playground/.storybook/sbTheme.ts
Click on the logo now navigates to the landing page
Related to: #7284
=> docs(playground): correct brand url

docs/4-frameworks/01-React.md, docs/4-frameworks/02-Angular.md
The angular tutorial has been update to demonstrate both UI5 Web Components and UI5 Web Components for Angular usage. We no longer recommend Origami, instead we added a sample how to build Form and make use of two-way data binding via the UI5 Web Components for Angular wrappers.
=> docs: update Angular tutorial

packages/fiori/src/Wizard.hbs, packages/fiori/src/Wizard.ts
=> fix(ui5-wizard): scrollbar styles are now present on root

packages/main/src/Table.ts, packages/main/test/specs/Table.spec.js, yarn.lock
=> fix(ui5-table): popin-change is now fired on pop out

packages/main/src/themes/Panel.css, packages/main/src/themes/base/Panel-parameters.css, packages/main/src/themes/base/sizes-parameters.css, packages/main/src/themes/sap_belize/Panel-parameters.css, packages/main/src/themes/sap_fiori_3/Panel-parameters.css, packages/main/src/themes/sap_fiori_3/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_dark/Panel-parameters.css, packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css, packages/main/src/themes/sap_horizon/Panel-parameters.css, packages/main/src/themes/sap_horizon_dark/Panel-parameters.css, packages/main/src/themes/sap_horizon_hcw/Panel-parameters.css
=> fix(ui5-panel): improve header visualization

packages/main/src/themes/TextArea.css, packages/main/src/themes/base/TextArea-parameters.css, packages/main/src/themes/sap_horizon/TextArea-parameters.css, packages/main/src/themes/sap_horizon_dark/TextArea-parameters.css
=> fix(ui5-textarea): adjust scroll positioning

packages/fiori/src/DynamicPage.hbs, packages/fiori/src/DynamicPage.ts, packages/fiori/src/themes/DynamicPage.css, packages/fiori/src/themes/DynamicPageHeader.css
Add responsive left/right paddings
=> feat(ui5-dynamic-page): add responsive paddings

packages/main/src/Menu.hbs, packages/main/src/themes/Menu.css, packages/main/test/pages/Menu.html
=> fix(ui5-menu): menu item text doesn't overflow submenu arrow

packages/main/src/themes/TableRow.css, packages/main/src/themes/base/TableRow-parameters.css, packages/main/src/themes/sap_belize/TableRow-parameters.css, packages/main/src/themes/sap_belize_hcb/TableRow-parameters.css, packages/main/src/themes/sap_belize_hcw/TableRow-parameters.css
=> fix(ui5-table): correct alignment of popin in multiselect mode

packages/main/src/ComboBox.ts, packages/main/src/ComboBoxPopover.hbs, packages/main/test/specs/ComboBox.spec.js
=> fix(ui5-combobox): scroll to item upon keyboard navigation

.gitignore, packages/playground/.storybook/main.ts, packages/playground/build-scripts-storybook/sitemap-prepare.ts, packages/playground/docs/landing-page.html, packages/playground/package.json, packages/playground/public/Robots.txt, yarn.lock
- Creates a sitemap from the generated stories.json file. 
- Creates Robots.txt file with the sitemap's location.
- Includes a meta tag in the landing page for google search console verification.
=> docs: generate sitemap.xml and robots.txt

packages/create-package/template/src/MyFirstComponent.ts, packages/tools/lib/create-new-component/tsFileContentTemplate.js
Adapted scripts that create new components/packages with TypeScript to generate output with correct JSDoc syntax.
=> chore: adapt file/package creators to new JSDoc

packages/fiori/src/IllustratedMessage.hbs, packages/fiori/src/IllustratedMessage.ts
Related to: https://github.com/SAP/ui5-webcomponents/issues/7879
=> feat(ui5-illustrated-message): add subtitle css part

packages/main/src/Card.hbs, packages/main/src/Card.ts, packages/main/src/themes/Card.css
=> refactor(ui5-card): add new CSS Shadow parts

packages/create-package/template/src/MyFirstComponent.hbs, packages/create-package/template/src/themes/MyFirstComponent.css, packages/create-package/template/test/pages/index.html
- use correct path to bundle
- make the button click take the whole area and show a cursor: pointer
=> fix: broken test page

packages/main/src/themes/TextArea.css
=> fix(ui5-textarea): prevent page height from growing on large input

packages/fiori/test/specs/SideNavigation.spec.js
=> test(ui5-side-navigation): correct test

packages/main/src/DateTimePicker.ts, packages/main/src/DateTimePickerPopover.hbs, packages/main/src/TimeSelection.hbs, packages/main/src/TimeSelection.ts, packages/main/src/WheelSlider.hbs, packages/main/src/WheelSlider.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/7992
=> fix(ui5-date-time-picker): align calculations with density change

packages/fiori/src/SideNavigation.ts, packages/fiori/src/themes/SideNavigation.css
=> fix(ui5-side-navigation): allow overstyling of width and border-radius

packages/main/src/themes/List.css, packages/main/test/specs/List.spec.js
Closes https://github.com/SAP/ui5-webcomponents/issues/7426
=> fix(ui5-list): load-more event fired correctly

packages/fiori/src/FlexibleColumnLayout.ts, packages/fiori/src/ShellBar.ts, packages/fiori/src/SideNavigation.ts, packages/tools/lib/cem/custom-elements-manifest.config.mjs, packages/tools/lib/cem/utils.mjs
Check if local declared types (declared in the file) that describe public API are exported.
=> chore: guarantee type exports

packages/main/src/CheckBox.ts
=> docs(ui5-checkbox): make displayOnly public

packages/tools/lib/cem/custom-elements-manifest.config.mjs, packages/tools/lib/cem/event.mjs, packages/tools/lib/cem/utils.mjs
Error messages are combined per file and improved the texts.
=> chore: improved error messages for cem

packages/main/src/themes/PopupsCommon.css, packages/main/test/pages/Popover.html
When there is height set on the popover
the footer should be positioned on the bottom
of the popover.
Fixes: #8009
=> fix(ui5-popover): correct position of the footer

packages/main/src/Toolbar.ts, packages/main/src/ToolbarSelect.ts, packages/main/test/specs/ToolbarSelect.spec.js
=> fix(ui5-toolbar): fire noConflict events correctly

packages/base/src/UI5Element.ts, packages/fiori/package.json, packages/main/package.json
revert ssr for further investigation
=> fix: build

.github/ISSUE_TEMPLATE/bug_report.yml, docs/FAQ.md
Remove CodeSandbox links due policy changes.
=> chore: remove codesandbox references

packages/main/src/Toast.ts
=> fix(ui5-toast): check whether the event key property exists

packages/main/test/specs/ComboBox.mobile.spec.js
=> fix(ui5-combobox): fix failing test

CHANGELOG.md, lerna.json, packages/base/CHANGELOG.md, packages/base/package.json, packages/create-package/CHANGELOG.md, packages/create-package/package.json, packages/fiori/CHANGELOG.md, packages/fiori/package.json, packages/icons-business-suite/CHANGELOG.md, packages/icons-business-suite/package.json, packages/icons-tnt/CHANGELOG.md, packages/icons-tnt/package.json, packages/icons/CHANGELOG.md, packages/icons/package.json, packages/localization/CHANGELOG.md, packages/localization/package.json, packages/main/CHANGELOG.md, packages/main/package.json, packages/playground/CHANGELOG.md, packages/playground/package.json, packages/theming/CHANGELOG.md, packages/theming/package.json, packages/tools/CHANGELOG.md, packages/tools/package.json
This reverts commit 93752a67f240914de69c3e5d5986168fd6f2c028.
This reverts commit c1e2404c596342979a2b233c7e96bb118ee00c54.
=> chore: revert auto committed releases of v1.22.0-rc.3 and v1.22.0-rc.4

packages/main/src/Button.ts, packages/main/src/Link.ts, packages/main/src/ToolbarButton.ts
With https://github.com/SAP/ui5-webcomponents/pull/8201 accepted values in the JSDoc were changed start with lower case.
=> docs: accessibility attributes accepted value

packages/main/src/TreeItemBase.ts
=> fix(ui5-tree-item): fix double announcement

packages/main/src/Table.ts, packages/main/test/pages/TableGrowingWithScroll.html, packages/main/test/specs/Table.spec.js
=> fix(ui5-table): prevent load-more event on initial load

.gitignore, packages/fiori/src/types/MediaGalleryItemLayout.ts, packages/playground/build-scripts-storybook/types-prepare.ts, packages/playground/package.json
Provide documentation pages for Interfaces and Enums.
=> chore: generate docs page for interfaces and enums

packages/playground/_stories/main/CheckBox/CheckBox.stories.ts
=> docs(ui5-checkbox): correct displayOnly property showcase

packages/main/src/StepInput.ts, packages/main/test/pages/StepInput.html, packages/main/test/specs/StepInput.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/4791
fixes: https://github.com/SAP/ui5-webcomponents/issues/5130
=> feat(ui5-step-input): add value-state-change event

packages/main/src/themes/CardHeader.css
=> fix(ui5-card-header): truncate long single-word description

packages/main/src/Tree.hbs, packages/main/src/Tree.ts
=> chore(ui5-tree): introduce "item-focus" private event

packages/main/src/TabContainer.ts, packages/main/src/themes/TabContainer.css, packages/main/test/specs/TabContainer.spec.js
=> refactor(ui5-tabcontainer): revert responsive paddings using container logic

packages/fiori/src/TimelineItem.hbs, packages/fiori/src/TimelineItem.ts, packages/fiori/test/pages/Timeline.html, packages/fiori/test/specs/Timeline.spec.js
=> fix(ui5-timeline-item): correct content check

packages/main/src/themes/Button.css, packages/main/src/themes/base/Button-parameters.css
=> fix(ui5-button): correct focus outline colors in active/focus state

packages/playground/_stories/fiori/SideNavigation/SideNavigation.stories.ts
=> fix(ui5-side-navigation): fix broken storybook example

packages/fiori/src/themes/IllustratedMessage.css
=> fix(ui5-illustrated-message): title subtitle aligned with visual spec

packages/main/src/Button.hbs, packages/main/src/Button.ts, packages/main/src/types/ButtonAccessibleRole.ts, packages/main/test/pages/Button.html, packages/main/test/specs/Button.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/7612
=> feat(ui5-button): add accessible-role api

packages/main/src/TextArea.hbs, packages/main/src/TextArea.ts, packages/main/test/pages/TextArea-selection.html, packages/main/test/specs/TextArea.spec.js
=> feat(ui5-textarea): select and scroll events

packages/main/src/themes/TableRow.css
=> fix(ui5-table): highlight popined selected rows

packages/main/src/ComboBox.ts, packages/main/test/specs/ComboBox.spec.js
=> fix(ui5-combobox): show all items upon arrow click

packages/website/build-scripts/api-reference-generation/component-file.mjs, packages/website/src/components/HomepageDemoApps/index.tsx, packages/website/src/components/HomepageFeatures/index.tsx, packages/website/src/components/HomepageFeatures/styles.css, packages/website/src/components/HomepageTestimonials/index.tsx, packages/website/src/components/HomepageTestimonials/styles.css, packages/website/src/css/custom.css, packages/website/src/pages/index.module.css, packages/website/src/pages/index.tsx
- Fix landing page on larger screens
- Remove overview title in order to add overview text into component cards
=> chore: fix landing page and cards description

packages/main/src/DatePicker.ts, packages/main/test/specs/DatePicker.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/8218
=> fix(ui5-date-picker): open correct picker

packages/website/build-scripts/icons-generation/index.mjs, packages/website/src/pages/icons.css
Show tickmark after icon name is copied:
https://github.com/SAP/ui5-webcomponents/assets/15702139/4342be03-0156-4066-b079-b615c43c143d
=> chore: improve copy icon names ux

packages/website/build-scripts/icons-generation/index.mjs, packages/website/src/pages/icons.css
Pressing on the picture button below the Icon copies the icon's SVG to the clipboard.
=> docs: add copy svg to icon explorer

packages/main/src/themes/Icon.css
=> fix(ui5-icon): default icon color aligned with specification

packages/main/src/themes/ProgressIndicator.css, packages/main/src/themes/sap_horizon/ProgressIndicator-parameters.css, packages/main/src/themes/sap_horizon_exp/ProgressIndicator-parameters.css, packages/main/src/themes/sap_horizon_hcb/ProgressIndicator-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/ProgressIndicator-parameters.css
=> fix(ui5-progress-indicator): visual fix

packages/fiori/test/specs/ShellBar.spec.js
=> fix(ui5-shellbar): fix volatile test

packages/main/src/MultiComboBox.ts
=> fix(ui5-multi-combobox): rename togglePopover method

packages/website/docs/_samples/base/UI5Element/Basic/sample.html, packages/website/docs/play.md, packages/website/src/components/Editor/index.js, packages/website/src/components/Editor/share.js
`/play` now has an editor with share button and the shared url works when opened
=> chore(docs): add play page and share feature

packages/website/docs/play.md, packages/website/src/components/Editor/index.js, packages/website/src/components/Editor/index.module.css
- improve share button placement
- add option to initially show editor
- extract inline styles as classes
=> chore: replace "Share" sample button

packages/main/src/CheckBox.hbs, packages/main/src/CheckBox.ts
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8326
=> feat(ui5-checkbox): csspart icon added

packages/main/src/MessageStrip.hbs
=> fix(ui5-message-strip): remove aria-live

packages/main/src/themes/Panel.css, packages/main/src/themes/base/Panel-parameters.css, packages/main/src/themes/sap_horizon/Panel-parameters.css, packages/main/src/themes/sap_horizon_dark/Panel-parameters.css
=> fix(ui5-panel): prevent border cut on horizon themes

packages/website/docs/play.md, packages/website/package.json, packages/website/src/components/Editor/index.js, packages/website/src/components/Editor/index.module.css, yarn.lock
add splitter, make editor standalone
=> chore: improve playground

.github/workflows/ci-test-website.yaml, .github/workflows/deploy-website-on-push.yaml, .github/workflows/deploy-website-on-release.yaml, .github/workflows/deploy-website.yaml, package.json, packages/website/.env, packages/website/.env.latest, packages/website/docusaurus.config.ts, packages/website/package.json, yarn.lock
Define website baseUrl, based on the deployment type .
```ts
const getBaseURL = () => {
// localhost:3000
if (process.env.NODE_ENV === "development") {
return "";
}
// nightly deployment - https://sap.github.io/ui5-webcomponents/nightly
if (process.env.DEPLOYMENT_TYPE === "nightly") {
return "/ui5-webcomponents/nightly/";
}
// latest deployment - https://sap.github.io/ui5-webcomponents/
return "/ui5-webcomponents/";
};
```
=> chore: add deployment conig of website

docs/6-contributing/03-website.md
=> docs: update 03-website.md

docs/FAQ.md
=> docs: update FAQ.md

packages/website/src/components/Editor/index.js, packages/website/src/components/Editor/index.module.css, packages/website/src/css/custom.css
Styling of toolbar with the Share button are updated:
=> docs: prettify playground toolbar

packages/main/src/MultiComboBox.ts, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): pasting content should not be prevented

packages/website/src/components/HomepageFeatures/index.tsx, packages/website/src/components/HomepageTestimonials/index.tsx, packages/website/src/components/HomepageTestimonials/styles.css
=> docs: improve lighthouse score in a11y

packages/website/docs/_components_pages/main/Carousel.mdx, packages/website/docs/_samples/main/Carousel/ArrowsPlacement/ArrowsPlacement.md, packages/website/docs/_samples/main/Carousel/ArrowsPlacement/main.css, packages/website/docs/_samples/main/Carousel/ArrowsPlacement/main.js, packages/website/docs/_samples/main/Carousel/ArrowsPlacement/sample.html, packages/website/docs/_samples/main/Carousel/Cyclic/Cyclic.md, packages/website/docs/_samples/main/Carousel/Cyclic/main.css, packages/website/docs/_samples/main/Carousel/Cyclic/main.js, packages/website/docs/_samples/main/Carousel/Cyclic/sample.html, packages/website/docs/_samples/main/Carousel/MultipleItemsPerPage/sample.html, packages/website/docs/_samples/main/Carousel/PageIndicatorType/PageIndicatorType.md, packages/website/docs/_samples/main/Carousel/PageIndicatorType/main.css, packages/website/docs/_samples/main/Carousel/PageIndicatorType/main.js, packages/website/docs/_samples/main/Carousel/PageIndicatorType/sample.html, packages/website/package.json, packages/website/src/components/Editor/download.js, packages/website/src/components/Editor/index.js, packages/website/src/components/Editor/index.module.css, packages/website/src/components/Editor/sample/sample-package.js, packages/website/src/components/Editor/sample/sample-tsconfig.js, packages/website/src/css/custom.css, packages/website/src/pages/play.tsx, packages/website/tsconfig.json, yarn.lock
Let users download samples (an archive with all necessary files - index.html, main.ts, tsconfig, package.json, css files + vit dev server) ready to run.
After unzipping the archive, you can run these commands in the folder:
```bash
npm init
npm run dev
```
https://github.com/SAP/ui5-webcomponents/assets/15702139/8f38acd2-aae2-4dd1-9183-97c194443567
=> docs: introduce download of samples

packages/base/index.js
=> fix: wrong import in base package module index

packages/website/docusaurus.config.ts
=> docs: update docusaurus.config.ts legal links

packages/main/src/Tab.ts, packages/main/test/pages/TabContainer.html, packages/main/test/specs/TabContainer.spec.js
Related to https://github.com/SAP/ui5-webcomponents/pull/8265
=> fix(ui5-tab): focus() now works if dom ref in strip is not rendered yet 

packages/main/src/List.ts, packages/main/src/TabContainer.ts, packages/main/test/pages/ListDragAndDrop.html, packages/main/test/pages/TabContainerDragAndDrop.html, packages/main/test/specs/List.spec.js
=> feat(ui5-tabcontainer, ui5-list): automatically focus dropped element

packages/website/docs/_components_pages/main/Link.mdx
=> docs: update Link.mdx

packages/website/docs/_components_pages/main/Icon.mdx
'SAP Fiori Tools Icons' should be 'SAP Business Suite Icons'.
=> docs: fix typo in update Icon.mdx

packages/main/src/RadioButton.ts
=> refactor(ui5-radio-button): delete private strokeWidth getter

packages/main/src/themes/FileUploader.css
=> fix(ui5-file-uploader): adjust mouse cursor style

packages/website/src/components/Editor/index.js
save the playground state to local storage
=> docs: save project to localStorage on each key stroke

packages/main/src/themes/sap_belize/Button-parameters.css, packages/main/src/themes/sap_belize_hcb/Button-parameters.css, packages/main/src/themes/sap_belize_hcw/Button-parameters.css
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8480
=> fix(ui5-button): fix focus in belize

packages/main/src/Tab.ts, packages/main/src/TabContainer.ts, packages/main/test/pages/TabContainer.html, packages/main/test/specs/TabContainer.spec.js
Revert some logic from #8249
Fixes #8454
=> fix(ui5-tabcontainer): fix tab selection

packages/fiori/test/specs/UploadCollection.spec.js, packages/main/test/specs/ComboBox.spec.js, packages/main/test/specs/List.spec.js, packages/main/test/specs/TableGrouping.spec.js
Commented tests have been enabled for ComboBox, List, TableGrouping, and UploadCollection components. However, tests for MultiComboBox remain commented out until the issue at https://github.com/SAP/ui5-webcomponents/issues/8567 is resolved.
Related to: https://github.com/SAP/ui5-webcomponents/issues/3541
=> chore: enable comment tests

packages/main/src/features/InputSuggestions.ts
=> fix(ui5-input): prevent scroll on value state focus

docs/3-customizing/03-theme_part2.md
=> docs: update 03-theme_part2.md

docs/5-development/04-understanding-hbs-templates.md
=> docs: update 04-understanding-hbs-templates.md

docs/3-customizing/01-styles.md
=> docs: update 01-styles.md

packages/website/src/pages/index.tsx
Add banner to the landing page to make more consumers aware of 2.0
=> docs: add 2.0 banner to the landing page

packages/fiori/src/themes/FlexibleColumnLayout.css
=> fix(ui5-flexible-column-layout): improved separators borders

docs/2-advanced/09-ignore-custom-elements.md
=> docs: update 09-ignore-custom-elements.md

docs/2-advanced/07-accessibility.md
=> docs: update 07-accessibility.md

packages/main/test/specs/MultiInput.spec.js
temporary comment the failing test comited in #8655
=> fix(ui5-multi-input): fix failing popover test

packages/main/src/MultiInput.ts, packages/main/src/Tokenizer.ts, packages/main/test/specs/MultiInput.spec.js
=> fix(ui5-multi-input): prevent double value state message on nMore open

docs/2-advanced/08-scrollbars-customization.md
=> docs: update 08-scrollbars-customization.md

docs/5-development/07-typescript-in-UI5-Web-Components.md
=> docs: update 07-typescript-in-UI5-Web-Components.md

docs/6-contributing/06-storybook-samples.md
=> docs: update 06-storybook-samples.md

docs/6-contributing/04-website-samples.md
=> docs: update 04-website-samples.md

packages/main/src/themes/StepInput.css
=> fix(ui5-step-input): align the input vertically

packages/main/src/themes/MenuListItem.css
=> fix(ui5-menu): adjust active menu item text color

docs/Migrating to version 2.0 guide.md
Goal:
- consolidate the changes from the changelog per topic/component
- provide an easy to read table for each topic
Link: https://github.com/SAP/ui5-webcomponents/blob/migrating-2.0/docs/Migrating%20to%20version%202.0%20guide.md
=> chore: add a migration guide for 2.0

packages/main/test/pages/Text.html, packages/main/test/specs/Text.spec.js
=> test(ui5-text): add tests

packages/fiori/src/SideNavigation.ts
=> fix(ui5-side-navigation): import overflow icon

packages/main/src/Tab.ts, packages/main/src/TabContainer.ts, packages/main/src/TabSeparator.ts
Related to: https://github.com/SAP/ui5-webcomponents/issues/8698
=> fix(ui5-tabcontainer): replace default slot union type with interface

packages/base/src/util/clamp.ts
fix clamp function to handle case when max < min
Fixes #8580
=> fix(ui5-popover): fix popover going out of the viewport

packages/main/src/Popup.hbs, packages/main/src/Popup.ts, packages/main/src/PopupBlockLayer.hbs, packages/main/src/themes/Dialog.css, packages/main/src/themes/Popover.css, packages/main/src/themes/PopupBlockLayer.css, packages/main/src/themes/PopupsCommon.css, packages/main/test/pages/Dialog.html, packages/main/test/pages/styles/Dialog-photon.svg, packages/main/test/pages/styles/Dialog.css, packages/main/test/specs/Dialog.spec.js
block layer is no longer a popover
used `::backdrop` for background color
=> refactor(ui5-popup): simplify block layer logic

packages/main/src/themes/DayPicker.css, packages/main/src/themes/base/DayPicker-parameters.css, packages/main/src/themes/sap_horizon/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_dark/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_exp/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcb/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcw/DayPicker-parameters.css, packages/main/src/themes/sap_horizon_hcw_exp/DayPicker-parameters.css
=> fix(ui5-calendar, ui5-daterange-picker): align range selection styling with vd specification

packages/main/src/ResponsivePopover.hbs, packages/main/test/pages/ResponsivePopover.html, packages/main/test/specs/ResponsivePopover.mobile.spec.js
=> fix(ui5-responsive-popover): fix dialog initial focus

packages/main/src/themes/ProgressIndicator.css, packages/main/src/themes/base/ProgressIndicator-parameters.css, packages/main/src/themes/sap_horizon/ProgressIndicatorLayout-parameters.css, packages/main/src/themes/sap_horizon_exp/ProgressIndicatorLayout-parameters.css
Component padding reduced in case with hidden value.
=> fix(ui5-progress-indicator): hidden value design

packages/base/src/UI5Element.ts, packages/base/test/elements/Accessor.js, packages/base/test/elements/AccessorBase.js, packages/base/test/specs/Accessor.spec.js
=> fix(framework): Custom setter works when defined in base class and does not include HTMLElement props

docs/Migrating to version 2.0 guide.md
=> docs: update Migrating to version 2.0 guide.md

packages/main/src/SelectPopover.hbs
=> fix(ui5-select): options are now properly focused

packages/website/blog/2024/preparing-for-v2.mdx, packages/website/blog/releases/preparing-for-v2.mdx, packages/website/docusaurus.config.ts
Reuse the docusaurs way of displaying blogs
=> docs: setup blogs section

packages/main/src/MultiComboBox.ts, packages/main/test/specs/MultiComboBox.spec.js, packages/tools/components-package/wdio.js
=> fix(ui5-multi-combobox): remove value state header on validation reset

packages/main/src/SelectMenu.ts
=> fix(ui5-select-menu): prevent popover event bubbling

packages/fiori/src/UploadCollectionItem.ts
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8771
=> docs(ui5-upload-collection-item): improve uploadState property description

docs/Migrating to version 2.0 guide.md, packages/website/docs/_samples/main/SegmentedButton/SelectionModes/sample.html
The API of the SegmentedButton has been recently changed, but the oficial sample was not adapted
=> docs: fix SegmentedButton multiple selection sample

packages/main/src/types/IconMode.ts
The documentation for the IconMode enum has been updated to include more detailed explanations for each of its values.
=> docs(ui5-icon): update IconMode documentation

packages/main/src/Toolbar.ts, packages/main/test/pages/Toolbar.html, packages/main/test/specs/Toolbar.spec.js
=> fix(ui5-toolbar): prevent closing of overflow on interaction

docs/2-advanced/07-accessibility.md
=> docs: fixed incorrect links in accessibility section

docs/1-getting-started/06-using-features.md
Added info about F6 feature (how it works and its usage) and arranged other features description.
=> docs: enhance features

packages/main/src/StepInput.hbs, packages/main/src/StepInput.ts, packages/main/test/specs/StepInput.spec.js
=> fix(ui5-step-input): remove value rounding, apply value-state

packages/main/src/ComboBox.ts, packages/main/src/ComboBoxGroupItem.ts, packages/main/src/ComboBoxItem.ts, packages/main/src/ComboBoxPopover.hbs, packages/main/src/MultiComboBoxItem.ts, packages/main/test/pages/ComboBox.html, packages/main/test/specs/ComboBox.spec.js
=> fix(ui5-cb-item): return the DOM reference of the list item

packages/main/src/themes/sap_fiori_3_hcb/Tag-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/Tag-parameters.css, packages/main/src/themes/sap_horizon_hcb/Tag-parameters.css, packages/main/src/themes/sap_horizon_hcw/Tag-parameters.css
=> fix(ui5-tag): add colors for Quartz high contrast themes for Set 2

packages/main/src/NavigationMenu.ts
Downport of bcb3008187fb0e66d7ddeb6bb048857382d414a2
=> fix(ui5-side-navigation): overflow menu items are now displayed (#8948)

packages/main/src/ColorPalettePopover.ts, packages/main/src/Menu.ts, packages/main/src/Popover.ts, packages/main/src/Select.ts, packages/main/src/Tokenizer.ts
=> docs: more detailed explanation of opener attribute

packages/main/src/popup-utils/PopoverRegistry.ts, packages/main/test/pages/Popover.html, packages/main/test/specs/Popover.spec.js
=> fix(ui5-popover): fix auto close when click on iframe inside a shadow root

docs/2-advanced/07-accessibility.md
=> docs: update accessibility documentation

packages/main/src/types/InputType.ts, packages/main/test/pages/Input.html
Additional "Search" type added to the input types. 
FIXES: #7641
=> feat(ui5-input): add input type search

packages/main/src/themes/Popup.css
Fixes https://github.com/SAP/ui5-webcomponents/issues/8988
=> fix(ui5-popover): correct placement in RTL direction

packages/main/src/Button.ts, packages/main/test/specs/Button.spec.js
=> fix(ui5-button): add keyboard shortcut to cancel the button's action 

packages/website/docs/_components_pages/main/Dialog.mdx, packages/website/docs/_samples/compat/Table/ActiveRows/main.js, packages/website/docs/_samples/compat/Table/ActiveRows/sample.html, packages/website/docs/_samples/compat/Table/Basic/main.js, packages/website/docs/_samples/compat/Table/Basic/sample.html, packages/website/docs/_samples/compat/Table/Grouping/main.js, packages/website/docs/_samples/compat/Table/Grouping/sample.html, packages/website/docs/_samples/compat/Table/GrowingOnButtonPress/main.js, packages/website/docs/_samples/compat/Table/GrowingOnButtonPress/sample.html, packages/website/docs/_samples/compat/Table/GrowingOnScroll/main.js, packages/website/docs/_samples/compat/Table/GrowingOnScroll/sample.html, packages/website/docs/_samples/compat/Table/MultipleSelection/main.js, packages/website/docs/_samples/compat/Table/MultipleSelection/sample.html, packages/website/docs/_samples/compat/Table/NoData/main.js, packages/website/docs/_samples/compat/Table/NoData/sample.html, packages/website/docs/_samples/compat/Table/Popin/main.js, packages/website/docs/_samples/compat/Table/Popin/sample.html, packages/website/docs/_samples/compat/Table/SingleSelection/main.js, packages/website/docs/_samples/compat/Table/SingleSelection/sample.html, packages/website/docs/_samples/compat/Table/StickyHeader/main.js, packages/website/docs/_samples/compat/Table/StickyHeader/sample.html, packages/website/docs/_samples/main/Card/MoreCards/main.js, packages/website/docs/_samples/main/Card/MoreCards/sample.html, packages/website/docs/_samples/main/Card/WithTable/main.js, packages/website/docs/_samples/main/Card/WithTable/sample.html, packages/website/docs/_samples/main/Dialog/WithState/main.js, packages/website/docs/_samples/main/Dialog/WithState/sample.html
update samples to use ui5-text to get the proper styling, font
=> chore: use ui5-text instead of plain spans in website samples

packages/main/src/Popover.ts, packages/main/test/pages/Popover.html, packages/main/test/pages/styles/Popover.css, packages/main/test/specs/Popover.spec.js
Fixes https://github.com/SAP/ui5-webcomponents/issues/8981
=> fix(ui5-popover): prevent runtime error when opener is outside the viewport

packages/main/src/MultiInput.ts, packages/main/test/specs/MultiInput.spec.js
=> fix(ui5-multi-input): delete selected value on BACKSPACE

packages/main/test/pages/Panel.html, packages/main/test/specs/Panel.spec.js
=> fix(ui5-panel): fix failing tests

docs/Migrating to version 2.0 guide.md, packages/fiori/src/NotificationListGroupItem.hbs, packages/fiori/src/NotificationListGroupItem.ts, packages/fiori/src/i18n/messagebundle.properties, packages/fiori/test/pages/NotificationListGroupItem.html, packages/fiori/test/pages/NotificationListItem.html, packages/fiori/test/specs/NotificationList.spec.js
- enhance the tooltip of the expand/collapse icon in the group header
- add "Breaking 2.0 change" information to the Migration guide
- enhance test pages
=> feat(ui5-li-notification-group): enhance 'Expand'/'Collapse' tooltip

packages/main/test/specs/DatePicker.spec.js
=> fix(ui5-date-picker): adjust failing tests

packages/main/src/Option.ts
Added necessary `desktop` attribute to `ui5-option` in order to enable focus styling.
=> chore(ui5-option): focus update

packages/main/src/themes/sap_belize/Switch-parameters.css, packages/main/src/themes/sap_belize/parameters-bundle.css
In internal communication,  style changes were requested.
=> fix(ui5-switch): align styles to design

packages/main/test/specs/Popover.spec.js
=> chore(ui5-popover): remove unstable test

packages/main/src/MonthPicker.hbs, packages/main/src/YearPicker.hbs
=> fix(ui5-calendar): adjust accessibility semantics

packages/main/src/themes/TimePicker.css
=> fix(ui5-time-picker): remove box shadow

packages/base/src/util/dragAndDrop/DragRegistry.ts, packages/main/src/ListItem.ts, packages/main/src/TabContainer.ts, packages/main/test/pages/DragAndDropGeneric.html, packages/main/test/pages/styles/DragAndDropGeneric.css
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9131
=> fix(framework): set dataTransfer.effectAllowed only for UI5 elements

packages/fiori/src/NotificationList.ts, packages/fiori/src/themes/NotificationList.css
As block element notification list can have width/height
=> fix(ui5-notification-list): change host to display:block

packages/website/blog/releases/announcing-rc-v2.mdx
Update announcing-rc-v2.mdx blog with the latest rc version links.
=> chore: update announcing-rc-v2.mdx blog

packages/main/src/Button.ts, packages/main/test/specs/Button.spec.js
=> fix(ui5-button): add keyboard shortcut to cancel the button's action

packages/main/src/StepInput.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/9119
=> fix(ui5-step-input): check for inner input before using value

packages/fiori/src/ShellBarPopover.hbs
Fixes: https://github.com/SAP/ui5-webcomponents/issues/5885
=> fix(ui5-shellbar): add tooltip for shellbar items

packages/website/docs/_samples/ai/PromptInput/Basic/sample.html
Fix small typo in the basic sample: 'Ask my anything...' --> 'Ask me anything...'.
=> chore: fix sample

packages/main/test/specs/DatePicker.spec.js
=> fix(ui5-date-picker): adjust unstable tests

packages/main/src/Button.hbs, packages/main/src/Button.ts, packages/main/test/specs/Button.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8976
=> fix(ui5-button): adjust screen reader announcement order (#8997)

packages/main/src/StepInput.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/9119
=> fix(ui5-step-input): check input before accessing value

packages/main/test/specs/TableLoading.spec.js
- add a timeout to prevent unstable test execution
Fixes: #9250
=> fix(ui5-table): adjust unstable loading test

docs/DoD.md
The goal of this document is to provide component developers with a **short** list the most common issues found in code reviews.
You can read the Definition of Done here: https://github.com/SAP/ui5-webcomponents/blob/dod/docs/DoD.md
=> docs: add Definition of Done

packages/main/src/List.ts
Fixed a bug where the list items are not properly updated initially.
Fixes: #9266
=> fix(ui5-list): improved items initial rendering

packages/website/docs/_samples/main/DateTimePicker/DateTimePickerInDifferentTimezone/main.js, packages/website/docs/_samples/main/DateTimePicker/DateTimePickerInDifferentTimezone/sample.html
Improve the time zones sample by adding a select that provides an option to select a specific time zone that you want the control to work with.
=> docs(ui5-datetime-picker): improve time zones sample

packages/main/src/Calendar.ts, packages/main/src/Menu.ts
=> fix(ui5-calendar): add icon dependency

packages/main/src/Table.ts
Arrow function should not return assignment no-return-assign
=> fix(ui5-table): lint issue is fixed

packages/fiori/test/pages/uploadCollectionScript.js, packages/main/src/themes/Tag.css, packages/main/src/themes/base/Tag-parameters.css, packages/main/src/themes/sap_fiori_3/Tag-parameters.css, packages/main/src/themes/sap_fiori_3/parameters-bundle.css, packages/main/test/pages/Dialog.html, packages/main/test/pages/Tag.html, packages/main/test/pages/Tag.js
- Tag test page
- Information tag styles in Fiori_3
- Set1 and Set2 tag default hover style
- UploadCollection test page
- Dialog test page
=> fix(ui5-tag): fix styling issues

packages/main/src/Calendar.hbs, packages/main/src/Calendar.ts, packages/main/test/specs/Calendar.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9107
=> fix(ui5-calendar): adjust year button visibility

packages/tools/package.json, yarn.lock
Attempt to resolve https://github.com/SAP/ui5-webcomponents/issues/8824
=> chore: bump chokidar version

packages/main/test/pages/RatingIndicator.html
Remove duplicate controls from Rating Indicator test page
=> fix(ui5-rating-indicator): fix test page - remove duplicates

packages/fiori/src/themes/DynamicPage.css, packages/fiori/src/themes/DynamicPageHeaderActions.css
=> fix(dynamic-page): some remarks fixed

packages/create-package/template/src/MyFirstComponent.ts
validator `Integer` is no longer used -> `type: Number`
=> chore: update create-webc-package template

packages/fiori/test/specs/NotificationList.spec.js
=> fix(ui5-notification-list): fixed show more test

packages/website/blog/releases/announcing-v2.mdx
Adjust the blog post to reflect the correct publication date.
=> docs: update announcing-v2.mdx

packages/main/src/TextArea.ts, packages/main/src/TextAreaPopover.hbs, packages/main/test/pages/TextArea.html, packages/main/test/specs/TextArea.cy.js
=> fix(ui5-textarea): remove the cloning of the value state message

packages/fiori/src/NotificationListGroupList.ts
Fixes https://github.com/SAP/ui5-webcomponents/issues/9360
=> fix(ui5-li-notification-group): suspend nested item navigation

packages/base/package.json, packages/localization/package.json, yarn.lock
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9430
=> chore: update `@openui5/sap.ui.core` dep to `1.120.17`

packages/main/src/MultiComboBox.ts, packages/main/test/specs/MultiComboBox.mobile.spec.js
=> fix(ui5-multi-combobox): collapse the tokenizer on mobile devices

packages/fiori/src/FlexibleColumnLayout.ts, packages/fiori/src/themes/FlexibleColumnLayout.css
=> fix(ui5-flexible-column-layout): correct separator visualization

packages/website/docs/_samples/fiori/NotificationList/GroupItems/sample.html
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9370
=> docs(ui5-notification-list): set sample with group items height to 500px

packages/main/src/ComboBox.ts, packages/main/src/DatePicker.ts, packages/main/src/FileUploader.ts, packages/main/src/Input.ts, packages/main/src/MultiComboBox.ts, packages/main/src/RatingIndicator.ts, packages/main/src/Select.ts, packages/main/src/StepInput.ts, packages/main/src/TextArea.ts, packages/main/src/TimePicker.ts
=> fix(ui5-combobox): correct valueStateMessage documentation

packages/fiori/src/Wizard.ts, packages/fiori/src/themes/WizardTab.css, packages/fiori/test/specs/Wizard.spec.js
=> fix(ui5-wizard): disabled steps are no longer clickable

packages/main/test/specs/Toolbar.spec.js
=> fix(ui5-toolbar): failing test fixed

packages/main/test/pages/Input.html, packages/main/test/pages/Input_quickview.html, packages/main/test/pages/InputsLazyLoading.html, packages/main/test/pages/MultiInput.html
=> fix(ui5-input, ui5-multi-input): fix issues in inputs test pages

packages/main/src/Input.hbs, packages/main/src/Input.ts, packages/main/test/pages/Input.html, packages/main/test/specs/Input.spec.js
=> feat(ui5-input): expose select event

packages/main/src/Card.hbs, packages/main/src/Card.ts, packages/main/src/themes/Card.css, packages/main/test/pages/Card.html, packages/main/test/specs/Card.spec.js
=> feat(ui5-card): add properties loading and loadingDelay

packages/base/src/FeaturesRegistry.ts, packages/base/src/UI5Element.ts, packages/base/src/UI5ElementMetadata.ts, packages/base/src/decorators/customElement.ts, packages/main/src/Input.hbs, packages/main/src/Input.ts, packages/main/src/InputPopover.hbs, packages/main/src/features/InputSuggestions.ts
This reverts commit 74a8a4c1c2547f528c7ae40a83b752e35b352517.
=> Revert "chore: fix features loading"

packages/main/src/themes/MultiComboBoxPopover.css
=> fix(ui5-multi-combobox): add background color to select all

packages/ai/src/Button.ts, packages/ai/src/ButtonState.ts, packages/main/src/CalendarDateRange.ts, packages/main/src/MenuSeparator.ts, packages/main/src/MultiComboBoxItemGroup.ts, packages/main/src/Table.ts, packages/main/src/TableCell.ts, packages/main/src/TableCellBase.ts, packages/main/src/TableGrowing.ts, packages/main/src/TableHeaderCell.ts, packages/main/src/TableHeaderRow.ts, packages/main/src/TableRow.ts, packages/main/src/TableRowBase.ts, packages/main/src/TableSelection.ts, packages/main/src/TimePicker.ts, packages/website/build-scripts/api-reference-generation/component-file.mjs, packages/website/src/css/custom.css, packages/website/src/theme/DocItem/Content/index.js, packages/website/src/theme/DocSidebar/Desktop/Content/index.js, packages/website/src/theme/DocSidebar/Desktop/Content/styles.module.css, packages/website/src/theme/DocSidebar/Input/index.js, packages/website/src/theme/DocSidebar/Mobile/index.js, packages/website/src/theme/DocSidebar/filter.util.js, packages/website/src/theme/DocSidebarItem/Category/index.js
Additional information for since / tag of the component is not displayed in category cards as broken strings.
In addition, sidebar filter is added.
=> docs: playground enhancements

packages/main/src/themes/base/sizes-parameters.css, packages/main/src/themes/sap_fiori_3/Token-parameters.css, packages/main/src/themes/sap_fiori_3_dark/Token-parameters.css
adjust token icon size according to the new accessibility standard
=> feat(ui5-token): adjust token icon size according to the new accessibility standard

packages/theming/package.json, yarn.lock
Update theming-base-content фром 11.12.0 to 11.17.1
=> feat(theming): update theming-base-content to 11.17.1

packages/main/src/DatePicker.ts, packages/main/src/DatePickerPopover.hbs, packages/main/src/DateTimePickerPopover.hbs, packages/main/test/specs/DatePicker.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9217
=> fix(ui5-date-picker): adjust timestamp

packages/fiori/src/DynamicPageTitle.hbs, packages/fiori/src/DynamicPageTitle.ts
=> fix(ui5-dynamic-page-title): separator fixed

packages/base/src/Runtimes.ts
Enhance runtime information stored inside shared resources. This will be helpful in debugging MFE scenarios.
=> chore: enhance runtime information

packages/main/src/Dialog.hbs, packages/main/src/themes/Dialog.css, packages/main/src/themes/base/Dialog-parameters.css, packages/main/src/themes/sap_horizon/Dialog-parameters.css, packages/main/src/themes/sap_horizon_dark/Dialog-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/Dialog-parameters.css, packages/main/src/themes/sap_horizon_exp/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcb/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/parameters-bundle.css, packages/main/src/themes/sap_horizon_hcw/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcw_exp/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcw_exp/parameters-bundle.css
=> feat(ui5-dialog): increase resize handle size

packages/fiori/src/DynamicSideContent.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/9462
=> fix(ui5-dynamic-side-content): retrieve correct width

packages/fiori/src/WizardTab.hbs, packages/main/src/ComboBox.hbs, packages/main/src/ComboBox.ts, packages/main/src/ComboBoxPopover.hbs, packages/main/src/MultiComboBox.hbs, packages/main/src/MultiComboBox.ts, packages/main/src/MultiComboBoxPopover.hbs, packages/main/src/MultiInput.hbs, packages/main/src/MultiInput.ts, packages/main/src/RangeSlider.hbs, packages/main/src/Slider.hbs, packages/main/src/i18n/messagebundle.properties, packages/main/test/specs/ComboBox.spec.js, packages/main/test/specs/MultiComboBox.spec.js
This change improves the coverage of the accessibility automation tests in the team scope.
=> chore(ui5-combobox, ui5-multi-combobox, ui5-wizard, ui5-multiinput, ui5-slider, ui5-range-slider): accessibility improvements

packages/main/src/themes/SplitButton.css
=> fix(ui5-split-button): adjust arrow part width

packages/main/src/Breadcrumbs.ts
=> fix(ui5-breadcrumbs): redundant import removed

packages/main/src/Input.ts, packages/main/test/specs/Input.spec.js
=> fix(ui5-input): reset value on when set to null

packages/fiori/src/themes/ShellBar.css
=> fix(ui5-shellbar): buttons now have equal styles

packages/main/src/themes/TimePicker.css
=> fix(ui5-time-picker): adjust height in compact mode

packages/website/build-scripts/icons-generation/index.mjs, packages/website/docusaurus.config.ts, packages/website/package.json, packages/website/src/components/Editor/index.js
=> docs: serve samples for released version from jsdelivr

packages/main/src/TimePicker.ts, packages/main/src/TimePickerPopover.hbs
fixes: https://github.com/SAP/ui5-webcomponents/issues/9705
=> fix(ui5-timepicker): allow inputs popover on tablet

packages/main/src/Popup.ts, packages/main/test/pages/DialogInitiallyOpen.html, packages/main/test/specs/Dialog.spec.js
=> fix(ui5-dialog): fix block layer of initially opened dialog 

packages/main/src/DayPicker.ts, packages/main/src/MonthPicker.hbs, packages/main/src/MonthPicker.ts, packages/main/src/YearPicker.hbs, packages/main/src/YearPicker.ts
=> fix(ui5-calendar): adjust aria-disabled attribute

packages/fiori/src/Wizard.hbs
=> fix(ui5-wizard): improve accessibility

packages/main/src/DayPicker.ts, packages/main/src/MonthPicker.hbs, packages/main/src/MonthPicker.ts, packages/main/src/YearPicker.hbs, packages/main/src/YearPicker.ts
=> fix(ui5-calendar): adjust aria-disabled attribute (#9732)

packages/compat/src/themes/base/Table-parameters.css, packages/compat/src/themes/base/sizes-parameters.css, packages/compat/src/themes/sap_horizon_hcb/Table-parameters.css, packages/compat/src/themes/sap_horizon_hcw/Table-parameters.css
=> fix(ui5-table): fix border and focus overlap (compat)

packages/website/src/components/Editor/playground-support.js
=> docs: fix compat table samples theming

packages/main/src/MultiComboBox.ts, packages/main/test/pages/MultiComboBox.html, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): remove VS header after setting VH to None

packages/base/package.json, packages/fiori/package.json, packages/localization/package.json, packages/main/package.json, packages/main/src/themes/base/Table-parameters.css, packages/main/src/themes/base/sizes-parameters.css, packages/main/src/themes/sap_horizon_hcb/Table-parameters.css, packages/main/src/themes/sap_horizon_hcw/Table-parameters.css, yarn.lock
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9526
=> fix(ui5-table): fix border and focus overlap

packages/localization/lib/copy-and-strip-cldr/index.js
=> chore: do not strip languages from CLDR assets

packages/compat/src/Table.hbs, packages/compat/src/Table.ts, packages/compat/src/themes/Table.css, packages/compat/test/pages/TableGrowingWithButton.html
=> fix(ui5-table): busy indicator overlay (compat)

packages/main/src/Table.hbs, packages/main/src/Table.ts, packages/main/src/themes/Table.css, packages/main/test/pages/TableGrowingWithButton.html
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9438
=> fix(ui5-table): busy indicator overlay

packages/fiori/src/Wizard.hbs, packages/fiori/src/Wizard.ts, packages/fiori/src/WizardTab.hbs, packages/fiori/src/WizardTab.ts, packages/fiori/test/specs/Wizard.spec.js
=> fix(ui5-wizard): improve focus and keyboard handling

packages/main/test/pages/CalendarLegend.html
Fixate the date, as some months are not filled correctly with special dates
=> chore(ui5-calendar-legend): fix unstable test

packages/main/src/ColorPicker.ts, packages/main/test/specs/ColorPicker.spec.js
=> fix(ui5-color-picker): adjust hue slider update

packages/main/test/specs/DatePicker.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/5203
=> fix(ui5-date-picker): uncomment failing test

packages/website/docs/_samples/main/SegmentedButton/Basic/sample.html, packages/website/docs/_samples/main/SegmentedButton/SelectionModes/sample.html
=> fix(ui5-segmented-button): add accessible name in the sample

packages/website/build-scripts/icons-generation/index.mjs
Fixes https://github.com/SAP/ui5-webcomponents/issues/9804
=> chore(website): properly resolve path on Windows

packages/main/src/Popover.ts, packages/main/src/types/PopoverVerticalAlign.ts, packages/main/test/pages/Popover.html
Popover should recieve the height of the opener if vertical-align=stretch and placment=start / end.
FIXES: #9552
=> fix(ui5-popover): adjust heigh when vertical-align=stretch

packages/website/docusaurus.config.ts
add a version parameter to algolia config from docusaurus so results are filtered to the current version
=> docs: add versioned search

packages/main/src/themes/Popover.css
=> fix(ui5-popover): fix arrow placement

packages/main/src/themes/Popover.css
=> fix(ui5-popover): fix arrow placement 

packages/main/src/Popover.ts, packages/main/test/pages/Popover.html
=> fix(ui5-popover): adjust height when vertical-align=stretch

packages/main/src/MultiComboBox.ts, packages/main/test/specs/MultiComboBox.spec.js
the token count is now updated correctly after each token deletion
fixes: #9778
=> fix(ui5-multi-combobox): fix aria-describedby token count

packages/main/cypress/specs/base/AriaLabelHelper.cy.ts, packages/main/cypress/specs/base/IconCollection.cy.ts
=> chore: cleanup Cypress tests

packages/main/test/pageobjects/TabContainerTestPage.js
Fixes https://github.com/SAP/ui5-webcomponents/issues/9879
=> test(ui5-tabcontainer): stabilize test

packages/fiori/src/themes/NotificationListGroupItem.css, packages/fiori/src/themes/base/NotificationListItem-parameters.css, packages/fiori/src/themes/sap_horizon/NotificationListItem-parameters.css, packages/fiori/src/themes/sap_horizon_dark/NotificationListItem-parameters.css, packages/fiori/src/themes/sap_horizon_hcb/NotificationListItem-parameters.css, packages/fiori/src/themes/sap_horizon_hcw/NotificationListItem-parameters.css
Fixed Fiori 3 themes and sticky header small moving. 
BGSOFUIRODOPI-3231
=> chore(ui5-notification-list): fix minor styling issues

packages/website/docs/components/patterns/AI Custom Prompt/AI Custom Prompt.mdx, packages/website/docs/components/patterns/AI Custom Prompt/Level 1/Level 1.md, packages/website/docs/components/patterns/AI Custom Prompt/Level 1/main.css, packages/website/docs/components/patterns/AI Custom Prompt/Level 1/main.js, packages/website/docs/components/patterns/AI Custom Prompt/Level 1/sample.html, packages/website/docs/components/patterns/AI Custom Prompt/Level 2/Level 2.md, packages/website/docs/components/patterns/AI Custom Prompt/Level 2/main.css, packages/website/docs/components/patterns/AI Custom Prompt/Level 2/main.js, packages/website/docs/components/patterns/AI Custom Prompt/Level 2/sample.html, packages/website/docs/components/patterns/AI Custom Prompt/Level 3/Level 3.md, packages/website/docs/components/patterns/AI Custom Prompt/Level 3/main.css, packages/website/docs/components/patterns/AI Custom Prompt/Level 3/main.js, packages/website/docs/components/patterns/AI Custom Prompt/Level 3/sample.html, packages/website/docs/components/patterns/AI Custom Prompt/Level 4/Level 4.md, packages/website/docs/components/patterns/AI Custom Prompt/Level 4/main.css, packages/website/docs/components/patterns/AI Custom Prompt/Level 4/main.js, packages/website/docs/components/patterns/AI Custom Prompt/Level 4/sample.html
Adding samples for web component, showcasing a Custom Prompt pattern usage.
=> chore: add custom prompt pattern samples

CONTRIBUTING.md
Reference GenAI contribution guidelines in CONTRIBUTING.md file as per Open Source Program Office recommendation.
=> chore: add GenAI contribution guidelines in CONTRIBUTING.md

packages/main/src/Menu.ts
=> fix(ui5-menu): adjust loading items display

packages/main/src/features/InputSuggestions.ts, packages/main/test/specs/Input.spec.js
=> fix(ui5-input): arrow up scrolls the suggestion items when item is behind value state header

packages/fiori/src/Page.ts
=> fix(ui5-page): correct noScrolling documentation

packages/main/src/Slider.hbs, packages/main/test/specs/Slider.spec.js
=> fix(ui5-slider): correct icon name

packages/main/src/Form.ts
The Form web component is a layout, it isn't a replacement for the `form` HTML element. The Form web component does not provide any APIs for form submission
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9891
=> docs: enhance Form docs

packages/main/src/Input.ts, packages/main/test/pages/Input.html, packages/main/test/specs/Input.spec.js
=> feat(ui5-input): enable preventing input event

packages/website/docs/_samples/patterns/AIAcknowledgement/Basic/Basic.md, packages/website/docs/_samples/patterns/AIAcknowledgement/Basic/main.js, packages/website/docs/_samples/patterns/AIAcknowledgement/Basic/sample.html, packages/website/docs/components/patterns/AI Acknowledgement.mdx
Adding a sample, showcasing the **AI Acknowledgment** pattern and its usage.
=> chore: add ai acknowledgment pattern sample

packages/main/src/DayPicker.ts
=> fix(ui5-daypicker): announce selected state change

packages/main/src/Popup.hbs
=> fix(ui5-popup): add role attribute to focus helper element

packages/website/docs/components/patterns/AI QuickPrompt/AI QuickPrompt.md
Previously we didn't have an **Overview** section to help users better understand the purpose of our AI Quick Prompt pattern.
With this change we add Overview section, helping the users to understand better its purpose.
=> docs: add overview section to sample

packages/main/src/themes/SliderBase.css, packages/main/src/themes/base/sizes-parameters.css, packages/main/src/themes/sap_fiori_3/SliderBase-parameters.css, packages/main/src/themes/sap_fiori_3/sizes-parameters.css, packages/main/src/themes/sap_fiori_3_dark/SliderBase-parameters.css, packages/main/src/themes/sap_fiori_3_dark/sizes-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/sizes-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/sizes-parameters.css, packages/main/src/themes/sap_horizon_hcb/SliderBase-parameters.css, packages/main/src/themes/sap_horizon_hcw/SliderBase-parameters.css
=> fix(ui5-slider, ui5-range-slider): adjust styles according to Fiori specs

packages/fiori/test/pages/styles/NotificationListGroupItem.css, packages/website/docs/_samples/fiori/NotificationList/InShellBar/main.css
=> fix(ui5-notification-list): fix header bar visibility

packages/ai/test/pages/Button.html, packages/website/docs/_samples/ai/Button/ButtonMenu/sample.html, packages/website/docs/_samples/ai/Button/IconOnlyButton/sample.html, packages/website/docs/_samples/patterns/AIGuidedPrompt/Dialog/sample.html, packages/website/docs/_samples/patterns/AIGuidedPrompt/DynamicSideContent/sample.html, packages/website/docs/_samples/patterns/AIGuidedPrompt/Popover/sample.html, packages/website/docs/components/patterns/AI CustomPrompt/Level 3/sample.html, packages/website/docs/components/patterns/AI CustomPrompt/Level 4/sample.html, packages/website/docs/components/patterns/AI QuickPrompt/sample.html
Updating text in AI patterns and samples for better readability and flow:
- Changed `Stop Generation` to `Stop Generating`
- Changed `Text Length` to `Adjust Length`
- Changed `Text Length` sub menu titles from `Short` / `Medium` / `Long` to `Shorten text` and `Lengthen text`
=> docs(ai-button): improve readability in samples

packages/main/cypress/specs/Menu.cy.ts, packages/main/cypress/support/commands/Menu.commands.ts
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10070
=> chore: stabilize tests

docs/6-migration-guides/01-to-version-2.md
=> docs(ui5-suggestion-item): fix migration guide section

docs/FAQ.md
Fix typo (speps-->steps) in FAQ.md
=> chore: fix typo in FAQ.md

packages/website/docs/_components_pages/main/TabContainer/TabContainer.mdx, packages/website/docs/_samples/main/TabContainer/TransparentDesign/TransparentDesign.md, packages/website/docs/_samples/main/TabContainer/TransparentDesign/main.js, packages/website/docs/_samples/main/TabContainer/TransparentDesign/sample.html
=> docs(ui5-tabcontainer): add sample for transparent design

packages/main/src/themes/sap_fiori_3_hcb/Badge-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/Badge-parameters.css
Fixes: #10052
downport of #8952
=> fix(ui5-badge): correct parameters for Color Set 2 in high contrast themes

packages/fiori/src/ShellBar.hbs, packages/fiori/src/ShellBar.ts
Arrow navigation is added for the `ui5-shellbar`
=> feat(ui5-shellbar): added arrow navigation

packages/fiori/src/ShellBar.hbs, packages/fiori/src/ShellBar.ts, packages/fiori/src/themes/ShellBar.css
Separators added, some spacings aligned to spec
=> Add shellbar additional context separators

packages/main/src/themes/SegmentedButton.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/10112
=> fix(ui5-segmented-button): remove overstyling when disabled and pressed)

packages/main/src/CardHeader.ts
Fixes https://github.com/SAP/ui5-webcomponents/issues/10132
=> fix(ui5-card-header): update interactive property documentation

packages/website/docs/components/patterns/AI CustomPrompt/Level 4/main.js
=> docs(ui5-ai-custom-prompt): spelling mistake fixed in level 4

packages/main/src/List.ts
=>  fix(ui5-list): load-more no longer fired on initial mount

packages/fiori/src/ShellBar.hbs, packages/fiori/src/ShellBar.ts, packages/fiori/src/i18n/messagebundle.properties
Screen reader support is added for the `ui5-shellbar`
=> feat(ui5-shellbar): add screen reader support

packages/fiori/src/ShellBar.ts, packages/fiori/test/pages/ShellBar_evolution.html
Event thrown when element inside additional context area changes its visibility
=> chore(ui5-shellbar): additional context event

packages/ai/test/pages/Button.html, packages/website/docs/_samples/patterns/AIAcknowledgement/Basic/sample.html, packages/website/docs/components/patterns/AI QuickPrompt/main.js, packages/website/docs/components/patterns/AI QuickPrompt/sample.html
With this change we're improving the content of the AI Acknowledgment and AI Quick Prompt patterns.
```diff
In the Rewrite Text submenu
- Summarise
+ Summarize
Error message:
- Spelling or grammar issues found, please try again!
+ Something went wrong during the generation process. Please try again.
Option:
- Fix Spelling & Grammar
+ Fix Spelling and Grammar
```
```diff
+ Cancel Button
+ New Boilerplate message
+ Explicit clarification about what "AI" abbreviation is.
```
=> docs: apply feedback comments for ai patterns' contents

packages/main/cypress/specs/Input.cy.ts, packages/main/src/Input.ts
=> fix(ui5-input): set value after preventDefault of input event

packages/fiori/src/ShellBar.ts, packages/fiori/src/themes/ShellBar.css
=> fix(ui5-shellbar): visual spec alignments

packages/fiori/src/WizardTab.hbs, packages/fiori/test/pages/Wizard.html
FIXES: https://github.com/SAP/ui5-webcomponents/issues/9779
The solution: Added if statement that checks if there is subtitle-text attribute, so it is not rendered when not needed.
=> fix(ui5-wizard): stacked Wizard Steps are aligned properly

docs/1-getting-started/01-first-steps.md
Some IDE require manual enablement of code autocompletion. With this PR steps about how to enable autocompletion are described.
=> docs: describe how to enable autocompletion

packages/main/cypress/specs/RatingIndicator.cy.ts, packages/main/src/RatingIndicator.hbs, packages/main/src/RatingIndicator.ts
=> fix(ui5-rating-indicator): correct half icon appearance

packages/main/src/themes/Tag.css, packages/main/src/themes/base/Tag-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/Tag-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/Tag-parameters.css, packages/main/src/themes/sap_horizon_dark/Tag-parameters.css, packages/main/src/themes/sap_horizon_hcb/Tag-parameters.css, packages/main/src/themes/sap_horizon_hcw/Tag-parameters.css
=> fix(ui5-tag): correct hover background color for Set 2 Color Scheme 9

packages/main/src/Bar.hbs, packages/main/src/Bar.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/10101
=> feat(ui5-bar): add shadow parts

packages/main/src/Popover.ts, packages/main/test/pages/PopoverInitiallyOpen.html
=> chore(ui5-popover): remove unwanted console warning

packages/main/src/Icon.ts
=> docs(ui5-icon): fix typo

packages/main/cypress/specs/StepInput.cy.ts, packages/main/src/StepInput.hbs, packages/main/src/StepInput.ts, packages/main/test/pages/StepInput.html
fixes: https://github.com/SAP/ui5-webcomponents/issues/5177
=> feat(ui5-step-input): add input event

packages/main/src/Breadcrumbs.ts, packages/main/src/BreadcrumbsPopover.hbs, packages/main/src/i18n/messagebundle.properties, packages/main/test/specs/Breadcrumbs.spec.js
=> fix(ui5-breadcrumbs): accessible name of popover

packages/main/src/Popover.ts, packages/main/test/pages/PopoverInitiallyOpen.html, packages/main/test/specs/Popover.spec.js
=> fix(ui5-popover): fix finding opener when popover is not in the DOM

packages/main/src/CalendarLegend.hbs, packages/main/src/CalendarLegend.ts, packages/main/src/CalendarLegendItem.hbs, packages/main/src/i18n/messagebundle.properties, packages/main/src/themes/CalendarLegendItem.css
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10298
=> fix(ui5-calendar-legend): add accessibility semantics

packages/main/cypress/specs/Input.cy.ts, packages/main/src/Input.ts, packages/main/src/ListItemBase.ts, packages/main/src/SuggestionItem.hbs, packages/main/src/SuggestionItem.ts, packages/main/src/SuggestionItemCustom.hbs, packages/main/src/SuggestionItemCustom.ts
=> fix(ui5-input): remove initial tabindex 0 from suggestions

packages/main/src/Popover.ts, packages/main/src/themes/base/rtl-parameters.css, packages/main/test/pages/Popover.html, packages/main/test/pages/PopoverRTL.html, packages/main/test/pages/styles/Popover.css
downport of #10293
fixes #9966
=> fix(ui5-popover): fix arrow position in RTL direction

packages/main/src/Table.hbs, packages/main/src/themes/Table.css, packages/main/src/themes/TableHeaderRow.css, packages/main/src/themes/TableRowBase.css, packages/main/src/themes/base/Table-parameters.css, packages/main/test/specs/Table.spec.js
=> fix(ui5-table-row): add left and right borders

.github/actions/mergeReleaseChangelog.mjs
Updates the release notes to show features first and fixes - second.
=> chore: updates release notes generation show features first, fixes - second

packages/main/src/List.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/10120
=> fix(ui5-list): stop tab index change propagation

packages/main/src/Popover.ts, packages/main/test/pages/PopoverInitiallyOpen.html, packages/main/test/specs/Popover.spec.js
=> fix(ui5-popover): fix finding opener

packages/main/cypress/specs/List.cy.ts
=> chore(ui5-list): stabilize unstable list tests

packages/main/src/ExpandableText.ts, packages/main/src/TimePickerClockTemplate.tsx, packages/main/src/themes/TimePickerClock.css
Fixed one scoping issue.
Note: `data-ui5-label` is a false positive. It would be best to rework the scoping linter instead of fixing it now, so I just reverted it to how it was (`data-label`) before the TSX refactoring.
=> chore: scoping issues

packages/theming/package.json, yarn.lock
New theming variables, changelog: https://github.com/SAP/theming-base-content/releases/tag/11.24.0
=> feat: update theming-base-content

packages/main/src/Input.ts, packages/main/src/ListItemBase.ts, packages/main/src/SuggestionListItem.ts, packages/main/test/specs/Input.spec.js
=> fix(ui5-input): prevent setting tabindex to items

packages/fiori/cypress/specs/SideNavigation.cy.ts, packages/fiori/src/SideNavigationItemTemplate.tsx
=> fix(ui5-side-navigation): fix expand and collapse

packages/main/src/themes/base/Panel-parameters.css, packages/main/src/themes/sap_horizon/Panel-parameters.css, packages/main/src/themes/sap_horizon_dark/Panel-parameters.css
Update css parameters values with variables
=> chore(ui5-panel): update css variables

packages/fiori/src/NotificationListItem.ts
=> fix(ui5-notification-list-item): scoping issue

packages/fiori/src/SideNavigation.ts
=> fix(ui5-side-navigation): ensure all items are focusable after expand

packages/main/cypress/specs/Table.cy.ts, packages/main/src/TableCell.hbs, packages/main/src/TableCell.ts, packages/main/src/TableHeaderCell.ts, packages/main/test/pages/TablePopin.html
=> feat(ui5-table): popin-text property added

packages/tools/lib/create-new-component/Component.js, packages/tools/lib/create-new-component/ComponentTemplate.js, packages/tools/lib/create-new-component/index.js
Update the `create-ui5-element` script to generate jsx template and apply all jsx related changes (indluding jsxRenderer, template path, usage of event-strict decorator, describing the eventDetails, etc.)
=> chore: update `create-ui5-element` script

packages/main/src/themes/Label.css
=> fix(ui5-label): adjust asterisk size

packages/main/src/themes/FormItem.css, packages/main/test/pages/form/FormWithElements.html
If the content of an item exceeds the width of the ui5-form-item, it will overflow. With this change, the content now grows to the width of the ui5-form-item.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10473
=> fix(ui5-form): prevent content overflow

packages/main/src/Input.ts, packages/main/src/themes/base/rtl-parameters.css
part of #9966
revert of #10316
=> chore(ui5-popover): remove an unnecessary selector  

packages/main/cypress/specs/Label.cy.ts, packages/main/cypress/specs/Tag.cy.ts, packages/main/cypress/specs/Text.cy.ts, packages/main/cypress/specs/Title.cy.ts
=> chore: add Cypress tests for Label, Tag, Text, Title

packages/fiori/src/Bar.hbs, packages/fiori/src/Bar.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/10446
=> chore(ui5-bar): introduce parts for slot containers

packages/main/src/Button.ts, packages/main/src/SplitButton.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/10611
=> feat(ui5-button): introduce CSS Shadow parts

packages/main/cypress/specs/RatingIndicator.cy.ts, packages/main/src/RatingIndicator.ts
=> fix(ui5-rating-indicator): allow tab next/prev when readonly

packages/main/src/themes/SegmentedButton.css, packages/main/src/themes/SplitButton.css, packages/main/src/themes/base/ColorPicker-parameters.css, packages/main/src/themes/base/SegmentedButtton-parameters.css, packages/main/src/themes/base/SplitButton-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/ColorPicker-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/SplitButton-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/ColorPicker-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/SplitButton-parameters.css, packages/main/src/themes/sap_horizon/SegmentedButtton-parameters.css, packages/main/src/themes/sap_horizon/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_dark/SegmentedButtton-parameters.css, packages/main/src/themes/sap_horizon_dark/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_hcb/ColorPicker-parameters.css, packages/main/src/themes/sap_horizon_hcb/SegmentedButtton-parameters.css, packages/main/src/themes/sap_horizon_hcb/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_hcw/ColorPicker-parameters.css, packages/main/src/themes/sap_horizon_hcw/SegmentedButtton-parameters.css, packages/main/src/themes/sap_horizon_hcw/SplitButton-parameters.css
The following parameters were introduced in all themes:
- Inner corner radius for `ui5-segmented-button` and `ui5-split-button`
- Border width for the inner picker circle in `ui5-colorpicker`
=> feat(ui5-split-button, etc): introduce new parameters

packages/fiori/cypress/specs/FCL.cy.ts, packages/fiori/test/specs/FCL.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10660
=> chore: fix FCL tests

packages/fiori/src/types/SideNavigationItemDesign.ts, packages/website/docs/_samples/fiori/SideNavigation/QuickAction/main.js, packages/website/docs/_samples/fiori/SideNavigation/UnselectableParentItems/sample.html
=> docs(ui5-side-navigation): improve quick actions descriptions

packages/main/cypress/specs/MessageStrip.cy.ts, packages/main/cypress/specs/base/Events.cy.ts, packages/main/src/MessageStrip.ts, packages/main/test/pages/MessageStrip.html
=> fix(ui5-message-strip): close event bubbling

packages/fiori/cypress/specs/FCL.cy.tsx, packages/fiori/src/FlexibleColumnLayoutTemplate.tsx
closes: https://github.com/SAP/ui5-webcomponents/issues/10747
=> fix(ui5-flexible-column-layout): aria-hidden is now correct

packages/main/cypress/specs/FormSupport.cy.tsx, packages/main/src/RadioButtonGroup.ts, packages/main/src/Select.ts, packages/tools/components-package/cypress/support/commands.js
Remove unnecessary waits in Cypress tests.
=> chore: clear wait command in tests

packages/fiori/test/specs/ShellBar.spec.js, packages/main/src/Popover.ts, packages/main/test/specs/MultiInput.spec.js
Downport of #9938
Fixes: #9886
=> fix(ui5-popover): popover arrow is aligned to the middle of the opener

packages/fiori/src/SideNavigation.ts
=> fix(ui5-side-navigation): remove inappropriate exclamation mark usage

packages/fiori/src/UploadCollectionItem.ts, packages/main/src/ListItem.ts, packages/main/src/ListItemTemplate.tsx
After https://github.com/SAP/ui5-webcomponents/pull/5148, UploadCollectionItem renders its own delete button, making related code in ListItem obselete.
=> refactor(ListItem): delete unused code

packages/fiori/cypress/specs/UploadCollection.cy.tsx, packages/fiori/src/UploadCollectionItemTemplate.tsx, packages/fiori/test/pages/UploadCollection.html
Fixes https://github.com/SAP/ui5-webcomponents/issues/10783
=> fix(ui5-upload-collection-item): properly display deleteButton slot

packages/main/src/InputPopoverTemplate.tsx, packages/main/src/InputTemplate.tsx, packages/main/src/features/InputSuggestionsTemplate.tsx, packages/tools/components-package/nps.js
=> refactor(ui5-input): support suggestionList hook from Input template

packages/main/src/Popover.ts, packages/main/test/pages/ResponsivePopover.html
=> fix(ui5-popover): popover is opened from header slot

packages/main/cypress/specs/Input.cy.tsx, packages/main/cypress/specs/base/Events.cy.tsx, packages/main/src/Input.ts
=> refactor(ui5-input): prevent bubbling on close

README.md
Update icon with text in README.md with the SAP design asset from Figma.
=> docs: Update icon with text in README.md

packages/main/cypress/specs/Tokenizer.cy.tsx, packages/main/src/Tokenizer.ts
=> fix(ui5-tokenizer): fix overflow mechanism

packages/fiori/src/themes/IllustratedMessage.css
=> fix(ui5-illustrated-message): update title font styles

packages/main/src/Tokenizer.hbs, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-tokenizer): hide visually hidden text from screen reader

packages/main/src/themes/Toast.css, packages/main/src/themes/base/Toast-parameters.css
=> chore(ui5-toast): visual update

packages/fiori/src/ShellBar.ts
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10890
=> fix(ui5-shellbar): correct matching content check

packages/main/cypress/specs/Toolbar.cy.tsx, packages/main/src/Toolbar.ts, packages/main/src/ToolbarPopoverTemplate.tsx, packages/main/src/i18n/messagebundle.properties
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10324
=> fix(ui5-toolbar): prevent default dialog announcement

packages/main/src/themes/base/InputIcon-parameters.css, packages/main/src/themes/sap_horizon/InputIcon-parameters.css, packages/main/src/themes/sap_horizon_dark/InputIcon-parameters.css
=> fix: align input with icons to latest VD spec

packages/fiori/src/NotificationListGroupList.ts
Fixes https://github.com/SAP/ui5-webcomponents/issues/11002
=> chore(ui5-notification-group-list): import Keys module correctly

packages/main/src/themes/MessageStrip.css, packages/main/src/themes/base/MessageStrip-parameters.css, packages/main/src/themes/sap_fiori_3/MessageStrip-parameters.css, packages/main/src/themes/sap_fiori_3_dark/MessageStrip-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/MessageStrip-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/MessageStrip-parameters.css, packages/main/src/themes/sap_horizon_dark/MessageStrip-parameters.css, packages/main/src/themes/sap_horizon_hcb/MessageStrip-parameters.css, packages/main/src/themes/sap_horizon_hcw/MessageStrip-parameters.css
=> chore(ui5-message-strip): update css parameters

packages/main/src/TableCell.hbs
Probably forgotten, but triggers the hbs compilation
=> chore: remove last .hbs file

packages/main/cypress/specs/List.cy.tsx, packages/main/src/List.ts
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10442
=> fix(ui5-list): prevent load-more event fire without scroll

packages/base/src/util/dragAndDrop/findClosestPosition.ts, packages/main/cypress/specs/TabContainer.cy.tsx, packages/main/src/TabContainer.ts
Fixes https://github.com/SAP/ui5-webcomponents/issues/10478
=> fix(ui5-tabcontainer): allow browser refresh shortcut to work

packages/main/cypress/specs/Menu.cy.tsx
=> chore(ui5-menu): removing an unstable test to stabilize the build

packages/theming/package.json, yarn.lock
Adopt latest theming-base-content to enable usage of new CSS variables.
--sapTab_Neutral_TextColor: #1d2d3e;
--sapTab_Neutral_ForegroundColor: #788fa6;
--sapTab_Neutral_IconColor: #788fa6;
--sapTab_Neutral_Selected_TextColor: #1d2d3e;
--sapTab_Neutral_Selected_IconColor: #fff;
--sapTab_Neutral_Selected_Background: #788fa6;
=> feat(framework): update theming-base-content to 11.26.0

packages/main/src/ListItemGroupHeader.ts
=> fix(ui5-list-item-group-header): typo fixed

docs/2-advanced/09-accessibility.md, packages/fiori/cypress/specs/ShellBar.cy.tsx, packages/fiori/src/ShellBar.ts, packages/fiori/src/ShellBarItem.ts, packages/fiori/src/ShellBarPopoverTemplate.tsx, packages/fiori/src/ShellBarTemplate.tsx, packages/fiori/test/pages/ShellBar_evolution.html
aria-described and aria-hasPopup are now available for setting on custom actions buttons in Shellbar.
=> feat(ui5-shellbar): accessibility attributes added to action buttons

packages/main/src/themes/sap_horizon/Tag-parameters.css, packages/main/src/themes/sap_horizon_dark/Tag-parameters.css, packages/main/src/themes/sap_horizon_hcb/Tag-parameters.css, packages/main/src/themes/sap_horizon_hcw/Tag-parameters.css
Second Color Set of Indication Colors - colors and backgrounds are updated.
BGSOFUIRODOPI-3429
=> chore(ui5-tag): update CSS custom parameters

packages/main/cypress/specs/Tag.cy.tsx, packages/main/src/Tag.ts
Fix firing click event twice 
fixes #11096
=> fix(ui5-tag): fix click event

packages/main/src/Carousel.hbs, packages/main/src/Carousel.ts, packages/main/src/i18n/messagebundle.properties
JIRA: BGSOFUIRODOPI-3382
fixes https://github.com/SAP/ui5-webcomponents/issues/10198
fixes https://github.com/SAP/ui5-webcomponents/issues/8624
downport of #11032
=> fix(ui5-carousel): update roles to match ACC specification

packages/compat/src/themes/Table.css, packages/compat/src/themes/TableGroupRow.css
Fixes: https://github.com/SAP/ui5-webcomponents/issues/11112
=> fix(ui5-table): focus visiblity (compat)

packages/main/cypress/specs/MultiComboBox.cy.tsx, packages/main/src/Token.ts, packages/main/src/TokenTemplate.tsx
=> fix(ui5-multi-combobox): fix deletion of long tokens

packages/main/src/themes/Input.css
=> fix(ui5-input): remove additional icon in Edge

packages/main/src/themes/base/RadioButton-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/RadioButton-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/RadioButton-parameters.css, packages/main/src/themes/sap_horizon/RadioButton-parameters.css, packages/main/src/themes/sap_horizon_dark/RadioButton-parameters.css, packages/main/src/themes/sap_horizon_hcb/RadioButton-parameters.css, packages/main/src/themes/sap_horizon_hcw/RadioButton-parameters.css
=> chore(ui5-radio-button): update dash style for read-only state in Fiori themes

packages/fiori/src/themes/NavigationMenu.css, packages/fiori/src/themes/NavigationMenuItem.css, packages/fiori/src/themes/SideNavigationItem.css, packages/fiori/src/themes/base/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_dark/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_hcb/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_hcw/SideNavigation-parameters.css, packages/fiori/test/pages/SideNavigation.html
=> feat(ui5-side-navigation): reduce space between items in popovers

packages/main/cypress/specs/DateControlsWithTimezone.cy.tsx
fixes: https://github.com/SAP/ui5-webcomponents/issues/11188
=> fix(ui5-date-*): make tests stable

packages/fiori/cypress/specs/Search.cy.tsx
=> fix(ui5-search): fix failing test

packages/main/cypress/specs/Calendar.cy.tsx, packages/main/cypress/support/commands/Calendar.commands.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/11178
=> chore(ui5-calendar): make tests stable

packages/fiori/cypress/specs/ViewSettingsDialog.cy.tsx, packages/fiori/src/ViewSettingsDialogTemplate.tsx
=> fix(ui5-view-settings-dialog): provide accessible name for the dialog

packages/main/cypress/specs/Input.cy.tsx, packages/main/src/Input.ts
=> fix(ui5-input): change event firing after clear icon click

packages/website/src/components/Editor/index.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8776
=> docs(website): playground height

packages/fiori/cypress/specs/Search.mobile.cy.tsx
=> fix(ui5-search): stabilitze mobile test

packages/fiori/test/pages/FCL.html, packages/fiori/test/pages/Wizard.html, packages/fiori/test/pages/WizardPageMode_test.html, packages/fiori/test/pages/Wizard_test.html, packages/main/cypress/specs/Form.cy.tsx, packages/main/src/Form.ts
Propagate `itemSpacing` properly from Form to Form items
Fixes: https://github.com/SAP/ui5-webcomponents/issues/11307
=> fix(ui5-form): propagate `itemSpacing` properly

packages/main/cypress/specs/TableRowActions.cy.tsx, packages/main/src/TableRow.ts
=> fix(ui5-table): stops the propagation of overflow button

packages/fiori/src/themes/SideNavigationItemBase.css
=> fix(ui5-side-navigation): correct hover styles of selected items

packages/main/cypress/specs/Input.cy.tsx
FIXES: [#11381](https://github.com/SAP/ui5-webcomponents/issues/11381)
=> fix(ui5-input): correct failing test

packages/main/cypress/specs/Table.cy.tsx, packages/main/src/TableTemplate.tsx, packages/website/docs/_components_pages/main/Table/Table.mdx, packages/website/docs/_samples/main/Table/NoDataSlot/sample.html
=> fix(ui5-table): fixes noData slot issue

packages/fiori/src/themes/FlexibleColumnLayout.css
=> fix(ui5-flexible-column-layout): min width of column adjusted to spec

packages/fiori/src/themes/SideNavigationItem.css
=> fix(ui5-side-navigation): update font-weight for first level items

packages/main/src/Calendar.ts, packages/main/src/CalendarHeaderTemplate.tsx, packages/main/src/YearPickerTemplate.tsx, packages/main/src/themes/CalendarHeader.css
downport: https://github.com/SAP/ui5-webcomponents/pull/11468
=> fix(ui5-calendar): show year range text in year view

packages/main/cypress/specs/Slider.cy.tsx, packages/main/src/RangeSliderTemplate.tsx, packages/main/src/SliderBase.ts, packages/main/src/SliderTemplate.tsx
=> fix(ui5-slider, ui5-range-slider): correct f2 announcement

packages/main/cypress/specs/Avatar.cy.tsx, packages/main/src/themes/Avatar.css, packages/main/test/specs/Avatar.spec.js
=> fix(ui5-avatar): disable click on disabled interactive

packages/main/src/themes/PopupsCommon.css, packages/main/src/themes/base/PopupsCommon-parameters.css
=> fix(popups): fix header styles according to the specification

packages/fiori/cypress/specs/Search.mobile.cy.tsx, packages/fiori/src/Search.ts
=> fix(ui5-search): preserve value before open on mobile

packages/website/docs/_samples/fiori/Page/Basic/sample.html
=> docs(ui5-page): adjust floating footer sample

packages/base/src/features/OpenUI5Support.ts
fixes: https://github.com/SAP/ui5-webcomponents/issues/11579
=> chore(framework): make OpenUI5Support promise consistent

packages/fiori/src/types/IllustrationMessageType.ts, packages/website/build-scripts/api-reference-generation/component-file.mjs
=> docs(website): display depracated text to enum members

packages/main/cypress/specs/Tokenizer.mobile.cy.tsx, packages/main/src/Tokenizer.ts
=> fix(ui5-tokenizer): fix token selection on mobile

packages/main/cypress/specs/FormSupport.cy.tsx, packages/main/src/Switch.ts, packages/main/test/pages/FormSupport.html, packages/main/test/pages/Switch.html
fixes: https://github.com/SAP/ui5-webcomponents/issues/11608
=> feat(ui5-switch): add value for form

packages/main/src/themes/ComboBoxItem.css, packages/main/src/themes/MultiComboBoxItem.css, packages/main/src/themes/SuggestionItem.css
=> fix(ui5-cb-item): adjust height in compact

packages/website/docs/_samples/patterns/AIRegenerate/Basic/sample.html
Reworded the dialog in the AI Regenerate pattern based on designer feedback. 
Previously: 
> Do you wish to proceed?
Now: 
> Do you want to continue?
=> docs(ui5-ai-button): improve pattern based on design feedback

packages/main/cypress/specs/DynamicDateRange.cy.tsx
fixes: https://github.com/SAP/ui5-webcomponents/issues/11923
=> fix(ui5-dynamic-date-range): skip test

packages/fiori/src/themes/ShellBar.css, packages/fiori/src/themes/base/ShellBar-parameters.css, packages/fiori/src/themes/sap_horizon/ShellBar-parameters.css, packages/fiori/src/themes/sap_horizon_dark/ShellBar-parameters.css, packages/fiori/src/themes/sap_horizon_dark_exp/ShellBar-parameters.css, packages/fiori/src/themes/sap_horizon_exp/ShellBar-parameters.css
=> fix(ui5-shellbar): search button adjusted to visual design

packages/fiori/cypress/specs/Search.cy.tsx, packages/fiori/src/SearchItem.ts, packages/fiori/src/SearchItemTemplate.tsx, packages/fiori/src/themes/SearchItem.css, packages/fiori/test/pages/Search.html
=> feat(ui5-search-item): add deletable property

packages/fiori/cypress/specs/NotificationList.cy.tsx
Fixes: https://github.com/SAP/ui5-webcomponents/issues/11716
=> test(ui5-notification-list): stabilze test

packages/main/src/themes/sap_horizon/TabContainer-parameters.css, packages/main/src/themes/sap_horizon_dark/TabContainer-parameters.css, packages/main/test/pages/TabContainer.html
font-weight is adjusted according to visual specification.
Fixes: #11998
=> fix(ui5-tabconatiner): removed wrong font-weight

packages/main/cypress/specs/Table.cy.tsx, packages/main/cypress/specs/TableGrowing.cy.tsx, packages/main/cypress/specs/TableRowActions.cy.tsx, packages/main/cypress/specs/TableSelections.cy.tsx, packages/main/cypress/specs/TableVirtualizer.cy.tsx, packages/main/src/Table.ts, packages/main/src/TableHeaderRow.ts, packages/main/src/TableHeaderRowTemplate.tsx, packages/main/src/TableRow.ts, packages/main/src/TableRowTemplate.tsx, packages/main/src/TableSelection.ts, packages/main/src/TableSelectionBase.ts, packages/main/src/TableSelectionMulti.ts, packages/main/src/TableTemplate.tsx, packages/main/src/i18n/messagebundle.properties
- aria-rowcount/colcount/rowindex/colindex attributes are set
- aria-hidden is set for the the growing row and navigated cell
- aria-multiselectable custom announcement is added
- custom announcement for the header row selection cell
- custom row and cell announcement are not included
Fixes: #11639
=> fix(ui5-table): aria relevant attributes are set

packages/main/cypress/specs/Popover.cy.tsx, packages/main/src/Dialog.ts, packages/main/src/Popup.ts, packages/main/test/pages/Popover.html
=> fix(ui5-popover): allow f6 navigation

docs/2-advanced/17-drag-and-drop.md, packages/base/src/util/dragAndDrop/DragRegistry.ts, packages/main/test/pages/MultipleDragDemo.html, packages/website/docs/_samples/main/List/MultipleDrag/main.js
This new parameter will be necessary in a future phase.
JIRA: BGSOFUIRODOPI-3442
=> chore(DnD): modify startMultipleDrag method to use DragEvent

packages/fiori/src/SearchItem.ts, packages/fiori/src/SearchItemTemplate.tsx, packages/fiori/src/i18n/messagebundle.properties, packages/fiori/src/themes/Search.css, packages/fiori/src/themes/SearchField.css, packages/fiori/src/themes/SearchItemGroup.css, packages/fiori/src/themes/SearchMessageArea.css, packages/main/src/SelectTemplate.tsx
FIXES: #11982
FIXES: #11964
FIXES: #11981
FIXES: #11999
FIXES: #12042
FIXES: #11955
=> fix(ui5-search): visual issues

README.md
This small PR fixes the the UI Theme Designer guide in `README.md`.
=> docs: update the UI Theme Designer guide
