UI5/webcomponents

packages/main/src/TableRow.ts
Assuming that the activeElement is guaranteed to be non-null object is **not** entirely valid although in real case usages, nobody had a problem.
However, in a test execution environment, the authors of the linked issue got an execution thrown by `activeElement!.hasAttribute` and I think it's best to ensure this can't happen as done with the change.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7787
=> fix(ui5-table-row): fix runtime exception in test env execution

vite.config.js
The `path.join` and `path.resolve` methods convert paths to win32 separators `\` and this breaks the checks and the replacements.
This change converts the paths to posix separators after these two calls to work on windows.
=> fix(infra): windows build

packages/main/src/TabContainer.hbs, packages/main/src/TabContainer.ts, packages/main/test/pages/TabContainer.html
adds `tabstrip` CSS Shadow Part to allow styling of the respective element - mostly its padding.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/6035
=> feat(ui5-tabcontainer): add `tabstrip` Shadow Part

packages/main/src/ColorPalette.ts, packages/main/src/ColorPalettePopover.hbs, packages/main/src/ColorPalettePopover.ts, packages/main/src/Popover.ts, packages/main/src/themes/ColorPalettePopover.css, packages/main/test/pages/ColorPalettePopover.html, packages/main/test/specs/ColorPalettePopover.spec.js
**Background**
After we introduced the declarative option to open and close popups via  the`open` and `opener` props in the Popover in the past, the idea was to gradually enable all popover-based components to support the same convenient, declarative API. And, the ColorPalettePopover is one of them.
Recently, we have been asked how the ColorPalettePopover can be opened by default upon web page loading (not opening upon button click as usual), which is difficult with the available imperative API `showAt` as the component not only must be defined, but also rendered completely as `showAt` calls methods of the internal responsive popover. 
Providing the declarative API resolves all this - the consumer just sets `open` and `opener` and the component handles everything else in its lifecycle.
As …
=> feat(ui5-color-palette-popover): introduce `open` and `opener` properties

packages/fiori/src/ViewSettingsDialog.ts
The Bar does not seems to be used in the ViewSettingsDialog any more, the Bar dependency is not needed.
=> chore(vsd): remove obsolete dependency

packages/main/src/Select.hbs, packages/main/src/Select.ts, packages/main/src/themes/Input.css, packages/main/src/themes/base/Input-parameters.css, packages/main/src/themes/sap_horizon/Input-parameters.css, packages/main/src/themes/sap_horizon_dark/Input-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/Input-parameters.css, packages/main/src/themes/sap_horizon_exp/Input-parameters.css, packages/main/test/pages/Select.html, packages/main/test/pages/SelectMenu.html, packages/main/test/specs/Select.spec.js, packages/playground/_stories/main/Select/Select.stories.ts
Introduces `readonly` state to the Select web component and align the `readonly` styles for all input fields to the latest specs
- API: new property `readonly` 
- VD: respective visual styling for `readonly` state, dropdown icon is not displayed
- InteractionDesign:  dropdown remains always closed, no changes in selection allowed
- a11y: new aria attribute `aria-readonly` true|false accordingly 
While introducing the Select `readonly` state that should follow the general input field specification, we noticed that the readonly styling for the focused state differs from design specs for Horizon.
@hristop @niyap is this deviation intended. If yes, I will revert this part.
**Horizon Design spec**
**Current implementation** 
- outline is over the input border
- border-radius is as for the …
=> feat(ui5-select): introduce `readonly` state

packages/main/src/themes/Toolbar.css
This change removes unnecessary styles of the Toolbar.css file, related to the background of the Toolbar.
As we decided not to implement `desing` and `styling` property, some styles were not removed with the initial commit of the toolbar component.
Additionally, a risky override is removed of the color of the toolbar items.
=> fix(ui5-toolbar): remove unnecessary styles

.github/ISSUE_TEMPLATE/bug_report.yml, docs/FAQ.md, packages/playground/docs/landing-page.html
Access to `Codesandbox` is sometimes constrained on SAP corporative network, so we start suggesting the usage of `Stackblitz` as alternative platform for sample creation for testing the ui5 web comps, or to create reproducible samples to show-case bugs.
=> docs: add `Stackblitz` alternative for sample creation

packages/icons-business-suite/src/json-imports/Icons.ts, packages/icons-tnt/src/json-imports/Icons.ts, packages/icons/src/json-imports/Icons.ts, packages/tools/lib/generate-js-imports/illustrations.js
This change is a continuation of https://github.com/SAP/ui5-webcomponents/pull/7835.  I found a few more places where dynamic imports are used, so this is to add well-defined names to those as well.
Specifically I found 2 new cases:
1. Loading of icons
2. Loading of illustration SVGs in the fiori package.
This change tries to follow a similar naming convention as was used before.  Here's an example of some of the new chunks from my SAC build:
=> fix: declare webpackChunkName in more generated dynamic imports

packages/playground/.storybook/addons/TitleEnhancer.ts, packages/playground/.storybook/docs.tsx, packages/playground/.storybook/manager.tsx, packages/playground/assets/css/api.css
Summary: 
- TitleEnhancer introduced to inlcude keywords in the document's title tag when a story page is loaded (eg. component tag)
- The component tag displayed in the docs page is now with a semantinc h2 element.
=> docs(storybook): use semantic headings for better seo

packages/main/src/CheckBox.hbs, packages/main/src/CheckBox.ts
Enable overstyling of the checkbox's label.
=> feat(ui5-checkbox): add css shadow part to the label

packages/main/src/TreeItemBase.ts, packages/main/test/pages/Tree.html, packages/main/test/specs/Tree.spec.js
Tree listens for child invalidation only on first level tree items. Adding item on a deeper level doesn't trigger invalidation and the items are displayed with wrong indentation. With this change we are triggering invalidation when default slot of nested child is changed.
Fixes: #8050
Fixes: #8048
=> fix(ui5-tree): correct item indentation

packages/main/src/Select.ts
There are use-cases when the "value" setter is called early on, before the component definition and that call simply does not   occur and the state is lost.
- make "value" setter "upgraded" (as it's done for the `@property` decorated properties), so that the setter is available
- the setter no longer rely on the component framework-created accessors  (`this.options` or `option.disabled`) because web components might not be defined yet. Instead, rely on the Light DOM - children and attributes.
=> refactor: update "value" setter

packages/main/src/NavigationMenu.ts, packages/main/src/NavigationMenuItem.ts
Changes:
- updated the `JSDoc` to use the new format (no `@name`, no `@alias`, `@defaultvalue` -> `@default`, no namespaces)
- updated the `@since` from `1.3` to `1.22`
- removed `Menu` from `dependencies` as it's not used in the template (there are no extra components used in the `NavitgationMenu.hbs` compared to `Menu.hbs`, therefore `dependencies` should not be changed)
- removed the non-existent interface `sap.ui.webc.main.INavigationMenuItem` and overrid the `@slot` to correctly aggregate the new item
=> docs(ui5-navigation-menu): use new JSDoc syntax

packages/main/src/ListItem.ts
Fixes: #8047
_level property is removed from ui5-li, since it is no longer used.
Also, import of 'Integer' is removed, since it is not used as well.
=> fix(ui5-list): removed _level property

docs/1-getting-started/08-wrapping-up.md, docs/2-advanced/01-configuration.md, docs/5-development/01-custom-UI5-Web-Components-Packages.md, docs/5-development/02-custom-UI5-Web-Components.md
The following themes are deprecated and no longer maintained.
The themes will work until the next major version (2.0) and will be removed afterwards.
- The `sap_belize` is known as `Belize`.
- The `sap_belize_hcb` is known as `High Contrast Black`.
- The `sap_belize_hcw` is known as `High Contrast White`.
=> docs: publish "sap_belize-*" deprecation statement

packages/main/src/MultiComboBox.ts, packages/main/src/MultiComboBoxPopover.hbs, packages/main/src/i18n/messagebundle.properties, packages/main/test/specs/MultiComboBox.mobile.spec.js
- accessibleName attribute is added to the show selected button used in the mobile dialog
FIXES: #8060
=> fix(ui5-multi-combobox): enhance accessibility on mobile

packages/base/tsconfig.json, packages/create-package/template/tsconfig.json, packages/fiori/src/UploadCollectionItem.ts, packages/fiori/tsconfig.json, packages/icons-business-suite/tsconfig.json, packages/icons-tnt/tsconfig.json, packages/icons/tsconfig.json, packages/localization/tsconfig.json, packages/main/src/CustomListItem.ts, packages/main/src/ListItem.ts, packages/main/src/MultiComboBoxItem.ts, packages/main/src/NavigationMenu.ts, packages/main/src/SegmentedButtonItem.ts, packages/main/src/SelectMenuOption.ts, packages/main/src/StandardListItem.ts, packages/main/src/TreeItem.ts, packages/main/src/TreeItemBase.ts, packages/main/tsconfig.json, packages/playground/tsconfig.json, packages/theming/tsconfig.json
`Array.toSorted` is supported in all browsers, but appears in `lib: es2023` and TypeScript complains.
Checking how functionality is added in the standard es2023 - it has to be stage 4 which means the spec is final and two browsers implement it.
So for this project it seems safe to add the latest `lib: es2023`, as additions are not made there too early.
=> chore: update tsconfig target and lib

packages/fiori/src/themes/ShellBar.css
The logo now has small gap between itself and its focus/hover outline in order to avoid overlap.
Fixes: #8058
=> fix(ui5-shellbar): logo aligned with visual specification

packages/base/src/util/detectNavigatorLanguage.ts, packages/base/src/util/getDesigntimePropertyAsArray.ts
Exporting anonymous function creates export without name which leads to wrong validation of custom elements manifest.
=> chore: fix cem generation for base

packages/main/src/SplitButton.hbs, packages/main/src/themes/SplitButton.css, packages/main/src/themes/base/SplitButton-parameters.css, packages/main/src/themes/base/rtl-parameters.css, packages/main/src/themes/base/sizes-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/SplitButton-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/SplitButton-parameters.css, packages/main/src/themes/sap_horizon/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_dark/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_exp/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_hcb/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_hcw/SplitButton-parameters.css, packages/main/src/themes/sap_horizon_hcw_exp/SplitButton-parameters.css, packages/main/test/pages/SplitButton.html
When our `<ui5-split-button>` is wrapped and a width is set to the wrapper, our `<ui5-split-button>` is not correctly displayed. 
With this change, we fix that issue and we also adopt the usage of CSS Logical Props, removing redunancies and reducing our CSS code significantly.
Fixes: #7659
=> fix(ui5-split-button): fix split button when in wrapper

packages/base/package-scripts.cjs, packages/fiori/package-scripts.cjs, packages/main/package-scripts.cjs, packages/tools/components-package/nps.js, packages/tools/lib/cem/custom-elements-manifest.config.mjs, packages/tools/lib/cem/validate.js, patches/@custom-elements-manifest+analyzer+0.8.4.patch
Enable errors when validating custom-element-manifest for ui5 packages and stop the build if invalid syntax is used.
In this PR a patch for `@custom-elements-manifest/analyzer` package is added to enable `ui5generation` cli parameter because the package has strict check for used parameters.
=> chore: enable errors for cem validation

packages/main/src/themes/sap_fiori_3_dark/Badge-parameters.css, packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_hcb/Badge-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/Badge-parameters.css
=> fix(ui5-badge): correct text-shadow for Quartz dark theme

packages/main/src/ColorPalette.hbs, packages/main/src/ColorPalette.ts, packages/main/src/i18n/messagebundle.properties
Currently in our `<ui5-color-palette>` and `<ui5-color-palette-popover>` components the **'More Colors...'** button have its text in the i18n Bundle, while in the **'Default Color'** button the text was hardcoded, which is inconsistent and leads to a non-translated text in different regions.
With this change we added the text of the **'Default Color'** button in the I18N Bundle.
Fixes: #8155
=> fix(ui5-color-palette): add i18n text for default color button's text

packages/main/src/Tokenizer.ts, packages/main/test/pages/MultiInput.html, packages/main/test/specs/MultiInput.spec.js
=> fix(ui5-multi-input): fix multiple token addition

packages/fiori/src/ViewSettingsDialog.ts, packages/main/src/Tree.ts, packages/tools/lib/cem/custom-elements-manifest.config.mjs
Provide export only for exports that have JavaScript representation (function / class / variable / enum) and remove ones like interfaces, types.
=> chore: provide exports with js representation only

packages/fiori/src/ShellBar.ts, packages/fiori/test/pages/ShellBar.html, packages/fiori/test/specs/ShellBar.spec.js
The ui5-shellbar component now allows the app to prevent the default action of the  'menu-item-click' event
Fixes #8149
=> fix(ui5-shellbar): allow prevent default 'menu-item-click' action

packages/main/src/bundle.esm.ts
After importing ToolbarSelectOption class only as a type in ToolbarSelect, options was not rendering properly.
Adding it to the bundle fixes the reference.
=> fix(ui5-toolbar-select): options added to bundle

packages/tools/lib/cem/custom-elements-manifest.config.mjs, packages/tools/lib/cem/schema-internal.json, packages/tools/lib/cem/types-internal.d.ts
Provide information in the manifest for properties that are explicitly set to not have attribute.
=> chore: add noattribute information

packages/tools/lib/cem/custom-elements-manifest.config.mjs, packages/tools/lib/cem/utils.mjs
References from return types described as following were not correctly generated:
```ts
get hiddenItems(): IAvatar[] 
```
Now, `IAvatar[]` and `Array<IAvatar>` generate correct references and both are transpiled to `Array<IAvatar>` as basic array syntax into custom-elements.json.
=> chore: process bracket array syntax

packages/main/src/themes/SplitButton.css
After updating the theming version and adapting new values of the css parameters, we found few issues we had in the SplitButton. 
With this change we apply the correct parameters, and align the Split Button with the Visual Specifications.
Fixes: #8136
=> fix(ui5-split-button): use correct params

packages/base/package.json, packages/base/src/UI5Element.ts, packages/fiori/package.json, packages/localization/package.json, packages/main/package.json, vite.config.js, yarn.lock
In `dev` the shim `js` files are not in `dist` and we need to add resolver so vite finds the `ts` files in `src`
=> chore: fix ssr-shim import resolve on dev

packages/base/src/UI5ElementMetadata.ts
Properties with `type: Object` that don't have specified default value in their declaration decorator have `{}` as default value.
This `{}` is stored in the initial state of the component and its reference is shared between instanced.
Same apply for multiple properties but with `[]` instead of `{}`
In some cases where the property value is changed with an index instead of a new reference, the component starts to behave wrongly because the value of the shared reference is changed. 
```ts
this.propertyName.somethingNested = "Some new value"
```
With this change, we provide a new object reference whether the default value of the property is accessed
=> fix(framework): property with empty object as default value

packages/fiori/src/ShellBar.ts, packages/fiori/test/pages/ShellBar.html, packages/fiori/test/specs/ShellBar.spec.js
New event search-button-click is added, which allows different actions to be triggered
when it is fired on the search button inside the ui5-shellbar.
If its preventDefault  method is called, the default action of the search button
(expanding/collapsing the input) won`t be triggered, but let the users trigger their own.
Related: https://github.com/SAP/ui5-webcomponents/issues/6273
=> feat(ui5-shellbar): new event added

packages/base/package.json, packages/fiori/package.json, packages/icons-business-suite/package.json, packages/icons-tnt/package.json, packages/icons/package.json, packages/localization/package.json, packages/main/package.json, packages/theming/package.json
Executing TypeScript in `prepublishOnly` command wasn't enable to check for existing build information.
=> fix: release build

.github/workflows/ci-test-storybook.yaml, .github/workflows/ci-test.yaml, .github/workflows/deploy-latest-playground-on-push.yaml, .github/workflows/deploy-latest-playground-on-release.yaml, .github/workflows/deploy-main-playground-on-push.yaml, .github/workflows/deploy-main-playground.yaml, .github/workflows/issues-handling.yaml, .github/workflows/lint.yaml, .github/workflows/release-downport.yaml, .github/workflows/release-experimental.yaml, .github/workflows/release-rc-auto.yaml, .github/workflows/release-rc.yaml, .github/workflows/release-stable.yaml, .github/workflows/reset-gh-pages.yaml
As Node 16 is reaching end of support, there is deprecation process - [GitHub Actions: Transitioning from Node 16 to Node 20](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/). 
As users of several stock actions (`checkout`, `setup-node`) we must ensure our workflows use the latest versions of the actions that are running on Node 20. Currently, workflows containing actions running on Node 16, will display only warnings, but it's nevertheless good to follow the recommendations and update.
=> chore: update stock actions to latest, to run on Node 20

packages/tools/lib/cem/custom-elements-manifest.config.mjs, packages/tools/lib/cem/validate.js
By default `custom-elements-manifest/analyzer` removes every declaration without export from the `custom-elements.json`. Previously, we were removing exports of interfaces during the generation of the manifest and this leads to removed declarations of interfaces. Now, we remove interfaces exports during the validation phase.
=> chore: show interface declarations in cem

packages/base/package.json, packages/fiori/package.json, packages/fiori/src/DynamicPage.ts, packages/fiori/src/DynamicPageHeader.ts, packages/fiori/src/DynamicPageHeaderActions.ts, packages/fiori/src/DynamicPageTitle.ts, packages/localization/package.json, packages/main/package.json, packages/playground/_stories/fiori/DynamicPage/DynamicPage.stories.ts, packages/playground/_stories/fiori/DynamicPage/DynamicPageHeader/DynamicPageHeader.stories.ts, packages/playground/_stories/fiori/DynamicPage/DynamicPageHeaderTemplate.ts, packages/playground/_stories/fiori/DynamicPage/DynamicPageTitle/DynamicPageTitle.stories.ts, packages/playground/_stories/fiori/DynamicPage/DynamicPageTitleTemplate.ts
Dynamic Page docs added.
Dynamic behaviour added to the buttons inside Dynamic page basic story.
=> feat(ui5-dynamic-page): proper docs added

packages/fiori/src/themes/ShellBar.css
After a recent change for the XXL breakpoint, the secondaryTitle didn't looked properly aligned. Now it's fixed by removing redundant CSS styling.
Fixes: #8189
=> fix(ui5-shellbar): fixed secondaryTitle visual presentation

packages/fiori/src/ShellBar.ts, packages/fiori/test/specs/ShellBar.spec.js, packages/main/src/Button.hbs, packages/main/src/Button.ts, packages/main/src/DatePicker.ts, packages/main/src/Link.hbs, packages/main/src/Link.ts, packages/main/src/ListItem.ts, packages/main/src/Toolbar.ts, packages/main/src/TreeItemBase.ts, packages/main/test/specs/DatePicker.spec.js, packages/main/test/specs/Link.spec.js
Some of the components accept values from `HasPopup` enum. These values result in `CamelCase` which may lead to inappropriate behaviour when tools analyze the components. With this change we cast the enum values to lowercase to make them appear as expected in the DOM
=> fix: cast ariaHasPopup acc attribute to lowercase

packages/playground/build-scripts-storybook/samples-prepare.ts, packages/tools/lib/cem/types-internal.d.ts
`_ui5package` is property specific to storybook so we're removing it from the types. In addition wrong inheritance was causing errors in Enum and Interface declarations and now it's fixed.
=> chore: align internal cem types

packages/base/src/Boot.ts, packages/base/src/config/Language.ts, packages/base/src/config/Theme.ts
Based on how your application is structured and how the chunks are made, you can configure before boot of the library. This leads to runtime error especially when theme is configured, because it depends on runtime information which is calculated after boot time.
=> fix: setting configuration before boot

packages/main/src/Tab.ts, packages/main/src/TabContainer.ts, packages/main/src/TabContainerPopover.hbs, packages/main/src/TabInOverflow.hbs, packages/main/test/specs/TabContainer.spec.js
This PR is preparation to handle drop operations.
- Popover content is now refreshed if item is inserted or removed in it, while it is open
- Opening the popover now just requires an opener
- Popover items are now stored in flattened array
- Items `forcedLevel` is no longer set in `_getAllSubItems`. It is now extracted in dedicated method
- `_getAllSubItems` is renamed to `_flatten` and it is reused
- Avoided ambiguous code `realTabReference = this._selectedTab`, which caused unpredictable behavior. Now there is dedicated property `selectedTabReference`.
- Fixed indentation in popover
- Added tests
=> refactor(ui5-tabcontainer): simplify popover logic

packages/playground/docs/landing-page.html
The new link points to https://community.sap.com with tag: "ui5 web components" in "Technology Blogs by SAP".
Fixes #8270
=> docs(landing-page): fix link to Blog post

packages/fiori/src/SideNavigation.hbs, packages/fiori/src/SideNavigation.ts, packages/fiori/src/SideNavigationItemBase.ts, packages/fiori/src/SideNavigationPopover.hbs, packages/fiori/src/themes/SideNavigation.css, packages/fiori/src/themes/base/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_dark/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_hcb/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_hcw/SideNavigation-parameters.css, packages/fiori/test/pages/SideNavigation.html, packages/fiori/test/pages/SideNavigationOnly.html, packages/fiori/test/specs/SideNavigation.spec.js, packages/main/src/NavigationMenu.hbs, packages/main/src/themes/NavigationMenu.css, packages/playground/_stories/fiori/SideNavigation/SideNavigation.stories.ts, packages/playground/_stories/fiori/SideNavigation/SideNavigationSubItem/SideNavigationSubItem.stories.ts
if the navigation item is an external link, show the external link indicator
=> feat(ui5-side-navigation): add external link icon

packages/main/src/ProgressIndicator.hbs, packages/main/src/ProgressIndicator.ts
The part can be used like this to alter the end points' size.
```
[ui5-progress-indicator]::part(remaining-bar)::before,
[ui5-progress-indicator]::part(remaining-bar)::after {
width: 0.375rem;
height: 0.375rem;
}
```
Related to: #8213
=> feat(ui5-rating-indicator): introduced "remaining-bar" CSS part

packages/main/src/themes/TreeItem.css
Background color on hovering items is alligned with the ones for the ui5-list as they share the same spec for their state styles.
Issues solved:
- when no mode was set, the items still can be hovered and clicked. The background color was not changed despite cursor pointer was shown.
- when a selected item was hovered its background color was not changed.
=> fix(ui5-tree-item): fix background color on hover

packages/main/src/CalendarLegendItem.ts, packages/playground/_stories/main/CalendarLegend/CalendarLegend.stories.ts
Currently the tabulations in the Calendar Legend Overview story is a little bit off.
Also an Overview explanation about the Calendar Legend Item Component was missing.
With this change we add the Overview description of the Calendar Legend Item, and fix the tabulations in the Storybook.
=> docs(ui5-calendar-legend, ui5-calendar-legend-item): fix tabulation, add overview

packages/main/src/ListItem.hbs, packages/main/src/ListItem.ts, packages/main/test/pages/List_test_page.html, packages/main/test/specs/List.spec.js, packages/playground/_stories/fiori/UploadCollection/UploadCollectionItem/UploadCollectionItem.stories.ts, packages/playground/_stories/main/List/CustomListItem/CustomListItem.stories.ts, packages/playground/_stories/main/List/StandardListItem/StandardListItem.stories.ts, packages/playground/_stories/main/Tree/TreeItem/TreeItem.stories.ts, packages/playground/_stories/main/Tree/TreeItemCustom/TreeItemCustom.stories.ts
With this change, the `ui5-li` component now supports the `tooltip` property. This allows developers to provide a tooltip for each list item, which will be displayed when hovering over the item.
Related to: #7372
=> feat(ui5-li): add tooltip support to list items

.github/workflows/release-rc-auto.yaml, .github/workflows/release-rc.yaml
Ensure build tasks are run against the updated version (the one that will be released)
- previously: build -> release (version and publish)
- now: version -> build -> publish
=> ci: reorder version-build-publish order

packages/main/src/List.ts, packages/main/src/ListItem.ts, packages/main/src/ListItemBase.ts, packages/main/src/Menu.hbs, packages/main/src/Menu.ts, packages/main/src/MenuItem.ts, packages/main/src/MenuListItem.ts, packages/main/src/themes/Menu.css, packages/main/src/themes/MenuListItem.css, packages/main/test/pages/Menu.html, packages/main/test/specs/Menu.spec.js
- There is a new behavior implemented, which enables
the end users to navigate via mouse and keyboard to a
disabled `ui5-menu-item` element. This behavior is aimed
to improve the accessibility of the `ui5-menu` component
by providing screen reader announcements for disabled
menu items as well.
- The haspopup attribute is now applied to the` ui5-menu item`'s
with a sub-menu.
- There is a new `tooltip` property for the `ui5-menu-item`.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7096
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8214
=> feat(ui5-menu): enable navigation over disabled items

packages/fiori/src/NotificationListGroupItem.ts
Expand icon (navigation-down-arrow) is now imported properly.
Fixes: #8302
=> fix(ui5-li-notification-group): expand arrow visible

packages/main/src/TabInStrip.hbs, packages/main/test/pages/TabContainer.html, packages/main/test/specs/TabContainer.spec.js
The additional text (the number) is rendered only once - in the brackets after the rest of the text
Fixes #8274
=> fix(ui5-tab-container): correct inline mode visualization

packages/main/src/RadioButton.hbs, packages/main/src/RadioButton.ts, packages/main/test/pages/RadioButton.html, packages/main/test/pages/styles/RadioButton.css
We received the following requests for customization of certain parts of the ui5-radio-button:
- inner ring color on hover: can be styled via the new "inner-ring" Css shadow part.
- outer ring Error and Success state colors: can be styled via the new "outer-ring" Css shadow part.
Part of #8105
=> feat(ui5-radio-button): expose new Css shadow parts

packages/main/src/popup-utils/OpenedPopupsRegistry.ts
Previously, registered opened popup exists only in the current runtime registry and pressing `escape` key was triggering close action for every registry handler that exists.
With this change we are moving the opened popup registry to shared resource and all popups are registered into the same central place where single close handler will be executed.
Fixes: #6884
=> fix(ui5-popup): move popup registry to shared resource

packages/main/src/DatePicker.ts, packages/main/src/TimePicker.ts
The aria-autocomplete and aria-controls attributes are no longer considered as valid for the ui5-time-picker and ui5-date-picker input fields.
Fixes: #6931
=> fix(ui5-time-picker): remove redundant aria attributes

packages/main/src/Dialog.ts
Missing information about keyboard shortcuts for dragging/resizing the dialog is now properly documented.
Fixes #8190
=> docs(ui5-dialog): add documentation for keyboard handling

packages/main/src/Avatar.hbs, packages/main/src/Avatar.ts, packages/main/src/themes/Avatar.css
Fixes: #8345 
Now both initials and fallback icon have visibility:hidden initially. Later on when we measure the sizes in onAfterRendering we decide which one to show.
=> fix(ui5-avatar): resolve initial flickering during fallback to icon

packages/main/src/themes/Breadcrumbs.css
It seems that in the context of our project backslashes in CSS need to be escaped twice. Presenting this fix as a temporary solution.
=> fix(ui5-breadcrumbs): fixed not working separators

packages/website/build-scripts/icons-generation/index.mjs, packages/website/src/css/custom.css
- wrap long props
-  better tooltips for copy icon name/svg
=> docs: wrap long props and better tooltips for copy icon name/svg

packages/main/src/themes/DatePicker.css, packages/main/src/themes/StepInput.css, packages/main/src/themes/TimePicker.css
Currently we can observe that in our Input-based controls, when clicking multiple times in a short time-frame, we can see a text selection outside of the reach of the controls. 
We now prevent this behaviour as it hurts the user experience. 
Closes: #8026
=> fix(ui5-date/time-picker, ui5-step-input): prevent text selection

.vscode/settings.json, packages/tools/lib/cem/custom-elements-manifest.config.mjs, packages/tools/lib/cem/utils.mjs, packages/tools/package.json, yarn.lock
Fill attributes array with properties that have attribute representation for custom elements. In addition provide `vscode.html-custom-data.json` and `web-types.json` for better integration with IDEs.
Usage:
- JetBrains automatically detect when `web-types.json` exist
- For VS code manual work has to be done
- `.vscode/settings.json` is adjusted for improve development in ui5-webcomponents packages (you need to build the project for autocompletion)
- if you are using ui5-webcomponents inside your project you have to create `.vscode/settings.json` on your own and to add:
```json
{
"html.customData": [
"./node_modules/@ui5/webcomponents/dist/vscode.html-custom-data.json",
"./node_modules/@ui5/webcomponents-fiori/dist/vscode.html-custom-data.json"
]
}
```
Fixes: …
=> chore: add attributes to cem

packages/base/.eslintignore, packages/base/tsconfig.json
`Cannot write file '.../ui5-webcomponents/packages/base/dist/ssr-dom.d.ts' because it would overwrite input file.`
There is a special import in the base package inside UI5Element for a dom-shim. Even though it is in the same package, it is imported with a bare module specifier
`import "@ui5/webcomponents-base/dist/ssr-dom.js";`
so that export conditions can be checked - an empty module on the browser and a shim in a nodejs environement
This import leads to an error at dev time as the typescript compiler seems to treat the `dist` folder of this modules as both input and output and throws an error that the output will overwrite the input.
This change adds an ignore for these two special files, so their types are not treated as input and will not be overwritten in the output.
=> chore: fix ts dev error

packages/base/src/UI5Element.ts, packages/base/src/decorators.ts, packages/website/src/pages/play.tsx
UI5 element has a static getter for the styles, which prevents using a static assignement and forces cubsclasses to overwrite the getter which is more verbose.
Before:
```js
static get styles() {
return "some styles";
}
```
Now:
```js
static styles = "some styles";
```
The second change makes all decorators available from a single export, so the imports are smaller in the samples:
```js
import { customElement, property, slot } from "@ui5/webcomponents-base/dist/decorators.js";
```
=> chore: enable more concise custom element samples

docs/1-getting-started/01-first-steps.md, docs/1-getting-started/02-importing-components.md, docs/1-getting-started/03-understanding-components-APIs.md, docs/1-getting-started/04-using-icons.md, docs/1-getting-started/05-using-assets.md, docs/1-getting-started/06-using-features.md, docs/1-getting-started/07-typescript-support.md, docs/2-advanced/01-configuration.md, docs/2-advanced/02-RTL-and-compact-mode.md, docs/2-advanced/03-scoping.md, docs/2-advanced/04-OpenUI5-integration.md, docs/2-advanced/05-other-framework-level-APIs.md, docs/2-advanced/06-using-i18n-for-apps.md, docs/2-advanced/07-accessibility.md, docs/2-advanced/08-CSP.md, docs/2-advanced/09-scrollbars-customization.md, docs/3-customizing/01-styles.md, docs/3-customizing/02-theme.md, docs/3-customizing/03-theme_part2.md, docs/5-development/01-custom-UI5-Web-Components-Packages.md, docs/5-development/02-custom-UI5-Web-Components.md, docs/5-development/03-understanding-components-metadata.md, docs/5-development/04-understanding-hbs-templates.md, docs/5-development/05-testing-UI5-Web-Components.md, docs/5-development/06-deep-dive-and-best-practices.md
Remove unnecessary "Next:", as Docusaurus already puts next and previous.
=> docs: remove unnecessary "Next:"

packages/website/docusaurus.config.ts, packages/website/src/pages/Privacy.md
As hosted on Github Pages, we need to reference different kind of privacy information:
=> docs: add `Privacy` page

packages/website/build-scripts/api-reference-generation/components.mjs, packages/website/build-scripts/api-reference-generation/index.mjs, packages/website/build-scripts/api-reference-generation/manifest.mjs, packages/website/build-scripts/api-reference-generation/types.mjs
Previously, if there was a multi package hierarchy (e.g. NotificationListItem) some properties were missing. With this change all properties are displayed.
In addition, implemented interfaces are added to each child component and now list with components that implement a specific interface is extended (IButton)
=> chore: fix components API hierarchy

packages/fiori/src/themes/TimelineItem.css
When having a long `subTitle` text in a `<ui5-timeline-item>`, the text is getting truncated without an ellipsis and the item is getting cut from the side.
With this change we fix the unwanted border and text cut from the side.
Fixes: #8438
=> fix(ui5-timeline-item): fix subtitle text overflows when long text provided

packages/fiori/src/themes/ShellBar.css
Fix sizing issue with the Avatar, when used as a profile within the ShellBar. The default styles for the Avatar  are applied when the `size` attribute is not present (which is the recommended way of using the Avatar in the SHellBar). The default size is `S`, so `S` size styles are applied. And, this is how exactly the Avatar is supposed to be working.
However, this was not always the case. Recently, we have fixed this in the Avatar with this change: https://github.com/SAP/ui5-webcomponents/pull/8415
Previously, prior to this change, the Avatar did not handle the case when no `size` attribute was passed, e.g
this was missing and we added this selector to cover it:
```css
:host(:not([size]))
```
Otherwise, without the change, an Avatar without size and an Avatar with Size="S" looked …
=> chore: force Avatar size, used as ShellBar profile

packages/website/docs/_components_pages/main/MessageStrip.mdx
=> docs: fix typo in MessageStrip sample

packages/base/index.js, packages/base/src/Device.ts, packages/base/test/ssr/Device.js
We're discontinuing support for Internet Explorer as it is no longer supported. With this change, we're removing all Internet Explorer-related checks from the framework.
BREAKING CHANGE: "isIE" method is removed
=> refactor(framework): remove internet explorer related checks

packages/main/src/Avatar.ts, packages/main/src/themes/Avatar.css
This update corrects the unwarranted toggle-like behaviour of the avatar on clicking. It also introduces proper active state styles to enhance the user experience.
Fixes: #8309
=> fix(ui5-avatar): revise active state styles

packages/main/src/Card.ts, packages/main/src/CardHeader.ts
Removes the `ICardHeader` interface as no other header types are currently supported or requested.
BREAKING CHANGE: Removed the `ICardHeader` interface. If you previously used the interface
```ts
import type { ICardHeader } from "@ui5/webcomponents-base/dist/Card.js"
```
Use the CardHeader type instead:
```ts
import type CardHeader from "@ui5/webcomponents-base/dist/CardHeader.js"
```
Related to [#8461](https://github.com/SAP/ui5-webcomponents/issues/8461)
=> refactor(ui5-card): remove ICardHeader interface

packages/fiori/src/UploadCollection.ts, packages/fiori/src/UploadCollectionItem.ts
Removes the `IUploadCollectionItem` interface as no other item types are currently supported or requested.
BREAKING CHANGE: Removed the `IUploadCollectionItem` interface. If you previously used the interface
```js
import type { IUploadCollectionItem} from "@ui5/webcomponents-fiori/dist/UploadCollection.js"
```
Use the `UploadCollectionItem` type instead:
```js
import type UploadCollectionItem from "@ui5/webcomponents-fiori/dist/UploadCollectionItem.js"
```
=> refactor(ui5-upload-collection): remove IUploadCollectionItem interface

packages/website/src/components/Editor/index.js, patches/playground-elements+0.18.1.patch
The `playground-preview` element has an `iframe` property that is cached and used internally. But we also use it to send configuration, and when accessed too early from outside, the shadow root is not ready and the `iframe` gets initialized with null. Because it is cached, it never initializes leading to an empty preview.
This patch makes it not cached, as the alternative to access it after the element is defined is a bit more complicated.
=> chore: don't cache iframe in case of early access

packages/fiori/src/BarcodeScannerDialog.hbs, packages/fiori/src/NotificationListGroupItem.hbs, packages/fiori/src/NotificationListItem.hbs, packages/main/src/BusyIndicator.ts, packages/main/src/ComboBoxPopover.hbs, packages/main/src/List.hbs, packages/main/src/Table.hbs, packages/main/src/themes/BusyIndicator.css, packages/main/src/types/BusyIndicatorSize.ts, packages/main/test/pages/BusyIndicator.html, packages/main/test/samples/BusyIndicator.sample.html, packages/playground/_stories/main/BusyIndicator/BusyIndicator.stories.ts, packages/website/docs/_components_pages/main/BusyIndicator.mdx, packages/website/docs/_samples/main/BusyIndicator/Basic/sample.html, packages/website/docs/_samples/main/BusyIndicator/Sizes/sample.html, packages/website/docs/_samples/main/BusyIndicator/WithComponent/sample.html
Renames the values of BusyIndicatorSize from "Small", "Medium" and "Large" to "S", "M" and "L".
BREAKING CHANGE: The `size` property now accepts different values. If you previously used it like:
```html
<ui5-busy-indicator size="Small"></ui5-busy-indicator>
```
Now use the new values instead:
```html
<ui5-busy-indicator size="S"></ui5-busy-indicator>
```
=> refactor(ui5-busy-indicator): rename BusyIndicatorSize values to S, M and L

packages/main/src/CardHeader.hbs, packages/main/src/CardHeader.ts, packages/main/src/themes/CardHeader.css, packages/main/test/pages/Card.html, packages/main/test/specs/Card.spec.js, packages/playground/_stories/main/Card/Card.stories.ts, packages/playground/_stories/main/Card/CardHeader/CardHeader.stories.ts, packages/website/docs/_samples/main/Card/Basic/sample.html, packages/website/docs/_samples/main/Card/WithList/sample.html, packages/website/docs/_samples/main/Card/WithTable/sample.html
Renames the `status` property to `additionalText` and its shadow part.
BREAKING CHANGE: The `status` property and its shadow part have been removed. If you previously used them:
```html
<style>
.cardHeader::part(status) { ... }
</style>
<ui5-card-header status="3 of 10"></ui5-popover>
```
Now use `additionalText` instead:
```html
<style>
.cardHeader::part(additional-text) { ... }
</style>
<ui5-card-header class="cardHeader" additional-text="3 of 10"></ui5-card-header>
```
=> refactor(ui5-card-header): rename status to additionalText

packages/main/src/Carousel.ts, packages/main/src/types/CarouselPageIndicatorType.ts, packages/main/test/pages/Carousel.html, packages/main/test/specs/Carousel.spec.js, packages/playground/_stories/main/Carousel/Carousel.stories.ts, packages/website/docs/_components_pages/main/Carousel.mdx, packages/website/docs/_samples/main/Carousel/PageIndicatorType/sample.html
Renames the property `pageIndicatorStyle` to `pageIndicatorType` and enumeration `PageIndicatorStyle` to `PageIndicatorType`.
BREAKING CHANGE: The `pageIndicatorStyle` no longer exists. If you previously used it like:
```html
<ui5-carousel page-indicator-style="Numeric"></ui5-carousel>
```
Now you should use `pageIndicatorType` instead:
```html
<ui5-carousel page-indicator-type="Numeric"></ui5-carousel>
```
=> refactor(ui5-carousel): rename pageIndicatorStyle to pageIndicatorType

docs/5-development/02-custom-UI5-Web-Components.md, docs/5-development/07-typescript-in-UI5-Web-Components.md, packages/base/src/UI5Element.ts, packages/base/src/decorators/customElement.ts, packages/base/src/updateShadowRoot.ts, packages/base/test/elements/Child.js, packages/base/test/elements/Generic.js, packages/base/test/elements/Parent.js, packages/base/test/elements/WithComplexTemplate.js, packages/base/test/elements/WithStaticArea.js, packages/create-package/template/src/MyFirstComponent.js, packages/main/src/SliderBase.ts
Removed the deprecated `UI5Element#render` method of the UI5Element class and replaced it with `renderer`.
BREAKING CHANGE:  Removed `UI5Element#render` method in favour of `UI5Element#renderer`. If you previously used "render"
```js
class MyClass extends UI5Element {
static get render() {
return litRenderer;
}
}
```
use "renderer"
```ts
class MyClass extends UI5Element {
static get renderer() {
return litRenderer;
}
}
```
Related to [#8461](https://github.com/SAP/ui5-webcomponents/issues/8461)
=> refactor(framework): remove render method

packages/main/src/Menu.hbs, packages/main/src/Menu.ts, packages/main/src/MenuItem.ts, packages/main/src/NavigationMenu.ts, packages/main/test/pages/Menu.html, packages/main/test/specs/Menu.spec.js
- The ui5-menu elements used for sub-menus are created only once and are being reused afterwards. They are no longer destroyed on close. This contributes to lowering the count of the slow DOM manipulation operations.
- There is now no differentiation between mobile and desktop device in regards to the display mechanism. In both cases we rely on the template to do the job as the components used for composition like ui5-list and ui5-responsive-popover do comply with the device.
Fixes: #7767
Fixes: #7423
Fixes: #6761
=> refactor(ui5-menu): adjust menu and sub-menu creation

packages/base/test/specs/ConfigurationChange.spec.js
Restoring configuration tests that were removed with #6617 by mistake
=> chore: restore configuration tests

packages/fiori/src/Assets-static.ts, packages/icons-business-suite/src/json-imports/Icons.ts, packages/icons-tnt/src/json-imports/Icons.ts, packages/icons/src/Assets-static.ts, packages/icons/src/json-imports/Icons.ts, packages/localization/lib/generate-json-imports/cldr.js, packages/localization/src/Assets-static.ts, packages/main/src/Assets-static.ts, packages/theming/src/Assets-static.ts, packages/tools/lib/generate-json-imports/i18n.js, packages/tools/lib/generate-json-imports/themes.js
Remove all Assets-static.js modules in favour of their dynamic counterparts - the Assets.js modules.
BREAKING CHANGE: All Assets-static.js modules are removed. If you previously imported any Assets-static.js module from any package:
```ts
import "@ui5/webcomponents/dist/Assets-static.js";
import "@ui5/webcomponents-icons/dist/Assets-static.js"
```
use the dynamic equivalent of it:
```ts
import "@ui5/webcomponents/dist/Assets.js";
import "@ui5/webcomponents-icons/dist/Assets.js"
```
=> refactor: remove all Assets-static.js modules

packages/main/src/Calendar.ts, packages/main/src/DatePicker.ts, packages/main/src/DatePickerPopover.hbs, packages/main/src/DateRangePicker.ts, packages/main/src/DateTimePicker.ts, packages/main/src/DateTimePickerPopover.hbs, packages/main/test/pages/Calendar.html
Renames the `selected-dates-change ` event name of the Calendar to `selection-change` and the names of two event details - `values` and `dates`  to `selectedValues` and `selectedDateValues` respectively.
BREAKING CHANGE: The event `selected-dates-change ` is renamed to `selection-change`. In addition the event details
`values` and `dates` are renamed to `selectedValues` and `selectedDateValues`. If you previously used the Calendar event as follows:
```ts
myCalendar.addEventListener("selected-dates-change", () => {
const values = e.detail.values;
const dates = e.detail.dates;
})
```
Now you have to use the new event name and details:
```ts
myCalendar.addEventListener("selection-change", () => {
const values = event.detail.selectedValues;
const dates = event.detail.selectedDateValues;
}) …
```
=> refactor(ui5-calendar):  rename `selected-dates-change`  to `selection-change` and rename few event details

packages/website/src/components/Editor/index.js
When opening a sample from the components, it overwrites the initial playground example and there is now UI to get it back.
Add a reset button that just deletes what is in local storage and refreshes the page which brings back the default example.
=> docs: add reset button in playground

packages/base/package.json, packages/fiori/package.json, packages/localization/package.json, packages/main/package.json
development machines already get chrome 123 and 121 breaks, but the GH actions image has 122 so this is the update
=> chore: update chromedriver

packages/base/src/asset-registries/LocaleData.ts
UI5 version 1.103.0 is out of support and not available on CDN any more. Update to latest long-term maintenance version 1.120.5.
Related to: #8535
=> docs: update LocaleData.ts

packages/main/src/SegmentedButtonItem.ts
Marking properties in documentation that have no effect over the control.
=> docs(ui5-segmented-button-item): add notes to inherited properties

.editorconfig
The `.editorconfig` does not explicitly set `indent_style` which causes some IDEs to assume `space` is the default.
=> chore: set tab in editorconfig

packages/main/src/Carousel.hbs, packages/main/test/specs/Carousel.spec.js
=> fix(ui5-carousel): Fixed paging indicator numbers in right-to-left (RTL) mode

packages/main/src/ColorPalette.ts, packages/main/src/ColorPicker.hbs, packages/main/src/ColorPicker.ts, packages/main/test/pages/ColorPicker.html, packages/main/test/specs/ColorPalette.spec.js, packages/main/test/specs/ColorPicker.spec.js, packages/playground/_stories/main/ColorPicker/ColorPicker.stories.ts, packages/website/docs/_samples/main/ColorPicker/Basic/sample.html
Renames the `color` property name of the ColorPicker to `value` and the names of two private properties.
BREAKING CHANGE: The property `color`  is renamed to `value`. If you previously used the change event of the ColorPicker as follows:
```html
<ui5-color-picker color="red"></ui5-color-picker>
```
Now you have to use it like this:
```html
<ui5-color-picker value="red"></ui5-color-picker>
```
=> refactor(ui5-color-picker): rename `color` to `value`

packages/main/src/ColorPalettePopover.ts, packages/main/test/pages/ColorPalettePopover.html, packages/main/test/samples/ColorPalettePopover.sample.html, packages/playground/_stories/main/ColorPalettePopover/ColorPalettePopover.stories.ts, packages/website/docs/_samples/main/ColorPalettePopover/Basic/main.js, packages/website/docs/_samples/main/ColorPalettePopover/Basic/sample.html, packages/website/docs/_samples/main/ColorPalettePopover/DefaultColor/main.js, packages/website/docs/_samples/main/ColorPalettePopover/DefaultColor/sample.html, packages/website/docs/_samples/main/ColorPalettePopover/MoreColors/main.js, packages/website/docs/_samples/main/ColorPalettePopover/MoreColors/sample.html
Removes the `openPopover` and `showAt` methods from the `ui5-color-palette-popover`.
BREAKING CHANGE:
The `openPopover` and `showAt` methods are removed in favor of `open`  and `opener` properties. If you previously used the imperative API:
```js
button.addEventListener("click", function(event) {
colorPalettePopover.showAt(this);
});
```
Now the declarative API should be used instead:
```html
<ui5-button id="opener">Open</ui5-button>
<ui5-color-palette-popover opener="opener">
```
```js
button.addEventListener("click", function(event) {
colorPalettePopover.open = !colorPalettePopover.open;
});
```
Related to: #8461
=> refactor(ui5-color-palette): remove deprecated APIs

packages/website/docs/_samples/fiori/IllustratedMessage/WithDialog/main.js, packages/website/docs/_samples/fiori/MediaGallery/Interactive/main.js, packages/website/docs/_samples/fiori/Page/Basic/main.js, packages/website/docs/_samples/fiori/Page/FloatingFooter/main.js, packages/website/docs/_samples/fiori/Wizard/PageMode/main.js, packages/website/docs/_samples/main/Dialog/BarInDialog/main.js
Correct imports are now used after we moved the ui5-bar control to main library.
=> fix(ui5-bar): fix import in samples

packages/main/src/Tab.ts, packages/main/src/TabContainer.hbs, packages/main/src/TabContainer.ts, packages/main/src/TabSeparator.ts, packages/main/test/pages/TabContainer.html, packages/main/test/pages/TabContainerDragAndDrop.html, packages/main/test/samples/TabContainer.sample.html, packages/playground/_stories/main/TabContainer/Tab/Tab.stories.ts, packages/playground/_stories/main/TabContainer/TabContainer.stories.ts, packages/website/docs/_samples/main/TabContainer/NestedTabs/sample.html
Renames 'subTabs' slot of ui5-tab to 'items'.
BREAKING CHANGE: If you have previously used:
```html
<ui5-tab id="nestedTab" slot="subTabs"></ui5-tab>
```
Now use:
```html
<ui5-tab id="nestedTab" slot="items"></ui5-tab>
```
Relates to https://github.com/SAP/ui5-webcomponents/issues/8461
=> Rename subTabs slot

packages/main/src/themes/Avatar.css, packages/main/src/themes/Badge.css, packages/main/src/themes/base/Badge-parameters.css
This commit rectifies the badge alignment inside the avatar that was disrupted after commit #7564. The badge is now properly aligned within the avatar enhancing its visual appeal.
Fixes: #8491
=> fix(ui5-avatar): correct badge style

packages/main/src/DayPicker.ts, packages/main/test/specs/Calendar.spec.js
With support of new cldr, we add one more symbol allowance in the check for the day names length.
=> fix(ui5-day-picker): improve  day name length check

packages/main/src/ProgressIndicator.hbs, packages/main/src/ProgressIndicator.ts, packages/main/test/pages/ProgressIndicator.html, packages/main/test/pages/styles/ProgressIndicator.css
=> feat(ui5-progress-indicator): introduce "bar" CSS part

packages/fiori/src/IllustratedMessage.ts, packages/fiori/test/pages/IllustratedMessage.html, packages/fiori/test/specs/IllustratedMessage.spec.js, packages/playground/_stories/fiori/IllustratedMessage/IllustratedMessage.stories.ts
Renames the `size` property  of  the `ui5-illustrated-message` to `design`.
The semantic values `Auto`, `Base`, `Spot`, `Dialog`, `Scene` and size aspect of this property is not directly clear.
BREAKING CHANGE: The `size` property of the `ui5--illustrated-message` is renamed to `design`.
If you have previously used the `size` property:
```html
<ui5-illustrated-message size="Dialog">
```
Now use `design` instead:
```html
<ui5-illustrated-message design="Dialog">
```
=> refactor(ui5-illustrated-message): rename `size` property to `design`

packages/main/src/Breadcrumbs.ts, packages/main/src/themes/Breadcrumbs.css, packages/main/src/types/BreadcrumbsSeparator.ts, packages/main/test/pages/Breadcrumbs.html, packages/main/test/samples/Breadcrumbs.sample.html, packages/playground/_stories/main/Breadcrumbs/Breadcrumbs.stories.ts, packages/website/docs/_samples/main/Breadcrumbs/BreadcrumbsStyles/sample.html
Renames the `separator-style` property  of `ui5-breadcrumbs` to `separators`.
Also the `BreadcrumbsSeparatorStyle` enum is renamed to `BreadcrumbsSeparator`
BREAKING CHANGE: The `separator-style` property is renamed to  `separators` and the `BreadcrumbsSeparatorStyle` enum is renamed to `BreadcrumbsSeparator`.
If you have previously used the `separator-style` property:
```html
<ui5-breadcrumbs separator-style="Slash">
```
Now use  `separators`  instead:
```html
<ui5-breadcrumbs separators="Slash">
```
=> refactor(ui5-breadcrumbs): rename property separator-style to separators

packages/fiori/src/ShellBar.ts
Icons used inside `ui5-shellbar`'s template are not scoped because `ui5-icon` is not described as dependency of it. In addition `slim-arrow-down` is imported otherwise it wasn't loaded.
Fixes: #8609
=> fix(ui5-shellbar): scope internally used icons

packages/main/src/Option.ts, packages/main/src/ProgressIndicator.hbs, packages/main/src/ProgressIndicator.ts, packages/main/src/Select.ts, packages/main/test/pages/ProgressIndicator.html, packages/main/test/pages/Select.html, packages/main/test/pages/styles/ProgressIndicator.css, packages/playground/_stories/main/Select/Option/Option.stories.ts
Removes the `disabled` property  of  the `ui5-option`, since UX and ACC standards suggest to not include any disabled items in the dropdown.
BREAKING CHANGE: The `disabled` property of the `ui5-option`is removed.
If you have previously used the `disabled` property:
```html
<ui5-option disabled>Option</ui5-option>
```
it will no longer work for the component.
=> refactor(ui5-option): remove disabled property

packages/main/src/themes/TabSeparatorInOverflow.css, packages/main/src/themes/TabSeparatorInStrip.css
Unlike `ui5-tab`, `ui5-tab-separator` uses the same class name in both the strip and overflow, therefore it needs stronger selectors for both places.
This was an oversight from the popover API refactoring change, and is now fixed.
=> fix(ui5-tab-separator): styling in overflow

packages/base/src/UI5Element.ts, packages/base/test/elements/AccessorBase.js
When a property decorator is used in a base class, the generated getter/setter for the extending class should look up the accessors through the prototype chain and use them.
=> chore: property accessor should be looked up the prototype chain

packages/main/src/Tab.ts, packages/main/src/TabContainer.ts, packages/main/src/TabSeparator.ts, packages/main/test/specs/TabContainer.spec.js
Renames Tab#getTabInsStripDomRef and TabSeparator#getTabInsStripDomRef to getDomRefInStrip.
BREAKING CHANGE: If previously you have used:
```js
someTab.getTabInsStripDomRef();
someTabSeparator.getTabInsStripDomRef();
```
Now use:
```js
someTab.getDomRefInStrip();
someTabSeparator.getDomRefInStrip();
```
=> refactor(ui5-tab, ui5-tab-separator): rename getTabInStripDomRef to getDomRefInStrip

packages/base/src/util/dragAndDrop/DragRegistry.ts
This PR fixes a TypeScript build error introduced with v1.24.0
```
node_modules/@ui5/webcomponents-base/dist/util/dragAndDrop/DragRegistry.d.ts:1:29 - error TS2835: Relative import paths need explicit file extensions in ECMAScript imports when '--moduleResolution' is 'node16' or 'nodenext'. Did you mean '../../UI5Element.js'?
1 import type UI5Element from "../../UI5Element";
```
=> fix(DragRegistry - TypeScript): correct import

packages/fiori/src/UploadCollection.ts, packages/fiori/src/UploadCollectionItem.hbs, packages/fiori/src/UploadCollectionItem.ts, packages/fiori/src/themes/UploadCollectionItem.css, packages/fiori/src/types/UploadCollectionSelectionMode.ts, packages/fiori/test/pages/UploadCollection.html, packages/fiori/test/specs/UploadCollection.spec.js, packages/playground/_stories/fiori/UploadCollection/UploadCollection.stories.ts, packages/website/docs/_samples/fiori/UploadCollection/Basic/sample.html
Removes the "Delete" option of `selectionMode` of `ui5-upload-collection`. So far this property didn't have any effect.
BREAKING CHANGE: The `selectionMode` property no longer accepts "Delete" as value.
If you have previously used it:
```html
<ui5-upload-collection selection-mode="Delete"></ui5-upload-collection>
```
Now omit it completely:
```html
<ui5-upload-collection></ui5-upload-collection>
```
=> refactor(ui5-upload-collection): remove Delete selection mode

packages/main/src/ProgressIndicator.hbs, packages/main/src/ProgressIndicator.ts, packages/main/src/themes/ProgressIndicator.css, packages/main/test/pages/ProgressIndicator.html, packages/playground/_stories/main/ProgressIndicator/ProgressIndicator.stories.ts, packages/website/docs/_components_pages/main/ProgressIndicator.mdx, packages/website/docs/_samples/main/ProgressIndicator/States/sample.html
Removes the `disabled` property  of  the `ui5-progress-indicator`. 
The Progress Indicator isn't an interactive element, therefore the disabled property make no sense. 
Also aria-disabled is deprecated on the `progressbar` role since ARIA 1.2 .
BREAKING CHANGE: The `disabled` property of the `ui5-progress-indicator` is removed.
If you have previously used the `disabled` property:
```html
<ui5-progress-indicator disabled value="60"></ui5-progress-indicator>
```
it will no longer work for the component.
=> refactor(ui5-progress-indicator): remove disabled property

packages/main/src/List.hbs, packages/main/src/List.ts, packages/main/src/themes/List.css, packages/main/test/pages/List.html, packages/main/test/specs/List.spec.js, packages/playground/_stories/main/List/List.stories.ts, packages/website/docs/_samples/main/List/Growing/main.js, packages/website/docs/_samples/main/List/Growing/sample.html, packages/website/docs/_samples/main/List/GrowingOnButtonPress/main.js, packages/website/docs/_samples/main/List/GrowingOnButtonPress/sample.html
Renames the `busy`, `busyDelay` property of the `ui5-list` to `loading` and `loadingDelay`.
BREAKING CHANGE: The `busy` property of the `ui5-list` is renamed.
If you have previously used the `busy`, `busyDelay` properties:
```html
<ui5-list busy busy-delay="500"></ui5-list>
```
now you must use  `loading` and `loadingDelay` properties:
```html
<ui5-list loading loading-delay="500"></ui5-list>
```
Related: #8461 #7887
=> refactor(ui5-list): renamed busy, busyDelay to loading, loadingDelay

packages/main/src/Popup.ts
In 1.x it was possible to have this code:
```js
(new Dialog()).show()
```
without appending the dialog to the DOM tree, and it would work without throwing any errors (would just show the block layer) because the static area item was forced to be rendered even without the dialog itself being rendered.
In 2.x the same code throws a runtime error, because the blocking layer is not available before the component has been rendered (the shadow root is empty).
This fixes the error, although it is not a real use case.
=> fix(Popup): prevent a rare runtime error

packages/main/src/Menu.ts, packages/main/test/pages/Menu.html, packages/main/test/specs/Menu.spec.js
Change the event names in menu from `after-close` and `after-open` to `close` and `open`.
BREAKING CHANGE: Event names `after-close` and `after-open` are now named `open` and `close`.
Previously the application developers could include the ui5-bar as follows:
```ts
menu.addEventListener("ui5-after-open", function() {
//...
});
menu.addEventListener("ui5-after-close", function() {
/....
});
```
Now the application developers should include the ui5-bar as follows:
```ts
menu.addEventListener("ui5-open", function() {
//...
});
menu.addEventListener("ui5-close", function() {
/....
});
```
=> refactor(ui5-menu): rename open and close events

packages/main/test/specs/Menu.spec.js
The failing test often asserts that there are **2** items instead of **4**
The reason is this code in `Menu.html`
```js
menu.addEventListener("ui5-before-open", function(event) {
const item = event.detail.item;
if (item && item.text === "Open" && !fetched) {
setTimeout(function() {
item.removeAttribute("busy");
item.removeAttribute("busy-delay");
let oneNode = document.createElement("ui5-menu-item");
oneNode.setAttribute("text", "Open from Amazon Cloud");
let twoNode = document.createElement("ui5-menu-item");
twoNode.setAttribute("text", "Open from Google Cloud");
item.append(oneNode, twoNode);
fetched = true;
}, 1000);
}
});
```
There is a timeout of **1000ms** that adds **2** more items, and thus the total number of items becomes **4**.
However, the test does not account for this …
=> chore(ui5-menu): fix unstable test

packages/base/src/UI5Element.ts, packages/base/test/elements/Accessor.js, packages/base/test/specs/Accessor.spec.js
property decorators on accessors (getter/setter) introduced with #8587 and later modified to search accessors in the prototype chain with #8643 now have a problem when a property defined in a component has an accessor in HTMLElement.
For example, Link has a property `title`, HTMLElement has а `get title`. The current lookup finds the HTMLElement getter and starts using this. However having a class field `title` in the link means the component should use this one, especially for the default value. Setting `title = undefined` on the field works, but if there is a HTMLElement getter and it is used, it returns an empty string `''`.
This change stops searching for accessors when HTMLElement is reached. For the rest of the cases, TypeScript has a warning that a getter/setter pair cannot be …
=> fix: decorators stop searching for accessors when reaching HTMLElement

packages/base/src/UI5Element.ts, packages/base/src/UI5ElementMetadata.ts, packages/base/src/decorators/customElement.ts, packages/main/src/Button.ts, packages/main/test/pages/Button.html, packages/main/test/specs/Button.spec.js
The base class `UI5Element` calls `this.attachShadow({ mode: "open" });` and there is no way for components to change the mode or add other options.
This change adds a `shadowRootOptions` property to the `customElement` decorator.
```ts
@customElement({
tag: "ui5-button",
shadowRootOptions: { delegatesFocus: true },
```
full list of options on MDN:
https://developer.mozilla.org/en-US/docs/Web/API/Element/attachShadow#options
The specific need for `delegatesFocus` is the way focus handling works with slots (in Chrome specifically).
```html
<ui5-button>
text
<span>slotted text</span>
test
</ui5-button>
```
When the `text` nodes are clicked, the custom elements matches the `:focus` selector and any `focusin` handlers in the shadowRoot are called.
When the `slotted text` is clicked however, …
=> feat: add shadowRootOptions for @customElement decorator

packages/website/docusaurus.config.ts
docusaurus is building pages without a trailing slash, for example from the sitemap.xml
```xmls
<url>
<loc>
https://sap.github.io/ui5-webcomponents/components/Button
</loc>
<changefreq>weekly</changefreq>
<priority>0.5</priority>
</url>
```
Then github makes a redirect to a trailing slash url:
This in turn prevents google from indexing the pages
`Page is not indexed: Page with redirect`
=> docs: change to trailing slash urls to skip redirects

packages/fiori/src/themes/ShellBar.css
Visual alignments done to meet the last Visual specification updates
=> fix(ui5-shellbar): aligned specs

packages/main/src/themes/SplitButton.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/8615
=> fix(ui5-split-button): add correct opacity when disabled

packages/fiori/src/WizardTab.hbs, packages/fiori/src/WizardTab.ts
As part of Aria 1.2 support enhancement, aria-disabled attribute is no longer supported for elements with role="listitem". Remove aria-disabled attribute, which is used in disabled ui5-wizard-tab component.
=> refactor(ui5-wizard-tab): remove aria-disabled attribute

packages/base/package-scripts.cjs, packages/base/package.json, packages/base/tsconfig.json, packages/tools/components-package/nps.js, packages/tools/lib/dev-server/ssr-dom-shim-loader.js, vite.config.js, yarn.lock
UI5Element imports a ssr-dom.js file via the package in order to use the export conditions for SSR and serve a shim.
This confuses TS in watch mode and it treats the file as both input and output throwing an error that it cannot be overwritten.
This change ignores the ssr-dom.js file in TS completely and generates it in dist and fixes the dev server to load an empty one.
=> chore: fix dev time error in ts checker

packages/fiori/src/ShellBar.ts, packages/fiori/src/themes/ShellBar.css
ui5-shellbar assistant icon's color now has the accurate color, according to VD Spec.
=> fix(ui5-shellbar): assistant icon color fixed

packages/fiori/src/BarcodeScannerDialog.ts, packages/fiori/test/pages/BarcodeScannerDialog.html, packages/website/docs/_samples/fiori/BardcodeScannerDialog/Basic/main.js
This change adds support for `close` and `open` events to the barcode scanner dialog. Along with this change, the documentation and the sample have been updated.
Fixes #8695
=> feat(ui5-barcode-scanner-dialog): add support for close and open events

packages/main/src/ComboBox.ts, packages/main/test/specs/ComboBox.spec.js
Removes the `change` event firing on navigation in the suggestion of  the `ui5-combobox`, since the navigation is not considered a change confirmation by the user and is not final.
A change event is fired when a user confirm changes in the input field - focus out, Enter key press or item selection (via click or Enter key press on a item).
BREAKING CHANGE: The `change` event is not fired on item navigation anymore, use `selection-change` event instead.
Related to https://github.com/SAP/ui5-webcomponents/issues/8461 https://github.com/SAP/ui5-webcomponents/issues/7890
=> refactor(ui5-combobox): remove firing of change event on navigation

packages/fiori/src/BarcodeScannerDialog.hbs, packages/fiori/src/BarcodeScannerDialog.ts, packages/fiori/test/pages/BarcodeScannerDialog.html
Changes:
- deleted the `open` event (events are only fired upon user interaction and there is only user interaction for `close`)
- fixed the bug where the component would not work if the open property is set initially
- fixed the bug where the `close` event is fired when the component is closed programmatically (not upon user interaction)
- made use of declarative APIs.
BREAKING CHANGE:
The `show` and `close` public methods have been removed. Use the public property `open` instead.
For example, if you used:
```js
d.show();
...
d.close();
```
use:
```js
d.open = true;
...
d.open = false;
```
instead.
=> chore(ui5-barscanner-dialog): use declarative APIs

packages/main/src/MenuListItem.ts
Fixes #8745
This PR fixes the scoping issue of the `MenuItem`. I'm not sure if there's more changes necessary, but locally and when patching `@ui5/webcomponents` inside the node_modules it solved the issue for me. If there are more adjustments required, please feel free to use this branch.
=> fix(ui5-menu-item): apply scoping to internal `Icon`

packages/main/src/TextArea.ts, packages/main/src/themes/TextArea.css, packages/main/test/pages/TextArea.html, packages/main/test/specs/TextArea.spec.js, packages/playground/_stories/main/TextArea/TextArea.stories.ts, packages/website/docs/_samples/main/TextArea/Growing/sample.html
Renames the `growingMaxLines` property of `ui5-textarea`.
If you have previously used the `growingMaxLines` property 
```html
<ui5-textarea growing growing-max-lines="5"></ui5-textarea>
```
Now use `growingMaxRows` instead:
```html
<ui5-textarea growing growing-max-rows="5"></ui5-textarea>
```
BREAKING CHANGE: The `growingMaxLines` property  have been renamed to `growingMaxRows`.
Related to: #8461
=> refactor(ui5-textarea): rename property growingMaxLines to growingMaxRows

packages/main/src/MessageStrip.ts, packages/main/src/i18n/messagebundle.properties, packages/main/src/themes/MessageStrip.css, packages/main/src/themes/base/MessageStrip-parameters.css, packages/main/src/themes/sap_belize_hcb/MessageStrip-parameters.css, packages/main/src/themes/sap_belize_hcw/MessageStrip-parameters.css, packages/main/src/themes/sap_fiori_3/MessageStrip-parameters.css, packages/main/src/themes/sap_fiori_3/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_dark/MessageStrip-parameters.css, packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_hcb/MessageStrip-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/MessageStrip-parameters.css, packages/main/src/themes/sap_horizon_dark/MessageStrip-parameters.css, packages/main/src/themes/sap_horizon_hcb/MessageStrip-parameters.css, packages/main/src/themes/sap_horizon_hcw/MessageStrip-parameters.css, packages/main/src/types/MessageStripDesign.ts, packages/main/test/pages/MessageStrip.html, packages/main/test/specs/MessageStrip.spec.js, packages/website/docs/_components_pages/main/MessageStrip.mdx, packages/website/docs/_samples/main/MessageStrip/CustomColors/CustomColors.md, packages/website/docs/_samples/main/MessageStrip/CustomColors/main.js, packages/website/docs/_samples/main/MessageStrip/CustomColors/sample.html
With the following enhancement, the end user will be able to create message strips with custom colors from a predefined set of colors. That is achieved enhancing the `design` property enum `MessageStripDesign` with two new options `ColorSet1` and `ColorSet2` as well as the newly introduced property `colorScheme`.
Setting the `design` property value to `ColorSet1` or `ColorSet2`, then you are able to choose between 10 different colors for each using `colorScheme` property with values from "1" to "10".
=> feat(ui5-message-strip): introduce custom colors

packages/main/src/Icon.hbs, packages/main/src/Icon.ts, packages/main/src/themes/Icon.css
Adjusted `ui5-icon` focus display rules. On desktop, focus outline is always visible. For mobile, focus outline only appears with an external keyboard, it remains hidden for touch focus.
Related to: #8320
=> chore(ui5-icon): update focus handling

docs/2-advanced/07-accessibility.md, packages/main/src/Link.hbs, packages/main/src/Link.ts, packages/main/test/pages/Link.html, packages/main/test/specs/Link.spec.js
The a11y experts suggested using our own property and not reusing the standard `title` property as title attribute will both present on the custom element and inside the shadow root. Having tooltip on the custom element and the title set at only one place is more reliable.
Related to: https://github.com/SAP/ui5-webcomponents/issues/8461 https://github.com/SAP/ui5-webcomponents/issues/8353
=> feat(ui5-link): introduce `tooltip` property

packages/main/src/MultiComboBox.ts, packages/main/test/pages/MultiComboBox.html, packages/playground/_stories/main/MultiComboBox/MultiComboBox.stories.ts, packages/website/docs/_components_pages/main/MultiComboBox/MultiComboBox.mdx, packages/website/docs/_samples/main/MultiComboBox/ClearIcon/sample.html, packages/website/docs/_samples/main/MultiComboBox/MultiComboBoxCustomValue/sample.html
Renames the `allowCustomValues` property of ui5-multi-combobox.
If you have previously used the `allowCustomValues` property
`<ui5-multi-combobox allow-custom-values></ui5-multi-combobox>`
Now use noValidation instead:
`<ui5-multi-combobox no-validation></ui5-multi-combobox>`
BREAKING CHANGE: The `allowCustomValues` property have been renamed to `noValidation`.
=> refactor(ui5-multi-combobox): rename property allowCustomValues to noValidation

packages/main/src/TreeItemCustom.ts
Previously it was impossible to properly use keyboard inside input elements nested in TreeItemCustom. Now the handling is similar to CustomListItem and input elements can be used as expected.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7566
=> fix(ui5-tree-item-custom): improved key handling

packages/main/src/themes/ProgressIndicator.css
Removed redundant z-index which causes PI to overlap over some of its parent elements.
Fixes: #8303
=> fix(ui5-progress-indicator): removed redundant z-index

packages/website/blog/releases/popover-api-in-v2.mdx
Read here: https://github.com/SAP/ui5-webcomponents/blob/popover-api-blog/packages/website/blog/releases/popover-api-in-v2.mdx
=> docs: add popover API blog post

packages/main/src/Menu.hbs, packages/main/src/Menu.ts, packages/main/src/MenuItem.ts, packages/main/src/MenuListItem.ts, packages/main/src/NavigationMenu.hbs, packages/main/test/pages/Menu.html, packages/main/test/specs/Menu.spec.js, packages/playground/_stories/main/Menu/MenuItem/MenuItem.stories.ts
Renames the `busy` and `busyDelay` properties of the `ui5-menu` and `ui5-menu-item` to `loading` and `loadingDelay`.
BREAKING CHANGE: The `busy` and `busyDelay` and properties of the `ui5-menu` and `ui5-menu-item` are renamed.
If you have previously used the `busy`, `busyDelay` properties:
```html
<ui5-menu header-text="My ui5-menu" busy busy-delay="100"><ui5-menu>
```
```html
<ui5-menu-item text="Open" icon="open-folder" busy busy-delay="100"><ui5-menu-item>
```
now you should use  `loading` and `loadingDelay` properties:
```html
<ui5-menu header-text="My ui5-menu" loading loading-delay="100"><ui5-menu>
```
```html
<ui5-menu-item text="Open" icon="open-folder" loading loading-delay="100"><ui5-menu-item>
```
Fixes: #8764
=> refactor(ui5-menu): rename the busy and busy delay properties

packages/fiori/src/themes/ShellBar.css
Reverts SAP/ui5-webcomponents#8694
Seems that with this change the specificity of the selectors is getting too strong and this leads to redundant need for
adding the same specificity in other selectors, which complicates the css logic.
=> Revert "fix(ui5-shellbar): aligned specs" 

packages/main/src/themes/SplitButton.css, packages/main/test/pages/SplitButton.html
Previously when our `ui5-split-button` component was wrapped in a container with defined height, f.e:
<div style="border: 1px solid red; height: 80px">
<ui5-split-button style="width: 100%;" icon="picture">Random Text</ui5-split-button>
</div>
The button was filling the whole space in the container, which wasn't the desired behaviour:
Now the `ui5-split-button`'s height is not based on outside wrappers.
Fixes: #8705
=> fix(ui5-split-button): restrict height manipulation from outside wrapper

packages/main/src/ListItem.hbs, packages/main/src/ListItem.ts
The `role` property  of  the `ui5-li` is removed.
=> refactor(ui5-li): removes role property

packages/fiori/src/MediaGallery.ts, packages/fiori/src/MediaGalleryItem.hbs, packages/fiori/src/MediaGalleryItem.ts, packages/fiori/src/themes/MediaGalleryItem.css
Adjusted `ui5-media-gallery` focus display rules. On desktop, focus outline is always visible. For mobile, focus outline only appears with an external keyboard, it remains hidden for touch focus.
Related to: #8320
=> chore(ui5-media-gallery): update focus handling

packages/fiori/src/ShellBar.ts, packages/fiori/src/themes/ShellBar.css
Adjusted `ui5-shellbar` focus display rules. On desktop, focus outline is always visible. For mobile, focus outline only appears with an external keyboard, it remains hidden for touch focus.
Related to: #8320
=> chore(ui5-shellbar): update focus handling

packages/fiori/src/themes/ShellBar.css, packages/main/src/MultiComboBox.ts, packages/tools/lib/scoping/lint-src.js
- made the tool work with `.ts` files (it was still set for `.js` and wasn't working until now)
- mede the tool strip all comments first so we now allow to mention tag names in comments without causing lint errors
- fixed a scoping issue
=> chore: fix the lint scoping tool

packages/main/src/themes/Link.css, packages/main/src/themes/base/Link-parameters.css, packages/main/src/themes/sap_belize_hcb/Link-parameters.css, packages/main/src/themes/sap_belize_hcw/Link-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/Link-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/Link-parameters.css, packages/main/src/themes/sap_horizon/Link-parameters.css, packages/main/src/themes/sap_horizon_dark/Link-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/Link-parameters.css, packages/main/src/themes/sap_horizon_exp/Link-parameters.css, packages/main/src/themes/sap_horizon_hcb/Link-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/Link-parameters.css, packages/main/src/themes/sap_horizon_hcw/Link-parameters.css, packages/main/src/themes/sap_horizon_hcw_exp/Link-parameters.css, packages/main/test/specs/Link.spec.js
Issue:
- There was a transparent border displacing the link's text horizontally. It is mostly visible if there is an actual text component underneath. Solution:
- The border is replaced by an outline with an offset. Now the ui5-link component doesn't have an invisible border and it is compliant with the visual specification.
Fixes: #8512
=> fix(ui5-link): remove unnecessary transparent border

packages/fiori/src/Wizard.ts, packages/fiori/test/pages/Wizard_test.html
Rename `changeWithClick` to `withScroll` in the `WizardStepChangeEventDetail`.
If the application code relied on `qchangeWithClic` event detail, it should now rely on `withScroll` event detail instead. The `withScroll` parameter will be set to true when the event is fired due to user scrolling.
BREAKING CHANGE: `changeWithClick` was renamed to `withScroll` in the `WizardStepChangeEventDetail`.
JIRA: BGSOFUIRILA-3867
Related to: #8461
=> refactor(ui5-wizard): rename event parameter 

packages/fiori/test/pages/NotificationListGroupItem.html, packages/fiori/test/pages/NotificationListItem.html, packages/fiori/test/pages/ShellBar.html, packages/main/src/Toast.ts, packages/main/test/pages/Popover.html, packages/main/test/pages/Toast.html, packages/website/docs/_samples/main/Toast/Basic/main.js, packages/website/docs/_samples/main/Toast/Duration/main.js, packages/website/docs/_samples/main/Toast/Placement/main.js
Users now can open `ui5-toast` using the `open` property. A new event `after-close` is introduced.
It may be used to sync app state with the `open` state of the `ui5-toast`.
BREAKING CHANGE: The Toast#show method has been replaced by  `open` property. If you previously used  `toast.show()` to show the toast, you must now se `toast.open=true`.
Related to: #8461
=> refactor(ui5-toast): replace `show` method with `open` property

packages/main/src/SegmentedButtonItem.ts, packages/main/test/pages/SegmentedButton.html, packages/main/test/specs/SegmentedButton.spec.js
With #8669 `ui5-segmented-button-item` was separated from `ui5-toggle-button`. During the separation few properties were missed.
=> chore: add missing properties to ui5-segmented-button-item

packages/main/src/List.hbs, packages/main/src/List.ts, packages/main/src/ListItem.ts, packages/main/src/Menu.hbs, packages/main/src/NavigationMenu.hbs, packages/main/src/Tree.ts, packages/main/src/types/ListAccessibleRole.ts, packages/main/src/types/ListItemAccessibleRole.ts, packages/main/test/specs/Menu.spec.js
Changes the type of `accessibleRole` property  for both `ui5-li` and `ui5-list`.
BREAKING CHANGE: The `accessibleRole` property for both `ui5-li` and `ui5-list` has been updated from a string type to an enum type. 
Additionally, the new enums `ListItemAccessibleRole` and `ListAccessibleRole` have been introduced for these properties respectively.
The available options for the `ui5-li`:
`ListItem`- Represents the ARIA role "listitem". (by default)
`MenuItem`  -  Represents the ARIA role "menuitem".
`TreeItem ` -  Represents the ARIA role "treeitem".
`Option ` -  Represents the ARIA role "option".
`None` - Represents the ARIA role "none".
The available options for the `ui5-list`:
`List`- Represents the ARIA role "list".  (by default)
`Menu`  -  Represents the ARIA role "menu".
`Tree` - …
=> refactor(ui5-li, ui5-list): changes accessibleRole type

packages/main/src/Option.ts, packages/main/src/Select.ts, packages/main/src/SelectPopover.hbs, packages/main/test/pages/Select.html, packages/main/test/specs/Select.spec.js, packages/playground/_stories/main/Select/Option/Option.stories.ts
The private `title` property, previously available in the `ui5-option` component, has been removed. 
It is replaced by a new property named `tooltip`, used for defining the text of the tooltip that would be displayed for the `ui5-option` component.
Now, you can set the tooltip of the `ui5-option` as it follows:
```html
<ui5-select id="selectTooltip">
<ui5-option tooltip="Cozy">Cozy</ui5-option>
<ui5-option tooltip="Compact">Compact</ui5-option>
<ui5-option selected tooltip="Condensed">Condensed</ui5-option>
</ui5-select>
```
Related to: https://github.com/SAP/ui5-webcomponents/issues/8461, https://github.com/SAP/ui5-webcomponents/issues/7887
=> feature(ui5-option): tooltip property added

packages/main/src/ToggleSpinButton.hbs, packages/main/src/ToggleSpinButton.ts
The SR announcement of the top buttons (hours/minutes/seconds) in TimePicker/DateTimePicker wasn't correct because of wrong role of these buttons - it was "button" but must be "spinbutton".
This PR solves the issue.
Fixes: #7980
=> fix(ui5-time-picker): fix buttons announcements in value help dialog

packages/base/src/features/OpenUI5Support.ts, packages/base/src/features/patchPatcher.ts, packages/base/src/features/patchPopup.ts, packages/main/test/pages/OpenUI5.html
Background: UI5 Web Components popups use the popover API, therefore are always above OpenUI5 popups, which use the static area.
In order for OpenUI5 popups to be able to show on top of components popups, they must also use the popover API and top layer. This change adapts `Popup.js` to use the popover API.
How it works:
- `OpenUI5Support` patches 2 functions of `sap/m/Popup.js` and injects a tiny bit of CSS into the document
- If there is nothing in the **top layer**, OpenUI5 behaves normally (the patched functions don't do extra work)
- But if the popover API has been used (there is somethin in the **top layer**), then OpenUI5 also uses the top layer for any consequent popups (popups open up to this point are unaffected)
=> chore(OpenUI5Support): patch OpenUI5 Popup.js to support the Popover API

packages/website/docs/_components_pages/compat/Table/Table.mdx, packages/website/docs/_components_pages/compat/Table/TableCell.mdx, packages/website/docs/_components_pages/compat/Table/TableColumn.mdx, packages/website/docs/_components_pages/compat/Table/TableGroupRow.mdx, packages/website/docs/_components_pages/compat/Table/TableRow.mdx
The Table page url still hinting as it's part of the main package - `components/Table`
while it should be `components/compat/Table`.
=> chore: update slug in Table*.mdx

packages/main/src/Button.hbs, packages/main/src/Button.ts, packages/main/src/DatePicker.ts, packages/main/src/DatePickerInput.hbs, packages/main/src/Icon.ts, packages/main/src/Select.hbs, packages/main/src/StandardListItem.hbs, packages/main/src/themes/Icon.css, packages/main/src/types/IconMode.ts, packages/main/test/pages/Icon.html, packages/main/test/specs/Icon.spec.js, packages/playground/_stories/main/Icon/Icon.stories.ts, packages/playground/docs/landing-page.html, packages/website/docs/_samples/main/Icon/Interactive/sample.html
The properties `ariaHidden` , `interactive` and `accessibleRole` , previously available in the `ui5-icon` component, have been removed. 
They are replaced by a new property named `mode`.
BREAKING CHANGE: The properties `ariaHidden` , `interactive` and `accessibleRole` , previously available in the `ui5-icon` component, have been removed. They are replaced by a new property named `mode` that specifies the component's mode. 
Alongside this update, a new enumeration `IconMode`, has been introduced to outline the available options for this property:
`Image`: This is the default setting. It configures the component to internally render `role="img"`.
`Interactive`: Configures the component to internally render `role="button"`. This mode also supports focus and press handling to enhance …
=> refactor(ui5-icon): add mode property

packages/main/src/MultiInput.ts, packages/main/test/specs/MultiInput.spec.js
related to #8712
**Note:**
To determine whether or not to focus the last token we rely on the JS's `.selectionStart` to check if the caret is at the start of the input (right before the tokens). However, [Selection is only permitted with text/search, URL, tel and password](http://www.whatwg.org/specs/web-apps/current-work/multipage/the-input-element.html#do-not-apply). The likely reason that selection has been disabled for inputs of type number is that on some devices, or under some circumstances (e.g., when the input has been is presented as a short list), there might not be a caret.
So to determine if we should focus the last token in cases of inputs of type 'Number' and 'Email' now we check if there is a text value or not. This means that the (edge) case when there is a value and the …
=> fix(ui5-multi-input): focus tokens on BACKSPACE for inputs of type 'Number' and 'Email'

packages/website/build-scripts/api-reference-generation/types.mjs
JSON file for each interface / enum with metadata was previously generated. With this PR the generation is stopped because these files are no longer needed.
=> chore: stop generating unused files

packages/main/src/themes/Dialog.css
Downport of https://github.com/SAP/ui5-webcomponents/pull/8839
=> fix(ui5-dialog): state icon no longer shrinks when title is too long

packages/fiori/src/SideNavigation.ts
Downport of b58948676049565410592700b1796475f1ea94fa
=> fix(ui5-side-navigation): replace items and fixedItems union type with SideNavigationItemBase

packages/main/test/specs/Button.spec.js
Test was not valid and it was't testing correctly the scenario since it wasn't awaiting the getAttribute method.
=> chore: fix ui5-button test

packages/fiori/src/themes/UploadCollection.css, packages/fiori/src/themes/base/UploadCollection-parameters.css, packages/fiori/src/themes/sap_horizon/UploadCollection-parameters.css, packages/fiori/src/themes/sap_horizon_dark/UploadCollection-parameters.css, packages/fiori/src/themes/sap_horizon_hcb/UploadCollection-parameters.css, packages/fiori/src/themes/sap_horizon_hcw/UploadCollection-parameters.css
Downport ```ui5-upload-collection``` drag and drop overlay colors change
Related to #8616
=> fix(ui5-upload-collection): correct drag and drop text and icon color

packages/main/src/MonthPicker.hbs, packages/main/src/MonthPicker.ts, packages/main/src/themes/Calendar.css, packages/main/src/themes/MonthPicker.css
Previously when `secondaryCalendarType` was set to `Islamic` or `Persian`, the texts of the months' names didnt had enough space in the cell to be displayed on one row, which wasnt the desired behavior.
Now, when any of those two calendar types is set as a `secondaryCalendarType`, when the end user is in month view of the calendar, the months are displayed in two column layout, instead of three, providing enough space for the texts to be displayed in one row.
Tested in both Cozy/Compact modes in following scenarios:
------------------------------
1. Gregorian/Buddhist
2. Gregorian/Islamic
3. Gregorian/Japanese
4. Gregorian/Persian
5. Buddhist/Gregorian
6. Buddhist/Islamic
7. Buddhist/Japanese
8. Buddhist/Persian
9. Islamic/Gregorian
10. Islamic/Buddhist
11. Islamic/Japanese
12. …
=> fix(ui5-calendar): switch to two column layout on Islamic or Persian secondary calendar type

packages/fiori/test/specs/ShellBar.spec.js
Closes #8766 
- Rewrite test with timeouts to `browser. pause ` API.
- Failing tests are adapted to overflow rules of the shellbar's breakpoints.
- The copilot is not rendered any more in the center and the items overflow at smaller sizes.
- Height of the browser window is increased as there are more shellbars on the page now and the scrollbars messed with the width. Testing the breakpoints on the egde of the range was incorrect.
=> test(ui5-shellbar): stabilize tests with timeouts

packages/main/src/FileUploader.hbs, packages/main/src/FileUploader.ts
Issue:
- A file could be dragged over a very small transparent area representing the inner input type file. That would mean that the same file couldn't be dropped over the most of the visible ui5-file-uploader DOM. Solution:
- Dragged files will be dropped over the root component area.
Fixes: #8572
=> fix(ui5-file-uploader): adjust drop area

packages/fiori/src/UploadCollectionItem.hbs, packages/fiori/test/pages/F6TestPage.html, packages/fiori/test/pages/FCL.html, packages/fiori/test/pages/Wizard.html, packages/fiori/test/pages/WizardPageMode_test.html, packages/fiori/test/pages/Wizard_test.html, packages/fiori/test/pages/Wizard_test_mobile.html, packages/main/src/BusyIndicator.hbs, packages/main/src/Label.ts, packages/main/src/themes/Label.css, packages/main/test/pages/Kitchen.html, packages/main/test/pages/Kitchen.openui5.html, packages/main/test/pages/Label.html, packages/main/test/specs/Label.spec.js, packages/playground/_stories/fiori/Wizard/Wizard.stories.ts, packages/playground/_stories/fiori/Wizard/WizardStep/WizardStep.stories.ts, packages/playground/_stories/main/Panel/Panel.stories.ts, packages/website/docs/_components_pages/main/Label.mdx, packages/website/docs/_samples/fiori/Wizard/Basic/sample.html, packages/website/docs/_samples/fiori/Wizard/PageMode/sample.html, packages/website/docs/_samples/main/Label/TextWrapping/sample.html, packages/website/docs/_samples/main/Panel/Basic/sample.html, packages/website/docs/_samples/main/Panel/CustomHeader/sample.html, packages/website/docs/_samples/main/Panel/Fixed/sample.html, packages/website/docs/_samples/main/Panel/StickyHeader/sample.html
The text of `ui5-label` now wraps by default.
BREAKING CHANGE: `wrapping-type` property default value has changed from `None` to `Normal`.
Before: 
```html
<ui5-label>some very very very long label</ui5-label> 
```
Now:
```html
<ui5-label>some very very very long label</ui5-title> 
```
=> refactor(ui5-label): wrap text by default

packages/main/src/themes/NavigationMenu.css
Background:
After making the `ui5-responsive-popover` a native popover, `width: auto` stretches it to take the whole available space width.
Solution:
Make it take only as much as it needs by leveraging its default width `fit-content`.
Related to: https://github.com/SAP/ui5-webcomponents/issues/8739
=> fix(ui5-side-navigation): menu in collapsed mode width is not longer stretched unnecessary

packages/main/src/Dialog.ts, packages/main/src/Popover.ts, packages/main/src/Popup.ts, packages/main/src/themes/Popover.css, packages/main/test/pages/Popover.html, packages/main/test/pages/styles/Popover.css, packages/playground/_stories/main/Popover/Popover.stories.ts, packages/playground/_stories/main/ResponsivePopover/ResponsivePopover.stories.ts
Remove the hideBackdrop property
BREAKING CHANGE: Property `hideBackdrop` is removed.
Previously the application developers could define a modal popover without visible backdrop as follows:
```
<ui5-popover modal hide-backdrop>
```
Now the application developers can use the standard [`::backdrop` CSS selector](https://developer.mozilla.org/en-US/docs/Web/CSS/::backdrop)
```
<style>
.transparentBackdrop::backdrop {
background: transparent;
}
</style>
...
<ui5-popover modal class="transparentBackdrop">
```
Related to #8461
=> refactor(ui5-popover): remove hideBackdrop property

packages/fiori/src/BarcodeScannerDialog.hbs, packages/fiori/src/ShellBarPopover.hbs, packages/fiori/src/SideNavigationPopover.hbs, packages/fiori/src/ViewSettingsDialog.hbs, packages/main/src/ColorPalettePopover.hbs, packages/main/src/ComboBoxPopover.hbs, packages/main/src/DatePickerPopover.hbs, packages/main/src/InputPopover.hbs, packages/main/src/Menu.hbs, packages/main/src/MultiComboBoxPopover.hbs, packages/main/src/NavigationMenu.hbs, packages/main/src/Popover.ts, packages/main/src/Popup.ts, packages/main/src/ResponsivePopover.hbs, packages/main/src/SelectMenu.hbs, packages/main/src/SelectPopover.hbs, packages/main/src/TimePickerPopover.hbs, packages/main/src/Tokenizer.ts, packages/main/src/TokenizerPopover.hbs, packages/main/src/ToolbarPopover.hbs, packages/main/test/pages/DialogLifecycle.html, packages/main/test/pages/OpenUI5.html, packages/main/test/pages/Popover.html
Change the event names in popup from `after-close` and `after-open` to `close` and `open`.
BREAKING CHANGE: Event names `after-close` and `after-open` are now named `close` and `open`.
Previously the application developers could subscribe to the events as follows:
```ts
popup.addEventListener("ui5-after-open", function() {
//...
});
popup.addEventListener("ui5-after-close", function() {
//...
});
```
Now the application developers should include the ui5-bar as follows:
```ts
popup.addEventListener("ui5-open", function() {
//...
});
popup.addEventListener("ui5-close", function() {
//...
});
```
Related to #8461
=> refactor(ui5-popup): rename after-open and after-close events to 'open' and 'close'

packages/main/src/NavigationMenu.ts, packages/main/src/themes/NavigationMenu.css
Problem: `NavigationMenuItem` was not proper dependency of `SideNavigation`, therefore the private `ui5-navigation-menu-item` elements were not upgraded.
Solution: Import `NavigationMenuItem`.
Also fixes height issue that appeared after Popover API adoption.
Fixes https://github.com/SAP/ui5-webcomponents/issues/8242
=> fix(ui5-side-navigation): overflow menu items are now displayed

packages/fiori/src/SideNavigationSelectableItemBase.ts, packages/fiori/test/pages/SideNavigation.html, packages/fiori/test/specs/SideNavigation.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8692
=> fix(ui5-side-navigation-item): click event is no longer fired twice

docs/Migrating to version 2.0 guide.md, packages/main/src/Select.ts, packages/main/src/SelectMenu.ts, packages/main/src/Toast.ts, packages/playground/_stories/main/SplitButton/SplitButton.stories.ts
ui5-toast:  rename event `after-close` to `close`
BREAKING CHANGE: The `after-close`  event has been renamed to `close`. If you previously used it like:
```ts
toast.addEventListener("after-close", (event) => {
});
```
Now you have to use it like:
```ts
toast.addEventListener("close", (event) => {
});
```
=> refactor(ui5-toast): rename event `after-close` to `close`

packages/base/src/config/AnimationMode.ts
As currently written, it is impossible to use `setAnimationMode()` to disable animations because it is impossible to set the current mode to a valid option.  The conditional statement `if (animationMode in AnimationMode)` checks if the the passed-in `animationMode` matches one of the property/key names of the `AnimationMode` enum (the uppercase strings "Full", "Basic", "Minimal", or "None") rather than the actual values (lowercase strings), which means the uppercase values are the only options the function recognizes and will change the current mode to.  However, when a component like the `ui5-progress-indicator` checks whether to use animations, it compares the current animation mode to the lowercase string "none", which means animations will always be used regardless of what is passed …
=> fix(ui5-*): Make setAnimationMode() properly change modes

packages/fiori/src/DynamicPage.hbs, packages/fiori/src/DynamicPage.ts, packages/fiori/src/DynamicPageHeaderActions.hbs, packages/fiori/src/DynamicPageHeaderActions.ts, packages/fiori/src/DynamicPageTitle.ts, packages/fiori/src/themes/DynamicPageTitle.css, packages/fiori/test/pages/DynamicPage.html
Issues fixed:
1. Expand / collapse, pin buttons are visible even if header is not used
2. Title is missing visual separator (shadow) when header doesn't exist
3. If the header is snapped while the user is at the top of the page, it can't be expanded via scroll (deviation with openui5)
4. If the user starts to scroll from the position where header is snapped (basically around 0-5 top) and scroll a bit up the whole header appear.
5. Hovering expand / collapse button doesn't change ui5-dynamic-page-title background color
6. Only DynamicPageHeaderActions class should be described here since it's the only component of the family that is used directly in the hbs template.
7. why do we need to use querySelector here instead of this.navigationActions. In the documentation of the slot it's not …
=> fix(dynamic-page): final review visual issues

packages/main/src/CustomListItem.ts, packages/main/src/List.ts, packages/main/src/ListItemBase.ts, packages/main/src/StandardListItem.ts, packages/main/src/TreeItemBase.ts, packages/website/docs/_components_pages/main/List/List.mdx, packages/website/docs/_components_pages/main/Tree/Tree.mdx, packages/website/docs/_samples/main/List/DragAndDrop/DragAndDrop.md, packages/website/docs/_samples/main/List/DragAndDrop/main.js, packages/website/docs/_samples/main/List/DragAndDrop/sample.html, packages/website/docs/_samples/main/Tree/DragAndDrop/DragAndDrop.md, packages/website/docs/_samples/main/Tree/DragAndDrop/main.js, packages/website/docs/_samples/main/Tree/DragAndDrop/sample.html
The drag&drop feature for both `ui5-tree` and `ui5-list` components is now public. 
Updated documentation and new samples have been added to assist with implementation.
=> feat(ui5-list,ui5-tree): make drag&drop feature public

packages/fiori/src/themes/IllustratedMessage.css
The specs have been updated and now the subtitle color should use `--sapTextColor` variable, instead of `--sapContent_LabelColor`.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8984
=> fix(ui5-illustrated-mesasge): update subtitle color

packages/main/src/ListItemGroup.hbs, packages/main/src/ListItemGroup.ts, packages/main/test/specs/ListItemGroup.spec.js
Introduce `focused` attribute to implement fake focus feature in suggestion items.
=> refactor(ui5-li-group): forward focused attribute to header item

packages/main/src/Form.hbs, packages/main/src/Form.ts
Form header line is displayed even if headerText="" empty string and looks strange. 
Show form header line only if non-empty headerText or header slot are present.
=> chore: show form header line only if headerText or header slot

packages/localization/src/dates/calculateWeekNumber.ts, packages/main/src/DayPicker.ts
Previously when a `calendarType` was being set to `Islamic` or `Buddhist` in the document configuration, and a `primary-calendar-type="Gregorian"` on a date component level where week numbering is present, for example `<ui5-date-picker primary-calendar-type="Gregorian">`, `<ui5-calendar primary-calendar-type="Gregorian"`, etc the week numbers were calculated wrong.
```js
<script data-ui5-config type="application/json">
{
"language": "en_US",
"rtl": false,
"calendarType": "Islamic"
}
</script>
```
```html
<ui5-date-picker primary-calendar-type="Gregorian"></ui5-date-picker>
```
After the change, the weeks are calculated correctly now.
Fixes: #6835
=> fix(ui5-calendar): respect component level calendarType in week calculation

packages/base/src/Boot.ts
In SSR enviroments, regsterCurrentRuntime is skipped and the current runtime index does not get initialized. With nextjs SSR, hot reload loads two instances of the framework, which triggers the duplicate tags reporting logic, which breaks because it relies on the index being defined.
This fix runs the current runtime index initialization for all scenarios.
FIXES: #8886
=> fix: register runtime in ssr usage

packages/main/src/DateComponentBase.ts, packages/main/src/DateTimePicker.ts
The DateTimePicker was calling an inherited getFormat method, which was creating an instance with getDateInstance method. 
Now we are using the correct format created with getDateTimeInstance method.
=> fix(ui5-datetime-picker): change dateformat to datetime instance

packages/fiori/src/SideNavigationItem.hbs, packages/fiori/src/SideNavigationSubItem.hbs, packages/fiori/test/specs/SideNavigation.spec.js
Fixes https://github.com/SAP/ui5-webcomponents/issues/8790
=> fix(ui5-side-navigation-item): "selected" is no longer announced on every focused item

packages/main/src/ToolbarButton.hbs, packages/main/src/ToolbarButton.ts, packages/main/src/ToolbarPopoverButton.hbs, packages/main/test/pages/ToolbarButton.html, packages/main/test/specs/ToolbarButton.spec.js
ToolbarButton now can have second icon at the end
BREAKING CHANGE:  iconEnd property is changed from boolean to string type and now can accept name for second/end icon.
Before:
`<ui5-toolbar-button icon="home" icon-end>Button</ui5-toolbar-button>`
Now:
`<ui5-toolbar-button end-icon="home">Button</ui5-toolbar-button>`
or 
`<ui5-toolbar-button icon="employee" end-icon="home">Button</ui5-toolbar-button>`
=> feat(ui5-toolbar-button): add second (end) icon

packages/main/src/MultiInput.ts, packages/main/test/specs/MultiInput.spec.js
=> fix(ui5-multi-input): delete selected value on BACKSPACE

packages/main/src/Select.ts
Problem: When we type an item which is outside of the scroll viewport, the item is selected but the popover is not scrolled to it.
Solution: We make sure to scroll to the typed item.
Fixes: #8987
=> fix(ui5-select): popover scrolls to typed item

packages/base/src/StaticArea.ts, packages/base/src/util/InvisibleMessage.ts
Previously the ui5-static-area custom element was used to host all popovers, but now it's being used only by the InvisibleMessage for accessibility needs to announce opening of popups, so we rename it to ui5-announcement-area to avoid confusion with the previous purpose of the element.
=> chore: replace ui5-static-area with ui5-announcement-area

packages/ai/src/Assets.ts, packages/ai/src/Button.hbs, packages/ai/src/Button.ts, packages/ai/src/bundle.esm.ts, packages/ai/test/pages/Button.html, packages/ai/tsconfig.json
Icons and other test assets are now imported in the ai/bundle/esm.ts and available in test pages
=> chore: enable test assets for `ai` test pages

packages/main/src/MultiComboBox.ts, packages/main/src/MultiInput.ts, packages/main/src/TabContainer.ts, packages/main/src/TimeSelectionClocks.ts, packages/main/src/TimeSelectionInputs.ts, packages/main/src/Tokenizer.ts
When a component is using another components in its template, used components must be added to its dependencies in order to get the same scoping. With this change dependencies are fulfilled as in: #8823
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9030
=> fix(ui5-*): describe missing dependencies

packages/main/src/TimePicker.hbs, packages/main/src/TimePicker.ts, packages/main/src/TimePickerPopover.hbs, packages/main/test/specs/TimePicker.spec.js
Add `open` property to replace the `openPicker` method in the `ui5-time-picker` component.
BREAKING CHANGE: Removed `openPicker()`, `closePicker()`, and `isOpen()` methods.
Before, the `ui5-time-picker` popover could be opened and closed by calling `openPicker()` and `closePicker()`:
```ts
const timePicker = document.getElementById("exampleID");
timePicker.openPicker();
timePicker.closePicker();
```
Now, the popover is opened and closed by setting the `open` property to true or false:
```ts
const timePicker = document.getElementById("exampleID");
timePicker.open = true;
timePicker.open = false;
```
=> feat(ui5-time-picker): introduce `open` property

packages/main/test/pages/Button.html, packages/website/docs/_samples/main/Button/MenuButton/main.js
MenuButton samples were published while open/opener wasn't introduced for `ui5-menu`. Now these samples (Dev and Playground) are fixed to work with open/opener.
=> fix(ui5-button): adjust ui5-button menu button samples to use open/opener

packages/fiori/src/NotificationListGroupItem.hbs, packages/fiori/src/NotificationListGroupItem.ts, packages/fiori/src/NotificationListItem.hbs, packages/fiori/src/NotificationListItem.ts, packages/fiori/src/NotificationListItemBase.ts, packages/fiori/src/i18n/messagebundle.properties, packages/fiori/test/pages/NotificationListGroupItem.html, packages/fiori/test/pages/NotificationList_test_page.html, packages/fiori/test/specs/NotificationList.spec.js, packages/website/docs/_components_pages/fiori/NotificationListGroupItem.mdx, packages/website/docs/_samples/fiori/NotificationListGroupItem/Basic/main.js, packages/website/docs/_samples/fiori/NotificationListGroupItem/InShellBar/main.js, packages/website/docs/_samples/fiori/NotificationListItem/Basic/main.js
- read state is announced after the title (before it was at the end of the notification)
- "notification" word is removed from the description
- "important" should be announced before the title and the status text, since it is valuable information for the user and should be in the beginning
- status icon in the title should have tooltip
- there should be "loading" announcement (after the title) for items, which are in loading state
- ACC attributes are added for "More"/"Less" link, following the example of (openui5) sap.m.ExpandableText
- tooltip for the expand/collapse arrow in the group header is moved to the whole header
- tooltip for the group header is changed to static "Expand/Collapse" (doesn't change depending on the expand state of the group), following the example of ui5-panel …
=> fix(ui5-notification-list): improved accessibility

packages/main/src/TimePicker.ts, packages/main/src/TimePickerPopover.hbs
As we introduced a declaritive property `open` which controls wether the value-help dialog of the `<ui5-timepicker>` is open or not, we are now introducing `open` and `close` events fired **after** the value-help dialog is opened or closed.
Fixes: #9076
=> feat(ui5-time-picker): introduce `open` and `close` events

packages/main/src/Option.ts, packages/main/src/OptionCustom.ts
The selectors for focus outline don't match as the desktop attribute was missing, not set for the OptionCustom (as in the Option)
Before
After
- there is console error for missing dependency as the Option uses the Icon in its template
=> fix(ui5-option-custom): show focus outline

packages/fiori/src/NotificationListItem.hbs, packages/fiori/src/TimelineItem.hbs, packages/fiori/src/UploadCollectionItem.hbs, packages/main/src/Breadcrumbs.hbs, packages/main/src/Link.ts, packages/main/src/themes/Link.css, packages/main/test/pages/Link.html, packages/website/docs/_components_pages/main/Link.mdx, packages/website/docs/_samples/main/Link/TextWrapping/sample.html
The text of `ui5-link` now wraps by default.
BREAKING CHANGE: `wrapping-type` property default value has changed from `None` to `Normal`.
Before: 
```html
<ui5-link>some very very very long link</ui5-link> 
```
Now:
```html
<ui5-link>some very very very long link</ui5-link> 
```
=> refactor(ui5-link): wrap text by default

packages/main/src/Button.ts, packages/main/src/ListItemBase.ts, packages/main/src/Menu.ts, packages/main/src/MenuItem.hbs, packages/main/src/MenuItem.ts, packages/main/src/themes/MenuItem.css, packages/main/test/pages/Menu.html, packages/main/test/specs/Menu.spec.js, packages/website/docs/_components_pages/main/Menu/Menu.mdx, packages/website/docs/_samples/main/Menu/MenuEndContent/MenuEndContent.md, packages/website/docs/_samples/main/Menu/MenuEndContent/main.js, packages/website/docs/_samples/main/Menu/MenuEndContent/sample.html
New slot `endContent` is introduced in `ui5-menu-item` component. This slot accepts components that are displayed at the end of the Menu Item if it does not have sub-menu. If there are components slotted and also additionalText is being set, the additionalText will not be shown as well. 
It is strongly recommended  to slot only icon-only `ui5-button`, `ui5-icon` or `ui5-link` components.
BGSOFUIBALKAN-8160
#6350
=> feat(ui5-menu-item): add endContent slot

packages/fiori/src/NotificationList.ts, packages/main/src/RadioButton.ts, packages/main/src/themes/RadioButton.css, packages/main/test/pages/Kitchen.html, packages/main/test/pages/Kitchen.openui5.html, packages/main/test/pages/RadioButton.html, packages/website/docs/_components_pages/main/RadioButton.mdx, packages/website/docs/_samples/main/RadioButton/TextWrapping/sample.html
The text of `ui5-radio-button` now wraps by default.
BREAKING CHANGE: `wrapping-type` property default value has changed from `None` to `Normal`. Before:
```html
<ui5-radio-button text="Option A with long long text"></ui5-radio-button>
```
Now:
```html
<ui5-radio-button text="Option A with long long text"></ui5-radio-button>
```
=> refactor(ui5-radio-button): wrap text by default

packages/main/src/Popover.ts, packages/main/src/Select.ts, packages/main/src/SelectPopover.hbs, packages/main/test/pages/Select.html
Introduced `popover` `csspart` to the Select.
Now we can alter the popover styles (its max-height for example) with the following CSS:
```
#selectPopoverMaxHeight[ui5-select]::part(popover) {
max-height: 120px;
}
```
Implements: #4503
=> feat(ui5-select): introduced 'popover' part

packages/main/src/ComboBox.hbs, packages/main/src/Input.hbs, packages/main/src/MultiComboBox.hbs
=> fix(ui5-input, ui5-combobox, ui5-multi-combobox): prevent native input autocomplete

packages/main/src/CalendarDate.ts
`ICalendarSelectedDates` was imported in CalendarDate.ts without type keyword and this results into import of Calendar component making circular dependency.
=> fix(ui5-date): remove circular dependency

packages/main/src/Button.ts, packages/main/src/ListItemBase.ts
[feat(ui5-menu-item): add endContent slot](https://github.com/SAP/ui5-webcomponents/pull/9077) PR introduces a regression in Tab chaining in lists because of improper marking of `keyup` event in `ui5-button` component. It was marked always but should be marked only if event is fired by Space key. In addition, there is redundant check in ListItemBase which is removed now.
=> fix(ui5-button): fix tab chaining in lists

packages/main/src/ToolbarButton.ts
- Rename ToolbarAccessibilityAttributes to Toolbar**Button**AccessibilityAttributes as it's the ToolbarButton component
- Create the type explicitly in the ToolbarButton file, so that it is correctly referenced from `dist/ToolbarButton` (not `dist/Button`) in the custom-elements-manifest file.
=> chore(ui5-toolbar-button): rename accAttrs type name

packages/fiori/src/SideNavigationSelectableItemBase.ts, packages/main/src/SegmentedButtonItem.ts, packages/main/src/Tokenizer.ts, packages/tools/lib/cem/custom-elements-manifest.config.mjs
Add validation that checks correct usage of `@extends` and `@implements` JSDoc tags. Validations also check whether the tag has same value in heritage clause.
Example:
```
| === ERROR: Problem found in file: src/SuggestionItem.ts:
| 	- @interface { IInputSuggestionItem } tag is used, but the class doesn't implement the corresponding interface
| === ERROR: Problem found in file: src/Tokenizer.ts:
| 	- @extends sap.ui.webc.base.UI5Element is used, but the class doesn't extend the corresponding superclass
```
=> chore(tools): add more validation in cem generation

packages/main/src/themes/ListItemBase.css
Previous change (8b19ea9de825fac65847413dbe578d13407646b0) moved some CSS styles from the :host element to the first element in the shadow DOM. This caused issues with applying overrides. This commit reverts those styles back to :host to restore expected behavior.
=> fix(ui5-list-item): move styles back from shadow DOM element to :host

packages/main/src/Form.ts, packages/main/src/FormGroup.ts, packages/main/src/FormItem.ts
Mark `IFormItem` as public to display which items might be used inside default slot of `ui5-form` element.
=> docs(ui5-form): enhance IFormItem interface

packages/fiori/src/SideNavigationItem.ts
event.pointerType is not supported in Firefox browser, therefore the
check if event is with mouse is changed to check if the action is done in desktop
Fixes: #9057
=> fix(ui5-side-navigation-item): wholeItemToggleable works in Firefox

packages/main/src/Grid.ts, packages/main/src/GridHeaderRow.ts, packages/main/src/themes/GridHeaderRow.css
When a component is using another components in its template, used components must be added to its dependencies in order to get the same scoping.
=> chore: describe correct dependencies

packages/compat/src/bundle.esm.ts, packages/main/src/bundle.common.bootstrap.ts, packages/main/src/bundle.esm.ts
Split the button into two parts:
- All common imports related to configuration, etc.
- Component imports
Before, `bundle.esm.ts` was used as import in `bundle.esm.ts` compat. This caused a conflict when `ui5-grid` component were renamed to `ui5-table`, which is blocking the renaming.
With this change, we only use configuration imports and explicitly import only the components we need from other packages in `bundle.esm.ts` compat.
=> chore: split bundle

packages/fiori/src/BarcodeScannerDialog.hbs, packages/fiori/src/BarcodeScannerDialog.ts
Issue is fixed where when closing the BarcodeScannerDialog with 'ESC' key, the 'close' event isn't fired.
Now 'close' event is properly fired regardless of the way the dialog is closed.
Fixes: #9177
=> fix(ui5-barcode-scanner-dialog): properly fire 'close' event

packages/fiori/src/SideNavigationItem.ts, packages/fiori/test/pages/SideNavigation.html, packages/fiori/test/pages/SideNavigationOnly.html, packages/fiori/test/pages/SideNavigationWithGroups.html, packages/fiori/test/specs/SideNavigation.spec.js
BREAKING CHANGE: the `wholeItemToggleable` property of `ui5-side-navigation-item` is now removed. The functionality of clicking the whole item to show/hide the sub items is no longer available. The collapsing/expanding of the item can still be done by pressing the icon.
Related to #9057
=> refactor(ui5-side-navigation-item): remove wholeItemToggleable property

packages/main/src/themes/SegmentedButtonItem.css, packages/main/test/pages/SegmentedButton.html
fixes: https://github.com/SAP/ui5-webcomponents/issues/9172
Previous state:
State with the fix:
=> fix(ui5-segmented-button-item): add padding to icon when item is not in icon-only mode

packages/main/src/themes/sap_horizon/ProgressIndicatorLayout-parameters.css, packages/main/src/themes/sap_horizon/rtl-parameters.css
RTL parameters should be added as described in `rtl-parameters.css`. Otherwise, it might cause issues when PostCSS processes the CSS files.
For example, CSS variables that control icon appearance are broken because `[dir="rtl"]` is moved before the `:root` selector after PostCSS preprocessing:
Related to: #9133
=> chore: rearrange RTL related variables

packages/main/src/themes/TreeItem.css
Added CSS rule to set cursor to default when `_mode` attribute is not present
Fixes: #9146
=> fix(ui5-tree-item): ensure correct cursor style

packages/main/src/themes/sap_horizon/ProgressIndicatorLayout-parameters.css, packages/main/src/themes/sap_horizon/rtl-parameters.css
RTL parameters should be added as described in `rtl-parameters.css`. Otherwise, it might cause issues when PostCSS processes the CSS files.
For example, CSS variables that control icon appearance are broken because `[dir="rtl"]` is moved before the `:root` selector after PostCSS preprocessing:
Fixes: #9133
=> fix: rearrange RTL related variables

packages/fiori/src/NotificationListItem.hbs, packages/fiori/src/NotificationListItem.ts, packages/fiori/src/themes/NotificationListItem.css, packages/fiori/test/specs/NotificationList.spec.js
- the "More"/"Less" button (link) is not read when focusing the notification item. Now the "More"/"Less" button is announced only when the focus is on it.
- “tag” word before “Important” is not removed since it comes from the ui5-tag component and needs to be announced
fixes #9161
=> fix(ui5-li-notification): enhance accessibility

packages/fiori/src/NotificationListItemBase.ts, packages/main/src/ListItem.ts, packages/main/src/ListItemBase.ts, packages/main/src/ListItemGroupHeader.ts, packages/main/src/Option.ts, packages/main/src/OptionCustom.ts
The `ListItemBase` component now manages its focus styles, but previously required subclasses to set the `desktop` attribute. This update modifies `ListItemBase.ts` to directly set the `desktop` attribute, and thus completes the focus functionality.
=> chore: (ListItemBase): ensure desktop attribute is set for focus styles

packages/main/src/CheckBox.ts, packages/main/src/themes/CheckBox.css, packages/main/test/pages/CheckBox.html, packages/main/test/pages/Kitchen.html, packages/main/test/pages/Kitchen.openui5.html, packages/website/docs/_components_pages/main/CheckBox.mdx, packages/website/docs/_samples/main/CheckBox/TextWrapping/sample.html
The text of `ui5-checkbox` now wraps by default.
BREAKING CHANGE: `wrapping-type` property default value has changed from `None` to `Normal`.
Before: 
```html
<ui5-checkbox text=Some very very very very long text"></ui5-checkbox>
```
Now:
```html
<ui5-checkbox text=Some very very very very long text"></ui5-checkbox> 
```
=> refactor(ui5-checkbox): wrap text by default

packages/main/src/BusyIndicator.ts, packages/main/src/themes/BusyIndicator.css, packages/main/src/themes/base/BusyIndicator-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/BusyIndicator-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_hcw/BusyIndicator-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css, packages/main/src/themes/sap_horizon_hcb/BusyIndicator-parameters.css, packages/main/src/themes/sap_horizon_hcw/BusyIndicator-parameters.css
According to the design if busy indicator is used over some component there should be transparent background as overlay.
fixes #9079
=> fix(ui5-busy-indicator): add block layer

packages/main/src/DatePicker.ts, packages/main/src/DatePickerPopover.hbs, packages/main/src/DateRangePicker.ts, packages/main/src/DateTimePicker.ts, packages/main/src/TimePicker.ts, packages/main/src/TimePickerPopover.hbs, packages/main/src/i18n/messagebundle.properties, packages/main/test/specs/DatePicker.spec.js, packages/main/test/specs/DateRangePicker.spec.js, packages/main/test/specs/DateTimePicker.spec.js, packages/main/test/specs/TimePicker.spec.js
=> fix(ui5-date-picker): provide accessible name to the popover (#8693)

packages/base/src/features/OpenUI5Support.ts
`sap.ui.version` will be removed in future OpenUI5 versions and will cause the code to break.
=> chore: adapt OpenUI5 version check

package.json
`eslint` runs slow on Windows machines. On average it takes from 100 to 300 seconds to complete, sometimes even more.
=> chore: remove husky:lint

packages/main/src/MessageStrip.hbs, packages/main/src/MessageStrip.ts, packages/main/test/pages/MessageStrip.html, packages/main/test/specs/MessageStrip.spec.js, packages/website/src/css/custom.css
Changing design from value-states to color-set does remove the value state icon.
Fixes #9181
=> fix(ui5-message-strip): Remove icon when design changes to a color set

packages/base/src/features/OpenUI5Support.ts, packages/base/src/features/patchPopup.ts, packages/main/test/pages/DialogAndOpenUI5Dialog.html
Part of #9028
Downport of #9183
=> fix(ui5-dialog): fix focusing when dialog is open from OpenUI5 dialog

packages/main/src/themes/TabContainer.css
When display was "inline-block" there was a small gap on the top of the TabContainer. 
Now display is changed to "block" and this gap is gone. 
In addition display "block" is most suitable for the tab-container.
BREAKING CHANGE: the `display` CSS property of the `tab-container` is changed from `inline-block` to `block`
related to: #9248
=> fix(ui5-tab-container): change display

packages/main/src/BusyIndicator.ts, packages/website/docs/_components_pages/main/TabContainer/TabContainer.mdx, packages/website/docs/_samples/main/TabContainer/NestedTabs/sample.html, packages/website/docs/_samples/main/TabContainer/OverflowMode/sample.html, packages/website/docs/_samples/main/TabContainer/OverflowModeStartAndEnd/OverflowModeStartAndEnd.md, packages/website/docs/_samples/main/TabContainer/OverflowModeStartAndEnd/main.js, packages/website/docs/_samples/main/TabContainer/OverflowModeStartAndEnd/sample.html, packages/website/docs/_samples/main/TabContainer/TabLayout/sample.html, packages/website/docs/_samples/main/TabContainer/TabLayoutInline/TabLayoutInline.md, packages/website/docs/_samples/main/TabContainer/TabLayoutInline/main.js, packages/website/docs/_samples/main/TabContainer/TabLayoutInline/sample.html, packages/website/docs/_samples/main/TabContainer/TextOnlyTabs/sample.html
The documentation page with the samples now have descriptions added,
the samples are bigger in height and every sample contains only one TabContainer.
fixes: #9248
=> fix(ui5-tab-container): enhance documentation page

packages/website/build-scripts/api-reference-generation/component-file.mjs
Currently, `custom-elements.json` contains information whether the property is readonly but this information is not displayed in the component documentation pages. With this change the information is displayed.
=> chore: display readonly information

packages/tools/lib/hbs2ui5/index.js
Template generation has code that checks if the same content is produced and does not write the file to skip a refresh from the dev server.
This logic was broken and comparing a Buffer to a String leading to always refreshing the file content even if it is the same
FIXES: #9276
RELATED: #8824
=> fix: template result comparison

packages/main/test/pages/TableLoading.html, packages/main/test/specs/TableLoading.spec.js
- correct loading-delay attribute, it was not applied and 1000 default was used
- set 100ms timeout before pressing tab, so that the busy indicator has time to render
=> chore: improve unstable test

packages/main/src/MultiComboBoxPopover.hbs
With the following change the `ui5-multicombobox` component is now fully compliant with the Aria 1.2 specification.
=> chore(ui5-multi-combobox): comply with latest aria spec

.github/workflows/release-stable.yaml, lerna.json, package.json, yarn.lock
Updates `lerna` to version 7 to adopt the following [feature](https://github.com/lerna/lerna/issues/3727) exposing new option `--force-conventional-graduate` that should be used with `--conventional-graduate` to force publish all packages even when no changes are done to synchronise packages. 
Previously we used `--force-publish`, but it wasn't working always fine as described in the [issue](https://github.com/lerna/lerna/issues/3727), that has been resolved with the [change](https://github.com/lerna-lite/lerna-lite/pull/743/files) and released in `lerna@7.4.1`
We did not use any of the removed, changed APIs introduced with the v7 major, the only change adopted is that `useWorkspaces` setting in `lerna.json` is now by default and can be omitted.
=> chore: update lerna from v6 to v7

packages/main/src/ComboBoxPopover.hbs, packages/main/src/MultiComboBoxPopover.hbs
With the following change `ui5-combobox` and `ui5-multicombobox` are now compliant with the Aria 1.2 specification.
=> chore(ui5-combobox, ui5-multi-combobox): comply with latest aria spec

packages/main/src/Popup.ts
Before, the `ui5-open` event is fired even if the component was not part of the DOM. Now, the `ui5-open` event is fired only if the component is still in the DOM tree.
Example:
Component is detach from the DOM during execution of `openPopup` function which is waiting `renderFinished` to be done.
=> fix(Popup): correct "open" event

packages/ai/src/Button.ts, packages/ai/src/ButtonState.ts, packages/compat/src/TableColumn.ts, packages/fiori/src/FilterItem.ts, packages/fiori/src/NotificationListItemBase.ts, packages/main/src/Card.ts, packages/main/src/CheckBox.ts, packages/main/src/ComboBox.ts, packages/main/src/DatePicker.ts, packages/main/src/Input.ts, packages/main/src/ListItemCustom.ts, packages/main/src/ListItemGroup.ts, packages/main/src/ListItemStandard.ts, packages/main/src/Menu.ts, packages/main/src/MenuItem.ts, packages/main/src/MultiComboBox.ts, packages/main/src/MultiInput.ts, packages/main/src/RadioButton.ts, packages/main/src/RangeSlider.ts, packages/main/src/RatingIndicator.ts, packages/main/src/SegmentedButtonItem.ts, packages/main/src/SliderBase.ts, packages/main/src/SplitButton.ts, packages/main/src/SuggestionItem.ts, packages/main/src/TimePicker.ts, packages/main/src/ToolbarButton.ts, packages/main/src/TreeItemBase.ts, packages/main/src/features/InputSuggestions.ts
With the introduction of property initializers (https://github.com/SAP/ui5-webcomponents/pull/8846) many properties have changed they default values or types but on some places:
- JSDoc wasn't changed
- Properties with declared `declare` keyword were using wrong type
This change fixes most of the things until custom element analyzer plugin is adjusted to generate correct output
=> refactor: align different properties

packages/fiori/src/IllustratedMessage.ts, packages/fiori/src/types/IllustrationMessageDesign.ts
As follow up of #8605 the enumeration of the design property is renamed to IllustrationMessageDesign
Additionally, since tags are adjusted to 2.0.0
BREAKING CHANGE: The enum `IllustrationMessageSize` is renamed to `IllustrationMessageDesign`.
If you have previously imported the enum:
```js
import IllustrationMessageSize from "@ui5/webcomponents-base/dist/types/IllustrationMessageSize.js";
```
Now import IllustrationMessageDesign instead:
```js
import IllustrationMessageDesign from "@ui5/webcomponents-base/dist/types/IllustrationMessageDesign.js";
```
=> refactor(ui5-illustrated-message): rename IllustrationMessageSize enum

packages/main/test/specs/TableLoading.cy.js
Stabilize `ui5-table` regularly failing test.
Since the focus is inside `ui5-table` it should also match focus assertion. Once the table is focused we need to check if the busy indicator exist and if it exist to check if it is focused.
=> chore: stabilize table's failing test

packages/main/src/ComboBox.ts, packages/main/src/ComboBoxItemGroup.ts, packages/main/src/ComboBoxPopover.hbs, packages/main/src/MultiComboBox.ts, packages/main/src/MultiComboBoxItemGroup.ts, packages/main/src/MultiComboBoxPopover.hbs, packages/main/test/pages/ComboBox.html, packages/main/test/pages/MultiComboBox.html, packages/main/test/specs/MultiComboBox.spec.js, packages/website/docs/_samples/main/ComboBox/Grouping/sample.html, packages/website/docs/_samples/main/MultiComboBox/MultiComboBoxGrouping/sample.html
As the `ui5-multi-combobox` & `ui5-combobox` will use physical items, additional adjustments need to be performed in order to have a smooth and backward compatible transition.
This change renames the `text` property of the `ui5-cb-item-group` & `ui5-mcb-item-group` to `header-text` in consistency to the `ui5-li-group` which the `ComboBoxItemGroup` and `MultiComboBoxItemGroup` will extend once transitioning to physical items in the list.
After the transition from `IComboBoxItem`/`IMultiComboBoxItem` to `ListItemGroup` for the group items code clean up of the non-null assertion operator can be performed as well.
BREAKING CHANGE:  The `ui5-cb-item-group` & `ui5-mcb-item-group` `text` property is renamed to `header-text`.
If you previously used the `text` property:
```html
<ui5-cb-item-group …
```
=> refactor(ui5-combobox, ui5-multi-combobox): prepare for physical list items

packages/main/src/ColorPalette.ts
Issue:
- The `ui5-color-palette` gets re-rendered on each keyboard navigation in the swatches grid.
In the `onAfterRendering` hook there was a logic active only when in `ui5-color-palette-popover`,
which sets the focused element to the first swatch. As a result the keyboard navigation in the grid
was't possible.
=> fix(ui5-color-palette-popover): enable navigation over the swatches

packages/fiori/src/FilterItem.ts, packages/fiori/src/FilterItemOption.ts, packages/fiori/src/ShellBarItem.ts, packages/fiori/src/SortItem.ts, packages/fiori/src/ViewSettingsDialog.ts, packages/main/src/CheckBox.ts, packages/main/src/ColorPaletteItem.ts, packages/main/src/ColorPicker.ts, packages/main/src/ComboBox.ts, packages/main/src/ComboBoxItem.ts, packages/main/src/DateComponentBase.ts, packages/main/src/DateTimePicker.ts, packages/main/src/FileUploader.ts, packages/main/src/Filters.ts, packages/main/src/Input.ts, packages/main/src/Menu.ts, packages/main/src/MenuItem.ts, packages/main/src/MultiInput.ts, packages/main/src/RadioButton.ts, packages/main/src/SuggestionItem.ts, packages/main/src/SuggestionItemCustom.ts, packages/main/src/TimePicker.ts, packages/main/src/Token.ts, packages/main/src/ToolbarButton.ts, packages/main/src/TreeItem.ts, packages/main/src/features/InputSuggestions.ts, packages/main/test/specs/FormSupport.spec.js
With the introduction of property initializers (https://github.com/SAP/ui5-webcomponents/pull/8846) many properties have changed they default values or types but on some places:
- JSDoc wasn't changed
- Properties with declared `declare` keyword were using wrong type
This change fixes most of the things until custom element analyzer plugin is adjusted to generate correct output
=> chore: align property types and default values to framework

packages/main/src/Avatar.ts, packages/main/test/specs/AvatarGroup.spec.js
Ever since the deprecation of the avatar's group `avatarSize` property (https://github.com/SAP/ui5-webcomponents/pull/3229) the `_size` property of the avatar is not used. Since recent changes those underscored properties are showing as the attributes of the component. This causes the avatar size to be displayed incorrectly duo to the default value of the `_size` proeprty. 
The property is removed as is not used anymore.
=> chore(ui5-avatar): remove _size proeprty

packages/base/src/UI5Element.ts, packages/base/src/UI5ElementMetadata.ts
The `cloned` field of `@slot` decorator was introduced to invalidate component slot content was cloned to static area. https://github.com/SAP/ui5-webcomponents/pull/7882
Now, when the Popover API is integrated in all of the components, the field is obsolete.
=> refactor: remove cloned property from slot decorator

packages/main/src/themes/Link.css, packages/main/test/pages/Link.html
Previously when having an exceptionally long `<ui5-link>`, wrapping on multiple lines and with specified `end-icon` property, the icon of it was often displayed far away from the text, due to the `display: inline-flex` CSS property.
With this change the icon is always displayed right after the text of the `<ui5-link>`.
Fixes: #9210
=> fix(ui5-link): remove the space between `end-icon` and text in long links

packages/main/src/themes/CheckBox.css, packages/main/src/themes/base/CheckBox-parameters.css, packages/main/src/themes/base/sizes-parameters.css, packages/main/src/themes/sap_fiori_3/CheckBox-parameters.css, packages/main/src/themes/sap_fiori_3_dark/CheckBox-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/CheckBox-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_hcb/sizes-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/CheckBox-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_hcw/sizes-parameters.css, packages/main/src/themes/sap_horizon/CheckBox-parameters.css, packages/main/src/themes/sap_horizon/sizes-parameters.css, packages/main/src/themes/sap_horizon_dark/CheckBox-parameters.css, packages/main/src/themes/sap_horizon_dark/sizes-parameters.css, packages/main/src/themes/sap_horizon_exp/CheckBox-parameters.css, packages/main/src/themes/sap_horizon_hcb/CheckBox-parameters.css, packages/main/src/themes/sap_horizon_hcb/sizes-parameters.css, packages/main/src/themes/sap_horizon_hcw/CheckBox-parameters.css, packages/main/src/themes/sap_horizon_hcw/sizes-parameters.css
This commit adjusts the focus outline in wrapped mode for the CheckBox component. It address the initial concern that the focus outline was out of place in compact density mode, but also improves the overall focus outline in all density modes.
Themes that were checked:
- sap_horizon
- sap_horizon_dark
- sap_horizon_hcb
- sap_horizon_hcw
- sap_fiori_3
- sap_fiori_3_dark
- sap_fiori_3_hcb
- sap_fiori_3_hcw
Fixes: #9254
=> fix(ui5-checkbox): adjust focus outline in wrapped mode

packages/website/docs/_samples/main/Popover/Placement/sample.html, packages/website/docs/_samples/main/ResponsivePopover/Placement/sample.html
The height of the sample is enlarged in order to avoid scrollbar in the popover shown to bottom of the button.
=> chore(ui5-popover): fix samples

packages/website/src/components/NavbarItems/VersionNavbarItem.js
Update  website version dropdown to match the new setup as we now have one more website deployment in addition
previously
- root -> latest (1.24) 
- nightly - > main branch
now
- root -> latest (2.0.0) 
- v1 -> **long-term maintenance (1.24)**
- nightly - > main branch
=> chore: update website version dropdown

packages/main/src/Table.ts, packages/main/src/TableGrowing.ts, packages/main/src/TableRow.ts, packages/main/src/TableSelection.ts, packages/main/src/TableUtils.ts, packages/main/src/bundle.esm.ts, packages/main/test/pages/Table.html, packages/main/test/pages/TableSelection.html, packages/main/test/specs/TableSelection.spec.js, packages/website/docs/_samples/main/Table/Basic/sample.html, packages/website/docs/_samples/main/Table/Growing/sample.html, packages/website/docs/_samples/main/Table/Interactive/sample.html, packages/website/docs/_samples/main/Table/ScrollToLoad/sample.html, packages/website/docs/_samples/main/Table/Selection/sample.html
Table.ts imported TableSelection.ts, although it is not a base functionality.
Therefore, the selection has been removed as import and the code has been refactored to accomodate for that.
Additionaly, key is a reserved keyword in React, which is why the row key has been renamed to row-id.
=> chore(ui5-table): remove selection import & rename key

packages/main/src/MultiComboBox.ts, packages/main/src/MultiComboBoxPopover.hbs, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): remove the cloning of the value state message

docs/2-advanced/09-accessibility.md
The Accessibility documentation is being updated with changes introduced by PR #9333 
* `accessibilityAttributes` property introduced in `ui5-menu-item` component
Related to: #9333
=> docs(ui5-menu-item): update 09-accessibility.md

packages/main/src/DateRangePicker.ts, packages/main/src/FileUploader.ts, packages/main/src/Tokenizer.ts, packages/main/src/TreeItemBase.ts, packages/tools/lib/cem/custom-elements-manifest.config.mjs
Add alert when custom element generator can't determinate the type of the property. Also align some property default value tags with they initializer value.
=> chore: add alert for missing type in cem generation

packages/main/src/themes/sap_horizon/Table-parameters.css, packages/main/src/themes/sap_horizon/TableColumn-parameters.css, packages/main/src/themes/sap_horizon/parameters-bundle.css, packages/main/src/themes/sap_horizon_dark/Table-parameters.css, packages/main/src/themes/sap_horizon_dark/TableColumn-parameters.css, packages/main/src/themes/sap_horizon_dark/parameters-bundle.css, packages/main/src/themes/sap_horizon_dark_exp/Table-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/TableColumn-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/parameters-bundle.css, packages/main/src/themes/sap_horizon_exp/Table-parameters.css, packages/main/src/themes/sap_horizon_exp/TableColumn-parameters.css, packages/main/src/themes/sap_horizon_exp/parameters-bundle.css, packages/main/src/themes/sap_horizon_hcb/Table-parameters.css, packages/main/src/themes/sap_horizon_hcb_exp/Table-parameters.css, packages/main/src/themes/sap_horizon_hcw/Table-parameters.css, packages/main/src/themes/sap_horizon_hcw_exp/Table-parameters.css
"72-SemiboldDuplex", "72-SemiboldDuplexfull" fonts look broken in Safari browser when its font weight is set to bold.
With this the specification of `ui5-table-column` was updated and now, the column's font weight should be set to normal. With this PR the styles are align to the specification.
Fixes: #9046
=> fix(ui5-table): correct font weight

packages/main/src/Table.ts
If the `ui5-table` is made with `mode=Growing`, and then the mode is changed to `None` and back to `Growing`, the `load-more` event is not fired anymore. This is because the observed element by IntersectionObserver is not in the DOM anymore because it is conditionally rendered. To fix this, we reset the `tableEndObserved` flag when the mode changes, so the observed element is set again correctly when the DOM is ready.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8052
=> fix(ui5-table): correct load-more event on mode change

packages/compat/src/Table.hbs
Table row added for loading more functionality was read out by the screen readers. With this PR, the row is excluded from the accessibility tree.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9243
=> fix(ui5-table): correct announced row count

packages/base/src/asset-registries/LocaleData.ts
Recently we have updated the openui5/core dependency to 1.120.17, so updating the cdn url to be aligned
=> chore: update cldr cdn

packages/main/src/MultiComboBox.ts, packages/main/src/MultiComboBoxPopover.hbs, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): collapse tokenizer on n-more popover focusout

packages/main/src/TabInOverflow.hbs, packages/main/test/specs/TabContainer.spec.js
Selected sub item was read as “not selected” by screen readers.
=> fix(ui5-tabcontainer): fix selected sub items screen readers announcement

packages/main/src/Dialog.ts, packages/main/src/Popup.hbs, packages/main/src/Popup.ts
Reported from the exploratory testing.
In Chrome and Edge there is still issue, if "header" slot is used, because of https://issues.chromium.org/issues/41420461
=> fix(ui5-dialog): fix draggable dialog header focusing with mouse

packages/main/src/Toolbar.ts, packages/main/test/pages/Toolbar.html, packages/main/test/specs/Toolbar.spec.js
Prevent child controls of the ui5-toolbar`s events from bubbling.
Fixes: #9444
=> fix(ui5-toolbar): prevent child events bubble

packages/main/src/ListItemBase.hbs, packages/main/src/Option.hbs, packages/main/src/OptionCustom.hbs, packages/main/test/specs/Select.cy.js
As a side effect of https://github.com/SAP/ui5-webcomponents/pull/9015, an issue was introduced, making the tooltip property of the Option unused. This change allows customization of the attributes of the ListItemBase tempalte which the Option and OptionCustom classes implement to forward the tooltip property to the title attribute of the list item.
=> fix(ui5-option): correct tooltip property forwarding

packages/main/src/Select.ts
When closing the select's popover with 'ESC' key without previously navigating through items, the 'ui5-live-change' is wrongly fired. This issue is now fixed.
=> fix(ui5-select): prevent unnecessary live-change event

packages/main/src/Select.ts, packages/main/test/specs/Select.spec.js
Fixed a problem where if the select dropdown is closed and we are on the last item, when we press arrow down, a change event is unnecessarily fired without any change actually happening.
=> fix(ui5-select): prevent unnecessary change event

packages/main/src/Calendar.hbs, packages/main/src/Calendar.ts, packages/main/src/DayPicker.hbs, packages/main/src/DayPicker.ts, packages/main/src/MonthPicker.hbs, packages/main/src/MonthPicker.ts, packages/main/src/YearPicker.hbs, packages/main/src/YearPicker.ts, packages/main/src/themes/DayPicker.css, packages/main/test/pages/Calendar.html
Adding new CSS shadow parts to enable overstyling of cells in the Calendar component.
- `day-cell` - Used to style the day cells.
- `day-cell-selected` - Used to style the day cells when selected.
- `day-cell-selected-between` - Used to style the day cells in between of selected dates in range.
- `month-cell` - Used to style the month cells.
- `month-cell-selected`- Used to style the month cells when selected.
- `year-cell` - Used to style the year cells.
- `year-cell-selected` - Used to style the year cells when selected.
Example how to use it if you want to style the calendars selected date:
```CSS
[ui5-calendar]::part(day-cell day-cell-selected) {
background-color: rgb(241, 175, 53);
color: white;
border: 1px solid slateblue;
font-weight: bold;
}
```
fixes: …
=> feat(ui5-calendar): allow overstyling

packages/main/src/ComboBox.ts, packages/main/src/ComboBoxPopover.hbs, packages/main/src/Input.ts, packages/main/src/InputPopover.hbs, packages/main/src/MultiComboBox.ts, packages/main/src/MultiComboBoxPopover.hbs, packages/main/src/i18n/messagebundle.properties
When a header, nor a label is provided to an element with role dialog JAWS reads out the `<title>` element of the html document as a dialog header, once a dialog is opened/focused. In order to overcome this side effect and future announcemnt deviations the suggestion popover elements are now labelled following the existing pattern from UI5.
Related to: #9116
=> fix(ui5-multi-combobox, ui5-combobox, ui5-input): improve popup announcement

packages/main/src/themes/BusyIndicator.css, packages/main/src/themes/base/BusyIndicator-parameters.css, packages/main/src/themes/sap_horizon/BusyIndicator-parameters.css, packages/main/src/themes/sap_horizon_dark/BusyIndicator-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/BusyIndicator-parameters.css, packages/main/src/themes/sap_horizon_dark_exp/parameters-bundle.css, packages/main/src/themes/sap_horizon_exp/BusyIndicator-parameters.css, packages/main/src/themes/sap_horizon_exp/parameters-bundle.css, packages/main/test/pages/BusyIndicator.html, packages/main/test/pages/styles/BusyIndicator.css
By default, busy indicator should have rectangular focus border. If rounded one is needed, now it can be set using border-radius, like:
```html
<ui5-busy-indicator style="border-radius: 8px;">...</ui5-busy-indicator>
```
Automatic rounding will be evaluated further.
Related to https://github.com/SAP/ui5-webcomponents/issues/9465
=> fix(ui5-busy-indicator): let focus border radius be set from the host element

packages/tools/components-package/nps.js
Ignore the "src/generated" folder, in order to avoid issue on Windows, where this `chokidar` process's memory consumption  grows drastically.
Related to https://github.com/SAP/ui5-webcomponents/issues/8824
=> chore(watch.templates): ignore src/generated

packages/tools/components-package/nps.js
Ignore the "src/generated" folder, in order to avoid issue on Windows, where this chokidar process's memory consumption grows drastically.
Related to https://github.com/SAP/ui5-webcomponents/issues/8824
=> chore(copy.props): ensure src/generated folder is not processed

packages/website/build-scripts/api-reference-generation/component-file.mjs, packages/website/src/css/custom.css
Display component tag name and since information in playgorund.
=> chore: display tag / since information in playground

packages/main/src/Table.ts, packages/main/src/TableRow.hbs, packages/main/src/themes/Table.css, packages/main/src/themes/TableHeaderRow.css, packages/main/src/themes/TableRow.css, packages/main/src/themes/base/Table-parameters.css, packages/main/test/specs/Table.spec.js, packages/website/docs/_samples/main/Table/Selection/main.js, packages/website/docs/_samples/main/Table/Selection/sample.html
- The missing TableHeaderRow dependency is added
- Busy indicator dim background is added
- Explicit header row height is removed
- Multiple selection mode sample is fixed
- Navigated outline is aligned with spec
=> fix(ui5-table): adds the missing TableHeaderRow dependency

packages/fiori/src/themes/ShellBar.css
On 200% or more browser zoom, sometimes the primary title gets truncated, even if there is visibly enough space to be rendered.
This fix mitigates the issue.
Fixes: #9296
=> fix(ui5-shellbar): improved readability

packages/base/src/FeaturesRegistry.ts, packages/base/src/UI5Element.ts, packages/base/src/UI5ElementMetadata.ts, packages/base/src/decorators/customElement.ts, packages/main/src/ColorPalette.ts, packages/main/src/ColorPaletteDialog.hbs, packages/main/src/Input.hbs, packages/main/src/Input.ts, packages/main/src/InputPopover.hbs, packages/main/src/features/ColorPaletteMoreColors.ts, packages/main/src/features/InputSuggestions.ts
Previously, feature loading depended on the import order, requiring features to be imported before the component definition. This caused issues in some situations, especially when creating chunks because the imports can be reordered by the build tools.
With this change, we have split the features into two types: library-specific and component-specific. Library-specific features need to be imported before the boot process, otherwise, it can cause serious issues, because the need to re-render all components and manipulate the DOM (including scripts, styles, and meta tags). Component-specific features can now be imported without a specific order, and components that depend on these features will automatically update, enabling the feature on the next rendering of the component.
Fixes: #8175
=> feat: enhance feature initialization

packages/website/docs/_samples/base/UI5Element/Basic/main.ts, packages/website/src/components/Editor/examples/counter/main.js, packages/website/src/css/custom.css
Before
After
Fixes: https://github.com/SAP/ui5-webcomponents/issues/8777
=> docs: fix code completion color on dark

packages/main/src/List.hbs, packages/main/src/List.ts, packages/main/src/themes/List.css, packages/main/test/pages/List.html
Loading state wasn't displayed properly.
This change adapts the list to the busy indicator and fixes the issue.
Fixes: #9476
=> fix(ui5-list): improved loading state

packages/main/src/Menu.hbs, packages/main/src/Menu.ts
=> fix(ui5-menu): adjust loading sub-menu

packages/main/src/TimePickerClock.ts
Previously when selecting a time from the clock there was an error being thrown due to a check in the `TimePickerClock` class.
The reason an error was thrown was due to a check if a `radius` property was absent from an internal object, which in some cases was yet `undefined`, therefore trying to access that property resulted in an error.
Fixes: #9531 
Fixes: #9579
=> fix(ui5-timepicker): fix error thrown upon selection from the clock

packages/main/src/DatePicker.ts, packages/main/src/DatePickerPopover.hbs, packages/main/src/DateRangePicker.hbs, packages/main/src/DateTimePickerPopover.hbs, packages/main/test/specs/DatePicker.spec.js
Fixes: [9217](https://github.com/SAP/ui5-webcomponents/issues/9217)
=> fix(ui5-date-picker): adjust timestamp

packages/fiori/src/themes/DynamicPage.css
There was a problem where the handle of the Slider components was overlapping over the Dynamic Page header area. This was due to equal z-index of both the handle and the Dynamic Page header wrapper.
This change increases the z-index of the header wrapper making sure that the handle of the slider is always rendered under it and not overlapping.
Fixes: #9560
=> fix(ui5-dynamic-page): fixed wrong overlapping in header area

packages/main/src/AvatarGroup.ts
Added a null-check in the `firstAvatarSize` getter to prevent a TypeError when the component is initialized without items. This ensures that the component behaves correctly and does not throw errors in the console when it is first loaded or when no items are present.
Fixes #9581
=> fix(ui5-avatar-group): prevent console error when no items are present

packages/main/src/Toolbar.ts, packages/main/src/ToolbarRegistry.ts
This change updates the registration mechanism for toolbar items to use a metadata tag instead of the class name. 
- In `Toolbar.ts`, updated the `getItemsInfo` method to retrieve the registered toolbar item using `ctor.getMetadata().getPureTag()` instead of `item.constructor.name`.
- In `ToolbarRegistry.ts`, modified the `registerToolbarItem` function to register items with `ElementClass.getMetadata().getPureTag()` instead of `ElementClass.name`.
In production builds, webpack minifies class names which resulted in all toolbar buttons being registered under the same name ("i"). This caused all toolbar items to be registered as the last one registered due to name conflicts. By switching to a more stable identifier from the class metadata, we prevent such issues.
=> fix(ui5-toolbar): update ToolbarRegistry to use metadata tag instead of class name

packages/tools/components-package/nps.js
`copy.src` with `--watch` flag spawns `chokidar` process, that consumes a lot of memory on Windows machines in some cases. Since `js` and `json` files no longer need to be copied, these commands can be removed.
Related to https://github.com/SAP/ui5-webcomponents/issues/8824
=> chore(copy.src, watc.src): remove completely

packages/fiori/src/ShellBar.ts, packages/website/docs/_samples/fiori/FlexibleColumnLayout/Basic/main.js
An icon used by the shellbar template was not imported as dependecy. 
Additionally the FCL's sample was also using some icons that were not imported in the JS file.
Closes: https://github.com/SAP/ui5-webcomponents/issues/9580, https://github.com/SAP/ui5-webcomponents/issues/9534
=> fix(ui5-shellbar): add missing icon dependency

packages/main/src/themes/TimePicker.css, packages/main/test/pages/TimePicker.html
the ui5-input wasn't correctly inheriting the height from ui5-timepicker host.
Before:
After:
fixes: https://github.com/SAP/ui5-webcomponents/issues/9366
=> fix(ui5-timepicker): align input with timepicker styles

packages/main/src/themes/StepInput.css
the input control wasn't correctly inheriting the styles from step input overstyling.
Before:
After:
fixes: https://github.com/SAP/ui5-webcomponents/issues/9365
=> fix(ui5-step-input): apply overstyling correctly

packages/fiori/src/ShellBar.ts
The aria-expanded attribute on the search button inside the ui5-shellbar component causes an unnecessary announcement.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7123
=> fix(ui5-shellbar): remove aria attribute from search button

packages/fiori/src/Timeline.ts
Issue: On init of item navigation, the shadowdom of the timeline group item was not filled, and when searching for toggle button inside, it wasn't available, so we pushed null into the array and the item navigation was failing to set the `forcedIndex` property of `null`.
Solution: We've added check to verify that the `navigatableItems` array is filled only with valid items.
Addition: A global solution can be researched, that handles such cases. Searching for elements in `ShadowDom` in the callback function that we pass to ItemNavigation on init trough `getItemsCallback`(When we have invalid items in `ItemNavigation`).
Should the init function wait for the shadow dom of the children to be rendered?
fixes: https://github.com/SAP/ui5-webcomponents/issues/9633
=> fix(ui5-timeline): fix javascript error

packages/main/src/Menu.hbs, packages/main/src/Menu.ts, packages/main/src/MenuItem.hbs, packages/main/src/MenuItem.ts, packages/main/src/i18n/messagebundle.properties, packages/main/test/specs/Menu.cy.js
Issue:
- Every popover should have an accessible name
according to the accessibility standard.
Fixes: #9313
=> fix(ui5-menu): provide accessible name to the popover

packages/base/src/UI5Element.ts
When a component throws an error in its `onBeforeRendering` hook, `_suppressInvalidation` is not reset to false and no further property/slot changes trigger an invalidation, thus leaving the component fully broken even when correct data is passed to it in further steps.
As a general rule components should have checks and not throw errors, but this check at least guards from the framework side so the component is not left in a broken state forever.
Real issue came up when storybook for angular renders a table in two steps and the intermediate step throws an exception like described in this issue: #9636
=> fix(core): invalidation no longer leaves component broken after error in onBeforeRendering

packages/main/src/MultiComboBox.ts, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-comboBox): delete token from mcb with grouping

packages/main/src/Select.ts, packages/main/src/SelectPopover.hbs
=> fix(ui5-select): remove the cloning of the value state message

packages/main/src/Breadcrumbs.hbs, packages/main/src/Breadcrumbs.ts, packages/main/src/BreadcrumbsItem.ts, packages/main/src/themes/Breadcrumbs.css, packages/main/test/pages/Breadcrumbs.html
Regarding to recent feedback we move back the variant with breadcrumbs current item implemented as a text and kept the functionality to visualise it as a link if a href is passed to the last breadcrumbs item.
=> chore(ui5-breadcrumbs): current location hybrid

packages/main/src/Calendar.ts, packages/main/src/DayPicker.ts, packages/main/src/themes/DayPicker.css, packages/main/test/pages/CalendarLegend.html, packages/main/test/specs/CalendarLegend.spec.js, packages/website/docs/_samples/main/Calendar/CalendarWithLegend/main.js, packages/website/docs/_samples/main/Calendar/CalendarWithLegend/sample.html, packages/website/docs/_samples/main/CalendarLegend/Basic/main.js, packages/website/docs/_samples/main/CalendarLegend/Basic/sample.html
Previously, when adding a `SpecialCalendarDate` to the `Calendar` component and specifying the public types `Working` and `NonWorking`, these settings were not properly applied.
For example, setting a `Working` type to a weekend day did not visually reflect that the day was designated as a working day and vice versa for `NonWorking` type.
With this change we resolve that issue, ensuring that the specified types (`Working` and `NonWorking`) now take effect as intended.
Fixes: #9216
=> fix(ui5-special-date): add visual representation for Working/NonWorking types

packages/main/src/Table.ts, packages/main/test/pages/TableEmpty.html, packages/main/test/specs/Table.spec.js
When rendering an empty table (no header row, rows), there should be no exception thrown during initialisation of the table.
Therefore, added checks to see whether headerRow actually exists before accessing it.
Fixes: #9636
=> fix(ui5-table): rendering empty table leads to no exception

packages/website/build-scripts/icons-generation/index.mjs, packages/website/docusaurus.config.ts, packages/website/package.json, packages/website/src/components/Editor/index.js, packages/website/src/theme/DocSidebar/Input/index.js
github pages shows "rate limit exceeded" too often, partly because the samples use the modules that are also deployed on github pages.
with this change, the released versions (V1 and V2) are served from jsdeliver, local-cdn remains only for the nightly build.
=> docs: serve samples for released version from jsdelivr

packages/main/src/TableHeaderRow.ts, packages/website/docs/_samples/main/Table/StickyHeaderContainer/StickyHeaderContainer.md, packages/website/docs/_samples/main/Table/StickyHeaderContainer/sample.html
Due to a previous change with horizontal scrolling, the example with sticky headers broke. Added a fixed height to the table and adjusted end tags of ui5-table-row.
=> docs(ui5-table): fix sticky header example

packages/fiori/src/themes/FlexibleColumnLayout.css
Fixes flickering in the following scenario:
1. Open https://sap.github.io/ui5-webcomponents/components/fiori/FlexibleColumnLayout/
2. Navigate to the "Basic sample"
3. Select a list-item to open the second column
4. Hover the mouse cursor around the columns separator
Expected: Nothing is changed until we click
Actual: A slight one-time flickering
The issue is due to incorrect height of the separator contents during hover. Fixed the height calculation by provisioning space for the grip icon
=> fix(ui5-flexible-column-layout): correct separator height

packages/fiori/src/FlexibleColumnLayout.ts, packages/fiori/src/themes/FlexibleColumnLayout.css, packages/fiori/test/specs/FCL.spec.js
Fixes: #9682
Root cause: 
The smaller column was initially rendered with with smaller than the minimal allowed width.
This happens on smaller screens, as the current value of the column-min-width constraint (of 312px) is not properly aligned with the breakpoints of the FCL sizes. In particular, the current value (of 312px) is too large for the smallest tablet/desktop size (of 600px for tablet and 1024px for desktop) and cannot be attained when the maximum number of columns are shown.
Solution: 
1) Update the value of column-min-width to 25% of the available space of the smallest desktop width (of 1024px) when 3 columns are shown. So:
column-min-width  = 25% of  ( 1024 - 2*16 )
- where 25% is the space reserved for the narrowest column in ThreeColumnMidExpanded (defaults to [25%, 50%, 25%] …
=> fix(ui5-flexible-column-layout): correct min-width constraint

packages/main/src/TableSelection.ts
Instead of using isShift(), use event.shiftKey instead, as isShift just checks the released key.
=> fix(ui5-table): range selection should stop when releasing shift

packages/base/src/UI5Element.ts, packages/base/src/features/InputElementsFormSupport.ts, packages/main/src/Button.ts, packages/main/src/ComboBox.ts, packages/main/src/DatePicker.ts, packages/main/src/Input.ts, packages/main/src/MultiComboBox.ts, packages/main/src/TimePicker.ts, packages/main/test/pages/Input.html
Update the constructor of each UI5Element to use attachInternals directly. This ensures that the ElementInternals are attached only once per component.
Also, this change helps prepare for future improvements to component CustomState.
Fixes: #9713
=> fix(framework): attach element internals only once

packages/base/src/types.ts, packages/main/src/Breadcrumbs.hbs, packages/main/src/BreadcrumbsItem.ts, packages/main/src/Link.hbs, packages/main/src/Link.ts
=> fix(ui5-breadcrumbs): current link aria-current

packages/main/src/ColorPalettePopover.hbs
Issue:
- Based on the template the `open` is set before the `opener` attribute
resulting into a console warning.
Fixes: #9708
=> fix(ui5-color-palette-popover): set opener attribute

packages/ai/package.json, packages/base/package.json, packages/compat/package.json, packages/fiori/package.json, packages/fiori/test/specs/Page.spec.js, packages/fiori/test/specs/UploadCollection.spec.js, packages/localization/package.json, packages/main/package.json, packages/main/test/specs/MultiComboBox.spec.js, packages/main/test/specs/Panel.spec.js, packages/main/test/specs/Popover.spec.js, packages/tools/components-package/wdio.js, yarn.lock
In chrome 128 new headless mode described in https://developer.chrome.com/docs/chromium/new-headless is set to be used by default. This made tests unstable. To make tests stable again we have to pass `old` as value to the `headless` parameter in Chrome configuration options.
=> chore: bump chromedrier

packages/main/src/TextArea.ts
Custom scrollbar class should be added if custom scrollbars should be applied to the page. This was changed in #9751 and it is meant to be used with `!!` instead of `!`
=> chore: textarea scrollbar

packages/compat/test/specs/TableGrouping.spec.js, packages/fiori/test/specs/NotificationList.spec.js, packages/main/test/specs/Text.spec.js, packages/tools/lib/i18n/defaults.js
There are three files for english currently:
`messagebundle.properties` - written by developers and used as source format
`messagebundle_en.properties` - coming from translation system, used as fallback for en_US
`messagebundle_en_GB.properties` - coming from translation system
The default text `en` is inlined in the bundle and is not fetched from the network, unless the `fetchDefaultLanguage` configuration property is set.
The problem is when a browser with `en_US` is used, the locale is resolved to `en` and the inlined texts are used, but they are generated from `messagebundle.properties` instead of `messagebundle_en.properties`.
This change is using the translated file `messagebundle_en.properties` for generating the inlined texts. There is a timeframe when a text is only available in …
=> chore: default texts are populated from translations

packages/main/src/themes/sap_fiori_3/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css, packages/main/src/themes/sap_horizon_dark/parameters-bundle.css, packages/main/src/themes/sap_horizon_hcb/parameters-bundle.css, packages/main/src/themes/sap_horizon_hcw/parameters-bundle.css
The base params used to be included only in the default theme (sap_horizon) and not included in the rest. By adding  the params everything looks same in all themes.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9788
=> fix(ui5-form): fix layout issues by importing base params in all themes

packages/main/src/themes/sap_horizon/TextArea-parameters.css, packages/main/src/themes/sap_horizon_dark/TextArea-parameters.css
Related to Issue #9741 (issue 2)
Hello @nnaydenow,
You had already reviewed this PR request, and I opened a new PR for a cleaner version. I made the changes you requested. Thank you.
Best regards,
tw4
=> fix(ui5-textarea): focus outline and border overlapping in readonly textarea

packages/main/src/themes/GrowingButton.css
ui5-list: Corrected "More" Button Text Positioning
Issue: The "More" button text within the ui5-list component was not correctly aligned due to improper padding settings.
Solution: The padding for the growing-button-text class was adjusted in the CSS to ensure proper alignment of the text.
Fixes: [#9725](https://github.com/SAP/ui5-webcomponents/issues/9725)
=> fix(ui5-list): adjust growing button padding

packages/website/src/components/Editor/index.js
When typing `/`, the `@docsearch/react` package checks if the key is coming from an input/textarea and additionally from a `contenteditable` element. The editor however is inside the shadowroot of a custom element, so the event target is the custom element, not the actual contenteditable element.
This change adds a `isContentEditable` getter to the editor custom element, so typing `/` in the playground editor no longer opens the search box.
=> docs: fix shortcut opens search while typing in playground editor

packages/main/src/MultiComboBox.ts, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): restore focus to input after value state header is removed

packages/compat/src/Table.ts
The `moreDataText` has never been assigned, probably a degradation in the past after `growingButtonSubText` was introduced. Due to this even if `growingButtonSubText` is set, the span ({this._id}-growingButton-subtext) that is internally created for a11y reasons has never been referenced and read out by screen readers.
Related to: https://github.com/SAP/ui5-webcomponents/issues/9807
=> fix(ui5-table): add aria reference to growing btn sub text

packages/base/src/Runtimes.ts, packages/base/src/features/F6Navigation.ts
F6 navigation adds `keydown` handler to the body element that will move the focus to the previous / next group that has focusable element. If F6 navigation feature is enabled in multiple runtimes this handler will be attach multiple times.
With current change, we ensure that only one callback will be executed to move the focus to the correct element. This callback is coming from the latest registered runtime (newest version).
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9795
=> fix(f6 navigation): work properly when multiple runtimes

packages/main/src/Link.hbs, packages/main/src/themes/Breadcrumbs.css
Top and bottom touch area spacings are aded because of non-intersecting target area requirement.
The positioning of the drop-down popover also is changed accordingly.
Internal reference: BGSOFUIPIRIN-6642
=> refactor(ui5-breadcrumbs): increase links touch area

packages/fiori/src/DynamicSideContent.ts
Previously, when content was added to the `ui5-dynamic-side-content` component, a scrollbar would appear using the default browser scrollbar styles and sizes. 
Now, custom scrollbar styles have been added, which adapt to the current theme.
=> fix(ui5-dynamic-side-content): fix scrollbar styling

packages/main/src/themes/Dialog.css, packages/main/src/themes/Popover.css, packages/main/src/themes/base/Dialog-parameters.css, packages/main/src/themes/base/PopupBlockLayer-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/Dialog-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/PopupBlockLayer-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css, packages/main/src/themes/sap_fiori_3_hcw/Dialog-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/PopupBlockLayer-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css, packages/main/src/themes/sap_horizon_hcb/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcb/PopupBlockLayer-parameters.css, packages/main/src/themes/sap_horizon_hcb/parameters-bundle.css, packages/main/src/themes/sap_horizon_hcw/Dialog-parameters.css, packages/main/src/themes/sap_horizon_hcw/PopupBlockLayer-parameters.css, packages/main/src/themes/sap_horizon_hcw/parameters-bundle.css
The background of the modal popover backdrop was black which made the context page not visible
so opacity was added to grey out the background
Fixes: #9823
=> fix(ui5-popover): correct opacity

packages/base/src/Boot.ts, packages/base/src/UI5Element.ts, packages/compat/src/TableGroupRow.ts, packages/main/src/Calendar.ts
Before this change, importing a component module calls the `UI5Element.define()` base class method, which triggers some async work before calling `customElements.define()`
This causes frameworks like vuejs and react that check for property existence via `prop in el` to run before the element is defined, this check returns false and such frameworks set attributes (most notably boolean) as string resulting in `checked="false"` being treated as `true` by the components
With this change, the async work is triggered in the beginning of the `define()` call, but not awaited and `customElements.define()` runs as soon as the component is imported. The async work (waiting for the theme and i18n assets to be fetched) is now awaited in the `connectedCallback` so that the component is rendered once …
=> chore: call customElements.define synchronously

packages/base/src/util/ColorConversion.ts
There was a HEX value missing in the `RGBtoHEX()` method in the ColorConversion util.
With this change we added it.
```html
<div id="text"></div>
<script>
document.getElementById("text").innerHTML = RGBtoHEX({
r: 207,
b: 223,
g: 255
});  // results in #CundefinedundefinedundefinedDundefined
</script>
```
```html
<div id="text"></div>
<script>
document.getElementById("text").innerHTML = RGBtoHEX({
r: 207,
b: 223,
g: 255
});  // results in #CFFFDF
</script>
```
Fixes: #9895
=> fix(ui5-color-picker): add missing hex value to RGBtoHEX method

packages/main/src/MultiComboBox.ts, packages/main/test/specs/MultiComboBox.spec.js
=> fix(ui5-multi-combobox): fix aria-describedby token count

packages/base/src/features/patchPopup.ts
The OpenUI5 `Popup`'s `getContent` method may return a pure HTML Element, in addition to `sap.ui.core.Control`: https://sapui5.hana.ondemand.com/#/api/sap.ui.core.Popup%23methods/getContent
=> fix: patchPopup now correctly handles getContent

packages/main/src/MultiInput.ts, packages/main/test/specs/MultiInput.spec.js
=> fix(ui5-multi-input): tokens are not deletable when multi-input is readonly

packages/main/src/FileUploader.ts, packages/main/src/FileUploaderPopover.hbs, packages/main/test/pages/FileUploader.html, packages/main/test/specs/FileUploader.spec.js
The `valueStateMessage` slot content no longer needs to be cloned, as the `ui5-popover` is now integrated into the component’s shadow root through the new Popover API.
Related to: #9347
=> fix(ui5-file-uploader): remove the cloning of the value state message

packages/main/src/Select.ts, packages/main/test/pages/Toolbar.html, packages/main/test/specs/Select.spec.js
Issue: When changing the selection in the ui5-select, previously typed characters were cleared after a 1-second delay, which caused problems with quick successive selections.
Solution: Modified the selection change logic to clear typed characters immediately whenever the selection is updated, removing the 1-second delay and allowing users to change options quickly without interference from previous input.
Fixes: [#9757](https://github.com/SAP/ui5-webcomponents/issues/9757)
=> fix(ui5-select): improve selection change handling

packages/website/docs/_samples/patterns/AIGuidedPrompt/Dialog/main.js
This simplifies the sample for guided prompt in dialog, to avoid issue https://github.com/SAP/ui5-webcomponents/issues/9902 untill the issue is fixed.
Steps to reproduce the issue in the sample for AI GuidedPrompt with dialog:
1. Click the "Generate" ai-button to open a dialog
2. In the dialog, click "Apply" and wait [few seconds] until the generation ends and the ai-button text becomes "Revise"
3. Click the "Close" button to close the dialog
4. Click the "Send" button at the footer => the user is notified that the message is sent and the form is cleared
5. Repeat step 2 to re-open the dialog to compose new text
**Expected**: In the dialog, the text of the ai-button is "Apply"
**Actual**: the text of the ai-button is not entirely visible
With this change, clicking the footer "Send" button …
=> chore: simplify guided prompt sample for dialog

packages/main/src/Table.ts
Explain that the `compat/Table` and  the `main/Table` can't be used in parallel
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9920
=> docs: enhance Table docs

packages/fiori/src/Page.ts, packages/fiori/src/themes/Page.css, packages/fiori/test/specs/Page.spec.js, packages/main/src/themes/Bar.css
=> fix(ui5-page): fix double footer and adjust animation timing

packages/fiori/src/Wizard.hbs, packages/fiori/src/Wizard.ts, packages/fiori/src/WizardTab.hbs, packages/fiori/src/WizardTab.ts, packages/fiori/test/specs/Wizard.spec.js
=> fix(ui5-wizard): disabled steps are no longer clickable

packages/tools/components-package/nps.js
With the TS flow typescript copies files from `src/` to `dist/` but in order to support the old JS flow we need to restore the copy functionality.
=> fix: nps.js works with the JS flow

packages/fiori/src/DynamicPage.hbs, packages/fiori/src/DynamicPage.ts, packages/fiori/src/DynamicPageTitle.hbs, packages/fiori/src/DynamicPageTitle.ts, packages/fiori/src/themes/DynamicPage.css, packages/fiori/src/themes/DynamicPageTitle.css, packages/fiori/src/themes/base/DynamicPageTitle-parameters.css, packages/fiori/test/pages/DynamicPageWithSnappedTitleOnMobile.html, packages/fiori/test/specs/DynamicPage.mobile.spec.js, packages/fiori/test/specs/DynamicPage.spec.js
**Overview**
We have enhanced the `ui5-dynamic-page-title` component to improve the user experience on mobile devices when the `DynamicPageTitle` is in its collapsed (snapped) state. You can now display a simplified, single-line title specifically designed for mobile screens. This feature optimizes the use of limited screen space on mobile devices by showing a concise title that remains always visible.
**New Slot**
- `snappedTitleOnMobile`
- This slot allows you to provide custom content (typically a `ui5-title` component) that will be displayed as the title on mobile devices when the header is in its snapped state. The content set in this slot **overrides** other title content during the snapped state on mobile devices.
**Usage**
To utilize this feature, place a `ui5-title` into the …
=> feat(ui5-dynamic-page-title): implement snapped title on mobile

packages/fiori/src/DynamicPageHeaderActions.hbs, packages/fiori/test/specs/DynamicPage.spec.js
In regard to https://sap.github.io/ui5-webcomponents/docs/advanced/accessibility/#accessibility-apis , removing obsolete title property.
Fixes: [#9819](https://github.com/SAP/ui5-webcomponents/issues/9819)
=> fix(ui5-dynamic-page): action buttons reading fix

packages/website/docs/_samples/main/Form/LabelSpan/main.css, packages/website/docs/_samples/main/Form/Layout/main.css
Few samples did not look well in dark themes due to hard-coded backgrounds
=> docs: make Form samples theme-friendly

packages/main/src/Carousel.ts, packages/main/src/themes/Carousel.css, packages/main/test/pages/Carousel.html, packages/main/test/specs/Carousel.mobile.spec.js
- The  main difference with desktop is that when the arrows are in the content (middle)
they are not shown only on hover of the carousel, but always.
This relates to WCAG 2.2 - ACC-270.19 Alternative for Dragging
- The property "hideNavigationArrows" doesn't work on touch devices
- There is one exception - when there is only one page in the carousel no arrows are needed
- In addition the new design for hidden page indicator is implemented
(the arrows are near and no place for the page indicator is kept)
JIRA: BGSOFUIRODOPI-3314
=> feat(ui5-carousel): on touch devices navigation arrows are always visible

packages/fiori/src/FlexibleColumnLayout.ts
Issue: In Firefox and Safari, the separator in the Flexible Column Layout is not moving as expected.
Solution: Improved the handling of touch events to ensure proper functionality across all browsers during separator movement.
Fixes: [#9932](https://github.com/SAP/ui5-webcomponents/issues/9932)
=> fix(ui5-flexible-column-layout): handle separator movement

packages/main/src/List.hbs, packages/main/src/List.ts, packages/main/src/themes/GrowingButton.css
The new visual spec mandates that when we have growing with button there shouldn't be busy indicator overlay on top of the whole list but a small one next to "More" text without blocking the rest of the list.
=> fix(ui5-list): growing button loading aligned with visual spec

packages/main/src/themes/ListItemBase.css, packages/main/src/themes/ListItemGroupHeader.css
Removed redundant hover background and cursor: pointer from the group header. The changes ensure that only actionable items receive these effects, improving clarity and consistency in styling.
=> refactor(ui5-list-group-header):exclude group header from pointer and hover effects

packages/website/docs/_components_pages/main/Table/TableCell.mdx, packages/website/docs/_components_pages/main/Table/TableHeaderCell.mdx
The titles of the example sections of the horizontalAlign property had the wrong indentation.
=> fix(ui5-table): Wrong indentation of  horizontalAlign example sections

packages/tools/lib/hbs2ui5/index.js
=> fix: require handlebar file names processed by hbs2ui5 tool to end with the '.hbs' extension

packages/main/src/themes/Input.css, packages/main/src/themes/base/Input-parameters.css, packages/main/test/pages/styles/MultiInput.css
There is no such visual requirement in the Fiori specifications for the` ui5-input` to have a min-width.
Moreover, it breaks components that use `ui5-input` as part of them, like `ui5-slider` and `ui5-range-slider`.
=> fix(ui5-input): remove the width from the inner input

packages/fiori/src/themes/UploadCollection.css, packages/fiori/test/pages/UploadCollection.html
According to the design:
The icon should be displayed only when the height of the Drag enabled container is more than 10rem.
fixes: #9975
=> fix(ui5-upload-collеction): hide the upload icon when the height is too small

packages/fiori/src/Page.ts, packages/fiori/test/specs/Page.spec.js
Custom element must not gain any attributes or children in the constructor, as this violates the expectations of consumers who use the createElement or createElementNS methods.
Fixes #9981
=> fix(ui5-page): fix createElement error caused by adding new style property in the constructor

packages/ai/tsconfig.json, packages/base/tsconfig.json, packages/compat/tsconfig.json, packages/fiori/tsconfig.json, packages/icons-business-suite/tsconfig.json, packages/icons-tnt/tsconfig.json, packages/icons/tsconfig.json, packages/localization/tsconfig.json, packages/main/tsconfig.json, packages/theming/tsconfig.json, packages/tools/tsconfig.json
The default TypeScript moduleResolution was changed to "NodeNext" with #9948 
This is the recommended setting for libraries that should run on nodejs and the browser, but it introduces stricter CJS/MJS checks and is incompatible for existing projects that do not use `"type": "module"` in their package.json
This change reverts the default module resolution and moves it in the individual packages.
More information here:
https://www.typescriptlang.org/docs/handbook/modules/theory.html#module-resolution-for-libraries
=> fix(tools): revert tsconfig moduleResolution to node

packages/main/src/Select.ts
IOption interface is defined without interface keyword and this is leading to missing documentation.
=> docs(ui5-option): correct interface definition

packages/main/src/RangeSlider.ts
In some cases, right clicking on the slider handle throws an error because the mouse `move` event is being handled while the right mouse button is pressed.
This change prevents treating the mouse movement while the right mouse button is pressed as a valid (value affecting) drag interaction.
=> fix(ui5-range-slider): right click on the slider handle does not throw

packages/localization/src/sap/base/i18n/Formatting.ts, packages/localization/src/sap/ui/core/FormatSettings.ts, packages/localization/used-modules.txt, packages/main/test/pages/DatePicker_legacy_test_page.html, packages/main/test/specs/DatePicker.spec.js
With the update of OpenUI5 to version 1.120.17 (https://github.com/SAP/ui5-webcomponents/pull/9432), `Formatting.getLegacyDateCalendarCustomizing` was renamed to `Formatting.getCustomIslamicCalendarData`. Because of this change, `legacyDateCalendarCustomizing` stopped working. This PR fixes the mapping of `legacyDateCalendarCustomizing`, and now it works again.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9980
=> fix(localization): legacy date customization

packages/base/src/config/Language.ts
If the `language` changes dynamically after `fetchCldr` has been called, it's imperative to retrigger it for the new language (even if `boot` has not finished), otherwise an error will be thrown.
=> fix(framework): always fire languageChange regardless of boot status

packages/main/cypress/specs/Form.cy.ts, packages/main/src/Form.ts, packages/main/src/FormGroup.ts, packages/main/src/themes/Form.css, packages/main/src/themes/FormLayout.css, packages/main/test/pages/form/FormGroups3.html, packages/main/test/pages/form/FormGroups4.html, packages/main/test/pages/form/FormGroups5.html, packages/main/test/pages/form/FormGroups6.html, packages/main/test/pages/form/FormHeaderWrapping.html, packages/main/test/pages/form/FormMultipleColumns.html, packages/website/docs/_components_pages/main/Form/Form.mdx, packages/website/docs/_samples/main/Form/CustomHeader/sample.html, packages/website/docs/_samples/main/Form/HeaderTextWrapping/HeaderTextWrapping.md, packages/website/docs/_samples/main/Form/HeaderTextWrapping/main.js, packages/website/docs/_samples/main/Form/HeaderTextWrapping/sample.html, packages/website/docs/_samples/main/Form/Layout/sample.html
Updates the Form web component to latest UX design
Use 3 columns in XL by default (previously 2), e.g the layout property default is changed 
from `S1 M1 L2 XL2` to `S1 M1 L2 XL3`
Related to: https://github.com/SAP/ui5-webcomponents/issues/9963
=> refactor(ui5-form): change default columns number in XL and header text wrapping

packages/base/src/UI5Element.ts
`boot()` cannot be on the same level as `fetchI18nBundles` in a common `Promise.all` because if OpenUI5Support is enabled, `boot()` must have finished for the configuration to be available (and `fetchI18nBundles` needs the configuration).
=> fix: boot sequence

packages/main/src/Input.ts, packages/main/test/pages/Input.html, packages/main/test/specs/Input.spec.js
Downport #9616
Fire input event when user uses the arrow keys to increase or decrease the value of a numeric input
Fixes [#9785](https://github.com/SAP/ui5-webcomponents/issues/9785)
=> fix(ui5-input): properly change numeric input value using the arrow keys

packages/main/src/List.hbs, packages/main/src/themes/GrowingButton.css
With #9977 change we started rendering the busy indicator next to the growing text.
This introduced an issue where we align the growing text slightly to the right of the busy indicator but before the busy indicator is actually shown.
This fix fixes the issue and the growing text is centered before showing the busy indicator.
Fixes: #10047
=> fix(ui5-list): growing button loading layout fixed

packages/main/src/Table.ts, packages/main/src/TableCellBase.ts, packages/main/test/pages/HAlignTable.html, packages/main/test/specs/Table.spec.js, packages/website/docs/_components_pages/main/Table/TableCell.mdx, packages/website/docs/_components_pages/main/Table/TableHeaderCell.mdx
Fixed a problem where the horizontalAlign property would be applied to cells inside the popin area.
In addition I've changed some of the texts reviewed in the last PR (https://github.com/SAP/ui5-webcomponents/pull/9639).
fixes: https://github.com/SAP/ui5-webcomponents/issues/10017
=> fix(ui5-table): wrong horiz. alignm. behavior and wrong texts

packages/main/src/themes/SplitButton.css, packages/main/src/themes/base/SplitButton-parameters.css
Issue:
- The focus outline on key down wasn't clearly visible when the button is `Emphasized`.
=> fix(ui5-split-button): adjust focus outline on keydown

packages/fiori/src/themes/base/DynamicPage-parameters.css
Problem:
In some screen ranges, the header area was misaligned with the title and content, leading to an inconsistent layout.
Solution:
Adjusted the padding of the header area to improve alignment between the title, header area, and content, ensuring a more consistent and visually cohesive layout across all screen sizes.
Fixes: [#10034](https://github.com/SAP/ui5-webcomponents/issues/10034)
=> fix(ui5-dynamic-page): align header area with title and content

docs/09-FAQ.md, packages/website/src/components/Editor/index.js
**Issue**
Windows Contrast themes adjust colors of UI5 Web Components which leads to poor visual. 
**Change**
The PR fixes the issue for the playground samples setting `forced-color-adjust` to `none`. The property allows authors to opt certain elements out of forced colors mode as explained in [MDN](https://developer.mozilla.org/en-US/docs/Web/CSS/forced-color-adjust).
And adds suggestion for fixing it in apps the same way. We don't own the page and we believe this is in the apps domain to set it.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9436 https://github.com/SAP/ui5-webcomponents/issues/9917
Use the following CSS rule:
```CSS
html {
forced-color-adjust: none;
}
``` 
Or to be more precise, you can apply the CSS rule when `forced-colors` mode is `active`:
```CSS
@media …
```
=> docs: turn off forced colors mode in website

packages/main/src/Text.ts, packages/main/src/types/TextEmptyIndicatorMode.ts
Match enum and file name - either use EmptyIndictaroMode for both, or TextEmptyIndictaroMode for both. As currently only the Text is known to have such mode - the change uses TextEmptyIndictaroMode for the enum and the file name.
=> refactor(ui5-text): match enum and file names

packages/fiori/src/themes/ShellBar.css
The input slotted in the search slot must expand to 25rem on larged screens. Currently we have this size set on the wrapper elemenet, but the input doesn't expand to fill it. Moving the max-width to the search input iteself, resolves this.
Additionally, a double padding from the logo area is reset when we have the branding area merged with the title.
=> refactor(ui5-shellbar): apply max-width on search input

.github/actions/commentOnFixedIssues.mjs, .github/workflows/issues-handling.yaml, .github/workflows/release-stable.yaml
Create setup for commenting on issues that have been fixed and released.
For example
https://github.com/SAP/ui5-webcomponents/issues/9982#issuecomment-2444602555
https://github.com/SAP/ui5-webcomponents/issues/8544#issuecomment-2444602554
=> ci: add issues commenting after release

packages/fiori/src/MediaGallery.ts
Issue:
- When removing all of the media-gallery items, the thumbnail
of the last selected item remains displayed
- The gallery fails to clear the displayed content even when there are
no items left in the gallery
Solution:
- Added check for empty items array in _updateSelection method
- Clear selected item reference when no items exist
- Remove displayed content from main item when gallery is empty
Fixes: [#8642](https://github.com/SAP/ui5-webcomponents/issues/8642)
=> fix(ui5-media-gallery): clear selected thumbnail on item removal

packages/compat/src/TableRow.ts, packages/fiori/src/NotificationListItem.ts, packages/fiori/src/NotificationListItemBase.ts, packages/fiori/src/Timeline.ts, packages/main/src/Button.hbs, packages/main/src/Button.ts, packages/main/src/FileUploader.ts, packages/main/src/Link.hbs, packages/main/src/Link.ts, packages/main/src/List.ts, packages/main/src/ListItem.hbs, packages/main/src/ListItem.ts, packages/main/src/ListItemBase.ts, packages/main/src/SplitButton.ts, packages/main/test/specs/List.spec.js
Previously, event marking was used to identify the origin of an event from a specific component, preventing unintended interactions with other components. This approach prevented redundant event processing, particularly in cases of component composition.
Now, if a component receives focus, it will manage most events. The :has(:focus-within) selector checks if the current element (typically the root element) has a focusable child. If a child is focused, we assume it will handle user interactions.
=> chore: replace event marking with focus-within

packages/main/src/ListItem.ts
The `mousedown` event handler currently triggers before focus is applied, which can lead to false positives in the check.
With this PR, the handling of the active state for list items is updated as follows:
- On `mousedown`, the active state is always applied.
- When `focusin` is triggered:
- If the target differs from the list item’s focus DOM reference: This indicates that a child element has gained focus, so the active state should be deactivated to display the correct state.
- If the target matches the list item’s focus DOM reference: Do nothing, as the focus is still on the list item.
- When `focusout` is triggered:
- If the target matches the list item’s focus DOM reference: Deactivate, as the list item may have had its active state set previously.
- If the target differs from the …
=> chore(ui5-li): correct active state

packages/fiori/src/DynamicPage.ts
In order to not get redundant hover state, we should "clean" it on every rerender, since sometimes, when pressing the expand/collapse button, the change of the position of the mouse pointer is ignored according to viewport and the "hovered"
attribute remains in the title. 
I tried to cover the functionality with a test, but the specific mouse behaviour is hard to be mocked.
Fixes: #10019
=> fix(dynamic-page) redundant  title hover removed

packages/fiori/src/DynamicPage.ts, packages/fiori/src/themes/DynamicPage.css, packages/fiori/test/specs/DynamicPage.mobile.spec.js
When scrolling, the header content would snap into place, causing an unintended shift in the page content scroll position. This resulted in the main content scrolling further down than expected, disrupting the user’s view.
Snapping the header set the height of the `headerArea` content to 0, causing a layout shift. This shift created additional space, which moved the main content of the dynamic page upwards unexpectedly.
- Modified `snapTitleByScroll` to handle snapping conditions more precisely, using `requestAnimationFrame` to wait for rendering to complete before adjusting scroll positions.
- Adjusted logic to maintain a stable scroll position when the header snaps or unsnaps, preventing unnecessary layout shifts.
The header now snaps smoothly, maintaining the main content’s scroll …
=> fix(ui5-dynamic-page): improve scrolling smoothness

packages/main/cypress/specs/Toolbar.cy.ts, packages/main/src/Toolbar.ts, packages/main/src/ToolbarButton.hbs, packages/main/src/ToolbarButton.ts, packages/main/src/ToolbarPopoverSelect.hbs, packages/main/src/ToolbarPopoverSeparator.hbs, packages/main/src/ToolbarSelect.hbs, packages/main/src/ToolbarSeparator.hbs, packages/main/test/pages/Toolbar.html, packages/main/test/specs/Toolbar.spec.js
The `getDomRef()` method on `ui5-toolbar-*` items was returning `undefined` instead of a valid DOM reference. This limitation hindered developers from programmatically interacting with the toolbar items within the `ui5-toolbar` component.
- Introduced a custom getDomRef() implementation tailored for ui5-toolbar items, ensuring that the method reliably returns the actual DOM reference of each rendered toolbar item.
Developers can now confidently access and interact with each toolbar item’s DOM element through the `getDomRef()` method, improving the overall developer experience and ensuring consistent functionality within applications.
Fixes: #9996
Related: #9997, #10126
=> fix(ui5-toolbar-*): ensure getDomRef() returns the actual DOM reference

packages/tools/lib/cem/event.mjs
At some point we switched the  defaults of the bubbles. When `bubbles` is not specified, it's false. And this is how the components behave. However, the change was not reflected in the documentation of the events - bubbles is considered `true`, when not present at all.
For example:
Currently, for the Select's close event
```ts
/**
* Fired after the component's dropdown menu closes.
* @public
*/
@event("close")
```
we get `bubbles: Yes`:
but should be `bubbles: No`:
=> docs: fix documentation of event bubbling

packages/main/src/Select.ts
Enhances the `ui5-select` component to support Vue.js v-model directive by emitting an `input` event when the value changes.
Fixes: #9971
=> fix(ui5-select): add support for Vue.js v-model

packages/fiori/src/SideNavigation.ts
Documentation is updated to incorporate the new ui5-navigation-layout component.
=> chore(ui5-side-navigation): adapt documentation 

packages/fiori/src/DynamicPageTitle.hbs, packages/fiori/test/pages/styles/DynamicPage.css, packages/website/docs/_samples/fiori/DynamicPage/Basic/main.css
Issue:
- The subheading width was not 100% and was constrained by the title wrapper’s flex layout.
Solution:
- Moved the subheading slot outside the title wrapper to allow it to take full width.
Additional change:
Aligned the avatar with the title heading and subheading.
Fixes: [#10161](https://github.com/SAP/ui5-webcomponents/issues/10161)
=> fix(ui5-dynamic-page): move subheading slot outside the title wrapper

packages/base/src/features/F6Navigation.ts, packages/main/cypress/specs/Form.cy.ts, packages/main/src/Form.hbs, packages/main/src/Form.ts, packages/main/src/FormGroup.ts, packages/main/test/pages/form/FormF6.html
The following accessibility changes are applied to the Form web component to full-fill the latest spec.
**Form**
- form with groups has role="region"
- form without groups have role="form"
- form are referenced with the form header text (via aria-labelledby)
**FormGroup**
- form groups are referenced with their form group header texts (via aria-labelledby)
- form groups have role="form"
- form groups create a fast navigation group - to jump from one group to another with F6
Fixes: https://github.com/SAP/ui5-webcomponents/issues/9952
=> feat(ui5-form): update to latest accessibility spec

packages/main/cypress/specs/ColorPicker.cy.ts, packages/main/src/ColorPicker.hbs, packages/main/src/ColorPicker.ts, packages/main/src/types/ColorPickerDisplayMode.ts, packages/main/test/pages/ColorPicker.html, packages/main/test/specs/ColorPicker.spec.js, packages/website/docs/_components_pages/main/ColorPicker.mdx, packages/website/docs/_samples/main/ColorPicker/Simplified/Simplified.md, packages/website/docs/_samples/main/ColorPicker/Simplified/main.js, packages/website/docs/_samples/main/ColorPicker/Simplified/sample.html
Introducing a new property `displayMode` for the `ui5-color-picker` allowing users to select between the `default` (classic) color picker or the new `simplified` color picker. 
The simplified picker does not include the RGB inputs and alpha slider.
You can create a color picker in simplified mode as follows: 
```html
<ui5-color-picker display-mode="Simplified"></ui5-color-picker>
```
Which will look as follows:
Fixes: #9979
=> feat(ui5-color-picker): add simplified display mode

packages/base/package.json, packages/fiori/package.json, packages/localization/package.json, packages/main/package.json, packages/main/src/themes/Table.css, yarn.lock
If the table has a fixed size and the text in its columns cannot wrap, the content will be cut off due to overflow when the total width of the columns exceeds the table's width.
This issue, caused by an incorrect size of the busy indicator, has been resolved with the current update.
Fixes: #10168
=> fix(ui5-table): text cut due to column overflow

packages/website/docs/_samples/main/Form/FreeStyleForm/FreeStyleForm.md, packages/website/docs/_samples/main/Form/FreeStyleForm/main.css, packages/website/docs/_samples/main/Form/FreeStyleForm/sample.html
Show-case how applications can apply styles to get better alignment in specific scenarios.
By default, you get this misalignment due to the touch areas of these kind of components - Switch, CheckBox, Radio.
While the components are implemented by design, the misalignment, shown below, should be definitely addressed:
With few lines of CSS, applying small negative margins to shift the components to the left, 
you can get the perfect alignment:
We would not code this styling within the Form to avoid binding with these components (set by outside to the Form Item default slot), that may change any time.
=> docs: update fress-style form sample

packages/main/src/themes/Tokenizer.css, packages/main/src/themes/base/Tokenizer-parameters.css
Touch area in MultiLine mode is now according to specifiaction.
Fixes: #10216
MultiLine Tokenizer was not displayed properly in Safari because there seems to be a difference on how browsers inrerpret the css selectors when nested, therefore switched to a more "modular" approach.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10214
=> fix(ui5-tokenizer): adjust touch area for cozy and compact

packages/main/src/List.ts
Improving the keyboard navigation for the ui5-list when the Load More button is present:
Home Key: 
- If the focus is on the Load More button and the Home key is pressed, the focus moves to the first item in the list.
End Key:
- When pressed once, the focus moves to the last item in the list.
- When pressed again while the focus is already on the last item, the focus moves to the Load More button.
=> feat(ui5-list): add Home and End key handling for Load More button

packages/fiori/cypress/specs/ShellBar.cy.ts
Some basic unit tests suite has been added to test new responsive behaviour.
=> Shellbar unit tests

packages/main/cypress/specs/List.cy.ts, packages/main/src/List.ts
The "Load More" button can now be accessed using the arrow up and down keys:
- Pressing the arrow down key while focused on the last list item now moves focus to the "Load More" button.
- Pressing the arrow up key while focused on the "Load More" button navigates back to the last item in the list.
****
Tests added for:
- End key navigation: Moves focus from first item to last item and then to growing button
- Arrow down/up navigation: Moves focus between last list item and growing button
- Home key on growing button: Moves focus to first list item
=> feat(ui5-list): handle arrow up and down navigation for load more button

packages/main/src/themes/ListItem.css, packages/main/src/themes/ListItemBase.css
The contrast of the additional text in the list item is not sufficient. This change addresses the issue by increasing the contrast of the additional text by adding a text shadow and aligning the component with the design guidelines.
Related: #9869
=> fix(ui5-li): address additional text contrast issue

packages/main/src/Toolbar.ts, packages/main/src/ToolbarButton.ts
This change adds a reference to the actual DOM element in the event data of toolbar-items related events.
Fixes: #9997
=> chore(ui5-toolbar): add targetRef to event data

packages/main/cypress/specs/Button.cy.ts, packages/main/cypress/specs/Link.cy.ts, packages/main/src/Button.hbs, packages/main/src/Button.ts, packages/main/src/Link.hbs, packages/main/src/Link.ts, packages/main/test/pages/Button.html, packages/main/test/pages/Link.html
This change introduces the property `accessibleDescription` property to the `ui5-lnk` and `ui5-button` components. This new property enables developers to provide an accessible description, which sets the `aria-description` attribute for the component.
To provide an accessible description for a Link or Button, you can use the `accessibleDescription` property as follows:
```HTML
<ui5-link accessible-description="This is a link with a description"></ui5-link>
<ui5-Button accessible-description="This is a button with a description"></ui5-Button>
```
* ui5-button: https://github.com/SAP/ui5-webcomponents/issues/5310
* ui5-link: https://github.com/SAP/ui5-webcomponents/issues/3993
=> feat(ui5-button, ui5-link): support accessibile description

packages/main/cypress/specs/TableVirtualizer.cy.ts, packages/main/src/Table.hbs, packages/main/src/Table.ts, packages/main/src/TableGrowing.ts, packages/main/src/TableNavigation.ts, packages/main/src/TableRow.ts, packages/main/src/TableUtils.ts, packages/main/src/TableVirtualizer.ts, packages/main/src/bundle.esm.ts, packages/main/src/themes/Table.css, packages/main/src/themes/TableCellBase.css, packages/main/src/themes/TableRow.css, packages/main/test/pages/Table.html, packages/main/test/pages/TableVirtualizer.html, packages/main/test/specs/Table.spec.js
The ui5-table-virtualizer component is used inside the ui5-table to virtualize the table rows.It is responsible for rendering only the rows that are visible in the viewport and updating them on scroll. This allows large numbers of rows to exist, but maintain high performance by only paying the cost for those that are currently visible.
This component is experimental.
=> feat(table): table virtualization

packages/main/src/Dialog.ts, packages/main/src/themes/Dialog.css
Issue: When the base font in the 'html' element is changed to something different than the default 16px (for example 32px) the width of the dialog can become larger than the width of the phone's display. This is caused by the 'min-width' (20rem) of the dialog. For the dialog on phone it is recommended by the design to set the dialog's property 'stretch' to true to use the full screen size.
The solution: When we have stretched dialog on phone the 'min-width' should
not be applied (the width is 100%).
fixes: #10000
downport of #10199
=> fix(ui5-dialog): width on mobile is not bigger than the phone width

packages/main/src/themes/RatingIndicator.css, packages/main/src/themes/base/RatingIndicator-parameters.css, packages/main/src/themes/sap_horizon/RatingIndicator-parameters.css, packages/main/src/themes/sap_horizon_dark/RatingIndicator-parameters.css, packages/main/src/themes/sap_horizon_hcb/RatingIndicator-parameters.css, packages/main/src/themes/sap_horizon_hcw/RatingIndicator-parameters.css, packages/main/test/pages/RatingIndicator.html
FIXES: https://github.com/SAP/ui5-webcomponents/issues/10162
The solution:  made the "--_ui5_rating_indicator_outline_offset" parameter negative value, so now it can be seen when the rating indicator is focused. Added padding parameter, so the stars of the indicator are not touching the edges of the focus. Made the "--_ui5_rating_indicator_border_radius" parameter bigger.
=> fix(ui5-rating-indicator): outline border is visible when focus

packages/main/src/List.ts
Removed unnecessary `stopImmediatePropagation()` from the if block that handles returning focus to the list within the _onfocusin function.
=> refactor(ui5-list): remove unnecessary stopImmediatePropagation call

packages/main/cypress/specs/FormSupport.cy.ts
The first step in most form tests is to check if the form can be submitted, which depends on the custom components having their validity set without interacting with them. This often causes tests to fail because Cypress tests sometimes run too quickly.
=> chore: stabilize form support tests

packages/main/cypress/specs/Menu.cy.ts, packages/main/src/Menu.ts, packages/main/src/MenuItem.ts, packages/main/test/pages/Menu.html, packages/website/docs/_components_pages/main/Menu/Menu.mdx, packages/website/docs/_samples/main/Menu/DynamicallyAddedItems/DynamicallyAddedItems.md, packages/website/docs/_samples/main/Menu/DynamicallyAddedItems/main.js, packages/website/docs/_samples/main/Menu/DynamicallyAddedItems/sample.html
We now provide an option to set the focus to the first item when a menu is opened.
To achieve that you have to call the focus method of either the Menu or MenuItem parenting the menu you're opening.
How To can be seen in the sample we're adding.
fixes: https://github.com/SAP/ui5-webcomponents/issues/7237
=> fix(ui5-menu): provide a way to focus items on fetch

packages/fiori/src/ViewSettingsDialog.hbs
The dialog is considered as a separate context so it's heading should be `H1`.
Related to: https://github.com/SAP/ui5-webcomponents/discussions/10191
=> fix(ui5-view-settings-dialog): adjust dialog heading level

packages/main/cypress/specs/TableGrowing.cy.ts, packages/main/src/TableGrowing.ts, packages/website/docs/_samples/main/Table/Growing/main.js, packages/website/docs/_samples/main/Table/ScrollToLoad/main.js
Remove the `disabled` property from TableGrowing, as it is not needed in major frameworks and is misleading in its functionality.
=> chore(ui5-table-growing): remove disabled property

packages/fiori/src/DynamicPage.hbs, packages/fiori/src/DynamicPageHeader.hbs, packages/fiori/test/specs/DynamicPage.spec.js
=> fix(ui5-dynamic-page): fix header role

packages/fiori/cypress/specs/UserMenu.cy.ts, packages/fiori/src/UserMenu.hbs, packages/fiori/src/UserMenu.ts, packages/fiori/src/i18n/messagebundle.properties, packages/fiori/src/themes/UserMenu.css
On mobile phone, the header with selected account information should be scrollable and the title and manage account button should be moved to the header of the dialog when scrolled outside the visible view
=> feat(ui5-user-menu): add title and manage button to pin header on phone

packages/main/src/ColorPicker.hbs, packages/main/src/ColorPicker.ts, packages/main/test/specs/ColorPicker.spec.js
fixes: https://github.com/SAP/ui5-webcomponents/issues/10203
=> fix(ui5-color-picker): add tooltip to sliders

packages/main/src/Avatar.ts
`getAttribute` method might return null if the attribute doesn't exist. This means that we need provide fallback to the default value that is defined in the method.
Fixes: #10328
=> chore(ui5-avatar): wrong effective size

packages/main/cypress/specs/TableUtils.cy.ts, packages/main/src/TableUtils.ts
There are certain scenarios, where the row does not have the table as its parent (removed from the table). In these cases the type guard fails as `key in object` calls do not work with undefined values.
Therefore, introducing an additional check to avoid this issue.
Fixes #10340
=> fix(ui5-table): check for undefined in table type guard

packages/base/cypress/specs/Boot.cy.ts, packages/base/lib/generate-styles/index.js, packages/base/src/ManagedStyles.ts, packages/base/src/asset-registries/Themes.ts, packages/base/src/theming/getStylesString.ts, packages/base/src/types.ts, packages/base/test/assets/Themes.ts, packages/main/src/TabContainer.ts, packages/tools/lib/css-processors/css-processor-components.mjs, packages/tools/lib/css-processors/css-processor-themes.mjs, packages/tools/lib/css-processors/shared.mjs
The `StyleDataCSP` type has been removed and `StyleData` / `ThemeData` changed to `string`:
*Old:*
and
*New:*
and
A string is valid JSON, therefore it's not necessary to generate theme data with the `{"_": data}` syntax.
Also, the `StyleDataCSP` format (`packageName` + `fileName` + `content`) is now redundant as all modern browsers support adopted stylesheets.
All theme/component style-build scripts have been modified to export strings in`.js`, `.ts` and `.json` variations.
- **Theme parameters**
*Old:*
*New:*
- **Component parameters**
*Old:*
*New:*
=> chore: remove StyleDataCSP and change StyleData / ThemeData to string

packages/ai/tsconfig.json, packages/compat/tsconfig.json, packages/fiori/tsconfig.json, packages/main/tsconfig.json, packages/tools/tsconfig.json
Move JSX configuration to `tools/tsconfig.json` instead of in every package. This enables 3rd party packages too.
=> chore: extract jsx config in tools/tsconfig.json

packages/base/package-scripts.cjs
When installing 2.6.0-rc.0 in an application, the app build fails to resolve the preact thirdparty files form the "prod" folder (otherwise available in `dist`, but missing in `dist/prod`). In this change, we extend the `generateProd` build step to to copy them as well.
=>  fix(framework): copy preact thirdparty files into `prod`

packages/website/src/components/Editor/examples/counter/main.js, packages/website/src/components/Editor/examples/hello-world/main.js, packages/website/src/components/Editor/index.js, packages/website/src/pages/play.tsx
Update the playground page to work with JSX.
Type checking is broken locally and for nightly, since the local web server and the github pages hosting the `d.ts` files returns an incorrect mime type.
Also fixes the `isContentEditable` error.
=> docs: upgrade examples to JSX

docs/3-frameworks/03-Vue.md
Add a step-by-step guide to integrate UI5 Web Components into Nuxt applications.
This guide includes instructions for:
- Setting up a Nuxt project and adding the `@ui5/webcomponents` package.
- Configuring `nuxt.config.ts` to register UI5 Web Components as custom elements by updating `compilerOptions.isCustomElement`.
- Importing and using UI5 Web Components explicitly in Nuxt templates, since auto-import functionality is not yet supported.
Additionally, the guide provides examples for importing components and rendering them within templates, along with a brief explanation of Nuxt for developers unfamiliar with the framework.
This addition aims to support developers by providing clear and concise instructions for integrating UI5 Web Components into Nuxt projects.
=> docs(frameworks-vue): add nuxt integration guide

packages/tools/lib/cem/event.mjs
The API generation was failing because event types are retrieved from a class member named `eventDetails`. To identify this, we needed to iterate through all class members and check their names. However, the constructor is also part of class members, but it is not treated as member by typescript because it doesn't have name.
=> fix(build): generation of custom-elements.json

packages/main/cypress/specs/Toolbar.cy.ts, packages/main/src/Toolbar.ts, packages/main/src/themes/Toolbar.css, packages/main/src/themes/base/Toolbar-parameters.css, packages/main/test/pages/Toolbar.html
If the content width of ui5-toolbar fits within the toolbar's width, the overflow button was incorrectly displayed. Additionally, there was an issue where the last visible item had extra padding because a selector never matched. This pull request fixes both problems by ensuring the overflow button only appears when necessary and removing the unnecessary padding from the last item.
Fixes: #10376
=> fix(ui5-toolbar): hide overflow button when content fits

packages/main/src/FileUploader.ts
Previously when there wasn't any slotted element in the `<ui5-file-uploader>` an error was thrown on click in the console.
The reason behind this is because of the `getFocusDomRef()`. 
The getter tries to access the first slotted element in the FileUploader resulting in `undefined` when such is missing, while in the `if ()` statement there was a non-nullish assertion (`!`)
```diff
- if (this.getFocusDomRef()!.matches(":has(:focus-within)"))
+ if (this.getFocusDomRef()?.matches(":has(:focus-within)"))
```
Fixes: #10329
=> fix(ui5-file-uploader): use optional chain in onclick check

packages/base/src/theming/getThemeDesignerTheme.ts
We cannot rely on the `Path` field ending on `css_variables`, we have to follow the `<framework>.<lib>.<theme>.<field>` pattern, therefore the custom theme name is the third part of the value, split by `.`
=> fix: custom theme detection

packages/main/src/Popover.ts
reverted, because it breaks popover positioning, when the popover is inside an element with `transform` value
part of #9966
revert of #10316
=> fix(ui5-popover): revert rtl correction fix

packages/fiori/src/themes/DynamicPage.css
Corrected the `z-index` of `.ui5-dynamic-page-title-header-wrapper` to ensure it does not overlap the busy indicator.
Fixes: [#10399](https://github.com/SAP/ui5-webcomponents/issues/10399)
=> fix(ui5-dynamic-page): correct z-index for dynamic page header

packages/main/src/themes/TabInStrip.css
Text shadow is not by design for Horizon or Fiori 3 themes.
fixes: #10262
=> fix(ui5-tab-container): remove text shadow

packages/base/src/FeaturesRegistry.ts, packages/main/src/ColorPalette.ts, packages/main/src/Input.ts
The fix: the `getComponentFeature` function returns either the requested feature, if imported, or `undefined`.
`ui5-input` and `ui5-color-palette` initialized the `i18nBundle` static members of their features without checking for undefined, leading to a runtime error if an app tried to use any of these components without the optional features.
=> fix(framework): getComponentFeature can return undefined

packages/main/src/features/InputSuggestions.ts, packages/main/test/pages/Input.html, packages/main/test/specs/Input.spec.js
=> fix(ui5-input): open popup after toggling show-suggestions

packages/base/src/util/FocusableElements.ts, packages/main/cypress/specs/F6.cy.ts
F6 navigation was finding hidden elements, and this was stopping the navigation between groups.
Fixes: [#10236](https://github.com/SAP/ui5-webcomponents/issues/10236)
=> fix(f6navigation): skip hidden elements

packages/main/test/pages/PopoverArrowBounds.html
After https://github.com/SAP/ui5-webcomponents/pull/8846, fallback values are removed. This PR ensures that `verticalAlign` is not set to `undefined`.
Fixes https://github.com/SAP/ui5-webcomponents/issues/10309
=> test(ui5-popover): fix test page for popover arrow bounds

packages/fiori/src/DynamicPage.ts
When the header was manually snapped before scrolling, the sticky area
state wasn't properly updated, causing visual glitches during unsnap.
Fixes: [#10430](https://github.com/SAP/ui5-webcomponents/issues/10430)
=> fix(ui5-dynamic-page): update header sticky on manual snap

packages/fiori/cypress/specs/DynamicSideContent.cy.ts, packages/fiori/src/DynamicSideContent.ts, packages/fiori/src/DynamicSideContentTemplate.tsx, packages/fiori/src/i18n/messagebundle.properties, packages/fiori/test/pages/DynamicSideContent.html, packages/fiori/test/specs/DynamicSideContent.spec.js
Until now the **Dynamic Side Content** component (`<ui5-dynamic-side-content>`) had `role` with value **complementary** and fixed translatable `aria-label` only for its **Side Content** area.
With this PR is intruduced new property `accessibilityAttributes` that can be used for setting of custom `aria-label` texts for both **Main Content** and **Side Content** areas. Also, a `role` attribute with value **main** and a fixed translatable label is provided for the **Main Content** as a fallback if there is no custom label defined.
There are tests added for the new feature.
Fixes: #8612
=> feat(ui5-dynamic-side-content): add customizable aria labels

packages/fiori/src/DynamicPage.ts
Issue:
- When header was pinned before scrolling, unpinning would reset scroll position due to incorrect sticky area state.
Solution:
- Set sticky area to true on pin to preserve scroll state.
Fixes: [#10440](https://github.com/SAP/ui5-webcomponents/issues/10440)
=> fix(ui5-dynamic-page): prevent scroll position reset on unpinning the header

packages/website/docs/_components_pages/fiori/DynamicPage/DynamicPage.mdx, packages/website/docs/_components_pages/fiori/DynamicPage/DynamicPageHeader.mdx, packages/website/docs/_components_pages/fiori/DynamicPage/DynamicPageTitle.mdx, packages/website/docs/_components_pages/fiori/NavigationLayout.mdx, packages/website/docs/_components_pages/fiori/Timeline/TimelineGroupItem.mdx, packages/website/docs/_components_pages/main/Form/Form.mdx, packages/website/docs/_components_pages/main/Form/FormGroup.mdx, packages/website/docs/_components_pages/main/Form/FormItem.mdx, packages/website/docs/_components_pages/main/List/ListItemGroup.mdx, packages/website/docs/_components_pages/main/Table/Table.mdx, packages/website/docs/_components_pages/main/Table/TableCell.mdx, packages/website/docs/_components_pages/main/Table/TableGrowing.mdx, packages/website/docs/_components_pages/main/Table/TableHeaderCell.mdx, packages/website/docs/_components_pages/main/Table/TableHeaderRow.mdx, packages/website/docs/_components_pages/main/Table/TableRow.mdx, packages/website/docs/_components_pages/main/Table/TableSelection.mdx, packages/website/docs/_components_pages/main/Text.mdx, packages/website/docs/_components_pages/main/Tokenizer.mdx
There are a lot of components marked as new but available for 6 months+ => mark only the most recent as "new"
=> docs: update component badges in website

packages/main/src/Button.ts, packages/tools/lib/cem/custom-elements-manifest.config.mjs
Currently, the Button emits a native click that doesn't need and doesn't have an event decorator, but at the same time event decorators are the source for displaying events in the website, moreover to include events in the custom elements manifest.
Until we find better way to describe native events, or change the event to custom (due to other considerations), we manually add the native click event entry to the custom elements manifest.
=> docs: fix jsdoc issues with native click

packages/main/src/Form.ts, packages/main/src/FormGroup.ts, packages/main/src/FormItem.ts, packages/website/docs/_components_pages/main/Form/FormGroup.mdx, packages/website/docs/_components_pages/main/Form/FormItem.mdx
Since the component is available for 6 months +  design has been finalised in the end of 2024 and we don't expect major design changes, we now remove the "experimental" flag.
=> docs(ui5-form): remove exp flag

packages/base/src/UI5Element.ts, packages/main/src/Popover.ts
Previously the Popover's code assumed that if the opener is an UI5Element, then the DOM ref of the opener is the result of the `getFocusDomRef` method, which is not always the case.
There are also noticeable misalignments of the popover that are caused by this fact. For example here the popover is shifted as it's aligned with the inner input (the focus dom ref):
With this change, the popover will use the getFocusDomRef oof the opener, only if the opener is abstract UI5Element,
with no effect on the rest of the cases.
=> fix(ui5-popover): fix opener reference

packages/create-package/template/src/MyFirstComponent.hbs, packages/create-package/template/src/MyFirstComponent.ts, packages/create-package/template/src/MyFirstComponentTemplate.tsx
Running `npm init @ui5/webcomponents-package` will generate jsx component template (previously hbs template).
=> feat(create-package): generate jsx component template

packages/main/src/ToastTemplate.tsx
Fix template - without brackets the condition is treated as string and appended to the DOM.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10558
=> fix(ui5-toast): fix template and remove additional text

packages/main/cypress/specs/Toolbar.cy.ts, packages/main/src/Toolbar.ts, packages/main/src/themes/sap_horizon_dark/parameters-bundle.css
This fix ensures that the overflow button does not appear when the component is initially rendered in a hidden container and later made visible.
=> fix(ui5-toolbar): correct display of overflow button in hidden container

packages/main/src/themes/Toolbar.css, packages/main/src/themes/base/Toolbar-parameters.css
This PR fixes regression introduced with: https://github.com/SAP/ui5-webcomponents/pull/10405. Gap is not part of the overflow calculations and items overflow lately.
=> fix(ui5-toolbar): overflow behaviour

packages/base/src/UI5Element.ts, packages/base/src/decorators/i18n.ts, packages/fiori/src/BarcodeScannerDialog.ts
**Problem:**  
The i18n bundle is stored as a static property in the child class where the `i18n` decorator is last used. This creates an issue when trying to access the static property from a parent class if it is overridden in the child class. The result might be `undefined` because the bundle is only stored in the class where the decorator was last used.
This issue can be observed on the https://sap.github.io/ui5-webcomponents/nightly/components/Tree/
Note: The issue is reproducible only if the `ui5-tree` and `ui5-tree-item` components are loaded. For local testing, the defined components in the bundle should be limited to just these two.
**Example:**  
```typescript
abstract class ListItem extends ListItemBase {
@i18n("@ui5/webcomponents")
static i18nBundle: I18nBundle;
get …
```
=> fix: i18n decorator property definition

packages/main/src/Token.ts, packages/main/src/Tokenizer.ts, packages/main/src/TokenizerPopoverTemplate.tsx
Tokenizer shows list item for each to token in the N-more popover. This means that _isVisible property is redundant and it has no value.
=> chore(ui5-tokenizer): simplify popover items calculation

packages/main/test/specs/DateRangePicker.spec.js
The test would fail because the years in `ui5-year-picker` shift depending on the current year. This fix updates the test to use the first year in the picker, which is always at the first index.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10451
=> chore: stabilize test

packages/main/src/TreeItemCustom.ts
Stop propagation of arrow down events when interacting with elements in the content slot, enabling proper functionality of interactive elements while preserving tree navigation.
Fixes: [#10474](https://github.com/SAP/ui5-webcomponents/issues/10474)
=> fix(ui5-tree): improve keydown handling in content slot

packages/fiori/src/DynamicPage.ts, packages/fiori/src/themes/DynamicPage.css
- Replace media-range attributes with container queries for responsive paddings
Fixes: [#10564](https://github.com/SAP/ui5-webcomponents/issues/10564)
=> fix(ui5-dynamic-page): prevent layout shift with container queries

packages/fiori/src/themes/DynamicPageHeader.css, packages/fiori/src/themes/base/DynamicPageHeader-parameters.css
Removed unnecessary padding-top and padding-bottom from `ui5-dynamic-page-header-root` to reduce spacing between the title and content.
Fixes: [#10413](https://github.com/SAP/ui5-webcomponents/issues/10413)
=> fix(ui5-dynamic-page): remove redundant padding

packages/fiori/src/ShellBar.hbs, packages/fiori/src/ShellBar.ts, packages/fiori/src/ShellBarSpacer.ts, packages/fiori/src/bundle.esm.ts, packages/fiori/src/themes/ShellBar.css, packages/fiori/test/pages/ShellBar.html, packages/fiori/test/pages/ShellBar_evolution.html, packages/fiori/test/specs/ShellBar.spec.js, packages/fiori/test/ssr/component-imports.js
This pull request introduces changes to the ShellBar component to improve content management and introduces a new `ui5-shellbar-spacer` element for better layout separation. Below are the 
**Refactored Slots:**
- Replaced `startContent` and `endContent` slots with a unified `content` slot.
Added new computed properties (startContent and endContent) to dynamically calculate items before and after the `ui5-shellbar-spacer`. This is usefull in order to keep the current implementaion around the additional items slots, like resposnsive design, overflow, etc.  
**Addapted tests:**
- some tests were previously working correctly based on a side effect where a shellbar cofngured with `show-search-field` was initially loaded with closed input.
- Serves as a visual separator between the start and …
=> feat(ui5-shellbar): introduce content slot

packages/main/cypress/support/commands/ColorPalette.commands.ts, packages/main/src/ColorPalette.ts, packages/main/src/features/ColorPaletteMoreColorsTemplate.tsx, packages/main/test/specs/ColorPalette.spec.js
Changes:
- Querying the shadow DOM and manually modifying the composed components' state is an anti-pattern. The component was reworked to use state so that the changes to the composed elements are done via bindings.
**Important:** this will enable the rework to component features (they will become dynamic imports) - the feature template will be loaded dynamically and executed at a later stage, therefore _there can't be any functionality that directly queries elements in the shadow DOM_ (they won't be there until the feature template has been dynamically loaded and executed) 
- two improvements to the Cypress test: the OK button selector is improved (very minor) and more importantly, the command **waits till the dialog has closed** - this ensures that the next command won't run until the …
=> chore: make color palette more colors declarative

packages/ai/src/Button.ts, packages/ai/src/ButtonState.ts, packages/ai/test/pages/Button.html, packages/website/docs/_samples/ai/Button/ButtonSplitMenu/main.js, packages/website/docs/_samples/ai/Button/ButtonSplitMenu/sample.html
We're improving API naming. We have 3 changes in the API.
CHANGE: In the ButtonState we change the `splitMode` property to `showArrowButton`. 
BEFORE:
```HTML
<ui5-ai-button-state name="revise" text="Revise" icon="ai" split-mode></ui5-ai-button-state>
```
NOW:
```HTML
<ui5-ai-button-state name="revise" text="Revise" icon="ai" show-arrow-button></ui5-ai-button-state>
```
CHANGE: In the Button, we change the `activeArrowButton` to `arrowButtonPressed` following the convention in the framework.
```TS
function menuOpenHandler() {
var button = menu.opener;
button.activeArrowButton = true;
}
```
NOW:
```TS
function menuOpenHandler() {
var button = menu.opener;
button.arrowButtonPressed = true;
}
```
CHANGE: In the Button we also change the `arrow-click` event name to `arrow-button-click`, so …
=> refactor(ui5-ai-button): change api names

packages/website/docs/_samples/fiori/SideNavigation/Basic/main.js
Missing import resulted in side navigation sample not loading in the playground
Fixes: #10592
=> fix(ui5-side-navigation): corrects playground sample 

packages/main/cypress/specs/Card.cy.ts, packages/main/src/CardHeader.ts, packages/main/src/CardHeaderTemplate.tsx, packages/main/test/specs/Card.spec.js
=> fix(ui5-card): fix accessibiity role position

packages/fiori/src/TimelineItemTemplate.tsx, packages/fiori/src/themes/TimelineItem.css
Previously within our `ui5-timeline-item` component, when an exceptionally long text was provided in the `title-text`, `subtitle-text` or `name` properties, the content was being hidden due to missing properties for text wrapping.
With this change we now correctly wrap the words of the content, by leveraging the `word-break` CSS property, so now the whole content is being shown.
Fixes: #10303
=> fix(ui5-timeline-item): correct wrapping on long text

packages/main/src/SplitButton.ts
During the work on another task I have found that when a default action of a `ui5-split-button` is activated by pressing of `Space` key, the `click` event is fired twice - on **keydown** and on **keyup**. It should be fired only once on **keyup** only if the `Space` is pressed and before the release `Escape` or `Shift` is not pressed (this is accessibility feature related to all buttons).
This PR fixes the issue.
=> fix(ui5-split-button): fix doubled click event when space is pressed

packages/main/cypress/specs/MultiComboBox.cy.ts, packages/main/src/MultiComboBox.ts
=> fix(ui5-multi-combobox): fix valueState background set while typing

packages/main/src/themes/Switch.css
Previously on our `ui5-switch` component, focus was being applied even if the root element was not clicked. 
With this change, focus is applied only when the `ui5-switch`'s touch area is clicked.
Fixes: #10567
=> fix(ui5-switch): apply focus only on root element click

packages/main/src/TimePicker.ts
When the `ui5-datetime-input` component was introduced, an internal getter in the `ui5-timepicker` wasn't updated. As a result, pressing any key triggered errors.
This change resolves those errors by correctly referencing the new private component, ensuring the timepicker’s internal logic functions as intended.
=> fix(ui5-timepicker): adapt new private component with internal logic

packages/main/src/TableGrowing.ts, packages/main/src/types/TableGrowingMode.ts
Add special note regarding Scrolling in TableGrowing description to ensure its availability in the React Wrapper.
If the type is set to `Scroll`, but the Table is not scrollable yet (not enough items, etc.), the table will render a growing button. This will ensure that growing can always be triggered.
Fixes #10481
=> docs(ui5-table-growing): add note for scroll type

packages/website/docs/_samples/patterns/AIRegenerate/Basic/main.js, packages/website/docs/_samples/patterns/AIRegenerate/Basic/sample.html
Previously, in our AI Regenerate pattern sample, the dialog notifying users that fields would be regenerated with AI-generated content continued to appear every time someone clicked the "Regenerate" button—even when the corresponding checkbox was selected.
With this change, the checkbox selection is being taken into account and no longer displays the dialog repeatedly.
=> chore: address ai regenerate pattern feedback

packages/fiori/cypress/specs/SideNavigation.cy.ts, packages/fiori/src/SideNavigationItem.ts
=> fix(ui5-side-navigation): don't toggle expanded state of items in popover

packages/website/docs/_samples/ai/Button/ButtonSplitMenu/main.js, packages/website/docs/_samples/ai/Button/ButtonSplitMenu/sample.html
There is a recommendation from AI topics design team to change the label of one state of AI button in split button mode sample from 'Revise' to 'Regenerate'.
=> docs(ui5-ai-button): change split mode label in the sample

packages/website/src/components/Editor/playground-support.js
Documentation samples don't display correctly in any theme other than Horizon light. Upon loading via getThemeProperties, the website loaders used to respond with the old format {_: stylesData } (removed with https://github.com/SAP/ui5-webcomponents/pull/10368), which led to wrong creation of the adopted stylesheets
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10607
=> docs: fix theme switch in website

packages/website/src/components/Editor/index.js
opening the playground for the first time loads a project with a `main.tsx` file and stores it in localStorage
if the playground is opened and there was an old `main.js` or `main.ts` file stored from the old template default, then the new one has to be removed, otherwise two files show up
if the playground is opened via a share link (from the samples for example), then both `main.ts` and `main.tsx` exist and the sample is broken until `main.tsx` is removed.
this change fixes the both issues.
=> docs: remove new default main file if shared/save project has an old default main file

packages/main/src/FileUploader.ts
Previously, when using screen reader with `ui5-file-uploader` with attribute `hide-input` set to `true`, the check 
`this.getFocusDomRef().matches(":has(:focus-within)")` on our `_onclick()` event handler was falsy when the component was being focused with screen reader ON, preventing the `click` event from happening.
The reason may be that with the screen reader on, focus is **most likely** landing on the parent element itself (not on a child), which breaks the `:has(:focus-within)` check.
The `:has(:focus-within)` checks - "does this element contain at least one child that is `:focus-within`", which excludes the parent itself causing the check to be falsy in those scenarios.
With this change, the `element.matches(":focus-within")` checks -"Is this element or any of its children …
=> fix(ui5-file-uploder): match focus correctly with screen readers

packages/main/src/Select.ts, packages/main/src/SelectPopoverTemplate.tsx
We can now navigate through Select's options with arrow keys after clicking custom value state message slot.
Fixes: #10661
=> fix(ui5-select): improved custom value state click behavior

packages/base/src/features/patchPopup.ts
Currently, `patchPopup.ts` checks for open native popovers in the body only, which is incorrect. It should check inside shadow roots as well.
closes: https://github.com/SAP/ui5-webcomponents/issues/10740
=> fix(framework): improve check for native popovers

packages/main/src/List.ts
=> docs(ui5-list): improve "item-click" event description

packages/main/cypress/specs/Avatar.cy.tsx, packages/main/src/Avatar.ts
=> fix(ui5-avatar): announce initials

packages/tools/components-package/cypress/support/component.d.ts, packages/tools/components-package/cypress/support/component.js
In the previous solution, the mount function was executed twice because the invoke function runs once for each chainer it contains.
=>  chore: mount JSX only once in tests

packages/fiori/src/FlexibleColumnLayoutTemplate.tsx, packages/fiori/src/themes/FlexibleColumnLayout.css
- Problem:
The grip did not meet the minimum target size requirements.
- Solution:
Add a container div around the grip icon to control the minimum target size, setting it to 1.5rem width and 2rem height.
- Explanation:
**Restructured the grip to handle width and height at the div level instead of the icon because the .ui5-icon-root class (which gets automatically applied to icons) sets width and height to 100%. Applying the dimensions directly to the icon would cause it to stretch and fill the entire available space, distorting its proportions.**
Fixes: [#10669](https://github.com/SAP/ui5-webcomponents/issues/10669)
=> fix(ui5-flexible-column-layout): adjust grip minimum target size

packages/base/src/CustomElementsRegistry.ts, packages/base/src/CustomElementsScopeUtils.ts
To address wrong use of scoping, which happens more often recently, we log a warning when scoping is set after any tag definition. Because for scoping to work, it must be set and known before custom elements definitions.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10771
=> chore: warn when scoping suffix is set too late

packages/main/src/themes/base/Select-parameters.css, packages/main/src/themes/sap_fiori_3_hcb/Select-parameters.css, packages/main/src/themes/sap_fiori_3_hcw/Select-parameters.css, packages/main/src/themes/sap_horizon_hcb/Select-parameters.css, packages/main/src/themes/sap_horizon_hcw/Select-parameters.css
The Select component is reusing the input styles, there were still some vars which were not removed.
=> chore(ui5-select): remove unused css vars

packages/main/cypress/specs/MultiInput.cy.tsx
Token is used in the test cases but not imported.
=> chore: fix MultiInput test

packages/fiori/src/types/TimelineGrowingMode.ts
The TimelineGrowingMode enum was lacking the public tag and some data in the custom-element manifest was missing.
The UI5 Web Components for Angular tooling is using it and depends on it to generate properly the UI5 Web Components wrappers.
=> docs: fix TimelineGrowingMode enum docs

packages/ai/package.json, packages/fiori/package.json, packages/main/package.json, packages/tools/components-package/nps.js
Run single Cypress test with `test:cypress:single`
```sh
cd packages/{package}
yarn test:cypress:single ./cypress/specs/{Component}.cy.tsx
```
=> test: add command for single cy test run

packages/main/src/MultiComboBoxTemplate.tsx
This is the Combo
This is the Select
And this is the Multi prior the current change:
Although the Select and the Combo are also behind the latest specs (see this [issue](https://github.com/SAP/ui5-webcomponents/issues/10819)) and the icon pressed state seems to be changed, still the Multi does not get any icon styling and this is now corrected. Once the shared InputIcon styles is updated, all components with input and icon will get it - including the MultiComboBox.
For now, this is the Multi with the change (its icon pressed state looks like the Combo and the Select):
=> chore(ui5-multi-cbx): apply icon pressed styles

packages/main/src/themes/Button.css
fixes: https://github.com/SAP/ui5-webcomponents/issues/10777
downport of: https://github.com/SAP/ui5-webcomponents/pull/10786
=> fix(ui5-button): remove tap highlight on safari

packages/main/src/bundle.esm.ts, packages/main/test/unit/vitest.test.js
Basic jsdom support was added with https://github.com/SAP/ui5-webcomponents/pull/10606
Later, a bug was found in the `ui5-button` which was using some non-existent functionality (fixed with https://github.com/SAP/ui5-webcomponents/pull/10782)
This change adds a smoke test that will run for all components from the `main` package by doing the following for each registered tag in the bundle:
```ts
// step 1 - it should be possible to create every element
const el = document.createElement(tag);
// step 2 - adding it in the document should not fail (connectedCallback and render)
document.body.appendChild(el)
```
=> chore: create and connect all main components to test jsdom support

packages/main/src/DateTimeInput.ts, packages/main/src/TimePicker.ts, packages/main/src/TimePickerPopoverTemplate.tsx, packages/main/src/TimePickerTemplate.tsx
We encountered an issue on mobile devices where opening the `ui5-time-picker`'s time selection popover by clicking the input field (instead of the icon) results in an empty value state message in the header.
The reason behind this was that there was a racing condition between the ResponsivePopover and the Popover in the template, where the first one, 'steals' the `slot=valueStateMessage`. 
The first component to access the valueStateMessage slot claims it, and since a given light DOM node can only be assigned to one slot at a time, the other component ends up without the value state message.
=> fix(ui5-time-picker): display value state message in popover's header correctly on mobile

packages/website/docs/_samples/main/Button/CustomStyling/sample.html
Updated the sample for the `ui5-button` with custom styling to align with the accessibility guidelines.
=> fix(ui5-button): update sample

packages/main/src/Input.ts, packages/main/src/features/InputSuggestions.ts
There was some legacy code mistakenly left in the Input Suggestions, which previously caused items to receive focus (as was the case with non-physical items). This should no longer happen, and only a fake focus should now be applied to the Input Suggestions.
FIXES: #10830
=> chore(ui5-input): fix failing tests

packages/tools/lib/cem/custom-elements-manifest.config.mjs, packages/tools/lib/cem/utils.mjs
TypeScript decorators can be imported in two ways:  
- **Default import** from `@ui5/webcomponents-base/dist/decorators/{decoratorName}.js`  
- **Named import** from `@ui5/webcomponents-base/dist/decorators.js`  
Recently, the `event.js` decorator was deprecated and replaced with `event-strict.js`. When using the default import, the decorator could retain its old name, and the custom element analyzer would still process it correctly. However, when using the named import, the `@eventStrict` decorator was not processed, leading to missing parts of the component's API.  
This PR adjusts the custom element analyzer to correctly process both `@event` and `@eventStrict` decorators.
=> chore: correct generation of events in cem

packages/main/src/themes/CheckBox.css, packages/main/test/pages/CheckBox.html, packages/main/test/specs/MultiComboBox.mobile.spec.js
Ensure focus is applied consistently around the checkbox container and respective text, aligning behavior with other components.
Fixes #10566
=> fix(ui5-checkbox): ensure consistent focus behavior

packages/main/cypress/specs/base/Events.cy.tsx, packages/main/src/Select.ts
Stop bubbling of the open event as it causes issues when the Select is used inside Dialog.
It's likely for consumers to listen for the Select's open on the Select level, not on a parent of the Select.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10422
=> refactor(ui5-select): stop  bubbling of the `open` event

packages/fiori/src/themes/FlexibleColumnLayout.css, packages/fiori/src/themes/base/FlexibleColumnLayout-parameters.css
- Problem:
. High Contrast Black/White themes had missing focus indicators
. The CSS parameter --_ui5_fcl_separator_focus_border was undefined when switching to High Contrast themes (HCB/HCW)
- Solution:
. Replaced border-based focus with outline and adjusted offset to ensure proper focus visualization across all themes
Fixes: [#10670](https://github.com/SAP/ui5-webcomponents/issues/10670)
=> fix(ui5-flexible-column-layout): correct focus outline styles

packages/main/cypress/specs/Avatar.cy.tsx, packages/main/src/AvatarTemplate.tsx
Now, when the `ui5-avatar` is used with an icon, its accessible-name is correctly set at the SVG level, ensuring proper announcement.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10461
=> fix(ui5-avatar): fix acc-name announcement

packages/main/src/themes/Tag.css
The tags with icon have same alignment compared to those without. 
Fixes: #10810
=> fix(ui5-tag): fix tag alignment

packages/main/src/TableHeaderCellActionAI.ts, packages/main/src/TableRowAction.ts, packages/main/src/TableRowActionNavigation.ts, packages/main/src/types/TableCellHorizontalAlign.ts, packages/main/src/types/TableGrowingMode.ts, packages/main/src/types/TableOverflowMode.ts, packages/main/src/types/TableSelectionMode.ts, packages/tools/lib/cem/utils.mjs, packages/website/build-scripts/api-reference-generation/component-file.mjs, packages/website/docs/_components_pages/ai/Button/Button.mdx, packages/website/docs/_components_pages/ai/Button/ButtonState.mdx, packages/website/docs/_components_pages/ai/PromptInput.mdx, packages/website/docs/_components_pages/main/Table/Table.mdx, packages/website/docs/_components_pages/main/Table/TableCell.mdx, packages/website/docs/_components_pages/main/Table/TableGrowing.mdx, packages/website/docs/_components_pages/main/Table/TableHeaderCell.mdx, packages/website/docs/_components_pages/main/Table/TableHeaderCellActionAI.mdx, packages/website/docs/_components_pages/main/Table/TableHeaderRow.mdx, packages/website/docs/_components_pages/main/Table/TableRow.mdx, packages/website/docs/_components_pages/main/Table/TableRowAction.mdx, packages/website/docs/_components_pages/main/Table/TableRowActionNavigation.mdx, packages/website/docs/_components_pages/main/Table/TableSelection.mdx, packages/website/docs/_components_pages/main/Table/TableVirtualizer.mdx, packages/website/docs/components/patterns/AI Acknowledgement.mdx, packages/website/docs/components/patterns/AI CustomPrompt/AI CustomPrompt.mdx, packages/website/docs/components/patterns/AI GuidedPrompt.mdx, packages/website/docs/components/patterns/AI QuickPrompt.mdx, packages/website/docs/components/patterns/AI Regenerate.mdx, packages/website/docs/components/patterns/SelectionAssistant/Selection Assistant.mdx, packages/website/src/css/custom.css
A visual indication for component deprecation has been added to the playground. Previously, a message was automatically displayed for components in an experimental state. Now, if a component is deprecated, the deprecation message will override the experimental message and be displayed instead.  
In addition:
- Enabled the experimental tag for enums.  
- Removed unnecessary experimental CSS classes from component pages (these are added automatically).  
- Unmarked patterns as experimental since they are examples and do not have compatibility concerns.
=> chore: add deprecation message in component pages

packages/base/cypress/specs/Events.cy.tsx, packages/base/src/jsx-utils.ts, packages/base/test/test-elements/Events.tsx
There are some assumptions in the code base that event names are `kebab-case`. This change adds support for `camelCase` event names
Event name: `token-delete` (kebap-case)
fired events    |   TSX usage:    | subscribed event:
------------------ | --------------- | ------------------
`token-delete`     |                 |
`ui5-token-delete` | `onTokenDelete` | `ui5-token-delete`
`TokenDelete`      |                 |
`ui5-TokenDelete`  |                 |
In the table above, the subscribed event matches the declared event and is subscribed with the prefix so noConflict works
Event name: `tokenDelete` (camelCase)
|   fired events    |   TSX usage:    | subscribed event: |            |
| ----------------- | --------------- | ----------------- | ---------- |
| `tokenDelete`     | …
=> fix(framework): allow usage of events with any name not only kebab-case

packages/ai/package.json, packages/fiori/package.json, packages/main/package.json, packages/tools/components-package/nps.js
Rework the `test:cypress:single` to run without `nps`, as with nps the command was unexpectedly starting additional tasks after finishing with the test run. The additional task is always the first available script in nps.js and it happens to be the clean command, which removes generated resources and sequential test run is not possible without rebuilding these resources, which is not convenient at all.
To run a single Cypress test:
`cd packages/main|fiori|ai`
`yarn test:cypress:single -- ./cypress/specs/Avatar.cy.tsx`
=> test: fix single test run command

packages/main/src/themes/Menu.css
Previously setting a `line-height` property on global level e.g `body { line-height: 0.5rem }` was being inherited by the `ui5-menu` and its `ui5-menu-item`'s which was not convenient.
With this chnange we now prevent the global inheritance of the `line-height` with the following priority:
`ui5-menu-item` > `ui5-menu` > `global (globally no longer takes effect)`, which means if a `line-height` is set to the `ui5-menu`, all of its children (ui5-menu-items) would receive the effect, but if a specific `ui5-menu-item` receives the property, it would take over.
For example, here all children, except the first one (which has explicitly set `style="line-height: 0.5rem;"`) would have `line-height` of `1rem`
```ts
<ui5-menu style="line-height: 1rem;" header-text="Basic Menu with Items" …
```
=> fix(ui5-menu): prevent global line-height inheritance

packages/fiori/src/themes/ShellBar.css
- Override button's default focus border to match shellbar's focus styling
Fixes: [#10598](https://github.com/SAP/ui5-webcomponents/issues/10598)
=> fix(ui5-shellbar): adjust focus style of startButton

packages/main/cypress/specs/Table.cy.tsx, packages/main/cypress/specs/TableSelection.cy.tsx, packages/main/cypress/specs/TableSelections.cy.tsx, packages/main/src/Table.ts, packages/main/src/TableHeaderRow.hbs, packages/main/src/TableHeaderRow.ts, packages/main/src/TableRow.hbs, packages/main/src/TableRow.ts, packages/main/src/TableRowAction.ts, packages/main/src/TableRowBase.ts, packages/main/src/TableSelection.ts, packages/main/src/TableSelectionBase.ts, packages/main/src/TableSelectionMulti.ts, packages/main/src/TableSelectionSingle.ts, packages/main/src/bundle.esm.ts, packages/main/src/types/TableSelectionMode.ts, packages/main/test/pages/Table.html, packages/website/docs/_components_pages/main/Table/TableSelectionMulti.mdx, packages/website/docs/_components_pages/main/Table/TableSelectionSingle.mdx, packages/website/docs/_samples/main/Table/SelectionMulti/SelectionMulti.md, packages/website/docs/_samples/main/Table/SelectionMulti/main.js, packages/website/docs/_samples/main/Table/SelectionMulti/sample.html, packages/website/docs/_samples/main/Table/SelectionSingle/SelectionSingle.md, packages/website/docs/_samples/main/Table/SelectionSingle/main.js, packages/website/docs/_samples/main/Table/SelectionSingle/sample.html
- dedicated selection components `ui5-table-selection-single` and `ui5-table-selection-multi` are added
- old `ui5-table-selection` component is deprecated
Fixes: #9677
=> feat(ui5-table): single and multi selection components added

packages/base/src/UI5Element.ts, packages/base/src/decorators/i18n.ts
With the introduction of i18n storage, all loaded bundles are now stored within `UI5Element` ([PR #10521](https://github.com/SAP/ui5-webcomponents/pull/10521)). This storage mechanism allows child components of a `UI5Element` to share localization data, but the final stored bundle depends on which component loads its bundle last.  
```
class Example extends UI5Element {
@i18n("@ui5/webcomponents")
static i18nBundle: I18nBundle;
}
class Example2 extends UI5Element {
@i18n("@ui5/webcomponents-fiori")
static i18nBundle: I18nBundle;
}
```
Previously, when accessing `i18nBundle`, the storage would always return `@ui5/webcomponents-fiori`, since bundles were stored under a shared key, leading to overwrites.  
With this change, bundles are now stored with their bundle names. As a result:  
- …
=> fix: i18n bundle storage

packages/main/src/Avatar.ts
=> docs(ui5-avatar): add missing CSS example

packages/main/cypress/specs/Select.cy.tsx, packages/main/src/Select.ts, packages/main/src/SelectTemplate.tsx
New "tooltip" property is introduced to the Select component.
When the property is set to a string, it is shown as tooltip when we hover over the component.
Implements: #10855
=> feat(ui5-select): introduced tooltip property

packages/main/cypress/specs/Popover.cy.tsx, packages/main/src/popup-utils/PopoverRegistry.ts
Fixes https://github.com/SAP/ui5-webcomponents/issues/10237
=> fix(ui5-popover): ensure that popover is closed when mousedown propagation is stopped

packages/main/cypress/specs/AvatarGroup.cy.tsx, packages/main/src/AvatarGroup.ts
In some cases overflow button is rendered even though there is only one item in the group.
This change fixes the issue.
Fixes: #10948
=> fix(ui5-avatar-group): fixed unnecessary rendering of overflow button

docs/4-development/08-templates.md, packages/ai/src/PromptInput.ts, packages/base/src/UI5Element.ts, packages/base/src/index.d.ts, packages/fiori/src/NotificationListInternal.ts, packages/fiori/src/NotificationListItem.ts, packages/main/src/ColorPicker.ts
The generated event handlers for events described in `eventDetails` now have the correct type for the `e.currentTarget` parameter
```tsx
<Input onClick={(e => e.currentTarget)} />
// ^^^^^^^^^^^^^
// `ui5-input` element now, was `EventTarget` before
```
Additionally, the `UI5CustomEvent` helper also adds the correct type to the event parameter `e.currentTarget`
Before:
```ts
onInput(e: CustomEvent) {
const value: string = (e.target as Input).value;
```
This works, but the same event handler is also attached to a ui5-slider and the `e.target.value` is a number in that case which goes unnoticed because of the `as Input` type assertion.
After
```ts
onInput(e: UI5CustomEvent<Input, "input">) {
const value: string = e.currentTarget.value;
//                        ^^^^^^^^^^^^^^^^^^^
// …
```
=> feat(framework): add `.currentTarget` to the type of event handler in TSX and UI5CustomEvent

packages/main/src/ToolbarButton.ts
- The ToolbarButton component had no hidden property implemented, which meant that buttons could not be dynamically shown or hidden after the initial render.
Fixes: [#10585](https://github.com/SAP/ui5-webcomponents/issues/10585)
=> fix(ui5-toolbar-button): add hidden property

packages/main/src/themes/List.css
- Added min-height to .ui5-list-nodata to maintain proper spacing.
- Set white-space: normal to .ui5-list-nodata-text to allow text wrapping and applied margin for better vertical alignment.
Fixes: [#10346](https://github.com/SAP/ui5-webcomponents/issues/10346)
=> fix(ui5-list): ensure no data text wraps instead of truncating

packages/main/cypress/specs/AvatarGroup.cy.tsx, packages/main/src/AvatarGroup.ts
Problem: In some cases there the focus outline of the AvatarGroup is incorrect.
Root cause: There is unnecessary inline margin left when dynamically removing Avatars from the AvatarGroup.
Solution: We make sure to always remove the margin when we no longer need it.
Fixes: #10963
=> fix(ui5-avatar-group): fixed focus outline

packages/main/src/Icon.ts, packages/main/test/specs/Icon.spec.js
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10835
With v2 the default mode was changed to "Image" unintentionally, which results in many app reports for icons with no labels.
=> fix(ui5-icon): revert default mode to decorative

packages/main/src/MenuItem.ts
related to: https://github.com/SAP/ui5-webcomponents/issues/10981
After we merge this we will have to wait for [this](https://github.com/SAP/ui5-webcomponents/issues/11041) so it can take effect, because currently declare only applies the JSDoc override, but not the type itself.
=> docs(ui5-menu-item): update accessibilityAttributes documentation

packages/cypress-ct-ui5-webc/package.json
`cypress` and `preact` packages are used in the files shipped to `npm`.
=> chore: correct dependency marking

packages/main/src/Select.ts
In some cases the SelectMenu is discovered by id or reference, but its definition is not completed, and some accessors are not yet available but called from the Select, leading to a JS error in `this.selectOptions.find(..)` (this.selectOptions returns undefined, because menu.options is undefined)
Fixes: https://github.com/SAP/ui5-webcomponents/issues/11019
=> fix(ui5-select-menu): handle late component definition

packages/cypress-ct-ui5-webc/tsconfig.definition.json, packages/cypress-ct-ui5-webc/tsconfig.mount.json
Both TypeScript configurations were configured to process all files in `src` file. With that modules were not in the correct in the correct format that `cypress` expects.
- `definition.js` should be resolved in CommonJS
- `index.js` should be resolved in ESM
=> chore: correct typescript configuration for cypress mount

packages/main/src/Icon.ts
In some frameworks, even if the name is part of the template and added on the ui5-icon, it is sometimes set on a second step and the warning is confusing. Also, not very useful in general, because using the component without an icon name is not something that people will easily miss and even if they miss it - they will quickly get it because nothing will be displayed.
=> chore(ui5-icon): remove 'no name' warning

packages/fiori/src/themes/NotificationListItem.css, packages/fiori/test/pages/NotificationListItem.html
The footer of the NotificationListItem no longer overflows when its content is too long.
Fixes https://github.com/SAP/ui5-webcomponents/issues/10882
=> fix(ui5-li-notification): footer no longer overflows

packages/main/cypress/specs/ComboBox.cy.tsx, packages/main/cypress/specs/MultiComboBox.cy.tsx, packages/main/src/ComboBox.ts, packages/main/src/MultiComboBox.ts, packages/main/src/MultiComboBoxPopoverTemplate.tsx, packages/main/test/pages/ComboBox.html
=> feat(ui5-multi-combobox/ui5-combobox): introduce open property

packages/fiori/cypress/specs/SideNavigation.cy.tsx, packages/fiori/src/NavigationMenuItem.ts, packages/fiori/src/NavigationMenuItemTemplate.tsx, packages/main/src/MenuItemTemplate.tsx
1. Removed obsolete and ineffective `listItemPostContent` hook from MenuItemTemplate
2. Implemented alternative solution for `accessible-name` of NavigationMenuItem's popover
=> refactor(ui5-navigation-menu-item): remove usage of ineffective `listItemPostContent` hook 

packages/tools/lib/create-icons/index.js
We have hardcoded path to the i18n resources, assuming that the icons imports are nested in versioned folder v4, v5, one level below the `generated` folder.
```ts
import { ${accData.key} } from "../generated/i18n/i18n-defaults.js";
```
However, in case of not versioned icons, this is not true anymore, the icon imports become top-level, at the level of the `generated` folder and the imports fail a it should be
```ts
import { ${accData.key} } from "./generated/i18n/i18n-defaults.js";
```
And exactly this happened with an external project of Signavio for custom icons package (mirroring the @ui5/webcomponents-icons package as structure and using @ui5/webcomponents-tools to build it).
Unlike our icons, they don't have versions per theme families.
It was all working so far, the issue did not …
=> fix(tools): fix icon imports to i18n texts

packages/base/package.json
The current base export paths could lead to corrupted production builds if you e.g. import the `setTheme` from  `'@ui5/webcomponents-base/config/Theme.js'` instead of `'@ui5/webcomponents-base/dist/config/Theme.js'`
Due to the not existing `production` case, we were actually running in two different bundles of UI5 Web Components in our production build.
=> fix: keep export paths in base in sync

packages/main/src/Toolbar.ts
Querying the shadow DOM and manually modifying the composed components' state is an anti-pattern. The `ui5-toolbar` component has been reworked to utilize state when calculating its accessibility attributes.
=> chore(ui5-toolbar): set acc attributes declaratively

packages/fiori/cypress/specs/ShellBar.cy.tsx, packages/fiori/src/ShellBar.ts, packages/fiori/src/ShellBarTemplate.tsx
When items are being hidden, the disappearing separators were messing up the math for calculating available space. 
This commit fixes the issue by rendering the hidden separators with the last visible item. This way the space is still resevered and taken into account when calculating the available space. 
The tests are also extended to cover this case.
=> fix(ui5-shellbar): fix separators visibility when items are hidden

packages/main/src/Menu.ts, packages/main/src/MenuItem.ts
Before:
When used in SideNavigation,  the item doesn't have "ui5-menu-item" attribute, because it's a subclass of MenuItem and the navigation checks are failing.
After:
We check with a getter done in the MenuItem class, so even if the class is extended, we will have the correct results in these checks.
fixes: https://github.com/SAP/ui5-webcomponents/issues/10933
=> fix(ui5-menu): fix menu item type fix

packages/fiori/cypress/specs/SideNavigation.cy.tsx, packages/fiori/src/SideNavigation.ts, packages/fiori/src/SideNavigationTemplate.tsx, packages/fiori/test/pages/SideNavigation.html
=> feat(ui5-side-navigation): add accessibleName property

packages/fiori/cypress/specs/DynamicPage.cy.tsx, packages/fiori/src/DynamicPage.ts
Problem:
Several issues occurred with the header snap/pin interaction:
1. When the header was pinned and then snapped, it would glitch into an inconsistent state appearing both snapped and unsnapped simultaneously
2. After unpinning a previously pinned header, attempting to snap it would cause the same visual inconsistency
3. Pinned headers that were snapped remained in a pinned state, causing unexpected behavior
Solution:
- Modified the _toggleHeader method to properly detect when a pinned header is being snapped and ensure it unpins automatically. Also improved the onPinClick method to better handle unpinning when at the top of the page by checking the scroll position and updating the showHeaderInStickArea property accordingly.
Fixes: …
=> fix(ui5-dynamic-page): correct header snap/pin inconsistency at page top

packages/main/cypress/specs/Breadcrumbs.mobile.cy.tsx, packages/main/src/Breadcrumbs.ts, packages/main/src/BreadcrumbsPopoverTemplate.tsx
This update enhances the mobile experience by ensuring all navigation items are accessible from the dropdown menu.
Fixes: #9697
=> fix(ui5-breadcrumbs): show all items in popover on mobile

packages/main/src/Input.ts, packages/main/src/InputTemplate.tsx, packages/main/src/types/InputKeyHint.ts
This change adds 2 additional features to the input in order to be reused better by other internal classes.
- `hint` property - replicates [enterkeyhint](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/enterkeyhint)
- styling party `clear-icon-wrapper` to style internal clear icon
=> chore(ui5-input): add private hint property

.gitignore, packages/cypress-internal/package.json, packages/cypress-internal/src/acc_report/index, packages/cypress-internal/src/acc_report/support.ts, packages/cypress-internal/src/acc_report/task.ts, packages/cypress-internal/src/commands.ts, packages/cypress-internal/src/copy.js, packages/cypress-internal/src/cypress.config.ts, packages/cypress-internal/src/helpers.ts, packages/cypress-internal/tsconfig.json, packages/main/cypress/specs/Button.cy.tsx, yarn.lock
**Note: These changes are intended for use within the monorepo only**
These changes are integrating the `cypress-axe` plugin to enable accessibility testing within the UI5 webcomponents project. As part of the integration, a new `CYPRESS_UI5_ACC` environment  has been added to control the execution of accessibility tests. When set to `true`, it allows generating an accessibility report otherwise, the tests are skipped.  
Additionally, a new global function, `ui5AccDescribe`, has been introduced for test files. This function acts as a wrapper around the standard `describe` function, accepting the same parameters. Internally, it determines whether to run or skip tests based on the `CYPRESS_UI5_ACC` value. The wrapper also injects the necessary `axe-core` tool and includes the `ui5CheckA11y` …
=> chore: integrate `cypress-axe` for accessibility testing

packages/main/src/SelectPopoverTemplate.tsx
Problem:
- List items with role="option" lack required parent with role="listbox".
Solution:
- Set accessibleRole="ListBox" on List component to establish proper ARIA hierarchy.
Fixes: [#11151](https://github.com/SAP/ui5-webcomponents/issues/11151)
Fixes: [#11152](https://github.com/SAP/ui5-webcomponents/issues/11152)
=> fix(ui5-select): add listbox role to meet ARIA parent-child requirements

packages/main/cypress/specs/Calendar.cy.tsx, packages/main/cypress/specs/DayPicker.cy.tsx, packages/main/src/DayPicker.ts, packages/main/test/pages/Calendar.html
Previously when initially rendered the `ui5-calendar` component was "stealing" the focus of the page as well as when being re-rendered since the focus was being applied in the `onAfterRendering()` hook.
With this change we now handle this behaviour, by applying focus only when the `ui5-calendar` is intentionally focused by the end user, ensuring that the focus is not being "stolen" from other interactive web page elements while still ensuring that the correct day is focused.
Fixes: #10728
=> fix(ui5-calendar): remove auto focus of current day on initial render

packages/fiori/src/ShellBar.ts, packages/fiori/src/ShellBarTemplate.tsx
- Added accessible name that announces item title and text with count from data-count.
Fixes: [#11198](https://github.com/SAP/ui5-webcomponents/issues/11198)
=> fix(ui5-shellbar): improve accessibility for shellbar item count announcement

packages/fiori/src/themes/NavigationLayout.css, packages/fiori/src/themes/SideNavigation.css, packages/fiori/src/themes/base/NavigationLayout-parameters.css, packages/fiori/src/themes/sap_fiori_3/parameters-bundle.css, packages/fiori/src/themes/sap_fiori_3_dark/parameters-bundle.css, packages/fiori/src/themes/sap_fiori_3_hcb/parameters-bundle.css, packages/fiori/src/themes/sap_fiori_3_hcw/parameters-bundle.css, packages/fiori/src/themes/sap_horizon/NavigationLayout-parameters.css, packages/fiori/src/themes/sap_horizon/parameters-bundle.css, packages/fiori/src/themes/sap_horizon_dark/NavigationLayout-parameters.css, packages/fiori/src/themes/sap_horizon_dark/parameters-bundle.css, packages/fiori/src/themes/sap_horizon_hcb/NavigationLayout-parameters.css, packages/fiori/src/themes/sap_horizon_hcb/parameters-bundle.css, packages/fiori/src/themes/sap_horizon_hcw/NavigationLayout-parameters.css, packages/fiori/src/themes/sap_horizon_hcw/parameters-bundle.css, packages/website/docs/_samples/fiori/SideNavigation/OverlayMode/main.css
The change
- brings the `box-shadow` by default back as the Side Navigation can be used in different layouts and use-cases with or without NavigationLayout and the box-shadow is by spec
- In case the box-shadow is not necessary (f.e. when the SideNavigation is used in popover), 
it can be removed by single line of css, as it is set on the host and this is what we will suggest now. This will give us time to decide to provide css class or API in future.
=> refactor(ui5-side-navigation): add box-shadow by default

packages/main/src/DateRangePicker.ts
With https://github.com/SAP/ui5-webcomponents/pull/11162, the override still appears and is only partially applied, leading to incorrect CEM information. This PR adds explicit JSDoc for the `isValid` and `isValidInRange` methods.
=> docs(ui5-daterange-picker): correct jsdoc

.github/workflows/issue-reopen-on-comment.yaml
When GitHub issue was closed with comment via `Close with comment` button it was automatically reopened. To ensure that issue is reopened correctly we now check the timestamp of the comment and the timestamp when the issue was closed.
=> chore: auto reopen script

packages/main/cypress/specs/Tree.cy.tsx, packages/main/src/TreeItemBase.ts, packages/main/src/TreeItemBaseTemplate.tsx, packages/main/src/themes/ListItem.css, packages/main/src/themes/TreeItem.css, packages/main/test/pages/List.html, packages/main/test/pages/Tree.html, packages/website/docs/_samples/main/Tree/Basic/main.js
This feature enables semantic icons to be used with the ui5-tree-item
Fixes: https://github.com/SAP/ui5-webcomponents/issues/7481
=> feat(ui5-tree-item): image slot added

packages/fiori/src/themes/SideNavigationItemBase.css, packages/fiori/src/themes/base/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_dark/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_hcb/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_hcw/SideNavigation-parameters.css
Separator line from the hovered two-click item in collapsed Side Navigation
is removed since there are no two click areas in this case.
JIRA: BGSOFUIRODOPI-3443
=> fix(ui5-side-navigation): remove separator line

packages/fiori/cypress/specs/Search.mobile.cy.tsx, packages/fiori/cypress/specs/ShellBar.cy.tsx, packages/fiori/cypress/specs/UploadCollection.cy.tsx, packages/main/cypress/support/commands/ResponsivePopover.commands.ts, packages/main/cypress/support/commands/utils/popup-open.ts
When the detail button is pressed, `editing` mode is activated. In this state, the element with the `.ui5-uci-file-name` class is not rendered in the DOM.
Ensure that the responsive popover is open before interacting with any components inside it.
Skip test due bug inside component https://github.com/SAP/ui5-webcomponents/issues/11314
The responsive popover command should locate a `ui5-popover` or `ui5-dialog` within the shadow root and verify that it is internally visible.
=> chore: stable failing test

packages/fiori/src/ShellBar.ts, packages/fiori/src/ShellBarTemplate.tsx
Enhance accessibility for the ShellBar component by adding support for custom accessibility attributes on the branding/primary title area. This allows developers to provide consistent screen reader announcements for menu buttons across different pages, regardless of the changing page title content.
Fixes: #6826, #8708
=> feat(ui5-shellbar): add branding area accessibility attributes

packages/main/src/Menu.ts, packages/main/src/MenuTemplate.tsx, packages/main/test/pages/Menu.html, packages/website/docs/_samples/patterns/AIQuickPrompt/sample.html
This change introduces a new `horizontalAlign` property to `ui5-menu`, similar to what's available in `ui5-popover`. It allows users to control the menu's horizontal alignment. 
The default value is `start`, but it can also be set to `end`, `center`, or `stretch`.
Setting the property to `end` as follows will align the menu to the end of the opener button:
```html
<ui5-menu horizontal-align="End">
<ui5-menu-item ...
</ui5-menu>
```
The menu will look as follows:
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10765
=> feat(ui5-menu): introduce HorizontalAlign property

packages/fiori/test/specs/Wizard.spec.js, packages/main/src/Button.ts, packages/main/src/SegmentedButton.ts, packages/main/src/SplitButton.hbs, packages/main/src/SplitButton.ts, packages/main/src/themes/Button.css, packages/main/src/themes/SplitButton.css, packages/main/src/themes/ToggleButton.css, packages/main/test/pages/ToggleButton.html, packages/main/test/specs/ColorPalettePopover.spec.js, packages/main/test/specs/Popover.spec.js, packages/main/test/specs/Table.spec.js, packages/main/test/specs/ToggleButton.spec.js, packages/tools/components-package/wdio.js
Button elements can now receive focus when using keyboards on mobile devices. Focus outline is now displayed via CSS pseudo-classes and no longer relies on using the[focused] attribute.
The following components were updated:
* ui5-button
* ui5-toggle-button
* ui5-segmented-button
* ui5-split-button
Fixes: #11024
Downport of: https://github.com/SAP/ui5-webcomponents/pull/8414
=> feat(ui5-button): provide focus support for mobile

packages/fiori/src/ShellBar.ts, packages/fiori/test/pages/ShellBar_evolution.html
The `searchButtonDomRef` has been refactored into an asynchronous method `getSearchButtonDomRef` that waits for the component to finish rendering. This ensures the DOM is available for use cases that require focusing the search button.
A similar code has been applied to the `search-field-toggle` event, which is now fired after rendering is complete.
=> feat(ui5-shellbar): introduce async search btn getter

packages/main/src/Tree.ts
- Problem:
- The issue occurs because the selection-change event from the MultiComboBox bubbles up to the Tree component, which tries to process it as a Tree selection event but the event  doesn't have the expected properties.
- Solution:
- Added validation checks in the _onListSelectionChange method to verify that the expected properties exist before attempting to access them.
Fixes: [#11352](https://github.com/SAP/ui5-webcomponents/issues/11352)
=> fix(ui5-tree): add event validation to selection handler

packages/main/src/themes/Breadcrumbs.css
Bug description: When we have dropdown arrow (when there is not enough space for all the links) and we focus it, the color of the arrow and triple dots remains bluish. It should become white.
This change fixes the issue by improving the CSS selector for making the focused color to be bright.
Fixes: #11336
=> fix(ui5-breadcrumbs): dropdown arrow focused color fixed

packages/create-package/create-package.js
Globby isn't finding any files because the script is being executed from the `bin` folder. Update the file path to explicitly point to the location of the `create-package.js` module and search for template files relative to that path.
=> chore: correct file path of template files

packages/base/package.json, packages/fiori/package.json, packages/localization/package.json, packages/main/package.json, packages/main/src/Popover.ts, packages/main/test/pages/Popover.html, yarn.lock
Resolves the issue where the opener is small and the alignment is not centered.
fixes https://github.com/SAP/ui5-webcomponents/issues/10702
downport of #11275
=> fix(ui5-popover): fix arrow positioning

packages/main/cypress/specs/TableGrowing.cy.tsx, packages/main/src/TableGrowing.ts
When scrolling to grow the first row is focused, which leads to unexpected behaviour during scrolling.
Focusing the first row/last row should only be done if the table has a growing component
Fixes #11298
=> fix(ui5-table-growing): prevent focus while scroll to grow

packages/main/cypress/specs/TableGrowing.cy.tsx, packages/main/src/TableGrowing.ts
When pressing the Growing button with "Enter" instead of clicking it, the growing button stays focused, although
the last remembered row should be focused now.
Removed reset of _currentLastRow in onBeforeRendering to avoid this issue
Fixes #10978
=> fix(ui5-table-growing): remember correct last row with Enter

packages/main/src/themes/base/sizes-parameters.css
According to the new specifications the button/icon width of the `ui5-panel` should be the same for the cozy and compact theme variants (2.75rem)
fixes: #11062
=> fix(ui5-panel): adjust header button width to the new specifications

packages/main/cypress/specs/DateTimePicker.cy.tsx, packages/main/cypress/support/commands/DateTimePicker.commands.ts
Added TypeScript definitions for custom Cypress commands related to the `ui5-datetime-picker` component.​
One test remains skipped due to two open issues in the `ui5-datetime-picker`:​
- Issue #11375
- Issue #11376
=> chore: stabilize `ui5-datetime-picker` tests

packages/fiori/src/themes/DynamicPage.css
Problem:
- The current implementation uses 'container-type: size' which applies containment 
to both width and height dimensions. This creates a problem when combined with 
'height: inherit' as it disrupts the height inheritance chain, causing inner 
components to collapse to zero height while width continues to work correctly.
Solution:
- By changing to 'container-type: inline-size', we maintain containment only for
the inline (width) dimension while allowing height to behave normally. This 
preserves all width-based container queries used for responsive design while
fixing the height inheritance issue.
Related to: [#11309](https://github.com/SAP/ui5-webcomponents/issues/11309)
=> fix(ui5-dynamic-page): change the container-type

packages/fiori/src/FlexibleColumnLayout.ts
Problem:
When disableResizing="true" was set, only the start-mid column separator was 
disabled, while the mid-end separator remained interactive and resizable.
Solution:
- Updated the onSeparatorPress method to check both separator types and prevent 
interaction for the end separator when disableResizing is true
- Modified the endSeparatorTabIndex getter to make it consistent with the start 
separator by removing the explicit -1 return value, which makes it 
unfocusable when disableResizing is true
Fixes: [#11402](https://github.com/SAP/ui5-webcomponents/issues/11402)
=> fix(ui5-flexible-column-layout): disable resizing for both separators

packages/fiori/cypress/specs/FCL.cy.tsx, packages/fiori/src/FlexibleColumnLayout.ts, packages/fiori/src/themes/FlexibleColumnLayout.css
Problem:
1. On initial rendering, hidden columns do not have the required "ui5-fcl-column--hidden" class
2. When a column is being collapsed with animation, the transition to hidden state is not gradual 
Solution
For problem1, the root cause if that the function that sets the required class  is not invoked on initial rendering. 
It is not invoked, because the function in question is a listener for end of animation. However, on initial rendering there is no animation for technical constraints (because on initial rendering the element width a set for a first time).
Therefore, fixed problem1 by synchronously applying the required class when there is no animation
For problem2, the root cause is that the CSS rule "min-width:15.5rem" overrides the "width: 0px" rule (that is set for the purpose …
=> fix(ui5-flexible-column-layout): column visibility issue fixed

packages/fiori/src/themes/ShellBar.css, packages/fiori/test/pages/ShellBar_evolution.html
Avatar font-size was inheriting style for size "S", while it has hardcoded size, which is smaller than "S" and a little bit larger than "XS", so font-size for XS looks more suitable.
=> fix(ui5-shellbar): fixed avatar font-size

packages/main/src/MenuItem.ts
Issue 1:
- The aria-labelledby reference to the `ui5-menu-item` has wrong text.
Issue 2:
- The aria-labelledby reference to the `ui5-menu-item` has redundant text.
Solution:
- Use the text provided from the underlying `ui5-list-item` for an aria-labelledby.
Fixes: #11380
Fixes: #11405
=> fix(ui5-menu-item): remove redundant screen reader  announcements

packages/fiori/src/themes/ShellBar.css
Avatar font-size was inheriting style for size "S", while it has hardcoded size, which is smaller than "S" and a little bit larger than "XS", so font-size for XS looks more suitable.
=> fix(ui5-shellbar): fixed avatar font-size var

packages/create-package/README.md, packages/create-package/create-package.js, packages/create-package/template/cypress/component/MyFirstComponent.cy.tsx, packages/create-package/template/env, packages/create-package/template/src/bundle.esm.ts, packages/create-package/template/test/pages/index.html, packages/tools/lib/create-new-component/index.js
- Move the bundle from the root folder to the `src` folder and update the test page to use Vite environment variables for resolving the bundle path.
- Remove the `componentName` and `tagName` options from both the CLI and the configuration wizard.
- Update the test specification file to use the correct tag for the initially created component, replacing the previously "hardcoded-button" tag with the component's actual tag.
- Ensure that all new components are generated with the `my-` prefix, maintaining consistent naming whether the component name is a single word or multiple words.
=> chore: improve generating new package and component scripts

packages/website/docs/_samples/main/Table/Growing/Growing.md, packages/website/docs/_samples/main/Table/Growing/sample.html
To align the API the `type` property of the `TableGrowing` component has been changed to `mode`.
This alignment has not been made in the playground, which is why the growing behaviour seems like it is "not working".
=> docs(ui5-table-growing): change type to mode

packages/tools/lib/css-processors/css-processor-components.mjs
The `.w-\[100px\]` selector is a valid CSS class. However, when processed by the tools package, it is incorrectly saved as `.w-[100px]`, making it an invalid selector.  
With this PR, when a backslash is encountered during processing inside a CSS file, it is properly escaped before being saved to the new file.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/11413
=> fix: escape backslash when processing component's css

packages/fiori/src/ShellBar.ts, packages/fiori/src/ShellBarItem.ts, packages/fiori/src/UploadCollectionItem.ts, packages/fiori/src/Wizard.ts, packages/main/cypress/specs/Card.cy.tsx, packages/main/cypress/specs/FormSupport.cy.tsx, packages/main/src/AvatarGroup.ts, packages/main/src/AvatarGroupTemplate.tsx, packages/main/src/Button.ts, packages/main/src/Carousel.ts, packages/main/src/ExpandableText.ts, packages/main/src/MultiComboBox.ts, packages/main/src/Panel.ts, packages/main/src/SplitButton.ts, packages/main/src/TableHeaderCellActionBase.ts, packages/main/src/TableRow.ts, packages/main/src/TableRowActionBase.ts, packages/main/src/Tokenizer.ts, packages/tools/lib/cem/custom-elements-manifest.config.mjs
Currently, the click event on the `ui5-button` is the native click event from the user interaction. This creates some problems. One main issue is that the click event cannot be prevented because the event handler in the template is always attached first. This means that the `isPrevented` flag is missing if the event is prevented during the bubble phase.
A bigger problem happens when the `ui5-button` has `type="Submit"` and is inside a HTML form element. In this case, each time the button is clicked, the form is submitted, even if the click event is prevented.
This pull request fixes the issue by changing the click event to a `CustomEvent`, instead of the native `Event`. In most cases, only `event.target` or `event.currentTarget` are used, and no other event details are usually needed. To …
=> feat(ui5-button): make click button preventable

packages/main/src/themes/CalendarLegendItem.css, packages/main/src/themes/base/CalendarLegendItem-parameters.css, packages/main/src/themes/sap_horizon/CalendarLegendItem-parameters.css, packages/main/src/themes/sap_horizon_dark/CalendarLegendItem-parameters.css
We have new design specification, about the representation of the Selected day default item of the `ui5-calendar-legend` component.
Now in SAP Horizon and SAP Horizon Dark themes, the Selected Day item of the `ui5-calendar-legend` has a dot in the middle, which makes its concept more clear.
=> fix(ui5-calendar-legend): align selected item representation to new VD spec

packages/fiori/cypress/specs/IllustratedMessage.cy.tsx, packages/fiori/src/IllustratedMessage.ts
The `decorative` property has been added to the `ui5-illustrated-message` component. 
The attributes `role="presentation"` and `aria-hidden="true"` are added to the SVG element when it is true.
=> feat(ui5-illustrated-message): decorative property added

packages/main/src/themes/Button.css, packages/main/src/themes/ButtonBadge.css, packages/main/src/themes/base/Button-parameters.css, packages/main/src/themes/sap_horizon/Button-parameters.css, packages/main/src/themes/sap_horizon_dark/Button-parameters.css
With this change we update the font-family parameters in the `<ui5-button>` component in order to be compliant with the VD Specifications.
**_Ref:_** _BGSOFUIBALKAN-9197_
=> fix(ui5-button): update parameters according to VD

packages/fiori/src/illustrations/sapIllus-Dialog-Survey.svg, packages/fiori/src/illustrations/sapIllus-Spot-Survey.svg
Replace inline style="mask-type:alpha" with standard SVG attribute mask-type="alpha" to avoid styling issues
Fixes:[#11354](https://github.com/SAP/ui5-webcomponents/issues/11354)
=> fix(ui5-illustrated-message): change SVG inline styling to proper attributes

packages/main/cypress/specs/Form.cy.tsx, packages/main/src/Form.ts, packages/main/src/FormGroup.ts, packages/main/src/FormTemplate.tsx, packages/main/src/i18n/messagebundle.properties
New APIs:
- introduce `headerLevel` API (similar to Panel and others) for customizing the aria-levels of Form and FormGroup headings according to the use-case with default values of 2 for the Form and 3 for the FormGroup.
- introduce `accessibleName` API to allow defining a unique accessible name of the Form, especially when used without a header or when multiple forms are used (as the aria-label should be unique and even if we set built-in one, the tools would complain that the role+accessible name combination isn't unique).
Minor visual change:
- update `font-size` of the FormGroup heading (from H5 to H6) to to match the latest design
Fixes: https://github.com/SAP/ui5-webcomponents/issues/11371
=> feat(ui5-form, ui5-form-group): add `headerLevel` property

packages/create-package/template/src/themes/sap_fiori_3/parameters-bundle.css, packages/create-package/template/test/pages/css/index.css, packages/create-package/template/test/pages/index.html, packages/tools/lib/create-new-component/index.js
Facelift new component dev landing page
=> chore: update new component development's landing page

packages/fiori/cypress/specs/SideNavigationWithGroups.cy.tsx, packages/fiori/src/SideNavigationGroup.ts, packages/fiori/test/pages/SideNavigation.html, packages/fiori/test/pages/SideNavigationWithGroups.html
=> fix(ui5-side-navigation): disabled groups no longer interactive

packages/fiori/src/themes/UploadCollectionItem.css
The width of the file name is the same as the text, and if the user clicks outside the text of the file name, the file-name-click event is not triggered.
fixes: #11463
=> fix(ui5-upload-collection): fix file name width

packages/fiori/cypress/specs/SideNavigation.cy.tsx, packages/fiori/src/SideNavigation.ts, packages/fiori/src/SideNavigationTemplate.tsx, packages/fiori/src/i18n/messagebundle.properties
The `SideNavigation` component now includes descriptive labels (`aria-label`) for both the primary and footer navigation sections.
JIRA: BGSOFUIRODOPI-3230
=> chore(ui5-side-navigation): add invisible texts for primary and footer list trees

docs/2-advanced/05-using-features.md, packages/base/src/UI5Element.ts, packages/main/cypress/specs/F6.cy.tsx
Currently, it's not possible to skip built-in fast navigation groups from the F6 navigation chain—for example, a `ui5-bar` component always participates by default.
With this PR, developers can bypass a specific fast navigation group by adding the attribute `data-sap-ui-fastnavgroup="false"` to the element that defines group. This prevents the first focusable element of the marked group from receiving focus during F6 navigation.
**Note:** This only affects the element where the attribute is set. Nested fast navigation groups inside it will still be included in the F6 chain unless they are also explicitly marked with `data-sap-ui-fastnavgroup="false"`.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/11452
=> feat(f6navigation): add option to bypass groups

packages/main/cypress/specs/List.cy.tsx, packages/main/src/List.ts
Fixes https://github.com/SAP/ui5-webcomponents/issues/11483
BGSOFUIRODOPI-3459
=> feat(ui5-list): focus() now focuses item

packages/base/src/features/F6Navigation.ts, packages/main/test/pages/F6Test8.html
If UI5 Web Components are used within the OpenUI5 framework and OpenUI5 is loaded first, we allow it to handle fast navigation.
With this change, fast navigation is delegated to OpenUI5 even when it is loaded after the Web Components are initialized.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/10462
=> fix(f6navigation): delegate fast navigation to openui5

packages/main/cypress/specs/Button.cy.tsx, packages/main/src/Button.ts, packages/main/src/i18n/messagebundle.properties
Issue:
- The badge wasn't announced at all when an `accessible-name` attribute is provided
for the `ui5-button`. The reason behind this behaviour is that the screen reader doesn't
read the inner text nodes of the root `button` node when the same has `aria-label` attribute.
Solution:
- The proper badge description text is placed into the `aria-label` attribute of the root
`button` element. As a result the screen reader won't rely on the inner text content
for the announcements.
- Additionally the `design` description is also moved into the `aria-label` attribute,
in order to keep a proper announcement order.
Fixes: #11350
=> fix(ui5-button): announce accessible name

packages/main/cypress/specs/TextArea.cy.tsx, packages/main/src/TextArea.ts, packages/main/src/themes/TextArea.css
=> fix(ui5-textarea): remove symbols encoding when growing

packages/main/src/Bar.ts, packages/main/src/BarTemplate.tsx, packages/main/src/types/BarAccessibleRole.ts, packages/main/test/pages/Bar.html, packages/website/docs/_components_pages/main/Bar.mdx, packages/website/docs/_samples/main/Bar/AccessibleRole/AccessibleRole.md, packages/website/docs/_samples/main/Bar/AccessibleRole/main.js, packages/website/docs/_samples/main/Bar/AccessibleRole/sample.html
Introduces a new `accessibleRole` property to the `ui5-bar` component, allowing developers to customize the ARIA role of the bar for accessibility purposes.
By default, the role is set to "toolbar", but now it can be explicitly changed by the application.
fixes: https://github.com/SAP/ui5-webcomponents/issues/10990
=> feat(ui5-bar): allow role change

packages/main/src/List.ts
Problem:
The list's onLoadMore event is not triggered in Firefox at certain zoom levels when a sticky header is present. This is due to how Firefox calculates intersections with sticky positioned elements, causing subpixel rendering issues.
Solution:
Use the proper scroll container as the root for the IntersectionObserver and add a rootMargin of 5px.
Similar to: #11242
Fixes: [#11461](https://github.com/SAP/ui5-webcomponents/issues/11461)
=> fix(ui5-list): adjust observer to handle sticky headers

packages/fiori/src/themes/NavigationMenuItem.css, packages/fiori/src/themes/SideNavigationGroup.css, packages/fiori/src/themes/SideNavigationItem.css, packages/fiori/src/themes/base/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_dark/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_hcb/SideNavigation-parameters.css, packages/fiori/src/themes/sap_horizon_hcw/SideNavigation-parameters.css
Problem: the 'sapFontSemiboldFamily' parameter did not result in a change in the font since font '72-Semibold' doesn't load.
Solution: replace it with 'sapFontSemiboldDuplexFamily'
Fixes: #11525
=> fix(ui5-side-navigation): change CSS param 'sapFontSemiboldFamily' to 'sapFontSemiboldDuplexFamily'

packages/main/src/themes/ListItem.css, packages/main/src/themes/ListItemCustom.css
This change addresses an issue with padding styles in the ListItemCustom component, ensuring consistent and accurate layout.
Fixes: #11480
=> fix(ui5-li-custom): correct padding for ListItemCustom

packages/fiori/src/themes/Timeline.css, packages/fiori/test/pages/Timeline.html
Previously, when a `ui5-timeline-item` was being focused, the focus outline was getting cut, due to a `overflow: auto` property in `Vertical` mode.
With this change we remove the `overflow` property, and the focus behaves as expected.
Fixes: #11386
=> fix(ui5-timeline-item): remove focus getting cut

packages/main/src/Tree.ts
Added missing JSDoc comments for the `move` and `move-over` events to the `ui5-tree` component, describing their purpose and parameters for drag-and-drop reordering functionality.
Fixes: #11199
=> docs(ui5-tree): add move and move-over event documentation

packages/main/cypress/specs/TableSelections.cy.tsx, packages/main/src/Table.ts, packages/main/src/TableRow.ts, packages/main/src/TableSelectionBase.ts, packages/main/src/TableSelectionMulti.ts, packages/main/src/types/TableSelectionBehavior.ts, packages/main/test/pages/Table.html, packages/website/docs/_samples/main/Table/SelectionMulti/main.js, packages/website/docs/_samples/main/Table/SelectionMulti/sample.html, packages/website/docs/_samples/main/Table/SelectionSingle/main.js, packages/website/docs/_samples/main/Table/SelectionSingle/sample.html
- RowSelector: In this default mode, rows can only be selected using the row selector column.
- RowOnly: Rows can only be selected by clicking directly on the row, as the row selector column is hidden.
Fixes: #10893
=> feat(ui5-table): behavior property added for selections

packages/fiori/cypress/specs/SearchField.cy.tsx, packages/fiori/src/SearchField.ts, packages/fiori/src/SearchFieldTemplate.tsx, packages/fiori/src/themes/SearchField.css, packages/fiori/src/themes/base/SearchField-parameters.css, packages/fiori/src/themes/sap_fiori_3/SearchField-parameters.css, packages/fiori/src/themes/sap_fiori_3_dark/SearchField-parameters.css, packages/fiori/src/themes/sap_fiori_3_hcb/SearchField-parameters.css, packages/fiori/src/themes/sap_fiori_3_hcw/SearchField-parameters.css, packages/fiori/src/themes/sap_horizon_hcb/SearchField-parameters.css, packages/fiori/src/themes/sap_horizon_hcw/SearchField-parameters.css, packages/fiori/test/pages/SearchField.html, packages/website/docs/_components_pages/fiori/Search/Search.mdx, packages/website/docs/_samples/fiori/Search/AdvancedFilter/AdvancedFilter.md, packages/website/docs/_samples/fiori/Search/AdvancedFilter/main.js, packages/website/docs/_samples/fiori/Search/AdvancedFilter/sample.html
=> feat(ui5-search-field): introduce advanced filtering

packages/main/src/Avatar.ts, packages/main/src/themes/Avatar.css, packages/main/src/themes/base/Avatar-parameters.css, packages/main/test/pages/Avatar.html, packages/main/test/pages/styles/Avatar.css
- Ensure the optional border is consistently applied whenever the avatar displays an image (e.g., a person).
- Update CSS and parameters to support the new border logic.
- Improve visual consistency for avatars with images across themes and test pages.
Fixes: #11437
=> fix(ui5-avatar): apply optional border for avatars with image

packages/main/src/CheckBoxTemplate.tsx, packages/main/src/themes/CheckBox.css
Previously the required asterisk was rendered next to the checkbox's text block.
Now it's at the end of the text line.
Fixes: #11547
=> fix(ui5-checkbox): fixed required asterisk alignment

packages/ai/.npmignore, packages/base/.npmignore, packages/compat/.npmignore, packages/fiori/.npmignore, packages/main/.npmignore
Exclude the Cypress folder from being published to the npm registry in each component package.
=> chore: exclude cypress test files from npm

packages/main/src/Avatar.ts, packages/main/src/Icon.ts
- Change event click decorator from private to public in Avatar component
- Change event click decorator from private to public in Icon component
Allows seamless integration to "wrap" the click events on interactive avatars and icons
=> feat(ui5-avatar, ui5-icon): make click events public

packages/main/src/themes/DatePicker.css
Removed a `min-width` style from the DatePicker input that was overriding the value defined in the VD specs.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/11561
=> fix(ui5-date-picker): align width to vd specs

packages/fiori/cypress/specs/ShellBar.cy.tsx, packages/fiori/src/ShellBarTemplate.tsx
Fixes: #11595
Shellbar without logo and primary title no longer renders an empty placeholder. This prevent an unnecessary tab stop while navigating.
=> fix(ui5-shellbar): remove empty logo from tab chain

packages/fiori/cypress/specs/FCL.cy.tsx, packages/fiori/src/FlexibleColumnLayout.ts, packages/fiori/src/FlexibleColumnLayoutTemplate.tsx
Problem:
Axe DevTools reports critical accessibility errors because focusable separator elements (role="separator" with tabindex="0") are missing the required aria-valuenow attribute.
Solution:
Added aria-valuenow attributes to start and end separators in the template, with new getter methods that derive position values from column widths (as percentages) to provide screen readers with position information.
Fixes: [#11533](https://github.com/SAP/ui5-webcomponents/issues/11533)
=> fix(ui5-flexible-column-layout): add aria-valuenow attribute to separators

packages/fiori/cypress/specs/SearchField.cy.tsx, packages/fiori/src/SearchField.ts, packages/fiori/src/SearchFieldTemplate.tsx, packages/fiori/src/themes/SearchField.css, packages/fiori/src/themes/base/SearchField-parameters.css, packages/fiori/src/themes/sap_fiori_3/SearchField-parameters.css, packages/fiori/src/themes/sap_fiori_3_dark/SearchField-parameters.css, packages/fiori/src/themes/sap_fiori_3_hcb/SearchField-parameters.css, packages/fiori/src/themes/sap_fiori_3_hcw/SearchField-parameters.css, packages/fiori/src/themes/sap_horizon_hcb/SearchField-parameters.css, packages/fiori/src/themes/sap_horizon_hcw/SearchField-parameters.css, packages/fiori/test/pages/SearchField.html, packages/website/docs/_components_pages/fiori/Search/Search.mdx, packages/website/docs/_samples/fiori/Search/AdvancedFilter/sample.html
Renamed advancedFilter slot to filterButton.
=> refactor(ui5-search-field): rename advancedFilter slot to filterButton

packages/main/src/themes/base/CheckBox-parameters.css
- Override `--_ui5_checkbox_label_offset` to use compact wrapper padding in compact mode. 
Fixes: [#11664](https://github.com/SAP/ui5-webcomponents/issues/11664)
=> fix(ui5-checkbox): correct spacing between checkbox and label in compact

packages/tools/lib/create-new-component/index.js
Update the prompt of the  `create-ui5-element` script
to suggest correct import statement of a new component.
=> chore: update the prompt of create-ui5-element script

packages/main/cypress/specs/Button.cy.tsx, packages/main/src/Button.ts, packages/main/src/ToggleButton.ts, packages/main/test/pages/Button.html
Native click behavior triggered by the `ui5-button` is not suppressed based on the custom event fired by the web component. Although the native `click` event does not propagate, its default behavior still occurs—even when the custom event is prevented.
With this PR, the native behavior is now correctly prevented when the custom event is prevented.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/11653
=> fix(ui5-button): prevents native behavior when click prevented

packages/main/cypress/specs/Avatar.cy.tsx, packages/main/src/Avatar.ts, packages/main/src/AvatarTemplate.tsx, packages/main/test/pages/AvatarFallback.html
This commit fixes image error handling in the Avatar component to ensure fallback content is displayed when images fail to load.
**Problem Fixed:**
- Avatar would show broken/empty content when image sources were invalid
- No automatic fallback when images failed to load dynamically
- Missing error detection for already-broken images at initialization
**Solution:**
- **Dynamic Image Error Detection**: Added real-time monitoring of image load states with automatic fallback switching
- **Reactive Error Handling**: Image failures now trigger immediate UI updates to show appropriate fallback content
- **Comprehensive Error Detection**: Handles both runtime failures and already-broken images via `complete` and `naturalWidth` checks
**Technical Implementation:**
- Added `_imageLoadError` …
=> fix(ui5-avatar): add dynamic image error handling with fallback logic

packages/fiori/src/themes/WizardTab.css
=> fix(ui5-wizard): define min-width for header steps separators

packages/create-package/create-package.js
Now, on package generation the process folder followed by package base name as suggested as folder. With this PR, it is corrected to the package base name.
=> chore: suggest correct folder on package creation

packages/main/cypress/specs/Menu.cy.tsx, packages/main/src/MenuItem.ts, packages/main/src/MenuItemGroup.ts, packages/main/src/MenuItemGroupTemplate.tsx, packages/main/test/pages/Menu.html
There were 2 events introduced in PR #10028 - private `item-check` event fired by `MenuItem` when its `checked` property changes, and public `check-change` event fired by `MenuItemGroup` when any of its `MenuItem` components changes it's `checked` property.
This PR removes these two events in favor of single public `check` event, fired by the `MenuItem` when its `checked` property changes. The new situation will be more suitable for handling `MenuItem` `checked` states and updating models in applications that use Menu Item Groups.
=> Add MenuItem 'check' public event and remove MenuItemGroup 'check-change' event

packages/fiori/src/ViewSettingsDialog.ts
Change announce type for the screen reader when view settings are reset.
=> fix(ui5-view-settings-dialog): change announce type for the screen reader when view settings are reset

packages/main/cypress/specs/DatePicker.cy.tsx, packages/main/src/DatePicker.ts, packages/main/src/DateRangePicker.ts, packages/main/src/TimePicker.ts, packages/main/src/i18n/messagebundle.properties
Previously, when no `placeholder` was provided in our Date/Time components, the default placeholder simply displayed the `formatPattern` string (e.g., `MMM d, y`, `dd/MM/yyyy - dd/MM/yyyy`).
With this change, if no `placeholder` is set, the default placeholder now displays a translatable example value in the correct `formatPattern`/`displayFormat`— using the last value of the relevant period (such as the last day of the year, last hour of the day, etc.).
Examples:
`e.g. 23:59:59`
`e.g. Dec 31, 2025`
Fixes: #11749
=> feat(ui5-date/time*): introduce translatable fallback placeholder

packages/main/src/themes/sap_horizon/Avatar-parameters.css, packages/main/src/themes/sap_horizon_dark/Avatar-parameters.css, packages/main/src/themes/sap_horizon_hcb/Avatar-parameters.css, packages/main/src/themes/sap_horizon_hcw/Avatar-parameters.css
Remove `--ui5-avatar-placeholder` and `--ui5-avatar-placeholder-color` variables from horizon theme variants as they duplicate the base theme values.
The base Avatar-parameters.css already defines these variables correctly using 
- `--sapContent_ImagePlaceholderBackground`
- `--sapContent_ImagePlaceholderForegroundColor` 
as per design specification.
Fixes: #11750
=> fix(ui5-avatar): remove redundant placeholder variables from horizon themes

packages/main/src/List.ts, packages/main/src/ListItemBase.ts
- Add duck-typing check in onItemToggle using isListItemBase getter
- Prevents unwanted toggle events from nested components like panels
Fixes #11812
=> fix(ui5-list): prevent toggle event bubbling from non-list items

packages/main/src/RangeSlider.ts, packages/main/src/Slider.ts, packages/main/src/SliderBase.ts, packages/main/src/SliderBaseTemplate.tsx, packages/main/src/themes/SliderBase.css, packages/main/test/pages/Slider.html
=> fix(ui5-slider): improve labels structure and placement

packages/main/cypress/specs/MultiComboBox.cy.tsx, packages/main/cypress/specs/Tokenizer.cy.tsx, packages/main/src/Tokenizer.ts, packages/main/src/TokenizerPopoverTemplate.tsx
- The token's text now is bound to the text property of the `ListItemStandard` element and not rendered as its default slot, because after  #11108 dynamic updates in it doesn't get reflected (do not cause re-rendering of the list item).
Note: The problem in the ListItemStandard occurs only with `wrappingType` set to `Normal` because it uses the` ui5-expandable-text` component. That component has its own `text `property which is getting updated when the `text `property of the `ListItemStandart `is updated, but not when its slot is.
- Add `invalidateOnChildChange `config to tokens slot to watch for text property changes to ensure popover list items automatically update when token text is modified
fixes: #11825
=> fix(ui5-tokenizer): sync popover list items with token text changes

packages/website/build-scripts/local-cdn.mjs
There is an issue with `readdir` method of `fs/promises` which is used to get the path and name of files to delete in `local-can.mjs`.
**Node 21** introduced `parentPath` property, having the same value as `path`.
In **Node 23** `path` was deprecated  in favour of `parentPath`.
In **Node 24** `path` is completely removed.
The fix allows `yarn start:website` script to work with all **Node versions from 20 to 24** by using either `path` or `parentPath`, whichever is available.
Fixes issue: https://github.com/SAP/ui5-webcomponents/issues/11878
=> fix(framework): make "yarn start:website" script work with both node 20 and 24

packages/fiori/src/DynamicPage.ts, packages/fiori/src/DynamicPageTemplate.tsx, packages/fiori/test/specs/DynamicPage.spec.js
Removes non-compliant aria-expanded attribute from DynamicPage header element to conform with W3C ARIA specifications.
Fixes #11633
=> fix(ui5-dynamic-page): remove aria-expanded from header element

packages/main/src/ListItemStandard.ts
The default slot documentation was moved from the class-level JSDoc comments to the actual slot property declaration for better clarity and consistency.
This change improves documentation structure while maintaining the same functional behavior - the slot is still defined with `type: Node` and `"default": true`, which ensures that text content changes will properly trigger component invalidation as expected for Node-type slots.
Relates to #11825
=> fix(ui5-li): move default slot documentation from class to property level

packages/fiori/src/SideNavigationItem.ts, packages/fiori/src/themes/SideNavigationItem.css, packages/fiori/src/themes/SideNavigationItemBase.css, packages/fiori/test/pages/SideNavigationWithGroups.html
Issue: When the text spans the full length of the item, for example, when it is truncated, there was no padding at the end.
Solution: Added padding at the end of the text.
fixes: #11828
=> fix(ui5-side-navigation): add padding at the end of the text

packages/main/src/SplitButtonTemplate.tsx
Issue:
- The invisible label containing the accessible role and other screen reader announcements
is not properly linked to the focusable button element.
Fixes: #11893
=> fix(ui5-split-button): adjust labelledby reference

packages/main/src/NavigationMenu.ts
Previously, when hovering over the "arrow right" icon inside a navigation item, the mouseover event incorrectly targeted the icon itself, not the parent navigation item.
The code now detects if the hovered element is a ui5-icon (like the "arrow right").
If so, it adjusts the reference to the parent navigation item. This ensures the responsive popover is opened and positioned relative to the correct parent navigation item, even when the hover occurs on the "arrow right" icon.
fixes: #11121
=> fix(ui5-side-navigation): ensure correct popover position when hovering the "arrow right" icon on subitems

packages/main/src/themes/Button.css
The `z-index` property of the slotted `ui5-button-badge` inside of the `ui5-button` is set to **1000** - this value is very high and it happens that badge can appear over other elements that appear on higher `z-index` (as dialogs, etc.).
This PR sets the `z-index` to **1**, which is more secure options and doesn't destroy current badge appearance.
=> fix(ui5-button): adjust button badge z-index

packages/fiori/src/themes/IllustratedMessage.css
Remove explicit line-height values from all media query variants (spot, dot, base) and base styles as they were causing text clipping issues and are not specified in the design specifications.
Fixes #11851
=> fix(ui5-illustrated-message): remove unnecessary line-height overrides

packages/main/src/Table.ts, packages/main/src/TableSelection.ts, packages/main/src/TableSelectionMulti.ts
Capturing events should be specific to the components, therefore moved capture phase into the selection components.
This also prevents the row action from firing the row-click event as well, which was an unwanted side effect from the previous change
Fixes #11509
Fixes #11932
=> fix(ui5-table): register capture individually for selection

packages/main/src/List.ts, packages/main/src/ListItemGroup.ts, packages/main/src/Tree.ts, packages/main/src/delegate/DragAndDropHandler.ts
- Create reusable DragAndDropHandler delegate class
- Refactor List, Tree, and ListItemGroup to use shared handler
- Remove duplicated drag and drop logic across components
- Improve maintainability and consistency of drag/drop behavior
- Support configurable drag validation and placement filtering
This consolidates ~200 lines of duplicated code into a single, configurable handler that can be reused across all drag-enabled components.
Fixes: #11120
=> refactor(ui5-list, ui5-tree, ui5-list-item-group): extract drag-and-drop logic

packages/main/cypress/specs/Button.cy.tsx, packages/main/src/Button.ts
Issue:
- The inner text of the button wasn't announced when the design property was set.
Solution:
- The inner text is now part of the aria-label attribute alongside the design type text.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/12037
=> fix(ui5-button): announce the text node properly

packages/fiori/src/themes/ShellBar.css, packages/fiori/src/themes/base/ShellBar-parameters.css
- Added new CSS custom property `--_ui5-shellbar_cancel-button-color` in parameters file with value `sapButton_Lite_TextColor` to follow tertiary button styling
- Applied the custom property to `.ui5-shellbar-cancel-button` class for default and hover states
Fixes #11957
=> fix(ui5-shellbar): apply tertiary button color to cancel button

packages/fiori/src/SearchFieldTemplate.tsx
- Separtor is now shown only when filter exists.
FIXES: [#12095](https://github.com/SAP/ui5-webcomponents/issues/12095)
=> fix(ui5-search-field): show separator only when needed

packages/website/docs/components/patterns/UXC Integration.mdx
Add description and key features documentation to help developers understand UXC compliance standards.
JIRA: BGSOFUIPIRIN-6897
=> docs(uxc-integration): add overview description

packages/fiori/cypress/specs/FCL.cy.tsx
Fixes test by setting AnimationMode.Full before component mount instead of after. Eliminates race condition where animation classes weren't applied in time on slower CI environments. Also the rerender is now done with layout change.
=> test(flexible-column-layout): fix test

packages/main/cypress/specs/Select.cy.tsx, packages/main/src/Select.ts, packages/main/src/SelectTemplate.tsx, packages/main/test/pages/Select.html
- Add `accessibleDescription` property for providing descriptive text
- Add `accessibleDescriptionRef` property for referencing external description elements
- Update `aria-describedby` to include both value state and accessible descriptions
- Add comprehensive Cypress tests covering:
* Basic `accessibleDescription` functionality
* `accessibleDescriptionRef` with single and multiple element references
* Dynamic updates when referenced elements change
* Interaction with existing `valueState` descriptions
- Add test page examples demonstrating various usage scenarios
- Ensure proper accessibility attribute handling and ARIA compliance
Related: #12004 
JIRA: BGSOFUIPIRIN-6901
=> feat(ui5-select): add accessibleDescription and accessibleDescriptionRef

packages/main/src/Calendar.ts, packages/main/src/CalendarHeaderTemplate.tsx, packages/main/src/CalendarTemplate.tsx, packages/main/src/YearRangePickerTemplate.tsx, packages/main/test/pages/Calendar.html
Previously there was no possible way of overstyling the header navigation buttons and the year range picker root container of the `ui5-calendar` web component.
With this change we are introducing CSS Shadow Parts, which allows overstyling of those calendar parts.
```css
ui5-calendar::part(calendar-header-arrow-button) {
background: var(--sapButton_Background, #ffffff);
color: var(--sapButton_TextColor, #0070f2);
border: 1px solid var(--sapButton_BorderColor, #0070f2);
border-radius: 4px;
box-shadow: 0 1px 3px rgba(0, 0, 0, 0.12);
}
ui5-calendar::part(year-range-picker-root) {
padding: 16px 20px;
background: var(--sapObjectHeader_Background, #ffffff);
border: 1px solid var(--sapList_BorderColor, #e5e5e5);
border-radius: 6px;
box-shadow: 0 2px 8px rgba(0, 0, 0, 0.08);
}
```
Fixes: #12090
=> feat(ui5-calendar): expose shadow parts for YearRangePicker and CalendarHeader arrows

packages/base/src/theming/applyTheme.ts, packages/tools/lib/css-processors/shared.mjs, packages/tools/lib/generate-json-imports/i18n.js, packages/tools/lib/generate-json-imports/themes.js
**Problem**: tooling modules mistakes string constants for imports.
**Temporary solution:** until tooling modules is patched, do not use string constants for package names
Output:
```js
// Component CSS
registerThemePropertiesLoader("@" + "ui5" + "/" + "webcomponents-theming", "sap_horizon", async () => defaultThemeBase);
registerThemePropertiesLoader("@" + "u" + "i" + "5" + "/" + "w" + "e" + "b" + "c" + "o" + "m" + "p" + "o" + "n" + "e" + "n" + "t" + "s", "sap_horizon", async () => defaultTheme);
// Themes
["sap_fiori_3", "sap_fiori_3_dark", "sap_fiori_3_hcb", "sap_fiori_3_hcw", "sap_horizon", "sap_horizon_dark", "sap_horizon_hcb", "sap_horizon_hcw"]
.forEach(themeName => registerThemePropertiesLoader("@" + "u" + "i" + "5" + "/" + "w" + "e" + "b" + "c" + "o" + "m" + "p" + "o" + "n" + "e" …
```
=> chore: change theming base constant so it is not mistaken for import

packages/fiori/src/DynamicPageTitle.ts, packages/fiori/src/DynamicPageTitleTemplate.tsx
Only apply button role and ARIA attributes when the title can actually toggle the header. When no header is present (non-interactive state), the title area should not have button semantics or related ARIA attributes.
- Remove `button` role when title is not interactive
- Remove `aria-expanded` when title is not interactive
- Remove `aria-describedby` when title is not interactive
This ensures screen readers don't announce toggle functionality when no header exists to toggle.
Fixes: #12053
=> fix(ui5-dynamic-page-title): conditionally apply ARIA attributes based on interactivity

packages/fiori/src/ShellBarSearch.ts, packages/fiori/src/themes/ShellBarSearch.css
ShellBarSearch used to be overflowing the ShellBar when displayed on really small desktop screens (320px)
=> fix(ui5-shellbar-search): correct min-width

packages/main/cypress/specs/ComboBox.cy.tsx, packages/main/src/ComboBoxPopoverTemplate.tsx
Fixes: #12150 
- Fixes whitespace issue in ComboBox with value state but no suggestion items
=> fix(ui5-combobox): prevent whitespace below value state when no items are present

packages/main/cypress/specs/Input.cy.tsx, packages/main/src/Input.ts
Fixes - #12179 
- Previously, clicking a suggestion after fully typing the same text did not fire change; now both mouse and keyboard selection paths are consistent
- clicking a suggestion now emits a change event in addition to the existing selection-change
=> fix(ui5-input): emit change when suggestion is clicked

packages/main/src/themes/SegmentedButton.css
There was missing CSS selector for background of `hover` + `active` state of the non-selected `ui5-segmented-button-item` component.
This PR introduces it and now the mentioned color is as defined in the visual specification.
**JIRA: BGSOFUIBALKAN-9029**, case 5
=> fix(ui5-segmented-button): fix hover+active segmented button item background

packages/fiori/cypress/specs/ShellBar.cy.tsx, packages/fiori/src/ShellBar.ts
The cancel button now clears the search field value by default. Previously, the search field value was preserved. To maintain the previous behavior, listen for the `search-field-clear` event and call `preventDefault()`.
- Add `search-field-clear` event with `preventDefault` support
- Change default behavior to clear search field value on cancel
- Separate clearing behavior from closing behavior
- Add comprehensive test coverage for both scenarios
Jira: BGSOFUIPIRIN-6909
=> feat(ui5-shellbar): add preventable search field clear event

packages/tools/components-package/nps.js
The test pages like don't open after migrating from SAP to UI5 org
https://ui5.github.io/webcomponents/nightly/packages/main/test/pages/Select.html
because of the renaming of the project name from ui5-webcomponents to webcomponents.
=> docs: fix assets paths of test pages

packages/base/src/features/F6Navigation.ts, packages/main/cypress/specs/F6.cy.tsx, packages/main/test/pages/F6Test9.html
Previously, only the first parent was checked when determining the next focusable group during backward navigation. With this PR, all parent groups are traversed until a different element is found.
Fixes: https://github.com/UI5/webcomponents/issues/12268
=> fix(f6navigation): backward navigation in N level nesting

packages/main/cypress/specs/Toolbar.cy.tsx
Async tests reworked to sync
click interactions replaced with realClick
=> fix(ui5-toolbar): fix async toolbar tests

packages/tools/bin/dev.js
Remove the usage of `npx`. When the `ui5nps` bin is not found, `npx` attempts to fetch it from the npm registry, which leads to an error. If running the scripts still results in a missing `ui5nps` bin, the dependencies need to be reinstalled. This can be done by removing `node_modules` and installing everything again, since Yarn does not automatically re-link new binaries unless the installation is refreshed.
=> chore: remove npx from wc-dev

packages/fiori/cypress/specs/ShellBarItem.cy.tsx, packages/fiori/src/ShellBar.ts, packages/fiori/src/ShellBarPopoverTemplate.tsx, packages/fiori/src/ShellBarTemplate.tsx
Improves `ShellBarItem` focus handling when moving between the ShellBar's main area and overflow popover.
**Changes**
- Switched _getRealDomRef to use shadowRoot for accurate queries.
- Applied data-ui5-stable only to visible items and overflow popover entries for reliable DOM targeting.
- Added Cypress tests to verify getFocusDomRef() in both contexts.
=> fix(ui5-shellbar-item): correct getFocusDomRef return value

packages/main/src/Tokenizer.ts
Update the documentation to allow the usage of the popoverMinWidth property in the FileUploader component. 
FIXES: #11856
=> docs(ui5-tokenizer): updated documentation of popoverMinWidth
