UI5/webcomponents

packages/main/src/themes/base/CheckBox.less

The cursor over the ui5-checkbox text
is changed from type text to default in order to full-fill the visual design.

fix(ui5-checkbox): cursor over text

---

packages/base/src/sap/ui/webcomponents/base/DOMEventHandler.js
packages/base/src/sap/ui/webcomponents/base/WebComponent.js

fix(eventing): remove unnecessary tag name check

---

packages/main/test/sap/ui/webcomponents/main/samples/Input.sample.html

Issue
One of the ui5-label components within the "Input with Labels" section
used to reference a wrong ui5-input through its 'for' attribute.
Solution
Changing the ui5-label 'for' attribute to point the expected ui5-input field.
Fixes https://github.com/SAP/ui5-webcomponents/issues/28

fix(ui5-input): playground sample with labels

---

packages/main/test/sap/ui/webcomponents/main/samples/Popover.sample.html

Improve the accessibility inside the ui5-popover by
referencing the 'email' ui5-input with the 'Email' label
with the use of the 'for' attribute.

docs(playground): improve the ACC of the popover sample

---

packages/playground/webapp/index.html

Remove unnecessary attribute "popover-horizontal-align" both from the code section 
and the ui5-datepicker itself.

docs(playground): update DatePicker code snippet in home page

---

packages/base/src/sap/ui/webcomponents/base/ControlRenderer.js
packages/base/src/sap/ui/webcomponents/base/Core.js
packages/base/src/sap/ui/webcomponents/base/WebComponent.js
packages/base/src/sap/ui/webcomponents/base/compatibility/ShadowDOM.js
packages/main/src/themes/base/Button.less
packages/main/src/themes/base/Icon.less
packages/main/src/themes/base/Label.less
packages/main/src/themes/base/Link.less

fix: do not modify the HTML tag

---

packages/playground/webapp/css/style.css

Update styling of the 'apply' button within the configuration panel.
from:
to:
Change:
Removing the 'sapMBtnHoverable' clas, as on phone the components do not have hover and the class is never added.

docs(playground): fix configuration button appearance on phone

---

packages/main/src/themes/base/DatePicker.less

The correct selector, defining the icon`s color,
was not used to be applied.

fix(ui5-datepicker): icon color in pressed state

---

packages/base/src/sap/ui/webcomponents/base/events/PolymerGestures.js

gestures depends on the polyfills loaded before it runs.

fix: broken bundle on Edge

---

packages/playground/webapp/css/style.css
packages/playground/webapp/view/Main.view.xml

There is no overflow menu any more. The configuration button is always present
and opens the configuration panel.
On small sizes the version label goes inside the configuration panel.
After
Before

docs(playground): improve configuration openning on small sizes

---

packages/main/test/sap/ui/webcomponents/main/samples/Card.sample.html

Make use of ui5-list and the standard ui5-li only to accomplish the following sample:
and gather up other cards in one section

docs(playground): add new card sample with ui5-list

---

packages/main/test/sap/ui/webcomponents/main/samples/Card.sample.html

docs(playground): fix status labels in card with table sample

---

packages/main/src/themes/base/ListItem.less

Height of list item with both title and description should be 5rem in both Cozy and Compact.

fix(ui5-li): height with title and description in Compact

---

packages/base/src/sap/ui/webcomponents/base/compatibility/ShadowDOM.js
packages/base/src/sap/ui/webcomponents/base/theming/ThemeBundle.js
packages/main/lib/less-to-json-imports/index.js
packages/main/rollup.config.js

- generate a -css.js file for each imported .less file
- this file exports the generated CSS as a string value
- rewrite the imports from .less to -css.js
- more compatible for build tools as these files are supposed to be
inlined anyway and no longer force a json configuration at build time
which makes it easier for less capable build tools.

improvement: inline theme imports

---

packages/main/src/Tab.js
packages/main/src/TabContainer.hbs
packages/main/src/TabContainer.js
packages/main/test/sap/ui/webcomponents/main/pages/TabContainer.html
packages/main/test/sap/ui/webcomponents/main/qunit/TabContainer.qunit.js
packages/main/test/sap/ui/webcomponents/main/samples/TabContainer.sample.html
packages/main/test/specs/TabContainer.spec.js

The following changes are applied:
* remove the selectedKey property
* remove the key property
* introduce selectedIndex to substitute selectedKey and key pair for selection purposes
* change itemSelect event param to provide the selected item, instead of
the tab container internal key to make app development easier.
Furthermore, in React, the key is reserved for the purpose of VDOM optimisations.
* start firing itemSelect when item is selected from the overflow menu as well.
* add simple interaction test
BREAKING CHANGE: The TabContainer selected-key and Tab key properties are removed.

refactor(ui5-tabcontainer): item selection and itemSelect event

---

packages/base/src/sap/ui/webcomponents/base/WebComponent.js

fix: unknown slots no longer cause an error

---

packages/main/test/sap/ui/webcomponents/main/pages/DatePicker_test_page.html
packages/main/test/specs/DatePicker.spec.js

It seems that WDIO is not waiting for a test to finish if the last
command is a click. In such cases, it was already starting the next test
causing the click async callback to hang and the test to timeout.

test: fix unstable test

---

packages/main/src/TabContainer.js
packages/main/test/sap/ui/webcomponents/main/pages/TabContainer.html
packages/main/test/specs/TabContainer.spec.js

Fixes: https://github.com/SAP/ui5-webcomponents/issues/94

fix(ui5-tabcontainer): left arrow correctly scrolls to left in textOnly

---

packages/main/rollup.config.js

url-search-params-polyfill causes rollup to report an error although it still works.

build: suppress rollup error

---

packages/base/src/sap/ui/webcomponents/base/WebComponent.js

Certain child should inform their parents for property change and make the parent invalidate.
This is done through a listenFor in the metadata. However, when two such components are used inside each other, the metadata for the inner one was get for the first time incorrectly (prop.target was wrong).
* Now the correct element is used (this)
* Early return is performed if for some reason the listenFor is empty (not needed for the fix)
This fixes the ui5-table inside a ui5-tabcontainer

fix: prevent throwing exception if slotted child does not have listenFor

---

lib/documentation/templates/api-properties-section.js
packages/main/src/StandardListItem.js
packages/main/test/playground/css/api.css

docs: display since info for properties

---

lib/documentation/index.js
lib/documentation/templates/api-component-since.js
packages/main/src/Select.js
packages/main/src/ShellBar.js
packages/main/src/Switch.js
packages/main/src/Timeline.js
packages/main/test/playground/css/api.css
packages/main/test/sap/ui/webcomponents/main/samples/Select.sample.html
packages/main/test/sap/ui/webcomponents/main/samples/ShellBar.sample.html
packages/main/test/sap/ui/webcomponents/main/samples/Switch.sample.html
packages/main/test/sap/ui/webcomponents/main/samples/Timeline.sample.html

On small devices the "next release" label hides, instead of wrapping together with the since version.

docs: enable component since info

---

packages/main/src/CheckBox.js
packages/main/src/CheckBoxTemplateContext.js
packages/main/src/ListItem.hbs
packages/main/src/RadioButton.js
packages/main/src/RadioButtonTemplateContext.js
packages/main/test/sap/ui/webcomponents/main/pages/List_test_page.html
packages/main/test/specs/List.spec.js

This commits reverts: a30577ee8ab3fe978a520c9d42380a1c668e0462
It introduced an issue that ui5-checkbox and ui5-radiobutton
have two tab stops.
Another change will come after this one to implemented the
keyboard handling improvement for the ui5-list

revert: ui5-list keyboard handling improvement

---

packages/main/test/sap/ui/webcomponents/main/samples/Link.sample.html

There is a typo in the link documentation: ```Standart Link```
https://sap.github.io/ui5-webcomponents/playground.html#/components/Link

Typo: Standard Link

---

packages/main/src/Switch.js
packages/main/src/SwitchTemplateContext.js
packages/main/src/types/SwitchType.js

The displayed default value for the property "type"
is changed from Standard to Textual as the real type options are.

refactor: make SwitchType enum keys compliant with the type values

---

packages/main/src/themes/base/Icon.less
packages/main/src/themes/base/TableCell.less
packages/main/src/themes/base/TextArea.less
packages/main/test/sap/ui/webcomponents/main/samples/Table.sample.html

Fixes Icon colour, TextArea exceeded text and Table sample in HCB.
Before:
After:
Before:
After:
Before:
After:

fix: fix HCB colours for Icon, TextArea and Table sample

---

packages/main/src/themes/base/Link.less
packages/main/src/themes/sap_belize/Link.less
packages/main/src/themes/sap_belize_hcb/Link.less
packages/main/src/themes/sap_fiori_3/Link.less

Remove style nesting and move all the selectors in the base file
an overwrite local variables, where needed, to make the path to css variables smoother.

refactor(ui5-link): keep all CSS selectors in the Base Less file only

---

packages/core/overlay/sap/ui/Device.js

System detection (phone) depends on platform and touch support,
both not calculated, causing a JS error within the Device module.

fix: correct system detection error on mobile

---

packages/main/src/themes/base/CheckBox.less
packages/main/src/themes/base/Popover.less
packages/main/src/themes/sap_belize_hcb/CheckBox.less
packages/main/src/themes/sap_fiori_3/CheckBox.less
packages/main/test/sap/ui/webcomponents/main/samples/CheckBox.sample.html

Introduce local variables per theme and move all the selectors in the base less.
Add more checkbox examples in the playground sample. And, In addition provide small improvement in the Popover.less, removing the "sap-ios" dependant css without side effect in the rest of the browsers.

refactor(ui5-checkbox): keep styles in base LESS only

---

packages/core/overlay/sap/ui/Device.js

Call the _setBrowser method, that exist, instead of previously available setBrowser.

fix: stop calling non-existing method

---

packages/main/src/DatePicker.hbs
packages/main/src/Input.hbs
packages/main/src/Input.js
packages/main/test/sap/ui/webcomponents/main/pages/Input.html
packages/main/test/sap/ui/webcomponents/main/pages/Select.html
packages/main/test/sap/ui/webcomponents/main/pages/kitchen-scripts.js
packages/main/test/sap/ui/webcomponents/main/samples/Input.sample.html
packages/main/test/specs/Input.spec.js

Fire 'input' event upon user typing and stop firing liveChange.
BREAKING CHANGE: liveChange event is no longer fired, listen for the input event instead.

refactor(ui5-input): fire input, instead of liveChange

---

packages/base/src/sap/ui/webcomponents/base/Bootstrap.js
packages/base/src/sap/ui/webcomponents/base/Configuration.js
packages/base/src/sap/ui/webcomponents/base/FormatSettings.js
packages/base/src/sap/ui/webcomponents/base/LocaleDataConfigurationProvider.js
packages/base/src/sap/ui/webcomponents/base/LocaleProvider.js
packages/base/src/sap/ui/webcomponents/base/ResourceBundle.js
packages/base/src/sap/ui/webcomponents/base/ResourceLoaderOverrides.js
packages/base/src/sap/ui/webcomponents/base/dates/CalendarUtils.js
packages/base/src/sap/ui/webcomponents/base/shims/Core-shim.js
packages/base/src/sap/ui/webcomponents/base/shims/jquery-shim.js
packages/core/overlay/sap/ui/core/LocaleData.js
packages/core/overlay/sap/ui/core/date/Islamic.js
packages/core/overlay/sap/ui/core/date/UniversalDate.js
packages/core/overlay/sap/ui/core/format/DateFormat.js
packages/main/src/Calendar.js
packages/main/src/DatePicker.js
packages/main/src/DayPicker.js
packages/main/src/MonthPicker.js
packages/main/src/TimelineItem.js
packages/main/src/YearPicker.js
packages/main/test/sap/ui/webcomponents/main/pages/DatePicker.html
packages/main/test/sap/ui/webcomponents/main/samples/DatePicker.sample.html

- configuration is now set only from url or JSON script
- locale is required for all controls that need it, not on central level as it used to be
- new module LocaleProvider is added - it returns the locale from the configuration or locale based on browser
- all compatibility core-shim and jQuery levels are moved to Calendar and DatePicker
- bundle size for a single CheckBox reduced to ~ 15kb

refactor: modularize configuration and locales

---

packages/main/src/Input.hbs
packages/main/src/Input.js
packages/main/test/sap/ui/webcomponents/main/pages/DatePicker_test_page.html
packages/main/test/sap/ui/webcomponents/main/pages/Input.html
packages/main/test/sap/ui/webcomponents/main/qunit/Input.qunit.js
packages/main/test/specs/DatePicker.spec.js
packages/main/test/specs/Input.spec.js

Bind to the native input "change" event and fire the ui5-input semantic one.
Manually fire "change", when suggestion item is selected.
Fixes: #154

fix(ui5-input): fire change in sync with the native input

---

packages/main/src/ListItemBase.js

After the refactoring of the Pseudo events onsaptabprevious stopped working.
It`s now replaced by _handleTabPrevious.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/192

fix(ui5-list): correct backward navigation with SHIFT+TAB

---

packages/main/src/CheckBoxTemplateContext.js

Set aria-readonly, when readOnly property is set (previously checking for the disabled property, which is not correct).

fix(ui5-checkbox): correct setting of aria-readonly

---

packages/main/src/Panel.js
packages/main/test/sap/ui/webcomponents/main/pages/Panel.html
packages/main/test/specs/Panel.spec.js

Fire toggle event on expand/collapse instead of expand.
BREAKING CHANGE: the expand event is removed, use the toggle event instead.

refactor(ui5-panel): rename the expand event to toggle

---

packages/main/src/SwitchTemplateContext.js
packages/main/src/themes/base/Switch.less

- root class renamed from `ui5-switch` to `ui5-switch-wrapper`
- `shadycss` is placing the tag name as a class to all shadow dom children of a Custom Element which is causing some layouting problems when such a class has already some styling applied for the component

fix(ui5-switch): fix layouting on IE

---

packages/main/src/Card.hbs
packages/main/src/Card.js
packages/main/src/themes/base/Card.less
packages/main/src/themes/sap_belize_hcb/Card.less
packages/main/test/sap/ui/webcomponents/main/pages/Card.html
packages/main/test/specs/Card.spec.js

headerPress is now fired on header click or via Enter and Space keys.
Focus and active states are implemented upon those actions.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/243

feat(ui5-card): fires headerPress event upon header click

---

packages/base/src/ResourceBundle.js

Fixes: https://github.com/SAP/ui5-webcomponents/issues/237

fix: add missing dependency to jquery-shim in resource bundle

---

packages/main/src/ShellBar.js
packages/main/test/sap/ui/webcomponents/main/pages/ShellBar.html
packages/main/test/sap/ui/webcomponents/main/samples/ShellBar.sample.html

BREAKING CHANGE: press handlers used to have param "iconRef". As not always
an Icon is pressed (e.g. title is not an icon) - the parameter is renamed to targetRef.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/297

refactor(ui5-shellbar): rename press handlers param

---

packages/main/src/Card.hbs
packages/main/src/Card.js
packages/main/src/themes-next/Card.css
packages/main/test/sap/ui/webcomponents/main/pages/Kitchen.html

* Issue: Both the card root element and its header provides border, but in case no content is added, bottom border gets doubled.
* Solution: Remove the header bottom border, if no content is set.

 fix(ui5-card): remove header double border if no content

---

packages/main/src/ShellBar.hbs
packages/main/src/ShellBar.js
packages/main/src/ShellBarTemplateContext.js
packages/main/src/themes-next/ShellBar.css
packages/main/test/sap/ui/webcomponents/main/pages/ShellBar.html
packages/main/test/sap/ui/webcomponents/main/samples/ShellBar.sample.html
packages/main/test/specs/ShellBar.spec.js

- menuItems renders list items in a popover which is might be open by clicking the primary title
- menuItemPress is fired when a menu item is pressed
- if no menu items are defined - no arrow down is rendered next to the primary title
BREAKING CHANGE: titlePress event is removed and replaced by menuItems slot.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/290

feat(ui5-shellbar): menuItems slot and menuItemPress event

---

packages/main/src/themes-next/CustomListItem.css
packages/main/test/sap/ui/webcomponents/main/pages/Kitchen.html

Provide min-height and height: auto to the custom list item,  so the consumers can set a custom height to their content.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/310

fix(ui5-li-custom): enable setting height of the custom content

---

lib/documentation/templates/api-events-section.js

chore: display API Events since info

---

packages/main/src/TimelineItem.hbs
packages/main/src/TimelineItem.js
packages/main/src/TimelineItemTemplateContext.js
packages/main/src/themes-next/TimelineItem.css
packages/main/src/themes/base/TimelineItem.less
packages/main/test/sap/ui/webcomponents/main/pages/Timeline.html
packages/main/test/sap/ui/webcomponents/main/samples/Timeline.sample.html

Closes: https://github.com/SAP/ui5-webcomponents/issues/299
BREAKING CHANGE: 'timestamp' and 'timeFormat'  properties are removed.
Instead use subtitle-text property and directly format the text as
desired.

refactor(ui5-timeline): change timestamp property to subtitleText

---

packages/main/src/themes-next/ToggleButton.css

* remove the text shadow in pressed state
* correct the background colour for the negative and positive toggle buttons
* image of the issue (positive and negative button should be green/red):

 fix(ui5-togglebutton): correct negative/positive stylings

---

packages/main/src/themes-next/ToggleButton.css

* The hover colour and the text colour of the default toggle button in pressed state used to be wrong

fix(ui5-togglebutton): correct default btn hover bg and text color

---

packages/main/src/Button.js
packages/main/src/ToggleButton.js
packages/main/src/ToggleButtonTemplateContext.js
packages/main/src/themes-next/Button.css

- The activate state of the buttons used to be displayed and controlled by the :active CSS selector. Seems like :active has some issues on different browsers and it is not consistently implemented. Therefore, the active state is now controlled by a javascript implementation.
- chromium issue: https://bugs.chromium.org/p/chromium/issues/detail?id=945854
fixes: https://github.com/SAP/ui5-webcomponents/issues/156

fix(ui5-button): removes active state after tabbing on an pressed button

---

packages/playground/webapp/css/style.css

* Issue: The sapMSltHoverable class is not present on mobile, thus the background of the select controls remains white and as the text colour is also white - they can`t be distinguished.
* Solution: remove this class from the selector

docs: fix settings background on mobile

---

packages/base/Theming.js
packages/base/index.js
packages/base/package.json
packages/base/src/Theming.js
packages/base/src/theming/ThemeProperties.js
packages/main/src/ThemePropertiesProvider.js

- UI5Element is now default export of webcomponents-base
- Theming features exported in "@ui5/webcomponents-base/Theming"

feat: provide named exports for some base modules

---

packages/main/src/RadioButton.hbs
packages/main/src/RadioButton.js
packages/main/src/RadioButtonGroup.js
packages/main/src/RadioButtonTemplateContext.js
packages/main/test/sap/ui/webcomponents/main/pages/RadioButton.html
packages/main/test/sap/ui/webcomponents/main/qunit/RadioButton.qunit.js
packages/main/test/sap/ui/webcomponents/main/samples/RadioButton.sample.html
packages/main/test/specs/RadioButton.spec.js

* Added new property "name", which replaces the property "group" (removed with this change)
* When selection changes within the group by user interaction - single "select" event is being fired and
the newly selected radio button is the event target.
* if more than one radio buttons within a group is set as selected, the last one is effectively selected.
* if  a ui5-radiobutton is added to a new group, the single selection rule would be applied.
* if the selected state is programatically changed, the single selection rule is applied and no event is fired.
BREAKING CHANGE: the property "group" is replaced by the "name" property.

refactor(ui5-radiobutton): improve group handling

---

packages/main/src/CheckBox.js
packages/main/src/InputElementsFormSupport.js
packages/main/src/RadioButton.js
packages/main/test/sap/ui/webcomponents/main/pages/FormSupport.html
packages/main/test/sap/ui/webcomponents/main/pages/form.html
packages/main/test/specs/FormSupport.spec.js

feat: enable radio button form support

---

packages/base/src/UI5Element.js

- in order to have easier styling of the sizes of the components all the css should be applied to the root of the element (such as width, height, etc).
- when having a compact size setting applied, all components should change their sizes, in order to track this change in the css we add a private data attribute to the root of each element

feat: add data-ui5-compact-size attribute to root when compact is set

---

packages/base/src/Theming.js
packages/base/src/theming/CustomStyle.js

With the move to CSS custom properties, the CSS that is added to the shadow DOM is theme independent and never changed when the theme is changed. Theme dependent styling has to be achieved by use of CSS cutsom properties only. This method is adjusted to reflect the standard framework behaviour.
BREAKING CHANGE: the signature of the addCustomCSS method exported by "@ui5/webcomponents-base/Theming.js" is changed from addCustomCSS(tag, theme, css) to addCustomCSS(tag, css)

refactor: make customCSS theme independent

---

packages/main/src/List.js
packages/main/src/ListItemBase.js
packages/main/src/ListItemBaseTemplateContext.js
packages/main/src/themes/GroupHeaderListItem.css
packages/main/src/themes/ListItemBase.css
packages/main/src/themes/base/GroupHeaderListItem-parameters.css
packages/main/src/themes/base/ListItemBase-parameters.css
packages/main/src/themes/sap_belize/GroupHeaderListItem-parameters.css
packages/main/src/themes/sap_belize/parameters-bundle.css
packages/main/src/themes/sap_belize_hcb/GroupHeaderListItem-parameters.css
packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
packages/main/src/themes/sap_fiori_3/GroupHeaderListItem-parameters.css
packages/main/src/themes/sap_fiori_3/parameters-bundle.css
packages/main/test/sap/ui/webcomponents/main/qunit/List.qunit.js
packages/main/test/sap/ui/webcomponents/main/qunit/ListItem.qunit.js

* Remove backgroundDesign property
* Introduce css var: --_ui5_listitem_background_color for ui5-li
* Introduce css var: --_ui5_group_header_listitem_background_color for ui5-li-groupheader
BREAKING CHANGE: the "backgroundDesign" property has been removed, use the corresponding
CSS variable (--_ui5_listitem_background_color) to alter the list items` background.

refactor(ui5-list): remove backgroundDesign property

---

packages/main/src/Panel.js
packages/main/src/themes/Panel.css
packages/main/src/themes/base/Panel-parameters.css
packages/main/test/sap/ui/webcomponents/main/qunit/Panel.qunit.js

* remove "backgroundDesign" property
* introduce css vars: --_ui5_panel_background_color and --_ui5_panel_bottom_border_color to replace the property
BREAKING CHANGE: the "backgroundDesign" property has been removed, use the corresponding 
CSS variables to alter the panel background.

refactor(ui5-panel): remove backgroundDesign property

---

packages/main/src/themes/MessageStrip.css

* Issue: the message strip used to take full parent height, although it might contain only few words.
* Solution: remove the height 100% on element tag, as it can be altered any time by the consumers.
* FIXES: https://github.com/SAP/ui5-webcomponents/issues/375

fix(ui5-messagestrip): remove height 100% on element tag

---

lib/documentation/index.js

FIXES: https://github.com/SAP/ui5-webcomponents/issues/390
* Background: some of the components do not have separate sample page, but they are appended to others sample page. The API of those components is part (in most cases) of parent components API, that use them as composite components.
* Issue: the API of the composite/child components misses base properties.
* Root cause: the API generation of the parent component is done before the API generation of the composite/child components.
* Solution: calculate the API of those composite components before their addition to parents` component API.
Before (StandardListItem "selected"  and "type" properties are missing)
After (StandardListItem "selected"  and "type" properties are in place)

fix: fix API build for composite components 

---

packages/main/src/DatePicker.js
packages/main/test/sap/ui/webcomponents/main/pages/DatePicker.html
packages/main/test/sap/ui/webcomponents/main/pages/DatePicker_fg.html
packages/main/test/sap/ui/webcomponents/main/samples/DatePicker.sample.html

Rename the 'liveChange' event  to 'input' in order to have consistency with the ui5-input,
which already fires 'input' event.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/365
BREAKING CHANGE: 'liveChange' event  has been renamed to 'input'.

 refactor(ui5-datepicker): rename event 'liveChange' to 'input'

---

packages/main/src/Panel.js

When importing the `ui5-panel` by itself, it would not be able to load the `ui5-icon` that it makes use of.
Rendering the panel with
```html
<ui5-panel width="100%" accesible-role="Complementary"></ui5-panel>
```
Without the fix:
With this fix, it works as expected:
Also, I did not find how to test this implementation.

fix(ui5-panel): add missing dependency for ui5-icon

---

packages/base/src/State.js
packages/main/src/Button.js
packages/main/src/DatePicker.js
packages/main/src/Dialog.js
packages/main/src/Input.js
packages/main/src/Label.js
packages/main/src/Link.js
packages/main/src/List.js
packages/main/src/ListItem.js
packages/main/src/Panel.js
packages/main/src/Popover.js
packages/main/src/Popup.js
packages/main/src/RadioButton.js
packages/main/src/Select.js
packages/main/src/ShellBar.js
packages/main/src/StandardListItem.js
packages/main/src/Switch.js
packages/main/src/Tab.js
packages/main/src/TabContainer.js
packages/main/src/Table.js
packages/main/src/TableColumn.js
packages/main/src/TimelineItem.js
packages/main/src/Title.js
packages/main/src/ToggleButton.js
packages/main/test/sap/ui/webcomponents/main/pages/DefaultValues.html
packages/main/test/specs/DefaultValues.spec.js

* Make the defaultValue of boolean properties "false"
* Update components JSDoc, so the the defaultValue for boolean properties appears in playground
* Add generic test
Fixes: https://github.com/SAP/ui5-webcomponents/issues/407

chore: make boolean props false by default

---

packages/main/src/CheckBox.js
packages/main/test/specs/CheckBox.spec.js

- Add default value as false for checked, disabled, read-only, wrap
Fixes: #407

fix(ui5-checkbox): Add ui5-checkbox components default values

---

packages/base/src/State.js
packages/main/src/CheckBox.js
packages/main/src/DatePicker.js
packages/main/src/MessageStrip.js
packages/main/src/Select.js
packages/main/src/TableColumn.js
packages/main/src/TextArea.js

Remove boolean props defaultValue from metadata, as all boolean props are and must be "false" by default.

chore: remove boolean props defaultValue from metadata

---

packages/main/src/CheckBox.hbs
packages/main/src/CheckBox.js
packages/main/src/CheckBoxTemplateContext.js
packages/main/src/RadioButton.hbs
packages/main/src/RadioButton.js
packages/main/src/RadioButtonTemplateContext.js
packages/main/test/sap/ui/webcomponents/main/pages/RadioButton.html
packages/main/test/sap/ui/webcomponents/main/qunit/RadioButton.qunit.js
packages/main/test/sap/ui/webcomponents/main/samples/CheckBox.sample.html
packages/main/test/specs/DefaultValues.spec.js

The property "readOnly" is renamed to "readonly" in both ui5-checkbox and ui5-radiobutton
components to make the API consistent with ui5-input and ui5-datepicker, where the property is already called "readonly". 
Fixes: https://github.com/SAP/ui5-webcomponents/issues/412
BREAKING CHANGE: property "readOnly" is renamed to "readonly" in both ui5-checkbox and ui5-radiobutton.

refactor(ui5-checkbox, ui5-radiobutton): rename "readOnly" to "readonly"

---

packages/main/src/ShellBar.js
packages/main/src/ShellBarItem.js
packages/main/test/sap/ui/webcomponents/main/pages/ShellBar.html

- adds a targetRef parameter to press event of shellbar-item
- adds a support for preventDefault() of press event of shellbar-item
- provides a public method #closeOverflow to the shellbar component
FIXES: https://github.com/SAP/ui5-webcomponents/issues/419

feat(ui5-shellbar): API improvements

---

packages/main/test/sap/ui/webcomponents/main/samples/MultiComboBox.sample.html
packages/playground/webapp/model/models.js

* add since so the users know the component is available since 0.11
* label the component as new to bring users attention
* make the value states example more intuitive by providing tokens with text-  "warning", "error", "success". This way, when users open the multi, the popover is not empty, otherwise looks broken, although it`s not.

doc: update the MultiComboBox sample with since, new labels

---

packages/base/src/UI5Element.js
packages/base/src/UI5ElementMetadata.js

IE does not support assignedElements, therefore assignedNodes should be used instead.
This causes issues for Input with suggestions and Select.
Seems to be a known bug with the polyfill for IE:
https://github.com/webcomponents/webcomponentsjs/issues/1079

fix: do not use assignedElements

---

packages/main/src/Title.hbs
packages/main/src/Title.js
packages/main/src/themes/Title.css
packages/main/test/sap/ui/webcomponents/main/pages/Title.html
packages/main/test/specs/Title.spec.js

* render correct h{n} tag in the component Shadow DOM, based on the "level" property
* make the ui5-title a block element to match the native title behavior
* FIXES: https://github.com/SAP/ui5-webcomponents/issues/434

 fix(ui5-title): render correct h{n} tag based on the "level" property

---

packages/main/src/TabContainer.hbs

Removed typo, the letter 's', from the template, that previously was repeated with each list item in the <ui5-tabcontainer> overflow menu.

fix(ui5-tabcontainer): remove typo from component template

---

packages/main/src/Switch.js
packages/main/test/sap/ui/webcomponents/main/samples/Switch.sample.html

* Improve the overview section with more info about the text, that the ui5-switch can display.
* Remove the custom switch example as it is not Fiori 3 from one hand and from other the switch does not stretch to fit the whole text automatically, so better not advertise long texts in the documentation. However, the info about customising the ui5-switch is added to the overview section.

 docs: improve ui5-switch sample and jsdoc

---

packages/main/src/RadioButton.hbs
packages/main/src/RadioButton.js
packages/main/src/RadioButtonTemplateContext.js
packages/main/src/themes/RadioButton.css
packages/main/test/sap/ui/webcomponents/main/pages/RadioButton.html

* correct touch area size and outer circle radius, according to the latest Fiori 3 spec
* correct outer circle width, based on the valueState
* declare aria-readonly as standard attribute (not boolean) as JAWS does not announce readonly,
if just aria-readonly is present, but it is fine if aria-readonly="true"
* add keyboard handling section
* FIXES: https://github.com/SAP/ui5-webcomponents/issues/443

 fix(ui5-radiobutton): fix touch area size

---

packages/main/src/themes/ToggleButton.css

The fix is already done for ui5-button, but was not done for the ui5-togglebutton.

 fix(ui5-togglebutton): fix text vertical alignment in IE

---

packages/main/src/themes/Button.css

Correct the focus outline color of button with type="Emphasized", based on visual designer feedback
to fulfil contrast ratio requirements.
before
after

fix(ui5-button): fix focus outline color of Emphasized button

---

packages/main/src/Popup.js

The beforeOpen, afterOpen, beforeClose, afterClose events of ui5-dialog and ui5-popover events were missing from the API, because the  ```/** @lends  sap.ui.webcomponents.main.Popup.prototype */```was missing.

docs(ui5-dialog, ui5-popover): show public events as part of the API

---

packages/main/src/themes/Label.css
packages/main/src/themes/Title.css

The css props font-* and color of ui5-label can be changed by setting them the tag.
And, same goes for the ui5-title, except for the font-size as the "h" tags` font-size would overwrite the styles on the tag level.

refactor(ui5-label): allow color and font-* customization

---

packages/main/src/Tab.js
packages/main/src/TabContainer.js
packages/main/src/types/SemanticColor.js

As not just the icon color is what changes we rename the iconColor property to semanticColor
BREAKING CHANGE: iconColor is removed, use semanticColor instead.

refactor(ui5-tab): rename iconColor to semanticColor

---

packages/main/bundle.esm.js
packages/main/src/Badge.hbs
packages/main/src/Badge.js
packages/main/src/themes/Badge.css
packages/main/src/themes/base/Badge-parameters.css
packages/main/src/themes/base/component-derived-colors.js
packages/main/src/themes/sap_belize/Badge-parameters.css
packages/main/src/themes/sap_belize/base-parameters.css
packages/main/src/themes/sap_belize/global-parameters.css
packages/main/src/themes/sap_belize/parameters-bundle.css
packages/main/src/themes/sap_belize_hcb/Badge-parameters.css
packages/main/src/themes/sap_belize_hcb/base-parameters.css
packages/main/src/themes/sap_belize_hcb/global-parameters.css
packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
packages/main/src/themes/sap_fiori_3/Badge-parameters.css
packages/main/src/themes/sap_fiori_3/base-parameters.css
packages/main/src/themes/sap_fiori_3/parameters-bundle.css
packages/main/test/sap/ui/webcomponents/main/pages/Badge.html
packages/main/test/sap/ui/webcomponents/main/pages/Components.html
packages/main/test/sap/ui/webcomponents/main/samples/Badge.sample.html
packages/main/test/specs/Badge.spec.js
packages/main/test/specs/Components.spec.js
packages/playground/webapp/model/models.js

FIXES: https://github.com/SAP/ui5-webcomponents/issues/501

feat(ui5-badge): iniital implementation

---

packages/base/src/UI5Element.js

When a custom element is created via "document.createElement", the browser throws an exception when compactSize=true, because DOM is accessed in the constructor, rather than in connectedCallback

fix: access DOM in connectedCallback instead of constructor

---

packages/base/src/UI5Element.js
packages/base/src/UI5ElementMetadata.js
packages/main/src/List.js

Late validation allows to delay the validation of slot content until custom elements have been defined.
Note: only enable late validation on web components that don't depend on their children being defined. This may include setting properties/attributes, but not calling methods or instance checking. 
To support this change, UI5Element now upgrades all properties (including private) so that when a parent web component sets private properties to children, these will be upgraded as well eventually.
To enable the feature for a slot, use "lateValidation: true"

feat(base): implement late validation

---

packages/base/src/renderer/ifDefined.js
packages/main/src/Link.hbs
packages/main/src/Link.js

- all string attributes with an empty string value will now be written in the DOM
FIXES: https://github.com/SAP/ui5-webcomponents/issues/542

fix: remove custom "falsy" checks from ifDefined

---

packages/base/src/ResourceBundle.js

when a locale other than english is selected, the missing core-shim.js
import was causing the wrong locale to be used by the
core/ResourceBundle
now with adding the Core-shim.js import, all resource bundles
will have the correct locale at run time

fix: fix broken translations

---

packages/main/src/Badge.js
packages/main/src/themes/Badge.css
packages/main/src/themes/base/Badge-parameters.css
packages/main/src/themes/base/component-derived-colors.js

In addition, the appearance of color-scheme="10" is changed according to the Fiori 3 design,
as it used to result in wrong grey background color.
Before
After

refactor(ui5-badge): set default color scheme

---

packages/main/src/Button.hbs
packages/main/src/Button.js

As the button has a disabled attribute the aria-disabled attribute is not needed.

refactor(ui5-button): remove aria-disabled

---

packages/base/src/events/ManagedEvents.js
packages/main/src/Button.hbs
packages/main/src/Button.js
packages/main/src/GroupHeaderListItem.hbs
packages/main/src/Input.hbs
packages/main/src/Input.js
packages/main/src/List.hbs
packages/main/src/ListItem.hbs
packages/main/src/Popover.hbs
packages/main/src/TableRow.hbs
packages/main/src/TextArea.hbs

- if a keydown is on the button but keyup is not, the button used to stay active

refactor: remove focusout and focusin calling by convention

---

lib/documentation/templates/api-slots-section.js

BREAKING CHANGE: the "data-ui5-slot" attribute is deprecated. Use "slot" instead.
All slots can accept multiple child nodes now. Several web components can now accept
text in addition to HTML elements. See the documentation for details about individual web components.
Previous changes: #590

docs: better explain slot usage

---

packages/base/src/DOMEventHandler.js
packages/base/src/events/getShadowDOMTarget.js
packages/main/src/CalendarHeader.js
packages/main/src/DatePicker.js
packages/main/src/DayPicker.js
packages/main/src/MonthPicker.js
packages/main/src/Panel.hbs
packages/main/src/Panel.js
packages/main/src/YearPicker.js
packages/main/test/sap/ui/webcomponents/main/qunit/DayPicker.qunit.js

In addition, a bug is fixed with this change: clicking between the cells in the date picker no longer produces a JS error in the console.

refactor: remove ui5target

---

packages/main/src/Button.js
packages/main/src/Card.js
packages/main/src/Link.js
packages/main/src/List.js
packages/main/src/ShellBar.js
packages/main/src/TimelineItem.hbs
packages/main/src/TimelineItem.js
packages/main/src/themes/Link.css
packages/main/test/sap/ui/webcomponents/main/pages/Card.html
packages/main/test/sap/ui/webcomponents/main/pages/Eventing.html
packages/main/test/sap/ui/webcomponents/main/pages/Link.html
packages/main/test/sap/ui/webcomponents/main/pages/List.html
packages/main/test/sap/ui/webcomponents/main/pages/ShellBar.html
packages/main/test/sap/ui/webcomponents/main/pages/Timeline.html
packages/main/test/sap/ui/webcomponents/main/samples/ShellBar.sample.html
packages/main/test/specs/Card.spec.js
packages/main/test/specs/Link.spec.js
packages/main/test/specs/Timeline.spec.js

also rename two-word events from press to click for consistency
BREAKING CHANGE: ui5-button press event is renamed to click
BREAKING CHANGE: ui5-card headerPress event is renamed to headerClick
BREAKING CHANGE: ui5-link press event is renamed to click
BREAKING CHANGE: ui5-list itemPress event is renamed to itemClick
BREAKING CHANGE: ui5-shellbar notificationsPress event is renamed to notificationsClick
BREAKING CHANGE: ui5-shellbar profilePress event is renamed to profileClick
BREAKING CHANGE: ui5-shellbar productSwitchPress event is renamed to productSwitchClick
BREAKING CHANGE: ui5-shellbar logoPress event is renamed to logoClick
BREAKING CHANGE: ui5-shellbar coPilotPress event is renamed to coPilotClick
BREAKING CHANGE: ui5-shellbar menuItemPress event is renamed to menuItemClick …

refactor: remove press event in favour of click

---

packages/base/src/DOMEventHandler.js

Including  multiple instances of the webcomponents on the same page
causes the global event handlers to be registered multiple times
This then causes multiple calls of the event handlers on the prototype
and multiple semantic events being fired.

fix: fix redundant event dispatch

---

packages/main/src/ShellBar.js
packages/main/src/ShellBarItem.js
packages/main/test/sap/ui/webcomponents/main/pages/ShellBar.html

FIXES: https://github.com/SAP/ui5-webcomponents/issues/611
BREAKING CHANGE: ui5-shellbar-item press event is renamed to itemClick

refactor(ui5-shellbar-item): rename press event to itemClick

---

packages/main/src/themes/BusyIndicator.css

ui5-popover and ui5-dialog start from z-index 100
FIXES: https://github.com/SAP/ui5-webcomponents/issues/610

fix(ui5-busyindicator): change z-index not to overlap popover or dialog

---

packages/main/src/themes/Icon.css

move the default font size to the host element so it can be styled externally

fix: enable default icon size to be changed

---

packages/main/src/Badge.hbs
packages/main/src/Badge.js
packages/main/src/themes/Badge.css

- remove element tag within host selector
- avoid slot element rendering if no icon (slot) is set

refactor(ui5-badge): styles clean up

---

packages/base/src/UI5Element.js
packages/base/src/UI5ElementMetadata.js
packages/main/src/Calendar.js
packages/main/src/Card.js
packages/main/src/DatePicker.js
packages/main/src/DayPicker.js
packages/main/src/Label.js
packages/main/src/Link.js
packages/main/src/ListItem.js
packages/main/src/ListItemBase.js
packages/main/src/MonthPicker.js
packages/main/src/MultiComboBox.js
packages/main/src/Panel.js
packages/main/src/Popover.js
packages/main/src/Popup.js
packages/main/src/Select.js
packages/main/src/ShellBar.js
packages/main/src/Tab.js
packages/main/src/TabContainer.js
packages/main/src/TableCell.js
packages/main/src/TextArea.js
packages/main/src/TimelineItem.js
packages/main/src/Token.js
packages/main/src/Tokenizer.js
packages/main/src/YearPicker.js
packages/main/test/sap/ui/webcomponents/main/pages/notepad/notepad.html

- new metadata entity added: "noAttribute"
- properties that have "noAttribute: true" or are of type "Object" won't have attributes
- all other properties will have attributes (no magic detection if their names start with _ or not)
- metadata "association" entity is removed
After this change it will be possible to have properties starting with underscore that also have attribute equivalents. Until now if you wanted to make a private property also have an attribute, you had to rename it not to start with underscore.

refactor: metadata noAttribute added

---

packages/main/src/Icon.js
packages/main/test/sap/ui/webcomponents/main/pages/Simple.html

For IE CSS enters the head tag with setTimeout, because we schedule the CSS Vars ponyfill rather than run it immediately when CSS is available. The reason for this scheduling is that we need all CSS styles processed at once, otherwise it's too slow. We can't run the ponyfill for styles one by one due to the way it works (if you run it for just one style, the output will be for only this style, regardless of others processed earlier).
This is an icon-only solution until we have a framework-wide solution, because for icon the flicker is the worst, due to SVG scaling on IE. We create a global style in the head at define time and use it to hide the icon until it has entered the DOM.

fix: icon no longer flickers on IE

---

packages/main/src/themes/Badge.css
packages/main/src/themes/base/Badge-parameters.css

- fix the icon size, after using SVG, instead of icon-font
- enable component scaling based on the set font-size, using `em`, instead of `rem`.

fix(ui5-badge): fix icon size

---

packages/main/src/Switch.hbs

before (in RTL):
after  (in RTL):

fix(ui5-switch): don`t mirror checkmark icon in RTL

---

packages/main/lib/create-new-component/create-new-component.js
packages/main/package.json

Adding a script for automatically create files by template for new web component.

feat: implement create control script

---

packages/main/src/MultiComboBox.js
packages/main/test/sap/ui/webcomponents/main/pages/MultiComboBox.html
packages/main/test/sap/ui/webcomponents/main/samples/MultiComboBox.sample.html
packages/main/test/specs/MultiComboBox.spec.js

BREAKING CHANGE:
- validate-input property is removed
- allow-custom-values not replaces validate-input and built in validation is enabled by default

refactor(ui5-multi-combobox): Replace validate-input with allow-custom-values

---

packages/main/src/TextArea.js

The "_height" private property is removed as it is not used. This way we are one step closer to remove the "CSSSize" type.

chore(ui5-textarea): remove unused private property

---

packages/main/src/Input.js
packages/main/src/features/InputSuggestions.js
packages/main/test/sap/ui/webcomponents/main/samples/Input.sample.html

The ui5-input with suggestions used to import both StandardListItem and CustomListItem,
but It`s better to let this to the consumer. The consumer can decide to import the one or the other (or both) or not use them at all, although usage of other items will not work as expected.
* Remove StandardListItem and CustomListItem imports.
* Update API doc, recommending to use StandardListItem or CustomListItem items.
* Fix unrelated sample issue - the placeholder of the input below has been misaligned due to obsolete styling.
before:
after:
BREAKING CHANGE: `ui5-input` with suggestions no longer loads `ui5-li `and `ui5-li-custom` items, you need to explicitly import them.

refactor(ui5-input): stop importing StandardListItem and CustomListItem

---

packages/base/src/CSS.js
packages/base/src/theming/StyleInjection.js
packages/base/src/util/CSSTransformUtils.js
packages/main/src/themes/Badge.css
packages/main/src/themes/Button.css
packages/main/src/themes/Input.css
packages/main/src/themes/ShellBar.css
packages/main/src/themes/Table.css
packages/main/src/themes/TableCell.css
packages/main/src/themes/TableColumn.css

- automatically add the tag before each selector that doesn't have it
- replace :host
- replace ::slotted
- revert all CSS selectors that had :host added artificially due to the previous algorithm

refactor: provide better CSS encapsulation for IE

---

packages/main/src/themes/Button.css
packages/main/src/themes/base/Button-parameters.css
packages/main/src/themes/sap_belize/Button-parameters.css
packages/main/src/themes/sap_belize_hcb/Button-parameters.css

Fixes: https://github.com/SAP/ui5-webcomponents/issues/788
Two corrections:
- Border provided for Transparent button upon hover in Fiori 3:
- In HCB there should be always a border even for Transparent button (hovered or not):
Note:
- However, in Belize there is no border on hover for Transparent button and this is kept as it is currently:

fix(ui5-button): fix Transparent button border in Fiori 3 & HCB

---

packages/main/src/Input.js

"Suggestions available" is now correctly translated.

fix(ui5-input): use translated text

---

packages/main/src/Table.js
packages/main/src/TableColumn.hbs
packages/main/src/TableColumn.js
packages/main/src/themes/TableCell.css
packages/main/src/themes/TableColumn.css
packages/main/test/sap/ui/webcomponents/main/samples/Table.sample.html

BREAKING CHANGE: width property of the ui5-table-column has been removed.
Use CSS to give width to the columns.
Usage: `<ui5-table-column style="width: 100px"></ ...`

refactor(ui5-table): width property of column is removed

---

packages/main/src/themes/Panel.css
packages/main/src/themes/base/Panel-parameters.css
packages/main/src/themes/sap_belize_hcb/Panel-parameters.css
packages/main/src/themes/sap_fiori_3/Panel-parameters.css

The latest design suggests that the ui5-panel's expand/collapse button should be the same as a Transparent ui5-button. We used to have significant amount of additional css, that is no longer needed as we use Transparent ui5-button already. All the css (other than sizing) and css properties  are removed.
Note: The following design is for Fiori 3 (quartz), but we will apply it for Fiori 2 (belize) as well.

refactor(ui5-panel): align toggle button visual design

---

packages/main/src/List.js
packages/main/src/ListItem.hbs
packages/main/src/ListItem.js
packages/main/test/sap/ui/webcomponents/main/pages/List_test_page.html
packages/main/test/specs/List.spec.js

`selectionComponentPressed` param will be provided along with the `selectionChange` event
to indicate if a selection component is used in SingleSelect (ui5-radiobutton) and MultiSelect (ui5-checkbox) modes to change the selection.

feat(ui5-list): added new param for selectionChange event

---

packages/playground/webapp/index.html

The purpose of this change is to make it clearer that the email should be used for high level product-related questions, and technical questions should be asked in slack. Also, a subject is pre-populated so that it can be distinguished from OpenUI5.

chore: update contact info

---

packages/main/src/themes/Link.css
packages/main/test/sap/ui/webcomponents/main/pages/Link.html

Due to previous CSS refactoring we lost the hover effect on the ui5-links, now it is fixed.

fix(ui5-link): fix link hover effect

---

packages/main/src/DayPicker.hbs
packages/main/src/DayPicker.js
packages/main/test/sap/ui/webcomponents/main/samples/Input.sample.html

The week number does not make sense for Islamic, Buddhist Japanese calendars and show it only for Gregorian calendar.

fix: hide week number in Islamic, Buddhist Japanese calendars

---

packages/main/src/MultiComboBox.js
packages/main/src/Panel.js

- ui5-panel  uses ui5-button (see Panel.hbs), but does not import it
- MultiComboBox no longer uses ui5-input, but native input (see MultiComboBox.hbs)

 chore: fix component dependencies

---

packages/main/src/themes/TabContainer.css
packages/main/src/themes/base/TabContainer-parameters.css
packages/main/src/themes/sap_belize_hcb/TabContainer-parameters.css

Fix tab selected text color and ensure proper contrast  ration in HCB.
before:
after:

fix(ui5-tabcontainer): fix selected tab text color in HCB

---

packages/main/src/Panel.hbs
packages/main/src/Panel.js
packages/main/src/themes/Button.css
packages/main/src/themes/Panel.css
packages/main/test/sap/ui/webcomponents/main/qunit/Panel.qunit.js

- refactor `ui5-panel` toggle button as following:  remove the `ui5-icon` inside `ui5-button` form the template as it is not needed as we can use `ui5-button` with `icon` property. 
- the `flex-shrink: 0` is needed in order to make the toggle button not move to left and right when the user shrinks or expands the screen
```css
.ui5-panel-header-button-root {flex-shrink: 0}
```

refactor(ui5-panel): remove ui5-icon from hbs template

---

packages/base/src/util/CSSTransformUtils.js

keyframes gets optimised by csso
'100%' --> 'to' which doesn't match the
runtime CSS transformation rules
and incorrectly prepends the tag name,
making the CSS invalid and braking on IE

fix(ui5-busyindicator): remove incorrect CSS transformation in IE

---

packages/playground/webapp/index.html
packages/playground/webapp/view/Main.view.xml

Hi there, this is my first "test contribution". I hope I did everything right. cla-assistant.io is not working right now...
This PR just just updates the version number you see in the playground in some places.

fix: update version to 1.0.0-rc3 in playground

---

packages/main/src/TableRow.js
packages/main/test/sap/ui/webcomponents/main/pages/Table.html
packages/main/test/specs/Table.spec.js

In case we have more columns declared, but less cells provided,
a JS error is present and the ui5-table is not displayed at all.

fix(ui5-table): fix JS error when there are less cells than columns

---

packages/main/src/Input.hbs
packages/main/src/Input.js

The _accInfo method used to return undefined for aria attributes. Now the method works as expected.

fix(ui5-input): correct acc info implementation

---

packages/base/src/compatibility/whenPolyfillLoaded.js

Check that polyfill are not already loaded and that we are not waiting on an event that has already been emitted.

Fix: whenPolyfillLoaded

---

packages/base/src/UI5Element.js
packages/main/test/sap/ui/webcomponents/main/pages/base/DOMObserver.html
packages/main/test/specs/base/DOMObserver.spec.js

DOM insertion order was leading to situations where the mutation
observer was not registered
leaving empty rendered rows
fixes: #839

fix: trigger dom mutation observer independent of insertion order

---

packages/base/src/UI5Element.js
packages/main/src/Calendar.js
packages/main/src/DatePicker.js
packages/main/src/DayPicker.js
packages/main/src/ShellBar.js
packages/main/src/TableRow.js

- invalidation again happens only on reference change for objects
- if some web component needs to minimize invalidation, equality checks must be done internally

refactor: remove deepEqual from metadata

---

packages/main/src/Button.hbs
packages/main/src/Button.js
packages/main/src/Panel.hbs
packages/main/src/Panel.js
packages/main/test/specs/Panel.spec.js

Implemented accessibility for the ui5-panel.

feat(ui5-panel): implement accessibility

---

packages/main/src/Input.js

**Issue** 
When you use ui5-input and set the name property, warnings are thrown.
**Steps**
1. Go to https://sap.github.io/ui5-webcomponents/master/test-resources/sap/ui/webcomponents/main/pages/Input.html
2.  Observe the warnings in the console: "Unknown slotName: formSupport, ignoring <input type=​"hidden" data-ui5-form-support slot=​"formSupport" name=​"my-input-email" value>​ Valid values are: icon, default, _beginContent
**Root cause**
We create a native input to enable form support and insert it with slot="formSupport", but the UI5 Element slot validation throws these warnings when a slot, unknown to component's metadata, is about to be slotted.
**Solution**
It`s strange to have warnings, as there is nothing wrong with the usage, "name" property has been given and the "FormSupport" …

chore(ui5-input): clear warnings when name property is set

---

packages/base/src/UI5Element.js

FIXES: https://github.com/SAP/ui5-webcomponents/issues/873
Order slotted children in components state properly, keeping their order in the Light DOM, not the order the children are defined.

fix: order slots in state as in Light DOM

---

packages/main/src/Input.hbs
packages/main/src/Input.js

The _beginContent slot used  to serve the MultiComboBox, but since the component started using a native input element  instead of ui5-input, the slot is not used anymore.

chore(ui5-input): remove obsolete _beginContent slot

---

packages/base/src/UI5Element.js
packages/base/src/delegate/ItemNavigation.js
packages/main/src/DayPicker.js
packages/main/src/List.js
packages/main/src/MonthPicker.js
packages/main/src/ShellBar.js
packages/main/src/TabContainer.js
packages/main/src/Table.js
packages/main/src/Timeline.js
packages/main/src/Tokenizer.js
packages/main/src/YearPicker.js

- ItemNavigation invalidates the component when it
changes the tabIndex, this is simpler than the removed setItemsCallback
- UI5Element fires a private event after onBeforeRendering, but before the
actual rendering so the item navigation
can automatically apply tab indexes
in case the component changed the state and wipted the tab indexes
- adapt all components to new behaviour

refactor: item navigation simplification

---

packages/base/src/delegate/ScrollEnablement.js

- since the ScrollEnablement does not use preventDefault, it is ok
to switch to passive event listeneres
for the touch events (and get rid of
the console warnings)

chore: use passive touch listeners

---

packages/main/src/ShellBar.hbs
packages/main/src/ShellBar.js
packages/main/src/themes/ShellBar.css
packages/main/test/pages/ShellBar.html
packages/main/test/samples/ShellBar.sample.html
packages/main/test/specs/ShellBar.spec.js

FIXES: https://github.com/SAP/ui5-webcomponents/issues/884
BREAKING CHANGE: icon aggregation has been renamed to startButton.
It accepts a ui5-button and overstyles it to match ShellBar's styling.

refactor(ui5-shellbar): rename icon slot to startButton

---

packages/main/src/Button.hbs
packages/main/src/Button.js

The button should not override on* handlers and instead use internal functions and subscribe the event handlers within HBS template.
Part of https://github.com/SAP/ui5-webcomponents/issues/834

refactor(ui5-button): subscribe event handlers within HBS template

---

docs/Configuration.md
packages/base/src/InitialConfiguration.js
packages/base/src/config/AnimationMode.js
packages/base/src/types/AnimationMode.js
packages/base/src/types/AnimationModes.js
packages/main/bundle.esm.js
packages/main/src/Panel.hbs
packages/main/src/Panel.js
packages/main/src/themes/Panel.css
packages/main/test/pages/AnimanitionOff.html

- Add `animationMode` to configure the degree of components animations.
Available options are: `full` (by default), `basic`, `minimal` and `none`,
where `full` means all animations run without restrictions and `none` means all animations are off.
- Switch on/off the ui5-panel toggle animation based on the `animationMode`.

feat: add animationMode configuration

---

packages/main/jsconfig.json

VS code reads the jsconfig.json file and the paths mapping.
This enables CMD-click on a module in `@ui5/webcomponents-base/dist/` to navigate to the `src` folder of the monorepo instead of the `dist` folder where any edits would be lost.

chore: map dist to src for VSCode navigation

---

packages/main/test/pages/DatePicker_test_page.html

all the failing tests are when an interaction in the popover of the datepicker occurs.
since those interactions are on the last date picker towards the end of the document,
try moving it to the beginning so
we hopfully don't get the element not interactible errors

chore: improve test stability

---

packages/main/src/Popover.hbs
packages/main/src/Popover.js
packages/main/src/themes/Popover.css
packages/main/test/pages/Popover.html
packages/main/test/specs/Popover.spec.js

FIXES: https://github.com/SAP/ui5-webcomponents/issues/853

fix(ui5-popover): restrict max content height when overflowing the screen

---

packages/main/src/MultiComboBox.js
packages/main/test/pages/MultiComboBox.html
packages/main/test/specs/MultiComboBox.spec.js

FIXES: https://github.com/SAP/ui5-webcomponents/issues/713

feat(ui5-multicombobox): introduce open property and openChange event

---

packages/main/src/Table.js

We prevented spacebar inside a table in order to suppress the default scrolling behavior. However, the side effects of this are too detrimental - buttons inside the table don't activate on space and inputs inside the table don't accept space. Therefore, it's better to let the developer manually prevent scrolling, if necessary.

fix: spacebar works for HTML elements inside a ui5-table

---

packages/base/src/delegate/ItemNavigation.js
packages/main/test/pages/ItemNavigation.html
packages/main/test/specs/ItemNavigation.spec.js

**Background**
By default the focus (managed by ItemNavigation) does not cycle trough the items, which turned out that has not been working.
**Root Cause**
We check for the `cycle` config when border cases are reached (first or last item), but the only thing we do is to fire a private event ("_borderReach"), but updating the index, so it actually makes a whole loop (cycle).
**Fix**
In these border cases we just update the internal index to `0` (when "top" border is reached) and `items.length-1` (when "bottom" border is reached).

fix: prevent ItemNavigation from cycling by default

---

packages/main/src/TabContainer.hbs
packages/main/src/themes/TabContainer.css

- The icon is in the correct color for positive, negative and critical items.
- Pressing over the icon now works - it performs selection.

fix(ui5-tabcontainer): fix overflow items appearance and selection 

---

packages/main/src/themes/TabContainer.css
packages/main/test/pages/TabContainer.html

This is a follow up of Follow up of: #988 where overflow items appearance in negative, positive and critical states have been fixed. However, I missed the default semantic appearance.
Now the default semantic appearance of the overflow item text and icon in active state also looks correct.

fix(ui5-tabcontainer): fix overflow item default semantic color

---

packages/main/src/themes/CheckBox.css
packages/main/src/themes/Label.css

The pull request fixes degradation, caused by a recent style changes in the ui5-label #965,
causing ui5-checkbox label stop wrapping.

chore: fix checkbox wrapping degradation caused by #965

---

packages/base/src/UI5Element.js
packages/main/src/DatePicker.js
packages/main/test/pages/DatePicker.html

- It is now possible to explicitly set `undefined` as default value for `String`, and it will not be overridden by `""`
- Datepicker.js sets the default value for `placeholder` to `undefined`

fix(ui5-datepicker): it is now possible to set an empty placeholder

---

packages/main/src/themes/CheckBox.css
packages/main/test/pages/CheckBox.html

Although there is enough space, the checkbox used to truncate,
now this is fixed.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/996
Before
After

fix(ui5-checkbox): fix truncation in compactSize

---

packages/fiori/src/ShellBar.js
packages/fiori/src/ShellBarItem.js

Display `ui5-shellbar` and `ui5-shellbar-item` properties as part of the API.
Root cause: mixing the @ lends marks (sap.ui.webcomponents.main and sap.ui.webcomponents.fiori) causes missing of API data.

docs(ui5-shellbar): display component properties

---

packages/main/test/pages/CheckBox.html
packages/main/test/specs/CheckBox.spec.js

The test that verifies if the wrapping of the component is working is now actually tests that correctly.
- The checkbox under test used to not have "wrap" set and 
- In addition, it has 2px border (set by inline styles in the test page) so its height is bigger than our threshold (44px) with 2px, and even when it stops wrapping - the test would pass.

chore(ui5-checkbox): fix the wrapping functionality unit test

---

packages/tools/components-package/rollup.js
packages/tools/package.json
yarn.lock

- enabled only for `main`
- notifications switched to errors only
- filesize plugin moved to prod build only (bundle in less than 1s now)

chore: add livereload

---

packages/base/src/asset-registries/Themes.js

We used to throw an error with the recommendation to import `@ui5/webcomponents/dist/json-imports/Themes`, when the requested theme is not even existing.
Now, if the requested theme is not existing, we will output a warning and fallback to `sap_fiori_3`, and never fetch the requested (non-existing) theme.

refactor(Theming): fallback to Fiori 3 theme

---

packages/main/test/specs/TabContainer.spec.js

Make the build pass again. 
The tests must be addressed and re-added though: https://github.com/SAP/ui5-webcomponents/issues/1044

chore: comment out failing tabcontainer test

---

packages/main/src/TabContainer.hbs
packages/main/src/TabContainer.js
packages/main/src/themes/TabContainer.css
packages/main/src/themes/base/TabContainer-parameters.css
packages/main/test/pages/TabContainer.html
packages/main/test/specs/TabContainer.spec.js

The tab container content part used to have height: 100% and did not take into account the header (the tab strip). 
Now the tab strip have determined heights in cozy and compact and the content is calculated accordingly calc(100% - headerHeight) and the test are green again.

fix(ui5-tabcontainer): fix tab content overflow and height calculation

---

packages/theme-base/lib/verify-vars/index.js

The sapHC_* are High Contrast Black specific and should not be log as missing in the rest of the themes.

chore(css-vars-verify): ignore HCB specific variables

---

packages/main/src/themes/ListItem.css
packages/main/src/themes/ListItemBase.css
packages/main/src/themes/base/ListItemBase-parameters.css
packages/theme-base/src/themes/sap_belize/base-parameters-vars.less
packages/theme-base/src/themes/sap_belize/base-parameters.less
packages/theme-base/src/themes/sap_belize_hcb/base-parameters-vars.less
packages/theme-base/src/themes/sap_belize_hcb/base-parameters.less
packages/theme-base/src/themes/sap_fiori_3/base-parameters-vars.less
packages/theme-base/src/themes/sap_fiori_3/base-parameters.less
packages/theme-base/src/themes/sap_fiori_3_dark/base-parameters-vars.less
packages/theme-base/src/themes/sap_fiori_3_dark/base-parameters.less

It`s an enhancement and alignment with the latest list item visual design.
The selected item should have bottom-border:

 refactor(ui5-li): apply selection border color

---

packages/main/src/Select.js
packages/main/test/pages/Select.html
packages/main/test/specs/Select.spec.js

**Background**
We stopped the ui5-list from cycling the focus. The ui5-select internally uses a list to display its options, but cycles the selection and there is a mismatch between the selected option and the option on focus.
Now, both the focus and the selection matches and do not cycle (as the sap.m.Select in openui5)
**Before**
**After**

fix(ui5-select): prevent selection from cycling

---

packages/main/src/themes/RadioButton.css
packages/main/src/themes/base/CheckBox-parameters.css
packages/main/src/themes/base/RadioButton-parameters.css
packages/theme-base/src/themes/base/component-derived-colors-vars.less
packages/theme-base/src/themes/base/component-derived-colors.less

- Fix the background for the `ui5-radiobutton` outer circle, used to be transparent
- Replace a derived color for warning state with latest suggested param in the visual spec
- Fix the appearance of the active dot in warning state for Quartz Dark
- Fix `ui5-radiobutton` outer circle stroke(border) in selected state
Before:
After:
Before (the border should become blue on hover not in regular state):
After:

fix(ui5-radiobutton): align visual to latest spec

---

packages/main/src/TextArea.js
packages/main/test/pages/TextArea.html
packages/main/test/samples/TextArea.sample.html

The ui5-input has the same property and it is called `maxlength` (lowercase)  and as the native input element attribute is called the same way, we decided to rename ui5-textarea `maxLength` (camelcase) to `maxlength` (lowercase)
BREAKING CHANGE: The property `maxLength` has been renamed to `maxlength`.
Also, the corresponding attribute name is changed from `max-length` to `maxlength`.

refactor(ui5-textarea): rename property maxLength to maxlength

---

packages/main/src/themes/Select.css
packages/main/src/themes/base/InputIcon-parameters.css
packages/main/test/pages/Input.html

FIXES: https://github.com/SAP/ui5-webcomponents/issues/1074
**Background**
The `overflow: hidden` causes the ui5-select to be pushed upwards the main baseline (as described in the issue). Originally, the style was introduced  not to allow the hover of the arrow to cover the input border. Now, this is resolved by moving this `overflow: hidden` to inner element and in the same time not disrupting the baseline alignment of the whole component.

fix(ui5-select): fix component baseline alignment

---

packages/main/src/themes/Label.css
packages/main/test/pages/Label.html
packages/main/test/specs/Label.spec.js

Fixes: https://github.com/SAP/ui5-webcomponents/issues/1077
The allocated width for the ":" used to be bigger than the ":" itself causing the ui5-label always to truncate, when show-colon is set to "true".

fix(ui5-label): fix truncation when show-colon is set

---

docs/Configuration.md
docs/Public Module Imports.md
packages/base/src/ContentDensity.js
packages/base/src/UI5Element.js
packages/base/src/UI5ElementMetadata.js
packages/base/src/config/CompactSize.js
packages/main/bundle.es5.js
packages/main/bundle.esm.js
packages/main/src/RadioButton.js

- The term `contentDensity` is used instead of `compactSize` for new files and vars (to be compatible with the upcoming rework of `compactSize`)
- All UI5 Elements subscribe to content density change and modify their host accordingly
- A new module `ContentDensity.js`, similar to `Theming.js` added to allow to subscribe/execute
- Only `ui5-radiobutton` currently uses `compactSize` outside of pure CSS, therefore it needs to be rerendered, thus the new metadata `invalidateOnContentDensityChange`. This is needed as components cannot call `_invalidate()` themselves, it's private to `UI5Element.js`

feature(framework): allow setting compactSize dynamically

---

packages/base/src/FontFace.js
packages/main/src/themes/List.css
packages/main/src/themes/Switch.css
packages/main/src/themes/TableCell.css

- If the framework boots from several bundles, it will create the font face style just once
- Additionally `font-family` CSS rules have been unified

fix: The font face style tag is created only once

---

packages/base/src/UI5Element.js
packages/main/src/MonthPicker.js
packages/main/src/YearPicker.js

- `_nextID` now generates better IDs based on the class name (rather than a hard-coded prefix), which makes the Map used useful (before it could have been an integer instead).
- Wrongly generated IDs were fixed (`_state` is private to `UI5Element.js` and should not be used outside)

refactor: improve auto-generated IDs

---

packages/base/src/UI5Element.js
packages/utils/used-modules.txt

- The `metadata` objects were not merged correctly due to calling `Array.prototype.reverse` several times in a row, while not considering it changes the original object, thus when merging slots, it was done in the opposite direction
- The merge was not deep so you couldn't just override a setting for a property or slot for example
- Additionally the variable `klass` was used only when necessary for clarity (when looping over prototypes), for the rest `this` is more intuitive
This changes uses the deep merge `merge.js` from the `utils` project.
closes: https://github.com/SAP/ui5-webcomponents/issues/454

fix: Merge metadata properly

---

packages/main/src/ListItem.js
packages/main/src/ListItemBase.js
packages/main/src/themes/ListItemBase.css

Add private property "focused" to apply the focus styling, even when the component is not on focus. This will allow the implementation of complex UX requirements related to the Combobox and MiltiCombobox, where the actual focus remains in the input field, but the visual focus outline moves between the items.

refactor(ui5-li): switch focus styling via state

---

packages/base/src/CSS.js
packages/base/src/UI5Element.js

- Component-specific CSS is no longer dependent on the theme, therefore nothing happens on theme change
- Constructable stylesheets no longer need the theme as part of the key - currently exactly the same constructable style is created 4 times (once for each theme) unnecessarily
- Directly use `getEffectiveStyle` in `UI5Element.js` and move the logic when to use it there as well, in order to make it consistent with the Chrome and IE/Edge checks (which are also in `UI5Element.js`). Therefore `getShadowRootStyle` becomes unnecessary.

refactor: simplify theming management

---

packages/main/src/themes/Timeline.css
packages/main/test/pages/Timeline.html

According to both Timeline integration card and Timeline visual specs, the component should not set its own background.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1118

refactor(ui5-timeline): remove style bg color

---

packages/base/src/UI5Element.js
packages/base/src/compatibility/patchNodeValue.js
packages/base/test/specs/UI5ElementInvalidation.js

- The IE patch that overcomes the limitation of the fake Mutation Observer now uses the official duck-typing check for UI5Element. Additionally it was documented that `_processChildren` is called from the outside and should not be renamed.
- Added 2 tests checking for invalidation upon text change inside a web component with a slot of type `Node`

chore: improve UI5Element detection

---

packages/base/src/asset-registries/Themes.js
packages/base/src/asset-registries/i18n.js
packages/main/src/Icon.js

- remove the `src` property in favor of `name` (it used to be deprecated)
- fix the `console.warn` messages to suggest the new asset imports (not just for icons, but for other assets as well)
BREAKING CHANGE: The `src` property is replaced with `name` and no longer requires the `sap-icon://` protocol. For example: `<ui5-icon src="sap-icon://add">` becomes `<ui5-icon name="add">`

refactor(ui5-icon): remove src property

---

docs/Public Module Imports.md
packages/base/bundle.esm.js
packages/base/src/asset-registries/Themes.js
packages/base/test/elements/Generic.js
packages/base/test/specs/CustomTheme.spec.js

Creating a custom theme is largely possible today with a couple of slight adjustments:
- Change the theme registry to allow for custom themes (instead of hard-coded list with ours)
- Document (both in jsdoc and .md) the `registerThemeProperties` method
- Add a test

feature(framework): Allow the registration of custom themes

---

packages/main/test/pageobjects/DayPickerTestPage.js
packages/main/test/specs/DayPicker.spec.js

- This test sometimes fails, because it does not use the framework methods that synchronize with the `RenderScheduler`, but rather directly executes low-level code with `browser.execute`. Therefore the fix is to use `browser.executeAsync` and wait for the rendering to be complete manually.
- Additionally fixed the wrongly named getter

chore: fix unstable test

---

packages/theme-base/.npmignore
packages/tools/.npmignore

The tools package "lib" folder and rollup.js are not being published in npm (they are simply ignored),
but they are needed for other repos using our tooling to build and develop UI5 Web Components.

chore: update npmignore files

---

packages/main/src/RadioButton.hbs
packages/main/src/RadioButton.js
packages/main/src/themes/RadioButton.css
packages/main/src/themes/base/RadioButton-parameters.css

Reuse same SVG mark up for both "compact and "cozy" content densities and apply corresponding differences in size via CSS only and remove all current JS calculations.

refactor(ui5-radiobutton): set compact via CSS

---

packages/main/src/Icon.js

The warning was pointing to `@ui5/webcomponents` instead of `@ui5/webcomponents-icons`

fix(Icon): Update warning to show correct path

---

packages/main/src/themes/ListItemBase.css

When pressed down the list item focus color should be changed to fulfil the constrast ratio with the background in active state.

fix(ui5-li): correct focus color when active

---

packages/main/src/themes/TextArea.css

Users can now override the color, but not the background. So move the CSS rule to the host.

feature(ui5-textarea): allow users to modify textarea background

---

packages/main/src/themes/Avatar.css

The CSS rule was left over when "img-src" was renamed to "image" and due to that all transparent images became blue.

fix(ui5-avatar): remove background color when there is no image

---

packages/main/src/Card.hbs
packages/main/src/Card.js
packages/main/src/themes/Card.css
packages/main/test/pages/Card.html
packages/main/test/samples/Card.sample.html

**refactor**
rename subtitle property to subheading to match the heading property
**fix**
don`t allocate space for the avatar if avatar is not present
BREAKING CHANGE: the property subtitle has been renamed to subheading

refactor(ui5-card): update API and correct visual

---

packages/main/src/themes/Input.css

due to css syntax typo (combining :not selectors), the hover effect used not apply.

fix(ui5-input): border-color on hover

---

packages/main/src/themes/Table.css
packages/main/src/themes/TableRow.css

Before (the 1st row and the "nodata" rows have been greyish)
After

fix(ui5-table-row): fix 1st and "nodata" rows visual

---

packages/main/src/CheckBox.js
packages/main/src/ListItem.hbs
packages/main/src/RadioButton.js
packages/main/src/themes/ListItem.css
packages/main/test/specs/List.spec.js

- checkbox,  radio: consider the "tabindex" set on the host and propagate it into the shadow DOM.
- list item: set "tabindex='-1'" to the selection components as there is no need of a tab stop

refactor(ui5-checkbox, ui5-radiobutton): propagate tabindex

---

packages/base/src/RenderScheduler.js
packages/base/src/UI5Element.js
packages/base/src/delegate/ItemNavigation.js

O(n) -> O(1)
- unnecessary creation of timeouts per element replaced with single timeout
- unnecessary event dispatching replaced by hook

improve: performance for high number of elements

---

packages/main/src/themes/Input.css
packages/main/src/themes/MultiComboBox.css
packages/main/src/themes/TextArea.css
packages/main/src/themes/base/Input-parameters.css
packages/main/src/themes/base/sizes-parameters.css
packages/main/src/themes/sap_fiori_3/Input-parameters.css
packages/main/src/themes/sap_fiori_3_dark/Input-parameters.css
packages/main/test/pages/Input.html

- rename legacy "sap_wc" prefixed params with "ui5_" prefix ones
- remove fixed width of the input's icon area, so users can display more than one.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1153
```html
<ui5-input id="input3" placeholder="Search ...">
<ui5-icon slot="icon" name="search" style="padding-left: 8px; padding-right: 8px"></ui5-icon>
<ui5-icon slot="icon" name="decline" style="padding-left: 8px; padding-right: 8px"></ui5-icon>
</ui5-input>
```

refactor(ui5-input): allow displaying multiple icons

---

packages/main/src/List.js
packages/main/src/ListItem.hbs
packages/main/src/ListItem.js
packages/main/src/themes/CheckBox.css
packages/main/test/pages/List.html
packages/main/test/pages/List_test_page.html
packages/main/test/specs/List.spec.js

Previously, clicking on list items with type="Inactive" in a List used to change selection in "SingleSelect" and "MultiSelect" modes. 
Now,  clicking on inactive items would not take effect. To change the selection you have to use list items with type="Active".
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1171

refactor(ui5-list): clicking inactive items doesn't change selection

---

packages/tools/lib/create-icons/index.js

Just a shot in the dark.
The only difference I found between the Button (working in CodeSandbox) and the Switch, MessageStrip and DatePicker (which does not), is that the last import icons.

chore: add export to icons to fix CodeSandbox

---

packages/main/src/ComboBoxPopover.hbs
packages/main/src/DatePickerPopover.hbs
packages/main/src/InputPopover.hbs
packages/main/src/MultiComboBoxPopover.hbs
packages/main/src/ResponsivePopover.js
packages/main/src/SelectPopover.hbs
packages/main/src/TabContainerPopover.hbs
packages/main/test/pages/ResponsivePopover.html
packages/main/test/specs/ResponsivePopover.spec.js

The `horizontalAlign` and `placementType` properties in the Popover have defaults `Center` and `Right`, but the ResponsivePopover (which extends the Popover) overwrites these defaults in its constructor (for the purposes of other components - Select, Input, ComboBox, DatePicker) to `Left` and `Bottom`.
Also, until know the "header" and the "footer" slots was not displayed on desktop.
As a result, the API reference displays the defaults, inherited from the Popover, but in reality they are implicitly overwritten or not working as expected.
Now the slots are displayed by default, unless the new protected API is not used - contentOnlyOnDesktop (for the purposes of other components - Select, Input, ComboBox, DatePicker)
And we keep the defaults, inherited from the Popover and set the needed …

refactor(ui5-responsive-popover): keep Popover defaults

---

packages/fiori/src/ShellBar.hbs
packages/fiori/test/pages/ShellBar.html
packages/fiori/test/specs/ShellBar.spec.js

On small sizes, the img tag, that represents the user logo is rendered in different place in the template, but the click handler was not attached and therefore on small sizes the logoClick event is not fired.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1188#

fix(ui5-shellbar): fire logoClick on small size

---

packages/main/src/TabContainer.js
packages/main/test/pages/TabContainer.html
packages/main/test/specs/TabContainer.spec.js

The tab index is provided as event details and don't have to be calculated by users, that otherwise have to consider the tab separators, which can be a little cumbersome.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1196
BREAKING CHANGE: `itemSelect` is renamed to `tabSelect` and the `item` event param is renamed to `tab`.

refactor(ui5-tabcontainer):  provide tabIndex in tabSelect event

---

packages/base/package.json
packages/fiori/index.js
packages/fiori/package.json
packages/icons/index.js
packages/icons/package.json
packages/main/index.js
packages/main/package.json

This PR removes ```type: "module"``` from packages.json files which causes the travis build to fail

fix(framework): fix travis build

---

packages/main/src/themes/TextArea.css
packages/main/test/pages/TextArea.html

- All themes and browsers: readonly textarea does not change its background on hover
- Quartz Dark and IE: the textarea has proper dark background, not a white one as used to.

fix(ui5-textarea): fix visual issues

---

packages/main/src/SegmentedButton.hbs
packages/main/src/SegmentedButton.js
packages/main/test/pages/SegmentedButton.html
packages/main/test/specs/SegmentedButton.spec.js

- Upon initial focus,
the focus should go to the selected button (if present) or to the first button.
- Otherwise, the focus should go to the previously focused button

refactor(ui5-segmentedbutton): focus selected button

---

packages/main/src/Tab.js
packages/main/src/TabContainer.hbs
packages/main/src/TabContainer.js
packages/main/src/themes/TabContainer.css
packages/main/src/types/TabLayout.js
packages/main/test/pages/TabContainer.html
packages/main/test/samples/TabContainer.sample.html

Fixes: https://github.com/SAP/ui5-webcomponents/issues/1195

feat(ui5-tabcontainer): add tabLayout property

---

packages/main/src/List.hbs
packages/main/src/List.js
packages/main/src/themes/List.css
packages/main/src/themes/base/List-parameters.css
packages/main/src/themes/base/sizes-parameters.css
packages/main/test/pages/List.html
packages/main/test/pages/List_test_page.html
packages/main/test/samples/List.sample.html
packages/main/test/specs/List.spec.js

- introduce infiniteScroll property, when set an event  "loadMore" will be fired when user scrolls to the very bottom of the list, then the user might load new items
- introduce "loadMore" event
- introduce "busy" property to display a loading indicator

feat(ui5-list): add infinite-scroll capability

---

packages/main/src/SegmentedButton.js
packages/main/src/themes/SegmentedButton.css

- correct cosy and compact height
- listen on resize of the parent, not on the body

fix(ui5-segmentedbutton): size adjustments

---

packages/main/src/themes/Switch.css

When there is a lot of content on the page, the switch animation may cause the browser to repaint everything. This creates a new context for the switch animated area only.

chore(ui5-switch): optimize animation

---

packages/main/src/Table.js

Ever since we removed the `deepEqual` metadata property, components are expected to handle object invalidation manually (to suppress invalidation if the object content did not change). This way the rows are not invalidated unnecessarily any more.

chore(ui5-table): do not invalidate all rows unnecessarily

---

packages/base/src/features/OpenUI5Support.js

We used to directly access the private `mData` property, but it's safer in the long run to use a `ui5-restricted` method instead.

chore: use the LocaleData.js _get() method

---

packages/base/src/UI5Element.js

- `_invalidated` was replaced with `_upToDate`
- all components start with `_upToDate = false`
- this way `getDomRef` is called less often

chore(framework): All elements start invalidated

---

packages/main/src/Carousel.js
packages/main/src/themes/Carousel.css

It is recommended and better for the performance to use transform: translate instead of transitioning the "left"

refactor(ui5-carousel): improve animation

---

docs/dev/Metadata.md
packages/base/src/UI5Element.js
packages/base/src/UI5ElementMetadata.js
packages/base/test/elements/Generic.js
packages/base/test/elements/Parent.js
packages/fiori/src/ProductSwitch.js
packages/fiori/src/ShellBar.js
packages/fiori/test/pages/Components.html
packages/main/src/Badge.js
packages/main/src/Card.js
packages/main/src/Carousel.js
packages/main/src/ComboBox.js
packages/main/src/FileUploader.js
packages/main/src/Input.js
packages/main/src/List.js
packages/main/src/MessageStrip.js
packages/main/src/MultiComboBox.js
packages/main/src/Panel.js
packages/main/src/Popover.js
packages/main/src/Popup.js
packages/main/src/SegmentedButton.js
packages/main/src/Select.js
packages/main/src/TabContainer.js
packages/main/src/Table.js
packages/main/src/TableRow.js
packages/main/src/Timeline.js
packages/main/src/Tokenizer.js

Most components that slot children don't base their own rendering on the presence/absence/state of their children, so it's unnecessary to have them wait for their children on first rendering, invalidate on children change, etc... Therefore slot support is off by default for all components. Components that really use their children should set `managedSlots` to `true` in their metadata.
BREAKING CHANGE: If your components need to access their children, you should set `managedSlots: true` in metadata. Otherwise slot accessors (such as `this.items`, `this.content`, etc...) will no longer work.

feature(framework): add managedSlots metadata entity

---

packages/base/src/UI5Element.js

This is a very slight performance improvement for pages with thousands of components. Managing one counter is cheaper than several.

chore(framework): Simplify IDs

---

packages/base/src/UI5Element.js
packages/base/src/UI5ElementMetadata.js

This is a performance optimization, because checking the metadata is much cheaper than iterating through all DOM children, and for most components this is unnecessary.
Note: Object.entries is used because Object.values does not exist in IE.

chore(framework): check for individual slots

---

packages/main/src/themes/Button.css

Setting smaller width to ui5-button makes its icon shrinking:
Setting flex-shrink: 0, preserves the icon size.

fix(ui5-button): fix icon shrinking

---

packages/main/src/Switch.hbs
packages/main/test/pages/Switch.html

This change is experimental. It adds 4 shadow parts to `ui5-switch`
- `slider` (on the -track div, note: it's not on the -slider div)
- `text-on` (text on span)
- `text-off` (text off span)
- `handle` (on the -handle div)
Two samples were added in the test page.

chore(ui5-switch): add shadow parts

---

packages/main/bundle.esm.js
packages/main/src/ComboBox.js
packages/main/src/ComboBoxItem.js
packages/main/src/MultiComboBox.hbs
packages/main/src/MultiComboBox.js
packages/main/src/MultiComboBoxItem.js
packages/main/src/MultiComboBoxPopover.hbs
packages/main/test/pages/ComboBox.html
packages/main/test/pages/InputsAlignment.html
packages/main/test/pages/MultiComboBox.html
packages/main/test/samples/ComboBox.sample.html
packages/main/test/samples/MultiComboBox.sample.html

BREAKING CHANGE: ui5-multi-combobox no longer accepts ui5-li for items. Use ui5-mcb-item instead.

feat(ui5-mcb-item): initial implementation

---

packages/fiori/src/ShellBar.hbs
packages/fiori/src/ShellBar.js
packages/fiori/src/themes/ShellBar.css
packages/fiori/test/pages/ShellBar.html
packages/fiori/test/specs/ShellBar.spec.js

- fix: search field suggestions popup used to open in the left most corner
- fix: clicking on suggestions did not take effect due to pop up reposition
Root cause: the search field used to close upon interaction with the items in the popover, forcing the popover to reposition itself without knowing the DOM ref of  its opener.
Solution: the search field is now toggled only by clicking the search icon.

fix(ui5-shellbar): fix search field behavior

---

packages/main/src/Button.hbs
packages/main/test/pages/Button.html

Sometimes it makes sense to have a button, much wider than its text, and be able to align the text and icon.

chore(ui5-button): button part exposed

---

packages/fiori/.npmignore
packages/icons/.npmignore
packages/main/.npmignore
packages/theme-base/.npmignore

This PR removes the generated api.json from the `.npmignore` files. With the help of that file, the UI5 Web Components for React can more easily generate the wrapper components.

chore: Remove api.json from .npmignore files

---

packages/base/src/UI5Element.js
packages/base/src/UI5ElementMetadata.js
packages/main/src/Panel.js
packages/main/src/Popover.js
packages/main/src/Popup.js
packages/main/test/pages/Panel.html

Background: the Mutation Observer needs `subtree` only for the purpose of detecting changes to text nodes. `childList` will trigger the Mutation Observer if new text nodes are added/removed, but it will not if an existing text node is changed by `nodeValue` assignment. Therefore `subtree` is required to efficiently track whenever the text inside a component changed. This is relevant if a component for example renders differently based on the presence of text or the length of the text.
It is safe to remove `subtree` for all components that do not slot text, as they either don't care about changes to their children (but do care about new children are added/removed), or they use `listenFor`.
In addition to the change, some often used containers' default slots were changed to `HTMLElement` …

chore(framework): improve Mutation Observer performance

---

packages/main/src/Input.js
packages/main/src/InputPopover.hbs
packages/main/src/features/InputSuggestions.js
packages/main/test/specs/Input.spec.js

Fix exceptions thrown when keyboard handling is used. When the input has suggestions, moving up/down throws exception in few cases: always when the suggestions popup is closed and always when it is opened and tries to bring an item into view
- fix: the ScrollContainer (that moves the item into view) used to throw exceptions
- fix: handle UP/DOWN when the suggestions are opened, otherwise we prevent the default behaviour - bringing the cursor to the start/end of the input text
- fix: the icons of the items are not displayed

fix(ui5-input): fix exceptions thrown when KH used

---

packages/main/src/ResponsivePopover.js
packages/main/test/pages/Dialog.html
packages/main/test/pages/Popover.html
packages/main/test/pages/ResponsivePopover.html

**Issue**
- when a component, that opens a dialog on phone, such as Select, DatePicker, ComboBox, MultiComboBox is opened within Dialog, it remains invisible, because the Dialog remains on top.
- when such component opens a dialog on phone, all icons on the page are visible, but should not
**Solution**
set z-index on the ui5-responsive-popover tag (on desktop it relies on the ui5-popover to handle that)

fix(ui5-responsive-popover): set z-index on phone

---

packages/main/src/themes/Tokenizer.css

Ensure no horizontal scrollbar would appear and always align tokens so the last one is completely visible
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1304

fix(ui5-multi-cbx): remove horizontal scrollbar

---

packages/main/src/themes/BusyIndicator.css
packages/main/test/pages/BusyIndicator.html

Currently if the user does not set the "size" property, the indicator (animated dots) will not not be displayed, but should be displayed as "size=Large", which is the default value of the "size" property.
Now the following markup works and displays the animated dots as expected:
```html
<ui5-busyindicator active></ui5-busyindicator>
```

fix(ui5-busyindicator): display animated dots as size=Large by default

---

packages/main/src/Toast.js
packages/main/test/specs/Toast.spec.js

Toast used to modify its public API in `onBeforeRendering`, leading to an infinite loop of property-attribute-property-... conversion when the user sets a value below the allowed. Now it just uses `effectiveDuration` without touching what the user set.
In addition, some constants/getters were simplified a bit.

fix(ui5-toast): infinite loop prevented

---

packages/main/src/ComboBox.js
packages/main/src/DatePicker.js
packages/main/src/Input.js
packages/main/src/MultiComboBox.js
packages/main/src/Select.js
packages/main/src/Token.js

Several components did not import their respective icons and didn't look correctly unless the whole icons `Assets.js` file was imported by chance.

fix(main): add missing icons

---

packages/tools/components-package/nps.js
packages/tools/icons-collection/nps.js

I had issues building the project because the path contained spaces.
This fix puts paths in quotes to allow build on paths with space.
Signed-off-by: Michael Sprauer <Michael.Sprauer@sap.com>

chore(framework): support build env with space in path

---

packages/main/bundle.esm.js
packages/main/src/Input.js
packages/main/src/InputPopover.hbs
packages/main/src/SuggestionItem.js
packages/main/src/features/InputSuggestions.js
packages/main/src/themes/GroupHeaderListItem.css
packages/main/test/pages/Input.html
packages/main/test/samples/Input.sample.html

An abstract item to serve as a suggestion item within the Input. Based on the suggestion item properties, the Input will display either a StandardListItem, or a GroupHeaderListItem within the suggestion popover.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1313
The usage becomes:
```html
<ui5-input id="myInput2" show-suggestions >
<ui5-suggestion-item group text="group 1"></ui5-suggestion-item>
<ui5-suggestion-item text="Cozy"></ui5-suggestion-item>
<ui5-suggestion-item text="Compact"></ui5-suggestion-item>
<ui5-suggestion-item text="Condensed"></ui5-suggestion-item>
</ui5-input>
```
Although this is still compatible:
```html
<ui5-input  show-suggestions >
<ui5-li>Cozy</ui5-li>
<ui5-li>Compact</ui5-li>
<ui5-li>Condensed</ui5-li>
</ui5-input>
```

feat(ui5-suggestion-item): add new component

---

packages/main/src/GroupHeaderListItem.js
packages/main/src/Input.js
packages/main/src/ListItem.js
packages/main/src/ListItemBase.js
packages/main/src/SuggestionItem.js
packages/main/src/features/InputSuggestions.js
packages/main/src/themes/ListItem.css
packages/main/src/themes/ListItemBase.css
packages/main/test/pages/Input.html
packages/main/test/specs/Input.spec.js

Couple of improvements in handling a group item within the suggestion popover:
- When navigating via the keyboard over a group item, the text in the input field should be cleared
- However, the group item should also have the selection visual, when reached via the keyboard, but it can not be selected neither with the keyboard, nor with a click

refactor(ui5-input): improve group suggestion item handling

---

packages/main/src/BusyIndicator.js
packages/main/src/themes/BusyIndicator.css
packages/main/test/pages/BusyIndicator.html

- adjust stylings to latest spec
BREAKING CHANGE: Medium size is now default
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1337

fix(ui5-busyindicator): prevent dots blur on Safari

---

packages/base/src/UI5Element.js

Firefox 74 seems to have a bug regarding shadow root creation. Even though `attachShadow` is called in the constructor, `this.shadowRoot` is still `null` in `connectedCallback`. If you try to create it again there, it fails, as it was already created, it's just not available yet. Therefore with `managedSlots: true` it works, as there is async work going on, and the `shadowRoot` is ready when rendering. 
The fix is to await a microtask, if there is no shadow root in `connectedCallback` and `needsShadowRoot` is equal to `true`.

fix(framework): Provide a workaround for Firefox 74 shadow root bug

---

packages/main/src/TabContainer.hbs
packages/main/src/themes/TabContainer.css
packages/main/src/themes/base/sizes-parameters.css

- size of text-only and text-only + count should be the same in cozy and compact
- overflow button is transparent by design
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1358

fix(ui5-tabcontainer): fix sizes on compact

---

packages/main/src/themes/Input.css

The hover state used to be wrong, when the date picker is readonly.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1354

fix(ui5-datepicker): fix hover bg-color when readonly

---

packages/main/src/Carousel.js

These icons are used in Carousel.hbs

fix(ui5-carousel): add missing icon imports

---

packages/tools/lib/init-package/resources/src/Assets.js

The `localization` package is not a dependency of the demo project, but its `Assets.js` is imported, breaking the build. Instead of making it a dependency, just remove the import. CLDR assets are not needed by the demo project.

chore(tools): Remove the unnecessary Assets.js import

---

packages/main/src/BusyIndicator.js

docs(ui5-busyindicator): use 'Medium' as default size

---

docs/Configuration.md
docs/Public Module Imports.md
packages/main/README.md
packages/main/src/Avatar.js
packages/main/src/Calendar.js
packages/main/src/Carousel.js
packages/main/src/DatePicker.js
packages/main/src/DayPicker.js
packages/main/src/Dialog.js
packages/main/src/Input.js
packages/main/src/MonthPicker.js
packages/main/src/Tab.js
packages/main/src/TabContainer.js
packages/main/src/TimelineItem.js
packages/main/src/YearPicker.js
packages/playground/Gemfile.lock
packages/playground/_layouts/sample.html

- add sap_belize_hcw switch
- provide public imports for the newly added components
- unify type naming - in most of the places we use "boolean" and "string", but in several palces we can see "Boolean" and "String"

chore: add  sap_belize_hcw switch, public imports and other stuff

---

packages/main/src/Avatar.js
packages/main/src/Calendar.js
packages/main/src/CheckBox.js
packages/main/src/ComboBox.js
packages/main/src/DatePicker.js
packages/main/src/DayPicker.js
packages/main/src/FileUploader.js
packages/main/src/Input.js
packages/main/src/Link.js
packages/main/src/List.js
packages/main/src/ListItem.js
packages/main/src/MessageStrip.js
packages/main/src/MonthPicker.js
packages/main/src/MultiComboBox.js
packages/main/src/RadioButton.js
packages/main/src/Select.js
packages/main/src/StandardListItem.js
packages/main/src/SuggestionItem.js
packages/main/src/Tab.js
packages/main/src/TabContainer.js
packages/main/src/TimePicker.js
packages/main/src/TimelineItem.js
packages/main/src/Title.js
packages/main/src/Toast.js
packages/main/src/YearPicker.js

In several places, `string` was used as `@type` annotation for the documentation. This PR is replacing those string annotations with the corresponding enums.

docs: use enum type instead of string

---

packages/main/src/Carousel.hbs
packages/main/src/Carousel.js
packages/main/src/themes/Carousel.css
packages/main/test/pages/Carousel.html
packages/main/test/specs/Carousel.spec.js

When the user shrinks the Carousel a lot, items overlap each other and items from other pages also appear from the sides and overlap the currently visible items. The goal of this change is to provide items fixed-size containers with pre-calculated widths and space these containers evenly.
Changes:
- rename `items` to `pages` in the names of variables/CSS classes
- introduce `items` - divs around the slots that have calculated width (100% / number of items per page),  `100% height` and margins, so that the content may not go out of its boundary and looks tidy even when you shrink the carousel.
- do not modify the public API (`itemsPerPage`) in `onBeforeRendering` but use `effectiveItemsPerPage` everywhere instead
- When to the side, navigation arrows used to be positioned at `50%` which …

fix(ui5-carousel): Content now shrinks properly

---

packages/main/src/TextArea.js
packages/main/src/themes/TextArea.css

The property works as in the ui5-input, with one note:
If maxlength property is set, the component turns into "Warning" state once the characters exceeds the limit. In this case, only the "Error" state is considered and can be applied.
Resource: [TextAreaUX](https://experience.sap.com/fiori-design-web/text-area/)

feat(ui5-textarea): add "valueState" property

---

packages/main/src/themes/Input.css
packages/main/src/themes/TextArea.css
packages/main/src/themes/base/Input-parameters.css

Enable users to change the font-style of the text in the input and textarea.
It's a recent requirement by the "MDK" project, that consume us.

refactor(ui5-input, ui5-textarea): enable "font-style" overstyling

---

packages/main/src/Carousel.hbs
packages/main/src/Carousel.js
packages/main/test/pages/Carousel.html
packages/main/test/specs/Carousel.spec.js

The navigation arrows and page indicator bar should be hidden when there is
a single page displayed within the Carousel.Reported by the "MDK" users.

fix(ui5-carousel): hide arrows and dots when single page

---

packages/main/src/Select.js

When the parent container has scrollbar, pressing SPACE activates scrolling by default
and the Select have to prevent it.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1412

fix(ui5-select): prevent scrolling on SPACE

---

packages/main/src/TextArea.js

Problem: I found out that pressing TAB or SHIFT+TAB from a TextArea with valueStateMessage popover opened is not possible, due to the focus restoring mechanism of the popover, that brings the focus back to the TextArea.
Solution: use the 3rd param of Popover.prototype.close as follows: popover.close(false, false, true /*preventFocusRestore*/)

chore: fix TextArea  TAB/SHIFT+TAB  interaction

---

packages/main/src/TimePicker.js
packages/main/test/pages/TimePicker.html
packages/main/test/specs/TimePicker.spec.js
packages/tools/components-package/wdio.js

- Fixes the issue: when the user clears the input of the TimePicker, value-state="Error' is set, but should not as empty value is allowed and valid (this is how it works in openui5). And, the user also gets "change" event and he/she always can set  "Error" state when encounter an empty value.
- Refactors the TimePicker tests entirely, as they used to depend on some hardcoded ids that change whenever we add new TimePicker components in the test page.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1398

fix(ui5-timepicker): prevent setting valueState="Error" on empty value

---

packages/main/src/Carousel.hbs
packages/main/src/Carousel.js
packages/main/test/pages/Carousel.html

`ui5-carousel` is now size-aware:
- uses a `ResizeHandler`
- `itemsPerPage` replaced by `itemsPerPageS`, `itemsPerPageM` and `itemsPerPageL`. They all have default value of `1` so a plain `ui5-carousel` without any properties set will behave as before. The user can now increase the number of items for different screen sizes separately. Since the default value for `itemsPerPageS` is  `1`, no special logic is needed for phone any more.
- `cycling` renamed to `cyclic` as this is the correct adjective
BREAKING CHANGE:
The `cycling` property was renamed to `cyclic`.
The `itemsPerPage` property was replaced by 3 new properties:  `itemsPerPageS`, `itemsPerPageM` and `itemsPerPageL`. To achieve exactly the same result as before, set `itemsPerPageM` and `itemsPerPageL` to whatever the value of …

feat(ui5-carousel): Allow different number of items per page based on component width

---

packages/fiori/src/upload-utils/UploadCollectionBodyDnD.js

In Internet Explorer event.dataTransfer.types is DOMStringList,
which doesn't implement the "includes" method.

fix(ui5-upload-collection): ensure event.dataTransfer.types is array

---

packages/fiori/src/ShellBar.js

When `profile` was turned into a slot, the check whether there is a profile element provided, remained `this.profile` which is always truthy for a slot (since it's an array). 
Additionally, the line `show: this.profile` which is supposed to be a Boolean, became an array, holding a reference to the `ui5-avatar` instance that the user passed, making it fail when transformed into `JSON` for the purpose of object comparison.
The fix is to check whether the avatar array is not empty.
closes: https://github.com/SAP/ui5-webcomponents/issues/1427

fix(ui5-shellbar): check for profile correctly

---

packages/base/src/StaticAreaItem.js
packages/base/src/UI5Element.js
packages/base/src/theming/createComponentStyleTag.js

The `createComponentStyleTag` method did not take into account Static Area CSS and did not inject it in the head. Instead, this CSS went to the `ui5-static-area-item` like on normal browsers. However, it wasn't processed there so CSS vars were not replaced.
The fix:
- Do not inject any CSS in `_updateFragment` for IE11 (if `shadyDOM` is `true`). 
- Inject the static area CSS along with the normal CSS in `createComponentStyleTag` instead, where it will be processed like the regular CSS
- Finally, add a static getter for static area CSS in `UI5Element.js` to ensure it's always a string.

fix(framework): CSS Vars in Static Styles work on IE11

---

packages/main/src/Popover.js

fix(ui5-popover): allow opening if opener is not fully visible

---

packages/base/src/UI5Element.js
packages/fiori/src/ShellBar.js

The `_menuPopoverItems` metadata property had a wrong type and a wrong default value. When the default value is an object, in this case `[]`, whenever there is a type mismatch, the default value is returned: `return propDefaultValue;` in `UI5Element.js`. However, if the default value is an object, it's passed by reference and when the components work with it (f.e. push items as is here), the `defaultValue` is updated every time. Thus items are duplicated again and again.
In addition, to prevent this from happening in the future, some more metadata checks are added:
- `type` can no longer be `Array`
- properties of `type` equal to `Object`, or with `multiple: true`, cannot have a default value at all. The default value can only be `{}` or `[]` respectively, and provided by the framework. …

fix(ui5-shellbar): do not duplicate popover menu items

---

packages/fiori/src/ShellBar.js
packages/fiori/src/ShellBarPopover.hbs
packages/fiori/test/pages/ShellBar.html
packages/fiori/test/specs/ShellBar.spec.js

We used to just copy the text of the menuItems within the Light DOM of the ui5-shellbar, and not only the attributes of those items are missing, but also we don't update the internal items whenever the original ones change. For example: if the textContent change - it is not applied to the internal one. Adding a mutation observer keeps everything in sync. Currently we can not just forward the outside slot to the List, that is inside a Popover, that is in the static area.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1442

fix(ui5-shellbar): fix menuItems cloning

---

packages/base/src/asset-registries/Themes.js

Support registration of theme parameters (css vars) via URL to a CSS file.

feat(framework): register theme variables via CSS file

---

packages/main/src/Popover.js
packages/main/test/pages/Popover.html

**Issue**
When the opener element is taking full width and the placement is set to "Right" (same for "Left"), the popover tried to open on the opposite side, but both sides are not possible and the popover remains cut off with only its arrow visible.
**Solution**
Now, it checks "Bottom" and "Top" sides as well. 
**Note1:** The fallback is applied before the allow-target-overlap to be taken into account, which means that Popover with placement "Right" or "Left", will try to open on all sides, before overlapping its target.
**Note2:** The fallback is used currently for "Left" and "Right' only for two reasons: (1) it fixes the issue that was originally reported by the MDK colleagues and (2) all the components, that use popover internally (f.e DatePicker) have placement="Bottom" and the …

fix(ui5-popover): set fallback placement when no place to popup

---

packages/main/src/DatePicker.js

**Background**
If there is value in the input field and the user removes that value,
the component sets "value-state=error" and fires "change" and "input" events with "valid: false" and this is not correct - empty input field should be a valid state.
**Note**: there is a method, called "isValid", but I did not add the check for empty value in that method by purpose, because it is used in a lot of places, where (if valid) the value is parsed or formatted  and would throw errors on empty string, and I would need to make more changes to handle that. So this "isValid" is more like is the value valid for the given format.

fix(ui5-datepicker): fix the value validation

---

packages/fiori/src/ShellBar.hbs
packages/fiori/src/ShellBar.js
packages/fiori/src/themes/ShellBar.css
packages/fiori/test/specs/ShellBar.spec.js

**Fixes**
- Enable moving between all focusable items in she ShellBar with TAB and SHIFT + TAB
- all actions can be now triggered with SPACE or ENTER
**Background**
All ui5-icon elements now become ui5-button, the ui5-button has tabindex=0 and also can be triggered with SPACE and ENTER. To ensure the correct tab order, the layout of the items is changed in such way that their DOM order is the same as their display order.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/860

fix(ui5-shellbar): enable items keyboard handling

---

packages/main/src/Dialog.hbs
packages/main/src/Popup.hbs

The footer was missing its role="toolbar" attribute, the "h2" tag does not need a role="heading" and 
change "section" tag  to achieve proper acc landmark for the footer and the header.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1466

fix(ui5-dialog): improve accessibility

---

packages/main/src/SegmentedButton.hbs
packages/main/src/SegmentedButton.js
packages/main/src/i18n/messagebundle.properties
packages/main/src/themes/SegmentedButton.css

fixes: https://github.com/SAP/ui5-webcomponents/issues/1286

feat(ui5-segmentedbutton): implement accessibility spec

---

packages/main/src/MessageStrip.hbs
packages/main/src/themes/MessageStrip.css

- fix type="Information" appearance, by setting the correct variables, previously the "neutral" semantic variables has been used
- fix the icons colours in all types, they used to remain grey (their default color), instead of being in the respective semantic color according to the component type
Before
After
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1496

fix(ui5-messagestrip): fix component visual

---

packages/main/src/Panel.hbs
packages/main/src/Panel.js
packages/main/src/themes/Panel.css
packages/main/src/themes/base/Panel-parameters.css
packages/main/src/themes/sap_fiori_3/Panel-parameters.css
packages/main/src/themes/sap_fiori_3_dark/Panel-parameters.css
packages/main/test/pages/Panel.html
packages/main/test/specs/Panel.spec.js

**Background**
Our native title used to be "h1", which is indeed wrong. In openui5 it is "h2" and it is not configurable. But, in the related issue the author wants to be able to change the title level in general. Although we provide the possibility of a custom header, the author is asking for this feature to make use of the fact that the the entire native header is clickable and focusable, which is not the case with the custom one.
**Options**
So, we either reject this and (1) hardcode it to "h2" as in openui5, (2) introduce a property as in this change, or (3) make another slot for the title, but then we will have the current "header" slot and "headerTitle" slot and it might be confusing.
**In this change:**
- [refactoring] Use div with role="heading" and "aria-level" attrs, instead of …

feat(ui5-panel): enable configuring the heading level

---

packages/main/src/themes/BusyIndicator.css

The opacity of 0.6 used to apply to the busy indicator inter elements in IE due to the absence of shadow DOM, also the position of the circles used to be wrong. Both the visual and the placement is now fixed.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1497
Now in IE:
Previously in IE:

fix(ui5-busyindicator): fix component placement and appearance in IE

---

packages/main/src/BusyIndicator.hbs
packages/main/src/BusyIndicator.js
packages/main/src/themes/BusyIndicator.css
packages/main/src/themes/Label.css
packages/main/test/pages/BusyIndicator.html

feat(ui5-busyindicator): implement text property

---

packages/base/src/delegate/ScrollEnablement.js
packages/main/src/Carousel.hbs
packages/main/src/Carousel.js
packages/main/src/i18n/messagebundle.properties
packages/main/src/themes/Carousel.css
packages/main/test/pages/Carousel.html
packages/main/test/samples/Carousel.sample.html
packages/main/test/specs/Carousel.spec.js

- [ Refactor ] Previously entire page of items is being moved in and out of the view during navigation. Now, the items are moved in and out the visible area one by one, in other words all the items are shifted to the left and to the right by one.
- [ New Implementation ] Initial accessibility spec is implemented (as in openui5), but can be further improved as it does not handle the multiple items per page case the best way.
- [ Bug Fix ] Previously the navigation arrows were remaining displayed, although no previous or next item is available and pressing the arrows didn't perform any action. Now, the arrows remain hidden if no previous/next item is available to navigate towards.
- [ Bug Fix ] Previously the navigation arrows have been misplaced in IE, making the component not usable at …

refactor(ui5-carousel): rework component behaviour

---

packages/main/src/Select.hbs
packages/main/src/Select.js
packages/main/src/themes/Select.css

feat(ui5-select): implement accessibility spec

---

packages/main/src/Avatar.hbs
packages/main/src/Avatar.js

feat(ui5-avatar): implement accessibility spec

---

packages/theme-base/package-scripts.js
packages/tools/components-package/nps.js
packages/tools/lib/generate-json-imports/i18n.js
packages/tools/lib/generate-json-imports/themes.js
packages/tools/lib/i18n/defaults.js
packages/tools/lib/i18n/toJSON.js

This PR adds `src` and `dest` parameters to the `generate-json-imports` scripts and generates the required parent folders for i18n assets during the script execution.

chore(tools): enhance i18n json imports scripts

---

packages/tools/lib/i18n/defaults.js

**Background**
The Translation Delivery pull request fails and I found out that one of the new texts in messagebundle_en.properties has has quoted word  `Drop files to upload them or use the "Upload" button `.
**Issue:**
Later when building the i18n-defaults.js, the following fails:
```js
// effectiveValue  has double quotes itself and a word inside with double quotes in addition
return `const ${key} = {key: "${key}", defaultText: "${effectiveValue}"};`;
```
**Solution**: escaping those quotes.

fix(build): escape quotes in translation texts

---

packages/tools/lib/i18n/defaults.js

Sorry, technical mistake, the new value after the replace was never used, now it is correct.

chore: use the changed value

---

packages/main/src/MultiComboBox.js
packages/main/src/MultiComboBoxPopover.hbs

Before this change, when opened the initial focus of the ```ui5-multi-combobox``` on mobile was still on the native input out of the dialog. This breaks the whole view as the input can be anywhere on the page. With this change the focus is now set on the input inside the dialog
It is implemented like this(and not using the initial-focus API of the popover), because on both Chrome and Safari the bug is still present.

fix(ui5-multi-combobox): fix initial focus on mobile

---

packages/main/src/Carousel.hbs
packages/main/src/Carousel.js
packages/main/test/pages/Carousel.html
packages/main/test/specs/Carousel.spec.js

The event is fired whenever the selectedIndex changes due to user interaction - when the user clicks on the navigation arrows or while resizing, based on the "items-per-page-s/m/l" properties.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1449

feat(ui5-carousel): add navigate event

---

packages/main/src/DateTimePicker.js

DateTimePicker's  icon background blinks on open (look at the video). 
Calling super.openPicker first resolves the issue as the pressed state of the icon is immediately set upon click, otherwise it is clicked, released and then the pressed state is set, causing that blinking.

chore(ui5-datetime-picker): fix icon blinking on open

---

packages/main/src/TabContainerPopover.hbs

The overflow list should not have a header with close button, when opened in phone as dialog

chore(ui5-tabcontainer): hide header in overflow dialog

---

packages/base/src/CustomElementsRegistry.js
packages/base/src/RenderScheduler.js
packages/base/src/UI5Element.js

- When there are not-imported UI5 Elements on the page, each rendering cycle is delayed by 5 seconds, making the whole page unresponsive. This is an extract from this pull request: https://github.com/SAP/ui5-webcomponents/pull/1308 :
- All elements are registered centrally (so not only `UI5Element.js` can access this information)
- `RenderScheduler.js` no longer guesses which elements are UI5 Elements, but reads this from the registry, and no longer waits for 5 seconds. If an element is imported, its awaited until it's defined.
- Additionally the `whenShadowDOMReady` function was renamed as its name was misleading.
As a result of this change, it's now possible to have UI5 Elements that don't start with `ui5-`.
closes: https://github.com/SAP/ui5-webcomponents/issues/1537

fix(framework): rendering is no longer delayed 

---

packages/main/test/specs/ComboBox.spec.js
packages/tools/lib/hbs2lit/src/litVisitor2.js

In the `lit-html` `repeat` directive, the key function is defined as follows:
`export type KeyFn<T> = (item: T, index: number) => unknown;`
It takes 2 arguments: `item` and `index` and the usage is as follows:
`newKeys[index] = keyFn ? keyFn(item, index) : index;`
We pass `undefined` to our `repeat` in `litVisitor` class. Therefore `lit-html` takes the `index` as key.
The purpose of this change is to pass the `_id`, which is unique to every UI5 Web Component, and the `index` as fallback, so that the algorithm works as before when there are no `_id`s (f.e. when we don't iterate on arrays of UI5 Web Components).
This will optimize the rerendering of lists of UI5 Web Comopnents and also prevent some bugs, such as the filtering of items in `ui5-multi-combobox`.
fixes: …

fix(framework): reliably re-render lists of DOM nodes

---

packages/main/src/TextArea.hbs
packages/main/test/pages/TextArea.html

The MDK colleagues requested a way to change the bg-color of the TextArea.
But, the TextArea has relatively complex structure and setting background on the "host" would affect the exceeded text under the native textarea. Introducing a "part" attribute will enable users to change inner textarea background.

chore(ui5-textarea): add "part" to inner textarea

---

packages/main/src/TabContainer.js

With the standard `ui5-tab` the `click`, `keydown` and `keyup` events are always fired with the tab itself as the event target due to the specific markup we use, but when extending the tab and providing your own implementation, the event target might be different.
Therefore, the TabContainer first needs to determine the tab (which could be in the parent chain) and can only then proceed with the normal eventing logic.

fix(ui5-tabcontainer): clicking a tab now always works

---

packages/main/src/TextArea.js
packages/main/src/TextAreaPopover.hbs
packages/main/test/pages/TextArea.html
packages/main/test/specs/TextArea.spec.js

Previously if value state msg slot is set, it used to be displayed in all value states.
But, by spec the no matter as slot or built-in text, the value state message should be displayed in Error, Warning and Information states only.

fix(ui5-textarea): stop showing valueStateMsg in value-state="None"

---

packages/main/src/TimePicker.js

Fix period selection. Previously selecting "PM" results in "AM" within the input field and vice verca.

fix(ui5-timepicker): fix AM/PM selection

---

packages/main/src/themes/Icon.css

WebView user agent stylesheet sets document as:
transform-origin: 0px 0px 0px
As a result all icons as displaced
This is to support usage of WebComponents on Android devices.

refactor(ui5-icon): Overwrite WebView user agent stylesheet

---

packages/fiori/src/ShellBar.hbs
packages/fiori/src/ShellBar.js
packages/fiori/src/ShellBarPopover.hbs
packages/fiori/src/i18n/messagebundle.properties
packages/fiori/src/themes/ShellBar.css
packages/main/src/Button.hbs
packages/main/src/Button.js

Implemented accessibility spec of the ShellBar. In addition some minor issues are fixed:
- Now, primary-title is displayed in menu button when logo is not provided.
- Now, empty image tags are not rendered when src is not provided.
#1289

feat(ui5-shellbar): implement accessibility spec

---

packages/main/src/ListItem.js
packages/main/src/StandardListItem.hbs

Since most of the list items are of `type` `active` by default, it is redundant to have the screen reader repeat the word "Active" so many times. It's simpler to only read "Inactive" or "Detail" for the items of these two types.

fix(ui5-li): Do not announce active list item type

---

packages/tools/lib/hbs2lit/src/compiler.js
packages/tools/lib/hbs2lit/src/includesReplacer.js

- lookup for include statements in the hbs files used to be just
one level above the class.

fix(hbs2ui5): enables 3 or more levels of inheritance with templates

---

packages/fiori/src/themes/ShellBar.css
packages/main/src/themes/Button.css
packages/main/test/pages/Button.html

The text of a button should truncate if it is longer than the button(if width is set). Before this change it was wrapping.
Related to: #1400

fix(ui5-button): make buttons truncate

---

packages/main/src/Icon.hbs
packages/main/src/Icon.js
packages/main/src/themes/Icon.css
packages/main/test/pages/Icon.html
packages/main/test/specs/Icon.spec.js

feat(ui5-icon): introduce interactive property

---

packages/fiori/src/NotificationListGroupItem.js
packages/fiori/src/NotificationListItem.js
packages/fiori/src/NotificationListItemBase.js
packages/fiori/src/UploadCollectionItem.js
packages/main/src/ComboBox.js
packages/main/src/CustomListItem.js
packages/main/src/DatePicker.js
packages/main/src/DateTimePicker.js
packages/main/src/GroupHeaderListItem.js
packages/main/src/ListItem.js
packages/main/src/ListItemBase.js
packages/main/src/MultiComboBoxItem.js
packages/main/src/ResponsivePopover.js
packages/main/src/StandardListItem.js
packages/main/src/TabContainer.js
packages/main/src/TimePicker.js
packages/main/src/ToggleButton.js
packages/main/src/TreeListItem.js

Several changes:
- In `static get styles()` and `static get staticAreaStyles()` the order of CSS files matters. The base class CSS/static area CSS should always come first so that the more specific child component CSS overrides it (and not the other way round). Some components currently load these in the wrong order, but as far as I could find out, there were not any duplicate selectors.
- For components that extend other components (not `UI5Element.js`) it is unneeded to specify `static get render` as it was specified in the parent already.
- If a component does not have its own CSS, it is not necessary to have `static get styles()` and return the CSS of its parent component, because this is already there on the inheritance chain.

chore: cleanup static class members

---

packages/main/src/Input.hbs

Adds a template hook to allow components,  extending the Input to add content, positioned right before the input field. The use case is an ui5-input, used as a search field that needs to show a "transitive search" info, the category that the users search in. For more info see the related issue.
Related to: https://github.com/SAP/ui5-webcomponents/issues/1588

refactor(ui5-input): add template hook

---

packages/main/src/List.js
packages/main/test/pages/List_test_page.html
packages/main/test/specs/List.spec.js

We used to fire the "itemClick" and "itemPress" before the selection finishes and if someone gets the "event.detail.item.selected" - it is will be the old one. 
Now, they are fired after the selection finishes and provide the correct "item" state, although it is not common to listen for  "itemClick" in selection modes, but rather for "selectionChange".
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1615

fix(ui5-list): fire itemClick after the selection

---

packages/main/src/TableRow.hbs

There are use cases when a column does not have a title at all, hence no popin text is set for it either. However, if this is the case, the colon symbol (`:`) always stays alone on a single line above the value.

fix(ui5-table-row): Do not show the colon when there is no popin text

---

packages/main/src/TabContainer.js

The TabContainer now toggles with animation.
Related to: https://github.com/SAP/ui5-webcomponents/issues/1540

feat(ui5-tabcontainer): add expand/collapse animation

---

packages/main/src/Popover.js

The popover used to position itself according to 0, 0, 0 ,0 coordinates after the opener is being removed from the DOM. Now, it closes.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1571

fix(ui5-popover): close popup when no opener

---

packages/main/src/Input.hbs
packages/main/src/Input.js
packages/main/test/specs/Input.spec.js

The Input with type="Number" now behaves as the sap.m.Input when it comes to incrementing/decrementing the value.
Previously it used to round the value to the next Integer (2.14 to 2 or 3), now it increments or decrements the value by 1 (2.14 to 1.14 or 3.14).
Related to: https://github.com/SAP/ui5-webcomponents/issues/1637

refactor(ui5-input): define increment step for type="Number"

---

packages/fiori/src/ShellBar.js
packages/fiori/test/pages/ShellBar.html
packages/fiori/test/specs/ShellBar.spec.js
packages/main/src/Input.js

**Issue**: the valueStateMsg popover does not show up when the user clicks on the search icon.
**Root cause**: the ShellBar uses a timeout to focus the input to ensure it is displayed and ready to be focused, but sometimes the timeout executes too late. 
- First, the Iinput checks (onAfterRendering) if it should show a valueStateMessage and one of the requirements is to be on focus, which is still false (the timeout is called later) and does not show the popover.
- Then, the timeout is called, moves the focus to the input, but it does not trigger re-rendering and the popover does not show up.
**Solution:** update the state (Input "focused" property) immediately, keep the focus move delayed.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1590

fix(ui5-shellbar): fix search field focus handling

---

packages/fiori/src/ShellBar.js
packages/fiori/test/pages/NotificationListGroupItem.html
packages/fiori/test/pages/NotificationListItem.html
packages/fiori/test/pages/ShellBar.html
packages/fiori/test/samples/NotificationListGroupItem.sample.html
packages/fiori/test/samples/NotificationListItem.sample.html
packages/fiori/test/samples/ProductSwitch.sample.html
packages/fiori/test/samples/ShellBar.sample.html
packages/fiori/test/specs/ShellBar.spec.js

The built-in notification icon can overflow and if you try to open another popover by clicking on the corresponding list item within the overflow, it does not open as the provided targetRef is not correct. 
Now it provides the correct targetRef, considering whether the notification icon is in or out of the overflow. In addition, all samples and test pages that opens popover from the notification icon use event.preventDefault() to prevent the overflow popover from closing.

fix(ui5-shellbar): fix open popup on notificationClick

---

packages/base/src/asset-registries/Themes.js

It is valid for a theme parameters file to be empty (no parameters for this theme). However, `Theming.js` did not account for this and in both registering and getting a theme.
closes: https://github.com/SAP/ui5-webcomponents/issues/1599

fix(framework): allow for empty theme files

---

packages/main/src/Label.hbs
packages/main/src/Label.js
packages/main/src/themes/Label.css
packages/main/test/pages/Label.html

fix(ui5-label): fix width for italic labels

---

packages/fiori/src/themes/ShellBar.css
packages/fiori/test/pages/ShellBar.html

FIXES: https://github.com/SAP/ui5-webcomponents/issues/1640

fix(ui5-shellbar): fix search field visual in IE

---

packages/tools/components-package/nps.js
packages/tools/icons-collection/nps.js
packages/tools/lib/copy-and-watch/index.js
packages/tools/package.json

The problem: `copy-and-watch` internally uses `chokidar` to watch files, but provides no interface for setting `chokidar`'s options. One of these options is `awaitWriteFinish` which makes `chokidar` fire `add` and `change` events only when the file is no longer being written (as opposed to when the file starts being written). This ensures that `rollup` does not try to bundle files that are not completely copied to `dist/`.
The solution: fork `copy-and-watch` to our `lib/` in the `tools` package and add a `safe` option that forces `chokidar` to use `awaitWriteFinish`. We can revert to the original `copy-and-watch` if such a feature gets added sometime in the future.
fixes: https://github.com/SAP/ui5-webcomponents/issues/1634

chore(tools): blank files are no longer copied to dist

---

packages/main/src/TableCell.hbs
packages/main/src/TableColumn.hbs
packages/main/src/TableRow.hbs
packages/main/src/themes/TableColumn.css
packages/main/src/themes/TableRow.css
packages/main/test/pages/TableCustomStyling.html

Currently the user has no control over **size** and **positioning** for `ui5-table-column`, `ui5-table-row` and `ui5-table-cell`.
This change exposes shadow parts that make it possible to control these settings. 
Additionally, the Table Column must be one element only in order for the positioning to work, so the nested `div` is removed.
*Important*: exposing these shadow parts to a large extend binds us to using `th`, `tr` and `td` as people will start setting CSS properties that work on their respective `display` modes, and wouldn't work on `div`, if we change it down the road.
closes: https://github.com/SAP/ui5-webcomponents/issues/1626

feat(ui5-table): allow for custom styling

---

packages/playground/assets/js/playground.js

Currently on the playground if you search for textarea the top answer leads to: https://sap.github.io/ui5-webcomponents/playground/main/pages/TextArea/
which is usually not what users are looking for. Most of the people are looking for the textarea sample and docs: https://sap.github.io/ui5-webcomponents/playground/components/TextArea/
Now all the results from pages area excluded from the search results

chore: remove pages from search results on the playground

---

docs/CustomFonts.md

Background:
In `FontFace.js` we already have the check:
```js
if (document.querySelector(`head>style[data-ui5-font-face]`)) {
return;
}
```
due to multiple versions of the framework running side by side. So it was already possible to achieve easy font style customization by setting the `style` manually.
The goal of this change is to just document the process.

docs: document font customization

---

packages/base/src/UI5Element.js
packages/base/src/UI5ElementMetadata.js
packages/base/src/util/isSlot.js
packages/main/src/Input.js

There are composition scenarios where a component, say `ui5-upload-collection` creates a `ui5-list` in its shadow root and slots all its children to the list transitively by just rendering a `slot` in the list.
Example:
```html
<ui5-list
mode="{{mode}}"
@ui5-selectionChange="{{_onSelectionChange}}"
@ui5-itemDelete="{{_onItemDelete}}"
>
<slot></slot>
</ui5-list>
```
The problem with this is that the framework will only invalidate the `ui5-list` whenever its children are added/removed, but in this case the only child is the slot and it is completely static. Yet, when the user adds items to the `ui5-upload-collection`, they will be rendered transitively by the list, but the list will not be updated. Therefore some of the children may not be displayed properly.
The reported issue is that when …

fix(framework): component children that are slots now invalidate parent upon slotchange

---

packages/main/src/CalendarHeader.hbs
packages/main/src/Icon.hbs
packages/main/src/Icon.js

Until now `ui5-icon` had a fixed `role` attribute - it was always `img`.
Now, according to the `accessibleName` and `interactive` properties, it may be `button`, `img` or `presentation`.
The default `role` of all icons is now `presentation`. The only way to change this is to set either `interactive` to `true` (so you get `role=button`) or to set `accessibleName`, in which case you get `img`.
In addition: a missing closing `</div>` was added.
closes: https://github.com/SAP/ui5-webcomponents/issues/1581

fix(ui5-icon): Icon now has a correct role

---

packages/main/src/DurationPicker.hbs
packages/main/src/DurationPickerPopover.hbs
packages/main/src/TimePicker.hbs
packages/main/src/TimePickerPopover.hbs
packages/main/src/themes/DurationPicker.css
packages/main/src/themes/TimePicker.css
packages/main/test/pages/DurationPicker.html
packages/main/test/pages/TimePicker.html

The following issues has been resolved with this change:
- the input field now expands together with the host tag (as in the DatePicker)
- the Popover with the time controls remains the same in size, when the input gets bigger (as in the DatePicker)
- the TimePicker on phone used to have a header with a close button that is not supposed to be displayed a the component has a cancel button in the footer and that default header is meant for other components.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1659

fix(ui5-timepicker, ui5-duration-picker):  enable  width customization

---

packages/main/src/DurationPicker.js

Fixes #1660
#1658 depends on this, because the changes in #1658 should have been done together with the changes in this PR or vice versa.

fix(ui5-duration-picker): maxValue can be greater than 23:59:59

---

packages/main/src/Table.js
packages/main/src/TableCell.hbs
packages/main/src/TableCell.js
packages/main/src/TableRow.hbs
packages/main/src/TableRow.js
packages/main/test/pages/TableCustomStyling.html

There were 2 separate bugs:
- In `TableRow.hbs` the event handler for popped in rows was bound inside a loop (`{{#each popinCells}}`) however without `../` so it was never executed.
- Even after adding `../` the event was firing only when the user specifically clicks on the table cell, not on the whole row. The reason is that `_cellclick` is fired from `ui5-table-cell` only and inside popped in rows much of the content is just regular `<td>`s which don't fire any events. It is not necessary for the table cell to proxy clicks to the table row and the row to proxy clicks to the table. It is enough to just bind `@click` handlers to the normal `<tr>` and the popped in `<tr>` inside `TableRow.hbs`. In addition, it is not necessary to fire the publick `rowClick` event from `ui5-table`. It's …

fix(ui5-table): rowClick is fired for popped in cells as well

---

packages/main/src/themes/TextArea.css
packages/main/src/themes/base/sizes-parameters.css
packages/main/test/pages/TextArea.html

Issue: when growing and growing-max-lines="1" are set the text in the input field is a little downwards and not vertically centred. Now it is fixed and the new metrics for padding and height are the ones the openui5 TextArea uses.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1661

fix(ui5-textarea): fix text vertical alignment

---

packages/fiori/src/NotificationListGroupItem.hbs
packages/fiori/src/NotificationListGroupItem.js
packages/fiori/src/NotificationListItem.hbs
packages/fiori/src/NotificationListItem.js
packages/fiori/src/NotificationListItemBase.js
packages/fiori/src/themes/NotificationListItemBase.css
packages/fiori/test/pages/NotificationListGroupItem.html
packages/fiori/test/pages/NotificationListItem.html
packages/fiori/test/pages/NotificationList_test_page.html
packages/fiori/test/specs/NotificationList.spec.js

Add "busy" property to NotificationList(Group)ItemBase to enable users show busy state on notification item and group level.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1672

feat(ui5-li-notification, ui5-li-notification-group): add busy property

---

packages/main/src/Button.js
packages/main/test/pages/Button.html

If we use the "ui5-button" internally in other component's template like this:
```html
<ui5-button icon="{{this.icon}}">{{this.text}}</ui5-button>
```
And, if any button happens not to have a text, we will get the following result in the DOM:
```html
<ui5-button icon="home"></ui5-button>
```
Then, in Button.js we used to set icon-only if there are no childNodes, but in this case there are child nodes, because the comments are child nodes. Some styles, that rely on having a text are applied and the button does not look right:
Now the icon-only is set properly, checking against the textContent as it does not include comments and the same button looks like a standard one:
Other possible way is to filter the child nodes by nodeType:
```js
this.iconOnly = !Array.from(this.childNodes) …
```

fix(ui5-button): determine icon-only ignoring comment nodes

---

packages/base/src/AssetRegistry.js

The asset registry: `@ui5/webcomponents-base/dist/AssetRegistry.js` now exports a new method:
`registerCldrMappingFunction` 
that can be used to specify custom paths to the CLDR assets whenever they are not bundled.
Example usage:
```js
import { registerCldrMappingFunction } from "@ui5/webcomponents-base/dist/AssetRegistry.js";
registerCldrMappingFunction(locale => {
return `https://unpkg.com/@ui5/webcomponents-localization@0.19.0/dist/generated/assets/cldr/${locale}.json`
});
```
closes: https://github.com/SAP/ui5-webcomponents/issues/1524

feat(framework): CLDR location can now be specified

---

packages/fiori/src/UploadCollection.hbs
packages/fiori/src/UploadCollection.js
packages/fiori/src/themes/UploadCollection.css
packages/fiori/test/pages/UploadCollection.html

The "no-data" example we had predefined the height of the upload collection instance. However, when there is no height set, the design breaks. Therefore, a `min-height` value, enough for all visual elements to be seen, is supplied when there is no data.

fix(ui5-upload-collection): minimum height is guaranteed in no-data mode

---

packages/tools/lib/init-package/index.js

We used to update some constants by hand on each release, but it seems like these are not necessary at all, because the code that uses them puts them as dependencies in `package.json`. However, this is already the case because in the tutorial the step before running the script is:
`npm i --save @ui5/webcomponents-base @ui5/webcomponents-theme-base @ui5/webcomponents-tools`
closes: https://github.com/SAP/ui5-webcomponents/issues/1379

chore: remove unnecessary package init code

---

packages/base/package.json
packages/fiori/package.json
packages/icons/package.json
packages/localization/package.json
packages/main/package.json
packages/theme-base/package.json
packages/tools/lib/init-package/index.js
packages/tools/package.json
yarn.lock

Currently third-party libraries that use UI5 Web Components tools cannot control `chromedriver` version, which may be problematic whenever Google Chrome isn't automatically updated on their system. 
To solve this, we're moving `chromedriver` to a *peer dependency* rather than a *dev dependency* to `@ui5/webcomponents-tools`. All packages, internal or external, must now specify a suitable for them `chromedriver` version.
BREAKING CHANGE: If you are a UI5 Web Components third-party library author, you need to add a dev dependency to `chromedriver` in your project.
For example, if you had:
```json
"devDependencies": {
"@ui5/webcomponents-tools": "1.0.0-rc.7"
}
```
you should change this to:
```json
"devDependencies": {
"@ui5/webcomponents-tools": "1.0.0-rc.7",
"chromedriver": "latest"
}
``` …

feat(ui5-tools): libraries can now control chromedriver version

---

docs/dev/Creating UI5 Web Components Packages.md
packages/tools/lib/init-package/index.js

- do not automatically put `chromedriver` in `package.json` as people would need to manually run `yarn` or `npm i` afterwards (which moreover is not documented at all)
- ask people to install it directly themselves so that they understand they get to choose the version now

docs: explain chromedriver setup in the init package documentation

---

docs/dev/Creating UI5 Web Components Packages.md

After the last commit I saw that it doesn't look good on github (no new lines) so I changed it to be even more visible.
Now it will look like this:

docs: fix spacing

---

packages/main/src/DateTimePicker.js
packages/main/src/themes/DateTimePicker.css
packages/main/test/pages/DateTimePicker.html

The input length is not enough by several pixels and the text gets truncated/fully displayed whenever you focus/unfocus the component. 
- set `min-width` just enough to show the whole value
- remove the fixed width from our test page
closes: https://github.com/SAP/ui5-webcomponents/issues/1696

fix(ui5-datetime-picker): set min width

---

packages/base/test/specs/ConfigurationScript.spec.js
packages/main/test/specs/Calendar.spec.js
packages/main/test/specs/DateTimePicker.spec.js
packages/main/test/specs/ItemNavigation.spec.js
packages/main/test/specs/Popover.spec.js
packages/main/test/specs/TabContainer.spec.js
packages/main/test/specs/Table.spec.js
packages/tools/components-package/wdio.js

The goal of this change is to improve the test setup in several ways:
Stability and cleanup:
- Await for `RenderScheduler.whenFinished()` **before** read commands, such as `getAttribute` and not after them, as we did until now
- Await for `RenderScheduler.whenFinished()` **after** write/action/change commands, such as `click`, `setAttribute` as before
- wait for all commands that we use (or may use in the future), as some were still missing
- Remove obsolete commands such as `performActions`, `sendKeys`, etc... that we no longer use
- Await for `RenderScheduler.whenFinished()` after `url` and `pause` as it makes sense to await for all rendering after a page is loaded or after a pause (normally pauses should be an exception).
Performance:
- set "no conflict mode" only after a `url` …

chore(tools): Improve test setup

---

docs/dev/Creating UI5 Web Components Packages.md

This addition to the tutorial explains how to set custom configuration.
One of the examples shows how to disable "headless mode" for Chrome for the purpose of debugging tests.

docs: explain how to customize configuration for custom packages

---

packages/tools/bin/dev.js
packages/tools/components-package/nps.js

Currently the standard way to run a single test spec is as follows:
```
yarn run wdio ../tools/components-package/wdio.js --spec test/specs/Button.spec.js
```
After this change you can run "yarn test `<spec name>`", for example:
```
yarn test test/specs/Button.spec.js
```
*Note:*
What happens when you run "yarn test"
- The static server runs
- All test specs are executed
What happens when you run "yarn test `<spec name>`"
- Only the selected spec is executed (it is intended that you're already running `start` during development and testing anyway)

chore(tools): run single test spec

---

packages/main/src/CheckBox.hbs
packages/main/src/CheckBox.js
packages/main/src/ListItem.hbs
packages/main/src/ListItem.js
packages/main/src/i18n/messagebundle.properties
packages/main/test/pages/CheckBox.html
packages/main/test/specs/CheckBox.spec.js

The user now can set an aria-label on the component tag, it will be set on the root element with role="checkbox" and read by the screen readers. This feature is also useful for components that internally use checkbox such as the ListItem, that now can provide aria-label to the CheckBox in MultiSelect mode to meet the ACC requirements for having an accessible name.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1664

refactor(ui5-checkbox): enable aria-label forwarding

---

packages/main/src/Button.js
packages/main/test/pages/Button.html
packages/main/test/specs/Button.spec.js

Recent fix for how icon-only button with just comment nodes is rendered, has affected rendering of images, avatars inside the button.
This can be seen in the [ShellBar page](https://sap.github.io/ui5-webcomponents/master/playground/components/ShellBar/), where ui5-avatar is used for profile slot, internally slotted in a ui5-button. The profile image is not visible as "display: none" is applied due to the icon-only state of the ui5-button. 
Now we filter the comment nodes and check for the childNodes length to determine if its icon-only button or not.
Master and after this change

chore: fix button slot display

---

packages/main/src/Popover.js

Events are being duplicated in the Playground as already present in the base Popup class, we can remove it.

docs: remove inherited events

---

packages/base/src/asset-registries/i18n.js
packages/tools/lib/generate-json-imports/i18n.js

The goal of this change is to facilitate (and fix) custom i18n bundles, provided by users for our packages.
Currently it is already possible for the user to provide custom translations for our packages. For example:
```js
import { registerI18nBundle } from "@ui5/webcomponents-base/dist/asset-registries/i18n.js";
registerI18nBundle("@ui5/webcomponents", {
en: "./lang/en.json",
es: "./lang/es.json",
});
```
The code above will register these 2 URLs for fetching the translations for the respective package.
However, this works for all languages *except for the default language*. There is an optimization in the `i18n` asset registry: 
`if (localeId === DEFAULT_LANGUAGE)` 
that forces the components to use the built-in default language even if the user provided custom translations from their …

fix(framework): Allow users to override default language translations

---

packages/main/src/Select.js
packages/main/test/pages/Select.html
packages/main/test/specs/Select.spec.js

When the picker is closed and the user hits ESC, the component saves that action
and cancels the next selection. Now ESC cancels selection only if the picker is opened.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1721

fix(ui5-select): fix use of ESC leads to wrong selection

---

packages/main/src/TableRow.hbs
packages/main/src/TableRow.js
packages/main/src/themes/TableRow.css
packages/main/test/pages/TableAllPopin.html

This change fixes two issues:
- The `popin` rows had the wrong color until now, and they must be exactly the same color as the normal rows by design
- When all columns are popped in, since there is no normal row, there is nothing to provide the border. Therefore, the top popin row for the first column of for each group should do it.
closes: https://github.com/SAP/ui5-webcomponents/issues/1710

ui5-table: design implemented for popped-in columns

---

packages/main/src/TimePicker.js
packages/main/test/pages/TimePicker.html

Consider AM/PM periods in determining hours when 12h format is set, there is no need to adjust the hours in 24hours format. Previously we used to recalculate the hours for both formats, leading to a bug in 24hours format.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1714

fix(ui5-timepicker): adjust hours in 12hours format only

---

packages/main/src/TimePicker.js
packages/main/test/pages/TimePicker.html
packages/main/test/specs/TimePicker.spec.js

Previously the TImePicker used to fire "change" event unconditionally upon "Submit" press. 
Now, the value is checked and if it is changed, the event will be fired.
Additionally, the following has been removed from the constructor as these are existing boolean properties that by default are false
```js
this.readonly = false;
this.disabled = false;
```

fix(ui5-timepicker): fix firing "change" event for the same value

---

packages/fiori/src/UploadCollection.js

The condition to set `min-height` excluded DND mode, so when the user starts dragging a file, the drop area suddenly collapses.

fix(ui5-upload-collection): Provide min-height also when DND mode is on

---

packages/fiori/src/UploadCollectionItem.js
packages/main/src/CustomListItem.js
packages/main/src/TreeListItem.js

For some components, the styles are not built correctly, because the `static get styles` of their parent class returns an array and not a string. When these arrays are not properly destructured, they are interpreted as strings with a `,` between them.
Then during the IE CSS transformation, this `,` is translated to a selector with just the tag of the component.
Example:
`........pointer-events:none},.ui5-hidden-text........` (notice the comma that appears in the middle.
After IE transformation:
```css
ui5-li-custom,
ui5-li-custom .ui5-hidden-text {
position: absolute;
clip: rect(1px, 1px, 1px, 1px);
user-select: none;
left: 0;
top: 0
}
```
(notice the tag that appears before the comma).

fix: the styles getter always expects an array of strings

---

packages/main/src/Input.js
packages/main/test/pages/Input.html
packages/main/test/specs/Input.spec.js

Add "suggestion-item-preview" event to notify when the user navigates to a suggestion item via the ARROW keys, 
before he/she performs final selection.
Related to: https://github.com/SAP/ui5-webcomponents/issues/1768

feat(ui5-input): add suggestion-item-preview event

---

packages/tools/components-package/nps.js

The webcomponents polyfill was not copied correctly to the `dist/` directory for third-party packages, created with the init package script. The reason is that the path to `node_modules/` used to be hard-coded relatively to the packages in the UI5 Web Components project. The path is not the same however for third-party packages. Therefore the it is no longer guessed, but derived properly with `require.resolve` instead.
closes: https://github.com/SAP/ui5-webcomponents/issues/1762

fix(tools): Polyfill copied correctly in all scenarios

---

packages/main/src/themes/Avatar.css
packages/main/src/themes/base/Avatar-parameters.css
packages/main/src/themes/sap_belize/parameters-bundle.css
packages/main/src/themes/sap_belize_hcb/Avatar-parameters.css
packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
packages/main/src/themes/sap_belize_hcw/Avatar-parameters.css
packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
packages/main/src/themes/sap_fiori_3/parameters-bundle.css
packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css

For normal themes, `ui5-avatar` fulfilled the Fiori design, but for accessibility themes, there are different requirements:
- there must be a border for icon and initial type avatars
- background and text color must be purely black/white (no accent colors).
This change extracts all necessary variables to fulfill this.
Expected design:
closes: https://github.com/SAP/ui5-webcomponents/issues/1780

fix(ui5-avatar): Correct colors are applied for acc themes

---

packages/main/src/Input.js
packages/main/src/InputPopover.hbs
packages/main/src/Popover.js
packages/main/src/features/InputSuggestions.js
packages/main/test/pages/Input.html
packages/main/test/specs/Input.spec.js

The user can now bind for mouseover and mouseout events on the ui5-suggestion-item elements and perform some other action. For example: opening another popover, pointing to particular suggestion, when hovered.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1768
```html
<ui5-input id="inputPreview" show-suggestions>
<ui5-suggestion-item class="suggestionItem" text="Cozy"></ui5-suggestion-item>
<ui5-suggestion-item class="suggestionItem" text="Compact"></ui5-suggestion-item>
...
</ui5-input>
```
```js
[].slice.call(document.querySelectorAll(".suggestionItem")).forEach(function(el) {
suggestion.addEventListener("mouseover", function (event) {
const targetRef = event.detail.targetRef;
popover.openBy(targetRef, true /* prevent initial focus */); // open popover
}); …
```

feat(ui5-suggestion-item): enable mouseover|out events

---

packages/main/src/Panel.hbs
packages/main/src/themes/Panel.css

When the panel is `fixed`, the expand/collapse button should not be in the DOM at all. The current implementation violates accessibility best practices.
closes: https://github.com/SAP/ui5-webcomponents/issues/1753

fix(ui5-panel): The expand/collapse button is not in the DOM when fixed

---

packages/main/src/Select.js
packages/main/test/pages/Select.html
packages/main/test/specs/Select.spec.js

After this change:
- Opening/closing the select with Option/Alt + ArrowUp/ArrowDown doesn't scroll the page
- Tab on open select selects the current item & moves the focus to the next focusable item
- Shift + Tab on open select selects the current item & moves the focus to the previous focusable item
Part of #1534

fix(ui5-select): improve keyboard handling

---

packages/main/test/samples/Toast.sample.html

The statement "document.querySelectorAll("ui5-button").foeEach" used to throw an error, now it should not. (In addition make the code the users see es6).
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1794

docs: fix Toast sample for IE

---

packages/main/src/Popup.hbs
packages/main/src/Popup.js
packages/main/src/themes/MultiComboBox.css
packages/main/src/themes/Popover.css
packages/main/src/themes/Popup.css
packages/main/src/themes/ResponsivePopover.css
packages/main/src/themes/base/Popover-parameters.css
packages/main/src/themes/base/Popup-parameters.css
packages/main/src/themes/sap_belize/parameters-bundle.css
packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
packages/main/src/themes/sap_fiori_3/parameters-bundle.css
packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css

This change establishes a contract with third parties in terms of **protected** `Popup.js` APIs.
- `Popup.js` documented for the purpose of component development
- `createStyleInHead` used, and a data attribute given to the `style` tag for readability in the DOM. In addition, `ui5-dialog-scroll-blocker` renamed to `ui5-popup-scroll-blocker`.
- `id="ui5-popup-header"` is now set only on the div, wrapping the slot/`h2`. Otherwise it is duplicated inside the same instance.
- getters, intended to be overridden by derivatives, are now abstract (return undefined), and listed here. These are: `isModal` (used to return false), `_displayHeader` and `_displayFooter`.
- `--_ui5_popover_content_padding` renamed to `--_ui5_popup_content_padding:` and `Popover-parameters.css` renamed to …

refactor: document Popup.js and improve consistency

---

packages/main/src/themes/Link.css
packages/main/src/themes/base/Link-parameters.css
packages/main/src/themes/sap_belize_hcb/Link-parameters.css
packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
packages/main/src/themes/sap_belize_hcw/Link-parameters.css
packages/main/src/themes/sap_belize_hcw/parameters-bundle.css

The usage of pseudo elements such as **::after, ::before** has side effects on iOs/macOS making the first click to just focus the element and the second to be registered as click. Now, we set the focus with outline, instead of pseudo element. **Note:** in IE, the focus will be 1px wider on all sides, compared to Safari, Chrome and FF as the outline-offset is not supported.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1796

fix(ui5-link): fix "click twice" issue in Safari (#1799)

---

packages/fiori/src/themes/ShellBar.css

The CSS generated for IE for `::slotted(ui5-avatar)` is `ui5-shellbar ui5-avatar`, which is weaker than `ui5-avatar[size=S]`. Therefore, it is not applied.  This is unfortunately unavoidable because IE does not support `::slotted` and it's hard to replace it with an equally strong selector. Therefore in such cases it's best to make the expression inside `::slotted()` equally strong, if possible. Here it is by setting the slot name too. Now it generates `ui5-shellbar ui5-avatar[slot="profile"]` which is stronger than `ui5-avatar[size=S]`.
closes: https://github.com/SAP/ui5-webcomponents/issues/1806

fix(ui5-shellbar): Profile is styled correctly on IE

---

packages/main/src/Input.js
packages/main/test/pages/Input.html

There are use cases when the user dynamically appends/removes the value state msg slot
and we have to check if the value state msg popover is present before opening or closing it.
(The change in the test page has nothing to do with the fix, it is just visually improved.)
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1790

fix(ui5-input): fix JS errors when open/close popups

---

packages/main/src/TabContainer.hbs

There was a typo in the template: `_position` should have been `_posinset`.
closes: https://github.com/SAP/ui5-webcomponents/issues/1808

fix(ui5-tabcontainer): aria-controls now points to an existing ID

---

packages/main/src/Input.js

As we did for the Button, those aria stuff should be private to hide them from the API reference

chore(ui5-input):  make ariaLabel private

---

packages/main/src/Input.js
packages/main/test/pages/Input.html

In order to be more consistent with similar cases, when the user needs to open a popover from internal popover, as in the Shellbar, we provide the real DOM ref to an item (ui5-li) as "targetRef" param  in the event detail and leave "item" param for the external ui5-suggestion-item the user set.

chore(ui5-input): change event detail

---

packages/base/src/util/isValidPropertyName.js
packages/main/src/RatingIndicator.hbs
packages/main/src/RatingIndicator.js
packages/main/src/i18n/messagebundle.properties
packages/main/test/pages/RatingIndicator.html
packages/main/test/specs/RatingIndicator.spec.js

Add private aria-label and title props so the user can set them outside and ensure default tooltip ("Rating") is present when title is not provided, as elements with role="slider" needs aria-label, aria-labelledby or tooltip. 
A default aria-label was not an option as the word "Rating" would have been read twice as aria-roledescription="Rating Indicator" is already set.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1819

chore(ui5-rating-indicator): enable aria-label and tooltip

---

packages/fiori/test/specs/NotificationList.spec.js

Translation delivery fails with:
`AssertionError: The invisible text is correct.: expected 'Notification Group High Priority Counter 2' to equal 'Notification group High Priority Counter 2'`
and
`AssertionError: The invisible text is correct.: expected 'Notification Unread High Priority' to equal 'Notification unread High Priority'`
since the texts in the latest delivery have changed a bit.  The only difference is that some words are in small-case. However, changing the texts to the new ones won't be mergeable now, before the translation, so the simplest solution would be to check for case-insensitive.

chore: fix NotificationList tests

---

packages/base/src/UI5Element.js
packages/main/src/Tree.hbs
packages/main/src/Tree.js
packages/main/test/pages/LitKeyFunction.html
packages/main/test/specs/LitKeyFunction.spec.js
packages/tools/lib/hbs2lit/src/litVisitor2.js

This change is a step towards removing the auto-generated `_id` from the framework:
- What used to be `_id` is now instead `get _id()` which is created on demand only for components that use it. The first time some functionality needs to read `_id` from a UI5 Element, it will be guaranteed (and unique), but otherwise it will not exist. The real internal variable will be `__id`.
- `ui5-tree` used to override the `_id` of its list items (for matching tree items with list items) which is wrong. Now the checks are done by reference instead. `_id` cannot be set.
- Documented the famous "test" for the lit key function with a multi combo box, which filters the list of items until only one is visible, selects it, and then opens the popup, and verifies that the first item in the popup is not …

refactor(framework): make _id only generated on demand

---

packages/main/src/features/InputSuggestions.js

The scroll container should be awaited before we use it. Additionally, we use the step constant in the "isIteminView" method to avoid half visible items, because previously the input used to scroll if the item is entirely out of view (60 is the maximum height of a standard list item).
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1847

fix(ui5-input): fix scrolling item into view

---

packages/main/src/InputPopover.hbs

There is data-key set on the standard suggestions, but it's missing on the group suggestion. It is used for the mouseover/out events. Currently, if the users hovers on a group item, error is thrown as the corresponding suggestion item cant be found without this data-key attribute. Other way would be to not fire the events for hovering over group items, but at the end I think this is better.

chore(ui5-input): set data-key to group item

---

packages/tools/lib/hbs2lit/src/compiler.js

Now we no longer blindly replace `tab`s, but we strip whitespace around new lines. This way it also works if the `.hbs` uses spaces rather than tabs.
Changes: 
- the first expression `.replace(/\n+/g, "")` is enriched
- the last expression `.replace(/\t+/g, " ")` is removed.
close: https://github.com/SAP/ui5-webcomponents/issues/1804

fix(tools): strip unnecessary whitespaces

---

packages/main/src/Input.js
packages/main/test/pages/Input.html

The "focusout" event used to be fired whenever the user interacts with the suggestion lists, misleading the ones that listens for the event, that the user has clicked somewhere outside. Now, it is not fired.
Fixes: #1846

fix(ui5-input): stop firing focusout on suggestion click

---

packages/fiori/.npmignore
packages/main/.npmignore
packages/tools/lib/hbs2lit/index.js
packages/tools/lib/hbs2lit/src/compiler.js
packages/tools/lib/hbs2lit/src/includesReplacer.js
packages/tools/lib/hbs2ui5/index.js

This feature allows `.hbs` template authors to:
- Import other `.hbs` files from anywhere in the local filesystem: path starting with `.` or `..`
- Import other `.hbs` files from `node_modules/`
Examples:
```{{>include "./Popup.hbs"}}```
```{{>include "../my_partials/Header.hbs"}}```
```{{>include "@ui5/webcomponents/src/ListItem.hbs"}}```
This will enable third party developers to extend our components and implement the partials.
For the purpose, we need to start shipping the `src/` directory of `main` and `fiori`.
In addition, some parts of the `hbs2lit` and `hbs2ui5` libs have been improved, most notably `includesReplacer` in order to be able to recursively parse include statements while **simultaneously** keeping track of the current relative path of the currently parsed file so that …

feat(tools): Templates can be imported from node_modules/

---

packages/fiori/src/ShellBar.hbs
packages/fiori/src/ShellBar.js
packages/fiori/src/themes/ShellBar.css
packages/fiori/test/pages/ShellBar.html

Changes:
- enable tooltips for custom shellbar items
- set tooltips for the built-in icons: search, notifications, profile, products and oveflow
- fix "count" stopped displaying after replacing ui5-icon with ui5-button
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1854

feat(ui5-shellbar): enable tooltips of custom icons

---

packages/main/src/themes/Dialog.css
packages/main/test/pages/Dialog.html

The max-width of the Dialog content has been restricted to 90vh, however after the refactoring the Dialog can be expanded to 100% width with standard CSS (although not recommended by Fiori 3), causing visual issue.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1862

chore(ui5-dialog): allow content max-width 100%

---

packages/base/src/util/getEffectiveAriaLabelText.js
packages/main/src/Button.js
packages/main/src/Input.js
packages/main/test/pages/Input.html

This change centralizes the logic for calculating effective aria label text based on `ariaLabel` and `ariaLabelledBy`. Then this text is set as `ariaLabel` inside the shadow root, where IDs from the outer DOM cannot be cross-referenced.
Sample usage:
```html
<ui5-input aria-label="Very important input"></ui5-input>
<ui5-label id="enterNameLabel">Enter name: </ui5-label>
<ui5-input aria-labelledby="enterNameLabel"></ui5-input>
```
closes: https://github.com/SAP/ui5-webcomponents/issues/1866

feat(ui5-input): Support ariaLabelledBy

---

packages/main/src/SegmentedButton.js

It is possible that `_handleResize` be called before `onAfterRendering` and then `this.buttons` will be `undefined`, producing a JS error in the console.

fix(ui5-sebmentedbutton): fix intermittent js error

---

packages/main/src/themes/sap_belize/TabContainer-parameters.css
packages/main/src/themes/sap_belize/parameters-bundle.css

In OpenUI5 for `sap_belize` the tab container selected color is darkened by 5. We need to use this color as well to achieve the desired color contrast.
closes: https://github.com/SAP/ui5-webcomponents/issues/1870

fix(ui5-tabcontainer): correct selected text color used for sap_belize

---

packages/main/src/Tree.hbs

This change simplifies a bit the process of extending `ui5-tree` and overriding the tree list item content.
closes: https://github.com/SAP/ui5-webcomponents/issues/1845

chore(ui5-tree): extract tree list item partial

---

packages/main/bundle.es5.js
packages/main/bundle.esm.js
packages/main/test/pages/ResizeHandler.html

This test page demonstrates how app can use `ResizeHandler` for a cross-browser responsive paddings/margins solution.
The page compares media queries to `ResizeHandler` to showcase the differences between a full-page-width container and a container that only takes a part of the page (but needs to have responsive paddings/margins).

chore: create a test page for ResizeHandler

---

.github/actions/pre-release.js
package.json
yarn.lock

The script currently auto generates and releases versions based on the last commit - 0.0.0-2dsdsdds, 0.0.0-a4d5sdsd, etc. Now ,it can also release a specific version and tag, passed as an argument - 0.21.6, 0.21.7, etc.
```js
yarn prerelease // default: --tag=next, version=0.0.0-{commit_id}
yarn prerelease --tag sf --version 0.21.6
```

chore: improve pre-release script

---

packages/fiori/src/FlexibleColumnLayout.hbs
packages/fiori/src/FlexibleColumnLayout.js
packages/fiori/src/themes/FlexibleColumnLayout.css

In the initial implementation we removed "display: none" and start hiding the columns with width="0px" and position="absolute" and thus not having any issues with the column animation. Because in general the width animation can not run from 33% to display:none, when "display:none" and the "width" are set in same browser reflow. 
But, not using "display:none" leads to other issues, mainly accessibility. The slotted content within hidden columns might be accessed by TAB even if we set tabindex="-1" in the shadowRoot it does not help, the user should do the same to the external content. Also, if the app needs to start with OneColumn and later open the other columns, having display:none set will reduce the browser work on initial rendering.
With this change we have the same experience and …

chore(FCL): run column animation with display:none

---

packages/main/src/TreeListItem.js
packages/main/test/specs/Tree.spec.js

The aria-expanded attribute should not be set for non-expandable nodes.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1892

fix(ui5-li-tree): fix aria-expanded value

---

packages/tools/lib/jsdoc/plugin.js
packages/tools/lib/jsdoc/template/publish.js

The script that generates `api.json` had an unused entity `customTag` (probably leftover) which has been changed to tagname, which is used in our JSDoc.
closes: https://github.com/SAP/ui5-webcomponents/issues/1884

chore: add tagname to api.json

---

packages/main/src/Dialog.js
packages/main/src/Input.js
packages/main/src/Popover.js
packages/main/src/Popup.hbs
packages/main/src/Popup.js
packages/main/test/pages/Popover.html
packages/main/test/specs/Dialog.spec.js
packages/main/test/specs/Popover.spec.js

This change adds `aria-label` support for `ui5-popup`. The implementation in `ui5-popover` and `ui5-dialog` is:
- if the user passed `aria-label`, use it and do not set `aria-labelledby` in the shadow root (as it is stronger and will suppress `aria-label`)
- otherwise, set `aria-labelledby` normally (to point to the id of the popup's header).
Third-party popups will have full freedom to determine when `aria-label` and `aria-labelledby` are set by overriding the protected methods, as before.
In addition, added the missing description for `ariaLabel` for `ui5-input`.
closes: https://github.com/SAP/ui5-webcomponents/issues/1896

feat(ui5-popup): add support for aria-label

---

docs/i18n.md
packages/base/bundle.esm.js
packages/base/src/i18nBundle.js
packages/base/test/pages/assets/messagebundle_de.properties
packages/base/test/pages/assets/messagebundle_en.properties
packages/base/test/pages/assets/messagebundle_es.properties
packages/base/test/pages/assets/messagebundle_fr.properties
packages/base/test/pages/i18n.html

This tutorial shows how apps (not components) can use our `i18n` functionality.
Read the tutorial here: https://github.com/SAP/ui5-webcomponents/blob/document-i18n/docs/i18n.md
Changes to the actual code:
- For simplicity  `registerI18nBundle` is now also proxied by `i18nBundle.js`. This however makes the tutorial valid only for `rc.8` onwards. For current usage, import `registerI18nBundle` from `asset-registries/i18n.js` directly.
- `getText` may now have just the key as `String` as a first parameter (rather than an object with key and defaultText properties). This is useful for apps that wish to fetch the default language too, and never use fallback texts.
closes: https://github.com/SAP/ui5-webcomponents/issues/1713

docs: Document the usage of i18n for apps

---

packages/main/src/List.hbs
packages/main/src/List.js
packages/main/test/pages/List_test_page.html
packages/main/test/specs/List.spec.js

Add support for aria-label and aria-labelledby.
- if   **aria-label** or  **aria-labelledby**  are set externally, **aria-label** is set inside the shadowDOM.
- if not, **aria-labelledby** is set to reference the internal header, when the **header-text** property is set.
It is now possible to label the list as shown:
```html
<ui5-list aria-labelledby="testHeader">
<div slot="header">
<h2 id="testHeader">My heading</h2>
</div>
</ui5-list>
```
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1886

feat(ui5-list): support aria-label and aria-labelledby

---

docs/i18n.md
packages/base/src/i18nBundle.js
packages/base/test/pages/i18n.html

- `getText` now returns the key if no `defaultText` is given
- do not document the complex `getText` syntax, just the one with `key` as the first parameter

refactor(framework): getText uses the key as fallback, simplify docs

---

packages/main/src/Input.js
packages/main/src/features/InputSuggestions.js
packages/main/test/pages/Input.html
packages/main/test/specs/Input.spec.js

Add a method (isSuggestionsScrollable) that returns if the suggestions popup is currently scrollable or not.
- Note: the method is async.
- Note: call the method after the DOM is updated, otherwise you might get wrong result.
```js
// ensure the DOM has been updated
await RenderScheduler.whenFinished();
// check if the suggestions pop up is scrollable
const scrollable = await input.isSuggestionsScrollable();
```
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1902

chore(ui5-input): add isSuggestionsScrollable method

---

docs/dev/Creating UI5 Web Components Packages.md
packages/fiori/package.json
packages/main/package.json
packages/tools/bin/dev.js
packages/tools/lib/init-package/index.js

This change exposes two more `nps` commands as package scripts: `serve` and `watch`,  and additionally enhances the `test` command.
Examples:
Command | What it does
-----|-------
`yarn test` | Runs the dev server and executes all tests
`yarn test --no-server` | Executes all tests only
`yarn test test/specs/Button.spec.js` | Executes a single spec only (does not run server, no changes)
`yarn serve` | Runs the test server only
`yarn watch` | Runs the watch utility only
`yarn watch test` | Only watches for changes in the test files
`yarn watch src` | Only watches for changes in the source files
`yarn watch templates` | Only watches for template changes
This granularity would allow package authors greater flexibility, f.e. they could combine:
-  `yarn serve`
- `yarn test --no-server` 
- `yarn …

feat(tools): Add more commands to package.json

---

packages/main/src/Input.js
packages/main/src/Popover.js
packages/main/src/Popup.js
packages/main/src/ResponsivePopover.js
packages/main/src/features/InputSuggestions.js
packages/main/test/pages/Input.html
packages/main/test/pages/Input_quickview.html
packages/main/test/pages/Popover.html
packages/main/test/specs/Input.spec.js
packages/main/test/specs/Popover.spec.js

The change is related to the Quick View topic and affects the Input, InputSuggestions and Popover, and enables the following behaviour: (1) open an additional Popover from a suggestion on mouseover and suggestion-item-preview events, (2) to move the focus in that Popover, (3) to keep it open without a visible opener, and (4) the ability to get back via ESC.
- Add parameter to the openBy  method to prevent the popover from closing when its opener is not visible anymore
and use the old placement when the opener is gone (by default the popover would go to the top-left most corner).
- Add public method Popup.prototype.applyFocus (the logic has been extracted from applyInitialFocus) that focuses the first focusable element inside the Popup
- Change the focus retaining logic in …

feat(ui5-popover): prevent closing when no opener

---

packages/main/src/Card.hbs
packages/main/src/Card.js
packages/main/src/themes/Card.css
packages/main/test/pages/Card.html
packages/main/test/specs/Card.spec.js

Provides a new slot, called "action", displayed in the right most part of the header
to enable users add a action, in most cases single button. When the action slot is used, the status text would not be displayed (if present).
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1913

feat(ui5-card): add 'action' slot

---

packages/main/src/ComboBox.hbs
packages/main/src/ComboBox.js
packages/main/test/pages/ComboBox.html

Bug:
- `aria-expanded` is controlled by a non-existent property (`open`) which has been created
New implementation:
- add support for `aria-label` and `aria-labelledby`
closes: https://github.com/SAP/ui5-webcomponents/issues/1912

fix(ui5-combobox): support arial-labelledby and fix aria-expanded

---

packages/base/src/renderer/LitRenderer.js
packages/tools/lib/hbs2lit/src/litVisitor2.js
packages/tools/lib/hbs2ui5/RenderTemplates/LitRenderer.js

Now developers can use `{{{` and `}}}` to pass unescaped text to lit-html.
*Note:* This is only allowed for node values.
✔️ Example:
```html
<div>{{{myUnescapedText}}}</div>
```
❌ But this won't work:
```html
<div class="{{{myUnescapedText}}}"></div>
```

feature(tools): Support unsafeHTML in HBS compiler

---

packages/base/src/thirdparty/Map.prototype.keys.js

The `Map.prototype.keys` polyfill had ES6 code, which, under certain scenarios, does not get transpiled. All `thirdparty/` implementations need to be ES5.
closes: https://github.com/SAP/ui5-webcomponents/issues/1917

fix(framework): Remove ES6 code in IE polyfill

---

packages/main/src/Input.js
packages/main/src/InputPopover.hbs
packages/main/src/SuggestionItem.js
packages/main/src/features/InputSuggestions.js
packages/main/test/pages/Input.html
packages/main/test/specs/Input.spec.js

Now the Input suggestions can be from type="Inactive". 
- **Note**: the inactive items can't be selected neither with the mouse, nor with the keyboard.
- **Note**: the inactive items produces empty string in the input field, when previewed with the UP/DOWN arrow keys, the same way as the group header item, as both are not selectable
Related to: https://github.com/SAP/ui5-webcomponents/issues/1919

feat(ui5-input): Support 'inactive' suggestions

---

packages/main/src/Input.js
packages/main/src/InputPopover.hbs

Enable suggestion list separators customization
- add suggestionSeparators getter that can overwritten in order to have different separators type
- change the default separators type of the suggestion list to "None" as in classic UI5
Related to: https://github.com/SAP/ui5-webcomponents/issues/1919

chore(ui5-input): Enable separators customization

---

packages/fiori/src/upload-utils/UploadCollectionBodyDnD.js

If you drag a file over `ui5-upload-collection` and then drop it somewhere on the page, all upload collections get stuck with the "drop file" UI.
Example: drag a `.zip` file (downloadable by the browser, so it won't open in the same tab) but don't drop it on any upload collection, drop it **between them** instead
What happens then is that the browser downloads the file. When the file is downloaded, all instances get stuck:
In this case, the `drop` event is never fired by the browser, unless the `dragover` event is prevented.

fix(ui5-upload-collection): The component does not get stuck

---

packages/main/src/TextArea.hbs
packages/main/src/TextArea.js

This change:
- fixes missing `Popover.js` dependency due to value state
- adds a new partial that can be used for third-party development
For example, it would be possible to create a text area with a "clear button":
closes: https://github.com/SAP/ui5-webcomponents/issues/1879

fix(ui5-textarea): Add missing dependency, extract .hbs partial

---

packages/main/src/ComboBox.js
packages/main/test/specs/ComboBox.spec.js

When the user types and there is no match, the picker remains open and empty, now it closes.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1920

fix(ui5-combobox): Close picker when no match

---

packages/main/src/InputPopover.hbs

Add template hook for the suggestions list, so the third party components can entirely replace our list with another and to fully control the appearance of the suggestion items.
```js
// CustomInputPopoverTemplate.hbs
{{>include "InputPopoverTemplate"}}
{{#*inline "suggestionsList"}}
<ui5-my-list>
</ui5-my-list>
{{/inline}}
```

refactor(ui5-input): Add template hook for the suggestions

---

packages/main/src/Panel.hbs
packages/main/src/Panel.js
packages/main/test/pages/Panel.html
packages/main/test/specs/Panel.spec.js

Added support for **aria-label** and **aria-labelledby**
* if **aria-label** or **aria-labelledby** are set externally, **aria-label** is set inside the shadowDOM.
* if not, **aria-labelledby** is automatically set to the reference of internal title, when the header-text property is set.
* if panel has items in **header** slot these values are propagated to expand/collapse button.
In addition:
* accessibility attributes are removed from header container when the panel is fixed.
* panel could be expanded/collapsed throught expand/collapse button when it has items in **header** slot.
#1880

feat(ui5-panel): support aria-label and aria-labelledby

---

packages/base/src/features/OpenUI5Support.js

Change the regex to detect the openui5 CSS variables properly as from 1.79 the CSS Variables filename has changed to **css_variables.css** (previously css-varaibles.css with dash). 
But, the script will match the old name with "-" dash as well, if we need to support it, otherwise we can leave "_" only to support the latest name.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1932

fix(framework): Fix openui5 css varaibles detection

---

packages/base/src/RenderQueue.js
packages/base/src/RenderScheduler.js
packages/base/src/UI5Element.js
packages/base/test/specs/UI5ElementLifecycle.js
packages/main/test/pages/DialogLifecycle.html
packages/main/test/specs/Dialog.spec.js

- `RenderQueue.js` no longer manages promises at all
- `renderImmediately` is completely sync now and does not use the render queue. The render queue is only used by `renderDeferred`. `renderDeferred` is async and awaits for queue processing to be over (but does not await for the "official" end of the render task - the Mutation Observer).
- In `UI5Element.js` there are 2 new flags: `_inDOM` which is set immediately when `connectedCallback` is called, and is unset immediately when `disconnectedCallback` is called. It prevents the component from entering the render queue if removed from DOM before it gets to it. And `_fullyConnected` which is set before calling `onEnterDOM` and unset after calling `onExitDOM`. Thus we call `onExitDOM` only if we called `onEnterDOM`, thus preventing …

fix(framework): make renderImmediately sync, fix lifecycle issues

---

packages/fiori/src/themes/ShellBar.css

We used to force` background-color: transparent` to the ui5-avatar, when used as profile. But, it turns out that this is not needed, in classic UI5, the Avatar is displayed with its default AccentBGColor6 and we align to this with the change.
Moreover, in Fiori3 Dark, the transparent Avatar leads to missing color contrast as shown in the issue.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/1944

fix(ui5-shellbar): Fix profile bg-color

---

packages/main/src/ComboBox.js
packages/main/test/specs/ComboBox.spec.js

Now, all items are shown inside **ui5-popover**  when it is opened and items are filtered only on user input. 
Fixes: #1925

fix(ui5-combobox): corrected display of items in popover

---

packages/main/src/ComboBox.js
packages/main/test/specs/ComboBox.spec.js

Now, popover is closed when "Enter" key is pressed.
Fixes: #1940

fix(ui5-combobox): close popover on "Enter" key press

---

packages/main/src/themes/Input.css

The selection color and bg-color variables used to be wrong. In Chrome and Safari these values fallback to their defaults and the bug is more difficult to be seen, but in FF the color and bg color become unset, and you cant see any selection with ctr+a or cmd+a.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1951

fix(ui5-input): Fix selection color and bg

---

packages/main/src/Input.js

Added extension point to allow extending components control the behaviour on suggestion preview. The default behaviour of the Input with suggestions is to replace the current value with the value of the previewed suggestion, when the user navigates with UP/DOWN arrows. But, there are use cases as in the attached issue, that instead of replacing the entire text, just part of it has to  be replaced, changed or added to.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1878
```js
/**
* Updates the input value on item preview.
* @param {itemValue} itemValue The value of the item that is on preview
*/
updateValueOnPreview(itemValue) {
this.value = itemValue; // here the extending component may overwrite the behaviour
}
```

refactor(ui5-input): Add hook for value update on suggestion preview

---

packages/main/src/Input.js
packages/main/src/InputPopover.hbs
packages/main/src/Popover.js
packages/main/src/Popup.js
packages/main/src/TextArea.js
packages/main/src/TextAreaPopover.hbs
packages/main/src/popup-utils/OpenedPopupsRegistry.js
packages/main/src/popup-utils/PopupUtils.js
packages/main/test/pages/Input.html
packages/main/test/pages/Input_quickview.html
packages/main/test/specs/Input.spec.js

**Another PR to address the "QuickCardView" topic. The change keeps the Popover open, without an opener, if the focus is inside that popover.**
- add prevent-focus-restore protected property in addition to the preventFocusRestore param of Popup.prototype.close method, because the quickCardView might close due to user interaction - click, TAB, ESC.
- remove the recently added _closeWithOpener param, as now the popover without an opener would remain open if the focus is inside it and will be closed otherwise.
**QuickCardView Interaction** (test it on http://localhost:8080/test-resources/pages/Input_quickview.html)
- Once opened, both Suggestions Popover and QuickCardView will close if:
neither the SearchField nor the QuickCardView has the focus, because the user clicks somewhere outside or …

refactor(ui5-popover): Keep popup open if focus is inside

---

packages/base/src/util/isValidPropertyName.js

It would be useful to be able to support the `hidden` property for abstract elements, which don't have their own rendering, and marking them as hidden makes sense.

chore(framework): Allow the hidden property for custom elements

---

packages/main/src/Input.js
packages/main/src/features/InputSuggestions.js

Changes:
- The `_getItems` function now reads all children of the list, regardless of tag name, so that for example `ui5-li-custom` will also work.
- The `updateValueOnPreview` hook now gets not just a string, but the whole item as a parameter. This gives developers more freedom in determining what exactly is considered as the "preview value" of the item. This is handy for example if `ui5-li-custom` is used and the value is just part of that.
closes: https://github.com/SAP/ui5-webcomponents/issues/1967
BREAKING CHANGE: the format of the `updateValueOnPreview` hook has changed. The parameter is no longer a string (`itemValue`), but the whole `item` object now. It is this hook's responsibility to determine whether/how to preview group items and inactive items too.

fix(ui5-input): Suggestions can now be arbitrary list items

---

packages/main/src/TabContainer.js

Fixes #1953
BREAKING CHANGE: Tab Container will no longer automatically select the first tab, if no tab is selected. If you relied on this behavior, you should now explicitly set the `selected` property on the first tab.

fix(ui5-tabcontainer): prevent the tabcontainer from setting the selected property on ui5-tab internally

---

packages/base/src/UI5Element.js
packages/main/src/Popup.js

**Preface:** Some events should not bubble, because that leads to strange side effects (f.e. if there are nested popups and the inner one fires an event, the handlers of the outer one will be executed too, unless the user cancels the event or checks the event target).
`UI5Element.js` now supports non-bubbling events (a new parameter added to `fireEvent`).
All 4 events of `Popup.js` were tweaked:
1. `before-open`
- can now be prevented (and prevents any of the code in `open` from executing)
- does not bubble
2. `after-open`
- does not bubble
3. `before-close`
- not fired any more if the popup is already open
- does not bubble
4. `after-close`
- does not bubble
closes: https://github.com/SAP/ui5-webcomponents/issues/1962
BREAKING CHANGE: If you relied on `before-open`, `before-close`, …

refactor(ui5-popup): Events do not bubble

---

packages/fiori/src/FlexibleColumnLayout.js
packages/fiori/test/specs/FCL.spec.js

The media breakpoints are now aligned with the Fiori 3 specs.
Related to: https://github.com/SAP/ui5-webcomponents/issues/1972

fix(ui5-flexible-column-layout): Fix media breakpoints

---

packages/base/src/asset-registries/i18n.js

Currently region is not taken into account, so if you set `?sap-ui-language=zh_CN` for example, the framework will try to load `messagebundle_zh.json` which does not exist. The same bug would be observed for all languages that don't have an i18n file for the base language, but only for regions.

fix(framework): Take region into account for i18n assets

---

packages/main/src/Input.js

fix(ui5-input): fix inpur cursor movement in Safari

---

packages/main/src/Input.js
packages/main/src/InputPopover.hbs
packages/main/src/features/InputSuggestions.js
packages/main/test/pages/Input.html
packages/main/test/specs/Input.spec.js

fix(ui5-input): sync width of suggestions popover and input

---

packages/main/src/TabContainer.js
packages/main/test/specs/TabContainer.spec.js

When the TabContainer is no longer scrollable, the overflow arrows hides, the overflow popover should be closed as well. Previously it was automatically closed, but (after the  latest changes in the Popover) as the focus is within the popover, it remains open, if not handled.

fix(ui5-tabcontainer): Fix overflow visibility

---

packages/main/test/pages/Popover.html
packages/main/test/specs/Popover.spec.js

- openBy has no third parameter anymore
- add some delay, because even if the popover closes the test would not fail, because it is checked immediately.
*The test asserts that the popover will not close, when its opener is gone, as long it has the focus within.

chore: Fix Popover test

---

packages/theme-base/package-scripts.js
packages/tools/components-package/nps.js
packages/tools/lib/generate-json-imports/themes.js
packages/tools/lib/init-package/index.js
packages/tools/lib/init-package/resources/src/themes/sap_fiori_3_hcb/parameters-bundle.css
packages/tools/lib/init-package/resources/src/themes/sap_fiori_3_hcw/parameters-bundle.css

This change fixes 3 bugs:
- Now the build does not try to generate JSON imports for themes that don't exist on the file system of the package (but are otherwise supported by us). Before the fix, if a third party package updated and tried to build/start, it would fail due to not having `sap_fiori_3_*` acc themes.
- The init package script now also includes the new themes
- The framework no longer requires all components to start with `ui5-` so this restriction has been lifted.
closes: https://github.com/SAP/ui5-webcomponents/issues/1970

fix(tools): Building third-party packages no longer fails

---

packages/main/src/ComboBoxItem.js
packages/main/src/MultiComboBoxItem.js
packages/main/src/SuggestionListItem.js

Added jsdoc directive `tagname` to:
- `ui5-cb-item`
- `ui5-mcb-item`
- `ui5-suggestion-item`

docs: add missing tagname

---

packages/base/src/util/isValidPropertyName.js
packages/main/src/Button.js

Properties that already exist on HTML elements should be declared as `@private` in metadata, as we just want to integrate them in the lifecycle of the framework, without them appearing in the help.
Additionally: we now automatically whitelist all properties starting with `aria` without needing to enter them one by one.

chore(ui5-button): fix docs

---

packages/fiori/src/NotificationListGroupItem.hbs
packages/fiori/src/NotificationListItem.hbs
packages/main/src/GroupHeaderListItem.hbs
packages/main/src/List.hbs
packages/main/src/ListItem.hbs
packages/main/src/TabContainer.hbs
packages/main/src/TabInStrip.hbs
packages/main/src/TabSeparator.hbs
packages/main/src/Timeline.hbs
packages/main/src/WheelSlider.hbs

Despite having the right CSS style, for some reason it is not applied on IE until the component is repainted by the browser.
After the fix: 
there are no dots already on the first load.

fix: lists no longer show a dot on IE

---

packages/main/src/ComboBox.js
packages/main/src/ComboBoxPopover.hbs

Now the popup closes on focusout, except the case when the focusout is due to focusin of the items
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2009

fix(ui5-combobox): Close popup on focusout

---

packages/main/src/BusyIndicator.hbs
packages/main/src/BusyIndicator.js
packages/main/src/themes/BusyIndicator.css

Fixes: https://github.com/SAP/ui5-webcomponents/issues/2005

fix(ui5-busyindicator): Set bigger opacity for IE

---

packages/main/src/FileUploader.js

In IE, the native "input" element is not inside the ShadowDOM, but in the Light one, so the following statement fails to get it:
`this.getDomRef().querySelector(`input[type="file"]`)`. 
Instead, we should use the safe "_input" getter that looks in the Light DOM.
```js
get _input() {
return this.shadowRoot.querySelector("input[type=file]")
|| this.querySelector("input[type=file][data-ui5-form-support]");
}
```
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2018

fix(ui5-file-uploader): Fix JS error thrown in IE

---

packages/main/src/features/InputSuggestions.js
packages/main/test/pages/Input.html
packages/main/test/pages/Input_quickview.html
packages/main/test/specs/Input.spec.js

For some reason the statement `"this.responsivePopover.querySelectorAll("ui5-list>*")` always returns an empty array in IE,
later leading to a JS error, when element from that array had to be accessed, so I had to tweak it a little bit. In addition:
- Clean Input.html from ES6 code
- Everything, related to "suggestion-item-preview" event and the "Quick View Card" topic
is in separate Input_quickview.html page.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2019

 fix(ui5-input): Fix JS error thrown in IE

---

packages/fiori/src/FlexibleColumnLayout.js
packages/fiori/test/pages/FCLCustom.html

This change adds a new property, letting users provide their completely custom layouts configuration. The change is experimental.
closes: https://github.com/SAP/ui5-webcomponents/issues/1972

refactor(ui5-flexlible-column-layout): Custom layouts configuration

---

packages/base/src/config/AnimationMode.js
packages/fiori/src/FlexibleColumnLayout.js
packages/fiori/src/themes/FlexibleColumnLayout.css
packages/fiori/test/specs/FCL.spec.js
packages/main/bundle.es5.js
packages/main/bundle.esm.js
packages/theme-base/css-vars-usage.json

Framework level:
- support dynamically setting `animationMode`
FCL:
- respect the `animationMode=none` setting
- run the tests with no animations

feat(ui5-flexible-column-layout): animations can be disabled

---

packages/main/src/SegmentedButton.js

When the component was rerendered, all button widths were reset to `""`. Therefore on click the segmented button used to collapse.
Now the full processing is done. `_handleResize` is renamed to `_doLayout` and called both `onAfterRendering` and upon resize.
closes: https://github.com/SAP/ui5-webcomponents/issues/1986

fix(ui5-segmentedbutton): buttons no longer shrink on click

---

packages/main/src/List.js
packages/main/src/Select.js
packages/main/src/SelectPopover.hbs
packages/main/src/types/ListMode.js

In order for the selection to be smooth, the focus/selection handling should be done internally by the list. Otherwise the select will always be one step behind and the focus will always lag behind the selected item.
Changes:
- The list gets a new mode: `SingleSelectAuto` that changes the selection when the user presses the arrows. So in fact the focused item is always selected (automatically, hence the name).
- The select uses the new list mode and handles selection change and item click. The only difference is that on selection change the popup is not closed and on item click it is.
- The keyboard handling code that used to be in one function for both modes (when popup closed, when popup open) is now naturally split in 2 parts: when the popup is open, handle only esc/enter, as the list …

fix(ui5-select): Selection now changes instantly

---

packages/fiori/src/SideNavigation.hbs
packages/fiori/src/SideNavigation.js
packages/fiori/src/SideNavigationItem.js
packages/fiori/src/SideNavigationSubItem.js
packages/fiori/test/samples/SideNavigation.sample.html

Now we support icon on the subitem, but strongly recommend not to to be used as this by the Fiori 3 guidelines. The icons on the second level are removed from the sample. The JSDOC has been improved.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2033

chore(ui5-side-navigation): subitems may have icons, appenddocs fixed

---

packages/main/src/Button.hbs
packages/main/src/Button.js
packages/main/src/MessageStrip.hbs
packages/main/src/MessageStrip.js
packages/main/src/themes/Button.css
packages/main/src/themes/MessageStrip.css
packages/main/src/themes/base/MessageStrip-parameters.css
packages/main/test/specs/MessageStrip.spec.js

Changes to `ui5-button` to support this change:
- new property `iconSize` added, allowing the user control not only over the button size, but over the icon size as well
- padding removed for `iconOnly` mode, icon is now centered
Buttons like this are now possible:
with the following markup:
`ui5-messagestrip` was refactored:
- `ui5-button` used to achieve the desired design and behavior for the close button (kb handling, hover, focus, etc..)
- CSS simplified (same rules merged, duplicate selectors removed, redundant CSS removed after the close icon removal, etc...)
- CSS classes renamed and reordered
- keyboard handling logic and all code that simulates `ui5-button` behavior deleted
- `onDefine` now awaits all resources simultaneously
The close button looks like:
closes: …

fix(ui5-messagestrip): Close button now has the correct design

---

packages/fiori/src/FlexibleColumnLayout.hbs
packages/fiori/src/FlexibleColumnLayout.js
packages/fiori/src/themes/FlexibleColumnLayout.css

**Note:** The Icon inside Button cantering change should be merged first: https://github.com/SAP/ui5-webcomponents/pull/2029
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1998

fix(ui5-flexible-column-layout): Fix arrow misplacement in IE

---

packages/main/src/TabContainer.js
packages/main/test/specs/TabContainer.spec.js

The separator should be excluded, when calculating the aria-posinset and aria-setsize values.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2035

fix(ui5-tabcontainer): Fix ARIA posinset and setsize values

---

packages/main/src/TabInOverflow.hbs

fix(ui5-tabcontainer): implement acc for overflowed items

---

packages/base/src/StaticAreaItem.js
packages/base/src/theming/getEffectiveStyle.js
packages/base/src/theming/getStylesString.js
packages/fiori/src/UploadCollectionItem.js
packages/main/src/CustomListItem.js
packages/main/src/DateRangePicker.js
packages/main/src/DateTimePicker.js
packages/main/src/ResponsivePopover.js
packages/main/src/TabContainer.js
packages/main/src/TreeListItem.js

Currently when extending components, in order to include the parent component's `styles`/`staticAreaStyles`, you need to either:
- `styles: [...super.styles, myStyles]`
- or `styles: [super.styles, myStyles]`
depending on whether the parent `styles` static property is an array or not. This is error prone, especially due to the fact that the format of parent `styles` may change (f.e. the parent might add another style) and all children that did not destructure, will be bugged.
This change automatically flattens the `styles`/`staticAreaStyles` properties. Components that destructure parent styles will continue to work, but those who don't are now safe against future changes in the parent.
Additionally, all components that destructure parent styles have been refactored not to do it for …

feat(framework): styles and staticAreaStyles may now be nested arrays

---

README.md
docs/React-tutorial.md

Every now and then the question comes up how UI5 Web Components and UI5 Web Components for React are relating to each other. As we are more or less the "official" wrapper for UI5 Web Components, I though adding a couple of sentences about our wrapper to your README would make sense.
Example for such a question: https://openui5.slack.com/archives/CSQEJ2J04/p1596300002038000

docs: mention UI5 Web Components for React

---

packages/main/src/MultiComboBox.hbs
packages/main/src/MultiComboBox.js
packages/main/src/MultiComboBoxPopover.hbs

`MultiComboBox` state is currently reduntant:
- `_toggleIcon` renamed to `_toggle` as it does more than just that
- `_iconPressed` removed (same as `open`)
- `focused` is removed (never used, not even in CSS, only set)
- `expandedTokenizer` is not real state, it is computed state, so removed and replaced with a getter. It depends on `_rootFocused` (new state) and the `open` property:
```js
get _tokenizerExpanded() {
return this._rootFocused || this.open;
}
```
closes: https://github.com/SAP/ui5-webcomponents/issues/1991

refactor(ui5-multicombobox): simplify state

---

packages/tools/components-package/rollup.js

If dynamic imports are used, the ES5 build fails due to the inability to create several chunks for the `eefe` format. The ES5 build should always treat dynamic imports as standard, and always create one single file.
closes: https://github.com/SAP/ui5-webcomponents/issues/1946

feat(tools): ES5 build supports dynamic imports (inlined)

---

packages/tools/components-package/rollup.js

The current rollup configuration works for `@ui5/webcomponents` and related projects (`-base`, `-fiori`, etc...) but for third parties, all of our packages are actually in `node_modules/` and they don't get transpiled at all because of this rule. The solution is to either remove the rule altogether, or to allow `node_modules/lit-html` and `node_modules/@ui5-webcomponents` and the rest.
closes: https://github.com/SAP/ui5-webcomponents/issues/1959

@vladitasev fix(tools): UI5 Web Components are now correctly transpiled

---

packages/main/src/Input.js
packages/main/src/InputPopover.hbs
packages/main/src/themes/ResponsivePopoverCommon.css

- Fixes the height when the value state msg is displayed as standalone popover, previously too large. 
- Fixes the height within the suggestions popover, previously the message used to be cut off.
FIXES https://github.com/SAP/ui5-webcomponents/issues/2070
Before
After

fix(ui5-input): fix value state msg appearance

---

packages/tools/lib/hbs2ui5/index.js
packages/tools/package.json
yarn.lock

Now the the tools will process HBS files within nested directories and produce the output "lit" files into the "dist",
maintaining the file structures.
FIXES https://github.com/SAP/ui5-webcomponents/issues/2065
```js
src/
----> myComponent
----> MyComponent.hbs (nested lvl 1)
----> myComponentBadge
----> MyComponentBadge.hbs (nested lvl 2)
dist/generated/templates/
----> myComponent
----> MyComponent.hbs (nested lvl 1)
----> myComponentBadge
----> MyComponentBadge.hbs (nested lvl 2)
```

feat(tools): process HBS files in nested directories

---

packages/main/src/ComboBox.js
packages/main/src/ComboBoxPopover.hbs
packages/main/test/pages/ComboBox.html
packages/main/test/specs/ComboBox.spec.js

Now, selected item can be changed with arrow down / arrow up keys.
Fixes: #1939
In addition some issues are resolved:
- Change event could be fired on Enter key press.
- Change event could be fired on focusout.

feat(ui5-combobox): enable handling of arrow down/up keys

---

packages/base/src/RenderScheduler.js
packages/base/src/UI5Element.js
packages/base/src/theming/CustomStyle.js
packages/base/src/theming/createComponentStyleTag.js
packages/base/src/theming/getConstructableStyle.js
packages/base/src/theming/getEffectiveStyle.js
packages/main/bundle.es5.js
packages/main/bundle.esm.js
packages/main/test/pages/CustomCSS.html

The `addCustomCSS` API used to be static - custom styles were cached together with built-in styles and never re-evaluated (except for FF/Safari). 
This change makes `addCustomCSS` affect already rendered components too, for all browsers:
- `addCustomCSS` invalidates all cached CSS resources for the particular tag - constructable stylesheets (Chrome), style tags (IE11/Edge), and calculated effective styles (FF, Safari).
- `addCustomCSS` invalidates all already rendered components with this tag.
- All style management is now in `_render` rather than in `_initializeContainers` (basically `constructor`) to make it dynamic, but all style resources are now cached.
The following modules implement CSS resource caching and invalidation:
- `getEffectiveStyle`
- `getConstructableStyle`
- …

feat(framework): Make addCustomCSS dynamic

---

packages/fiori/src/themes/ShellBar.css

By specification logo should have only 2rem height limitation.
Fixes #2066

fix(ui5-shellbar): remove width limitation of logo

---

packages/base/src/StaticAreaItem.js
packages/fiori/src/ShellBar.js
packages/main/src/ComboBox.js
packages/main/src/DatePicker.js
packages/main/src/Input.js
packages/main/src/MultiComboBox.js
packages/main/src/Select.js
packages/main/test/pages/TimePicker.html

**Fixes**
TimePicker was never considering contentDensity and did not update the styles of its popover so far.
DatePicker and DateTimePicker used to call updateStaticAreaItemContentDensity before the staticAreaItem DOM is available.
**Solution:**
Handle setting the contentDensity on framework level when possible and remove updateStaticAreaItemContentDensity calls from ShellBar, ComboBox, Select, Input, MultiCombobox. The updateStaticAreaItemContentDensity method exists and used in the TabContainer only, because the component does not invalidate on overflow popover open/close and needs to force the contentDensity update.
FIXES https://github.com/SAP/ui5-webcomponents/issues/2093

fix(components): fix setting contentDensity styles

---

packages/base/src/Keys.js
packages/main/src/TimePicker.js
packages/main/src/TimePickerPopover.hbs
packages/main/test/specs/TimePicker.spec.js

Fixed one keyboard handling bug and added new features:
- PageUp - Hours + 1
- PageDown - Hours - 1
- PageUp + Shift - Minutes + 1
- PageDown + Shift - Minutes - 1
- PageUp + Shift + Ctrl - Seconds + 1
- PageDown + Shift + Ctrl - Seconds - 1
Related to: https://github.com/SAP/ui5-webcomponents/issues/1534

feat(ui5-time-picker): improve keyboard handling support

---

packages/main/src/Input.hbs
packages/main/src/Input.js

Previously just the buil-in text of a certain value state has been set to the hidden element that is being read out. Now the custom value state msg is also taken into account.
Related to: https://github.com/SAP/ui5-webcomponents/issues/2106

fix(ui5-input): announce custom valueStateMessage

---

packages/main/src/Toast.js
packages/main/src/themes/Toast.css
packages/main/test/pages/Toast.html
packages/main/test/specs/Toast.spec.js

Remove hardcoded z-index of 999. As the Toast is not a popup by implementation, 
but is a popup by nature, it should use the shared "z-index" between the Popups (Dialog and Popover) to appear correctly under or over them, depending on the place it has been opened.
FIXES https://github.com/SAP/ui5-webcomponents/issues/2110

fix(ui5-toast) avoid overlaying  Dialog and Popover

---

packages/main/src/TextArea.hbs
packages/main/src/TextArea.js
packages/main/test/pages/TextArea.html
packages/main/test/specs/TextArea.spec.js

As the Input, the TextArea should support aria-label and aria-labelledby set on the custom element.
Note: internally we also set aria-label, using the base method "getEffectiveAriaLabelText" for the purpose.
Related to https://github.com/SAP/ui5-webcomponents/issues/2107

feat(ui5-textarea): add ariaLabel and ariaLabelledby properties

---

packages/main/src/Select.hbs
packages/main/src/Select.js
packages/main/test/pages/Select.html
packages/main/test/specs/Select.spec.js

Similar to other components, the Select should also support aria-label and aria-labelledby set on the custom element.
Note: internally we also set aria-label, using the base method "getEffectiveAriaLabelText" for the purpose.
Related to https://github.com/SAP/ui5-webcomponents/issues/2107

feat(ui5-select): add ariaLabel and ariaLabelledby properties

---

packages/main/src/FileUploader.hbs
packages/main/src/FileUploader.js
packages/main/src/FileUploaderPopover.hbs
packages/main/test/pages/FileUploader.html

Introduce support for custom value state message as slot. Note: although the ui5-input is internally used, we can not just forward the slot (as in the DatePicker for example), because it is not the element that is clicked, focused and so on.
Related to https://github.com/SAP/ui5-webcomponents/issues/1086

feat(ui5-file-uploader): implement custom valueStateMessage

---

packages/main/src/Popover.js
packages/main/test/pages/Popover.html

Fix Popover's arrow horizontal position, when horizontalPlacement is either "Left", or "Right".
FIXES  https://github.com/SAP/ui5-webcomponents/issues/2111
Perviously
Now the arrow position is correct

fix(ui5-popover): fix arrow horizontal position

---

packages/main/src/themes/Title.css

Enable font-size customization setting styles on the host.
FIXES https://github.com/SAP/ui5-webcomponents/issues/2134
For example:
```html
<ui5-title level="H2" style="font-size: var(--ui5_title_level_5Size)"
<ui5-title level="H2" style="font-size: 1rem"
```

refactor(ui5-title): enable font-size customization

---

docs/dev/Development Workflow.md

Fix the Guidelines URL - The referenced "Guidelines' doc is in the parent directory, not in the current.

docs: fix not working link

---

packages/main/src/themes/DateRangePicker.css

When the ui5-datepicker has been renamed to ui5-date-picker, and the class .ui5-datepicker-input to .ui5-date-picker-input, the DateRangePicker.css has not been updated.

chore(ui5-daterange-picker): fix min-width

---

packages/main/src/Table.js
packages/main/src/TableRow.hbs
packages/main/src/TableRow.js
packages/main/test/specs/Table.spec.js

Upon accessing the row, all cells and the respective columns they are within, should be announced in the following order: column - cell, column - cell, etc.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2160

fix(ui5-table-row): announce entire row and columns

---

README.md
docs/Assets.md
docs/FAQ.md
docs/Public Module Imports.md
docs/Scoping.md
docs/dev/Development Workflow.md

See the proposed readme here: https://github.com/SAP/ui5-webcomponents/tree/readme-refactor
and the new article here: https://github.com/SAP/ui5-webcomponents/blob/readme-refactor/docs/Scoping.md
Initially there was fewer information in the readme, but with time we added more and more.
The goal of the change is to update the main `README.md` file in several aspects:
- Break down several key paragraphs to bullet lists to make them easier to read
- Make some of the content more easily understandable for people outside of SAP
- Replace the paragraph explaining what web components are with a bullet list, highlighting why we chose web components (assumption is that people already universally know what a web component means)
- Add more links to other `.md` files
- Combine the OpenUI5 and Web …

chore: Update README.md and add Scoping.md

---

packages/main/src/DatePicker.js
packages/main/src/DatePickerPopover.hbs
packages/main/src/DateTimePicker.js
packages/main/src/Popover.js
packages/main/src/themes/PopupsCommon.css

Fixes: https://github.com/SAP/ui5-webcomponents/issues/2012

fix(ui5-datetime-picker): fix scrollbar issue in IE11

---

packages/main/src/DatePickerPopover.hbs
packages/main/src/DateRangePicker.js

Prior to this change, when DateRangePicker was removed from the DOM, JS error occured, while removing the event listeners  in onExitDom. Now they are removed every time the DateRangePicker is closed.

fix(ui5-daterange-picker): fix js error when removed from the DOM

---

packages/main/src/Input.js
packages/main/src/MultiComboBox.hbs
packages/main/src/MultiComboBox.js
packages/main/src/MultiInput.hbs
packages/main/src/MultiInput.js
packages/main/src/Token.hbs
packages/main/src/Token.js
packages/main/src/Tokenizer.hbs
packages/main/src/Tokenizer.js

FIXES: #1534 
Imporoved keyboard handling for both components according to the specifications, making it consistent with the UI5 Controls.
- Arrow Left / Down / Right / Up
- Space
- Delete
- Backspace

feat(ui5-multiinput, ui5-multi-combobox): implement keyboard handling

---

packages/main/src/Calendar.js

FIXES: https://github.com/SAP/ui5-webcomponents/issues/2202

fix(ui5-calendar): Year text is now right in all timezones

---

packages/main/src/Token.hbs
packages/main/src/Token.js
packages/main/src/themes/Token.css
packages/main/test/pages/MultiInput.html

feat(ui5-token): provide closeIcon slot

---

packages/main/src/Popover.js
packages/main/src/TabContainer.hbs
packages/main/src/TabContainer.js
packages/main/src/themes/TabContainer.css
packages/main/test/pages/TabContainer.html

feat(ui5-tab-container): implement overflow-button slot

---

packages/base/src/InitialConfiguration.js
packages/base/src/asset-registries/i18n.js
packages/base/src/config/Language.js
packages/main/test/pages/i18n-defaultLang.html
packages/tools/lib/generate-json-imports/i18n.js

After the change all languages would be fetched over the network, including the defaultLanguage, that we have inlined. This will be the default behaviour. However, there is a new configuration option to stop fetching the default language, called "useDefaultLanguage". When the "useDefaultLanguage" is enabled,
the inlined texts will be used instead.
To test, open the http://localhost:8080/test-resources/pages/i18n-defaultLang.html page and enable and disable the option. Check the "Network" tab. When enabled - the i18n translation file is not fetched and when disabled - the i18n translation file is fetched.
```html
<script data-ui5-config type="application/json">{"useDefaultLanguage": true}</script>
```
Related to: https://github.com/SAP/ui5-webcomponents/issues/2169

refactor(framework):  fetch default language

---

.travis.yml
README.md
docs/Configuration.md
packages/base/src/InitialConfiguration.js
packages/base/src/asset-registries/Icons.js
packages/base/src/asset-registries/LocaleData.js
packages/base/src/asset-registries/Themes.js
packages/base/src/asset-registries/i18n.js
packages/base/src/config/AssetsPath.js
packages/base/src/util/getEffectiveAssetPath.js
packages/main/bundle.esm.js
packages/main/test/pages/DatePicker.html
packages/main/test/pages/Kitchen.html
packages/tools/components-package/nps.js
packages/tools/components-package/rollup.js
packages/tools/package.json
yarn.lock

This has been a highly requested feature for a long time. Although resource path is a build-time artefact, it often makes sense to build once and deploy in multiple, previously unknown directories. 
Changes:
- New configuration setting: `assetsPath`
- Users have the capability to build with `DEPLOY_PUBLIC_PATH` or to use `assetsPath` at runtime (or both).
**Option1**: build-time
```
DEPLOY_PUBLIC_PATH=/my/resources/ yarn build
```
(for Windows: `DEPLOY_PUBLIC_PATH="\/my\/resources\/" yarn build`)
**Option2**: runtime
```html
<script data-ui5-config type="application/json">
{
"assetsPath": "/my/resources/"
}
</script>
```
BREAKING CHANGE: Running the production build command: `yarn build` will now generate the `.json` resources asset paths without `/resources/` in the beginning. The `yarn …

feat(framework): make assets path configurable

---

packages/base/src/util/isValidPropertyName.js

According to SAP guidelines the words `slave`, `master`, `whitelist` and `blacklist` should be avoided due to being insensitive. These terms should be replaced with the recommended ones.
https://help.sap.com/doc/b0322267728e48a28b0c8ee7dd1ab4c7/1.0/en-US/Inclusive%20Language%20Guidelines.pdf

chore(framework): Do not use insensitive words

---

packages/main/src/themes/DatePicker.css
packages/main/src/themes/DateRangePicker.css
packages/main/src/themes/DateTimePicker.css
packages/theme-base/css-vars-usage.json

Until now the user can not set a DateRangePicker, DateTimePicker to a width smaller than 15rem, as 15 rem is their min-width.
Now we enable that by making the min-width propagated from the host to inner input.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2194

chore(ui5-date-*): make width customizable

---

packages/fiori/src/FlexibleColumnLayout.hbs
packages/fiori/src/FlexibleColumnLayout.js
packages/fiori/src/i18n/messagebundle.properties
packages/fiori/test/pages/FCL.html
packages/fiori/test/specs/FCL.spec.js

Add tooltip and aria-label to the toggle columns arrow to match the screen reader spec.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2226

fix(ui5-flexible-column-layout) fix arrows screen reader suport

---

packages/base/src/UI5Element.js
packages/base/src/theming/CSSVarsPonyfill.js

The goal of this change is to provide **limited** support for `compact` mode to IE11.
*Background:* Compact mode is entirely dynamic. The way to achieve it is with CSS variables, defined for compact mode markers (attribute or class). Example:
```css
[data-ui5-compact-size],
.ui5-content-density-compact,
.sapUiSizeCompact {
--_ui5_button_base_height: 1.625rem;
...................................
}
```
The IE CSS Vars ponyfill on the other hand can only handle variables on `:root` and `:host` since it needs to generate static CSS declarations.
*IE11 limitation*: 
- Compact mode only works for the page as a whole - you must set the `data-ui5-compact-size` attribute, the `ui5-content-density-compact` class or the `sapUiSizeCompact` class on the **body** element only.
- Compact mode is **not …

feat(framework): Limited support for campact size on IE

---

packages/fiori/src/FlexibleColumnLayout.hbs

Add template hooks for the toggle arrows of thew Flexible Column Layout, so that a derived class can fully customize them.
For example: provide different or new ARIA attributes, change the values of existing ones, etc. 
In order to that, the derived class should include the FCL template and overwrite the newly added "startArrow" and "endArrow" template hooks.
_Note: We considered providing slots or properties, but we wanted to keep the API more simple and agreed on this solution._
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2183

chore(ui5-fcl): add template hooks for toggle arrows

---

packages/main/src/themes/Input.css

fix(ui5-select): fix text color of disabled select in hcb/hcw

---

packages/main/src/MultiComboBox.hbs
packages/main/src/MultiComboBox.js
packages/main/src/MultiComboBoxPopover.hbs
packages/main/src/i18n/messagebundle.properties
packages/main/test/pages/MultiComboBox.html

Implement valueStateMessage support for MultiComboBox component.
FIXES: #1086

feat(ui5-multi-combobox): Implement valueStateMessage

---

packages/main/src/DayPicker.js
packages/main/src/TimePicker.js
packages/main/src/WheelSlider.js

Several modules were imported incorrectly, breaking the OpenUI5 retrofit builds.
Import rules:
- only import from `dist/`, never from `src/`
- imports from other packages must be with the full qualifier, e.g. `@ui5/webcomponents-base/...`, never with relative paths

chore: fix imports

---

packages/main/src/CalendarHeader.hbs
packages/main/src/CalendarHeader.js

fix(ui5-calendar-header): prevent scrolling when month/year picker is selected

---

packages/main/src/DayPicker.hbs
packages/main/src/DayPicker.js

This PR complements the following PR https://github.com/SAP/ui5-webcomponents/pull/2276
to fix everything requested by the referenced issue, more specifically forcing date selection with SPACE to take place on keyup, instead of keydown as at the moment.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2268

fix(ui5-date-picker): select date with SPACE on keyup

---

packages/fiori/test/samples/SideNavigation.sample.html

Prior to this change, the ```ui5-side-navigation``` sample used to overflow out of its parent div

chore(playground): fix ui5-side-navigation sample

---

packages/base/src/theming/createComponentStyleTag.js

Do not create component styles for IE11 with `disabled`, because if they don't contain at least one CSS Variable, they will not be processed by the CSS Vars ponyfill. It will skip them, and not create new styles with the compiled static CSS. Thus they will remain `disabled` and not have any effect on the page.
The bug can only be seen with components that don't have at least one CSS Var in their styles.
closes: https://github.com/SAP/ui5-webcomponents/issues/2283

fix(framework): Do not create IE styles with disabled

---

packages/main/src/DayPicker.js
packages/main/test/pages/DatePicker.html
packages/main/test/specs/DatePicker.spec.js

Fixing small issues found during implementation of tasks.

fix(ui5-date-picker): fixed samples and daypicker limits

---

packages/main/src/DateRangePicker.js
packages/main/src/DayPicker.js
packages/main/test/specs/DateRangePicker.spec.js

fixes: https://github.com/SAP/ui5-webcomponents/issues/2221

fix(ui5-daterange-picker): fixed getters for first and last date values

---

packages/main/src/themes/ListItem.css

When **ui5-li** has image and byline (description), the image should have 3rem height and 3rem width in Compact and Cozy mode. In addition its angles should be rounded.
Part of #2218

fix(ui5-li): correct image size

---

packages/base/src/util/isValidPropertyName.js
packages/main/src/Dialog.hbs
packages/main/src/Dialog.js
packages/main/src/themes/Dialog.css
packages/main/test/pages/Dialog.html
packages/main/test/specs/Dialog.spec.js

feat(ui5-dialog): introduce draggable property

---

packages/base/src/UI5Element.js
packages/base/src/util/isValidPropertyName.js

Allow `role` as a property name for UI5 Web Components.
Additionally, allow developers to override any property, but produce a warning except for the allowed.

fix(framework): Allow role as a property name

---

packages/main/src/Input.js
packages/main/test/pages/Input.html
packages/main/test/specs/Input.spec.js

When the users navigates between the items with UP/DOWN, the value is updated and shows the currently previewed item,
Now, the user is able to "cancel" this selection by pressing ESC.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2254

fix(ui5-input): cancel suggestion selection with ESC

---

packages/base/src/Theming.js
packages/base/src/theming/ThemeLoaded.js
packages/base/src/theming/applyTheme.js
packages/main/bundle.esm.js

Sometimes apps need to know exactly when the theme load has completed. To support this, we enrich `Theming.js` with two functions: `attachThemeLoaded` and `detachThemeLoaded`.
closes: https://github.com/SAP/ui5-webcomponents/issues/2197

feat(framework): Add API to subscribe/unsubscribe for theme loaded

---

packages/main/src/ListItem.js
packages/main/src/themes/ListItem.css
packages/main/src/themes/base/sizes-parameters.css
packages/main/test/pages/List.html

- info text is align centrally and it is align bottom if description attribute exists
- title text is align centrally and it is align top if description attribute exists
- item's height is changed to 5rem if description / image attribute exist
- checkbox / radio button is positioned correctly
In addition:
- align **ui5-li-custom**'s checkbox / radio button size is align to visual specification (44px / 2.75rem)
Thеre is no affected controls.
Fix: #2297
Fix: #2218

fix(ui5-li): visual alignment

---

packages/main/src/themes/Switch.css

This change fixes the wrong focus border position:
It's 2px more from the right side because the border itself is not considered.
Alternative solution would be:
```
box-sizing: border-box;
```
But using `width=100%` with absolutely positioned elements in general is not a best practice.

fix(ui5-switch): fix focus border position

---

packages/base/src/asset-registries/LocaleData.js
packages/main/test/pages/RTL.html

When there is a component that uses CLDR and someone calls **setLanguage**,
this causes the webcomponents to re-render and recalculate their state and it turns out that the CLDR for the newly set language is missing and JS error is thrown ("Error: CLDR data for locale de is not loaded").
Currently, this can be seen in our "RTL.html" page, if we add a DatePicker and then use the buttons on the page to change the language. This PR ensures that upon setLanguage, the CLDR is fetched/updated before the re-rendering.
On the other hand, there is **applyDirection** API that also force re-rendering, that if used together with setLanguage, should wait for the setLanguage to complete to allow the message bundles (although they won't fail with JS error) and CLDR to load.
``` …
```

fix: fix JS error on setLanguage call

---

packages/main/src/Dialog.hbs
packages/main/src/Dialog.js
packages/main/src/themes/Dialog.css
packages/main/src/themes/base/Dialog-parameters.css
packages/main/src/themes/base/sizes-parameters.css
packages/main/src/themes/sap_belize/Dialog-parameters.css
packages/main/src/themes/sap_belize/parameters-bundle.css
packages/main/src/themes/sap_belize_hcb/Dialog-parameters.css
packages/main/src/themes/sap_belize_hcb/parameters-bundle.css
packages/main/src/themes/sap_belize_hcw/Dialog-parameters.css
packages/main/src/themes/sap_belize_hcw/parameters-bundle.css
packages/main/src/themes/sap_fiori_3/parameters-bundle.css
packages/main/src/themes/sap_fiori_3_dark/parameters-bundle.css
packages/main/src/themes/sap_fiori_3_hcb/parameters-bundle.css
packages/main/src/themes/sap_fiori_3_hcw/parameters-bundle.css
packages/main/test/pages/Dialog.html
packages/main/test/specs/Dialog.spec.js
packages/tools/components-package/wdio.js

feat(ui5-dialog): introduce resizable property

---

packages/main/src/Link.hbs
packages/main/src/Link.js
packages/main/test/pages/Link.html
packages/main/test/specs/Link.spec.js

FIXES: https://github.com/SAP/ui5-webcomponents/issues/2356
**Side effect:** On VoiceOver the aria-label is read twice.

feat(ui5-link): add aria-label and aria-labelledby support

---

packages/main/src/MultiComboBox.js
packages/main/src/MultiComboBoxPopover.hbs

fix(ui5-multi-combobox): n-more popover in readonly fixed

---

packages/main/src/themes/DayPicker.css
packages/main/src/themes/base/DayPicker-parameters.css
packages/main/src/themes/sap_belize_hcb/DatePicker-parameters.css
packages/main/src/themes/sap_belize_hcw/DayPicker-parameters.css
packages/main/src/themes/sap_fiori_3_hcb/DayPicker-parameters.css
packages/main/src/themes/sap_fiori_3_hcw/DayPicker-parameters.css

We had contrast ratio issue between the purple outline and black border around the selected day:
The black border turns out to be wrong,  by design it should have been white and can be seen after the change:
FIXES https://github.com/SAP/ui5-webcomponents/issues/2372

fix(ui5-day-picker): fix color contrast of selected day in HCB

---

packages/main/src/StandardListItem.hbs
packages/main/test/pages/List_test_page.html
packages/main/test/specs/List.spec.js

When the textContent is an empty string initially, the following element, containing the "slot" for the title text is not rendered:
`<span part="title" class="ui5-li-title"><slot></slot></span>`
Later when we update the "textContent" is not displayed as it relies on the slotting, but the "slot" element is not there.
The issue has been found in a specific Select use case, referenced below. That's why I considered making a "ui5-select-list-item" and make that change in a separate template, but I can't find side effects or visual degradations.
FIXES https://github.com/SAP/ui5-webcomponents/issues/2342

fix(ui5-li): fix title update when initially empty

---

packages/base/src/theming/CSSVarsPonyfill.js

CSSVarsPonyfill creates the following attributes:
- `data-cssvars`
- `data-cssvars-job`
- `data-cssvars-group`
The counters for "job" and "group" are internal and are not shared among all instances of the ponyfill. Therefore if several ponyfills operate on the same page, there might be inconsistencies and some styles may not be processed.
Therefore we remove the `data-cssvars-group` attribute for all elements' styles before running the ponyfill to make sure all will be processed.

chore(framework): Improve behavior with multiple CSSVarsPonyfills

---

packages/main/src/ComboBox.js

Allow typing in the input field when using a mobile device.
FIXES: #2324

fix(ui5-combobox): allow typing in input on mobile devices

---

packages/main/src/Dialog.js
packages/main/src/Popup.js

fix(ui5-dialog): no longer gets clipped in short screen height in IE

---

packages/main/src/ComboBox.js
packages/main/test/specs/ComboBox.spec.js

fix(ui5-ComboBox):  avoid flickering problem
use the right activeElement by focus-checking to solve the flickering problem of the comboBox.
Fixes #2365

fix(ui5-ComboBox):  avoid flickering problem

---

packages/main/src/Dialog.js
packages/main/src/themes/Dialog.css
packages/main/test/pages/DialogLifecycle.html

Fixes: #2270
Bug in Chromium-based browsers (https://bugs.chromium.org/p/chromium/issues/detail?id=783388)
causes elements with transform translate applied to be blurred
due to values ending up resulting in fractional values.
As a workaround, ui5-dialog is now centered using position fixed (with top and left).

fix(ui5-dialog): Texts are no longer blurred in Chromium-based browsers

---

packages/base/src/locale/getLocale.js
packages/localization/src/getCachedLocaleDataInstance.js
packages/main/src/Calendar.js
packages/main/src/DatePicker.js
packages/main/src/DateTimePicker.js
packages/main/src/DayPicker.js
packages/main/src/MonthPicker.js
packages/main/src/TimePicker.js
packages/main/src/YearPicker.js
packages/main/test/pages/Simple.html
packages/main/test/specs/MultiComboBox.spec.js

This change addresses several problems with the usage of locale-related classes in all date/time components:
- `languageAware` missing for a couple of components that depend on locale data
- `LocaleData.js` used to be instantiated in the **constructor** for several components. This means that even if the locale changes at runtime, the instance of `LocaleData.js` will never update. Therefore it must be in `onBeforeRendering` instead.
- The `base/src/locale/Locale.js` and `localization/LocaleData.js` class instances can be reused among all components as they are read-only once initialized
fixes: https://github.com/SAP/ui5-webcomponents/issues/2439

fix: Several date/time components use locales correctly

---

packages/main/src/themes/TextArea.css

Previously (with this change https://github.com/SAP/ui5-webcomponents/pull/2340/)when [placeholder] attribute is present,  we used to set italic to both standard and placeholder text. Now we are applying "italic" to the placeholder text only.

fix(ui5-textarea): set italic to placeholder only

---

packages/main/src/Select.hbs
packages/main/src/Select.js
packages/main/src/i18n/messagebundle.properties

The reledescription prevents its role button to be read by JAWS
so it is now removed following consultation with ACC expert.
Fixes #2358

fix(ui5-select): remove aria-roledescription

---

packages/main/src/DateRangePicker.js

the previous import was crashing in UI5 Web Components React

fix(ui5-daterange-picker): fix RenderScheduler import

---

packages/main/src/CustomListItem.js
packages/main/test/pages/List_test_page.html
packages/main/test/specs/List.spec.js

fix(ui5-li-custom): prevent firing of events

---

packages/main/src/Dialog.js
packages/main/src/Popover.js
packages/main/src/Popup.js
packages/main/test/pages/Popover.html
packages/main/test/specs/Popover.spec.js

feat(ui5-popover): implement hide-block-layer property

---

packages/main/src/ComboBoxItem.js
packages/main/src/ComboBoxPopover.hbs
packages/main/test/pages/ComboBox.html
packages/main/test/samples/ComboBox.sample.html
packages/main/test/specs/ComboBox.spec.js

This change adds support for two-column layout in the ComboBox web component so that the apps can display additional information for the selection options, such as currencies, country abbreviations, or system abbreviations. 
**Overview**
New property `additionalText` is added to the ComboBoxItem.js
**Usage**
```
<ui5-combobox>
<ui5-cb-item text="Bulgaria" additional-text="BG"></ui5-cb-item>
</ui5-combobox>
```
Feature request: #2450

feat(ui5-combobox): аdd two-column layout support

---

packages/main/src/RangeSlider.js
packages/main/src/Slider.js
packages/main/src/SliderBase.js
packages/main/test/samples/RangeSlider.sample.html
packages/main/test/samples/Slider.sample.html
packages/playground/build-scripts/samples-prepare.js

- "appendocs SliderBase" is creating a section for the SliderBase, but instead we want to show the API of the Slider (and the RangeSLider) as it's own,
without any mentions of SliderBase 
- the directionStart getter used to appear as public property (this is some jsdoc plugin related bug), I had to make it private
- mark Slider and RangeSlider as new components

docs: fix (Range)Slider API ref

---

packages/tools/components-package/rollup.js

fix for the build time `Error: kill EPERM`

fix: build error on MacOS 11 from rollup-plugin-terser

---

packages/main/src/Button.hbs
packages/main/src/Button.js
packages/main/test/pages/Button.html

Fixes #2393
Going for this implementation as the tooltip is not read out twice.
Note: Tooltips should only be set to icon only buttons.

feat(ui5-button): implement title property

---

packages/fiori/src/SideNavigation.hbs
packages/fiori/src/SideNavigation.js
packages/fiori/src/themes/SideNavigation.css
packages/fiori/test/pages/SideNavigation.html
packages/fiori/test/specs/SideNavigation.spec.js

Provide API, header slot, displayed in the top-most area of the SideNavigation component to enable users adding additional information, usually profile/user data, avatar, etc.
Also includes a minor fix (min-width: 3rem;) that prevents the SideNavigation (when collapsed) from shrinking due to resize.
FIXES https://github.com/SAP/ui5-webcomponents/issues/2518

feat(ui5-side-navigation): add "header" slot

---

packages/base/src/UI5Element.js
packages/fiori/src/UploadCollection.hbs
packages/fiori/src/UploadCollection.js

fix(ui5-upload-collection): fire drop only when files are dropped within dnd overlay

---

packages/main/src/List.hbs
packages/main/src/List.js

This PR fixes a problem in ```ui5-list```.
Prior to this change, two divs for focus trapping were always rendered.
After this change they are only rendered if there is at least one item in the list.(Not rendered for empty lists)

fix(ui5-list): remove focus trap for empty list

---

packages/main/src/DayPicker.js

fixes: https://github.com/SAP/ui5-webcomponents/issues/2542

fix(ui5-date-picker): fixing the min and max date in timezones half hour difference

---

packages/main/.eslintignore
packages/tools/lib/jsdoc/config.json

Exclude directory, named "thirdparty" from jsdoc generation.

chore: exclude thirdparty from jsdoc generation

---

packages/fiori/src/themes/Wizard.css

- set default content background (equivalent to Standard in openui5)
- remove additional space from the content bottom
FIXES https://github.com/SAP/ui5-webcomponents/issues/2523

fix(ui5-wizard): fix styling issues

---

packages/main/src/themes/Badge.css

The RTL styles would be applied when we use the right selector [dir="rtl"], not just [rtl].

fix(ui5-badge): fix RTL appearance

---

packages/base/src/UI5Element.js
packages/base/src/util/FocusableElements.js
packages/main/src/Popup.js
packages/main/test/pages/Dialog.html
packages/main/test/specs/Dialog.spec.js

Now the initial focus is applied also in cases when the dialog
is opened before it is fully rendered.
Fixes: #2537

fix(ui5-dialog): apply initial focus after rendering

---

packages/main/src/Card.hbs
packages/main/src/Card.js
packages/main/test/pages/Card.html
packages/main/test/specs/Card.spec.js

Now the aria-labelledBy of card and header contain only the rendered elements.
Fixes: #2426

fix(ui5-card): correct aria-labelledBy to card and header

---

packages/fiori/src/FlexibleColumnLayout.js
packages/fiori/test/pages/FCL.html
packages/fiori/test/pages/FCLApp.html
packages/fiori/test/specs/FCL.spec.js

This PR changes the way accessibility-related texts are provided in order to customize `FlexibleColumnLayout`.
A new property called `accessibilityTexts` is added and it serves as a central place for all such texts.
**Note:** Since this property is of type `Object`, it does not support an attribute counterpart.
BREAKING CHANGE: the `startColumnAccessibleName`, `midColumnAccessibleName` and `endColumnAccessibleName` properties have been removed. Use the new `accessibilityTexts` property to provide these (as keys to the object).
closes: https://github.com/SAP/ui5-webcomponents/issues/2183

refactor(ui5-flexible-column-layout): Add more accessibility texts

---

docs/Public Module Imports.md
packages/fiori/bundle.esm.js
packages/fiori/src/NotificationAction.js
packages/fiori/src/NotificationListGroupItem.js
packages/fiori/src/NotificationListItem.js
packages/fiori/src/NotificationListItemBase.js
packages/fiori/test/pages/NotificationListGroupItem.html
packages/fiori/test/pages/NotificationListItem.html
packages/fiori/test/pages/NotificationList_test_page.html
packages/fiori/test/samples/NotificationListGroupItem.sample.html
packages/fiori/test/samples/NotificationListItem.sample.html

Based on the feedback that NotificationOverflowAction is not completely matching its purpose and usage, as it can be both displayed within and out of the overflow popover of a notification item. We decided to rename it as follows:
- rename `NotificationOverflowAction` -> `NotificationAction`
- rename `ui5-notification-overflow-action` to `ui5-notification-action`
BREAKING_CHANGE If you previously used `ui5-notification-overflow-action` and had the following import statement:
```js
import "@ui5/webcomponents-fiori/dist/NotificationOverflowAction.js";
```
now you have to  use the `ui5-notification-action` tag and import  the following module:
```js
import "@ui5/webcomponents-fiori/dist/NotificationAction.js";
```

refactor(ui5-notification-action): rename component

---

packages/fiori/src/ProductSwitch.js
packages/fiori/src/Timeline.hbs
packages/fiori/src/Timeline.js
packages/fiori/src/Wizard.js
packages/main/src/AvatarGroup.js
packages/main/src/List.js
packages/main/src/SegmentedButton.js
packages/main/src/TabContainer.js
packages/main/src/Tokenizer.js

This change refactors the usage of `ItemNavigation.js` for all components except date/time related ones (which will be addressed separately).
Changes:
- Now that `getItemsCallback` can be set in the constructor, this is the preferable way of passing it. This also eliminates the need of a separate `initItemNavigation` function that many components had as they needed 2 lines of code - `new ItemNavigation` and to set the callback.
- Implement the `focusin` event for `Timeline.js` as it did not update the item navigation like the rest of the components whenever the user clicks with the mouse.
- Do not use `ItemNavigation.prototype.current` any more (it is marked as deprecated). Always call `update` instead.
- Do not use `ItemNavigation.prototype.currentIndex` any more (it is private). Always …

refactor: use ItemNavigation optimally

---

packages/main/src/themes/Avatar.css
packages/main/test/pages/AvatarGroup.html

With the introduce of the AvatarGroup the XS size of the Avatar has been broken. Due to the following css the XS size appeared 3rem X 3rem, instead of 2rem X 2rem (as it is by spec). The "XS" styles define min-height and min-width, but the default styles make it 3rem by 3rem.
```css
:host {
height: 3rem;
width: 3rem;
}
:host([_size="XS"]),
:host([size="XS"]) {
min-height: 2rem;
min-width: 2rem;
font-size: .75rem;
}
```

fix(ui5-avatar): fix XS size

---

packages/base/src/delegate/ItemNavigation.js
packages/main/src/Calendar.js
packages/main/src/DatePicker.js
packages/main/src/DayPicker.js
packages/main/src/MonthPicker.js
packages/main/src/PickerBase.js
packages/main/src/TimePicker.js
packages/main/src/YearPicker.js
packages/main/src/util/DateTime.js

Changes:
- The `PageBottom` and `PageUp` events used only in `DayPicker.js` were removed from `ItemNavigation.js` and replaced with callbacks. Publish/subscribe is not the ideal design pattern for this type of communication, because the communication is two-directional. ItemNavigation tells DayPicker that it needs to know whether there is a previous/next page, and DayPicker responds back (by changing ItemNavigation state - prevPage/nextPage in the callback). Then, based on this state ItemNavigation continues execution. This is more transparently achieved with callbacks.
- All copy/pasted code (about 200 lines) between `Calendar`, `DayPicker`, `MonthPicker` and `YearPicker` was moved to a base class for these 4. There were only 2 different things: 
`return minDate.valueOf();`  vs  `return …

refactor: Date/time components refactoring part 1

---

packages/main/src/DayPicker.js
packages/main/src/MonthPicker.js
packages/main/src/YearPicker.js

Changes:
- create `focusableMonths` and `focusableYears` similarly to `focusableDays`. Use these to search for items intead of querying the ItemNavigation.
- Use the `update` function and just pass the item instead of doing complex calculations to determine its index.

refactor: simplify ItemNavigation usage in datetime components

---

packages/base/src/UI5Element.js
packages/main/src/Option.js
packages/main/src/Select.js
packages/main/src/SelectPopover.hbs

feat(ui5-option): provide stabledomref

---

packages/fiori/src/Wizard.js

The Phone breakpoint used to be wrong, it is updated from 559 to 599 (as defined in the visual design)

fix(ui5-wizard): correct phone breakpoint size

---

packages/fiori/src/themes/Bar.css
packages/fiori/test/pages/Bar.html

**Background**
Ensure ui5-icon is displayed when used inside ui5-bar. Currently the ui5-icon does not get displayed.
```html
<ui5-bar>
<ui5-icon name="home" slot="startContent"></ui5-icon>
</ui5-bar>
```
**Change**
Remove **"::slotted(*) { display: flex;"** because this  CSS breaks ui5-icon's display.
It was added to provide better support for multi levels of children like:
```html
<ui5-bar>
<div slot>
<ui5-button>
</div>
</ui5-bar>
```
But now we just let users add do it, instead of us. As shown below, everyone can add **"display: flex; align-items: center;"** to their own slotted elements. Moreover, this is not the main use-case we support.
```html
<ui5-bar>
<div slot="startContent" style="display: flex; align-items: center;">
<ui5-button>Start Button</ui5-button>
<ui5-label>Basic …
```

fix(ui5-bar): display ui5-icon properly inside bar

---

packages/main/src/Select.hbs
packages/main/src/Select.js
packages/main/src/themes/Select.css
packages/main/test/pages/Select.html
packages/main/test/specs/Select.spec.js

Role of the ui5-select is changed to combobox which change the speech output near to the default behavior. Issue where role="button" can't be used with aria-required / required attribute is fixed. Overwriting the aria-label speech output with aria-labelledby is fixed.
Fixes: #2485 
Fixes: #2339
Fixes: #2142

fix(ui5-select): correct role and screen reader speech out

---

packages/main/src/Dialog.js
packages/main/src/Popover.js
packages/main/src/Popup.hbs
packages/main/src/Popup.js
packages/main/src/themes/PopupsCommon.css
packages/main/test/pages/Popover.html
packages/main/test/specs/Popover.spec.js

When there is no focusable content, the focus should be on the root of the component.
Fixes SAP#2556

fix(ui5-popup): correct focus when there is no focusable content

---

packages/fiori/src/NotificationListGroupItem.hbs
packages/fiori/src/NotificationListGroupItem.js
packages/fiori/src/NotificationListItem.hbs
packages/fiori/src/NotificationListItem.js
packages/fiori/src/NotificationListItemBase.js
packages/fiori/src/i18n/messagebundle.properties
packages/fiori/src/themes/NotificationListGroupItem.css
packages/fiori/src/themes/NotificationListItem.css
packages/fiori/test/pages/NotificationListGroupItem.html
packages/fiori/test/specs/NotificationList.spec.js

We identified gaps in the accessibility implementation, that this change aims to address as follows:
**NotificationListItem**
- More Button: added aria-label="More"
- Close Button: added aria-label="Close"
**NotificationListGroupItem**
- Invisible text reading: added "read" or "unread", based on the "read" property.
- Root: added aria-expanded="true"/"false", based on the "collapsed" property
- More Button: added aria-label="More"
- Close Button: added aria-label="Close All"
- Toggle Button added title="Collapse Group" ("Expand Group") and aria-label="Collapse Group" ("Expand Group") - based on the "collapsed" property
**NotificationListGroupItem**
- new property "read" (previously available in the NotificationListItem only)
**Note:** I didn't set **aria-setsize** and **aria-posinset**, …

feat(ui5-li-notification*): full-fill accessibility spec

---

packages/main/src/themes/Icon.css

Icons used to have a wrong double vertical flip. This was removed, but
the RTL selectors were missed.
Fixes #2644

fix(ui5-icon): remove vertical icon flip in RTL

---

packages/main/src/MultiComboBoxPopover.hbs
packages/main/test/pages/MultiComboBox.html
packages/main/test/specs/MultiComboBox.spec.js

Enables two-column layout items in the MultiComboBox.
The MultiComboBoxItem already inherits the **additionalText** property from the ComboBoxItem, but never used it. The property is visible in the API reference and misleading users that can have two-column layout in the MultiComboBox as well.
The change just uses the property in the template and forwards it to the physically rendered list item.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2637

feat(ui5-multi-combobox): support two column layout for items

---

packages/fiori/src/WizardStep.js

The default slot of ui5-wizard-step was not documented, now it will be part of the API reference.

docs(ui5-wizard-step): document content slot

---

packages/base/src/locale/applyDirection.js
packages/base/src/locale/directionChange.js
packages/main/bundle.esm.js
packages/main/test/pages/RTL.html

The usage of the new utility function is similar to, and modeled by `attachLanguageChange`.
If any of the attached callbacks returns a Promise, this promise will be awaited for, before re-rendering components. Otherwise components will be re-rendered immediately in the next microtask.
Example:
```js
import { attachDirectionChange } from "@ui5/webcomponents-base/dist/locale/directionChange.js";
attachDirectionChange(() => {
console.log("Direction changed");
});
```
closes: https://github.com/SAP/ui5-webcomponents/issues/2643

feat(framework): Create attachDirectionChange function

---

packages/tools/lib/create-icons/index.js

Icons are now available as standalone SVG assets.
Usage example with react
```jsx
import flightIcon from '@ui5/webcomponents-icons/dist/flight.svg';
const App = () => {
return (
);
}
```

feat(icons): add icon assets as .svg files

---

packages/main/src/MultiComboBox.js

Prior to this change, if you have a multicombobox with placeholder, the filtration was not working on mobile devices(when dialog is opened)

fix(ui5-multi-combobox): fix livechange behaviour

---

packages/localization/src/dates/getTodayUTCTimestamp.js
packages/main/src/CalendarPart.js
packages/main/src/DatePicker.js
packages/main/src/DateRangePicker.js
packages/main/test/samples/Calendar.sample.html

For several components the `Today` timestamp was not a UTC timestamp but rather a timestamp, representing the Local date (`new Date().getTime()`) opposed to the UTC Date. Now `new Date()` is never used to get today's timestamp. It is however fine for time-related components, therefore it's not changed there.
closes: https://github.com/SAP/ui5-webcomponents/issues/2655

fix(ui5-calendar): Today date is properly calculated

---

packages/fiori/src/UploadCollection.hbs

Now the noDataText and noDateDescription texts will wrap upon overflow. Prior to this change the texts truncate.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2672

fix(ui5-upload-collection): wrap noDataText/Desc text

---

packages/main/src/DateTimePicker.js
packages/main/src/TimePickerBase.js

Clean up leftover from the "focusInput" functionality option removal within two date-time components.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2495

chore: remove obsolete code

---

packages/main/src/Link.hbs
packages/main/src/Link.js

aria-disabled attribute is removed, and only the native one is present now.
fixes: https://github.com/SAP/ui5-webcomponents/issues/2673

fix(ui5-link): Removed aria-disabled attribute

---

packages/main/src/Select.hbs
packages/main/src/Select.js

When the accessibility refactoring of was done the focus reference was changed. The click event should focus the correct element so the internal rules which controls the visibility of value state could pass.
Fixes: #2682

fix(ui5-select): fix popover opening

---

packages/main/src/ComboBox.js

The value in `ui5-combobox` no longer stays selected after it was set from the suggested items via the 'enter' key.
Issue: #2273

fix(ui5-combobox) clear selection when item is selected with 'enter'

---

packages/main/src/Avatar.js
packages/playground/_layouts/docs.html

Hey there,
I've adjusted some minor things in the docs/playground as 
- added missing single quote on import statement (copy & paste without the need for manual fix) and
- adjusted the path to the sap logo svg (SAP logo isn't displayed)
I did look at the contribution checklist and hope that everything is in order. I couldn't get the playground running locally but checked the url for the SAP logo myself. Hope it is fine.

fix(docs) SAP logo not shown in playground and missing start quote in Avatar.js

---

packages/main/src/List.hbs
packages/main/src/List.js
packages/main/src/themes/List.css
packages/main/test/pages/List.html
packages/main/test/pages/List_test_page.html

**Changes**
- Show busy indicator over the list (as specified in Fiori 3), not at the bottom (as it is prior to this change).
- Fade background with opacity (0.72), closest to openui5 where we have calculated background - fade(@sapBackgroundColor, 72%)
**Technical details**
- introduce new div element ("ui5-list-scroll-container") that is scrollable (overflows), so we can position the busy indicator centrally against the root element, otherwise such positioning with overflow enabled is possible only with position: fixed, which is a bad pattern.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2568

fix(ui5-list): show busy indicator over the list

---

packages/main/src/List.hbs
packages/main/test/specs/List.spec.js

Follow up of https://github.com/SAP/ui5-webcomponents/pull/2684 where the placement of the busy has been fixed. With this change we make sure the busy ind DOM is not even rendered when the List is not busy. And aims to fix the issue with components such as the ComboBox and Select and Input that uses the List internally would display additional space after the last list item.

fix(ui5-list): remove busy indicator DOM

---

packages/main/src/Input.js

The API is deleted, since it is never used.
Fixes: #2605

fix(ui5-input): Obsolete accessibility API removed

---

packages/main/src/List.js
packages/main/test/pages/List_test_page.html
packages/main/test/specs/List.spec.js

Fixe a JS error that used to thrown upon "focusin" when non-existing DOM elements have been accessed. Those DOM elements are not rendered when there are no list items, which is the example in the referenced issue.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2717

fix(ui5-list): fix JS error on focusin

---

packages/main/src/Input.js
packages/main/src/MultiInput.js
packages/main/test/pages/Input.html
packages/main/test/specs/Input.spec.js

Previously, on focus the ui5-input component, when the event target was ui5-input, the focused attribute was not added. As a result, the focus outline was not presented, as well as the suggestions were not visualised initially when used.
Fixes #2652

fix(ui5-input): focus is handled properly

---

packages/main/src/MultiComboBox.js

When ui5-multi-combobox web component is used on mobile phone and the list with the available options is visualised in a dialog, the initial focus on opening should be set to the dialog according to the specification.
Fixes: #2692

fix(ui5-multi-combobox): The initial focus is set on the ui5-dialog

---

packages/main/src/ComboBox.js
packages/main/src/MultiComboBox.js
packages/main/src/themes/ResponsivePopover.css
packages/main/src/themes/base/sizes-parameters.css

ValueState text is now vertically centered in the Popover's header.
Issue: #2274

fix(ui5-combobox, ui5-multicombobox): center ValueState text

---

packages/main/src/Input.js

ValueState text is now vertically centered in the Responsive Popover header of the suggestions.

fix(ui5-input) center ValueState text

---

packages/fiori/src/NotificationListItem.js
packages/fiori/test/pages/NotificationListItem.html

Since `description` is the default slot of type `Node`, there are usually at least some whitespaces such as new lines that go into that slot, so it is never empty, unless in the following marginal use case:
```
<ui5-li-notification></ui5-li-notification>
```
Then the component used to fail since there is no description DOM.

fix(ui5-li-notification): It is now possible to not have a description

---

packages/main/src/themes/Icon.css

- ui5-icon-root SVG is now forced with style "vertical-align: top"
which fixes the misalignment.
- No regressions introduced in the rest of the browsers
FIXES: https://github.com/SAP/ui5-webcomponents/issues/913

fix(ui5-icon): alignment issue in Safari

---

packages/main/src/themes/CheckBox.css

- redundant CSS styling is removed which was causing the issue

fix(ui5-checkbox): vertical misalignment when wrap is true

---

packages/main/src/List.js
packages/main/src/ListItem.hbs
packages/main/src/ListItemBase.js
packages/main/src/Option.js
packages/main/src/Select.js
packages/main/src/SelectPopover.hbs
packages/main/src/themes/ListItem.css
packages/main/src/themes/ListItemBase.css
packages/main/src/themes/base/ListItemBase-parameters.css
packages/main/test/pages/List_test_page.html
packages/main/test/pages/Select.html
packages/main/test/specs/List.spec.js
packages/main/test/specs/Select.spec.js

Allow the application specify select options as disabled. Disabled options are non-interactable.
Fixes: #2559

feat(ui5-select): Add support for disabled select options

---

packages/main/src/MultiComboBox.hbs
packages/main/src/MultiComboBox.js
packages/main/src/MultiInput.hbs
packages/main/src/MultiInput.js
packages/main/src/Tokenizer.js
packages/main/src/i18n/messagebundle.properties
packages/main/test/pages/MultiComboBox.html
packages/main/test/pages/MultiInput.html
packages/main/test/specs/MultiComboBox.spec.js
packages/main/test/specs/MultiInput.spec.js

ui5-multi-input is implemented according to the specification.
As part of the change, an existing accessibility issue in ui5-multi-combobox component is fixed as well. Now, the information about the contained tokens is added to aria-describedby attribute instead of aria-labelledby, because it is more appropriate, since the information is a descriptive text.
FIXES: #2705 
FIXES: #2459

feat(ui5-multi-input): Implement accessibility specifications

---

README.md
docs/Public Module Imports.md
packages/ie11/README.md

`UI5 Web Components` will no longer officially support `Internet Explorer 11` starting with `1.0.0-rc12`.
The `@ui5/webcomponents-11` package will continue to work and will be updated to keep the framework going in the near future, but compatibility is not guaranteed and the package might stop working at some point in the furure.

chore: Deprecate Internet Explorer 11

---

packages/main/src/themes/DatePicker.css
packages/main/src/themes/Input.css
packages/main/src/themes/TextArea.css

Allow letter spacing in the Input, TextArea, DatePicker, DateTimePicker, DateRangePicker components with common letter spacing tool that is based on three CSS properties - line-height, letter-spacing and word-spacing by setting their default values to the host and inherit them in the native input element.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2755
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2641

refactor(ui5-input, ui5-textarea, ui5-date-*): allow letter spacing

---

packages/playground/docs/landing-page.html

Remove statement for IE support and its logo

docs: remove IE statement from Playground

---

packages/base/src/UI5Element.js
packages/main/src/MultiInput.hbs

Each `UI5Element` instance is expected to have a single top-level DOM element, which is considered its `DOM Reference` (and returned by the `getDomRef` method. Usually this means that inside each `.hbs` template you are expected to create a single top-level DOM element, and lay out the component's structure inside it.
Changes:
- Not having a top-level element in the shadow root produces a warning
- `ui5-multi-input` DOM structure corrected to get rid of the warning for it.
Additionally, fixed an *unrelated* IE11 bug: the `createComponentStyleTag.js` method in the IE11 adaptor code is calling a non-existent function of `UI5Element.js`. This function was deleted by mistake and is now restored.

refactor(ui5-multi-input): Fix DOM structure

---

packages/main/src/RadioButton.js
packages/main/src/RadioButtonGroup.js
packages/main/test/pages/RadioButton.html
packages/main/test/specs/RadioButton.spec.js

**Background**
We used to set tabindex="0" to the selected item and tabindex="-1" to the rest, which works fine in all cases, besides the one reported in the issue - when the application wants to define a group without preselected item. In this case, all the radio buttons in the group have tabindex="-1" and as a result the group is not accessible via the keyboard.
**Solution**
Now, we calculate the tabindex for each item on every important action, such as: selection of item within the group, creating a new group, adding an item to the group or removal an item from the group. The logic considers the use-case from the issue as well - **If the group does not have a selected item, the first (not disabled) item would have tabindex="0"**.
In openui5, this is handled by the …

fix(ui5-radiobutton): fix tab order within group

---

packages/main/src/Input.hbs
packages/main/src/Input.js
packages/main/src/MultiInput.js
packages/main/test/pages/MultiInput.html
packages/main/test/specs/MultiInput.spec.js

fix(ui5-multiinput): hide placeholder when tokens

---

packages/main/src/Dialog.js
packages/main/src/Popover.js
packages/main/src/Popup.js
packages/main/test/pages/Popover.html
packages/main/test/specs/Popover.spec.js

Now when a popover is dynamically created it is shown only after its size can be determined.
This prevents its position to flicker on opening.
BREAKING CHANGE: The methods 'open' for Dialog and 'openBy' for Popover are now async
Fixes: https://github.com/SAP/ui5-webcomponents/issues/1755

fix(ui5-popover): correctly position a popover if dynamically created

---

packages/main/src/Dialog.js
packages/main/src/Popup.js
packages/main/test/specs/Dialog.spec.js

The block layer is created when #getStaticAreaItemDomRef is called, but the attribute "hidden" is not set at that time. Now it's set on onEnterDOM hook, unless the popup is already opened.
Fixes: #2696

fix(ui5-popup): hide block layer if popup is closed

---

packages/main/src/MultiComboBox.js

Fix JS error thrown on phone (Chrome phone emulator as well). It happens, because the selectedValues array is never declared, but accessed as "this.selectedValues.length" through the "_showAllItemsButtonPressed" getter upon initial rendering. To reproduce the issue you can use Chrome phone emulator and open https://sap.github.io/ui5-webcomponents/master/playground/main/pages/MultiComboBox/ on phone.

fix(ui5-multi-combobox): fix JS error on phone

---

packages/fiori/src/Wizard.js
packages/fiori/src/themes/Wizard.css
packages/fiori/test/pages/Wizard_test.html
packages/fiori/test/specs/Wizard.spec.js

Issue: When the step content size is changed runtime, step selection might go wrong as the steps' scroll positions are out of sync - the wizard works with the old ones.
Solution: Observe steps and update state to store steps' scroll positions.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2784
I recreated the setup - prior to the change after increasing the height of the current step at runtime and the user start to scroll, the selection moves to the previous step for a second (as shown in the referenced issue). Now, it is working fine:
https://user-images.githubusercontent.com/15702139/107360104-2e7a8f00-6ade-11eb-9d20-50954ab9f9d2.mov

fix(ui5-wizard): observe content height changes

---

packages/main/src/Popup.hbs
packages/main/src/Popup.js
packages/main/test/pages/Popover.html
packages/main/test/specs/Popover.spec.js

Problem:
The body element receives focus when an element inside the popup, which can't get focus (div, span) is clicked.
Then any element below the block layer can be focused.
Solution:
Don't let the focus leave the popup.
Fixes: #2626

fix(ui5-popup): prevent focus on elements below block layer

---

packages/main/test/specs/DateRangePicker.spec.js

- DateRangePicker test is using CTRL-A to reset
the state from the previous test.
- This fails on mac, so a quick fix is to
reopen the page to get a clean state.
- A follow-up fix will use a separate component so that tests do not
depend on the state of the previous test

test: fix failing test on mac

---

packages/main/src/Calendar.js
packages/main/src/DatePicker.js

When the users read the DatePicker/Calendar API reference it does not clear how to use different calendar types - Buddhist, Japanese, etc.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2792

docs: document calendarType usage

---

packages/tools/components-package/rollup.js

dynamic imports of assets introduce many new bundles, this change
improves the output
before:
```
bundle.esm.js → dist/resources...
164.4 KB
4.86 KB
4.61 KB
4.61 KB
```
after:
```
bundle.esm.js → dist/resources...
bundle.esm.js                       732.13 KB / gzipped: 164.37 KB
messagebundle_ar-5a7e48c6.js        55 B / gzipped: 75 B
messagebundle_bg-6490eb0a.js        55 B / gzipped: 75 B
messagebundle_ca-ee9b3967.js        55 B / gzipped: 75 B
```

chore: imrpove bundle size reporting

---

docs/Configuration.md
packages/base/src/InitialConfiguration.js
packages/base/src/asset-registries/i18n.js
packages/base/src/config/Language.js
packages/main/bundle.esm.js
packages/main/test/pages/i18n-defaultLang.html
packages/main/test/specs/DatePicker.spec.js
packages/main/test/specs/MultiComboBox.spec.js
packages/main/test/specs/MultiInput.spec.js
packages/tools/components-package/nps.js

Importing any component transitively imports the necessary default texts as an inlined JavaScript object (so that a prototyping workflow looks and works good even when assets are not configured productively).
Until now, the default behaviour was to fetch even the default language from the network, and use a configuration option to switch to inlined texts as an optimisation.
As this is more of an edge case and most developers would want the inlined texts, the default behaviour is changed to always use the inlined language (even when assets are configured).
If the network asset for the default language is preferred, the new configuration option `fetchDefaultLanguage` should be set to `true`

refactor: prefer usage of inlined language

---

packages/main/src/CheckBox.hbs

Input element now has aria-hidden="true" instead of role="none", to not be mapped to the accessibility tree.
Fixes: #2786

fix(ui5-checkbox): set aria-hidden attribute

---

packages/main/src/ResponsivePopover.hbs
packages/main/src/ResponsivePopover.js
packages/main/src/i18n/messagebundle.properties
packages/main/src/themes/ResponsivePopover.css
packages/main/src/themes/ResponsivePopoverCommon.css
packages/main/test/pages/ResponsivePopover.html

- When the header-text attribute is not provided, the Dialog (on mobile)
does not render an empty title element
- header-text attribute results in a title with level H2
- Added aria-label to the "Close dialog" button
Fixes: #2787

fix(ui5-responsive-popover): accessibility improvements

---

packages/main/src/themes/base/Button-parameters.css
packages/main/src/themes/sap_belize_hcb/Button-parameters.css
packages/main/src/themes/sap_belize_hcw/Button-parameters.css
packages/main/src/themes/sap_fiori_3/Button-parameters.css
packages/main/src/themes/sap_fiori_3_dark/Button-parameters.css
packages/main/src/themes/sap_fiori_3_hcb/Button-parameters.css
packages/main/src/themes/sap_fiori_3_hcw/Button-parameters.css

There is a standard CSS variable --sapButton_BorderCornerRadius meant to be used for the Button's border-radius
It is 0.25rem in Fiori3 and 0.375rem in HCB and HCW themes. In terms of metrics nothing changes, we use the same values, but now  we allow customization via the ThemeDesigner as we apply standard CSS variable.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2830

fix(ui5-button): use base CSS param for border-radius

---

packages/base/src/Device.js
packages/base/src/delegate/ScrollEnablement.js

This change reduces the size of the `ui5-checkbox`-only bundle from:
`113.24 KB / gzipped: 28.18 KB`
to
`109.65 KB / gzipped: 26.84 KB`
`Device.js` is one of the bigger files in the `@ui5/webcomponents-base` package. Most of the functions it exports trigger evaluations of the current device's OS (and its version), Browser (and its version) and other capabilities. The structure of the file allows for almost no tree-shaking. Even if one function is imported, this requires 90% of the code to be executed.
In reality, very little of all the information, gathered by `Device.js` is needed.
In general, application/component code should only detect the browser as a last resort (usually to work around bugs). Instead, the required feature should be detected instead.
Currently, of all functions, …

refactor(framework): Simplify Device.js

---

packages/main/src/types/CalendarSelectionMode.js
packages/main/src/types/CarouselArrowsPlacement.js
packages/main/src/types/InputType.js
packages/main/src/types/PopoverPlacementType.js

Changes:
- `CalendarSelectionMode` was not documented and not parsed by JSDoc at all
- `CarouselArrowsPlacement` and `PopoverPlacementType` had wrong values
- `InputTypes` has strange descriptions

chore: fix JSDoc for several types

---

packages/base/src/Keys.js
packages/main/bundle.esm.js
packages/main/src/Input.hbs
packages/main/src/Input.js
packages/main/src/StepInput.hbs
packages/main/src/StepInput.js
packages/main/src/i18n/messagebundle.properties
packages/main/src/themes/Input.css
packages/main/src/themes/StepInput.css
packages/main/test/pages/FormSupport.html
packages/main/test/pages/StepInput.html
packages/main/test/samples/StepInput.sample.html
packages/main/test/specs/FormSupport.spec.js
packages/main/test/specs/StepInput.spec.js

feat(ui5-step-input): inintial implementation

---

packages/main/src/Option.js
packages/main/src/TabContainer.js
packages/main/src/TableColumn.js
packages/main/src/TextArea.js

Fixes:
- `Option.js`: the type of `stableDomRef` is not documented
- Several components: use `Integer` instead of `Number` or `number`.

chore: fix several property types

---

packages/fiori/src/ShellBarItem.js
packages/fiori/src/SideNavigation.js
packages/main/src/ColorPaletteItem.js
packages/main/src/MultiComboBoxItem.js
packages/main/src/Tab.js
packages/main/src/Table.js

Some public properties or slots did not have a `@type` annotation

chore: add @type to all public entities

---

packages/main/src/Icon.js
packages/main/test/pages/Icon.html
packages/main/test/specs/Icon.spec.js

We used to fire a custom event, but did not stop the native one and end up with firing two "click" events.
Now, the native one is stopped properly (we need to fire the custom one, so the noConflict ui5-click is also fired). Also, one additional fix has been performed - the content no longer scrolls when the SPACE key is pressed over "interactive" icon.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2857

fix(ui5-icon): fix click event fired twice

---

packages/fiori/src/SideNavigation.js
packages/fiori/src/Wizard.js
packages/main/src/Input.js

Changes:
- some minor JSDoc fixes
- `Wizard.js`: the private `width` property renamed to `_width` so that `width` is free for the OpenUI5 wrapper and consistent with the rest of the controls.

chore: minor JSDoc fixes

---

packages/main/src/MultiComboBox.js
packages/main/test/pages/MultiComboBox.html
packages/main/test/specs/MultiComboBox.spec.js

- The focus of the MultiComboBox used to be lost when opened via icon, because we were moving the focus to the input after the ResponsivePopover has handled it's restoreFocus logic and the target of the focus restoration was the icon instead of the Input. This is not the case anymore, since we are forcing the focus inside the input, before we are toggling the ResponsivePopover.
FIXES: #2535 
FIXES: #2473

fix(ui5-multi-combobox): correct focus handling when picker is opened

---

packages/base/src/DOMObserver.js
packages/ie11/src/integrate.js

Prior to this change, if you use a bundle with the IE11 support in modern browsers, an error would be thrown

fix(framework): adaprt ie11 package for usage in modern browsers

---

packages/tools/lib/generate-json-imports/i18n.js

Locale id `in` matches a JS keyword and cannot be used in import identifier.
This change prefixes all import variables like `_in` so they never overlap language keywords.

fix: ensure locales don't use reserved JS names

---

packages/fiori/src/themes/Wizard.css

We introduced a small degradation with the following [PR](https://github.com/SAP/ui5-webcomponents/pull/2590), using a fixed colors, instead of CSS vars. Now, the Wizard navigation looks fine in all themes:
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2877
Before
After

fix(ui5-wizard): use CSS vars for navigation bg-color

---

packages/main/src/Input.js
packages/main/src/StepInput.hbs
packages/main/src/StepInput.js
packages/main/test/pages/Input.html

The 'submit' event fired from the `ui5-input` component is now removed as it is an event of the 'form' element and not of the input ones. From now on, the submit (event) must be triggered manually when enter key is pressed.
BREAKING CHANGE: the 'submit' event is now removed. The 'submit' functionality must be added with a custom code -  listen for the standard "keydown" event and check if ENTER is pressed to submit a form containing the input component.

fix(ui5-input): remove the 'submit' event

---

packages/fiori/src/Page.js
packages/fiori/src/themes/Page.css
packages/fiori/src/types/PageBackgroundDesign.js
packages/fiori/test/pages/Page.html
packages/fiori/test/samples/Page.sample.html

The styles used to rely on the property name **backgroundDesign**, which is not correct as in the DOM we use the attribute name **background-design**.
In addition,  the **"Standard"** background design is removed, because it's the same as **"Solid"**.
As a result **the background Design default value is changed from "Standard" to "Solid"**.

fix(ui5-page): correct background-design styles

---

packages/fiori/src/Wizard.js
packages/fiori/test/specs/Wizard.spec.js

On re-rendering the Wizard auto scrolls to the currently selected item's top, which is useful when the step selection is changed programatically. But, when re-rendering occurs for some other reason and the step selection remains the same, the Wizard still scrolls to the top of the selected step, which is not expected. Now, this is fixed by checking if the selection has been changed.
Fixes: https://github.com/SAP/ui5-webcomponents/issues/2883

    fix(ui5-wizard): prevent scrolling to step's very top

---

packages/main/src/Button.js
packages/main/test/pages/Button.html
packages/main/test/specs/Button.spec.js

Issue: When a ui5-button is created with blank text inside the component, for example
`<ui5-button icon="message-information"> </ui5-button>`, the attribute "icon-only" isn't set correctly. 
Solution: Trim the node value when node is type of "TEXT_NODE" and check the length of the trimmed value.
FIXES: #2567

fix(ui5-button): set icon-only attribute (#2567)

---

packages/tools/lib/generate-json-imports/themes.js

Before this change only optional themes were registered with the assumption that each component would register the default theme as part of its CSS.
There are edge-case scenarios where this is not the case. Therefore all themes are now registered. This allows the default theme to be fetched, if necessary, without incurring extra network activity in the usual use-case.

chore(framework): Register all themes

---

packages/main/src/CheckBox.js
packages/main/src/DatePicker.js
packages/main/src/FileUploader.js
packages/main/src/RadioButton.js
packages/main/src/Select.js
packages/main/src/StepInput.js
packages/main/src/TextArea.js

When some of the components such as FileUploader, Checkbox, Select are used with "name" attribute and FormSupport is enabled, the insertion of the native input with slot="formSupport" throws t warnings as the slot is unknown to component's metadata. 
Minor fix: when the Select has no options, the code that tries to get the value from the selected option used to fail.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2902

docs: describe formSupport slot

---

packages/tools/components-package/nps.js

The `package.json` and `src/` directory of the `webcomponentjs` polyfill are not necessary for the runtime, but may confuse some build tools.
Before:
After:

chore: do not distribute the webcomponentsjs polyfill's src dir

---

packages/main/src/DateRangePicker.js
packages/main/test/pages/DateRangePicker.html
packages/main/test/specs/DateRangePicker.spec.js
packages/theme-base/css-vars-usage.json

fixes: https://github.com/SAP/ui5-webcomponents/issues/2851

fix(ui5-daterange-picker): working with format pattern containing the delimiter

---

packages/main/src/CalendarHeader.js

The CalendarHeader is not language aware, because unlike the Calendar, DatePicker and the rest Date* components, the CalendarHeader is not derived by DateComponentBase class (which is language aware) and thus never re-renders on language change, triggered by the setLanguage API - the week days get translated, but the month text in the CalendarHeader - not.
Before
https://user-images.githubusercontent.com/15702139/110925172-88fc4a80-832b-11eb-9072-891f0dad05bf.mov
After
https://user-images.githubusercontent.com/15702139/110925305-b1844480-832b-11eb-9011-f25c6d783964.mov

fix(ui5-calendar): re-render header on lang change

---

packages/main/src/Button.js
packages/main/src/themes/Button.css

Added new nonInteractive private property which removes hover, active states and it can't be accessed thought Tab key and mouse.

chore(ui5-button): new nonInteractive property

---

packages/main/src/Popover.js
packages/main/test/pages/Popover.html

When the Popover is aligned horizontally against the opener,
but it is wider than the opener, the arrows will be centered to the middle of the opener element.
Fixes: #2758
Fixes: #2401

fix(ui5-popup): position arrows correctly

---

packages/base/src/StaticAreaItem.js

Some test pages such as `kitchen.html` have the following CSS:
```html
<style>
*:not(:defined) {
visibility: hidden;
}
</style>
```
This makes the `ui5-static-area` tag invisible. The solution is to define `ui5-static-area` as we do it for `ui5-static-area-item`. It used to be so, but this was removed in a recent update to static area functionality.

chore: Define ui5-static-area

---

packages/main/src/ColorPalette.js
packages/main/src/Select.js
packages/main/src/themes/AvatarGroup.css
packages/main/src/themes/ColorPaletteStaticArea.css
packages/main/src/themes/ColorPicker.css
packages/main/src/themes/Token.css

Only use selectors that would not break the scoping feature.
Please see: https://github.com/SAP/ui5-webcomponents/pull/2091
Additionally, fixed a missing `)` for a `Select.js` selector: `"ui5-li[focused]:not([selected]"`

chore: use scoping-friendly selectors

---

packages/main/src/themes/SliderBase.css
packages/main/src/themes/base/SliderBase-parameters.css
packages/main/src/themes/base/sizes-parameters.css

The focus outline was not fully visible among different browsers and mobile devices.

fix(ui5-slider): focus outline fully visible

---

packages/base/hash.txt
packages/base/src/features/OpenUI5Support.js
packages/base/src/util/PopupUtils.js
packages/main/src/Popover.js
packages/main/src/Popup.js
packages/main/src/ResponsivePopover.js
packages/main/src/Toast.js
packages/main/src/popup-utils/PopoverRegistry.js
packages/main/src/popup-utils/PopupUtils.js

A new Shared Resources entity was introduced: `PopupUtilsData`. You can test this in your browser as follows:
```js
document.head.querySelector("ui5-shared-resources").PopupUtilsData.currentZIndex
```
Thus all UI5 Web Components runtimes will use the same `currentZIndex` value, stored on the global `ui5-shared-resources` tag in the `head`.
Whenever the `OpenUI5Support` feature is imported by an application:
```js
import "@ui5/webcomponents-base/dist/features/OpenUI5Support.js";
```
the OpenUI5 popup registry will be used as a source of truth for each popup, opened by UI5 Web Components. This would allow UI5 Web Components popups to stack correctly with OpenUI5 popups.
There are 2 possible scenarios regarding which framework is loaded first:
- `OpenUI5` is loaded first: when this is the …

feat(framework): Maintain a common z-index for all UI5 Web Components instances and OpenUI5

---

packages/base/src/util/clamp.js
packages/main/src/Dialog.js
packages/main/src/Popover.js
packages/main/test/pages/Popover.html

The popover has a 10px offset from the edges of the screen,
so that its size would not reach the border of the page.
Left and Top positons are now clamped to adjust for that offset on all sides.
Fixes: #2697

fix(ui5-popover): calculate offset for all sides of the page

---

packages/main/src/Avatar.js
packages/main/src/AvatarGroup.hbs
packages/main/src/AvatarGroup.js
packages/main/test/pages/Avatar.html
packages/main/test/specs/Avatar.spec.js

We used to fire a custom event, but did not stop the native one and end up firing two "click" events.
Now, the native one is stopped properly (we need to fire the custom one, so the noConflict ui5-click is also fired). 
Also additional fixes have been performed:
- the content no longer scrolls when the SPACE key is pressed over "interactive" avatar.
- AvatarGroup now checks the target of the click event in order to detect whether an avatar or the overflow button is clicked.
FIXES: #2943

fix(ui5-avatar): fix click event fired twice

---

packages/main/src/Select.js
packages/main/test/specs/Select.spec.js

We used to return undefined for aria-expanded upon initial rendering, causing the attribute to not render at all, now we always return boolean and the attribute is added with "false" on initial rendering.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2987

fix(ui5-select): set aria-expanded initially

---

packages/main/test/specs/MultiComboBox.spec.js

This change should be reverted whenever the following issue is handled https://github.com/SAP/ui5-webcomponents/issues/2998

chore(ui5-multi-combobox): temporarily comment out failing test

---

packages/base/hash.txt

A change to the `@ui5/webcomponents-base` package was merged without recalculating the hash for this package: https://github.com/SAP/ui5-webcomponents/pull/2916/files
If any of the following packages is changed:
- `@ui5/webcomponents-base`
- `@ui5/webcomponents-localization`
- `@ui5/webcomponents-theme-base`
- `@ui5/webcomponents-icons`
- `@ui5/webcomponents-icons-tnt`
- `@ui5/webcomponents-ie11`
, please run `yarn hash` afterwards in order to generate the new hash. For more info, see: https://github.com/SAP/ui5-webcomponents/pull/2933

chore: fix the hash for the base package

---

packages/main/src/themes/base/SliderBase-parameters.css

Range Slider's handles' background is now fixed to be consistent across all browsers, as previously their opacity was not correct in IE11.

fix(ui5-rangeslider): fix handles opacity for IE11

---

packages/fiori/src/Wizard.js
packages/fiori/test/pages/Wizard_test.html

**Background**
There are complains that if the user is at the very beginning of a step and scrolls a bit upwards, the selection switches to the previous step, although most of the viewport is taken by the first one.
This has been raised with https://github.com/SAP/ui5-webcomponents/issues/2883:
"5. scroll up a little bit of the cascading goal dialog, and you can see the fact that although the most of dialog is step two, but the wizard will highlight the step one button. this is an issue, because the current step is still step two"
**Solution**
Add private/protected API, called step-switch-threshold
to give more control of the point the switch happens.
It support float values between 0.5 and 1, where 0.5 means the step will be switched after the user scrolls half of the current step, and 1 …

refactor(ui5-wizard): configure step change threshold

---

packages/fiori/src/SideNavigationItem.js
packages/fiori/src/SideNavigationSubItem.js
packages/fiori/src/UploadCollection.js
packages/main/src/Button.js
packages/main/src/Link.js
packages/tools/lib/jsdoc/plugin.js
packages/tools/lib/jsdoc/template/publish.js

Most `event`s described in `metadata` are instances of `CustomEvent`, but some are native browser events. They are however described in the events metadata to give developers extra information.
It is however important to know which events are native and which are custom for several reasons:
- native events are not fired by the framework, therefore they don't have a `ui5-` version. In practice this means that when they are bound in `.hbs` files, they are without the `ui5-` prefix. 
- for the purpose of documentation
These events get a new `native` field in `API.json` :
```
"events": [
{
"name": "click",
"native": "true",
"visibility": "public",
"description": "Fired when the <code>ui5-button</code> is activated either with a mouse/tap or by using the Enter or Space key. <br><br> …
```

docs: document native metadata events

---

packages/main/src/themes/Icon.css

The vertical flip fix in #2645 also removeд the horizontal mirroring. This returns the normal RTL mirroring.
Fixes: #3029

fix(ui5-icon): RTL mirroring

---

README.md
docs/dev/Testing Web Components.md

Getting the tests to run on Windows locally is quite complicated.
- Windows build tools 2015 is required
- Python 2.7 is required
- node-gyp is required
These must be installed and configured manually for `yarn test` to run successfully.

docs: Explain how to make the tests run on Windows

---

packages/main/src/themes/TreeListItem.css

While the TreeListItem is in its _minimal state (with no visible
text), the text was still taking space, causing incorrect alignment
of the icons. Now the text is not rendered when we are in _minimal state
which results in proper alignment of the icons.

fix(ui5-li-tree): fixed incorrect display of the text

---

packages/main/src/AvatarGroup.hbs
packages/main/src/AvatarGroup.js
packages/main/src/themes/AvatarGroup.css
packages/main/test/pages/AvatarGroup.html

Added new slot which allows to add custom overflow button and "overflow" event to let you know when avatars 
hide/show in order to update the overflow button text. If not provided, the AvatarGroup will display the built-in overflow button. The slot is provided to allow you defining the text of the overflow button  and let you set additional aria attributes, such as aria-label.  
```html
<ui5-avatar-group>
<ui5-button slot="overflowButton"  aria-label="your text">+99</ui5-button>
</ui5-avatar-group>
```
Fixes: #2912

feat(ui5-avatar-group): new slot overflowButton

---

packages/fiori/src/Wizard.js
packages/fiori/test/pages/Wizard_test.html
packages/fiori/test/specs/Wizard.spec.js

**Backgorund**
For certain cases, it is useful to provide info if the selection-change is fired due to user's click on a step within the step navigation (as the selection might also occur due to scrolling). For that, we are introducing a new event parameter, called **changeWithClick**. 
The parameter would be **true**, whenever the event is due to user click on a step within the step navigation header, and **false** when fired due to user scrolling
**Usage**
```js
wiz.addEventListener("selection-change", function (event) {
console.log(event.detail.changeWithClick);
});
```

feat(ui5-wizard): add parameter to selectionChange event

---

packages/main/src/Input.js
packages/main/test/specs/Input.spec.js

When a ui5-input with suggestions is positioned within a dialog a popover, closing the suggestions popover does not close the outer dialog/popover.
FIXES: #3028

fix(ui5-input): Prevent dialog closing on Escape

---

packages/fiori/src/Page.js
packages/fiori/src/Wizard.js

Changes:
- `Page.js` doesn't need a message bundle
- `Wizard.js` is loading the `main` bundle, but its texts are in the `fiori` bundle. Probably it was never translated.

chore: fix bundle problems for fiori

---

packages/main/test/specs/MultiComboBox.spec.js

Although some parts of the `aria-describedby value according to the tokens count` test were commented out, it still fails consistenly. Now the whole test is removed.
This will be addressed in the already existing issue: https://github.com/SAP/ui5-webcomponents/issues/2998

chore: disable the whole unstable test

---

packages/fiori/src/UploadCollectionItem.js

Fixes #3054
When a component from ```fiori``` package extends a component from the ```main``` package, the i18n bundle should not be overwritten. Both main & fiori bundles should be available

fix(ui5-upload-collection-item): make use of both main & fiori i18n bundles

---

packages/fiori/src/NotificationListGroupItem.js
packages/fiori/src/NotificationListItem.js
packages/fiori/src/NotificationListItemBase.js

This issue comes is the same as #3061
When a component from ```fiori``` package extends a component from the ```main``` package, the i18n bundle should not be overwritten. Both main & fiori bundles should be available

fix(ui5-li-notification-group, ui5-li-notification): fix i18n bundles usage

---

packages/main/src/Button.js
packages/main/src/ListItem.js

Fixes: #2995
There is one non ```passive``` event handler left in the code. It is in the ```SliderBase.hbs``` file. It is left because the behaviour of the slider depends on preventing the native event.

refactor(ui5-button, ui5-li): make touch events handlers passive

---

packages/main/src/themes/TreeListItem.css

When there was ellipsis of the text of the tree items, the ones
which got truncated were misaligned with the ones which weren't.
Now they are correctly aligned.
Fixes: #3069

fix(ui5-li-tree): fixed incorrect tree items alignment

---

packages/main/src/Input.js

Prevously, after padding: 0 was applied when the condition is false, it remained 0. That could be easily reproduced with native HTML as well. Setting 'undefined' as a value does not change the padding to the one specified in the component's css styles.
https://snippix.only.sap/snippets/52143
Now, when the padding should not be 0, the inline style is removed, instead of setting 'undefined' as a value
FIXES: #2940

fix(ui5-input): inner input padding is correctly updated

---

packages/base/hash.txt
packages/base/src/StaticAreaItem.js
packages/base/src/UI5Element.js
packages/fiori/src/Wizard.js
packages/fiori/src/themes/WizardTab.css
packages/ie11/hash.txt
packages/ie11/src/theming/createComponentStyleTag.js

Background: when new and old versions of UI5 Web Components are mixed on the same page and the old version has already upgraded the `ui5-static-area-item` tag, it will not have some of the newer functions. Therefore it should be scoped along with the other tags.
Changes:
- `StaticAreaItems.js` can now be scoped
- `UI5Element.js` delegates the creation of new static area items to `StaticAreaItem.js`
- The IE11 CSS script is now aware of the static area item scoping
Note:
- The `ui5-static-area-item` tag is defined lazily now, so that the app has had the chance to set the scoping suffix
Additionally:
- `ui5-wizard` and `ui5-wizard-step` have been made scoping-friendly

feat(ui5-static-area-item): StaticAreaItem can now be scoped

---

packages/main/src/themes/TreeListItem.css

The background of the selected items on level 2 and higher was wrong.
Now it's aligned with specification.
Fixes: #2978

fix(ui5-li-tree): fixed incorrect background of selected item

---

packages/fiori/src/themes/InvisibleTextStyles.css
packages/fiori/test/pages/Wizard_test.html
packages/fiori/test/specs/Wizard.spec.js
packages/main/src/themes/InvisibleTextStyles.css

Add negative coordinates to the a11y invisible texts to ensure they remain out of the view port. Already this is the case in most of the browsers, but on IE they can be still observed. The negative coordinates do not affect the a11y and do not prevent Screen Readers from announcing the texts.
FIXES: https://github.com/SAP/ui5-webcomponents/issues/2723
CLOSES: https://github.com/SAP/ui5-webcomponents/issues/2723

fix: keep invisible texts out of the view port

---

packages/base/hash.txt
packages/base/src/UI5Element.js
packages/base/src/util/getClassCopy.js
packages/main/test/pages/TimePicker.html

The `getClassCopy` util, used for registering the `altTag` (old tag) for some components, gets a new callback parameter that executes in the constructor.
The following warning is shown: "The ui5-timepicker tag is deprecated and will be removed in the next release, please use ui5-time-picker instead."

chore: show a deprecation warning for old tags

---

packages/fiori/src/Wizard.js

This is a follow up of a review comment from https://github.com/SAP/ui5-webcomponents/pull/3009
to make us of an existing method instead of local implementation.

chore(ui5-wizard): make use of base util mehtod

---

packages/main/src/DayPicker.js
packages/main/src/themes/DayPicker.css

Fixes: https://github.com/SAP/ui5-webcomponents/issues/3059
As the weekday names and the weeks themselves are build in different blocks and arrays, when removing the week numbers( not presenting them) we don't remove the 'filler' block which we insert in the header row where the names are. Now we remove the first block, if the property for hiding weeks is set to true, and then we place the DayPicker content block in the center.

fix(ui5-date-picker): calibrate the width and alignment of day names
